part of 'dashboard_preferences_page.dart';

final _dashboardPresets =
    <
      ({
        String id,
        IconData icon,
        String titleEn,
        String titleAr,
        String titleFr,
        String titleEs,
        String titleTr,
        String bodyEn,
        String bodyAr,
        String bodyFr,
        String bodyEs,
        String bodyTr,
        Set<String> sections,
        bool premium,
      })
    >[
      (
        id: 'calorie',
        icon: Icons.local_fire_department_outlined,
        titleEn: 'Calorie focused',
        titleAr: 'تركيز السعرات',
        titleFr: 'Centré sur les calories',
        titleEs: 'Enfoque en calorías',
        titleTr: 'Kalori odaklı',
        bodyEn: 'Calories consumed, activity, and remaining energy.',
        bodyAr: 'السعرات المستهلكة والنشاط والطاقة المتبقية.',
        bodyFr: 'Calories consommées, activité et énergie restante.',
        bodyEs: 'Calorías consumidas, actividad y energía restante.',
        bodyTr: 'Tüketilen kalori, aktivite ve kalan enerji.',
        sections: {
          DashboardSectionIds.calories,
          DashboardSectionIds.activity,
          DashboardSectionIds.quickLog,
          DashboardSectionIds.aiCoach,
          DashboardSectionIds.discover,
        },
        premium: false,
      ),
      (
        id: 'macros',
        icon: Icons.donut_large_rounded,
        titleEn: 'Macronutrients focused',
        titleAr: 'تركيز المغذيات الكبرى',
        titleFr: 'Centré sur les macronutriments',
        titleEs: 'Enfoque en macronutrientes',
        titleTr: 'Makro besin odaklı',
        bodyEn: 'Carbs, protein, fat, and remaining calories.',
        bodyAr: 'الكربوهيدرات والبروتين والدهون والسعرات المتبقية.',
        bodyFr: 'Glucides, protéines, lipides et calories restantes.',
        bodyEs: 'Carbohidratos, proteína, grasa y calorías restantes.',
        bodyTr: 'Karbonhidrat, protein, yağ ve kalan kalori.',
        sections: {
          DashboardSectionIds.calories,
          DashboardSectionIds.macros,
          DashboardSectionIds.quickLog,
          DashboardSectionIds.aiCoach,
          DashboardSectionIds.discover,
        },
        premium: true,
      ),
      (
        id: 'heart',
        icon: Icons.monitor_heart_outlined,
        titleEn: 'Heart and activity view',
        titleAr: 'عرض القلب والنشاط',
        titleFr: 'Vue cœur et activité',
        titleEs: 'Vista de corazón y actividad',
        titleTr: 'Kalp ve aktivite görünümü',
        bodyEn: 'Nutrition, activity, and connected health together.',
        bodyAr: 'التغذية والنشاط والصحة المتصلة في عرض واحد.',
        bodyFr: 'Nutrition, activité et santé connectée réunies.',
        bodyEs: 'Nutrición, actividad y salud conectada juntas.',
        bodyTr: 'Beslenme, aktivite ve bağlı sağlık bir arada.',
        sections: {
          DashboardSectionIds.calories,
          DashboardSectionIds.macros,
          DashboardSectionIds.activity,
          DashboardSectionIds.connectedHealth,
          DashboardSectionIds.progress,
          DashboardSectionIds.aiCoach,
        },
        premium: true,
      ),
      (
        id: 'low_carb',
        icon: Icons.eco_outlined,
        titleEn: 'Low carb',
        titleAr: 'كربوهيدرات منخفضة',
        titleFr: 'Faible en glucides',
        titleEs: 'Bajo en carbohidratos',
        titleTr: 'Düşük karbonhidrat',
        bodyEn: 'Macros, calories, quick logging, and evidence.',
        bodyAr: 'المغذيات والسعرات والتسجيل السريع والأدلة.',
        bodyFr: 'Macros, calories, saisie rapide et preuves.',
        bodyEs: 'Macros, calorías, registro rápido y evidencia.',
        bodyTr: 'Makrolar, kalori, hızlı kayıt ve kanıt.',
        sections: {
          DashboardSectionIds.calories,
          DashboardSectionIds.macros,
          DashboardSectionIds.quickLog,
          DashboardSectionIds.aiCoach,
        },
        premium: true,
      ),
    ];

final _dashboardPreferenceItems =
    <(String, IconData, String, String, String, String)>[
      (
        DashboardSectionIds.aiCoach,
        Icons.auto_awesome_rounded,
        'AI Coach',
        'مدرب BIL الذكي',
        'A private conversation with your health intelligence',
        'محادثة خاصة مع ذكائك الصحي الشخصي',
      ),
      (
        DashboardSectionIds.calories,
        Icons.local_fire_department_outlined,
        'Calories',
        'السعرات',
        'Goal, food, exercise, and remaining energy',
        'الهدف والطعام والتمرين والطاقة المتبقية',
      ),
      (
        DashboardSectionIds.macros,
        Icons.donut_large_rounded,
        'Macros',
        'العناصر الكبرى',
        'Macro and nutrient trends',
        'اتجاهات المغذيات الكبرى والعناصر الغذائية',
      ),
      (
        DashboardSectionIds.activity,
        Icons.directions_walk_rounded,
        'Activity',
        'النشاط',
        'Measured trends from your saved records',
        'اتجاهات مقاسة من سجلاتك المحفوظة',
      ),
      (
        DashboardSectionIds.quickLog,
        Icons.add_circle_outline_rounded,
        'Quick log',
        'التسجيل السريع',
        'Food, water, and weight shortcuts',
        'اختصارات الطعام والماء والوزن',
      ),
      (
        DashboardSectionIds.discover,
        Icons.explore_outlined,
        'Discover',
        'اكتشف',
        'Sleep, recipes, workouts, and community',
        'النوم والوصفات والتمارين والمجتمع',
      ),
      (
        DashboardSectionIds.bestAction,
        Icons.auto_awesome_outlined,
        'Personal intelligence',
        'الذكاء الشخصي',
        'One Best Action, evidence, and Body Twin',
        'أفضل إجراء والأدلة والتوأم الجسدي',
      ),
      (
        DashboardSectionIds.progress,
        Icons.show_chart_rounded,
        'Progress',
        'التقدم',
        'Measured trends from your saved records',
        'الاتجاهات المقاسة من سجلاتك المحفوظة',
      ),
      (
        DashboardSectionIds.connectedHealth,
        Icons.health_and_safety_outlined,
        'Connected health',
        'الصحة المتصلة',
        'Health sources and synchronization status',
        'مصادر الصحة وحالة المزامنة',
      ),
      (
        DashboardSectionIds.bodyTwin,
        Icons.accessibility_new_rounded,
        'Body Twin',
        'التوأم الجسدي',
        'Your explainable body model and its evidence',
        'نموذج جسمك القابل للتفسير وأدلته',
      ),
    ];
