from pathlib import Path
import json,re
# Explicit localized purpose text for the confirmed Community voice entry point.
texts={
'de':('BIL nutzt das Mikrofon nur, wenn Sie Spracheingabe für Gewicht, Mahlzeiten, Community-Beiträge oder BIL AI Coach wählen. Sie können den Text vor dem Speichern, Veröffentlichen oder Senden prüfen.','BIL wandelt von Ihnen gestartete Sprache für Gewicht, Mahlzeiten, Community-Beiträge oder BIL AI Coach in Text um. Sie können ihn vor dem Speichern, Veröffentlichen oder Senden prüfen.'),
'es':('BIL usa el micrófono solo cuando eliges la entrada de voz para el peso, comidas, publicaciones de la comunidad o BIL AI Coach. Puedes revisar el texto antes de guardarlo, publicarlo o enviarlo.','BIL convierte en texto el habla que inicias para el peso, comidas, publicaciones de la comunidad o BIL AI Coach. Puedes revisarlo antes de guardarlo, publicarlo o enviarlo.'),
'fr':('BIL utilise le microphone uniquement lorsque vous choisissez la saisie vocale pour le poids, les repas, les publications de la communauté ou BIL AI Coach. Vous pouvez vérifier le texte avant de l’enregistrer, de le publier ou de l’envoyer.','BIL convertit en texte la parole que vous lancez pour le poids, les repas, les publications de la communauté ou BIL AI Coach. Vous pouvez vérifier le texte avant de l’enregistrer, de le publier ou de l’envoyer.'),
'it':('BIL usa il microfono solo quando scegli la voce per peso, pasti, post della community o BIL AI Coach. Puoi rivedere il testo prima di salvarlo, pubblicarlo o inviarlo.','BIL converte in testo la voce che avvii per peso, pasti, post della community o BIL AI Coach. Puoi rivederlo prima di salvarlo, pubblicarlo o inviarlo.'),
'pt-BR':('BIL usa o microfone apenas quando você escolhe a entrada de voz para peso, refeições, publicações da comunidade ou BIL AI Coach. Você pode revisar o texto antes de salvar, publicar ou enviar.','BIL converte em texto a fala que você inicia para peso, refeições, publicações da comunidade ou BIL AI Coach. Você pode revisar o texto antes de salvar, publicar ou enviar.'),
'pt-PT':('BIL utiliza o microfone apenas quando escolhe a entrada de voz para peso, refeições, publicações da comunidade ou BIL AI Coach. Pode rever o texto antes de guardar, publicar ou enviar.','BIL converte em texto a fala que inicia para peso, refeições, publicações da comunidade ou BIL AI Coach. Pode rever o texto antes de guardar, publicar ou enviar.'),
'tr':('BIL mikrofonu yalnızca kilo, öğün, topluluk gönderileri veya BIL AI Coach için sesli girişi seçtiğinizde kullanır. Metni kaydetmeden, yayımlamadan veya göndermeden önce inceleyebilirsiniz.','BIL, kilo, öğün, topluluk gönderileri veya BIL AI Coach için başlattığınız konuşmayı metne dönüştürür. Metni kaydetmeden, yayımlamadan veya göndermeden önce inceleyebilirsiniz.'),
'nl':('BIL gebruikt de microfoon alleen wanneer je spraakinvoer kiest voor gewicht, maaltijden, communityberichten of BIL AI Coach. Je kunt de tekst controleren voordat je deze opslaat, publiceert of verzendt.','BIL zet spraak die je start voor gewicht, maaltijden, communityberichten of BIL AI Coach om in tekst. Je kunt de tekst controleren voordat je deze opslaat, publiceert of verzendt.'),
'pl':('BIL używa mikrofonu tylko wtedy, gdy wybierzesz głosowe wprowadzanie masy ciała, posiłków, postów społeczności lub rozmowę z BIL AI Coach. Możesz sprawdzić tekst przed zapisaniem, opublikowaniem lub wysłaniem.','BIL zamienia mowę uruchomioną przez Ciebie dla masy ciała, posiłków, postów społeczności lub BIL AI Coach na tekst. Możesz go sprawdzić przed zapisaniem, opublikowaniem lub wysłaniem.'),
'ru':('BIL использует микрофон только когда вы выбираете голосовой ввод для веса, еды, публикаций сообщества или BIL AI Coach. Вы можете проверить текст перед сохранением, публикацией или отправкой.','BIL преобразует начатую вами речь для веса, еды, публикаций сообщества или BIL AI Coach в текст. Вы можете проверить его перед сохранением, публикацией или отправкой.'),
'uk':('BIL використовує мікрофон лише коли ви вибираєте голосове введення для ваги, їжі, дописів спільноти або BIL AI Coach. Ви можете перевірити текст перед збереженням, публікацією або надсиланням.','BIL перетворює розпочате вами мовлення для ваги, їжі, дописів спільноти або BIL AI Coach на текст. Ви можете перевірити його перед збереженням, публікацією або надсиланням.'),
'id':('BIL menggunakan mikrofon hanya saat Anda memilih masukan suara untuk berat badan, makanan, postingan komunitas, atau BIL AI Coach. Anda dapat meninjau teks sebelum menyimpan, memposting, atau mengirimkannya.','BIL mengubah ucapan yang Anda mulai untuk berat badan, makanan, postingan komunitas, atau BIL AI Coach menjadi teks. Anda dapat meninjaunya sebelum menyimpan, memposting, atau mengirimkannya.'),
'ms':('BIL menggunakan mikrofon hanya apabila anda memilih input suara untuk berat, hidangan, siaran komuniti atau BIL AI Coach. Anda boleh menyemak teks sebelum menyimpan, menerbitkan atau menghantarnya.','BIL menukar pertuturan yang anda mulakan untuk berat, hidangan, siaran komuniti atau BIL AI Coach kepada teks. Anda boleh menyemaknya sebelum menyimpan, menerbitkan atau menghantarnya.'),
'vi':('BIL chỉ sử dụng micrô khi bạn chọn nhập bằng giọng nói cho cân nặng, bữa ăn, bài đăng cộng đồng hoặc BIL AI Coach. Bạn có thể xem lại văn bản trước khi lưu, đăng hoặc gửi.','BIL chuyển lời nói bạn bắt đầu cho cân nặng, bữa ăn, bài đăng cộng đồng hoặc BIL AI Coach thành văn bản. Bạn có thể xem lại trước khi lưu, đăng hoặc gửi.'),
'th':('BIL ใช้ไมโครโฟนเฉพาะเมื่อคุณเลือกป้อนข้อมูลด้วยเสียงสำหรับน้ำหนัก มื้ออาหาร โพสต์ในชุมชน หรือ BIL AI Coach คุณสามารถตรวจสอบข้อความก่อนบันทึก เผยแพร่ หรือส่งได้','BIL แปลงคำพูดที่คุณเริ่มสำหรับน้ำหนัก มื้ออาหาร โพสต์ในชุมชน หรือ BIL AI Coach เป็นข้อความ คุณสามารถตรวจสอบข้อความก่อนบันทึก เผยแพร่ หรือส่งได้'),
'ja':('BIL は、体重、食事、コミュニティ投稿、または BIL AI Coach の音声入力を選択した場合にのみマイクを使用します。保存、投稿、送信する前にテキストを確認できます。','BIL は、体重、食事、コミュニティ投稿、または BIL AI Coach のために開始した音声をテキストに変換します。保存、投稿、送信する前に確認できます。'),
'ko':('BIL은 체중, 식사, 커뮤니티 게시물 또는 BIL AI Coach에 음성 입력을 사용하도록 선택한 경우에만 마이크를 사용합니다. 저장, 게시 또는 전송하기 전에 텍스트를 검토할 수 있습니다.','BIL은 체중, 식사, 커뮤니티 게시물 또는 BIL AI Coach를 위해 시작한 음성을 텍스트로 변환합니다. 저장, 게시 또는 전송하기 전에 검토할 수 있습니다.'),
'zh-Hans':('BIL 仅在您选择为体重、餐食、社区帖子或 BIL AI Coach 使用语音输入时使用麦克风。您可以在保存、发布或发送前检查文本。','BIL 将您为体重、餐食、社区帖子或 BIL AI Coach 主动发起的语音转换为文本。您可以在保存、发布或发送前检查文本。'),
'zh-Hant':('BIL 僅在您選擇為體重、餐點、社群貼文或 BIL AI Coach 使用語音輸入時使用麥克風。您可以在儲存、發佈或傳送前檢查文字。','BIL 將您為體重、餐點、社群貼文或 BIL AI Coach 主動發起的語音轉換為文字。您可以在儲存、發佈或傳送前檢查文字。'),
'hi':('BIL माइक्रोफ़ोन का उपयोग केवल तब करता है जब आप वज़न, भोजन, समुदाय की पोस्ट या BIL AI Coach के लिए आवाज़ से इनपुट चुनते हैं। आप टेक्स्ट को सहेजने, पोस्ट करने या भेजने से पहले देख सकते हैं।','BIL वज़न, भोजन, समुदाय की पोस्ट या BIL AI Coach के लिए आपके द्वारा शुरू की गई आवाज़ को टेक्स्ट में बदलता है। आप उसे सहेजने, पोस्ट करने या भेजने से पहले देख सकते हैं।'),
'bn':('আপনি ওজন, খাবার, কমিউনিটি পোস্ট বা BIL AI Coach-এর জন্য ভয়েস ইনপুট বেছে নিলেই BIL মাইক্রোফোন ব্যবহার করে। সংরক্ষণ, প্রকাশ বা পাঠানোর আগে আপনি লেখাটি পর্যালোচনা করতে পারেন।','ওজন, খাবার, কমিউনিটি পোস্ট বা BIL AI Coach-এর জন্য আপনার শুরু করা কথাকে BIL লেখায় রূপান্তর করে। সংরক্ষণ, প্রকাশ বা পাঠানোর আগে আপনি তা পর্যালোচনা করতে পারেন।'),
'ur':('BIL مائیکروفون صرف اس وقت استعمال کرتا ہے جب آپ وزن، کھانے، کمیونٹی پوسٹ یا BIL AI Coach کے لیے صوتی ان پٹ منتخب کرتے ہیں۔ آپ متن کو محفوظ، شائع یا ارسال کرنے سے پہلے دیکھ سکتے ہیں۔','BIL وزن، کھانے، کمیونٹی پوسٹ یا BIL AI Coach کے لیے آپ کی شروع کردہ گفتگو کو متن میں بدلتا ہے۔ آپ اسے محفوظ، شائع یا ارسال کرنے سے پہلے دیکھ سکتے ہیں۔'),
'fa':('BIL فقط زمانی از میکروفون استفاده می‌کند که ورودی صوتی را برای وزن، غذا، پست‌های انجمن یا مربی هوشمند BIL انتخاب کنید. می‌توانید متن را پیش از ذخیره، انتشار یا ارسال بازبینی کنید.','BIL گفتاری را که برای وزن، غذا، پست‌های انجمن یا مربی هوشمند BIL آغاز می‌کنید به متن تبدیل می‌کند. می‌توانید آن را پیش از ذخیره، انتشار یا ارسال بازبینی کنید.'),
}
assert len(texts)==23
for locale,pair in texts.items():
 path=Path('ios/Runner')/(locale+'.lproj')/'InfoPlist.strings'
 source=path.read_text(); original=source
 for key,value in zip(('NSMicrophoneUsageDescription','NSSpeechRecognitionUsageDescription'),pair):
  pattern=r'^"'+key+r'"\s*=\s*".*";\s*$'
  replacement=json.dumps(key)+' = '+json.dumps(value,ensure_ascii=False)+';'
  source,n=re.subn(pattern,lambda _:replacement,source,flags=re.M)
  assert n==1,(locale,key,n)
 assert source!=original,locale
 path.write_text(source)
