"""Write a reviewable path/provenance inventory, not an automatic diff approval.

Reads text sources only. Existing owner media are listed without opening,
hashing or comparing image contents. The backup is never modified.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
from pathlib import Path
import subprocess

from audit_repository import TEXT
from run_gate import ROOT

OUTPUT = 'docs/qa/PREBUILD_CHANGED_FILES_2026-09-10.md'


def git(*args: str) -> list[str]:
    return subprocess.check_output(['git', *args], cwd=ROOT).decode('utf-8').split('\0')


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('backup', type=Path)
    args = parser.parse_args()
    with (args.backup / 'manifest.csv').open(encoding='utf-8-sig', newline='') as source:
        baseline = {row['Path']: row for row in csv.DictReader(source)}
    # Index entries include newly staged files. Classify against the commit,
    # so generating the report before/after staging produces the same result.
    tracked = set(git('ls-tree', '-r', '--name-only', '-z', 'HEAD')) - {''}
    changed = sorted(set(git('diff', 'HEAD', '--no-renames', '--name-only', '-z') +
                         git('ls-files', '--others', '--exclude-standard', '-z') + [OUTPUT]) - {''})
    lines = ['# Pre-build changed-file inventory — 2026-09-10', '',
             'Generated by `tool/prebuild/write_diff_inventory.py`.', '',
             'Provenance is compared with the verified pre-audit backup; it is not a test result.',
             'Owner text changed during audit is reviewed together with its original changes.',
             'Binary content is not inspected. Tests and runtime verification limits are in',
             '[the audit report](FINAL_PREBUILD_CODE_AUDIT_2026-09-10.md).', '',
             f'Candidate paths: {len(changed)} (Git may report a moved file as one rename).', '',
             '| Path | Change | Provenance |', '| --- | --- | --- |']
    for relative in changed:
        path = ROOT / relative
        if not path.resolve().is_relative_to(ROOT):
            raise ValueError('Out-of-scope Git path')
        original = baseline.get(relative)
        kind = 'modified' if relative in tracked else 'added'
        if relative == OUTPUT:
            provenance = 'Audit inventory (this file)'
        elif not path.is_file():
            kind = 'deleted/moved'
            provenance = 'Audit cleanup or resource relocation; reviewed in report'
        elif path.suffix.lower() not in TEXT and path.name != '.gitignore':
            if original is None:
                raise ValueError(f'Unreviewed new binary: {relative}')
            provenance = 'Existing owner binary; content NOT VERIFIED'
        elif original is None:
            provenance = 'Audit addition/change to baseline HEAD'
        else:
            digest = hashlib.sha256(path.read_bytes()).hexdigest().upper()
            provenance = ('Existing owner change preserved byte-for-byte' if digest == original['SHA256']
                          else 'Existing owner change plus audit correction/formatting')
        lines.append(f'| `{relative}` | {kind} | {provenance} |')
    (ROOT / OUTPUT).write_text('\n'.join(lines) + '\n', encoding='utf-8', newline='\n')
    print(f'{OUTPUT}: {len(changed)} candidate paths; binary content not read')


if __name__ == '__main__':
    main()
