/// Weight state is part of the calculation, not a translation of a food name.
abstract final class RecipeSourceCopy {
  static String state(String state, String locale) {
    final index = const [
      'raw',
      'cooked',
      'dry',
      'unbaked',
      'as-sold',
    ].indexOf(state);
    return (_copy[locale] ?? _copy['en']!)[index < 0 ? 4 : index];
  }

  static String weighingBasis(String locale) =>
      (_copy[locale] ?? _copy['en']!)[5];

  static const _copy = <String, List<String>>{
    'en': [
      'Raw',
      'Cooked',
      'Dry',
      'Unbaked',
      'As sold',
      'Weigh each ingredient in the state shown. The calculation uses these gram weights, not the weight after cooking.',
    ],
    'ar': [
      'نيئ',
      'مطهو',
      'جاف',
      'قبل الخَبز',
      'كما يباع',
      'زِن كل مكوّن بالحالة الموضحة. يعتمد الحساب على هذه الأوزان بالجرام، لا الوزن بعد طهي الوصفة.',
    ],
    'fr': [
      'Cru',
      'Cuit',
      'Sec',
      'Avant cuisson au four',
      'Tel que vendu',
      'Pesez chaque ingrédient dans l’état indiqué. Le calcul utilise ces poids en grammes, pas le poids final du plat.',
    ],
    'es': [
      'Crudo',
      'Cocido',
      'Seco',
      'Sin hornear',
      'Tal como se vende',
      'Pesa cada ingrediente en el estado indicado. El cálculo usa estos gramos, no el peso final del plato.',
    ],
    'tr': [
      'Çiğ',
      'Pişmiş',
      'Kuru',
      'Fırınlanmamış',
      'Satıldığı hâliyle',
      'Her malzemeyi belirtilen hâliyle tartın. Hesaplama yemeğin son ağırlığını değil, bu gramları kullanır.',
    ],
    'de': [
      'Roh',
      'Gegart',
      'Trocken',
      'Ungebacken',
      'Wie verkauft',
      'Wiege jede Zutat im angegebenen Zustand. Berechnet werden diese Grammangaben, nicht das Gewicht des fertigen Gerichts.',
    ],
    'it': [
      'Crudo',
      'Cotto',
      'Secco',
      'Non cotto al forno',
      'Come venduto',
      'Pesa ogni ingrediente nello stato indicato. Il calcolo usa questi grammi, non il peso finale del piatto.',
    ],
    'pt-BR': [
      'Cru',
      'Cozido',
      'Seco',
      'Antes de assar',
      'Como vendido',
      'Pese cada ingrediente no estado indicado. O cálculo usa estes gramas, não o peso final do prato.',
    ],
    'pt-PT': [
      'Cru',
      'Cozinhado',
      'Seco',
      'Antes de ir ao forno',
      'Tal como vendido',
      'Pese cada ingrediente no estado indicado. O cálculo usa estes gramas, não o peso final do prato.',
    ],
    'ur': [
      'کچا',
      'پکا ہوا',
      'خشک',
      'بیک کرنے سے پہلے',
      'فروخت کی حالت میں',
      'ہر جزو کو دکھائی گئی حالت میں تولیں۔ حساب ان گراموں پر مبنی ہے، تیار کھانے کے وزن پر نہیں۔',
    ],
    'fa': [
      'خام',
      'پخته',
      'خشک',
      'پیش از پخت در فر',
      'در حالت عرضه',
      'هر ماده را در حالت مشخص‌شده وزن کنید. محاسبه بر پایه این وزن‌هاست، نه وزن غذای نهایی.',
    ],
    'hi': [
      'कच्चा',
      'पका हुआ',
      'सूखा',
      'बेक करने से पहले',
      'जैसा बेचा जाता है',
      'हर सामग्री को बताई गई अवस्था में तौलें। गणना इन ग्रामों से होती है, तैयार व्यंजन के वजन से नहीं।',
    ],
    'id': [
      'Mentah',
      'Matang',
      'Kering',
      'Belum dipanggang',
      'Saat dijual',
      'Timbang setiap bahan dalam kondisi yang ditampilkan. Perhitungan memakai gram ini, bukan berat hidangan setelah dimasak.',
    ],
    'ms': [
      'Mentah',
      'Dimasak',
      'Kering',
      'Belum dibakar',
      'Seperti dijual',
      'Timbang setiap ramuan dalam keadaan yang ditunjukkan. Pengiraan menggunakan gram ini, bukan berat hidangan siap.',
    ],
    'ja': [
      '生',
      '調理済み',
      '乾燥',
      '焼く前',
      '販売時の状態',
      '各材料は表示された状態で量ってください。計算にはこのグラム数を使い、料理の完成後の重量は使いません。',
    ],
    'ko': [
      '생것',
      '조리됨',
      '건조',
      '굽기 전',
      '판매 상태',
      '각 재료를 표시된 상태로 계량하세요. 계산에는 이 그램 수를 사용하며 완성된 요리의 무게는 사용하지 않습니다.',
    ],
    'zh-Hans': [
      '生的',
      '熟的',
      '干燥',
      '未烘烤',
      '销售时状态',
      '请按所示状态称量各食材。计算使用这些克数，而不是成品菜肴的重量。',
    ],
    'zh-Hant': [
      '生的',
      '熟的',
      '乾燥',
      '未烘烤',
      '銷售時狀態',
      '請按所示狀態秤量各食材。計算使用這些克數，而不是成品菜餚的重量。',
    ],
    'ru': [
      'Сырой',
      'Приготовленный',
      'Сухой',
      'До выпекания',
      'В виде продажи',
      'Взвешивайте каждый ингредиент в указанном состоянии. Расчёт использует эти граммы, а не вес готового блюда.',
    ],
    'bn': [
      'কাঁচা',
      'রান্না করা',
      'শুকনো',
      'বেক করার আগে',
      'বিক্রির অবস্থায়',
      'প্রতিটি উপকরণ দেখানো অবস্থায় ওজন করুন। হিসাব এই গ্রাম অনুযায়ী হয়, রান্না করা খাবারের মোট ওজন অনুযায়ী নয়।',
    ],
    'vi': [
      'Sống',
      'Đã nấu',
      'Khô',
      'Chưa nướng',
      'Như khi bán',
      'Cân từng nguyên liệu ở trạng thái được hiển thị. Phép tính dùng số gam này, không dùng trọng lượng món ăn sau khi nấu.',
    ],
    'th': [
      'ดิบ',
      'สุก',
      'แห้ง',
      'ยังไม่อบ',
      'สภาพที่จำหน่าย',
      'ชั่งส่วนผสมแต่ละอย่างตามสภาพที่ระบุ การคำนวณใช้กรัมเหล่านี้ ไม่ใช่น้ำหนักอาหารหลังปรุงเสร็จ',
    ],
    'pl': [
      'Surowe',
      'Ugotowane',
      'Suche',
      'Przed pieczeniem',
      'W postaci sprzedawanej',
      'Waż każdy składnik we wskazanym stanie. Obliczenia używają tych gramów, nie wagi gotowego dania.',
    ],
    'nl': [
      'Rauw',
      'Bereid',
      'Droog',
      'Ongebakken',
      'Zoals verkocht',
      'Weeg elk ingrediënt in de aangegeven staat. De berekening gebruikt deze grammen, niet het gewicht van het bereide gerecht.',
    ],
    'uk': [
      'Сирий',
      'Приготований',
      'Сухий',
      'До випікання',
      'У вигляді продажу',
      'Зважуйте кожен інгредієнт у зазначеному стані. Розрахунок використовує ці грами, а не вагу готової страви.',
    ],
  };
}
