part of 'intelligence_center_engine.dart';

// Pure scope classifiers extracted unchanged from the engine coordinator.
bool _has(String value, List<String> markers) => markers.any(value.contains);
bool _isGreeting(String v) => _has(v, const [
  'مرحبا',
  'مرحبًا',
  'أهلا',
  'أهلًا',
  'كيفك',
  'كيف حالك',
  'شلونك',
  'السلام عليكم',
  'صباح الخير',
  'مساء الخير',
  'hi',
  'hello',
  'hey',
  'how are you',
  'good morning',
  'good afternoon',
  'good evening',
  'assalamualaikum',
  'assalamu alaikum',
  'as-salamu alaykum',
  'salamualaikum',
  'salaam alaikum',
]);
bool _isPlanRequest(String v) => _has(v, const [
  'خطة',
  'برنامج',
  'رتب لي',
  'اعمل لي',
  'أعمل لي',
  'plan',
  'program',
]);
bool _looksLikeLogging(String v) => _has(v, const [
  'أكلت',
  'شربت',
  'تمرنت',
  'وزني',
  'i ate',
  'i drank',
  'i trained',
  'my weight',
]);
bool _looksPersonal(String v) => _has(v, const [
  'جسمي',
  'وزني',
  'أكلي',
  'وجباتي',
  'بروتين',
  'سعرات',
  'تقدمي',
  'الماء',
  'ثبات',
  'هدف',
  'بياناتي',
  'لماذا',
  'my body',
  'my weight',
  'my food',
  'protein',
  'calories',
  'progress',
  'water',
  'hydration',
  'hydrate',
  'dehydration',
  'plateau',
  'goal',
  'my data',
  'why',
]);
bool _looksLikeDiagnosis(String v) => _has(v, const [
  'شخصني',
  'تشخيص',
  'هل عندي',
  'هل مصاب',
  'مرض',
  'دواء',
  'جرعة',
  'diagnose',
  'diagnosis',
  'do i have',
  'disease',
  'medication',
  'dose',
]);
bool _looksUrgent(String v) => _has(v, const [
  'ألم صدر',
  'لا أستطيع التنفس',
  'صعوبة تنفس',
  'إغماء',
  'نزيف شديد',
  'أفكر بالانتحار',
  'chest pain',
  "can't breathe",
  'difficulty breathing',
  'fainted',
  'severe bleeding',
  'suicide',
]);
bool _isAllowedScope(String v) => _has(v, const [
  'صحة',
  'جسم',
  'وزن',
  'أكل',
  'غذاء',
  'وجبة',
  'بروتين',
  'سعرات',
  'ماء',
  'نوم',
  'نشاط',
  'رياضة',
  'تمرين',
  'خطوات',
  'دهون',
  'عضلات',
  'قياس',
  'هدف',
  'تقدم',
  'خطة',
  'دواء',
  'مرض',
  'أعراض',
  'ألم',
  'bil',
  'توأم',
  'البرنامج',
  'التطبيق',
  'التسجيل',
  'coach',
  'health',
  'body',
  'weight',
  'food',
  'meal',
  'nutrition',
  'protein',
  'calories',
  'water',
  'hydration',
  'hydrate',
  'dehydration',
  'sleep',
  'activity',
  'exercise',
  'steps',
  'fat',
  'muscle',
  'measurement',
  'goal',
  'progress',
  'plan',
  'medicine',
  'symptom',
  'pain',
  'app',
  'log',
]);
