import 'package:flutter/widgets.dart';

import '../../app/localization/app_localizations.dart';

class ReferenceSettingsCopy {
  static String Function(String) of(BuildContext context) {
    final code = Localizations.localeOf(context).languageCode;
    return (key) =>
        _copy[code]?[key] ?? context.strings.text(_copy['en']?[key] ?? key);
  }

  static const _copy = <String, Map<String, String>>{
    'en': {},
    'ar': {
      'Account & profile': 'الحساب والملف الشخصي',
      'Diary & goals': 'اليوميات والأهداف',
      'Privacy & notifications': 'الخصوصية والإشعارات',
      'Health preferences': 'تفضيلات الصحة',
      'More': 'المزيد',
      'BIL member': 'عضو BIL',
      'Edit Profile': 'تعديل الملف الشخصي',
      'Last login': 'آخر تسجيل دخول',
      'Weight lost': 'الوزن المفقود',
      'View profile': 'عرض الملف الشخصي',
      'Current': 'الحالي',
      'Remaining': 'المتبقي',
      'Goal': 'الهدف',
      'kg': 'كجم',
      'Try Premium for Free': 'جرّب Premium مجانًا',
      'My Profile': 'ملفي الشخصي',
      'Intermittent Fasting': 'الصيام المتقطع',
      'Sleep': 'النوم',
      'Recipe Discovery': 'اكتشاف الوصفات',
      'Workout Routines': 'روتينات التمارين',
      'Goals': 'الأهداف',
      'Progress': 'التقدم',
      'Weekly Report': 'التقرير الأسبوعي',
      'Nutrition': 'التغذية',
      'My Meals, Recipes & Foods': 'وجباتي ووصفاتي وأطعمتي',
      'Reminders': 'التذكيرات',
      'Apps & Devices': 'التطبيقات والأجهزة',
      'Steps': 'الخطوات',
      'Community': 'المجتمع',
      'Learn': 'تعلّم',
      'Friends': 'الأصدقاء',
      'Messages': 'الرسائل',
      'Settings': 'الإعدادات',
      'Privacy': 'الخصوصية',
      'Help': 'المساعدة',
      'Sync': 'المزامنة',
      'Profile': 'الملف الشخصي',
      'App Appearance': 'مظهر التطبيق',
      'Diary Settings': 'إعدادات اليوميات',
      'Sharing & Privacy': 'المشاركة والخصوصية',
      'My Exercises': 'تماريني',
      'Weekly Nutrition Settings': 'إعدادات التغذية الأسبوعية',
      'Push Notifications': 'الإشعارات الفورية',
      'Logout': 'تسجيل الخروج',
      'Go Premium': 'الانتقال إلى Premium',
      'Explore Premium': 'استكشف Premium',
      'Premium adds advanced insights and customization. Your results still depend on your own data and actions.':
          'يضيف Premium رؤى متقدمة وخيارات تخصيص. وتظل نتائجك معتمدة على بياناتك وإجراءاتك.',
    },
    'fr': {
      'Account & profile': 'Compte et profil',
      'Diary & goals': 'Journal et objectifs',
      'Privacy & notifications': 'Confidentialité et notifications',
      'Health preferences': 'Préférences de santé',
      'More': 'Plus',
      'BIL member': 'Membre BIL',
      'View profile': 'Voir le profil',
      'Current': 'Actuel',
      'Remaining': 'Restant',
      'Goal': 'Objectif',
      'kg': 'kg',
      'Try Premium for Free': 'Essayer Premium gratuitement',
      'My Profile': 'Mon profil',
      'Intermittent Fasting': 'Jeûne intermittent',
      'Sleep': 'Sommeil',
      'Recipe Discovery': 'Découvrir des recettes',
      'Workout Routines': 'Programmes d’entraînement',
      'Goals': 'Objectifs',
      'Progress': 'Progrès',
      'Weekly Report': 'Rapport hebdomadaire',
      'Nutrition': 'Nutrition',
      'My Meals, Recipes & Foods': 'Mes repas, recettes et aliments',
      'Reminders': 'Rappels',
      'Apps & Devices': 'Applications et appareils',
      'Steps': 'Pas',
      'Community': 'Communauté',
      'Learn': 'Apprendre',
      'Friends': 'Amis',
      'Messages': 'Messages',
      'Settings': 'Paramètres',
      'Privacy': 'Confidentialité',
      'Help': 'Aide',
      'Sync': 'Synchroniser',
      'Profile': 'Profil',
      'App Appearance': 'Apparence de l’application',
      'Diary Settings': 'Paramètres du journal',
      'Sharing & Privacy': 'Partage et confidentialité',
      'My Exercises': 'Mes exercices',
      'Weekly Nutrition Settings': 'Nutrition hebdomadaire',
      'Push Notifications': 'Notifications push',
      'Logout': 'Déconnexion',
      'Go Premium': 'Passer à Premium',
      'Explore Premium': 'Découvrir Premium',
      'Premium adds advanced insights and customization. Your results still depend on your own data and actions.':
          'Premium ajoute des analyses avancées et des options de personnalisation. Vos résultats dépendent toujours de vos données et de vos actions.',
    },
    'es': {
      'Account & profile': 'Cuenta y perfil',
      'Diary & goals': 'Diario y objetivos',
      'Privacy & notifications': 'Privacidad y notificaciones',
      'Health preferences': 'Preferencias de salud',
      'More': 'Más',
      'BIL member': 'Miembro de BIL',
      'View profile': 'Ver perfil',
      'Current': 'Actual',
      'Remaining': 'Restante',
      'Goal': 'Objetivo',
      'kg': 'kg',
      'Try Premium for Free': 'Prueba Premium gratis',
      'My Profile': 'Mi perfil',
      'Intermittent Fasting': 'Ayuno intermitente',
      'Sleep': 'Sueño',
      'Recipe Discovery': 'Descubrir recetas',
      'Workout Routines': 'Rutinas de ejercicio',
      'Goals': 'Objetivos',
      'Progress': 'Progreso',
      'Weekly Report': 'Informe semanal',
      'Nutrition': 'Nutrición',
      'My Meals, Recipes & Foods': 'Mis comidas, recetas y alimentos',
      'Reminders': 'Recordatorios',
      'Apps & Devices': 'Aplicaciones y dispositivos',
      'Steps': 'Pasos',
      'Community': 'Comunidad',
      'Learn': 'Aprender',
      'Friends': 'Amigos',
      'Messages': 'Mensajes',
      'Settings': 'Configuración',
      'Privacy': 'Privacidad',
      'Help': 'Ayuda',
      'Sync': 'Sincronizar',
      'Profile': 'Perfil',
      'App Appearance': 'Apariencia de la aplicación',
      'Diary Settings': 'Configuración del diario',
      'Sharing & Privacy': 'Compartir y privacidad',
      'My Exercises': 'Mis ejercicios',
      'Weekly Nutrition Settings': 'Nutrición semanal',
      'Push Notifications': 'Notificaciones push',
      'Logout': 'Cerrar sesión',
      'Go Premium': 'Hazte Premium',
      'Explore Premium': 'Explorar Premium',
      'Premium adds advanced insights and customization. Your results still depend on your own data and actions.':
          'Premium añade análisis avanzados y opciones de personalización. Tus resultados siguen dependiendo de tus datos y acciones.',
    },
    'tr': {
      'Account & profile': 'Hesap ve profil',
      'Diary & goals': 'Günlük ve hedefler',
      'Privacy & notifications': 'Gizlilik ve bildirimler',
      'Health preferences': 'Sağlık tercihleri',
      'More': 'Daha Fazla',
      'BIL member': 'BIL üyesi',
      'View profile': 'Profili görüntüle',
      'Current': 'Mevcut',
      'Remaining': 'Kalan',
      'Goal': 'Hedef',
      'kg': 'kg',
      'Try Premium for Free': 'Premium’u ücretsiz dene',
      'My Profile': 'Profilim',
      'Intermittent Fasting': 'Aralıklı oruç',
      'Sleep': 'Uyku',
      'Recipe Discovery': 'Tarif keşfi',
      'Workout Routines': 'Egzersiz rutinleri',
      'Goals': 'Hedefler',
      'Progress': 'İlerleme',
      'Weekly Report': 'Haftalık rapor',
      'Nutrition': 'Beslenme',
      'My Meals, Recipes & Foods': 'Öğünlerim, tariflerim ve yiyeceklerim',
      'Reminders': 'Hatırlatıcılar',
      'Apps & Devices': 'Uygulamalar ve cihazlar',
      'Steps': 'Adımlar',
      'Community': 'Topluluk',
      'Learn': 'Öğren',
      'Friends': 'Arkadaşlar',
      'Messages': 'Mesajlar',
      'Settings': 'Ayarlar',
      'Privacy': 'Gizlilik',
      'Help': 'Yardım',
      'Sync': 'Eşitle',
      'Profile': 'Profil',
      'App Appearance': 'Uygulama görünümü',
      'Diary Settings': 'Günlük ayarları',
      'Sharing & Privacy': 'Paylaşım ve gizlilik',
      'My Exercises': 'Egzersizlerim',
      'Weekly Nutrition Settings': 'Haftalık beslenme ayarları',
      'Push Notifications': 'Anlık bildirimler',
      'Logout': 'Çıkış yap',
      'Go Premium': 'Premium’a geç',
      'Explore Premium': 'Premium’u keşfet',
      'Premium adds advanced insights and customization. Your results still depend on your own data and actions.':
          'Premium gelişmiş analizler ve özelleştirme seçenekleri sunar. Sonuçlarınız yine kendi verilerinize ve eylemlerinize bağlıdır.',
    },
  };
}
