import '../../../app/localization/runtime_copy.dart';

abstract final class BilStoreCopy {
  static const catalogs = <String, Map<String, String>>{
    'en': {
      'free': 'Free',
      'plans': 'Plans',
      'premium_store_title': 'Know your body. Progress intelligently.',
      'premium_store_eyebrow': 'BIL Premium',
      'premium_store_subtitle': 'Price from the store',
      'current_plan': 'Current plan',
      'free_detail': 'Core tracking and daily tools',
      'premium_detail': 'The complete experience, without ads',
      'premium_ai_detail': 'Premium plus a personal multilingual AI Coach',
      'boost_eyebrow': 'YOUR COACH. YOUR PLAN. EVERY DAY.',
      'boost_detail':
          'BIL AI Coach speaks every language and works beside you as a training and nutrition partner.',
      'free_benefit_1': 'Food, water and weight tracking',
      'free_benefit_2': 'Core nutrition insights',
      'free_benefit_3': 'Local progress analytics',
      'free_benefit_4': 'Export your own data',
      'free_benefit_5': 'Watch and health sync',
      'premium_benefit_1': 'Everything included in BIL Free',
      'premium_benefit_2': 'No ads',
      'premium_benefit_3': 'Personalized Meal Planner',
      'premium_benefit_barcode': 'Scan food barcode',
      'premium_benefit_dashboard': 'Macro and nutrient trends',
      'premium_benefit_recipes': '1,500 recipes',
      'premium_benefit_workouts': '300+ home workout videos',
      'premium_benefit_strength_plans':
          '100+ video-guided weight-training plans',
      'premium_benefit_meal_plan': 'Personal weekly meal plan',
      'premium_benefit_programs': 'Goal-based nutrition pathways',
      'premium_benefit_reports': 'Weekly trends and comparisons',
      'premium_benefit_fasting': 'Live fasting timer',
      'premium_benefit_sleep': 'Sleep trends',
      'premium_benefit_body': 'Detailed body profile',
      'premium_benefit_4': 'Connected health',
      'premium_benefit_5': 'Custom calories and macros',
      'premium_benefit_medical_devices':
          'Compatible fitness device connections',
      'premium_benefit_community':
          'Premium community, friends, and private messaging',
      'premium_benefit_trial': '7-day trial includes 1,000 AI tokens',
      'ai_benefit_1': 'Everything included in BIL Premium',
      'ai_benefit_2': 'Advanced personalized AI Coach',
      'ai_benefit_3': 'Global multilingual voice',
      'ai_benefit_4': '2,500 AI tokens each week, up to 10,000 each month',
      'ai_benefit_community':
          'All Premium community and friend features included',
      'ai_benefit_trial': '7-day trial includes 1,000 AI tokens',
      'boost_benefit_1': '2,500 BIL AI Coach tokens',
      'boost_benefit_2': 'Daily, weekly, and monthly plans for your goal',
      'boost_benefit_3':
          'A training and nutrition partner that follows your progress',
      'boost_benefit_4': 'One-time purchase',
      'boost_benefit_5': 'Tokens stack and never expire',
      'premium': 'Premium',
      'premium_ai_coach': 'Premium AI Coach',
      'ai_boost': 'BIL AI Boost',
      'monthly': 'Monthly',
      'annual': 'Annual',
      'billed_monthly': 'Billed monthly',
      'billed_annually': 'Billed annually',
      'twelve_monthly_payments': '12 monthly payments',
      'monthly_equivalent': 'Monthly equivalent',
      'per_month': 'per month',
      'save': 'Save',
      'versus_monthly': 'versus 12 monthly payments',
      'trial': 'Free trial',
      'trial_7_days': '7 days free',
      'continue': 'Continue',
      'restore': 'Restore purchases',
      'restore_checking': 'Checking purchase history…',
      'restore_checked': 'Purchase history checked securely.',
      'restore_verified': 'Your verified purchase was restored.',
      'restore_none': 'No restorable purchases were found for this account.',
      'restore_sign_in': 'Sign in before restoring purchases.',
      'restore_failed': 'Purchases could not be restored. Try again.',
      'restore_timeout': 'The store did not respond. Try again.',
      'manage': 'Manage subscription',
      'store_loading': 'Loading price from the store…',
      'store_unavailable': 'Price unavailable on this device',
      'purchase_error':
          'The purchase was not completed. No access was granted.',
      'ads_consent': 'Choose whether BIL may show contextual ads.',
    },
    'ar': {
      'free': 'مجاني',
      'plans': 'الخطط',
      'premium_store_title': 'عضوية مصممة حولك',
      'premium_store_eyebrow': 'عضوية BIL',
      'premium_store_subtitle':
          'شاهد كل شيء قبل أن تختار. يعرض المتجر السعر بعملتك المحلية.',
      'current_plan': 'خطتك الحالية',
      'free_detail': 'التسجيل الأساسي وأدواتك اليومية',
      'premium_detail': 'التجربة الكاملة، بدون إعلانات',
      'premium_ai_detail': 'بريميوم مع مدرب AI شخصي متعدد اللغات',
      'boost_eyebrow': 'مدربك. خطتك. كل يوم.',
      'boost_detail':
          'يتحدث مدرب BIL الذكي جميع اللغات ويعمل معك كشريك في التمرين والدايت.',
      'free_benefit_1': 'تسجيل الطعام والماء والوزن',
      'free_benefit_2': 'أساسيات وتحليلات التغذية',
      'free_benefit_3': 'تحليلات التقدم المحلية',
      'free_benefit_4': 'تصدير بياناتك',
      'free_benefit_5': 'مزامنة الساعة والصحة',
      'premium_benefit_1': 'كل ما في الخطة المجانية',
      'premium_benefit_2': 'بدون إعلانات',
      'premium_benefit_3': 'مخطط وجبات شخصي',
      'premium_benefit_barcode': 'ماسح باركود الطعام',
      'premium_benefit_dashboard': 'دوائر المغذيات وصحة القلب والأهداف المخصصة',
      'premium_benefit_recipes': '1,500 وصفة مع القيم الغذائية',
      'premium_benefit_workouts': 'أكثر من 300 فيديو تمارين منزلية',
      'premium_benefit_strength_plans':
          'أكثر من 100 خطة تمارين رفع أثقال بالفيديو',
      'premium_benefit_meal_plan': 'خطة وجبات أسبوعية شخصية',
      'premium_benefit_programs': 'مسارات تغذية مبنية على هدفك',
      'premium_benefit_reports': 'تقارير ومقارنات أسبوعية متقدمة',
      'premium_benefit_fasting': 'مؤقت صيام متقطع مباشر',
      'premium_benefit_sleep': 'اتجاهات ورؤى النوم',
      'premium_benefit_body': 'قياسات الجسم وملف التركيب المفصل',
      'premium_benefit_4': 'ربط المصادر الصحية',
      'premium_benefit_5': 'سعرات ومغذيات كبرى مخصصة',
      'premium_benefit_medical_devices': 'اتصالات أجهزة اللياقة المتوافقة',
      'premium_benefit_community':
          'مجتمع بريميوم، إضافة الأصدقاء والمراسلة الخاصة',
      'premium_benefit_trial': 'تجربة 7 أيام تشمل 1,000 توكن AI',
      'ai_benefit_1': 'كل ما في بريميوم',
      'ai_benefit_2': 'مدرب AI شخصي متقدم',
      'ai_benefit_3': 'صوت عالمي متعدد اللغات',
      'ai_benefit_4': '2,500 توكن AI أسبوعيًا، وبحد 10,000 شهريًا',
      'ai_benefit_community': 'يشمل كل مزايا مجتمع بريميوم والأصدقاء',
      'ai_benefit_trial': 'تجربة 7 أيام تشمل 1,000 توكن AI',
      'boost_benefit_1': '2,500 توكن لمدرب BIL الذكي',
      'boost_benefit_2': 'خطط يومية وأسبوعية وشهرية حسب هدفك',
      'boost_benefit_3': 'شريك للتمرين والدايت يتابع تقدمك',
      'boost_benefit_4': 'شراء لمرة واحدة',
      'boost_benefit_5': 'يتراكم الرصيد ولا تنتهي صلاحيته',
      'premium': 'بريميوم',
      'premium_ai_coach': 'بريميوم AI Coach',
      'ai_boost': 'BIL AI Boost',
      'monthly': 'شهري',
      'annual': 'سنوي',
      'billed_monthly': 'تُدفع شهريًا',
      'billed_annually': 'تُدفع سنويًا',
      'twelve_monthly_payments': 'إجمالي 12 دفعة شهرية',
      'monthly_equivalent': 'المكافئ الشهري',
      'per_month': 'شهريًا',
      'save': 'وفّر',
      'versus_monthly': 'مقارنةً بـ12 دفعة شهرية',
      'trial': 'تجربة مجانية',
      'trial_7_days': '7 أيام مجانًا',
      'continue': 'متابعة',
      'restore': 'استعادة المشتريات',
      'restore_checking': 'جارٍ التحقق من سجل المشتريات…',
      'restore_checked': 'تم التحقق من سجل المشتريات بأمان.',
      'restore_verified': 'تمت استعادة مشترياتك الموثّقة.',
      'restore_none': 'لم يتم العثور على مشتريات قابلة للاستعادة لهذا الحساب.',
      'restore_sign_in': 'سجّل الدخول قبل استعادة المشتريات.',
      'restore_failed': 'تعذرت استعادة المشتريات. حاول مرة أخرى.',
      'restore_timeout': 'لم يستجب المتجر. حاول مرة أخرى.',
      'manage': 'إدارة الاشتراك',
      'store_loading': 'جارٍ تحميل السعر من المتجر…',
      'store_unavailable': 'السعر غير متاح على هذا الجهاز',
      'purchase_error': 'لم تكتمل عملية الشراء ولم يتم منح أي صلاحية.',
      'ads_consent': 'اختر ما إذا كان بإمكان BIL عرض إعلانات سياقية.',
    },
    'fr': {
      'free': 'Gratuit',
      'plans': 'Forfaits',
      'premium_store_title':
          'Connaissez votre corps. Progressez intelligemment.',
      'premium_store_eyebrow': 'BIL Premium',
      'premium_store_subtitle': 'Prix fourni par la boutique',
      'current_plan': 'Forfait actuel',
      'free_detail': 'Suivi essentiel et outils quotidiens',
      'premium_detail': 'L’expérience complète, sans publicité',
      'premium_ai_detail': 'Premium avec un AI Coach personnel multilingue',
      'boost_eyebrow': 'VOTRE COACH. VOTRE PLAN. CHAQUE JOUR.',
      'boost_detail':
          'BIL AI Coach parle toutes les langues et vous accompagne comme partenaire d’entraînement et de nutrition.',
      'premium': 'Premium',
      'premium_ai_coach': 'Premium AI Coach',
      'ai_boost': 'BIL AI Boost',
      'free_benefit_1': 'Suivi des aliments, de l’eau et du poids',
      'free_benefit_2': 'Analyses nutritionnelles essentielles',
      'free_benefit_3': 'Analyses locales de progression',
      'free_benefit_4': 'Exportez vos propres données',
      'free_benefit_5': 'Synchronisation montre et santé',
      'premium_benefit_1': 'Tout ce qui est inclus dans BIL Gratuit',
      'premium_benefit_2': 'Sans publicité',
      'premium_benefit_3': 'Planificateur de repas personnalisé',
      'premium_benefit_barcode':
          'Scanner Premium des codes-barres alimentaires',
      'premium_benefit_dashboard':
          'Cercles des nutriments et de la santé cardiaque, objectifs personnalisés',
      'premium_benefit_recipes':
          '1 500 recettes avec informations nutritionnelles',
      'premium_benefit_workouts':
          'Plus de 300 vidéos d’entraînement à domicile',
      'premium_benefit_strength_plans':
          'Plus de 100 programmes de musculation guidés en vidéo',
      'premium_benefit_meal_plan': 'Plan de repas hebdomadaire personnalisé',
      'premium_benefit_programs': 'Parcours nutritionnels selon vos objectifs',
      'premium_benefit_reports': 'Rapports et comparaisons hebdomadaires',
      'premium_benefit_fasting': 'Minuteur de jeûne intermittent en direct',
      'premium_benefit_sleep': 'Tendances et analyses du sommeil',
      'premium_benefit_body': 'Mesures et profil corporel détaillés',
      'premium_benefit_4': 'Santé connectée',
      'premium_benefit_5': 'Calories et macros personnalisées',
      'premium_benefit_medical_devices':
          'Connexions aux appareils de fitness compatibles',
      'premium_benefit_community':
          'Communauté Premium, amis et messagerie privée',
      'premium_benefit_trial': 'Essai de 7 jours avec 1 000 jetons AI',
      'ai_benefit_1': 'Tout ce qui est inclus dans BIL Premium',
      'ai_benefit_2': 'AI Coach personnalisé avancé',
      'ai_benefit_3': 'Voix mondiale multilingue',
      'ai_benefit_4': '2 500 jetons AI par semaine, jusqu’à 10 000 par mois',
      'ai_benefit_community':
          'Toutes les fonctions Premium de communauté et d’amis incluses',
      'ai_benefit_trial': 'Essai de 7 jours avec 1 000 jetons AI',
      'boost_benefit_1': '2 500 jetons BIL AI Coach',
      'boost_benefit_2':
          'Programmes quotidiens, hebdomadaires et mensuels selon votre objectif',
      'boost_benefit_3':
          'Un partenaire d’entraînement et de nutrition qui suit vos progrès',
      'boost_benefit_4': 'Achat unique',
      'boost_benefit_5': 'Les jetons se cumulent et n’expirent jamais',
      'monthly': 'Mensuel',
      'annual': 'Annuel',
      'billed_monthly': 'Facturé mensuellement',
      'billed_annually': 'Facturé annuellement',
      'twelve_monthly_payments': '12 paiements mensuels',
      'monthly_equivalent': 'Équivalent mensuel',
      'per_month': 'par mois',
      'save': 'Économisez',
      'versus_monthly': 'par rapport à 12 paiements mensuels',
      'trial': 'Essai gratuit',
      'trial_7_days': '7 jours gratuits',
      'continue': 'Continuer',
      'restore': 'Restaurer les achats',
      'restore_checking': 'Vérification de l’historique des achats…',
      'restore_checked': 'Historique des achats vérifié en toute sécurité.',
      'restore_verified': 'Votre achat vérifié a été restauré.',
      'restore_none': 'Aucun achat restaurable trouvé pour ce compte.',
      'restore_sign_in': 'Connectez-vous avant de restaurer les achats.',
      'restore_failed': 'Impossible de restaurer les achats. Réessayez.',
      'restore_timeout': 'La boutique ne répond pas. Réessayez.',
      'manage': 'Gérer l’abonnement',
      'store_loading': 'Chargement du prix depuis la boutique…',
      'store_unavailable': 'Prix indisponible sur cet appareil',
      'purchase_error': 'L’achat n’a pas abouti. Aucun accès n’a été accordé.',
      'ads_consent':
          'Choisissez si BIL peut afficher des publicités contextuelles.',
    },
    'es': {
      'free': 'Gratis',
      'plans': 'Planes',
      'premium_store_title': 'Conoce tu cuerpo. Progresa con inteligencia.',
      'premium_store_eyebrow': 'BIL Premium',
      'premium_store_subtitle': 'Precio de la tienda',
      'current_plan': 'Plan actual',
      'free_detail': 'Seguimiento esencial y herramientas diarias',
      'premium_detail': 'La experiencia completa, sin anuncios',
      'premium_ai_detail': 'Premium con un AI Coach personal multilingüe',
      'boost_eyebrow': 'TU COACH. TU PLAN. CADA DÍA.',
      'boost_detail':
          'BIL AI Coach habla todos los idiomas y trabaja contigo como compañero de entrenamiento y nutrición.',
      'premium': 'Premium',
      'premium_ai_coach': 'Premium AI Coach',
      'ai_boost': 'BIL AI Boost',
      'free_benefit_1': 'Seguimiento de comida, agua y peso',
      'free_benefit_2': 'Información nutricional esencial',
      'free_benefit_3': 'Análisis local del progreso',
      'free_benefit_4': 'Exporta tus propios datos',
      'free_benefit_5': 'Sincronización de reloj y salud',
      'premium_benefit_1': 'Todo lo incluido en BIL Gratis',
      'premium_benefit_2': 'Sin anuncios',
      'premium_benefit_3': 'Planificador de comidas personalizado',
      'premium_benefit_barcode': 'Escáner Premium de códigos de alimentos',
      'premium_benefit_dashboard':
          'Círculos de nutrientes y salud cardíaca con objetivos personalizados',
      'premium_benefit_recipes': '1.500 recetas con información nutricional',
      'premium_benefit_workouts': 'Más de 300 vídeos de entrenamiento en casa',
      'premium_benefit_strength_plans':
          'Más de 100 planes de pesas guiados en vídeo',
      'premium_benefit_meal_plan': 'Plan semanal de comidas personalizado',
      'premium_benefit_programs': 'Rutas nutricionales según tus objetivos',
      'premium_benefit_reports': 'Informes y comparaciones semanales',
      'premium_benefit_fasting': 'Temporizador de ayuno intermitente en vivo',
      'premium_benefit_sleep': 'Tendencias y análisis del sueño',
      'premium_benefit_body': 'Medidas y perfil corporal detallados',
      'premium_benefit_4': 'Salud conectada',
      'premium_benefit_5': 'Calorías y macros personalizadas',
      'premium_benefit_medical_devices':
          'Conexiones con dispositivos de fitness compatibles',
      'premium_benefit_community':
          'Comunidad Premium, amigos y mensajería privada',
      'premium_benefit_trial': 'Prueba de 7 días con 1.000 tokens AI',
      'ai_benefit_1': 'Todo lo incluido en BIL Premium',
      'ai_benefit_2': 'AI Coach personalizado avanzado',
      'ai_benefit_3': 'Voz global multilingüe',
      'ai_benefit_4': '2.500 tokens AI por semana, hasta 10.000 al mes',
      'ai_benefit_community':
          'Incluye todas las funciones Premium de comunidad y amigos',
      'ai_benefit_trial': 'Prueba de 7 días con 1.000 tokens AI',
      'boost_benefit_1': '2.500 tokens de BIL AI Coach',
      'boost_benefit_2':
          'Planes diarios, semanales y mensuales para tu objetivo',
      'boost_benefit_3':
          'Un compañero de entrenamiento y nutrición que sigue tu progreso',
      'boost_benefit_4': 'Compra única',
      'boost_benefit_5': 'Los tokens se acumulan y nunca caducan',
      'monthly': 'Mensual',
      'annual': 'Anual',
      'billed_monthly': 'Facturado mensualmente',
      'billed_annually': 'Facturado anualmente',
      'twelve_monthly_payments': '12 pagos mensuales',
      'monthly_equivalent': 'Equivalente mensual',
      'per_month': 'al mes',
      'save': 'Ahorra',
      'versus_monthly': 'frente a 12 pagos mensuales',
      'trial': 'Prueba gratuita',
      'trial_7_days': '7 días gratis',
      'continue': 'Continuar',
      'restore': 'Restaurar compras',
      'restore_checking': 'Comprobando el historial de compras…',
      'restore_checked': 'Historial de compras comprobado de forma segura.',
      'restore_verified': 'Se restauró tu compra verificada.',
      'restore_none':
          'No se encontraron compras restaurables para esta cuenta.',
      'restore_sign_in': 'Inicia sesión antes de restaurar compras.',
      'restore_failed':
          'No se pudieron restaurar las compras. Inténtalo de nuevo.',
      'restore_timeout': 'La tienda no respondió. Inténtalo de nuevo.',
      'manage': 'Gestionar suscripción',
      'store_loading': 'Cargando el precio desde la tienda…',
      'store_unavailable': 'Precio no disponible en este dispositivo',
      'purchase_error': 'La compra no se completó. No se concedió acceso.',
      'ads_consent': 'Elige si BIL puede mostrar anuncios contextuales.',
    },
    'tr': {
      'free': 'Ücretsiz',
      'plans': 'Planlar',
      'premium_store_title': 'Vücudunu tanı. Akıllıca ilerle.',
      'premium_store_eyebrow': 'BIL Premium',
      'premium_store_subtitle': 'Mağazadaki fiyat',
      'current_plan': 'Mevcut plan',
      'free_detail': 'Temel takip ve günlük araçlar',
      'premium_detail': 'Reklamsız eksiksiz deneyim',
      'premium_ai_detail': 'Kişisel çok dilli AI Coach içeren Premium',
      'boost_eyebrow': 'KOÇUNUZ. PLANINIZ. HER GÜN.',
      'boost_detail':
          'BIL AI Coach tüm dilleri konuşur ve antrenman ile beslenme ortağınız olarak yanınızda çalışır.',
      'premium': 'Premium',
      'premium_ai_coach': 'Premium AI Coach',
      'ai_boost': 'BIL AI Boost',
      'free_benefit_1': 'Yemek, su ve kilo takibi',
      'free_benefit_2': 'Temel beslenme bilgileri',
      'free_benefit_3': 'Yerel ilerleme analizi',
      'free_benefit_4': 'Kendi verilerinizi dışa aktarın',
      'free_benefit_5': 'Saat ve sağlık eşitleme',
      'premium_benefit_1': 'BIL Ücretsiz’deki her şey',
      'premium_benefit_2': 'Reklamsız',
      'premium_benefit_3': 'Kişiselleştirilmiş Öğün Planlayıcı',
      'premium_benefit_barcode': 'Premium yiyecek barkodu tarayıcısı',
      'premium_benefit_dashboard':
          'Besin ve kalp sağlığı halkaları ile özel hedefler',
      'premium_benefit_recipes': 'Besin değerleriyle 1.500 tarif',
      'premium_benefit_workouts': '300+ ev antrenmanı videosu',
      'premium_benefit_strength_plans':
          '100+ video rehberli ağırlık antrenmanı planı',
      'premium_benefit_meal_plan': 'Kişisel haftalık öğün planı',
      'premium_benefit_programs': 'Hedefe dayalı beslenme yolları',
      'premium_benefit_reports': 'Haftalık raporlar ve karşılaştırmalar',
      'premium_benefit_fasting': 'Canlı aralıklı oruç zamanlayıcısı',
      'premium_benefit_sleep': 'Uyku eğilimleri ve analizleri',
      'premium_benefit_body': 'Ayrıntılı vücut ölçümleri ve profili',
      'premium_benefit_4': 'Bağlı sağlık',
      'premium_benefit_5': 'Özel kaloriler ve makrolar',
      'premium_benefit_medical_devices': 'Uyumlu fitness cihazı bağlantıları',
      'premium_benefit_community':
          'Premium topluluk, arkadaşlar ve özel mesajlaşma',
      'premium_benefit_trial': '1.000 AI token içeren 7 günlük deneme',
      'ai_benefit_1': 'BIL Premium’daki her şey',
      'ai_benefit_2': 'Gelişmiş kişisel AI Coach',
      'ai_benefit_3': 'Küresel çok dilli ses',
      'ai_benefit_4': 'Haftada 2.500 AI token, ayda en fazla 10.000',
      'ai_benefit_community':
          'Tüm Premium topluluk ve arkadaş özellikleri dahildir',
      'ai_benefit_trial': '1.000 AI token içeren 7 günlük deneme',
      'boost_benefit_1': '2.500 BIL AI Coach tokeni',
      'boost_benefit_2': 'Hedefinize göre günlük, haftalık ve aylık planlar',
      'boost_benefit_3': 'İlerlemenizi takip eden antrenman ve beslenme ortağı',
      'boost_benefit_4': 'Tek seferlik satın alma',
      'boost_benefit_5': 'Tokenler birikir ve asla sona ermez',
      'monthly': 'Aylık',
      'annual': 'Yıllık',
      'billed_monthly': 'Aylık faturalandırılır',
      'billed_annually': 'Yıllık faturalandırılır',
      'twelve_monthly_payments': '12 aylık ödeme',
      'monthly_equivalent': 'Aylık karşılığı',
      'per_month': 'aylık',
      'save': 'Tasarruf',
      'versus_monthly': '12 aylık ödemeye kıyasla',
      'trial': 'Ücretsiz deneme',
      'trial_7_days': '7 gün ücretsiz',
      'continue': 'Devam et',
      'restore': 'Satın alımları geri yükle',
      'restore_checking': 'Satın alma geçmişi kontrol ediliyor…',
      'restore_checked': 'Satın alma geçmişi güvenle kontrol edildi.',
      'restore_verified': 'Doğrulanmış satın alımınız geri yüklendi.',
      'restore_none': 'Bu hesap için geri yüklenebilir satın alım bulunamadı.',
      'restore_sign_in': 'Satın alımları geri yüklemeden önce oturum açın.',
      'restore_failed': 'Satın alımlar geri yüklenemedi. Tekrar deneyin.',
      'restore_timeout': 'Mağaza yanıt vermedi. Tekrar deneyin.',
      'manage': 'Aboneliği yönet',
      'store_loading': 'Fiyat mağazadan yükleniyor…',
      'store_unavailable': 'Fiyat bu cihazda kullanılamıyor',
      'purchase_error': 'Satın alma tamamlanmadı. Erişim verilmedi.',
      'ads_consent':
          'BIL’in bağlamsal reklam gösterip gösteremeyeceğini seçin.',
    },
  };

  static String text(String locale, String key) {
    final language = locale.toLowerCase().split(RegExp('[-_]')).first;
    final english = catalogs['en']![key] ?? key;
    return catalogs[language]?[key] ??
        RuntimeCopy.resolve(english, locale) ??
        english;
  }
}
