import 'food_search_assistance.dart';

/// Presentation-only localization for a small reviewed set of canonical foods
/// and serving units.
///
/// It never translates arbitrary catalog text. Branded, custom, and unknown
/// scientific names remain exactly as stored so the UI cannot invent identity.
abstract final class FoodPresentationLocalizer {
  static const supportedLocaleTags = <String>{
    'ar',
    'en',
    'fr',
    'es',
    'tr',
    'de',
    'it',
    'pt-BR',
    'pt-PT',
    'ur',
    'fa',
    'hi',
    'id',
    'ms',
    'ja',
    'ko',
    'zh-Hans',
    'zh-Hant',
    'ru',
    'bn',
    'vi',
    'th',
    'pl',
    'nl',
    'uk',
  };

  static String foodName({
    required String name,
    required String localeTag,
    String? arabicName,
    bool isCustom = false,
    String source = '',
  }) {
    final original = name.trim();
    if (original.isEmpty) return original;
    if (localeTag == 'en') return original;
    if (!isCustom && !_isBranded(source) && localeTag == 'ar') {
      if (arabicName?.trim().isNotEmpty == true) {
        return arabicName!.trim();
      }
      // Translate only when the reviewed lexicon preserves most of the
      // authoritative food identity. Partial labels are deliberately rejected.
      final reviewedArabic = const FoodSearchAssistance().arabicNameFor(
        original,
      );
      if (reviewedArabic != null) return reviewedArabic;
    }
    if (isCustom || _isBranded(source)) return original;
    final normalized = _normalize(original);
    final concept = _reviewedFoodConcept(normalized);
    return _localizedFoodName(concept, localeTag) ?? original;
  }

  /// Food rows always follow the selected interface locale. Search matching
  /// may accept any script, but it must never change the language of the
  /// results list behind the user's back.
  static String resultLocaleForQuery({
    required String query,
    required String interfaceLocaleTag,
  }) {
    final fallback = supportedLocaleTags.contains(interfaceLocaleTag)
        ? interfaceLocaleTag
        : 'en';
    return fallback;
  }

  /// Whether an anonymous browse suggestion owns a native display name.
  /// Branded/user-entered names remain authoritative in explicit search, but
  /// must not leak as English fallbacks into Arabic "popular" suggestions.
  static bool hasLocalizedBrowseName({
    required String name,
    required String localeTag,
    String? arabicName,
    bool isCustom = false,
    String source = '',
  }) {
    if (localeTag == 'en') return true;
    final original = name.trim();
    if (original.isEmpty) return false;
    if (isCustom || _isBranded(source)) return true;
    if (localeTag == 'ar' && arabicName?.trim().isNotEmpty == true) return true;
    return _reviewedFoodConcept(_normalize(original)) != null;
  }

  static String servingUnit(String raw, String localeTag) {
    final original = raw.trim();
    final normalized = _normalize(original);
    if (const {'', 'undetermined', 'unknown', 'unit'}.contains(normalized)) {
      return _units['unavailable']?[localeTag] ??
          _units['unavailable']?['en'] ??
          'Serving unavailable';
    }
    final concept = switch (normalized) {
      'g' || 'gram' || 'grams' => 'g',
      'mg' || 'milligram' || 'milligrams' => 'mg',
      'ml' || 'milliliter' || 'milliliters' => 'ml',
      'kcal' || 'calorie' || 'calories' => 'kcal',
      'piece' || 'pieces' => 'piece',
      'serving' || 'servings' => 'serving',
      'oz' || 'ounce' || 'ounces' => 'oz',
      'kg' || 'kilogram' || 'kilograms' => 'kg',
      'lb' || 'pound' || 'pounds' => 'lb',
      _ => null,
    };
    if (concept == null) return original;
    return _units[concept]?[localeTag] ?? _units[concept]?['en'] ?? original;
  }

  static bool hasKnownServingUnit(String raw) =>
      !const {'', 'undetermined', 'unknown', 'unit'}.contains(_normalize(raw));

  static String servingText({
    required String amount,
    required String unit,
    required String localeTag,
  }) {
    if (!hasKnownServingUnit(unit)) return servingUnit(unit, localeTag);
    return '$amount ${servingUnit(unit, localeTag)}';
  }

  /// Compact browse rows omit unknown portion metadata entirely. Showing a
  /// translated "unavailable" sentence beside calories creates visual noise
  /// and looks like a real serving value.
  static String? browseServingText({
    required String amount,
    required String unit,
    required String localeTag,
  }) => hasKnownServingUnit(unit)
      ? servingText(amount: amount, unit: unit, localeTag: localeTag)
      : null;

  static String label(String key, String localeTag) =>
      _labels[key]?[localeTag] ?? _labels[key]?['en'] ?? key;

  static bool _isBranded(String source) {
    final normalized = source.toLowerCase();
    return normalized.contains('brand') ||
        normalized.contains('barcode') ||
        normalized.contains('product');
  }

  static String _normalize(String value) =>
      value.trim().toLowerCase().replaceAll(RegExp(r'[^a-z0-9]+'), ' ').trim();

  static bool _isReviewedWholeEggName(String normalized) {
    if (normalized == 'egg' || normalized == 'eggs') return true;
    if (normalized.startsWith('egg ') || normalized.startsWith('eggs ')) {
      return !normalized.startsWith('eggplant') &&
          !normalized.contains(' egg roll');
    }
    return normalized.startsWith('chicken egg ') ||
        normalized.startsWith('chicken eggs ');
  }

  static String? _reviewedFoodConcept(String normalized) {
    bool has(String word) => RegExp(
      '(^| )${RegExp.escape(word)}'
      r'( |$)',
    ).hasMatch(normalized);
    if (normalized.contains('chicken breast')) return 'chickenBreast';
    if (_isReviewedWholeEggName(normalized) &&
        (normalized.contains('boiled') || normalized.contains('hard cooked'))) {
      return 'boiledEggs';
    }
    if (_isReviewedWholeEggName(normalized)) return 'eggs';
    for (final entry in const <(String, String)>[
      ('apple', 'apple'),
      ('banana', 'banana'),
      ('orange', 'orange'),
      ('chicken', 'chicken'),
      ('beef', 'beef'),
      ('fish', 'fish'),
      ('rice', 'rice'),
      ('bread', 'bread'),
      ('milk', 'milk'),
      ('yogurt', 'yogurt'),
      ('yoghurt', 'yogurt'),
      ('cheese', 'cheese'),
      ('potato', 'potato'),
      ('tomato', 'tomato'),
      ('cucumber', 'cucumber'),
      ('oat', 'oats'),
      ('oats', 'oats'),
      ('salmon', 'salmon'),
      ('tuna', 'tuna'),
      ('lentil', 'lentils'),
      ('lentils', 'lentils'),
      ('bean', 'beans'),
      ('beans', 'beans'),
      ('water', 'water'),
      ('coffee', 'coffee'),
      ('tea', 'tea'),
    ]) {
      if (has(entry.$1)) return entry.$2;
    }
    return null;
  }

  static String? _localizedFoodName(String? concept, String localeTag) {
    if (concept == null) return null;
    final direct = _foods[concept]?[localeTag];
    if (direct != null) return direct;
    final index = _foodLocaleOrder.indexOf(localeTag);
    final values = _coreFoodNames[concept];
    return index < 0 || values == null ? null : values[index];
  }

  static const _foods = <String, Map<String, String>>{
    'apple': {
      'ar': 'تفاحة',
      'en': 'Apple',
      'fr': 'Pomme',
      'es': 'Manzana',
      'tr': 'Elma',
      'de': 'Apfel',
      'it': 'Mela',
      'pt-BR': 'Maçã',
      'pt-PT': 'Maçã',
      'ur': 'سیب',
      'fa': 'سیب',
      'hi': 'सेब',
      'id': 'Apel',
      'ms': 'Epal',
      'ja': 'りんご',
      'ko': '사과',
      'zh-Hans': '苹果',
      'zh-Hant': '蘋果',
      'ru': 'Яблоко',
      'bn': 'আপেল',
      'vi': 'Táo',
      'th': 'แอปเปิล',
      'pl': 'Jabłko',
      'nl': 'Appel',
      'uk': 'Яблуко',
    },
    'boiledEggs': {
      'ar': 'بيض مسلوق',
      'en': 'Boiled eggs',
      'fr': 'Œufs durs',
      'es': 'Huevos cocidos',
      'tr': 'Haşlanmış yumurta',
      'de': 'Gekochte Eier',
      'it': 'Uova sode',
      'pt-BR': 'Ovos cozidos',
      'pt-PT': 'Ovos cozidos',
      'ur': 'ابلے ہوئے انڈے',
      'fa': 'تخم‌مرغ آب‌پز',
      'hi': 'उबले अंडे',
      'id': 'Telur rebus',
      'ms': 'Telur rebus',
      'ja': 'ゆで卵',
      'ko': '삶은 달걀',
      'zh-Hans': '水煮蛋',
      'zh-Hant': '水煮蛋',
      'ru': 'Варёные яйца',
      'bn': 'সেদ্ধ ডিম',
      'vi': 'Trứng luộc',
      'th': 'ไข่ต้ม',
      'pl': 'Jajka gotowane',
      'nl': 'Gekookte eieren',
      'uk': 'Варені яйця',
    },
    'eggs': {
      'ar': 'بيض',
      'en': 'Eggs',
      'fr': 'Œufs',
      'es': 'Huevos',
      'tr': 'Yumurta',
      'de': 'Eier',
      'it': 'Uova',
      'pt-BR': 'Ovos',
      'pt-PT': 'Ovos',
      'ur': 'انڈے',
      'fa': 'تخم‌مرغ',
      'hi': 'अंडे',
      'id': 'Telur',
      'ms': 'Telur',
      'ja': '卵',
      'ko': '달걀',
      'zh-Hans': '鸡蛋',
      'zh-Hant': '雞蛋',
      'ru': 'Яйца',
      'bn': 'ডিম',
      'vi': 'Trứng',
      'th': 'ไข่',
      'pl': 'Jajka',
      'nl': 'Eieren',
      'uk': 'Яйця',
    },
    'chickenBreast': {
      'ar': 'صدر دجاج',
      'en': 'Chicken breast',
      'fr': 'Blanc de poulet',
      'es': 'Pechuga de pollo',
      'tr': 'Tavuk göğsü',
      'de': 'Hähnchenbrust',
      'it': 'Petto di pollo',
      'pt-BR': 'Peito de frango',
      'pt-PT': 'Peito de frango',
      'ur': 'مرغی کا سینہ',
      'fa': 'سینه مرغ',
      'hi': 'चिकन ब्रेस्ट',
      'id': 'Dada ayam',
      'ms': 'Dada ayam',
      'ja': '鶏むね肉',
      'ko': '닭가슴살',
      'zh-Hans': '鸡胸肉',
      'zh-Hant': '雞胸肉',
      'ru': 'Куриная грудка',
      'bn': 'মুরগির বুকের মাংস',
      'vi': 'Ức gà',
      'th': 'อกไก่',
      'pl': 'Pierś z kurczaka',
      'nl': 'Kipfilet',
      'uk': 'Куряча грудка',
    },
  };

  static const _foodLocaleOrder = <String>[
    'ar',
    'en',
    'fr',
    'es',
    'tr',
    'de',
    'it',
    'pt-BR',
    'pt-PT',
    'ur',
    'fa',
    'hi',
    'id',
    'ms',
    'ja',
    'ko',
    'zh-Hans',
    'zh-Hant',
    'ru',
    'bn',
    'vi',
    'th',
    'pl',
    'nl',
    'uk',
  ];

  /// Reviewed primary identities for common whole foods. Detailed USDA
  /// descriptors remain authoritative in storage, while search rows use the
  /// localized primary identity instead of leaking an English paragraph into
  /// a non-English interface.
  static const _coreFoodNames = <String, List<String>>{
    'banana': [
      'موز',
      'Banana',
      'Banane',
      'Plátano',
      'Muz',
      'Banane',
      'Banana',
      'Banana',
      'Banana',
      'کیلا',
      'موز',
      'केला',
      'Pisang',
      'Pisang',
      'バナナ',
      '바나나',
      '香蕉',
      '香蕉',
      'Банан',
      'কলা',
      'Chuối',
      'กล้วย',
      'Banan',
      'Banaan',
      'Банан',
    ],
    'orange': [
      'برتقال',
      'Orange',
      'Orange',
      'Naranja',
      'Portakal',
      'Orange',
      'Arancia',
      'Laranja',
      'Laranja',
      'سنگترہ',
      'پرتقال',
      'संतरा',
      'Jeruk',
      'Oren',
      'オレンジ',
      '오렌지',
      '橙子',
      '橙子',
      'Апельсин',
      'কমলা',
      'Cam',
      'ส้ม',
      'Pomarańcza',
      'Sinaasappel',
      'Апельсин',
    ],
    'chicken': [
      'دجاج',
      'Chicken',
      'Poulet',
      'Pollo',
      'Tavuk',
      'Hähnchen',
      'Pollo',
      'Frango',
      'Frango',
      'مرغی',
      'مرغ',
      'चिकन',
      'Ayam',
      'Ayam',
      '鶏肉',
      '닭고기',
      '鸡肉',
      '雞肉',
      'Курица',
      'মুরগি',
      'Gà',
      'ไก่',
      'Kurczak',
      'Kip',
      'Курка',
    ],
    'beef': [
      'لحم بقري',
      'Beef',
      'Bœuf',
      'Carne de res',
      'Sığır eti',
      'Rindfleisch',
      'Manzo',
      'Carne bovina',
      'Carne de vaca',
      'گائے کا گوشت',
      'گوشت گاو',
      'गोमांस',
      'Daging sapi',
      'Daging lembu',
      '牛肉',
      '소고기',
      '牛肉',
      '牛肉',
      'Говядина',
      'গরুর মাংস',
      'Thịt bò',
      'เนื้อวัว',
      'Wołowina',
      'Rundvlees',
      'Яловичина',
    ],
    'fish': [
      'سمك',
      'Fish',
      'Poisson',
      'Pescado',
      'Balık',
      'Fisch',
      'Pesce',
      'Peixe',
      'Peixe',
      'مچھلی',
      'ماهی',
      'मछली',
      'Ikan',
      'Ikan',
      '魚',
      '생선',
      '鱼',
      '魚',
      'Рыба',
      'মাছ',
      'Cá',
      'ปลา',
      'Ryba',
      'Vis',
      'Риба',
    ],
    'rice': [
      'أرز',
      'Rice',
      'Riz',
      'Arroz',
      'Pirinç',
      'Reis',
      'Riso',
      'Arroz',
      'Arroz',
      'چاول',
      'برنج',
      'चावल',
      'Nasi',
      'Nasi',
      'ご飯',
      '쌀',
      '米饭',
      '米飯',
      'Рис',
      'ভাত',
      'Cơm',
      'ข้าว',
      'Ryż',
      'Rijst',
      'Рис',
    ],
    'bread': [
      'خبز',
      'Bread',
      'Pain',
      'Pan',
      'Ekmek',
      'Brot',
      'Pane',
      'Pão',
      'Pão',
      'روٹی',
      'نان',
      'ब्रेड',
      'Roti',
      'Roti',
      'パン',
      '빵',
      '面包',
      '麵包',
      'Хлеб',
      'রুটি',
      'Bánh mì',
      'ขนมปัง',
      'Chleb',
      'Brood',
      'Хліб',
    ],
    'milk': [
      'حليب',
      'Milk',
      'Lait',
      'Leche',
      'Süt',
      'Milch',
      'Latte',
      'Leite',
      'Leite',
      'دودھ',
      'شیر',
      'दूध',
      'Susu',
      'Susu',
      '牛乳',
      '우유',
      '牛奶',
      '牛奶',
      'Молоко',
      'দুধ',
      'Sữa',
      'นม',
      'Mleko',
      'Melk',
      'Молоко',
    ],
    'yogurt': [
      'زبادي',
      'Yogurt',
      'Yaourt',
      'Yogur',
      'Yoğurt',
      'Joghurt',
      'Yogurt',
      'Iogurte',
      'Iogurte',
      'دہی',
      'ماست',
      'दही',
      'Yoghurt',
      'Yogurt',
      'ヨーグルト',
      '요거트',
      '酸奶',
      '優格',
      'Йогурт',
      'দই',
      'Sữa chua',
      'โยเกิร์ต',
      'Jogurt',
      'Yoghurt',
      'Йогурт',
    ],
    'cheese': [
      'جبن',
      'Cheese',
      'Fromage',
      'Queso',
      'Peynir',
      'Käse',
      'Formaggio',
      'Queijo',
      'Queijo',
      'پنیر',
      'پنیر',
      'पनीर',
      'Keju',
      'Keju',
      'チーズ',
      '치즈',
      '奶酪',
      '起司',
      'Сыр',
      'পনির',
      'Phô mai',
      'ชีส',
      'Ser',
      'Kaas',
      'Сир',
    ],
    'potato': [
      'بطاطس',
      'Potato',
      'Pomme de terre',
      'Patata',
      'Patates',
      'Kartoffel',
      'Patata',
      'Batata',
      'Batata',
      'آلو',
      'سیب‌زمینی',
      'आलू',
      'Kentang',
      'Kentang',
      'じゃがいも',
      '감자',
      '土豆',
      '馬鈴薯',
      'Картофель',
      'আলু',
      'Khoai tây',
      'มันฝรั่ง',
      'Ziemniak',
      'Aardappel',
      'Картопля',
    ],
    'tomato': [
      'طماطم',
      'Tomato',
      'Tomate',
      'Tomate',
      'Domates',
      'Tomate',
      'Pomodoro',
      'Tomate',
      'Tomate',
      'ٹماٹر',
      'گوجه‌فرنگی',
      'टमाटर',
      'Tomat',
      'Tomato',
      'トマト',
      '토마토',
      '番茄',
      '番茄',
      'Помидор',
      'টমেটো',
      'Cà chua',
      'มะเขือเทศ',
      'Pomidor',
      'Tomaat',
      'Помідор',
    ],
    'cucumber': [
      'خيار',
      'Cucumber',
      'Concombre',
      'Pepino',
      'Salatalık',
      'Gurke',
      'Cetriolo',
      'Pepino',
      'Pepino',
      'کھیرا',
      'خیار',
      'खीरा',
      'Mentimun',
      'Timun',
      'きゅうり',
      '오이',
      '黄瓜',
      '小黃瓜',
      'Огурец',
      'শসা',
      'Dưa chuột',
      'แตงกวา',
      'Ogórek',
      'Komkommer',
      'Огірок',
    ],
    'oats': [
      'شوفان',
      'Oats',
      'Avoine',
      'Avena',
      'Yulaf',
      'Hafer',
      'Avena',
      'Aveia',
      'Aveia',
      'جئی',
      'جو دوسر',
      'जई',
      'Oat',
      'Oat',
      'オート麦',
      '귀리',
      '燕麦',
      '燕麥',
      'Овёс',
      'ওটস',
      'Yến mạch',
      'ข้าวโอ๊ต',
      'Owies',
      'Haver',
      'Овес',
    ],
    'salmon': [
      'سلمون',
      'Salmon',
      'Saumon',
      'Salmón',
      'Somon',
      'Lachs',
      'Salmone',
      'Salmão',
      'Salmão',
      'سالمن',
      'ماهی سالمون',
      'सैल्मन',
      'Salmon',
      'Salmon',
      'サーモン',
      '연어',
      '三文鱼',
      '鮭魚',
      'Лосось',
      'স্যামন',
      'Cá hồi',
      'ปลาแซลมอน',
      'Łosoś',
      'Zalm',
      'Лосось',
    ],
    'tuna': [
      'تونة',
      'Tuna',
      'Thon',
      'Atún',
      'Ton balığı',
      'Thunfisch',
      'Tonno',
      'Atum',
      'Atum',
      'ٹونا',
      'تن ماهی',
      'टूना',
      'Tuna',
      'Tuna',
      'マグロ',
      '참치',
      '金枪鱼',
      '鮪魚',
      'Тунец',
      'টুনা',
      'Cá ngừ',
      'ปลาทูน่า',
      'Tuńczyk',
      'Tonijn',
      'Тунець',
    ],
    'lentils': [
      'عدس',
      'Lentils',
      'Lentilles',
      'Lentejas',
      'Mercimek',
      'Linsen',
      'Lenticchie',
      'Lentilhas',
      'Lentilhas',
      'دال',
      'عدس',
      'मसूर',
      'Lentil',
      'Lentil',
      'レンズ豆',
      '렌틸콩',
      '扁豆',
      '扁豆',
      'Чечевица',
      'মসুর ডাল',
      'Đậu lăng',
      'ถั่วเลนทิล',
      'Soczewica',
      'Linzen',
      'Сочевиця',
    ],
    'beans': [
      'فاصوليا',
      'Beans',
      'Haricots',
      'Frijoles',
      'Fasulye',
      'Bohnen',
      'Fagioli',
      'Feijão',
      'Feijão',
      'لوبیا',
      'لوبیا',
      'बीन्स',
      'Kacang',
      'Kacang',
      '豆',
      '콩',
      '豆类',
      '豆類',
      'Фасоль',
      'শিম',
      'Đậu',
      'ถั่ว',
      'Fasola',
      'Bonen',
      'Квасоля',
    ],
    'water': [
      'ماء',
      'Water',
      'Eau',
      'Agua',
      'Su',
      'Wasser',
      'Acqua',
      'Água',
      'Água',
      'پانی',
      'آب',
      'पानी',
      'Air',
      'Air',
      '水',
      '물',
      '水',
      '水',
      'Вода',
      'পানি',
      'Nước',
      'น้ำ',
      'Woda',
      'Water',
      'Вода',
    ],
    'coffee': [
      'قهوة',
      'Coffee',
      'Café',
      'Café',
      'Kahve',
      'Kaffee',
      'Caffè',
      'Café',
      'Café',
      'کافی',
      'قهوه',
      'कॉफ़ी',
      'Kopi',
      'Kopi',
      'コーヒー',
      '커피',
      '咖啡',
      '咖啡',
      'Кофе',
      'কফি',
      'Cà phê',
      'กาแฟ',
      'Kawa',
      'Koffie',
      'Кава',
    ],
    'tea': [
      'شاي',
      'Tea',
      'Thé',
      'Té',
      'Çay',
      'Tee',
      'Tè',
      'Chá',
      'Chá',
      'چائے',
      'چای',
      'चाय',
      'Teh',
      'Teh',
      'お茶',
      '차',
      '茶',
      '茶',
      'Чай',
      'চা',
      'Trà',
      'ชา',
      'Herbata',
      'Thee',
      'Чай',
    ],
  };

  static final _units = <String, Map<String, String>>{
    'g': {
      'ar': 'جم',
      'en': 'g',
      'fr': 'g',
      'es': 'g',
      'tr': 'g',
      'de': 'g',
      'it': 'g',
      'pt-BR': 'g',
      'pt-PT': 'g',
      'ur': 'گرام',
      'fa': 'گرم',
      'hi': 'ग्राम',
      'id': 'g',
      'ms': 'g',
      'ja': 'g',
      'ko': 'g',
      'zh-Hans': '克',
      'zh-Hant': '克',
      'ru': 'г',
      'bn': 'গ্রাম',
      'vi': 'g',
      'th': 'กรัม',
      'pl': 'g',
      'nl': 'g',
      'uk': 'г',
    },
    'mg': {
      'ar': 'مجم',
      'en': 'mg',
      'fr': 'mg',
      'es': 'mg',
      'tr': 'mg',
      'de': 'mg',
      'it': 'mg',
      'pt-BR': 'mg',
      'pt-PT': 'mg',
      'ur': 'ملی گرام',
      'fa': 'میلی‌گرم',
      'hi': 'मि.ग्रा.',
      'id': 'mg',
      'ms': 'mg',
      'ja': 'mg',
      'ko': 'mg',
      'zh-Hans': '毫克',
      'zh-Hant': '毫克',
      'ru': 'мг',
      'bn': 'মি.গ্রা.',
      'vi': 'mg',
      'th': 'มก.',
      'pl': 'mg',
      'nl': 'mg',
      'uk': 'мг',
    },
    'ml': {
      'ar': 'مل',
      'en': 'ml',
      'fr': 'ml',
      'es': 'ml',
      'tr': 'ml',
      'de': 'ml',
      'it': 'ml',
      'pt-BR': 'ml',
      'pt-PT': 'ml',
      'ur': 'ملی لیٹر',
      'fa': 'میلی‌لیتر',
      'hi': 'मि.ली.',
      'id': 'ml',
      'ms': 'ml',
      'ja': 'ml',
      'ko': 'ml',
      'zh-Hans': '毫升',
      'zh-Hant': '毫升',
      'ru': 'мл',
      'bn': 'মি.লি.',
      'vi': 'ml',
      'th': 'มล.',
      'pl': 'ml',
      'nl': 'ml',
      'uk': 'мл',
    },
    'kcal': {
      'ar': 'سعرة',
      'en': 'kcal',
      'fr': 'kcal',
      'es': 'kcal',
      'tr': 'kcal',
      'de': 'kcal',
      'it': 'kcal',
      'pt-BR': 'kcal',
      'pt-PT': 'kcal',
      'ur': 'کیلوری',
      'fa': 'کیلوکالری',
      'hi': 'किलो कैलोरी',
      'id': 'kkal',
      'ms': 'kkal',
      'ja': 'kcal',
      'ko': 'kcal',
      'zh-Hans': '千卡',
      'zh-Hant': '千卡',
      'ru': 'ккал',
      'bn': 'কিলোক্যালরি',
      'vi': 'kcal',
      'th': 'กิโลแคลอรี',
      'pl': 'kcal',
      'nl': 'kcal',
      'uk': 'ккал',
    },
    'piece': {
      'ar': 'قطعة',
      'en': 'piece',
      'fr': 'pièce',
      'es': 'pieza',
      'tr': 'adet',
      'de': 'Stück',
      'it': 'pezzo',
      'pt-BR': 'unidade',
      'pt-PT': 'unidade',
      'ur': 'ٹکڑا',
      'fa': 'عدد',
      'hi': 'टुकड़ा',
      'id': 'buah',
      'ms': 'keping',
      'ja': '個',
      'ko': '개',
      'zh-Hans': '个',
      'zh-Hant': '個',
      'ru': 'шт.',
      'bn': 'টি',
      'vi': 'miếng',
      'th': 'ชิ้น',
      'pl': 'szt.',
      'nl': 'stuk',
      'uk': 'шт.',
    },
    'serving': {
      'ar': 'حصة',
      'en': 'serving',
      'fr': 'portion',
      'es': 'porción',
      'tr': 'porsiyon',
      'de': 'Portion',
      'it': 'porzione',
      'pt-BR': 'porção',
      'pt-PT': 'porção',
      'ur': 'حصہ',
      'fa': 'وعده',
      'hi': 'परोस',
      'id': 'porsi',
      'ms': 'hidangan',
      'ja': '食分',
      'ko': '회분',
      'zh-Hans': '份',
      'zh-Hant': '份',
      'ru': 'порция',
      'bn': 'পরিবেশন',
      'vi': 'khẩu phần',
      'th': 'หน่วยบริโภค',
      'pl': 'porcja',
      'nl': 'portie',
      'uk': 'порція',
    },
    'oz': {
      'ar': 'أونصة',
      'en': 'oz',
      'fr': 'oz',
      'es': 'oz',
      'tr': 'ons',
      'de': 'oz',
      'it': 'oz',
      'pt-BR': 'oz',
      'pt-PT': 'oz',
      'ur': 'اونس',
      'fa': 'اونس',
      'hi': 'औंस',
      'id': 'ons',
      'ms': 'auns',
      'ja': 'オンス',
      'ko': '온스',
      'zh-Hans': '盎司',
      'zh-Hant': '盎司',
      'ru': 'унц.',
      'bn': 'আউন্স',
      'vi': 'oz',
      'th': 'ออนซ์',
      'pl': 'oz',
      'nl': 'oz',
      'uk': 'унц.',
    },
    'kg': {
      for (final locale in supportedLocaleTags) locale: 'kg',
      'ar': 'كجم',
      'ur': 'کلوگرام',
      'fa': 'کیلوگرم',
      'hi': 'किग्रा',
      'ja': 'kg',
      'ko': 'kg',
      'zh-Hans': '千克',
      'zh-Hant': '公斤',
      'ru': 'кг',
      'bn': 'কেজি',
      'th': 'กก.',
      'uk': 'кг',
    },
    'lb': {
      for (final locale in supportedLocaleTags) locale: 'lb',
      'ar': 'رطل',
      'ur': 'پاؤنڈ',
      'fa': 'پوند',
      'hi': 'पाउंड',
      'id': 'pon',
      'ms': 'paun',
      'ja': 'ポンド',
      'ko': '파운드',
      'zh-Hans': '磅',
      'zh-Hant': '磅',
      'ru': 'фунт',
      'bn': 'পাউন্ড',
      'th': 'ปอนด์',
      'uk': 'фунт',
    },
    'unavailable': {
      'ar': 'الحصة غير متاحة',
      'en': 'Serving unavailable',
      'fr': 'Portion indisponible',
      'es': 'Porción no disponible',
      'tr': 'Porsiyon bilgisi yok',
      'de': 'Portionsangabe nicht verfügbar',
      'it': 'Porzione non disponibile',
      'pt-BR': 'Porção indisponível',
      'pt-PT': 'Porção indisponível',
      'ur': 'سرونگ کی معلومات دستیاب نہیں',
      'fa': 'اطلاعات وعده در دسترس نیست',
      'hi': 'सर्विंग की जानकारी उपलब्ध नहीं है',
      'id': 'Porsi tidak tersedia',
      'ms': 'Hidangan tidak tersedia',
      'ja': '1食分の情報はありません',
      'ko': '1회 제공량 정보 없음',
      'zh-Hans': '份量信息不可用',
      'zh-Hant': '份量資訊無法使用',
      'ru': 'Данные о порции недоступны',
      'bn': 'পরিবেশনের তথ্য পাওয়া যায়নি',
      'vi': 'Không có thông tin khẩu phần',
      'th': 'ไม่มีข้อมูลหน่วยบริโภค',
      'pl': 'Brak informacji o porcji',
      'nl': 'Portie niet beschikbaar',
      'uk': 'Дані про порцію недоступні',
    },
  };

  static const _labels = <String, Map<String, String>>{
    'nutritionFacts': {
      'ar': 'حقائق التغذية',
      'en': 'Nutrition Facts',
      'fr': 'Valeurs nutritionnelles',
      'es': 'Información nutricional',
      'tr': 'Besin değerleri',
      'de': 'Nährwertangaben',
      'it': 'Valori nutrizionali',
      'pt-BR': 'Informações nutricionais',
      'pt-PT': 'Informação nutricional',
      'ur': 'غذائی حقائق',
      'fa': 'اطلاعات تغذیه‌ای',
      'hi': 'पोषण तथ्य',
      'id': 'Informasi gizi',
      'ms': 'Maklumat pemakanan',
      'ja': '栄養成分',
      'ko': '영양 정보',
      'zh-Hans': '营养成分',
      'zh-Hant': '營養成分',
      'ru': 'Пищевая ценность',
      'bn': 'পুষ্টি তথ্য',
      'vi': 'Thông tin dinh dưỡng',
      'th': 'ข้อมูลโภชนาการ',
      'pl': 'Wartości odżywcze',
      'nl': 'Voedingswaarden',
      'uk': 'Харчова цінність',
    },
    'noAdditionalNutrients': {
      'ar': 'لا تتوفر بيانات إضافية عن العناصر الغذائية.',
      'en': 'No additional nutrient data available.',
      'fr': 'Aucune donnée nutritionnelle supplémentaire.',
      'es': 'No hay datos nutricionales adicionales disponibles.',
      'tr': 'Ek besin verisi yok.',
      'de': 'Keine zusätzlichen Nährwertdaten verfügbar.',
      'it': 'Non sono disponibili altri dati nutrizionali.',
      'pt-BR': 'Não há dados nutricionais adicionais disponíveis.',
      'pt-PT': 'Não existem dados nutricionais adicionais.',
      'ur': 'اضافی غذائی معلومات دستیاب نہیں۔',
      'fa': 'داده تغذیه‌ای بیشتری موجود نیست.',
      'hi': 'कोई अतिरिक्त पोषक डेटा उपलब्ध नहीं है।',
      'id': 'Tidak ada data gizi tambahan.',
      'ms': 'Tiada data pemakanan tambahan.',
      'ja': '追加の栄養データはありません。',
      'ko': '추가 영양 데이터가 없습니다.',
      'zh-Hans': '暂无其他营养数据。',
      'zh-Hant': '沒有其他營養資料。',
      'ru': 'Дополнительные данные о питании недоступны.',
      'bn': 'অতিরিক্ত পুষ্টির তথ্য পাওয়া যায়নি।',
      'vi': 'Không có dữ liệu dinh dưỡng bổ sung.',
      'th': 'ไม่มีข้อมูลโภชนาการเพิ่มเติม',
      'pl': 'Brak dodatkowych danych o wartościach odżywczych.',
      'nl': 'Geen aanvullende voedingsgegevens beschikbaar.',
      'uk': 'Додаткові дані про харчування недоступні.',
    },
  };
}
