import 'food_search_normalizer.dart';

/// Small, reviewed offline bridge between the app's supported writing systems
/// and the English USDA catalog. It is deliberately a food lexicon rather than
/// a UI-locale switch: users may search in any language regardless of the
/// interface language.
class FoodMultilingualLexicon {
  const FoodMultilingualLexicon._();

  static final Map<String, List<String>> _byAlias = _buildAliasIndex();

  static List<String> expand(String query) {
    final normalized = FoodSearchNormalizer.normalize(query);
    if (normalized.isEmpty) return const <String>[];

    final result = <String>{normalized};
    result.addAll(_byAlias[normalized] ?? const <String>[]);

    final translatedTokens = <String>[];
    var changed = false;
    for (final token in normalized.split(' ')) {
      final canonical = _byAlias[token]?.firstOrNull;
      translatedTokens.add(canonical ?? token);
      changed |= canonical != null;
    }
    if (changed) result.add(translatedTokens.join(' '));
    return result.toList(growable: false);
  }

  static Map<String, List<String>> _buildAliasIndex() {
    final index = <String, List<String>>{};
    for (final entry in _aliasesByCanonical.entries) {
      for (final rawAlias in <String>[entry.key, ...entry.value]) {
        final alias = FoodSearchNormalizer.normalize(rawAlias);
        if (alias.isEmpty || alias == entry.key) continue;
        final values = index.putIfAbsent(alias, () => <String>[]);
        if (!values.contains(entry.key)) values.add(entry.key);
      }
    }
    return Map<String, List<String>>.unmodifiable(
      index.map(
        (key, value) => MapEntry(key, List<String>.unmodifiable(value)),
      ),
    );
  }

  // ar, fr, es, tr, de, it, pt, ur, fa, hi, id/ms, ja, ko, zh,
  // ru, bn, vi, th, pl, nl and uk aliases are kept together by concept.
  static const Map<String, List<String>> _aliasesByCanonical = {
    'apple': [
      'تفاح',
      'تفاحة',
      'pomme',
      'manzana',
      'elma',
      'apfel',
      'mela',
      'maçã',
      'سیب',
      'सेब',
      'apel',
      'epal',
      'りんご',
      'リンゴ',
      '사과',
      '苹果',
      '蘋果',
      'яблоко',
      'আপেল',
      'táo',
      'แอปเปิล',
      'jabłko',
      'appel',
      'яблуко',
    ],
    'banana': [
      'موز',
      'banane',
      'plátano',
      'banana',
      'muz',
      'banane',
      'موز',
      'केला',
      'pisang',
      'バナナ',
      '바나나',
      '香蕉',
      'банан',
      'কলা',
      'chuối',
      'กล้วย',
      'banan',
      'banaan',
      'банан',
    ],
    'orange': [
      'برتقال',
      'orange',
      'naranja',
      'portakal',
      'orange',
      'arancia',
      'laranja',
      'سنگترہ',
      'پرتقال',
      'संतरा',
      'jeruk',
      'オレンジ',
      '오렌지',
      '橙子',
      'апельсин',
      'কমলা',
      'cam',
      'ส้ม',
      'pomarańcza',
      'sinaasappel',
      'апельсин',
    ],
    'chicken': [
      'دجاج',
      'فروج',
      'poulet',
      'pollo',
      'tavuk',
      'hähnchen',
      'pollo',
      'frango',
      'مرغی',
      'مرغ',
      'चिकन',
      'ayam',
      '鶏肉',
      '닭고기',
      '鸡肉',
      'курица',
      'মুরগি',
      'gà',
      'ไก่',
      'kurczak',
      'kip',
      'курка',
    ],
    'beef': [
      'لحم بقري',
      'bœuf',
      'boeuf',
      'carne de res',
      'sığır eti',
      'rindfleisch',
      'manzo',
      'carne bovina',
      'گائے کا گوشت',
      'گوشت گاو',
      'गोमांस',
      'daging sapi',
      'daging lembu',
      '牛肉',
      '소고기',
      'говядина',
      'গরুর মাংস',
      'thịt bò',
      'เนื้อวัว',
      'wołowina',
      'rundvlees',
      'яловичина',
    ],
    'fish': [
      'سمك',
      'poisson',
      'pescado',
      'balık',
      'fisch',
      'pesce',
      'peixe',
      'مچھلی',
      'ماهی',
      'मछली',
      'ikan',
      '魚',
      '鱼',
      '생선',
      'рыба',
      'মাছ',
      'cá',
      'ปลา',
      'ryba',
      'vis',
      'риба',
    ],
    'rice': [
      'أرز',
      'ارز',
      'رز',
      'riz',
      'arroz',
      'pirinç',
      'reis',
      'riso',
      'چاول',
      'برنج',
      'चावल',
      'nasi',
      'beras',
      '米',
      'ご飯',
      '쌀',
      'рис',
      'ভাত',
      'চাল',
      'cơm',
      'gạo',
      'ข้าว',
      'ryż',
      'rijst',
      'рис',
    ],
    'bread': [
      'خبز',
      'pain',
      'pan',
      'ekmek',
      'brot',
      'pane',
      'pão',
      'روٹی',
      'نان',
      'रोटी',
      'ब्रेड',
      'roti',
      'パン',
      '빵',
      '面包',
      '麵包',
      'хлеб',
      'রুটি',
      'bánh mì',
      'ขนมปัง',
      'chleb',
      'brood',
      'хліб',
    ],
    'egg': [
      'بيض',
      'بيضة',
      'œuf',
      'oeuf',
      'huevo',
      'yumurta',
      'ei',
      'uovo',
      'ovo',
      'انڈا',
      'تخم مرغ',
      'अंडा',
      'telur',
      '卵',
      'たまご',
      '계란',
      '鸡蛋',
      'яйцо',
      'ডিম',
      'trứng',
      'ไข่',
      'jajko',
      'яйце',
    ],
    'milk': [
      'حليب',
      'lait',
      'leche',
      'süt',
      'milch',
      'latte',
      'leite',
      'دودھ',
      'شیر',
      'दूध',
      'susu',
      '牛乳',
      '우유',
      '牛奶',
      'молоко',
      'দুধ',
      'sữa',
      'นม',
      'mleko',
      'melk',
      'молоко',
    ],
    'yogurt': [
      'زبادي',
      'لبن',
      'yaourt',
      'yogourt',
      'yogur',
      'yoğurt',
      'joghurt',
      'yogurt',
      'iogurte',
      'دہی',
      'ماست',
      'दही',
      'yoghurt',
      'ヨーグルト',
      '요거트',
      '酸奶',
      '優格',
      'йогурт',
      'দই',
      'sữa chua',
      'โยเกิร์ต',
      'jogurt',
      'йогурт',
    ],
    'cheese': [
      'جبن',
      'جبنة',
      'fromage',
      'queso',
      'peynir',
      'käse',
      'formaggio',
      'queijo',
      'پنیر',
      'पनीर',
      'keju',
      'チーズ',
      '치즈',
      '奶酪',
      'сыр',
      'পনির',
      'phô mai',
      'ชีส',
      'ser',
      'kaas',
      'сир',
    ],
    'potato': [
      'بطاطا',
      'بطاطس',
      'pomme de terre',
      'patata',
      'papa',
      'patates',
      'kartoffel',
      'batata',
      'آلو',
      'سیب زمینی',
      'आलू',
      'kentang',
      'じゃがいも',
      '감자',
      '土豆',
      '马铃薯',
      'картофель',
      'আলু',
      'khoai tây',
      'มันฝรั่ง',
      'ziemniak',
      'aardappel',
      'картопля',
    ],
    'tomato': [
      'طماطم',
      'بندورة',
      'tomate',
      'domates',
      'tomate',
      'pomodoro',
      'ٹماٹر',
      'گوجه فرنگی',
      'टमाटर',
      'tomat',
      'トマト',
      '토마토',
      '番茄',
      'помидор',
      'টমেটো',
      'cà chua',
      'มะเขือเทศ',
      'pomidor',
      'tomaat',
      'помідор',
    ],
    'cucumber': [
      'خيار',
      'concombre',
      'pepino',
      'salatalık',
      'gurke',
      'cetriolo',
      'pepino',
      'کھیرا',
      'خیار',
      'खीरा',
      'timun',
      'きゅうり',
      '오이',
      '黄瓜',
      'огурец',
      'শসা',
      'dưa chuột',
      'แตงกวา',
      'ogórek',
      'komkommer',
      'огірок',
    ],
    'oats': [
      'شوفان',
      'avoine',
      'avena',
      'yulaf',
      'hafer',
      'aveia',
      'جئی',
      'جو دوسر',
      'जई',
      'oat',
      'オーツ麦',
      '귀리',
      '燕麦',
      'овёс',
      'ওটস',
      'yến mạch',
      'ข้าวโอ๊ต',
      'owies',
      'haver',
      'овес',
    ],
    'salmon': [
      'سلمون',
      'saumon',
      'salmón',
      'somon',
      'lachs',
      'salmone',
      'salmão',
      'سالمن',
      'सैल्मन',
      'salmon',
      'サーモン',
      '연어',
      '三文鱼',
      'лосось',
      'স্যামন',
      'cá hồi',
      'ปลาแซลมอน',
      'łosoś',
      'zalm',
      'лосось',
    ],
    'tuna': [
      'تونة',
      'thon',
      'atún',
      'ton balığı',
      'thunfisch',
      'tonno',
      'atum',
      'ٹونا',
      'تن ماهی',
      'टूना',
      'tuna',
      'マグロ',
      '참치',
      '金枪鱼',
      'тунец',
      'টুনা',
      'cá ngừ',
      'ปลาทูน่า',
      'tuńczyk',
      'tonijn',
      'тунець',
    ],
    'lentil': [
      'عدس',
      'lentille',
      'lenteja',
      'mercimek',
      'linse',
      'lenticchia',
      'lentilha',
      'دال',
      'عدس',
      'मसूर',
      'lentil',
      'レンティル',
      '렌틸콩',
      '扁豆',
      'чечевица',
      'মসুর',
      'đậu lăng',
      'ถั่วเลนทิล',
      'soczewica',
      'linzen',
      'сочевиця',
    ],
    'beans': [
      'فاصوليا',
      'haricots',
      'frijoles',
      'fasulye',
      'bohnen',
      'fagioli',
      'feijão',
      'لوبیا',
      'सेम',
      'kacang',
      '豆',
      '콩',
      'фасоль',
      'শিম',
      'đậu',
      'ถั่ว',
      'fasola',
      'bonen',
      'квасоля',
    ],
    'water': [
      'ماء',
      'eau',
      'agua',
      'su',
      'wasser',
      'acqua',
      'água',
      'پانی',
      'آب',
      'पानी',
      'air',
      '水',
      '물',
      'вода',
      'পানি',
      'nước',
      'น้ำ',
      'woda',
      'water',
      'вода',
    ],
    'coffee': [
      'قهوة',
      'café',
      'cafe',
      'kahve',
      'kaffee',
      'caffè',
      'café',
      'کافی',
      'قهوه',
      'कॉफी',
      'kopi',
      'コーヒー',
      '커피',
      '咖啡',
      'кофе',
      'কফি',
      'cà phê',
      'กาแฟ',
      'kawa',
      'koffie',
      'кава',
    ],
    'tea': [
      'شاي',
      'thé',
      'té',
      'çay',
      'tee',
      'tè',
      'chá',
      'چائے',
      'چای',
      'चाय',
      'teh',
      'お茶',
      '차',
      '茶',
      'чай',
      'চা',
      'trà',
      'ชา',
      'herbata',
      'thee',
      'чай',
    ],
  };
}

extension<T> on List<T> {
  T? get firstOrNull => isEmpty ? null : first;
}
