part of 'food_presentation_localizer.dart';

final _units = <String, Map<String, String>>{
  'g': {
    'ar': 'جم',
    'en': 'g',
    'fr': 'g',
    'es': 'g',
    'tr': 'g',
    'de': 'g',
    'it': 'g',
    'pt-BR': 'g',
    'pt-PT': 'g',
    'ur': 'گرام',
    'fa': 'گرم',
    'hi': 'ग्राम',
    'id': 'g',
    'ms': 'g',
    'ja': 'g',
    'ko': 'g',
    'zh-Hans': '克',
    'zh-Hant': '克',
    'ru': 'г',
    'bn': 'গ্রাম',
    'vi': 'g',
    'th': 'กรัม',
    'pl': 'g',
    'nl': 'g',
    'uk': 'г',
  },
  'mg': {
    'ar': 'مجم',
    'en': 'mg',
    'fr': 'mg',
    'es': 'mg',
    'tr': 'mg',
    'de': 'mg',
    'it': 'mg',
    'pt-BR': 'mg',
    'pt-PT': 'mg',
    'ur': 'ملی گرام',
    'fa': 'میلی‌گرم',
    'hi': 'मि.ग्रा.',
    'id': 'mg',
    'ms': 'mg',
    'ja': 'mg',
    'ko': 'mg',
    'zh-Hans': '毫克',
    'zh-Hant': '毫克',
    'ru': 'мг',
    'bn': 'মি.গ্রা.',
    'vi': 'mg',
    'th': 'มก.',
    'pl': 'mg',
    'nl': 'mg',
    'uk': 'мг',
  },
  'ml': {
    'ar': 'مل',
    'en': 'ml',
    'fr': 'ml',
    'es': 'ml',
    'tr': 'ml',
    'de': 'ml',
    'it': 'ml',
    'pt-BR': 'ml',
    'pt-PT': 'ml',
    'ur': 'ملی لیٹر',
    'fa': 'میلی‌لیتر',
    'hi': 'मि.ली.',
    'id': 'ml',
    'ms': 'ml',
    'ja': 'ml',
    'ko': 'ml',
    'zh-Hans': '毫升',
    'zh-Hant': '毫升',
    'ru': 'мл',
    'bn': 'মি.লি.',
    'vi': 'ml',
    'th': 'มล.',
    'pl': 'ml',
    'nl': 'ml',
    'uk': 'мл',
  },
  'kcal': {
    'ar': 'سعرة',
    'en': 'kcal',
    'fr': 'kcal',
    'es': 'kcal',
    'tr': 'kcal',
    'de': 'kcal',
    'it': 'kcal',
    'pt-BR': 'kcal',
    'pt-PT': 'kcal',
    'ur': 'کیلوری',
    'fa': 'کیلوکالری',
    'hi': 'किलो कैलोरी',
    'id': 'kkal',
    'ms': 'kkal',
    'ja': 'kcal',
    'ko': 'kcal',
    'zh-Hans': '千卡',
    'zh-Hant': '千卡',
    'ru': 'ккал',
    'bn': 'কিলোক্যালরি',
    'vi': 'kcal',
    'th': 'กิโลแคลอรี',
    'pl': 'kcal',
    'nl': 'kcal',
    'uk': 'ккал',
  },
  'piece': {
    'ar': 'قطعة',
    'en': 'piece',
    'fr': 'pièce',
    'es': 'pieza',
    'tr': 'adet',
    'de': 'Stück',
    'it': 'pezzo',
    'pt-BR': 'unidade',
    'pt-PT': 'unidade',
    'ur': 'ٹکڑا',
    'fa': 'عدد',
    'hi': 'टुकड़ा',
    'id': 'buah',
    'ms': 'keping',
    'ja': '個',
    'ko': '개',
    'zh-Hans': '个',
    'zh-Hant': '個',
    'ru': 'шт.',
    'bn': 'টি',
    'vi': 'miếng',
    'th': 'ชิ้น',
    'pl': 'szt.',
    'nl': 'stuk',
    'uk': 'шт.',
  },
  'serving': {
    'ar': 'حصة',
    'en': 'serving',
    'fr': 'portion',
    'es': 'porción',
    'tr': 'porsiyon',
    'de': 'Portion',
    'it': 'porzione',
    'pt-BR': 'porção',
    'pt-PT': 'porção',
    'ur': 'حصہ',
    'fa': 'وعده',
    'hi': 'परोस',
    'id': 'porsi',
    'ms': 'hidangan',
    'ja': '食分',
    'ko': '회분',
    'zh-Hans': '份',
    'zh-Hant': '份',
    'ru': 'порция',
    'bn': 'পরিবেশন',
    'vi': 'khẩu phần',
    'th': 'หน่วยบริโภค',
    'pl': 'porcja',
    'nl': 'portie',
    'uk': 'порція',
  },
  'oz': {
    'ar': 'أونصة',
    'en': 'oz',
    'fr': 'oz',
    'es': 'oz',
    'tr': 'ons',
    'de': 'oz',
    'it': 'oz',
    'pt-BR': 'oz',
    'pt-PT': 'oz',
    'ur': 'اونس',
    'fa': 'اونس',
    'hi': 'औंस',
    'id': 'ons',
    'ms': 'auns',
    'ja': 'オンス',
    'ko': '온스',
    'zh-Hans': '盎司',
    'zh-Hant': '盎司',
    'ru': 'унц.',
    'bn': 'আউন্স',
    'vi': 'oz',
    'th': 'ออนซ์',
    'pl': 'oz',
    'nl': 'oz',
    'uk': 'унц.',
  },
  'kg': {
    for (final locale in FoodPresentationLocalizer.supportedLocaleTags)
      locale: 'kg',
    'ar': 'كجم',
    'ur': 'کلوگرام',
    'fa': 'کیلوگرم',
    'hi': 'किग्रा',
    'ja': 'kg',
    'ko': 'kg',
    'zh-Hans': '千克',
    'zh-Hant': '公斤',
    'ru': 'кг',
    'bn': 'কেজি',
    'th': 'กก.',
    'uk': 'кг',
  },
  'lb': {
    for (final locale in FoodPresentationLocalizer.supportedLocaleTags)
      locale: 'lb',
    'ar': 'رطل',
    'ur': 'پاؤنڈ',
    'fa': 'پوند',
    'hi': 'पाउंड',
    'id': 'pon',
    'ms': 'paun',
    'ja': 'ポンド',
    'ko': '파운드',
    'zh-Hans': '磅',
    'zh-Hant': '磅',
    'ru': 'фунт',
    'bn': 'পাউন্ড',
    'th': 'ปอนด์',
    'uk': 'фунт',
  },
  'unavailable': {
    'ar': 'الحصة غير متاحة',
    'en': 'Serving unavailable',
    'fr': 'Portion indisponible',
    'es': 'Porción no disponible',
    'tr': 'Porsiyon bilgisi yok',
    'de': 'Portionsangabe nicht verfügbar',
    'it': 'Porzione non disponibile',
    'pt-BR': 'Porção indisponível',
    'pt-PT': 'Porção indisponível',
    'ur': 'سرونگ کی معلومات دستیاب نہیں',
    'fa': 'اطلاعات وعده در دسترس نیست',
    'hi': 'सर्विंग की जानकारी उपलब्ध नहीं है',
    'id': 'Porsi tidak tersedia',
    'ms': 'Hidangan tidak tersedia',
    'ja': '1食分の情報はありません',
    'ko': '1회 제공량 정보 없음',
    'zh-Hans': '份量信息不可用',
    'zh-Hant': '份量資訊無法使用',
    'ru': 'Данные о порции недоступны',
    'bn': 'পরিবেশনের তথ্য পাওয়া যায়নি',
    'vi': 'Không có thông tin khẩu phần',
    'th': 'ไม่มีข้อมูลหน่วยบริโภค',
    'pl': 'Brak informacji o porcji',
    'nl': 'Portie niet beschikbaar',
    'uk': 'Дані про порцію недоступні',
  },
};

const _labels = <String, Map<String, String>>{
  'nutritionFacts': {
    'ar': 'حقائق التغذية',
    'en': 'Nutrition Facts',
    'fr': 'Valeurs nutritionnelles',
    'es': 'Información nutricional',
    'tr': 'Besin değerleri',
    'de': 'Nährwertangaben',
    'it': 'Valori nutrizionali',
    'pt-BR': 'Informações nutricionais',
    'pt-PT': 'Informação nutricional',
    'ur': 'غذائی حقائق',
    'fa': 'اطلاعات تغذیه‌ای',
    'hi': 'पोषण तथ्य',
    'id': 'Informasi gizi',
    'ms': 'Maklumat pemakanan',
    'ja': '栄養成分',
    'ko': '영양 정보',
    'zh-Hans': '营养成分',
    'zh-Hant': '營養成分',
    'ru': 'Пищевая ценность',
    'bn': 'পুষ্টি তথ্য',
    'vi': 'Thông tin dinh dưỡng',
    'th': 'ข้อมูลโภชนาการ',
    'pl': 'Wartości odżywcze',
    'nl': 'Voedingswaarden',
    'uk': 'Харчова цінність',
  },
  'noAdditionalNutrients': {
    'ar': 'لا تتوفر بيانات إضافية عن العناصر الغذائية.',
    'en': 'No additional nutrient data available.',
    'fr': 'Aucune donnée nutritionnelle supplémentaire.',
    'es': 'No hay datos nutricionales adicionales disponibles.',
    'tr': 'Ek besin verisi yok.',
    'de': 'Keine zusätzlichen Nährwertdaten verfügbar.',
    'it': 'Non sono disponibili altri dati nutrizionali.',
    'pt-BR': 'Não há dados nutricionais adicionais disponíveis.',
    'pt-PT': 'Não existem dados nutricionais adicionais.',
    'ur': 'اضافی غذائی معلومات دستیاب نہیں۔',
    'fa': 'داده تغذیه‌ای بیشتری موجود نیست.',
    'hi': 'कोई अतिरिक्त पोषक डेटा उपलब्ध नहीं है।',
    'id': 'Tidak ada data gizi tambahan.',
    'ms': 'Tiada data pemakanan tambahan.',
    'ja': '追加の栄養データはありません。',
    'ko': '추가 영양 데이터가 없습니다.',
    'zh-Hans': '暂无其他营养数据。',
    'zh-Hant': '沒有其他營養資料。',
    'ru': 'Дополнительные данные о питании недоступны.',
    'bn': 'অতিরিক্ত পুষ্টির তথ্য পাওয়া যায়নি।',
    'vi': 'Không có dữ liệu dinh dưỡng bổ sung.',
    'th': 'ไม่มีข้อมูลโภชนาการเพิ่มเติม',
    'pl': 'Brak dodatkowych danych o wartościach odżywczych.',
    'nl': 'Geen aanvullende voedingsgegevens beschikbaar.',
    'uk': 'Додаткові дані про харчування недоступні.',
  },
};
