part of 'food_presentation_localizer.dart';

const _foods = <String, Map<String, String>>{
  'apple': {
    'ar': 'تفاحة',
    'en': 'Apple',
    'fr': 'Pomme',
    'es': 'Manzana',
    'tr': 'Elma',
    'de': 'Apfel',
    'it': 'Mela',
    'pt-BR': 'Maçã',
    'pt-PT': 'Maçã',
    'ur': 'سیب',
    'fa': 'سیب',
    'hi': 'सेब',
    'id': 'Apel',
    'ms': 'Epal',
    'ja': 'りんご',
    'ko': '사과',
    'zh-Hans': '苹果',
    'zh-Hant': '蘋果',
    'ru': 'Яблоко',
    'bn': 'আপেল',
    'vi': 'Táo',
    'th': 'แอปเปิล',
    'pl': 'Jabłko',
    'nl': 'Appel',
    'uk': 'Яблуко',
  },
  'boiledEggs': {
    'ar': 'بيض مسلوق',
    'en': 'Boiled eggs',
    'fr': 'Œufs durs',
    'es': 'Huevos cocidos',
    'tr': 'Haşlanmış yumurta',
    'de': 'Gekochte Eier',
    'it': 'Uova sode',
    'pt-BR': 'Ovos cozidos',
    'pt-PT': 'Ovos cozidos',
    'ur': 'ابلے ہوئے انڈے',
    'fa': 'تخم‌مرغ آب‌پز',
    'hi': 'उबले अंडे',
    'id': 'Telur rebus',
    'ms': 'Telur rebus',
    'ja': 'ゆで卵',
    'ko': '삶은 달걀',
    'zh-Hans': '水煮蛋',
    'zh-Hant': '水煮蛋',
    'ru': 'Варёные яйца',
    'bn': 'সেদ্ধ ডিম',
    'vi': 'Trứng luộc',
    'th': 'ไข่ต้ม',
    'pl': 'Jajka gotowane',
    'nl': 'Gekookte eieren',
    'uk': 'Варені яйця',
  },
  'eggs': {
    'ar': 'بيض',
    'en': 'Eggs',
    'fr': 'Œufs',
    'es': 'Huevos',
    'tr': 'Yumurta',
    'de': 'Eier',
    'it': 'Uova',
    'pt-BR': 'Ovos',
    'pt-PT': 'Ovos',
    'ur': 'انڈے',
    'fa': 'تخم‌مرغ',
    'hi': 'अंडे',
    'id': 'Telur',
    'ms': 'Telur',
    'ja': '卵',
    'ko': '달걀',
    'zh-Hans': '鸡蛋',
    'zh-Hant': '雞蛋',
    'ru': 'Яйца',
    'bn': 'ডিম',
    'vi': 'Trứng',
    'th': 'ไข่',
    'pl': 'Jajka',
    'nl': 'Eieren',
    'uk': 'Яйця',
  },
  'chickenBreast': {
    'ar': 'صدر دجاج',
    'en': 'Chicken breast',
    'fr': 'Blanc de poulet',
    'es': 'Pechuga de pollo',
    'tr': 'Tavuk göğsü',
    'de': 'Hähnchenbrust',
    'it': 'Petto di pollo',
    'pt-BR': 'Peito de frango',
    'pt-PT': 'Peito de frango',
    'ur': 'مرغی کا سینہ',
    'fa': 'سینه مرغ',
    'hi': 'चिकन ब्रेस्ट',
    'id': 'Dada ayam',
    'ms': 'Dada ayam',
    'ja': '鶏むね肉',
    'ko': '닭가슴살',
    'zh-Hans': '鸡胸肉',
    'zh-Hant': '雞胸肉',
    'ru': 'Куриная грудка',
    'bn': 'মুরগির বুকের মাংস',
    'vi': 'Ức gà',
    'th': 'อกไก่',
    'pl': 'Pierś z kurczaka',
    'nl': 'Kipfilet',
    'uk': 'Куряча грудка',
  },
};

const _foodLocaleOrder = <String>[
  'ar',
  'en',
  'fr',
  'es',
  'tr',
  'de',
  'it',
  'pt-BR',
  'pt-PT',
  'ur',
  'fa',
  'hi',
  'id',
  'ms',
  'ja',
  'ko',
  'zh-Hans',
  'zh-Hant',
  'ru',
  'bn',
  'vi',
  'th',
  'pl',
  'nl',
  'uk',
];

/// Reviewed primary identities for common whole foods. Detailed USDA
/// descriptors remain authoritative in storage, while search rows use the
/// localized primary identity instead of leaking an English paragraph into
/// a non-English interface.
