import 'package:flutter/widgets.dart';

/// Administration follows the existing five-language operational copy.
String adminConsoleCopy(BuildContext context, String key) {
  final index = switch (Localizations.localeOf(context).languageCode) {
    'ar' => 1,
    'fr' => 2,
    'es' => 3,
    'tr' => 4,
    _ => 0,
  };
  return _copy[key]![index];
}

const _copy = <String, List<String>>{
  'title': [
    'BIL Administration',
    'إدارة BIL',
    'Administration BIL',
    'Administración BIL',
    'BIL Yönetimi',
  ],
  'reset': [
    'AI Coach Reset',
    'إعادة ضبط AI Coach',
    'Réinitialiser AI Coach',
    'Restablecer AI Coach',
    'AI Coach Sıfırlama',
  ],
  'community': ['Community', 'المجتمع', 'Communauté', 'Comunidad', 'Topluluk'],
  'free': [
    'Free Subscription',
    'اشتراك مجاني',
    'Abonnement offert',
    'Suscripción gratuita',
    'Ücretsiz Abonelik',
  ],
  'global': [
    'Reset all accounts',
    'إعادة ضبط جميع الحسابات',
    'Réinitialiser tous les comptes',
    'Restablecer todas las cuentas',
    'Tüm hesapları sıfırla',
  ],
  'individual': [
    'Reset one account',
    'إعادة ضبط حساب واحد',
    'Réinitialiser un compte',
    'Restablecer una cuenta',
    'Bir hesabı sıfırla',
  ],
  'notifications': [
    'Send a BIL notification',
    'إرسال إشعار من BIL',
    'Envoyer une notification BIL',
    'Enviar una notificación BIL',
    'BIL bildirimi gönder',
  ],
  'moderators': [
    'Manage moderators',
    'إدارة المشرفين',
    'Gérer les modérateurs',
    'Gestionar moderadores',
    'Moderatörleri yönet',
  ],
  'approvals': [
    'Open approval queue',
    'فتح قائمة الموافقات',
    'Ouvrir les validations',
    'Abrir aprobaciones',
    'Onay kuyruğunu aç',
  ],
  'members': [
    'Suspend or restore access',
    'تعليق الدخول أو إعادته',
    'Suspendre ou rétablir l’accès',
    'Suspender o restaurar el acceso',
    'Erişimi askıya al veya geri ver',
  ],
  'premium': [
    'Grant Premium',
    'منح Premium',
    'Offrir Premium',
    'Otorgar Premium',
    'Premium ver',
  ],
  'ai': [
    'Grant Premium + AI Coach',
    'منح Premium + AI Coach',
    'Offrir Premium + AI Coach',
    'Otorgar Premium + AI Coach',
    'Premium + AI Coach ver',
  ],
  'list': [
    'Granted accounts',
    'الحسابات الممنوحة',
    'Comptes bénéficiaires',
    'Cuentas beneficiarias',
    'Hediye verilen hesaplar',
  ],
  'email': [
    'Registered account email',
    'بريد حساب مسجل',
    'E-mail du compte inscrit',
    'Correo de una cuenta registrada',
    'Kayıtlı hesap e-postası',
  ],
  'duration': [
    'Grant duration',
    'مدة المنحة',
    'Durée du don',
    'Duración de la concesión',
    'Hediye süresi',
  ],
  '30': ['30 days', '30 يومًا', '30 jours', '30 días', '30 gün'],
  '90': ['90 days', '90 يومًا', '90 jours', '90 días', '90 gün'],
  '365': ['365 days', '365 يومًا', '365 jours', '365 días', '365 gün'],
  '0': [
    'Until revoked by an admin',
    'حتى يلغيها الأدمن',
    'Jusqu’à révocation',
    'Hasta revocación del administrador',
    'Yönetici iptal edene kadar',
  ],
  'reason': [
    'Reason (optional)',
    'السبب (اختياري)',
    'Motif (facultatif)',
    'Motivo (opcional)',
    'Neden (isteğe bağlı)',
  ],
  'separate': [
    'Admin grants are separate from store purchases and Boost. Revoking a grant leaves both untouched.',
    'المنحة الإدارية منفصلة عن مشتريات المتجر وBoost. إلغاؤها لا يمس أيًا منهما.',
    'Les dons sont distincts des achats et de Boost. Leur révocation ne les modifie pas.',
    'Las concesiones son independientes de las compras y Boost. Revocarlas no los modifica.',
    'Yönetici hediyeleri mağaza satın alımlarından ve Boost’tan ayrıdır. İptal bunları değiştirmez.',
  ],
  'quota': [
    'Includes the AI Coach plan’s real period allowance. Existing usage is retained; allowances do not stack.',
    'تشمل حصة التوكن الفعلية لباقة AI Coach. يبقى الاستهلاك السابق ولا تتضاعف الحصة.',
    'Inclut le quota réel d’AI Coach. L’usage reste conservé ; les quotas ne se cumulent pas.',
    'Incluye la cuota real de AI Coach. Se conserva el uso; las cuotas no se acumulan.',
    'AI Coach planının gerçek dönem kotasını içerir. Kullanım korunur; kotalar birikmez.',
  ],
  'grant': [
    'Grant subscription',
    'منح الاشتراك',
    'Offrir l’abonnement',
    'Otorgar suscripción',
    'Abonelik ver',
  ],
  'confirm': [
    'Confirm grant',
    'تأكيد المنحة',
    'Confirmer le don',
    'Confirmar concesión',
    'Hediyeyi onayla',
  ],
  'cancel': ['Cancel', 'رجوع', 'Annuler', 'Cancelar', 'Vazgeç'],
  'revoke': [
    'Revoke grant',
    'إلغاء المنحة',
    'Révoquer le don',
    'Revocar concesión',
    'Hediyeyi iptal et',
  ],
  'success': [
    'Subscription granted.',
    'تم منح الاشتراك.',
    'Abonnement offert.',
    'Suscripción otorgada.',
    'Abonelik verildi.',
  ],
  'already': [
    'This account already has this admin grant; its duration and usage were not reset.',
    'للحساب هذه المنحة بالفعل؛ لم تُصفّر المدة أو الاستخدام.',
    'Ce don existe déjà ; la durée et l’usage restent inchangés.',
    'La concesión ya existe; no se reiniciaron duración ni uso.',
    'Bu hediye zaten var; süre ve kullanım sıfırlanmadı.',
  ],
  'missing': [
    'No registered account matches this email.',
    'لا يوجد حساب مسجل بهذا البريد.',
    'Aucun compte inscrit ne correspond.',
    'No hay una cuenta registrada con este correo.',
    'Bu e-postaya ait kayıtlı hesap yok.',
  ],
  'revoked': ['Revoked', 'ملغاة', 'Révoqué', 'Revocada', 'İptal edildi'],
  'expired': ['Expired', 'منتهية', 'Expiré', 'Vencida', 'Süresi doldu'],
  'active': ['Active', 'نشطة', 'Actif', 'Activa', 'Etkin'],
  'created': [
    'Granted on',
    'تاريخ المنح',
    'Accordé le',
    'Fecha de concesión',
    'Verilme tarihi',
  ],
  'ends': ['Ends on', 'ينتهي في', 'Expire le', 'Vence el', 'Bitiş tarihi'],
  'failed': [
    'Could not confirm the result. Retry the same request or refresh the list.',
    'تعذر تأكيد النتيجة. أعد المحاولة أو حدّث القائمة.',
    'Résultat non confirmé. Réessayez ou actualisez la liste.',
    'No se pudo confirmar. Reintenta o actualiza la lista.',
    'Sonuç doğrulanamadı. Yeniden deneyin veya listeyi yenileyin.',
  ],
  'conflict': [
    'An active grant already exists with another plan. Revoke it from Granted accounts before changing the plan.',
    'توجد منحة نشطة بباقة أخرى. ألغِها من الحسابات الممنوحة قبل تغيير الباقة.',
    'Un autre don est actif. Révoquez-le avant de changer de forfait.',
    'Existe una concesión de otro plan. Revócala antes de cambiarlo.',
    'Başka planda etkin hediye var. Planı değiştirmeden önce iptal edin.',
  ],
  'retry': [
    'Retry',
    'إعادة المحاولة',
    'Réessayer',
    'Reintentar',
    'Yeniden dene',
  ],
  'empty': [
    'No administrative subscriptions yet.',
    'لا توجد اشتراكات إدارية بعد.',
    'Aucun abonnement offert.',
    'No hay suscripciones administrativas.',
    'Henüz yönetici aboneliği yok.',
  ],
  'refresh': ['Refresh', 'تحديث', 'Actualiser', 'Actualizar', 'Yenile'],
  'next': ['Next', 'التالي', 'Suivant', 'Siguiente', 'Sonraki'],
  'previous': ['Previous', 'السابق', 'Précédent', 'Anterior', 'Önceki'],
  'invalidEmail': [
    'Enter a valid email address.',
    'أدخل بريدًا إلكترونيًا صحيحًا.',
    'Saisissez un e-mail valide.',
    'Introduce un correo válido.',
    'Geçerli e-posta girin.',
  ],
};
