part of 'community_connections_page.dart';

class _ConnectionsCopy {
  const _ConnectionsCopy({
    required this.title,
    required this.findPeople,
    required this.loadFailed,
    required this.empty,
    required this.member,
    required this.accept,
    required this.decline,
    required this.message,
    required this.pendingIncoming,
    required this.pendingOutgoing,
    required this.accepted,
    required this.declined,
    required this.manage,
    required this.remove,
    required this.block,
    required this.report,
    required this.reportSubmitted,
    required this.actionFailed,
    required this.signInRequired,
    required this.signIn,
    required this.retry,
    required this.all,
    required this.requests,
    required this.educationTitle,
    required this.educationBody,
  });

  factory _ConnectionsCopy.of(
    BuildContext context,
  ) => switch (Localizations.localeOf(context).languageCode) {
    'ar' => const _ConnectionsCopy(
      title: 'الأصدقاء والطلبات',
      findPeople: 'البحث عن أشخاص',
      loadFailed: 'تعذر تحميل العلاقات بأمان.',
      empty: 'لا توجد طلبات أو صداقات بعد.',
      member: 'عضو BIL',
      accept: 'قبول',
      decline: 'رفض',
      message: 'مراسلة',
      pendingIncoming: 'طلب صداقة وارد',
      pendingOutgoing: 'طلب مرسل بانتظار الرد',
      accepted: 'صديق',
      declined: 'طلب مرفوض',
      manage: 'إدارة العلاقة',
      remove: 'إزالة الصداقة',
      block: 'حظر العضو',
      report: 'الإبلاغ عن العضو',
      reportSubmitted: 'تم إرسال البلاغ إلى فريق الإشراف.',
      actionFailed: 'تعذر تنفيذ الإجراء بأمان. حاول مجددًا.',
      signInRequired: 'سجّل الدخول لعرض الأصدقاء والطلبات.',
      signIn: 'تسجيل الدخول',
      retry: 'إعادة المحاولة',
      all: 'الكل',
      requests: 'الطلبات',
      educationTitle: 'أنت تتحكم في علاقاتك',
      educationBody: 'لا نشارك بياناتك الصحية. اقبل فقط الأشخاص الذين تعرفهم.',
    ),
    'fr' => const _ConnectionsCopy(
      title: 'Amis et demandes',
      findPeople: 'Trouver des personnes',
      loadFailed: 'Impossible de charger les relations.',
      empty: 'Aucune demande ou amitié.',
      member: 'Membre BIL',
      accept: 'Accepter',
      decline: 'Refuser',
      message: 'Message',
      pendingIncoming: 'Demande reçue',
      pendingOutgoing: 'Demande envoyée',
      accepted: 'Ami',
      declined: 'Demande refusée',
      manage: 'Gérer',
      remove: 'Retirer l’amitié',
      block: 'Bloquer',
      report: 'Signaler le membre',
      reportSubmitted: 'Signalement envoyé à la modération.',
      actionFailed: 'Action impossible. Réessayez.',
      signInRequired: 'Connectez-vous pour voir les amis et les demandes.',
      signIn: 'Se connecter',
      retry: 'Réessayer',
      all: 'Tous',
      requests: 'Demandes',
      educationTitle: 'Vous contrôlez vos relations',
      educationBody:
          'Vos données de santé restent privées. N’acceptez que les personnes que vous connaissez.',
    ),
    'es' => const _ConnectionsCopy(
      title: 'Amigos y solicitudes',
      findPeople: 'Buscar personas',
      loadFailed: 'No se pudieron cargar las relaciones.',
      empty: 'Aún no hay solicitudes ni amistades.',
      member: 'Miembro BIL',
      accept: 'Aceptar',
      decline: 'Rechazar',
      message: 'Mensaje',
      pendingIncoming: 'Solicitud recibida',
      pendingOutgoing: 'Solicitud enviada',
      accepted: 'Amigo',
      declined: 'Solicitud rechazada',
      manage: 'Gestionar',
      remove: 'Eliminar amistad',
      block: 'Bloquear',
      report: 'Denunciar miembro',
      reportSubmitted: 'Denuncia enviada a moderación.',
      actionFailed: 'No se pudo completar la acción.',
      signInRequired: 'Inicia sesión para ver amigos y solicitudes.',
      signIn: 'Iniciar sesión',
      retry: 'Reintentar',
      all: 'Todos',
      requests: 'Solicitudes',
      educationTitle: 'Tú controlas tus conexiones',
      educationBody:
          'Tus datos de salud son privados. Acepta solo a personas que conozcas.',
    ),
    'tr' => const _ConnectionsCopy(
      title: 'Arkadaşlar ve istekler',
      findPeople: 'Kişi bul',
      loadFailed: 'Bağlantılar yüklenemedi.',
      empty: 'Henüz istek veya arkadaş yok.',
      member: 'BIL üyesi',
      accept: 'Kabul et',
      decline: 'Reddet',
      message: 'Mesaj',
      pendingIncoming: 'Gelen arkadaşlık isteği',
      pendingOutgoing: 'Gönderilen istek',
      accepted: 'Arkadaş',
      declined: 'İstek reddedildi',
      manage: 'Yönet',
      remove: 'Arkadaşlığı kaldır',
      block: 'Engelle',
      report: 'Üyeyi bildir',
      reportSubmitted: 'Bildirim moderasyona gönderildi.',
      actionFailed: 'İşlem tamamlanamadı. Tekrar deneyin.',
      signInRequired: 'Arkadaşları ve istekleri görmek için oturum açın.',
      signIn: 'Oturum aç',
      retry: 'Tekrar dene',
      all: 'Tümü',
      requests: 'İstekler',
      educationTitle: 'Bağlantılarınızı siz kontrol edersiniz',
      educationBody:
          'Sağlık verileriniz gizli kalır. Yalnızca tanıdığınız kişileri kabul edin.',
    ),
    _ => _ConnectionsCopy.extended(context),
  };

  factory _ConnectionsCopy.extended(BuildContext context) {
    String t(String value) => AppLocalizations.of(context).text(value);
    return _ConnectionsCopy(
      title: t('Friends and requests'),
      findPeople: t('Find people'),
      loadFailed: t('Could not load connections safely.'),
      empty: t('No requests or friends yet.'),
      member: t('BIL member'),
      accept: t('Accept'),
      decline: t('Decline'),
      message: t('Message'),
      pendingIncoming: t('Incoming friend request'),
      pendingOutgoing: t('Request awaiting response'),
      accepted: t('Friend'),
      declined: t('Request declined'),
      manage: t('Manage connection'),
      remove: t('Remove friend'),
      block: t('Block member'),
      report: t('Report member'),
      reportSubmitted: t('Report sent to moderation.'),
      actionFailed: t('Could not complete that action safely. Try again.'),
      signInRequired: t('Sign in to view friends and requests.'),
      signIn: t('Sign in'),
      retry: t('Retry'),
      all: t('All'),
      requests: t('Requests'),
      educationTitle: t('You control your connections'),
      educationBody: t(
        'Your health data stays private. Only accept people you know.',
      ),
    );
  }

  final String title, findPeople, loadFailed, empty, member;
  final String accept, decline, message;
  final String pendingIncoming, pendingOutgoing, accepted, declined;
  final String manage, remove, block, report, reportSubmitted;
  final String actionFailed, signInRequired;
  final String signIn, retry;
  final String all, requests, educationTitle, educationBody;

  String status(String value, {required bool incoming}) => switch (value) {
    'accepted' => accepted,
    'declined' => declined,
    _ => incoming ? pendingIncoming : pendingOutgoing,
  };
}
