/// New community form feedback. Machine-authored translations require normal
/// linguistic QA; the tests verify coverage, not translation quality.
class CommunityFormCopy {
  static String? resolve(String english, String locale) {
    if (english == 'Review policy') {
      if (locale.toLowerCase() == 'en') return english;
      return reviewPolicyTranslations[locale.toLowerCase()];
    }
    final index = englishKeys.indexOf(english);
    if (index < 0) return null;
    if (locale.toLowerCase() == 'en') return english;
    final values = translations[locale.toLowerCase()];
    return values == null ? null : values[index];
  }

  static const englishKeys = <String>[
    'This value is required.',
    'Use 2 to 180 characters.',
    'Enter a non-negative decimal number.',
    'Serving weight must be greater than zero.',
    'Check this value and its unit; it is too large.',
    'Nutrient grams cannot exceed the serving weight.',
    'Total macro grams exceed this serving weight.',
    'Submission could not be confirmed. Your values are kept. Check your submissions before retrying.',
    'Enter all nutrition values for this serving, not per 100 g.',
    'Sending…',
    'Write your post before publishing.',
    'Write a caption before publishing your photo.',
  ];

  static const catalogSources = <String>{...englishKeys, 'Review policy'};

  static const reviewPolicyTranslations = <String, String>{
    'ar': 'مراجعة السياسة',
    'fr': 'Consulter la politique',
    'es': 'Revisar la política',
    'tr': 'Politikayı incele',
    'de': 'Richtlinie prüfen',
    'it': 'Esamina la policy',
    'pt-br': 'Revisar a política',
    'pt-pt': 'Rever a política',
    'ur': 'پالیسی کا جائزہ لیں',
    'fa': 'بررسی سیاست',
    'hi': 'नीति की समीक्षा करें',
    'id': 'Tinjau kebijakan',
    'ms': 'Semak dasar',
    'ja': 'ポリシーを確認',
    'ko': '정책 검토',
    'zh-hans': '查看政策',
    'zh-hant': '檢視政策',
    'ru': 'Просмотреть правила',
    'bn': 'নীতি দেখুন',
    'vi': 'Xem chính sách',
    'th': 'ดูนโยบาย',
    'pl': 'Sprawdź zasady',
    'nl': 'Beleid bekijken',
    'uk': 'Переглянути правила',
  };

  static const translations = <String, List<String>>{
    'ar': [
      'هذه القيمة مطلوبة.',
      'اكتب من حرفين إلى 180 حرفًا.',
      'أدخل رقمًا عشريًا غير سالب.',
      'يجب أن يكون وزن الحصة أكبر من صفر.',
      'راجع هذه القيمة ووحدتها؛ القيمة كبيرة جدًا.',
      'غرامات العنصر الغذائي لا يمكن أن تتجاوز وزن الحصة.',
      'مجموع غرامات الماكروز يتجاوز وزن هذه الحصة.',
      'تعذر تأكيد الإرسال. احتفظنا بالقيم. تحقق من مساهماتك قبل إعادة المحاولة.',
      'أدخل جميع القيم الغذائية لهذه الحصة، وليس لكل 100 غرام.',
      'جارٍ الإرسال…',
      'اكتب منشورك قبل النشر.',
      'اكتب وصفًا قبل نشر الصورة.',
    ],
    'fr': [
      'Cette valeur est obligatoire.',
      'Utilisez de 2 à 180 caractères.',
      'Saisissez un nombre décimal positif ou nul.',
      'Le poids de la portion doit être supérieur à zéro.',
      'Vérifiez cette valeur et son unité ; elle est trop élevée.',
      'Les grammes du nutriment ne peuvent pas dépasser le poids de la portion.',
      'Le total des grammes de macronutriments dépasse le poids de cette portion.',
      'Envoi non confirmé. Vos valeurs sont conservées. Vérifiez vos contributions avant de réessayer.',
      'Saisissez toutes les valeurs nutritionnelles pour cette portion, et non pour 100 g.',
      'Envoi…',
      'Rédigez votre publication avant de publier.',
      'Ajoutez une légende avant de publier votre photo.',
    ],
    'es': [
      'Este valor es obligatorio.',
      'Usa de 2 a 180 caracteres.',
      'Introduce un número decimal no negativo.',
      'El peso de la porción debe ser mayor que cero.',
      'Revisa este valor y su unidad; es demasiado alto.',
      'Los gramos del nutriente no pueden superar el peso de la porción.',
      'El total de gramos de macronutrientes supera el peso de esta porción.',
      'No se pudo confirmar el envío. Conservamos tus valores. Revisa tus contribuciones antes de reintentar.',
      'Introduce todos los valores nutricionales de esta porción, no por 100 g.',
      'Enviando…',
      'Escribe tu publicación antes de publicarla.',
      'Escribe un pie de foto antes de publicarla.',
    ],
    'tr': [
      'Bu değer gereklidir.',
      '2 ile 180 karakter kullanın.',
      'Negatif olmayan bir ondalık sayı girin.',
      'Porsiyon ağırlığı sıfırdan büyük olmalıdır.',
      'Bu değeri ve birimini kontrol edin; değer çok büyük.',
      'Besin öğesinin gramı porsiyon ağırlığını aşamaz.',
      'Makro besinlerin toplam gramı bu porsiyonun ağırlığını aşıyor.',
      'Gönderim doğrulanamadı. Değerleriniz korundu. Yeniden denemeden önce katkılarınızı kontrol edin.',
      'Tüm besin değerlerini 100 g için değil, bu porsiyon için girin.',
      'Gönderiliyor…',
      'Yayımlamadan önce gönderinizi yazın.',
      'Fotoğrafınızı yayımlamadan önce bir açıklama yazın.',
    ],
    'de': [
      'Dieser Wert ist erforderlich.',
      'Verwende 2 bis 180 Zeichen.',
      'Gib eine nicht negative Dezimalzahl ein.',
      'Das Portionsgewicht muss größer als null sein.',
      'Prüfe diesen Wert und seine Einheit; er ist zu groß.',
      'Die Nährstoffmenge in Gramm darf das Portionsgewicht nicht überschreiten.',
      'Die Summe der Makronährstoffe in Gramm überschreitet das Portionsgewicht.',
      'Das Senden konnte nicht bestätigt werden. Deine Werte bleiben erhalten. Prüfe vor einem neuen Versuch deine Beiträge.',
      'Gib alle Nährwerte für diese Portion ein, nicht pro 100 g.',
      'Wird gesendet…',
      'Schreibe deinen Beitrag vor dem Veröffentlichen.',
      'Schreibe vor dem Veröffentlichen deines Fotos eine Bildunterschrift.',
    ],
    'it': [
      'Questo valore è obbligatorio.',
      'Usa da 2 a 180 caratteri.',
      'Inserisci un numero decimale non negativo.',
      'Il peso della porzione deve essere maggiore di zero.',
      'Controlla questo valore e la sua unità: è troppo alto.',
      'I grammi del nutriente non possono superare il peso della porzione.',
      'Il totale dei grammi dei macronutrienti supera il peso di questa porzione.',
      'Invio non confermato. I valori sono conservati. Controlla i tuoi contributi prima di riprovare.',
      'Inserisci tutti i valori nutrizionali per questa porzione, non per 100 g.',
      'Invio…',
      'Scrivi il post prima di pubblicarlo.',
      'Scrivi una didascalia prima di pubblicare la foto.',
    ],
    'pt-br': [
      'Este valor é obrigatório.',
      'Use de 2 a 180 caracteres.',
      'Digite um número decimal não negativo.',
      'O peso da porção deve ser maior que zero.',
      'Confira este valor e sua unidade; ele é muito alto.',
      'Os gramas do nutriente não podem ultrapassar o peso da porção.',
      'O total de gramas dos macronutrientes ultrapassa o peso desta porção.',
      'Não foi possível confirmar o envio. Seus valores foram mantidos. Confira suas contribuições antes de tentar novamente.',
      'Digite todos os valores nutricionais desta porção, não por 100 g.',
      'Enviando…',
      'Escreva sua publicação antes de publicar.',
      'Escreva uma legenda antes de publicar sua foto.',
    ],
    'pt-pt': [
      'Este valor é obrigatório.',
      'Utilize de 2 a 180 carateres.',
      'Introduza um número decimal não negativo.',
      'O peso da porção deve ser superior a zero.',
      'Verifique este valor e a sua unidade; é demasiado elevado.',
      'Os gramas do nutriente não podem exceder o peso da porção.',
      'O total de gramas dos macronutrientes excede o peso desta porção.',
      'Não foi possível confirmar o envio. Os seus valores foram guardados. Verifique as suas contribuições antes de tentar novamente.',
      'Introduza todos os valores nutricionais desta porção, não por 100 g.',
      'A enviar…',
      'Escreva a sua publicação antes de publicar.',
      'Escreva uma legenda antes de publicar a fotografia.',
    ],
    'ur': [
      'یہ قدر درکار ہے۔',
      '2 سے 180 حروف استعمال کریں۔',
      'غیر منفی اعشاری عدد درج کریں۔',
      'حصے کا وزن صفر سے زیادہ ہونا چاہیے۔',
      'اس قدر اور اکائی کی جانچ کریں؛ قدر بہت زیادہ ہے۔',
      'غذائی جزو کے گرام حصے کے وزن سے زیادہ نہیں ہو سکتے۔',
      'بڑے غذائی اجزا کے مجموعی گرام اس حصے کے وزن سے زیادہ ہیں۔',
      'ارسال کی تصدیق نہیں ہو سکی۔ آپ کی قدریں محفوظ ہیں۔ دوبارہ کوشش سے پہلے اپنی جمع کردہ معلومات دیکھیں۔',
      'تمام غذائی قدریں اس حصے کے لیے درج کریں، فی 100 گرام نہیں۔',
      'بھیجا جا رہا ہے…',
      'شائع کرنے سے پہلے اپنی پوسٹ لکھیں۔',
      'تصویر شائع کرنے سے پہلے اس کی وضاحت لکھیں۔',
    ],
    'fa': [
      'این مقدار الزامی است.',
      'از ۲ تا ۱۸۰ نویسه استفاده کنید.',
      'یک عدد اعشاری غیرمنفی وارد کنید.',
      'وزن هر وعده باید بیشتر از صفر باشد.',
      'این مقدار و واحد آن را بررسی کنید؛ مقدار خیلی زیاد است.',
      'گرم مادهٔ مغذی نمی‌تواند از وزن وعده بیشتر باشد.',
      'مجموع گرم درشت‌مغذی‌ها از وزن این وعده بیشتر است.',
      'ارسال تأیید نشد. مقادیر شما حفظ شده‌اند. پیش از تلاش دوباره، موارد ارسالی خود را بررسی کنید.',
      'همهٔ مقادیر غذایی را برای این وعده وارد کنید، نه به ازای ۱۰۰ گرم.',
      'در حال ارسال…',
      'پیش از انتشار، متن پست را بنویسید.',
      'پیش از انتشار عکس، توضیحی برای آن بنویسید.',
    ],
    'hi': [
      'यह मान आवश्यक है।',
      '2 से 180 अक्षरों का उपयोग करें।',
      'एक गैर-ऋणात्मक दशमलव संख्या दर्ज करें।',
      'परोसने का वजन शून्य से अधिक होना चाहिए।',
      'इस मान और इसकी इकाई की जाँच करें; मान बहुत बड़ा है।',
      'पोषक तत्व के ग्राम परोसने के वजन से अधिक नहीं हो सकते।',
      'मैक्रोन्यूट्रिएंट के कुल ग्राम इस परोसने के वजन से अधिक हैं।',
      'भेजने की पुष्टि नहीं हो सकी। आपके मान सुरक्षित हैं। दोबारा कोशिश से पहले अपने भेजे गए योगदान देखें।',
      'सभी पोषण मान इस परोसने के लिए दर्ज करें, प्रति 100 ग्राम के लिए नहीं।',
      'भेजा जा रहा है…',
      'प्रकाशित करने से पहले अपनी पोस्ट लिखें।',
      'फ़ोटो प्रकाशित करने से पहले उसका विवरण लिखें।',
    ],
    'id': [
      'Nilai ini wajib diisi.',
      'Gunakan 2 hingga 180 karakter.',
      'Masukkan angka desimal yang tidak negatif.',
      'Berat porsi harus lebih besar dari nol.',
      'Periksa nilai dan satuannya; nilainya terlalu besar.',
      'Gram zat gizi tidak boleh melebihi berat porsi.',
      'Total gram makronutrien melebihi berat porsi ini.',
      'Pengiriman belum dapat dikonfirmasi. Nilai Anda tetap tersimpan. Periksa kiriman Anda sebelum mencoba lagi.',
      'Masukkan semua nilai gizi untuk porsi ini, bukan per 100 g.',
      'Mengirim…',
      'Tulis postingan sebelum menerbitkannya.',
      'Tulis keterangan sebelum menerbitkan foto Anda.',
    ],
    'ms': [
      'Nilai ini diperlukan.',
      'Gunakan 2 hingga 180 aksara.',
      'Masukkan nombor perpuluhan bukan negatif.',
      'Berat hidangan mesti lebih besar daripada sifar.',
      'Semak nilai ini dan unitnya; nilainya terlalu besar.',
      'Gram nutrien tidak boleh melebihi berat hidangan.',
      'Jumlah gram makronutrien melebihi berat hidangan ini.',
      'Penghantaran tidak dapat disahkan. Nilai anda dikekalkan. Semak sumbangan anda sebelum mencuba lagi.',
      'Masukkan semua nilai pemakanan untuk hidangan ini, bukan bagi setiap 100 g.',
      'Menghantar…',
      'Tulis siaran anda sebelum menerbitkannya.',
      'Tulis kapsyen sebelum menerbitkan foto anda.',
    ],
    'ja': [
      'この値は必須です。',
      '2～180文字で入力してください。',
      '0以上の小数を入力してください。',
      '1食分の重量は0より大きい値にしてください。',
      '値と単位を確認してください。値が大きすぎます。',
      '栄養素のグラム数は1食分の重量を超えることはできません。',
      '三大栄養素の合計グラム数が1食分の重量を超えています。',
      '送信を確認できませんでした。入力値は保持されています。再試行する前に送信済みの内容を確認してください。',
      '100 g当たりではなく、この1食分のすべての栄養値を入力してください。',
      '送信中…',
      '投稿する前に本文を入力してください。',
      '写真を投稿する前に説明文を入力してください。',
    ],
    'ko': [
      '이 값은 필수입니다.',
      '2~180자를 입력하세요.',
      '0 이상의 소수를 입력하세요.',
      '1회 제공량의 무게는 0보다 커야 합니다.',
      '이 값과 단위를 확인하세요. 값이 너무 큽니다.',
      '영양소의 그램 수는 1회 제공량의 무게를 초과할 수 없습니다.',
      '다량영양소의 총 그램 수가 이 1회 제공량의 무게를 초과합니다.',
      '전송을 확인할 수 없습니다. 입력값은 유지됩니다. 다시 시도하기 전에 제출 내역을 확인하세요.',
      '100 g당이 아닌 이 1회 제공량의 모든 영양값을 입력하세요.',
      '전송 중…',
      '게시하기 전에 글을 작성하세요.',
      '사진을 게시하기 전에 설명을 작성하세요.',
    ],
    'zh-hans': [
      '此项为必填项。',
      '请输入2至180个字符。',
      '请输入非负小数。',
      '每份重量必须大于零。',
      '请检查此数值及其单位，数值过大。',
      '营养素的克数不能超过每份重量。',
      '宏量营养素的总克数超过了这份食物的重量。',
      '无法确认提交。已保留您输入的数值。重试前请检查提交记录。',
      '请输入这一份食物的全部营养值，而非每100克的数值。',
      '正在发送…',
      '发布前请先填写帖子正文。',
      '发布照片前请先填写说明。',
    ],
    'zh-hant': [
      '此項為必填項。',
      '請輸入2至180個字元。',
      '請輸入非負小數。',
      '每份重量必須大於零。',
      '請檢查此數值及其單位，數值過大。',
      '營養素的克數不能超過每份重量。',
      '巨量營養素的總克數超過了這份食物的重量。',
      '無法確認提交。已保留您輸入的數值。重試前請檢查提交紀錄。',
      '請輸入這一份食物的全部營養值，而非每100克的數值。',
      '正在傳送…',
      '發布前請先填寫貼文內容。',
      '發布照片前請先填寫說明。',
    ],
    'ru': [
      'Это значение обязательно.',
      'Используйте от 2 до 180 символов.',
      'Введите неотрицательное десятичное число.',
      'Вес порции должен быть больше нуля.',
      'Проверьте значение и единицу измерения: значение слишком велико.',
      'Количество нутриента в граммах не может превышать вес порции.',
      'Суммарное количество макронутриентов в граммах превышает вес порции.',
      'Не удалось подтвердить отправку. Значения сохранены. Перед повторной попыткой проверьте свои отправленные материалы.',
      'Введите все пищевые значения для этой порции, а не на 100 г.',
      'Отправка…',
      'Напишите текст перед публикацией.',
      'Добавьте подпись перед публикацией фотографии.',
    ],
    'bn': [
      'এই মানটি আবশ্যক।',
      '2 থেকে 180টি অক্ষর ব্যবহার করুন।',
      'একটি অঋণাত্মক দশমিক সংখ্যা লিখুন।',
      'পরিবেশনের ওজন শূন্যের বেশি হতে হবে।',
      'এই মান ও তার একক যাচাই করুন; মানটি খুব বড়।',
      'পুষ্টি উপাদানের গ্রাম পরিবেশনের ওজনের বেশি হতে পারে না।',
      'ম্যাক্রোনিউট্রিয়েন্টের মোট গ্রাম এই পরিবেশনের ওজনের বেশি।',
      'পাঠানো নিশ্চিত করা যায়নি। আপনার মানগুলো রাখা হয়েছে। আবার চেষ্টা করার আগে আপনার জমা দেওয়া তথ্য দেখুন।',
      'সব পুষ্টিমান এই পরিবেশনের জন্য লিখুন, প্রতি 100 গ্রামের জন্য নয়।',
      'পাঠানো হচ্ছে…',
      'প্রকাশ করার আগে পোস্টটি লিখুন।',
      'ছবি প্রকাশ করার আগে তার বিবরণ লিখুন।',
    ],
    'vi': [
      'Giá trị này là bắt buộc.',
      'Dùng từ 2 đến 180 ký tự.',
      'Nhập số thập phân không âm.',
      'Khối lượng khẩu phần phải lớn hơn 0.',
      'Kiểm tra giá trị và đơn vị này; giá trị quá lớn.',
      'Số gam chất dinh dưỡng không thể vượt quá khối lượng khẩu phần.',
      'Tổng số gam các chất dinh dưỡng đa lượng vượt quá khối lượng khẩu phần này.',
      'Không thể xác nhận việc gửi. Các giá trị vẫn được giữ lại. Hãy kiểm tra các mục đã gửi trước khi thử lại.',
      'Nhập tất cả giá trị dinh dưỡng cho khẩu phần này, không phải cho mỗi 100 g.',
      'Đang gửi…',
      'Viết nội dung trước khi đăng.',
      'Viết chú thích trước khi đăng ảnh.',
    ],
    'th': [
      'จำเป็นต้องระบุค่านี้',
      'ใช้ 2 ถึง 180 อักขระ',
      'ป้อนเลขทศนิยมที่ไม่เป็นลบ',
      'น้ำหนักต่อหนึ่งหน่วยบริโภคต้องมากกว่าศูนย์',
      'ตรวจสอบค่านี้และหน่วย เนื่องจากค่าสูงเกินไป',
      'กรัมของสารอาหารต้องไม่เกินน้ำหนักต่อหนึ่งหน่วยบริโภค',
      'กรัมรวมของสารอาหารหลักเกินน้ำหนักของหน่วยบริโภคนี้',
      'ไม่สามารถยืนยันการส่งได้ ค่าที่กรอกยังถูกเก็บไว้ โปรดตรวจสอบรายการที่ส่งก่อนลองอีกครั้ง',
      'ป้อนคุณค่าทางโภชนาการทั้งหมดของหน่วยบริโภคนี้ ไม่ใช่ต่อ 100 กรัม',
      'กำลังส่ง…',
      'เขียนข้อความก่อนเผยแพร่โพสต์',
      'เขียนคำบรรยายก่อนเผยแพร่รูปภาพ',
    ],
    'pl': [
      'Ta wartość jest wymagana.',
      'Użyj od 2 do 180 znaków.',
      'Wpisz nieujemną liczbę dziesiętną.',
      'Masa porcji musi być większa od zera.',
      'Sprawdź tę wartość i jej jednostkę; wartość jest zbyt duża.',
      'Liczba gramów składnika nie może przekraczać masy porcji.',
      'Łączna liczba gramów makroskładników przekracza masę tej porcji.',
      'Nie udało się potwierdzić wysłania. Wartości zostały zachowane. Przed ponowną próbą sprawdź swoje zgłoszenia.',
      'Wpisz wszystkie wartości odżywcze dla tej porcji, nie na 100 g.',
      'Wysyłanie…',
      'Napisz post przed opublikowaniem.',
      'Dodaj podpis przed opublikowaniem zdjęcia.',
    ],
    'nl': [
      'Deze waarde is verplicht.',
      'Gebruik 2 tot 180 tekens.',
      'Voer een niet-negatief decimaal getal in.',
      'Het portiegewicht moet groter zijn dan nul.',
      'Controleer deze waarde en de eenheid; de waarde is te groot.',
      'Het aantal gram van de voedingsstof mag het portiegewicht niet overschrijden.',
      'Het totale aantal gram macronutriënten overschrijdt het gewicht van deze portie.',
      'De verzending kon niet worden bevestigd. Je waarden blijven bewaard. Controleer je inzendingen voordat je het opnieuw probeert.',
      'Voer alle voedingswaarden voor deze portie in, niet per 100 g.',
      'Verzenden…',
      'Schrijf je bericht voordat je het publiceert.',
      'Schrijf een bijschrift voordat je je foto publiceert.',
    ],
    'uk': [
      'Це значення обов’язкове.',
      'Використовуйте від 2 до 180 символів.',
      'Введіть невід’ємне десяткове число.',
      'Вага порції має бути більшою за нуль.',
      'Перевірте це значення та одиницю вимірювання: значення завелике.',
      'Кількість нутрієнта у грамах не може перевищувати вагу порції.',
      'Загальна кількість макронутрієнтів у грамах перевищує вагу цієї порції.',
      'Не вдалося підтвердити надсилання. Значення збережено. Перед повторною спробою перевірте свої надіслані матеріали.',
      'Введіть усі поживні значення для цієї порції, а не на 100 г.',
      'Надсилання…',
      'Напишіть текст перед публікацією.',
      'Додайте підпис перед публікацією фотографії.',
    ],
  };
}
