/// Reviewed phonetic building blocks for Arabic workout discovery titles.
///
/// These are transliterations of the canonical English names, not literal
/// translations of movement meaning. Unknown tokens fail closed so a newly
/// added exercise cannot silently receive a guessed or misleading title.
abstract final class WorkoutDiscoveryArabicTransliteration {
  static String transliterate(String canonicalEnglishTitle) {
    final tokens = canonicalEnglishTitle
        .toLowerCase()
        .split(RegExp('[^a-z]+'))
        .where((token) => token.isNotEmpty);
    final output = <String>[];
    for (final token in tokens) {
      if (token == 's') {
        if (output.isEmpty) {
          throw const FormatException('Invalid possessive workout title.');
        }
        output[output.length - 1] = '${output.last}ز';
        continue;
      }
      final transliteration = _tokens[token];
      if (transliteration == null) {
        throw FormatException(
          'Missing Arabic workout transliteration token: $token.',
        );
      }
      output.add(transliteration);
    }
    if (output.isEmpty) {
      throw const FormatException('Workout title cannot be transliterated.');
    }
    return output.join(' ');
  }

  static const _tokens = <String, String>{
    'adductor': 'أدَكتر',
    'air': 'إير',
    'airplane': 'إيربلين',
    'alternating': 'أولترنيتِنغ',
    'and': 'أند',
    'angel': 'إنجل',
    'ankle': 'آنكل',
    'apart': 'أبارت',
    'arm': 'آرم',
    'back': 'باك',
    'backward': 'باكوَرد',
    'balance': 'بالانس',
    'ball': 'بول',
    'band': 'باند',
    'battle': 'باتل',
    'bear': 'بير',
    'bench': 'بنش',
    'bend': 'بِند',
    'bent': 'بِنت',
    'biceps': 'بايسبس',
    'bicycle': 'بايسيكل',
    'bird': 'بيرد',
    'body': 'بادي',
    'bodyweight': 'بادي ويت',
    'book': 'بوك',
    'box': 'بوكس',
    'boxer': 'بوكسر',
    'boxing': 'بوكسينغ',
    'breathing': 'بريذِنغ',
    'bridge': 'بريدج',
    'bug': 'بَغ',
    'burpee': 'بيربي',
    'butt': 'بَت',
    'cable': 'كيبل',
    'calf': 'كاف',
    'carry': 'كاري',
    'cat': 'كات',
    'chair': 'تشير',
    'chest': 'تشِست',
    'child': 'تشايلد',
    'chop': 'تشوب',
    'circles': 'سيركلز',
    'clamshell': 'كلام شِل',
    'climber': 'كلايمر',
    'clock': 'كلوك',
    'controlled': 'كنترولْد',
    'counter': 'كاونتر',
    'cow': 'كاو',
    'crawl': 'كرول',
    'crunch': 'كرانش',
    'curl': 'كيرل',
    'dance': 'دانس',
    'dead': 'دِد',
    'deadlift': 'دِد لِفت',
    'deep': 'ديب',
    'diaphragmatic': 'دايافراغماتك',
    'dig': 'دِغ',
    'dip': 'دِب',
    'dog': 'دوغ',
    'doorway': 'دورواي',
    'dorsiflexion': 'دورسي فليكشن',
    'drill': 'دريل',
    'drive': 'درايف',
    'dumbbell': 'دمبل',
    'elevated': 'إليفيتِد',
    'extension': 'إكستنشن',
    'extensor': 'إكستنسور',
    'farmer': 'فارمر',
    'fast': 'فاست',
    'feet': 'فيت',
    'figure': 'فيغر',
    'flexor': 'فليكسور',
    'floor': 'فلور',
    'fly': 'فلاي',
    'forearm': 'فور آرم',
    'forward': 'فوروَرد',
    'four': 'فور',
    'from': 'فروم',
    'front': 'فرَنت',
    'gentle': 'جنتل',
    'get': 'غِت',
    'glute': 'غلوت',
    'goblet': 'غوبلت',
    'good': 'غود',
    'grapevine': 'غريب فاين',
    'half': 'هاف',
    'hammer': 'هامر',
    'hamstring': 'هامسترينغ',
    'heel': 'هيل',
    'high': 'هاي',
    'hinge': 'هينج',
    'hip': 'هِب',
    'hold': 'هولد',
    'hollow': 'هولو',
    'hop': 'هوب',
    'hover': 'هوفر',
    'hug': 'هَغ',
    'impact': 'إمباكت',
    'in': 'إن',
    'inchworm': 'إنش وورم',
    'incline': 'إنكلاين',
    'jack': 'جاك',
    'jump': 'جمب',
    'jumping': 'جمبينغ',
    'kettlebell': 'كيتل بِل',
    'kickback': 'كيك باك',
    'kicks': 'كيكس',
    'knee': 'ني',
    'kneeling': 'نيلينغ',
    'knees': 'نيز',
    'lateral': 'لاترال',
    'leg': 'ليغ',
    'legs': 'ليغز',
    'lift': 'لِفت',
    'line': 'لاين',
    'low': 'لو',
    'lower': 'لوَر',
    'lunge': 'لانج',
    'lying': 'لايينغ',
    'mambo': 'مامبو',
    'march': 'مارتش',
    'medicine': 'مِدِسن',
    'mobility': 'موبيلتي',
    'modified': 'موديفايد',
    'morning': 'مورنِنغ',
    'mountain': 'ماونتن',
    'neck': 'نِك',
    'ninety': 'ناينتي',
    'one': 'وَن',
    'open': 'أوبن',
    'over': 'أوفر',
    'overhead': 'أوفرهِد',
    'pallof': 'بالوف',
    'partial': 'بارشال',
    'pelvic': 'بيلفك',
    'place': 'بليس',
    'plank': 'بلانك',
    'pose': 'بوز',
    'power': 'باور',
    'press': 'بريس',
    'prone': 'برون',
    'pull': 'بول',
    'pump': 'بَمب',
    'push': 'بوش',
    'quadriceps': 'كوادريسبس',
    'quadruped': 'كوادرابِد',
    'rack': 'راك',
    'raise': 'ريز',
    'reach': 'ريتش',
    'reclined': 'ريكلايند',
    'relaxed': 'ريلاكسْت',
    'release': 'ريليس',
    'renegade': 'رينيغيد',
    'resistance': 'ريزيستانس',
    'reverse': 'ريفيرس',
    'rock': 'روك',
    'romanian': 'رومانيان',
    'rope': 'روب',
    'rotation': 'روتيشن',
    'row': 'رو',
    'run': 'رَن',
    'sandbag': 'ساند باغ',
    'scapular': 'سكابيولار',
    'seal': 'سيل',
    'seated': 'سيتِد',
    'shadow': 'شادو',
    'short': 'شورت',
    'shoulder': 'شولدر',
    'shrug': 'شرَغ',
    'shuffle': 'شَفِل',
    'shuttle': 'شاتل',
    'side': 'سايد',
    'single': 'سينغل',
    'sit': 'سِت',
    'six': 'سِكس',
    'skater': 'سكيتر',
    'slide': 'سلايد',
    'slow': 'سلو',
    'speed': 'سبيد',
    'spinal': 'سباينال',
    'split': 'سبليت',
    'squat': 'سكوات',
    'stair': 'ستير',
    'stance': 'ستانس',
    'stand': 'ستاند',
    'standard': 'ستاندرد',
    'standing': 'ستاندينغ',
    'step': 'ستيب',
    'stretch': 'ستريتش',
    'suitcase': 'سوتكيس',
    'sumo': 'سومو',
    'supine': 'سوباين',
    'supported': 'سبورتِد',
    'switch': 'سويتش',
    'tabletop': 'تيبل توب',
    'tandem': 'تاندِم',
    'tap': 'تاب',
    'thoracic': 'ثوراسك',
    'three': 'ثري',
    'thrust': 'ثرَست',
    'thruster': 'ثرستر',
    'tilt': 'تِلت',
    'to': 'تو',
    'toe': 'تو',
    'touch': 'تَتش',
    'tree': 'تري',
    'triceps': 'ترايسبس',
    'trunk': 'ترَنك',
    'tuck': 'تَك',
    'turkish': 'تيركش',
    'up': 'أب',
    'v': 'في',
    'walk': 'ووك',
    'walkout': 'ووك آوت',
    'wall': 'وول',
    'warrior': 'واريور',
    'wave': 'ويف',
    'wrist': 'رِست',
    'y': 'واي',
  };
}
