part of 'app_localizations.dart';

const _appLocaleArabicRuntime = {
  'BIL is preparing your local data': 'يُجهّز BIL بياناتك المحلية',
  'Could not open your local data': 'تعذر فتح بياناتك المحلية',
  'Your data was not reset or uploaded. Try opening it again.':
      'لم يتم حذف بياناتك أو رفعها. حاول فتحها مرة أخرى.',
  'Try again': 'حاول مرة أخرى',
  'Enter a quantity from 0.1 to 100000.': 'أدخل كمية من 0.1 إلى 100000.',
  'Enter a water amount from 1 to 5000 ml.': 'أدخل كمية ماء من 1 إلى 5000 مل.',
  'Could not load the food catalog.': 'تعذر تحميل دليل الأطعمة.',
  'Remove water entry': 'إزالة سجل الماء',
  'Remove meal item': 'إزالة عنصر الوجبة',
  'Remove meal item?': 'إزالة عنصر الوجبة؟',
  'Remove': 'إزالة',
  'from this meal?': 'من هذه الوجبة؟',
  'Verified': 'موثّق',
  'Unverified': 'غير موثّق',
  'Edit custom food': 'تعديل الطعام المخصص',
  'Delete custom food?': 'حذف الطعام المخصص؟',
  'Existing meal history keeps its nutrition snapshot. This food will no longer appear in search.':
      'سيحتفظ سجل الوجبات الحالي بلقطة التغذية، ولن يظهر هذا الطعام في البحث بعد الآن.',
  'Weight trend': 'اتجاه الوزن',
  'Loading your latest body data': 'جارٍ تحميل أحدث بيانات جسمك',
  'Your latest body data could not be loaded.': 'تعذر تحميل أحدث بيانات جسمك.',
  'Measurement date': 'تاريخ القياس',
  'Measurement conditions': 'ظروف القياس',
  'morning': 'صباحًا',
  'afterBathroom': 'بعد استخدام الحمام',
  'beforeFoodDrink': 'قبل الطعام أو الشراب',
  'differentConditions': 'ظروف مختلفة',
  'A weight entry already exists for this date.':
      'يوجد قياس وزن بالفعل لهذا التاريخ.',
  'Recorded weight trend over time': 'اتجاه الوزن المسجل عبر الزمن',
  'Seven-day change': 'تغير سبعة أيام',
  'Smoothed weekly direction': 'الاتجاه الأسبوعي الممهّد',
  'At least four entries needed': 'نحتاج أربعة قياسات على الأقل',
  'entries': 'قياسات',
  'days': 'أيام',
  'Direction': 'الاتجاه',
  'week': 'أسبوع',
  'Scale trends include water, glycogen, digestive content, and measurement variation; they do not prove fat or muscle change.':
      'تشمل اتجاهات الميزان الماء والجليكوجين ومحتوى الجهاز الهضمي واختلاف ظروف القياس؛ ولا تثبت تغير الدهون أو العضلات.',
  'Settings': 'الإعدادات',
  'Language': 'اللغة',
  'Appearance': 'المظهر',
  'System': 'النظام',
  'Light': 'فاتح',
  'Dark': 'داكن',
  'Units': 'الوحدات',
  'Metric (kg, cm)': 'متري (كجم، سم)',
  'Imperial (lb, in)': 'إمبراطوري (رطل، بوصة)',
  'Profile and goals': 'الملف الشخصي والأهداف',
  'Analytics': 'التحليلات',
  'Privacy': 'الخصوصية',
  'Health disclaimer': 'إخلاء المسؤولية الصحية',
  'Export local data': 'تصدير البيانات المحلية',
  'App version': 'إصدار التطبيق',
  'Cloud sync': 'المزامنة السحابية',
  'Reset local data': 'إعادة ضبط البيانات المحلية',
  'Daily Log': 'السجل اليومي',
  'Add water': 'إضافة ماء',
  'Custom water amount': 'كمية ماء مخصصة',
  'Amount in milliliters': 'الكمية بالملليلتر',
  'Water progress': 'تقدم شرب الماء',
  'remaining': 'متبقٍ',
  'Hydration target reached': 'تم الوصول إلى هدف شرب الماء',
  'Custom amount': 'كمية مخصصة',
  'Did you weigh yourself today?': 'هل قست وزنك اليوم؟',
  'A comparable daily check-in improves trend confidence. Normal fluctuations are expected, and skipping is always allowed.':
      'يحسن القياس اليومي في ظروف متقاربة ثقة الاتجاه. التقلبات الطبيعية متوقعة، ويمكنك التخطي دائمًا.',
  "Today's weight": 'وزن اليوم',
  'Skip today': 'تخطي اليوم',
  'Save check-in': 'حفظ القياس',
  'Analysis reliability': 'موثوقية التحليل',
  'Insufficient data': 'بيانات غير كافية',
  'Emerging confidence': 'ثقة قيد التكوين',
  'Useful confidence': 'ثقة مفيدة',
  'Strong confidence': 'ثقة قوية',
  'Loading Today dashboard': 'جارٍ تحميل لوحة اليوم',
  'Today is up to date.': 'بيانات اليوم محدثة.',
  'Some local Today data could not be refreshed.':
      'تعذر تحديث بعض بيانات اليوم المحلية.',
  'consumed': 'مستهلك',
  'target': 'هدف',
  'above target reference': 'أعلى من الهدف المرجعي',
  "Today's meals": 'وجبات اليوم',
  'Open Diary': 'فتح اليوميات',
  'No foods logged yet': 'لم تُسجل أطعمة بعد',
  'Historical food': 'طعام تاريخي',
  'protein': 'بروتين',
  'No target; informational only': 'لا يوجد هدف؛ للمعلومات فقط',
  'Meal type': 'نوع الوجبة',
  'Breakfast': 'الإفطار',
  'Lunch': 'الغداء',
  'Dinner': 'العشاء',
  'Snack': 'وجبة خفيفة',
  'Food': 'الطعام',
  'Save meal': 'حفظ الوجبة',
  'Save log': 'حفظ السجل',
  'Calculated nutrition': 'التغذية المحسوبة',
  'Weight history': 'سجل الوزن',
  'Seven-day trend': 'اتجاه سبعة أيام',
  'No weight entries yet.': 'لا توجد قياسات وزن بعد.',
  'Food catalog': 'دليل الأطعمة',
  'Custom food': 'طعام مخصص',
  'Create custom food': 'إنشاء طعام مخصص',
  'Cancel': 'إلغاء',
  'Save': 'حفظ',
  'Delete': 'حذف',
  'Continue': 'متابعة',
  'Complete your profile': 'أكمل ملفك الشخصي',
  'These essentials calculate your starting targets. Your draft stays on this device if you leave.':
      'تُستخدم هذه الأساسيات لحساب أهدافك الأولية. تبقى مسودتك على هذا الجهاز إذا غادرت.',
  'Age and biological sex are used only for established energy equations.':
      'يُستخدم العمر والجنس البيولوجي فقط في معادلات الطاقة المعتمدة.',
  'Restoring your private setup on this device':
      'جارٍ استعادة إعدادك الخاص من هذا الجهاز',
  'Your unfinished setup was restored from this device.':
      'تمت استعادة إعدادك غير المكتمل من هذا الجهاز.',
  'Could not restore your local setup': 'تعذرت استعادة إعدادك المحلي',
  'Nothing was deleted or uploaded. Reopen the local setup when your device storage is available.':
      'لم يتم حذف أي شيء أو رفعه. أعد فتح الإعداد المحلي عندما تصبح مساحة تخزين الجهاز متاحة.',
  'Your setup could not be saved. Your draft remains on this device; try again.':
      'تعذر حفظ إعدادك. تظل مسودتك على هذا الجهاز؛ حاول مرة أخرى.',
  'Saving your setup locally': 'جارٍ حفظ إعدادك محليًا',
  'Understand every insight': 'افهم كل رؤية',
  'See the evidence, confidence, and what BIL still does not know.':
      'اطّلع على الأدلة والثقة وما لا يزال BIL لا يعرفه.',
  'Private and useful offline': 'خاص ومفيد دون اتصال',
  'Start without an account. Your health data stays on this device.':
      'ابدأ دون حساب. تبقى بياناتك الصحية على هذا الجهاز.',
  'Honest about uncertainty': 'صريح بشأن عدم اليقين',
  'BIL never invents missing evidence or pretends a guess is a fact.':
      'لا يختلق BIL أدلة مفقودة ولا يقدم التخمين على أنه حقيقة.',
  'No account required. Nothing is uploaded.':
      'لا يلزم حساب. لا يتم رفع أي شيء.',
  'Let’s start with you': 'لنبدأ بك',
  'Your starting point': 'نقطة بدايتك',
  'Where do you want to go?': 'إلى أين تريد أن تصل؟',
  'Your choice and safety': 'اختيارك وسلامتك',
  'Age and biological sex are used only in established energy equations. Choose the units that feel natural to you.':
      'يُستخدم العمر والجنس البيولوجي فقط في معادلات الطاقة المعتمدة. اختر الوحدات الأنسب لك.',
  'Height, current weight, and usual activity establish your starting energy estimate.':
      'يحدد الطول والوزن الحالي والنشاط المعتاد تقدير طاقة البداية.',
  'Your direction shapes targets. BIL keeps the estimate cautious and you can change it later.':
      'يحدد اتجاهك الأهداف. يحافظ BIL على تقدير حذر ويمكنك تغييره لاحقًا.',
  'Extra context is optional and stays on this device. Review the safety boundary before finishing.':
      'السياق الإضافي اختياري ويبقى على هذا الجهاز. راجع حدود السلامة قبل الإنهاء.',
  'Setup progress': 'تقدم الإعداد',
  'Step 1 of 4': 'الخطوة ١ من ٤',
  'Step 2 of 4': 'الخطوة ٢ من ٤',
  'Step 3 of 4': 'الخطوة ٣ من ٤',
  'Step 4 of 4': 'الخطوة ٤ من ٤',
  'Usual activity': 'النشاط المعتاد',
  'Back': 'رجوع',
  'Finish setup': 'إنهاء الإعداد',
  'Your private starting point is ready': 'نقطة بدايتك الخاصة جاهزة',
  'BIL saved your profile and starting targets on this device.':
      'حفظ BIL ملفك وأهداف البداية على هذا الجهاز.',
  'BIL does not have a comparable daily measurement yet, so it will not claim a trend.':
      'لا يملك BIL قياسًا يوميًا قابلًا للمقارنة بعد، لذلك لن يدّعي وجود اتجاه.',
  'Record first check-in': 'سجّل أول قياس يومي',
  'Daily return summary': 'ملخص العودة اليومية',
  'Start today calmly': 'ابدأ اليوم بهدوء',
  'Continue today': 'تابع يومك',
  'Today is covered': 'اكتمل ما يلزم اليوم',
  'Welcome back — start with today': 'مرحبًا بعودتك — ابدأ من اليوم',
  'No backfill is required. Your earlier local records remain usable; today can be a fresh observation.':
      'لا يلزم ملء الأيام الماضية. تظل سجلاتك المحلية السابقة مفيدة، ويمكن أن يكون اليوم ملاحظة جديدة.',
  'Meals': 'الوجبات',
  'recorded': 'مسجّل',
  'missing': 'غير مسجّل',
  'What changed': 'ما الذي تغير',
  'Important missing evidence': 'الأدلة المهمة الناقصة',
  'No corrective action is needed from the evidence recorded today.':
      'لا يلزم إجراء تصحيحي وفق الأدلة المسجلة اليوم.',
  'Today could not read all local data':
      'تعذر على صفحة اليوم قراءة كل البيانات المحلية',
  'No current insight is shown because it may be stale. Existing records remain in local storage; retry when storage is available.':
      'لا تظهر رؤية حالية لأنها قد تكون قديمة. تظل السجلات الموجودة في التخزين المحلي؛ حاول مجددًا عندما يصبح التخزين متاحًا.',
  'Build your first comparable trend': 'ابنِ أول اتجاه قابل للمقارنة',
  'One measurement establishes a starting point. BIL waits for more comparable days before describing a trend.':
      'يحدد قياس واحد نقطة البداية. ينتظر BIL أيامًا أكثر قابلية للمقارنة قبل وصف أي اتجاه.',
  'Record first weight': 'سجّل أول وزن',
  'Your favorites will stay one tap away': 'ستبقى مفضلاتك على بُعد نقرة',
  'Favorite any food you trust to make future logging faster.':
      'أضف أي طعام تثق به إلى المفضلة لتسريع التسجيل لاحقًا.',
  'Recent foods appear after your first log':
      'تظهر الأطعمة الأخيرة بعد أول تسجيل',
  'BIL ranks foods you actually use without uploading your history.':
      'يرتب BIL الأطعمة التي تستخدمها فعليًا دون رفع سجلك.',
  'No local food matches this search': 'لا يطابق البحث أي طعام محلي',
  'BIL will not invent a match. Create a custom food from verified label evidence.':
      'لن يختلق BIL نتيجة. أنشئ طعامًا مخصصًا من بيانات الملصق الموثوقة.',
  'Browse all foods': 'تصفح كل الأطعمة',
  'Add food from label': 'أضف طعامًا من الملصق',
  'Gender (male/female)': 'الجنس البيولوجي (ذكر/أنثى)',
  'I understand BIL provides general information, not medical advice.':
      'أفهم أن BIL يقدم معلومات عامة وليس نصيحة طبية.',
  'Goal': 'الهدف',
  'Lose weight': 'خسارة الوزن',
  'Maintain weight': 'الحفاظ على الوزن',
  'Gain weight': 'زيادة الوزن',
  'Age': 'العمر',
  'Height (cm)': 'الطول (سم)',
  'Current weight (kg)': 'الوزن الحالي (كجم)',
  'Goal weight (kg)': 'الوزن المستهدف (كجم)',
  'Activity level': 'مستوى النشاط',
  'Add Daily Entry': 'إضافة سجل يومي',
  'Today': 'اليوم',
  'Diary': 'اليوميات',
  'Discover': 'اكتشف',
  'Progress': 'التقدم',
  'Insights': 'الرؤى',
  'More': 'المزيد',
  'Daily check-in': 'القياس اليومي',
  'Life context': 'سياق الحياة',
  'Water total': 'إجمالي الماء',
  'Water data unavailable': 'بيانات الماء غير متاحة',
  'Meals unavailable': 'بيانات الوجبات غير متاحة',
  'No meals for this day.': 'لا توجد وجبات لهذا اليوم.',
  'Quantity': 'الكمية',
  'Update': 'تحديث',
  'Meal saved locally.': 'تم حفظ الوجبة محليًا.',
  'Fiber': 'الألياف',
  'Sodium': 'الصوديوم',
  'Potassium': 'البوتاسيوم',
  'Magnesium': 'المغنيسيوم',
  'Calcium': 'الكالسيوم',
  'Sugar': 'السكر',
  'Search foods': 'ابحث عن طعام',
  'One best action': 'أفضل إجراء واحد',
  'Data honesty': 'موثوقية البيانات',
  'What changed today?': 'ما الذي تغير اليوم؟',
  'Body Twin': 'توأم الجسم',
  'Weekly review': 'المراجعة الأسبوعية',
  'Share Studio': 'استوديو المشاركة',
  'Create a privacy-safe progress image. Weight stays hidden.':
      'أنشئ صورة تقدم تحمي خصوصيتك. يظل الوزن مخفيًا.',
  'Challenges': 'التحديات',
  'Behavior-first private challenges with evidence-based progress.':
      'تحديات خاصة تركّز على السلوك ويُحسب تقدمها من الأدلة.',
  'Targets and plan': 'الأهداف والخطة',
  'Complete your profile first.': 'أكمل ملفك الشخصي أولًا.',
  'Enter whole-number targets in every field.':
      'أدخل أهدافًا بأرقام صحيحة في جميع الحقول.',
  'Plan saved. Historical records were not changed.':
      'تم حفظ الخطة. لم تتغير السجلات التاريخية.',
  'We recommend…': 'نوصي بـ…',
  'BMR': 'معدل الأيض الأساسي',
  'TDEE': 'إجمالي الإنفاق اليومي',
  'kcal': 'سعرة',
  'plan': 'خطة',
  'lose': 'خسارة',
  'maintain': 'ثبات',
  'gain': 'زيادة',
  'Confidence starts formula-based. Consistent weight and complete meal records are required before observed estimates become useful.':
      'تبدأ الثقة اعتمادًا على المعادلة. نحتاج إلى قياسات وزن منتظمة وسجلات وجبات مكتملة قبل أن تصبح التقديرات المرصودة مفيدة.',
  'Calories (kcal)': 'السعرات (سعرة)',
  'Protein (g)': 'البروتين (غ)',
  'Carbohydrates (g)': 'الكربوهيدرات (غ)',
  'Fat (g)': 'الدهون (غ)',
  'Fiber (g)': 'الألياف (غ)',
  'Water (ml)': 'الماء (مل)',
  'Using recommendation': 'باستخدام التوصية',
  'versus recommendation. Changing this may alter adherence and scenario interpretations.':
      'مقارنة بالتوصية. قد يؤثر التغيير في الالتزام وتفسير السيناريوهات.',
  'Saving…': 'جارٍ الحفظ…',
  'Save plan': 'حفظ الخطة',
  'Reset to recommended': 'العودة إلى الموصى به',
  'BIL does not recommend faster change as inherently better. If you have medical needs, pregnancy, an eating-disorder history, or clinician-directed targets, consult a qualified professional.':
      'لا يعتبر BIL التغيير الأسرع أفضل بطبيعته. عند وجود احتياجات طبية أو حمل أو تاريخ اضطراب أكل أو أهداف يحددها مختص، استشر مختصًا مؤهلًا.',
  'Personal experiments': 'التجارب الشخصية',
  'New experiment': 'تجربة جديدة',
  'Experiments are structured personal observations, not medical proof. Change one variable when practical and record missing data and limitations.':
      'التجارب ملاحظات شخصية منظمة وليست إثباتًا طبيًا. غيّر عاملًا واحدًا عندما يكون ذلك عمليًا وسجّل البيانات الناقصة والقيود.',
  'No experiment yet. Start with a cautious, measurable question such as whether a consistent protein breakfast affects your reported satiety.':
      'لا توجد تجربة بعد. ابدأ بسؤال حذر وقابل للقياس، مثل تأثير إفطار ثابت غني بالبروتين في شعورك المسجل بالشبع.',
  'No result recorded': 'لم تُسجل نتيجة',
  'insufficient': 'غير كافية',
  'low': 'منخفضة',
  'moderate': 'متوسطة',
  'confidence': 'ثقة',
  'adherence': 'التزام',
  'Active': 'نشطة',
  'required': 'المطلوب',
  'not specified': 'غير محدد',
  'Delete experiment': 'حذف التجربة',
  'Design an observation': 'صمّم ملاحظة',
  'Hypothesis': 'الفرضية',
  'One changed variable': 'عامل واحد متغير',
  'Factors to keep consistent': 'العوامل المطلوب تثبيتها',
  'Required data': 'البيانات المطلوبة',
  'Duration (3–90 days)': 'المدة (3–90 يومًا)',
  'Start': 'ابدأ',
  'Record observation': 'سجّل الملاحظة',
  'What did you observe?': 'ماذا لاحظت؟',
  'Adherence (0–100%)': 'الالتزام (0–100٪)',
  'Missing data and limitations': 'البيانات الناقصة والقيود',
  'Insufficient evidence': 'أدلة غير كافية',
  'Low confidence': 'ثقة منخفضة',
  'Moderate confidence': 'ثقة متوسطة',
  'This result is a personal observation, not medical proof.':
      'هذه النتيجة ملاحظة شخصية وليست إثباتًا طبيًا.',
  'Save observation': 'حفظ الملاحظة',
  'Close': 'إغلاق',
  'Local data export copied to the clipboard.':
      'تم نسخ تصدير البيانات المحلية إلى الحافظة.',
  'Reset all local data?': 'هل تريد حذف كل البيانات المحلية؟',
  'This permanently removes your profile, goals, logs, meals, custom foods, and settings. Type RESET to continue.':
      'سيؤدي هذا إلى حذف ملفك وأهدافك وسجلاتك ووجباتك وأطعمتك المخصصة وإعداداتك نهائيًا. اكتب RESET للمتابعة.',
  'Reset': 'حذف البيانات',
  'High contrast': 'تباين مرتفع',
  'Increase separation between text, controls, and surfaces.':
      'زيادة التمييز بين النصوص وعناصر التحكم والأسطح.',
  'Reduce motion': 'تقليل الحركة',
  'Minimize nonessential interface animation.':
      'تقليل حركات الواجهة غير الضرورية.',
  'Compare recommendations, assumptions, and your overrides.':
      'قارن التوصيات والافتراضات وتعديلاتك.',
  'Decision Memory': 'ذاكرة القرارات',
  'Review, rate, disable, or delete remembered actions.':
      'راجع الإجراءات المتذكّرة وقيّمها أو عطّلها أو احذفها.',
  'Test a cautious hypothesis and record limitations.':
      'اختبر فرضية حذرة وسجّل القيود.',
  'Your data remains on this device.': 'تبقى بياناتك على هذا الجهاز.',
  'BIL stores profile, weight, meals, foods, water, and preferences locally in SQLite. No data is uploaded while cloud services are disabled.':
      'يحفظ BIL الملف الشخصي والوزن والوجبات والأطعمة والماء والتفضيلات محليًا في SQLite. لا تُرفع أي بيانات ما دامت الخدمات السحابية معطلة.',
  'BIL provides general tracking information and cautious hypotheses. It does not diagnose, treat, or replace advice from a qualified healthcare professional.':
      'يقدم BIL معلومات متابعة عامة وفرضيات حذرة. لا يشخّص أو يعالج ولا يحل محل نصيحة مختص صحي مؤهل.',
  'Copy a JSON export to the clipboard.': 'انسخ تصدير JSON إلى الحافظة.',
  'Connected capabilities': 'الخدمات المتصلة',
  'Account': 'الحساب',
  'Secure account sign-in and registration are available.':
      'تسجيل الدخول وإنشاء الحساب الآمنان متاحان.',
  'Requires Supabase client configuration.': 'يتطلب إعداد عميل Supabase.',
  'Ask BIL': 'اسأل BIL',
  'Subscriptions and purchases': 'الاشتراكات والمشتريات',
  'Community': 'المجتمع',
  'Coach platform': 'منصة المختص',
  'Remote update channel': 'قناة التحديث البعيد',
  'Configuration found, but verified registration/session activation is not enabled in this build.':
      'تم العثور على إعدادات، لكن التسجيل والجلسات الموثقة غير مفعّلة في هذا الإصدار.',
  'Requires Supabase client configuration and the BIL server boundary.':
      'يتطلب إعداد عميل Supabase وحدود خادم BIL.',
  'Configuration found, but verified outbox/inbox activation is not enabled in this build.':
      'تم العثور على إعدادات، لكن مزامنة الصادر والوارد الموثقة غير مفعّلة في هذا الإصدار.',
  'Local Mode is active. No data is uploaded.':
      'الوضع المحلي نشط. لا تُرفع أي بيانات.',
  'Server endpoint found, but the consent and rate-limit adapter is not activated.':
      'تم العثور على عنوان الخادم، لكن طبقة الموافقة وتحديد المعدل غير مفعّلة.',
  'Requires a server-side AI proxy. Model secrets are never accepted by the client.':
      'يتطلب وسيط ذكاء اصطناعي على الخادم. لا يقبل التطبيق أسرار النموذج.',
  'Payment configuration exists, but verified receipt/webhook activation is pending.':
      'إعداد الدفع موجود، لكن تفعيل الإيصالات وإشعارات الخادم الموثقة ما زال معلقًا.',
  'Purchases are not configured. No payment details are collected.':
      'المشتريات غير معدّة. لا تُجمع أي بيانات دفع.',
  'Requires authenticated identities, consent, moderation, and enforced server-side access policies.':
      'يتطلب هويات موثقة وموافقة وإشرافًا وسياسات وصول مفروضة على الخادم.',
  'Remote signed update configuration is not configured; platform stores remain authoritative.':
      'إعداد التحديث البعيد الموقّع غير مهيأ؛ تظل متاجر المنصات هي المرجع.',
  'Add weight': 'إضافة وزن',
  'Edit weight': 'تعديل الوزن',
  'Delete weight?': 'هل تريد حذف الوزن؟',
  'from history?': 'من السجل؟',
  'Could not load weight history': 'تعذر تحميل سجل الوزن',
  'More data needed': 'نحتاج إلى مزيد من البيانات',
  'BIL account': 'حساب BIL',
  'Your data, on your terms': 'بياناتك بشروطك',
  'Cloud accounts are optional. Local Mode remains fully usable and keeps data on this device.':
      'الحساب السحابي اختياري. يظل الوضع المحلي كامل الاستخدام ويحفظ البيانات على هذا الجهاز.',
  'Email': 'البريد الإلكتروني',
  'Password': 'كلمة المرور',
  'Show password': 'إظهار كلمة المرور',
  'Hide password': 'إخفاء كلمة المرور',
  'Sign in': 'تسجيل الدخول',
  'Account sign-in remains disabled until the verified server auth boundary is initialized.':
      'يظل تسجيل الدخول معطلًا حتى تفعيل حدود المصادقة الموثقة على الخادم.',
  'Cloud accounts are not configured in this build. No credentials will be accepted or stored.':
      'الحسابات السحابية غير مهيأة في هذا الإصدار. لن تُقبل أو تُحفظ أي بيانات دخول.',
  'Continue in Local Mode': 'المتابعة في الوضع المحلي',
  'Manual barcode lookup': 'البحث اليدوي بالباركود',
  'Barcode digits': 'أرقام الباركود',
  'Enter an 8, 12, 13, or 14 digit GTIN. You can also use the camera scanner from the quick actions above.':
      'أدخل رقم GTIN من 8 أو 12 أو 13 أو 14 خانة، أو استخدم ماسح الكاميرا من الإجراءات السريعة أعلاه.',
  'Search': 'بحث',
  'Barcode not found locally': 'الباركود غير موجود محليًا',
  'BIL will not invent nutrition values. You can create a food from the product label and this barcode will be prefilled.':
      'لن يخترع BIL قيمًا غذائية. يمكنك إنشاء طعام من ملصق المنتج وسيُملأ هذا الباركود مسبقًا.',
  'Not now': 'ليس الآن',
  'English, Arabic, keyword, or barcode':
      'الاسم العربي أو الإنجليزي أو كلمة مفتاحية أو باركود',
  'Could not load foods': 'تعذر تحميل الأطعمة',
  'No matching foods. Create a custom food.':
      'لا توجد أطعمة مطابقة. أنشئ طعامًا مخصصًا.',
  'Source': 'المصدر',
  'Verified catalog record': 'سجل موثّق في الدليل',
  'Not independently verified': 'غير موثّق بصورة مستقلة',
  'Normalized serving': 'الحصة القياسية',
  'Updated locally': 'آخر تحديث محلي',
  'verified': 'موثّق',
  'unverified': 'غير موثّق',
  'starter': 'دليل البداية',
  'custom': 'مخصص',
  'user': 'أنشأه المستخدم',
  'Remove favorite': 'إزالة من المفضلة',
  'Add favorite': 'إضافة إلى المفضلة',
  'English name': 'الاسم الإنجليزي',
  'Arabic name': 'الاسم العربي',
  'Barcode': 'الباركود',
  'Serving size': 'حجم الحصة',
  'Serving unit': 'وحدة الحصة',
  'Carbohydrates': 'الكربوهيدرات',
  'Fat': 'الدهون',
  'Calories': 'السعرات',
  'Protein': 'البروتين',
  'Required': 'مطلوب',
  'Enter a non-negative number': 'أدخل رقمًا غير سالب',
  'Remember recommendation responses': 'تذكّر ردود التوصيات',
  'When off, BIL does not store new action responses or outcomes. Existing memories remain available for deletion.':
      'عند التعطيل، لا يحفظ BIL ردودًا أو نتائج جديدة. تظل الذكريات الحالية متاحة للحذف.',
  'No recommendation responses have been stored. BIL will never invent outcomes.':
      'لم تُحفظ ردود على التوصيات. لن يخترع BIL نتائج.',
  'accepted': 'مقبول',
  'done': 'تم',
  'notSuitable': 'غير مناسب',
  'dismissed': 'تم التجاهل',
  'Outcome': 'النتيجة',
  'Helpful?': 'هل كان مفيدًا؟',
  'of 5': 'من 5',
  'Helpfulness': 'درجة الفائدة',
  'Delete memory': 'حذف الذاكرة',
  'Edit': 'تعديل',
  'Scan food barcode': 'مسح باركود الطعام',
  'Toggle flashlight': 'تشغيل أو إطفاء الإضاءة',
  'Camera permission or scanner startup failed.':
      'تعذر بدء الكاميرا أو لم يُمنح الإذن.',
  'Camera permission was denied or the camera is unavailable. You can retry or use manual barcode entry.':
      'تم رفض إذن الكاميرا أو أن الكاميرا غير متاحة. يمكنك إعادة المحاولة أو إدخال الباركود يدويًا.',
  'Place the product barcode inside the frame. Nothing is uploaded.':
      'ضع باركود المنتج داخل الإطار. لا يتم رفع أي شيء.',
  'Scan with camera': 'المسح بالكاميرا',
  'Enter barcode manually': 'إدخال الباركود يدويًا',
  'Barcode result source': 'مصدر نتيجة الباركود',
  'No verified product matched this barcode.':
      'لا يوجد منتج موثّق مطابق لهذا الباركود.',
  'Analytics overview': 'نظرة عامة على التحليلات',
  'Since the previous check-in': 'منذ القياس السابق',
  'Measurement conditions differed': 'اختلفت ظروف القياس',
  'At least 14 observation days improve trends':
      'تحسن الاتجاهات بعد توفر 14 يوم ملاحظة على الأقل',
  'Record similar measurement conditions on more days':
      'سجّل القياس في ظروف متشابهة خلال أيام إضافية',
  'Weight is broadly stable since the previous check-in.':
      'الوزن مستقر عمومًا منذ القياس السابق.',
  'The scale changed, but one reading is not enough to justify a plan change.':
      'تغيّر رقم الميزان، لكن قراءة واحدة لا تكفي لتبرير تغيير الخطة.',
  'A modest change was recorded; the multi-day trend is more informative.':
      'سُجّل تغير محدود، ويبقى الاتجاه عبر عدة أيام أكثر فائدة.',
  'Water and glycogen': 'الماء والجليكوجين',
  'Digestive content': 'محتوى الجهاز الهضمي',
  'Measurement timing or conditions': 'توقيت القياس أو ظروفه',
  'Incomplete food logging': 'عدم اكتمال تسجيل الطعام',
  'Small daily variation can mask the underlying trend':
      'قد يخفي التذبذب اليومي البسيط الاتجاه الأساسي',
  'Quick Add': 'إضافة سريعة',
  'Enter a valid 8 to 14 digit barcode': 'أدخل باركود صحيحًا من 8 إلى 14 رقمًا',
  'Could not save this food. Review the values and try again.':
      'تعذر حفظ هذا الطعام. راجع القيم وحاول مرة أخرى.',
  'Could not delete this food. Try again.':
      'تعذر حذف هذا الطعام. حاول مرة أخرى.',
  'A food with this barcode already exists.': 'يوجد بالفعل طعام بهذا الباركود.',
  'Unavailable until the server-side AI consent and rate-limit boundary is configured.':
      'غير متاح حتى إعداد حدود موافقة الذكاء الاصطناعي وتحديد المعدل على الخادم.',
  'Choose report week': 'اختر أسبوع التقرير',
  'GO PREMIUM': 'الترقية إلى Premium',
  'Open nutrition importer': 'فتح مستورد التغذية',
  'Connect a supported app or device to bring saved activity into your weekly picture.':
      'اربط تطبيقًا أو جهازًا مدعومًا لإضافة النشاط المحفوظ إلى ملخصك الأسبوعي.',
  'Connect apps and devices': 'ربط التطبيقات والأجهزة',
  'Continue to log in every day to keep your streak going.':
      'واصل التسجيل يوميًا للحفاظ على سلسلتك.',
  'No foods logged': 'لا توجد أطعمة مسجلة',
};
