part of 'app_localizations.dart';

const _appLocaleAr = {
  'app_title': 'BIL – Body Intelligence Log',
  'welcome_back': 'مرحبًا بك من جديد',
  'dashboard': 'لوحة القيادة',
  'daily_log': 'السجل اليومي',
  'nutrition': 'التغذية',
  'history': 'السجل',
  'analytics': 'التحليلات',
  'settings': 'الإعدادات',
  'profile': 'الملف الشخصي',
  'weight': 'الوزن',
  'calories': 'السعرات',
  'protein': 'البروتين',
  'water': 'الماء',
  'save': 'حفظ',
  'onboarding_title': 'مرحبًا بك في BIL',
  'onboarding_body': 'يُحوِّل BIL بياناتك إلى رؤى عملية ومحددة.',
  'start': 'ابدأ',
  'next': 'التالي',
  'language': 'اللغة',
  'appearance': 'المظهر',
  'light': 'فاتح',
  'dark': 'داكن',
  'system': 'النظام',
  'english': 'الإنجليزية',
  'arabic': 'العربية',
  'profile_complete': 'اكتمال الملف الشخصي',
  'add_weight': 'إضافة وزن',
  'weight_history': 'سجل الوزن',
  'food_search': 'بحث عن الأطعمة',
  'custom_food': 'طعام مخصص',
  'daily_insights': 'الرؤى اليومية',
  'empty_state': 'لا توجد بيانات بعد. ابدأ بإضافة وزنك أو وجبتك الأولى.',
  'primary_navigation': 'التنقل الرئيسي',
  'quick_add': 'إضافة سريعة',
  'invalid_link':
      'لا يمكن فتح هذا الرابط بأمان. ارجع إلى لوحة القيادة وحاول مرة أخرى.',
  'french': 'الفرنسية',
  'spanish': 'الإسبانية',
  'turkish': 'التركية',
};

const _appLocaleEn = {
  'app_title': 'BIL – Body Intelligence Log',
  'welcome_back': 'Welcome back',
  'dashboard': 'Dashboard',
  'daily_log': 'Daily Log',
  'nutrition': 'Nutrition',
  'history': 'History',
  'analytics': 'Analytics',
  'settings': 'Settings',
  'profile': 'Profile',
  'weight': 'Weight',
  'calories': 'Calories',
  'protein': 'Protein',
  'water': 'Water',
  'save': 'Save',
  'onboarding_title': 'Welcome to BIL',
  'onboarding_body': 'BIL turns your data into practical, explainable insight.',
  'start': 'Start',
  'next': 'Next',
  'language': 'Language',
  'appearance': 'Appearance',
  'light': 'Light',
  'dark': 'Dark',
  'system': 'System',
  'english': 'English',
  'arabic': 'Arabic',
  'profile_complete': 'Profile complete',
  'add_weight': 'Add weight',
  'weight_history': 'Weight history',
  'food_search': 'Food search',
  'custom_food': 'Custom food',
  'daily_insights': 'Daily insights',
  'empty_state': 'No data yet. Start by adding your first weight or meal.',
  'primary_navigation': 'Primary navigation',
  'quick_add': 'Quick Add',
  'invalid_link':
      'This link cannot be opened safely. Return to the dashboard and try again.',
  'french': 'French',
  'spanish': 'Spanish',
  'turkish': 'Turkish',
};

const _appLocaleFr = {
  'app_title': 'BIL – Body Intelligence Log',
  'welcome_back': 'Bon retour',
  'dashboard': 'Tableau de bord',
  'daily_log': 'Journal quotidien',
  'nutrition': 'Nutrition',
  'history': 'Historique',
  'analytics': 'Analyses',
  'settings': 'Paramètres',
  'profile': 'Profil',
  'weight': 'Poids',
  'calories': 'Calories',
  'protein': 'Protéines',
  'water': 'Eau',
  'save': 'Enregistrer',
  'onboarding_title': 'Bienvenue dans BIL',
  'onboarding_body':
      'BIL transforme vos données en informations pratiques et explicables.',
  'start': 'Commencer',
  'next': 'Suivant',
  'language': 'Langue',
  'appearance': 'Apparence',
  'light': 'Clair',
  'dark': 'Sombre',
  'system': 'Système',
  'english': 'Anglais',
  'arabic': 'Arabe',
  'profile_complete': 'Profil complété',
  'add_weight': 'Ajouter un poids',
  'weight_history': 'Historique du poids',
  'food_search': 'Rechercher un aliment',
  'custom_food': 'Aliment personnalisé',
  'daily_insights': 'Aperçus du jour',
  'empty_state':
      'Aucune donnée. Commencez par ajouter votre poids ou votre premier repas.',
  'primary_navigation': 'Navigation principale',
  'quick_add': 'Ajout rapide',
  'invalid_link':
      'Ce lien ne peut pas être ouvert en toute sécurité. Revenez au tableau de bord et réessayez.',
  'french': 'Français',
  'spanish': 'Espagnol',
  'turkish': 'Turc',
};

const _appLocaleEs = {
  'app_title': 'BIL – Body Intelligence Log',
  'welcome_back': 'Te damos la bienvenida de nuevo',
  'dashboard': 'Panel',
  'daily_log': 'Diario',
  'nutrition': 'Nutrición',
  'history': 'Historial',
  'analytics': 'Análisis',
  'settings': 'Ajustes',
  'profile': 'Perfil',
  'weight': 'Peso',
  'calories': 'Calorías',
  'protein': 'Proteínas',
  'water': 'Agua',
  'save': 'Guardar',
  'onboarding_title': 'Te damos la bienvenida a BIL',
  'onboarding_body':
      'BIL convierte tus datos en información práctica y explicable.',
  'start': 'Empezar',
  'next': 'Siguiente',
  'language': 'Idioma',
  'appearance': 'Apariencia',
  'light': 'Claro',
  'dark': 'Oscuro',
  'system': 'Sistema',
  'english': 'Inglés',
  'arabic': 'Árabe',
  'profile_complete': 'Perfil completo',
  'add_weight': 'Añadir peso',
  'weight_history': 'Historial de peso',
  'food_search': 'Buscar alimentos',
  'custom_food': 'Alimento personalizado',
  'daily_insights': 'Información diaria',
  'empty_state':
      'Aún no hay datos. Empieza añadiendo tu peso o tu primera comida.',
  'primary_navigation': 'Navegación principal',
  'quick_add': 'Añadir rápido',
  'invalid_link':
      'Este enlace no se puede abrir de forma segura. Vuelve al panel e inténtalo de nuevo.',
  'french': 'Francés',
  'spanish': 'Español',
  'turkish': 'Turco',
};

const _appLocaleTr = {
  'app_title': 'BIL – Body Intelligence Log',
  'welcome_back': 'Tekrar hoş geldiniz',
  'dashboard': 'Gösterge paneli',
  'daily_log': 'Günlük kayıt',
  'nutrition': 'Beslenme',
  'history': 'Geçmiş',
  'analytics': 'Analizler',
  'settings': 'Ayarlar',
  'profile': 'Profil',
  'weight': 'Kilo',
  'calories': 'Kalori',
  'protein': 'Protein',
  'water': 'Su',
  'save': 'Kaydet',
  'onboarding_title': "BIL'e hoş geldiniz",
  'onboarding_body':
      'BIL, verilerinizi pratik ve açıklanabilir içgörülere dönüştürür.',
  'start': 'Başla',
  'next': 'Sonraki',
  'language': 'Dil',
  'appearance': 'Görünüm',
  'light': 'Açık',
  'dark': 'Koyu',
  'system': 'Sistem',
  'english': 'İngilizce',
  'arabic': 'Arapça',
  'profile_complete': 'Profil tamamlandı',
  'add_weight': 'Kilo ekle',
  'weight_history': 'Kilo geçmişi',
  'food_search': 'Yiyecek ara',
  'custom_food': 'Özel yiyecek',
  'daily_insights': 'Günlük içgörüler',
  'empty_state':
      'Henüz veri yok. İlk kilonuzu veya öğününüzü ekleyerek başlayın.',
  'primary_navigation': 'Ana gezinme',
  'quick_add': 'Hızlı ekle',
  'invalid_link':
      'Bu bağlantı güvenli bir şekilde açılamıyor. Gösterge paneline dönüp yeniden deneyin.',
  'french': 'Fransızca',
  'spanish': 'İspanyolca',
  'turkish': 'Türkçe',
};
