// GENERATED FOR THE ADMIN NOTIFICATION SURFACE.
// Keep every entry complete across all 25 production locales.
abstract final class AdminNotificationRuntimeCopy {
  static const supported = <String>{
    "ar",
    "en",
    "fr",
    "es",
    "tr",
    "de",
    "it",
    "pt-BR",
    "pt-PT",
    "ur",
    "fa",
    "hi",
    "id",
    "ms",
    "ja",
    "ko",
    "zh-Hans",
    "zh-Hant",
    "ru",
    "bn",
    "vi",
    "th",
    "pl",
    "nl",
    "uk",
  };
  static const values = <String, Map<String, String>>{
    "Send a BIL notification": {
      "ar": "إرسال إشعار من BIL",
      "en": "Send a BIL notification",
      "fr": "Envoyer une notification BIL",
      "es": "Enviar una notificación de BIL",
      "tr": "BIL bildirimi gönder",
      "de": "Senden Sie eine BIL-Benachrichtigung",
      "it": "Invia una notifica BIL",
      "pt-BR": "Envie uma notificação BIL",
      "pt-PT": "Enviar uma notificação BIL",
      "ur": "BIL اطلاع بھیجیں۔",
      "fa": "یک اعلان BIL ارسال کنید",
      "hi": "एक BIL अधिसूचना भेजें",
      "id": "Kirim pemberitahuan BIL",
      "ms": "Hantar pemberitahuan BIL",
      "ja": "BIL 通知を送信する",
      "ko": "BIL 알림 보내기",
      "zh-Hans": "发送 BIL 通知",
      "zh-Hant": "發送 BIL 通知",
      "ru": "Отправить уведомление BIL",
      "bn": "একটি BIL বিজ্ঞপ্তি পাঠান",
      "vi": "Gửi thông báo BIL",
      "th": "ส่งการแจ้งเตือน BIL",
      "pl": "Wyślij powiadomienie BIL",
      "nl": "Verzend een BIL-melding",
      "uk": "Надіслати сповіщення BIL",
    },
    "Choose a polished preset or write your own message, then send it to everyone or one exact account.": {
      "ar":
          "اختر رسالة جاهزة بصياغة راقية أو اكتب رسالتك، ثم أرسلها للجميع أو إلى حساب محدد.",
      "en":
          "Choose a polished preset or write your own message, then send it to everyone or one exact account.",
      "fr":
          "Choisissez un message soigné ou rédigez le vôtre, puis envoyez-le à tous ou à un compte précis.",
      "es":
          "Elige un mensaje cuidado o escribe el tuyo y envíalo a todos o a una cuenta concreta.",
      "tr":
          "Özenli bir hazır mesaj seçin veya kendi mesajınızı yazın; ardından herkese ya da belirli bir hesaba gönderin.",
      "de":
          "Wählen Sie eine ausgefeilte Voreinstellung oder schreiben Sie Ihre eigene Nachricht und senden Sie sie dann an alle oder an ein bestimmtes Konto.",
      "it":
          "Scegli un'impostazione predefinita raffinata o scrivi il tuo messaggio, quindi invialo a tutti o a un account esatto.",
      "pt-BR":
          "Escolha uma predefinição sofisticada ou escreva sua própria mensagem e envie-a para todos ou para uma conta exata.",
      "pt-PT":
          "Escolha uma predefinição sofisticada ou escreva a sua própria mensagem e envie-a para todos ou para uma conta exata.",
      "ur":
          "ایک پالش پیش سیٹ کا انتخاب کریں یا اپنا پیغام خود لکھیں، پھر اسے ہر کسی یا ایک درست اکاؤنٹ کو بھیجیں۔",
      "fa":
          "یک پیش تنظیم صیقلی انتخاب کنید یا پیام خود را بنویسید، سپس آن را به همه یا یک حساب دقیق ارسال کنید.",
      "hi":
          "एक परिष्कृत प्रीसेट चुनें या अपना स्वयं का संदेश लिखें, फिर इसे सभी को या किसी एक खाते को भेजें।",
      "id":
          "Pilih preset yang telah disempurnakan atau tulis pesan Anda sendiri, lalu kirimkan ke semua orang atau satu akun yang sama.",
      "ms":
          "Pilih pratetap yang digilap atau tulis mesej anda sendiri, kemudian hantarkannya kepada semua orang atau satu akaun yang tepat.",
      "ja": "洗練されたプリセットを選択するか、独自のメッセージを作成して、全員または 1 つのアカウントに送信します。",
      "ko": "세련된 사전 설정을 선택하거나 자신만의 메시지를 작성한 다음 모든 사람 또는 하나의 정확한 계정으로 보내세요.",
      "zh-Hans": "选择一个精美的预设或编写您自己的消息，然后将其发送给每个人或一个特定帐户。",
      "zh-Hant": "選擇一個精美的預設或編寫您自己的訊息，然後將其發送給每個人或一個特定帳戶。",
      "ru":
          "Выберите готовый пресет или напишите собственное сообщение, а затем отправьте его всем или одному конкретному аккаунту.",
      "bn":
          "একটি পালিশ প্রিসেট চয়ন করুন বা আপনার নিজের বার্তা লিখুন, তারপর এটি সবাইকে বা একটি সঠিক অ্যাকাউন্টে পাঠান৷",
      "vi":
          "Chọn một cài đặt trước tinh tế hoặc viết tin nhắn của riêng bạn, sau đó gửi cho mọi người hoặc một tài khoản chính xác.",
      "th":
          "เลือกพรีเซ็ตที่สวยงามหรือเขียนข้อความของคุณเอง จากนั้นส่งให้ทุกคนหรือบัญชีเดียว",
      "pl":
          "Wybierz dopracowane ustawienie wstępne lub napisz własną wiadomość, a następnie wyślij ją do wszystkich lub jednego konkretnego konta.",
      "nl":
          "Kies een gepolijste preset of schrijf uw eigen bericht en stuur het vervolgens naar iedereen of naar één exact account.",
      "uk":
          "Виберіть досконалий стиль або напишіть власне повідомлення, а потім надішліть його всім або одному облікового запису.",
    },
    "Compensation message": {
      "ar": "رسالة تعويض",
      "en": "Compensation message",
      "fr": "Message de compensation",
      "es": "Mensaje de compensación",
      "tr": "Telafi mesajı",
      "de": "Entschädigungsnachricht",
      "it": "Messaggio di compensazione",
      "pt-BR": "Mensagem de compensação",
      "pt-PT": "Mensagem de compensação",
      "ur": "معاوضے کا پیغام",
      "fa": "پیام جبران خسارت",
      "hi": "मुआवज़ा संदेश",
      "id": "Pesan kompensasi",
      "ms": "Mesej pampasan",
      "ja": "補償メッセージ",
      "ko": "보상 메시지",
      "zh-Hans": "补偿信息",
      "zh-Hant": "補償資訊",
      "ru": "Компенсационное сообщение",
      "bn": "ক্ষতিপূরণ বার্তা",
      "vi": "Tin nhắn bồi thường",
      "th": "ข้อความชดเชย",
      "pl": "Wiadomość o wynagrodzeniu",
      "nl": "Compensatie bericht",
      "uk": "Повідомлення про компенсацію",
    },
    "A considerate message that values the member’s trust.": {
      "ar": "صياغة لبقة تقدّر ثقة المستخدم واهتمامه.",
      "en": "A considerate message that values the member’s trust.",
      "fr": "Un message attentionné qui valorise la confiance du membre.",
      "es": "Un mensaje considerado que valora la confianza del miembro.",
      "tr": "Üyenin güvenine değer veren düşünceli bir mesaj.",
      "de":
          "Eine rücksichtsvolle Nachricht, die das Vertrauen des Mitglieds wertschätzt.",
      "it": "Un messaggio premuroso che valorizza la fiducia del membro.",
      "pt-BR": "Uma mensagem atenciosa que valoriza a confiança do associado.",
      "pt-PT": "Uma mensagem atenciosa que valoriza a confiança do associado.",
      "ur": "ایک قابل غور پیغام جو ممبر کے اعتماد کی قدر کرتا ہے۔",
      "fa": "پیامی قابل توجه که برای اعتماد اعضا ارزش قائل است.",
      "hi": "एक विचारशील संदेश जो सदस्य के विश्वास को महत्व देता है।",
      "id": "Pesan penuh perhatian yang menghargai kepercayaan anggota.",
      "ms": "Mesej bertimbang rasa yang menghargai kepercayaan ahli.",
      "ja": "メンバーの信頼を大切にした思いやりのあるメッセージ。",
      "ko": "회원의 신뢰를 중요하게 생각하는 사려 깊은 메시지입니다.",
      "zh-Hans": "重视会员信任的体贴信息。",
      "zh-Hant": "重視會員信任的體貼資訊。",
      "ru": "Внимательное сообщение, которое ценит доверие участника.",
      "bn": "একটি বিবেচ্য বার্তা যা সদস্যের বিশ্বাসকে মূল্য দেয়।",
      "vi": "Một thông điệp ân cần đánh giá cao sự tin tưởng của thành viên.",
      "th": "ข้อความที่คำนึงถึงคุณค่าของความไว้วางใจของสมาชิก",
      "pl": "Uprzejma wiadomość, która ceni zaufanie członka.",
      "nl": "Een attente boodschap die het vertrouwen van het lid waardeert.",
      "uk": "Уважне повідомлення, яке цінує довіру члена.",
    },
    "Gift message": {
      "ar": "رسالة هدية",
      "en": "Gift message",
      "fr": "Message cadeau",
      "es": "Mensaje de regalo",
      "tr": "Hediye mesajı",
      "de": "Geschenknachricht",
      "it": "Messaggio regalo",
      "pt-BR": "Mensagem de presente",
      "pt-PT": "Mensagem de oferta",
      "ur": "تحفہ پیغام",
      "fa": "پیام هدیه",
      "hi": "उपहार संदेश",
      "id": "Pesan hadiah",
      "ms": "Mesej hadiah",
      "ja": "ギフトメッセージ",
      "ko": "선물 메시지",
      "zh-Hans": "礼物留言",
      "zh-Hant": "禮物留言",
      "ru": "Подарочное сообщение",
      "bn": "উপহার বার্তা",
      "vi": "Tin nhắn quà tặng",
      "th": "ข้อความของขวัญ",
      "pl": "Wiadomość prezentowa",
      "nl": "Cadeau bericht",
      "uk": "Подарункове повідомлення",
    },
    "A warm BIL gift announcement with a premium tone.": {
      "ar": "إعلان هدية دافئ من BIL بصياغة فخمة.",
      "en": "A warm BIL gift announcement with a premium tone.",
      "fr": "Une annonce cadeau chaleureuse avec un ton haut de gamme.",
      "es": "Un anuncio de regalo cálido con un tono premium.",
      "tr": "Seçkin bir üslupla sıcak bir BIL hediye duyurusu.",
      "de": "Eine warme BIL-Geschenkankündigung mit erstklassigem Ton.",
      "it": "Un caldo annuncio regalo BIL con un tono premium.",
      "pt-BR": "Um anúncio de presente caloroso BIL com um tom premium.",
      "pt-PT": "Um anúncio de presente quente BIL com um tom premium.",
      "ur": "پریمیم ٹون کے ساتھ ایک گرم BIL گفٹ کا اعلان۔",
      "fa": "اعلان هدیه گرم BIL با لحن برتر.",
      "hi": "प्रीमियम टोन के साथ एक हार्दिक BIL उपहार की घोषणा।",
      "id": "Pengumuman hadiah BIL yang hangat dengan nada premium.",
      "ms": "Pengumuman hadiah BIL yang hangat dengan nada premium.",
      "ja": "プレミアムなトーンの温かみのある BIL ギフトのお知らせ。",
      "ko": "프리미엄 톤으로 따뜻한 BIL 선물 발표.",
      "zh-Hans": "温暖的 BIL 礼物公告，语气优质。",
      "zh-Hant": "溫暖的 BIL 禮物公告，語氣優質。",
      "ru": "Теплое объявление о подарке BIL в премиальном тоне.",
      "bn": "একটি প্রিমিয়াম টোন সহ একটি উষ্ণ BIL উপহারের ঘোষণা৷",
      "vi": "Thông báo quà tặng BIL ấm áp với tông màu cao cấp.",
      "th": "ประกาศของขวัญ BIL สุดอบอุ่น ด้วยโทนเสียงระดับพรีเมียม",
      "pl": "Ciepła zapowiedź prezentu BIL z tonem premium.",
      "nl": "Een warme BIL-cadeauaankondiging met een premium toon.",
      "uk": "Тепле оголошення про подарунок BIL із преміальним тоном.",
    },
    "Write a custom message": {
      "ar": "كتابة رسالة مخصصة",
      "en": "Write a custom message",
      "fr": "Rédiger un message personnalisé",
      "es": "Escribir un mensaje personalizado",
      "tr": "Özel bir mesaj yaz",
      "de": "Schreiben Sie eine benutzerdefinierte Nachricht",
      "it": "Scrivi un messaggio personalizzato",
      "pt-BR": "Escreva uma mensagem personalizada",
      "pt-PT": "Escreva uma mensagem personalizada",
      "ur": "حسب ضرورت پیغام لکھیں۔",
      "fa": "یک پیام سفارشی بنویسید",
      "hi": "एक कस्टम संदेश लिखें",
      "id": "Tulis pesan khusus",
      "ms": "Tulis mesej tersuai",
      "ja": "カスタムメッセージを書く",
      "ko": "맞춤 메시지 작성",
      "zh-Hans": "编写自定义消息",
      "zh-Hant": "編寫自訂訊息",
      "ru": "Напишите индивидуальное сообщение",
      "bn": "একটি কাস্টম বার্তা লিখুন",
      "vi": "Viết tin nhắn tùy chỉnh",
      "th": "เขียนข้อความที่กำหนดเอง",
      "pl": "Napisz niestandardową wiadomość",
      "nl": "Schrijf een aangepast bericht",
      "uk": "Напишіть власне повідомлення",
    },
    "Writing the message is required before sending is enabled.": {
      "ar": "كتابة النص إلزامية قبل تفعيل الإرسال.",
      "en": "Writing the message is required before sending is enabled.",
      "fr": "Le texte est obligatoire avant d’activer l’envoi.",
      "es": "El texto es obligatorio antes de habilitar el envío.",
      "tr": "Gönderim etkinleşmeden önce mesaj yazılması zorunludur.",
      "de":
          "Das Schreiben der Nachricht ist erforderlich, bevor das Senden aktiviert wird.",
      "it":
          "La scrittura del messaggio è necessaria prima che l'invio sia abilitato.",
      "pt-BR":
          "É necessário escrever a mensagem antes que o envio seja ativado.",
      "pt-PT": "É necessário escrever a mensagem antes de o envio ser ativado.",
      "ur": "بھیجنے کو فعال کرنے سے پہلے پیغام لکھنا ضروری ہے۔",
      "fa": "قبل از فعال شدن ارسال، نوشتن پیام الزامی است.",
      "hi": "भेजने को सक्षम करने से पहले संदेश लिखना आवश्यक है।",
      "id": "Menulis pesan diperlukan sebelum pengiriman diaktifkan.",
      "ms": "Menulis mesej diperlukan sebelum penghantaran didayakan.",
      "ja": "送信を有効にする前にメッセージを書き込む必要があります。",
      "ko": "전송이 활성화되기 전에 메시지를 작성해야 합니다.",
      "zh-Hans": "在启用发送之前需要写入消息。",
      "zh-Hant": "在啟用發送之前需要寫入訊息。",
      "ru": "Перед включением отправки необходимо написать сообщение.",
      "bn": "পাঠানো সক্ষম হওয়ার আগে বার্তাটি লিখতে হবে।",
      "vi": "Cần phải viết tin nhắn trước khi kích hoạt tính năng gửi.",
      "th": "จำเป็นต้องเขียนข้อความก่อนที่จะเปิดใช้งานการส่ง",
      "pl": "Aby możliwe było wysyłanie, wymagane jest napisanie wiadomości.",
      "nl":
          "Het schrijven van het bericht is vereist voordat verzenden wordt ingeschakeld.",
      "uk": "Перш ніж увімкнути надсилання, потрібно написати повідомлення.",
    },
    "Everyone": {
      "ar": "الجميع",
      "en": "Everyone",
      "fr": "Tous",
      "es": "Todos",
      "tr": "Herkes",
      "de": "Jeder",
      "it": "Tutti",
      "pt-BR": "Todos",
      "pt-PT": "Todos",
      "ur": "ہر کوئی",
      "fa": "همه",
      "hi": "हर कोई",
      "id": "Semuanya",
      "ms": "Semua orang",
      "ja": "みんな",
      "ko": "모두",
      "zh-Hans": "大家",
      "zh-Hant": "大家",
      "ru": "Все",
      "bn": "সবাই",
      "vi": "mọi người",
      "th": "ทุกคน",
      "pl": "Wszyscy",
      "nl": "Iedereen",
      "uk": "Всі",
    },
    "Confirm notification": {
      "ar": "تأكيد الإشعار",
      "en": "Confirm notification",
      "fr": "Confirmer la notification",
      "es": "Confirmar la notificación",
      "tr": "Bildirimi onayla",
      "de": "Benachrichtigung bestätigen",
      "it": "Conferma la notifica",
      "pt-BR": "Confirmar notificação",
      "pt-PT": "Confirmar notificação",
      "ur": "اطلاع کی تصدیق کریں۔",
      "fa": "اعلان را تایید کنید",
      "hi": "अधिसूचना की पुष्टि करें",
      "id": "Konfirmasikan pemberitahuan",
      "ms": "Sahkan pemberitahuan",
      "ja": "通知を確認する",
      "ko": "알림 확인",
      "zh-Hans": "确认通知",
      "zh-Hant": "確認通知",
      "ru": "Подтвердить уведомление",
      "bn": "বিজ্ঞপ্তি নিশ্চিত করুন",
      "vi": "Xác nhận thông báo",
      "th": "ยืนยันการแจ้งเตือน",
      "pl": "Potwierdź powiadomienie",
      "nl": "Bevestig de melding",
      "uk": "Підтвердити сповіщення",
    },
    "The notification will be delivered to:": {
      "ar": "سيُرسل الإشعار إلى:",
      "en": "The notification will be delivered to:",
      "fr": "La notification sera envoyée à :",
      "es": "La notificación se enviará a:",
      "tr": "Bildirim şu hedefe gönderilecek:",
      "de": "Die Benachrichtigung wird zugestellt an:",
      "it": "La notifica verrà recapitata a:",
      "pt-BR": "A notificação será entregue a:",
      "pt-PT": "A notificação será entregue a:",
      "ur": "نوٹیفکیشن ان پر پہنچا دیا جائے گا:",
      "fa": "اطلاعیه به آدرس زیر ارسال خواهد شد:",
      "hi": "अधिसूचना यहां पहुंचाई जाएगी:",
      "id": "Pemberitahuan akan dikirimkan ke:",
      "ms": "Pemberitahuan akan dihantar kepada:",
      "ja": "通知は次の宛先に配信されます。",
      "ko": "알림은 다음 주소로 전달됩니다.",
      "zh-Hans": "该通知将发送至：",
      "zh-Hant": "該通知將發送至：",
      "ru": "Уведомление будет доставлено:",
      "bn": "বিজ্ঞপ্তিটি এখানে বিতরণ করা হবে:",
      "vi": "Thông báo sẽ được gửi đến:",
      "th": "การแจ้งเตือนจะถูกส่งไปยัง:",
      "pl": "Zawiadomienie zostanie dostarczone na adres:",
      "nl": "De kennisgeving wordt verzonden naar:",
      "uk": "Повідомлення буде доставлено на адресу:",
    },
    "Send now": {
      "ar": "إرسال الآن",
      "en": "Send now",
      "fr": "Envoyer maintenant",
      "es": "Enviar ahora",
      "tr": "Şimdi gönder",
      "de": "Jetzt senden",
      "it": "Invia ora",
      "pt-BR": "Enviar agora",
      "pt-PT": "Enviar agora",
      "ur": "ابھی بھیجیں۔",
      "fa": "اکنون ارسال کنید",
      "hi": "अभी भेजें",
      "id": "Kirim sekarang",
      "ms": "Hantar sekarang",
      "ja": "今すぐ送信",
      "ko": "지금 보내기",
      "zh-Hans": "立即发送",
      "zh-Hant": "立即發送",
      "ru": "Отправить сейчас",
      "bn": "এখন পাঠান",
      "vi": "Gửi ngay bây giờ",
      "th": "ส่งตอนนี้",
      "pl": "Wyślij teraz",
      "nl": "Verstuur nu",
      "uk": "Надішліть зараз",
    },
    "No matching BIL account was found. Nothing was sent.": {
      "ar": "لم يوجد حساب BIL مطابق؛ لم يُرسل شيء.",
      "en": "No matching BIL account was found. Nothing was sent.",
      "fr": "Aucun compte BIL correspondant. Aucun envoi effectué.",
      "es": "No se encontró una cuenta BIL coincidente. No se envió nada.",
      "tr": "Eşleşen bir BIL hesabı bulunamadı. Hiçbir şey gönderilmedi.",
      "de":
          "Es wurde kein passendes BIL-Konto gefunden. Es wurde nichts gesendet.",
      "it":
          "Non è stato trovato alcun account BIL corrispondente. Non è stato inviato nulla.",
      "pt-BR":
          "Nenhuma conta BIL correspondente foi encontrada. Nada foi enviado.",
      "pt-PT":
          "Não foi encontrada nenhuma conta BIL correspondente. Nada foi enviado.",
      "ur": "کوئی مماثل BIL اکاؤنٹ نہیں ملا۔ کچھ نہیں بھیجا تھا۔",
      "fa": "هیچ حساب مطابق BIL یافت نشد. چیزی ارسال نشد.",
      "hi": "कोई मेल खाता BIL खाता नहीं मिला. कुछ भी नहीं भेजा गया.",
      "id": "Tidak ditemukan akun BIL yang cocok. Tidak ada yang dikirim.",
      "ms":
          "Tiada akaun BIL yang sepadan ditemui. Tiada apa-apa yang dihantar.",
      "ja": "一致する BIL アカウントが見つかりませんでした。何も送信されませんでした。",
      "ko": "일치하는 BIL 계정을 찾을 수 없습니다. 아무것도 전송되지 않았습니다.",
      "zh-Hans": "未找到匹配的 BIL 帐户。没有发送任何内容。",
      "zh-Hant": "未找到符合的 BIL 帳戶。沒有發送任何內容。",
      "ru":
          "Соответствующая учетная запись BIL не найдена. Ничего не было отправлено.",
      "bn": "কোন মিলিত BIL অ্যাকাউন্ট পাওয়া যায়নি. কিছুই পাঠানো হয়নি।",
      "vi": "Không tìm thấy tài khoản BIL phù hợp. Không có gì được gửi đi.",
      "th": "ไม่พบบัญชี BIL ที่ตรงกัน ไม่มีอะไรถูกส่งไป",
      "pl": "Nie znaleziono pasującego konta BIL. Nic nie zostało wysłane.",
      "nl":
          "Er is geen overeenkomend BIL-account gevonden. Er is niets verzonden.",
      "uk":
          "Не знайдено відповідного облікового запису BIL. Нічого не відправили.",
    },
    "Notification queued safely for {count} recipient(s).": {
      "ar": "تم تجهيز الإشعار بأمان لـ{count} مستلم.",
      "en": "Notification queued safely for {count} recipient(s).",
      "fr":
          "Notification mise en file en toute sécurité pour {count} destinataire(s).",
      "es":
          "Notificación preparada de forma segura para {count} destinatario(s).",
      "tr": "Bildirim {count} alıcı için güvenle sıraya alındı.",
      "de":
          "Benachrichtigung für {count}-Empfänger sicher in der Warteschlange.",
      "it": "Notifica accodata in modo sicuro per i destinatari {count}.",
      "pt-BR":
          "Notificação enfileirada com segurança para destinatário(s) {count}.",
      "pt-PT": "Notificação em fila de segurança para destinatário(s) {count}.",
      "ur": "{count} وصول کنندگان کے لیے اطلاع محفوظ طریقے سے قطار میں ہے۔",
      "fa": "اعلان به طور ایمن برای گیرنده(های) {count} در صف قرار گرفت.",
      "hi":
          "{count} प्राप्तकर्ताओं के लिए अधिसूचना सुरक्षित रूप से पंक्तिबद्ध है।",
      "id": "Pemberitahuan diantri dengan aman untuk penerima {count}.",
      "ms": "Pemberitahuan beratur dengan selamat untuk penerima {count}.",
      "ja": "通知は {count} 受信者のために安全にキューに入れられました。",
      "ko": "{count} 수신자를 위해 알림이 안전하게 대기열에 추가되었습니다.",
      "zh-Hans": "通知已安全排队等待 {count} 收件人。",
      "zh-Hant": "通知已安全排隊等待 {count} 收件者。",
      "ru":
          "Уведомление безопасно поставлено в очередь для получателей {count}.",
      "bn": "{count} প্রাপক(দের) জন্য বিজ্ঞপ্তি নিরাপদে সারিবদ্ধ।",
      "vi": "Thông báo được xếp hàng an toàn cho (những) người nhận {count}.",
      "th": "การแจ้งเตือนเข้าคิวอย่างปลอดภัยสำหรับผู้รับ {count}",
      "pl":
          "Powiadomienia bezpiecznie umieszczone w kolejce dla odbiorców {count}.",
      "nl":
          "Melding veilig in de wachtrij geplaatst voor {count}-ontvanger(s).",
      "uk": "Сповіщення безпечно поставлено в чергу для одержувачів {count}.",
    },
    "The notification was not sent. Review the details and try again.": {
      "ar": "لم يُرسل الإشعار. راجع التفاصيل وحاول مجددًا.",
      "en": "The notification was not sent. Review the details and try again.",
      "fr":
          "La notification n’a pas été envoyée. Vérifiez les détails et réessayez.",
      "es":
          "La notificación no se envió. Revisa los datos e inténtalo de nuevo.",
      "tr": "Bildirim gönderilmedi. Bilgileri kontrol edip yeniden deneyin.",
      "de":
          "Die Benachrichtigung wurde nicht gesendet. Überprüfen Sie die Details und versuchen Sie es erneut.",
      "it": "La notifica non è stata inviata. Controlla i dettagli e riprova.",
      "pt-BR":
          "A notificação não foi enviada. Revise os detalhes e tente novamente.",
      "pt-PT":
          "A notificação não foi enviada. Reveja os detalhes e tente novamente.",
      "ur": "اطلاع نہیں بھیجی گئی۔ تفصیلات کا جائزہ لیں اور دوبارہ کوشش کریں۔",
      "fa": "اطلاعیه ارسال نشد. جزئیات را مرور کنید و دوباره امتحان کنید.",
      "hi": "अधिसूचना नहीं भेजी गई. विवरण की समीक्षा करें और पुनः प्रयास करें.",
      "id": "Notifikasinya tidak terkirim. Tinjau detailnya dan coba lagi.",
      "ms": "Pemberitahuan tidak dihantar. Semak butiran dan cuba lagi.",
      "ja": "通知は送信されませんでした。詳細を確認して、再試行してください。",
      "ko": "알림이 전송되지 않았습니다. 세부정보를 검토한 후 다시 시도하세요.",
      "zh-Hans": "通知未发送。查看详细信息并重试。",
      "zh-Hant": "通知未發送。查看詳細資訊並重試。",
      "ru":
          "Уведомление не было отправлено. Просмотрите детали и повторите попытку.",
      "bn":
          "বিজ্ঞপ্তি পাঠানো হয়নি. বিস্তারিত পর্যালোচনা করুন এবং আবার চেষ্টা করুন.",
      "vi": "Thông báo không được gửi. Hãy xem lại chi tiết và thử lại.",
      "th": "ไม่ได้ส่งการแจ้งเตือน ตรวจสอบรายละเอียดแล้วลองอีกครั้ง",
      "pl":
          "Powiadomienie nie zostało wysłane. Przejrzyj szczegóły i spróbuj ponownie.",
      "nl":
          "De melding is niet verzonden. Controleer de details en probeer het opnieuw.",
      "uk":
          "Повідомлення не надіслано. Перегляньте деталі та повторіть спробу.",
    },
    "Notification text": {
      "ar": "نص الإشعار",
      "en": "Notification text",
      "fr": "Texte de la notification",
      "es": "Texto de la notificación",
      "tr": "Bildirim metni",
      "de": "Benachrichtigungstext",
      "it": "Testo della notifica",
      "pt-BR": "Texto de notificação",
      "pt-PT": "Texto de notificação",
      "ur": "اطلاع کا متن",
      "fa": "متن اعلان",
      "hi": "अधिसूचना पाठ",
      "id": "Teks pemberitahuan",
      "ms": "Teks pemberitahuan",
      "ja": "通知テキスト",
      "ko": "알림 텍스트",
      "zh-Hans": "通知文字",
      "zh-Hant": "通知文字",
      "ru": "Текст уведомления",
      "bn": "বিজ্ঞপ্তি পাঠ্য",
      "vi": "Văn bản thông báo",
      "th": "ข้อความแจ้งเตือน",
      "pl": "Tekst powiadomienia",
      "nl": "Meldingstekst",
      "uk": "Текст повідомлення",
    },
    "Write the message exactly as users should receive it.": {
      "ar": "اكتب الرسالة كما تريد أن تصل للمستخدم تمامًا.",
      "en": "Write the message exactly as users should receive it.",
      "fr":
          "Rédigez le message exactement comme les utilisateurs doivent le recevoir.",
      "es": "Escribe el mensaje exactamente como deben recibirlo los usuarios.",
      "tr": "Mesajı kullanıcılara ulaşmasını istediğiniz biçimde yazın.",
      "de":
          "Schreiben Sie die Nachricht genau so, wie Benutzer sie erhalten sollen.",
      "it":
          "Scrivi il messaggio esattamente come gli utenti dovrebbero riceverlo.",
      "pt-BR":
          "Escreva a mensagem exatamente como os usuários devem recebê-la.",
      "pt-PT":
          "Escreva a mensagem exatamente como os utilizadores devem recebê-la.",
      "ur": "پیغام کو بالکل اسی طرح لکھیں جیسا کہ صارفین کو موصول ہونا چاہیے۔",
      "fa": "پیام را دقیقاً همانطور که کاربران باید دریافت کنند بنویسید.",
      "hi":
          "संदेश बिल्कुल वैसे ही लिखें जैसे उपयोगकर्ताओं को उसे प्राप्त होना चाहिए।",
      "id": "Tulis pesan persis seperti yang seharusnya diterima pengguna.",
      "ms": "Tulis mesej tepat seperti yang sepatutnya diterima oleh pengguna.",
      "ja": "ユーザーが受け取るべきメッセージを正確に記述します。",
      "ko": "사용자가 수신해야 하는 메시지를 정확하게 작성하십시오.",
      "zh-Hans": "完全按照用户应该收到的方式编写消息。",
      "zh-Hant": "完全按照使用者應該收到的方式編寫訊息。",
      "ru":
          "Напишите сообщение именно так, как его должны получить пользователи.",
      "bn": "বার্তাটি ঠিক যেভাবে ব্যবহারকারীদের গ্রহণ করা উচিত সেভাবে লিখুন।",
      "vi": "Viết tin nhắn chính xác như người dùng sẽ nhận được.",
      "th": "เขียนข้อความตามที่ผู้ใช้ควรได้รับ",
      "pl":
          "Napisz wiadomość dokładnie tak, jak użytkownicy powinni ją otrzymać.",
      "nl":
          "Schrijf het bericht precies zoals gebruikers het zouden moeten ontvangen.",
      "uk":
          "Напишіть повідомлення саме так, як його мають отримати користувачі.",
    },
    "Write a message before continuing.": {
      "ar": "اكتب الرسالة قبل المتابعة.",
      "en": "Write a message before continuing.",
      "fr": "Rédigez un message avant de continuer.",
      "es": "Escribe un mensaje antes de continuar.",
      "tr": "Devam etmeden önce bir mesaj yazın.",
      "de": "Schreiben Sie eine Nachricht, bevor Sie fortfahren.",
      "it": "Scrivi un messaggio prima di continuare.",
      "pt-BR": "Escreva uma mensagem antes de continuar.",
      "pt-PT": "Escreva uma mensagem antes de continuar.",
      "ur": "جاری رکھنے سے پہلے ایک پیغام لکھیں۔",
      "fa": "قبل از ادامه پیام بنویسید",
      "hi": "जारी रखने से पहले एक संदेश लिखें.",
      "id": "Tulis pesan sebelum melanjutkan.",
      "ms": "Tulis mesej sebelum meneruskan.",
      "ja": "続行する前にメッセージを書いてください。",
      "ko": "계속하기 전에 메시지를 작성하세요.",
      "zh-Hans": "在继续之前先写一条消息。",
      "zh-Hant": "在繼續之前先寫一則訊息。",
      "ru": "Прежде чем продолжить, напишите сообщение.",
      "bn": "চালিয়ে যাওয়ার আগে একটি বার্তা লিখুন।",
      "vi": "Viết tin nhắn trước khi tiếp tục.",
      "th": "เขียนข้อความก่อนดำเนินการต่อ",
      "pl": "Zanim będziesz kontynuować, napisz wiadomość.",
      "nl": "Schrijf een bericht voordat u verdergaat.",
      "uk": "Перш ніж продовжити, напишіть повідомлення.",
    },
    "Recipients": {
      "ar": "المستلمون",
      "en": "Recipients",
      "fr": "Destinataires",
      "es": "Destinatarios",
      "tr": "Alıcılar",
      "de": "Empfänger",
      "it": "Destinatari",
      "pt-BR": "Destinatários",
      "pt-PT": "Destinatários",
      "ur": "وصول کنندگان",
      "fa": "گیرندگان",
      "hi": "प्राप्तकर्ता",
      "id": "Penerima",
      "ms": "Penerima",
      "ja": "受信者",
      "ko": "수신자",
      "zh-Hans": "收件人",
      "zh-Hant": "收件者",
      "ru": "Получатели",
      "bn": "প্রাপক",
      "vi": "Người nhận",
      "th": "ผู้รับ",
      "pl": "Odbiorcy",
      "nl": "Ontvangers",
      "uk": "Одержувачі",
    },
    "Specific email": {
      "ar": "بريد محدد",
      "en": "Specific email",
      "fr": "E-mail précis",
      "es": "Correo concreto",
      "tr": "Belirli e-posta",
      "de": "Spezifische E-Mail",
      "it": "E-mail specifica",
      "pt-BR": "E-mail específico",
      "pt-PT": "E-mail específico",
      "ur": "مخصوص ای میل",
      "fa": "ایمیل خاص",
      "hi": "विशिष्ट ईमेल",
      "id": "Email tertentu",
      "ms": "E-mel khusus",
      "ja": "特定のメールアドレス",
      "ko": "특정 이메일",
      "zh-Hans": "具体邮箱",
      "zh-Hant": "具體信箱",
      "ru": "Конкретный адрес электронной почты",
      "bn": "নির্দিষ্ট ইমেইল",
      "vi": "Email cụ thể",
      "th": "อีเมลเฉพาะ",
      "pl": "Konkretny e-mail",
      "nl": "Specifieke e-mail",
      "uk": "Конкретний email",
    },
    "Account email": {
      "ar": "بريد الحساب",
      "en": "Account email",
      "fr": "E-mail du compte",
      "es": "Correo de la cuenta",
      "tr": "Hesap e-postası",
      "de": "E-Mail-Adresse des Kontos",
      "it": "E-mail dell'account",
      "pt-BR": "E-mail da conta",
      "pt-PT": "E-mail da conta",
      "ur": "اکاؤنٹ ای میل",
      "fa": "ایمیل حساب",
      "hi": "खाता ईमेल",
      "id": "Email akun",
      "ms": "E-mel akaun",
      "ja": "アカウントのメールアドレス",
      "ko": "계정 이메일",
      "zh-Hans": "账户邮箱",
      "zh-Hant": "帳號",
      "ru": "Адрес электронной почты аккаунта",
      "bn": "অ্যাকাউন্ট ইমেল",
      "vi": "Email tài khoản",
      "th": "อีเมลบัญชี",
      "pl": "Adres e-mail konta",
      "nl": "Account-e-mailadres",
      "uk": "Електронна адреса облікового запису",
    },
    "Review before sending": {
      "ar": "مراجعة قبل الإرسال",
      "en": "Review before sending",
      "fr": "Vérifier avant l’envoi",
      "es": "Revisar antes de enviar",
      "tr": "Göndermeden önce incele",
      "de": "Überprüfen Sie es vor dem Senden",
      "it": "Rivedere prima di inviare",
      "pt-BR": "Revise antes de enviar",
      "pt-PT": "Reveja antes de enviar",
      "ur": "بھیجنے سے پہلے جائزہ لیں۔",
      "fa": "قبل از ارسال بررسی کنید",
      "hi": "भेजने से पहले समीक्षा करें",
      "id": "Tinjau sebelum mengirim",
      "ms": "Semak sebelum menghantar",
      "ja": "送信前に確認してください",
      "ko": "보내기 전에 검토하세요",
      "zh-Hans": "发送前检查",
      "zh-Hant": "發送前檢查",
      "ru": "Проверьте перед отправкой",
      "bn": "পাঠানোর আগে পর্যালোচনা করুন",
      "vi": "Xem xét trước khi gửi",
      "th": "ตรวจสอบก่อนส่ง",
      "pl": "Przejrzyj przed wysłaniem",
      "nl": "Controleer voordat u verzendt",
      "uk": "Перегляньте перед відправкою",
    },
    "Custom notification": {
      "ar": "إشعار مخصص",
      "en": "Custom notification",
      "fr": "Notification personnalisée",
      "es": "Notificación personalizada",
      "tr": "Özel bildirim",
      "de": "Benutzerdefinierte Benachrichtigung",
      "it": "Notifica personalizzata",
      "pt-BR": "Notificação personalizada",
      "pt-PT": "Notificação personalizada",
      "ur": "حسب ضرورت اطلاع",
      "fa": "اطلاع رسانی سفارشی",
      "hi": "कस्टम अधिसूचना",
      "id": "Pemberitahuan khusus",
      "ms": "Pemberitahuan tersuai",
      "ja": "カスタム通知",
      "ko": "맞춤 알림",
      "zh-Hans": "自定义通知",
      "zh-Hant": "自訂通知",
      "ru": "Пользовательское уведомление",
      "bn": "কাস্টম বিজ্ঞপ্তি",
      "vi": "Thông báo tùy chỉnh",
      "th": "การแจ้งเตือนที่กำหนดเอง",
      "pl": "Niestandardowe powiadomienie",
      "nl": "Aangepaste melding",
      "uk": "Спеціальне сповіщення",
    },
    "BIL will use its reviewed compensation copy. Choose who receives it.": {
      "ar": "ستستخدم BIL صياغة التعويض المعتمدة. اختر من سيستلمها.",
      "en":
          "BIL will use its reviewed compensation copy. Choose who receives it.",
      "fr":
          "BIL utilisera son texte de compensation validé. Choisissez les destinataires.",
      "es":
          "BIL usará su texto de compensación revisado. Elige quién lo recibirá.",
      "tr": "BIL onaylı telafi metnini kullanacak. Kimin alacağını seçin.",
      "de":
          "BIL wird sein überprüftes Vergütungsexemplar verwenden. Wählen Sie, wer es erhält.",
      "it":
          "BIL utilizzerà la copia di compensazione revisionata. Scegli chi lo riceve.",
      "pt-BR":
          "BIL usará sua cópia de remuneração revisada. Escolha quem recebe.",
      "pt-PT":
          "BIL utilizará a sua cópia de remuneração revista. Escolha quem recebe.",
      "ur":
          "BIL اس کی نظرثانی شدہ معاوضے کی کاپی استعمال کرے گا۔ منتخب کریں کہ کون اسے وصول کرتا ہے۔",
      "fa":
          "BIL از نسخه جبرانی بازبینی شده خود استفاده خواهد کرد. انتخاب کنید که چه کسی آن را دریافت می کند.",
      "hi":
          "BIL अपनी समीक्षा की गई क्षतिपूर्ति प्रति का उपयोग करेगा। चुनें कि इसे कौन प्राप्त करेगा.",
      "id":
          "BIL akan menggunakan salinan kompensasi yang telah ditinjau. Pilih siapa yang menerimanya.",
      "ms":
          "BIL akan menggunakan salinan pampasan yang disemak. Pilih siapa yang menerimanya.",
      "ja": "BIL は、レビューされた補償コピーを使用します。受け取る人を選択してください。",
      "ko": "BIL는 검토된 보상 사본을 사용합니다. 받을 사람을 선택하세요.",
      "zh-Hans": "BIL 将使用其经过审核的补偿副本。选择谁接收它。",
      "zh-Hant": "BIL 將使用其經過審核的補償副本。選擇誰接收它。",
      "ru":
          "BIL будет использовать проверенную компенсационную копию. Выберите, кто его получит.",
      "bn":
          "BIL এর পর্যালোচনা করা ক্ষতিপূরণ কপি ব্যবহার করবে। যারা এটি গ্রহণ করে তা চয়ন করুন৷",
      "vi":
          "BIL sẽ sử dụng bản sao khoản bồi thường đã được xem xét của mình. Chọn người nhận nó.",
      "th": "BIL จะใช้สำเนาการชดเชยที่ได้รับการตรวจสอบแล้ว เลือกว่าใครจะรับมัน",
      "pl":
          "BIL użyje sprawdzonej kopii wynagrodzenia. Wybierz, kto go otrzyma.",
      "nl":
          "BIL zal de beoordeelde compensatiekopie gebruiken. Kies wie het ontvangt.",
      "uk":
          "BIL використовуватиме свою перевірену компенсаційну копію. Виберіть, хто його отримає.",
    },
    "BIL will use its reviewed gift copy. Choose who receives it.": {
      "ar": "ستستخدم BIL صياغة الهدية المعتمدة. اختر من سيستلمها.",
      "en": "BIL will use its reviewed gift copy. Choose who receives it.",
      "fr":
          "BIL utilisera son texte cadeau validé. Choisissez les destinataires.",
      "es": "BIL usará su texto de regalo revisado. Elige quién lo recibirá.",
      "tr": "BIL onaylı hediye metnini kullanacak. Kimin alacağını seçin.",
      "de":
          "BIL wird sein überprüftes Geschenkexemplar verwenden. Wählen Sie, wer es erhält.",
      "it": "BIL utilizzerà la copia regalo esaminata. Scegli chi lo riceve.",
      "pt-BR": "BIL usará sua cópia de presente revisada. Escolha quem recebe.",
      "pt-PT":
          "BIL utilizará a sua cópia de oferta revista. Escolha quem recebe.",
      "ur":
          "BIL اپنی نظرثانی شدہ گفٹ کاپی استعمال کرے گا۔ منتخب کریں کہ کون اسے وصول کرتا ہے۔",
      "fa":
          "BIL از کپی هدیه بازبینی شده خود استفاده خواهد کرد. انتخاب کنید که چه کسی آن را دریافت می کند.",
      "hi":
          "BIL अपनी समीक्षा की गई उपहार प्रति का उपयोग करेगा। चुनें कि इसे कौन प्राप्त करेगा.",
      "id":
          "BIL akan menggunakan salinan hadiah yang telah ditinjau. Pilih siapa yang menerimanya.",
      "ms":
          "BIL akan menggunakan salinan hadiah yang disemak. Pilih siapa yang menerimanya.",
      "ja": "BIL は、レビュー済みのギフト コピーを使用します。受け取る人を選択してください。",
      "ko": "BIL는 검토된 선물 사본을 사용합니다. 받을 사람을 선택하세요.",
      "zh-Hans": "BIL 将使用其经过审核的礼品副本。选择谁接收它。",
      "zh-Hant": "BIL 將使用其經過審核的禮品副本。選擇誰接收它。",
      "ru":
          "BIL будет использовать проверенную подарочную копию. Выберите, кто его получит.",
      "bn":
          "BIL এর পর্যালোচনা করা উপহারের অনুলিপি ব্যবহার করবে। যারা এটি গ্রহণ করে তা চয়ন করুন৷",
      "vi":
          "BIL sẽ sử dụng bản sao quà tặng đã được đánh giá của mình. Chọn người nhận nó.",
      "th": "BIL จะใช้สำเนาของขวัญที่ได้รับการตรวจสอบแล้ว เลือกว่าใครจะรับมัน",
      "pl":
          "BIL użyje sprawdzonego egzemplarza podarunkowego. Wybierz, kto go otrzyma.",
      "nl":
          "BIL zal het beoordeelde geschenkexemplaar gebruiken. Kies wie het ontvangt.",
      "uk":
          "BIL використовуватиме свою перевірену подарункову копію. Виберіть, хто його отримає.",
    },
    "Write the text first, then choose everyone or one exact email.": {
      "ar": "اكتب النص أولًا، ثم اختر الجميع أو بريدًا محددًا.",
      "en": "Write the text first, then choose everyone or one exact email.",
      "fr":
          "Rédigez d’abord le texte, puis choisissez tous les comptes ou un e-mail précis.",
      "es":
          "Escribe primero el texto y luego elige todos o un correo concreto.",
      "tr":
          "Önce metni yazın, ardından herkesi veya belirli bir e-postayı seçin.",
      "de":
          "Schreiben Sie zuerst den Text und wählen Sie dann alle oder eine genaue E-Mail aus.",
      "it": "Scrivi prima il testo, poi scegli tutti o un'e-mail esatta.",
      "pt-BR":
          "Escreva o texto primeiro e depois escolha todos ou um e-mail exato.",
      "pt-PT":
          "Escreva primeiro o texto e depois escolha todos ou um e-mail exato.",
      "ur": "پہلے متن لکھیں، پھر سب کو یا ایک درست ای میل کا انتخاب کریں۔",
      "fa": "ابتدا متن را بنویسید، سپس همه یا یک ایمیل دقیق را انتخاب کنید.",
      "hi": "पहले टेक्स्ट लिखें, फिर सभी या एक सटीक ईमेल चुनें।",
      "id":
          "Tulis teksnya terlebih dahulu, lalu pilih semua orang atau satu email yang sama.",
      "ms":
          "Tulis teks dahulu, kemudian pilih semua orang atau satu e-mel yang tepat.",
      "ja": "最初にテキストを書いてから、全員または 1 つの電子メールを選択します。",
      "ko": "먼저 텍스트를 작성한 다음 모든 사람을 선택하거나 정확한 이메일 하나를 선택하세요.",
      "zh-Hans": "首先写下文字，然后选择所有人或一封确切的电子邮件。",
      "zh-Hant": "首先寫下文字，然後選擇所有人或一封確切的電子郵件。",
      "ru":
          "Сначала напишите текст, затем выберите все или одно конкретное письмо.",
      "bn": "প্রথমে টেক্সট লিখুন, তারপর সবাই বা একটি সঠিক ইমেল বেছে নিন।",
      "vi":
          "Viết văn bản trước, sau đó chọn tất cả mọi người hoặc một email chính xác.",
      "th": "เขียนข้อความก่อน จากนั้นเลือกทุกคนหรืออีเมลเดียว",
      "pl":
          "Najpierw napisz tekst, a następnie wybierz wszystkich lub jeden konkretny e-mail.",
      "nl":
          "Schrijf eerst de tekst en kies vervolgens iedereen of één exact e-mailadres.",
      "uk":
          "Спочатку напишіть текст, а потім виберіть усі або одну точну електронну адресу.",
    },
  };

  static String resolve(String english, String localeTag) {
    final normalized = localeTag.replaceAll('_', '-').toLowerCase();
    final exact = supported.where((tag) => tag.toLowerCase() == normalized);
    if (exact.length == 1) return values[english]![exact.single]!;
    final language = normalized.split('-').first;
    final matches = supported.where(
      (tag) =>
          tag.toLowerCase() == language ||
          tag.toLowerCase().startsWith('$language-'),
    );
    if (matches.length == 1) return values[english]![matches.single]!;
    return values[english]!['en']!;
  }

  static bool get balanced => values.values.every(
    (translations) =>
        translations.keys.toSet().containsAll(supported) &&
        supported.containsAll(translations.keys) &&
        translations.values.every((value) => value.trim().isNotEmpty),
  );
}
