import 'bil_locale_policy.dart';

/// Reviewed Food Log copy for every shipped locale.
///
/// Food identity translation remains owned by [FoodPresentationLocalizer].
/// This catalog covers only UI chrome and status messages, so a missing locale
/// can never turn the Food Log into a mixed-language experience.
abstract final class FoodLogRuntimeCopy {
  static const mostPopular = 'Most popular';
  static const noFoodsFound = 'No foods found';
  static const favoritesHelp =
      'Create and save your favorites for quick logging.';
  static const addedToDiary = 'Added to diary';
  static const couldNotAddFood = 'Could not add food';
  static const noVerifiedBarcodeMatch = 'No verified food matched this barcode';
  static const barcodeLookupFailed = 'Barcode lookup failed';
  static const quickAddSaved = 'Quick Add saved locally.';
  static const chooseServing = 'Choose a serving';
  static const searchHint = 'Search foods, brands, flavors…';
  static const notNow = 'Not now';
  static const loadingNutrition = 'Loading nutrition';
  static const snack = 'Snack';

  static const sources = <String>[
    mostPopular,
    noFoodsFound,
    favoritesHelp,
    addedToDiary,
    couldNotAddFood,
    noVerifiedBarcodeMatch,
    barcodeLookupFailed,
    quickAddSaved,
    chooseServing,
    searchHint,
    notNow,
    loadingNutrition,
    snack,
  ];

  static const supported = <String>{
    'ar',
    'en',
    'fr',
    'es',
    'tr',
    'de',
    'it',
    'pt-BR',
    'pt-PT',
    'ur',
    'fa',
    'hi',
    'id',
    'ms',
    'ja',
    'ko',
    'zh-Hans',
    'zh-Hant',
    'ru',
    'bn',
    'vi',
    'th',
    'pl',
    'nl',
    'uk',
  };

  static const rows = <String, List<String>>{
    'ar': <String>[
      'الأكثر شيوعًا',
      'لم يتم العثور على أطعمة',
      'أنشئ أطعمتك المفضلة واحفظها لتسجيل أسرع.',
      'تمت الإضافة إلى اليوميات',
      'تعذّرت إضافة الطعام',
      'لم يطابق هذا الباركود أي طعام موثّق',
      'تعذّر البحث عن الباركود',
      'تم حفظ الإضافة السريعة محليًا.',
      'اختر الحصة',
      'ابحث عن أطعمة أو علامات تجارية أو نكهات…',
      'ليس الآن',
      'جارٍ تحميل بيانات التغذية',
      'وجبة خفيفة',
    ],
    'en': sources,
    'fr': <String>[
      'Les plus populaires',
      'Aucun aliment trouvé',
      'Créez et enregistrez vos favoris pour les ajouter plus rapidement.',
      'Ajouté au journal',
      'Impossible d’ajouter l’aliment',
      'Aucun aliment vérifié ne correspond à ce code-barres',
      'Échec de la recherche du code-barres',
      'Ajout rapide enregistré localement.',
      'Choisissez une portion',
      'Rechercher des aliments, marques, saveurs…',
      'Pas maintenant',
      'Chargement des données nutritionnelles',
      'En-cas',
    ],
    'es': <String>[
      'Más populares',
      'No se encontraron alimentos',
      'Crea y guarda tus favoritos para registrarlos más rápido.',
      'Añadido al diario',
      'No se pudo añadir el alimento',
      'Ningún alimento verificado coincide con este código de barras',
      'Falló la búsqueda del código de barras',
      'Entrada rápida guardada localmente.',
      'Elige una porción',
      'Busca alimentos, marcas, sabores…',
      'Ahora no',
      'Cargando datos de nutrición',
      'Tentempié',
    ],
    'tr': <String>[
      'En popüler',
      'Yiyecek bulunamadı',
      'Hızlı kayıt için favorilerinizi oluşturup kaydedin.',
      'Günlüğe eklendi',
      'Yiyecek eklenemedi',
      'Bu barkodla eşleşen doğrulanmış yiyecek bulunamadı',
      'Barkod araması başarısız oldu',
      'Hızlı Ekle yerel olarak kaydedildi.',
      'Bir porsiyon seçin',
      'Yiyecek, marka veya lezzet ara…',
      'Şimdi değil',
      'Beslenme verileri yükleniyor',
      'Ara öğün',
    ],
    'de': <String>[
      'Am beliebtesten',
      'Keine Lebensmittel gefunden',
      'Erstelle und speichere Favoriten für schnelleres Protokollieren.',
      'Zum Tagebuch hinzugefügt',
      'Lebensmittel konnte nicht hinzugefügt werden',
      'Kein verifiziertes Lebensmittel stimmt mit diesem Barcode überein',
      'Barcode-Suche fehlgeschlagen',
      'Quick Add wurde lokal gespeichert.',
      'Portion auswählen',
      'Lebensmittel, Marken, Geschmacksrichtungen suchen…',
      'Nicht jetzt',
      'Ernährungsdaten werden geladen',
      'Zwischenmahlzeit',
    ],
    'it': <String>[
      'Più popolari',
      'Nessun alimento trovato',
      'Crea e salva i preferiti per registrarli più rapidamente.',
      'Aggiunto al diario',
      'Impossibile aggiungere l’alimento',
      'Nessun alimento verificato corrisponde a questo codice a barre',
      'Ricerca del codice a barre non riuscita',
      'Aggiunta rapida salvata localmente.',
      'Scegli una porzione',
      'Cerca alimenti, marche, gusti…',
      'Non ora',
      'Caricamento dei dati nutrizionali',
      'Spuntino',
    ],
    'pt-BR': <String>[
      'Mais populares',
      'Nenhum alimento encontrado',
      'Crie e salve seus favoritos para registrar mais rápido.',
      'Adicionado ao diário',
      'Não foi possível adicionar o alimento',
      'Nenhum alimento verificado corresponde a este código de barras',
      'Falha ao consultar o código de barras',
      'Adição rápida salva localmente.',
      'Escolha uma porção',
      'Pesquise alimentos, marcas, sabores…',
      'Agora não',
      'Carregando dados de nutrição',
      'Lanche',
    ],
    'pt-PT': <String>[
      'Mais populares',
      'Nenhum alimento encontrado',
      'Crie e guarde os seus favoritos para registar mais depressa.',
      'Adicionado ao diário',
      'Não foi possível adicionar o alimento',
      'Nenhum alimento verificado corresponde a este código de barras',
      'Falha na pesquisa do código de barras',
      'Adição rápida guardada localmente.',
      'Escolha uma porção',
      'Pesquise alimentos, marcas, sabores…',
      'Agora não',
      'A carregar dados de nutrição',
      'Lanche',
    ],
    'ur': <String>[
      'سب سے مقبول',
      'کوئی غذا نہیں ملی',
      'تیز اندراج کے لیے اپنی پسندیدہ غذائیں بنائیں اور محفوظ کریں۔',
      'ڈائری میں شامل کر دیا گیا',
      'غذا شامل نہیں ہو سکی',
      'اس بار کوڈ سے کوئی تصدیق شدہ غذا نہیں ملی',
      'بار کوڈ تلاش ناکام ہوئی',
      'فوری اندراج مقامی طور پر محفوظ ہو گیا۔',
      'ایک سرونگ منتخب کریں',
      'غذا، برانڈ یا ذائقہ تلاش کریں…',
      'ابھی نہیں',
      'غذائیت کا ڈیٹا لوڈ ہو رہا ہے',
      'ہلکی غذا',
    ],
    'fa': <String>[
      'محبوب‌ترین‌ها',
      'غذایی پیدا نشد',
      'برای ثبت سریع‌تر، موارد دلخواه خود را ایجاد و ذخیره کنید.',
      'به دفترچه اضافه شد',
      'افزودن غذا ممکن نشد',
      'هیچ غذای تأییدشده‌ای با این بارکد مطابقت ندارد',
      'جستجوی بارکد ناموفق بود',
      'افزودن سریع به‌صورت محلی ذخیره شد.',
      'یک وعده را انتخاب کنید',
      'جستجوی غذا، برند یا طعم…',
      'الان نه',
      'در حال بارگذاری داده‌های تغذیه',
      'میان‌وعده',
    ],
    'hi': <String>[
      'सबसे लोकप्रिय',
      'कोई भोजन नहीं मिला',
      'तेज़ लॉगिंग के लिए अपने पसंदीदा भोजन बनाएँ और सहेजें।',
      'डायरी में जोड़ा गया',
      'भोजन जोड़ा नहीं जा सका',
      'इस बारकोड से कोई सत्यापित भोजन नहीं मिला',
      'बारकोड खोज विफल रही',
      'क्विक ऐड स्थानीय रूप से सहेजा गया।',
      'एक सर्विंग चुनें',
      'भोजन, ब्रांड, स्वाद खोजें…',
      'अभी नहीं',
      'पोषण डेटा लोड हो रहा है',
      'स्नैक',
    ],
    'id': <String>[
      'Paling populer',
      'Makanan tidak ditemukan',
      'Buat dan simpan favorit agar pencatatan lebih cepat.',
      'Ditambahkan ke diari',
      'Makanan tidak dapat ditambahkan',
      'Tidak ada makanan terverifikasi yang cocok dengan kode batang ini',
      'Pencarian kode batang gagal',
      'Tambah Cepat disimpan secara lokal.',
      'Pilih satu porsi',
      'Cari makanan, merek, rasa…',
      'Jangan sekarang',
      'Memuat data nutrisi',
      'Camilan',
    ],
    'ms': <String>[
      'Paling popular',
      'Tiada makanan ditemui',
      'Cipta dan simpan kegemaran untuk catatan yang lebih pantas.',
      'Ditambah ke diari',
      'Makanan tidak dapat ditambah',
      'Tiada makanan disahkan sepadan dengan kod bar ini',
      'Carian kod bar gagal',
      'Tambah Pantas disimpan secara setempat.',
      'Pilih satu hidangan',
      'Cari makanan, jenama, perisa…',
      'Bukan sekarang',
      'Memuatkan data pemakanan',
      'Snek',
    ],
    'ja': <String>[
      '人気の食品',
      '食品が見つかりません',
      'お気に入りを作成して保存すると、すばやく記録できます。',
      '食事記録に追加しました',
      '食品を追加できませんでした',
      'このバーコードに一致する検証済み食品はありません',
      'バーコード検索に失敗しました',
      'クイック追加を端末に保存しました。',
      '1回分を選択',
      '食品、ブランド、味を検索…',
      '今はしない',
      '栄養データを読み込んでいます',
      '間食',
    ],
    'ko': <String>[
      '인기 음식',
      '음식을 찾을 수 없습니다',
      '즐겨찾기를 만들고 저장하면 더 빠르게 기록할 수 있습니다.',
      '식사 일지에 추가했습니다',
      '음식을 추가할 수 없습니다',
      '이 바코드와 일치하는 검증된 음식이 없습니다',
      '바코드 조회에 실패했습니다',
      '빠른 추가를 기기에 저장했습니다.',
      '1회 제공량 선택',
      '음식, 브랜드, 맛 검색…',
      '나중에',
      '영양 데이터를 불러오는 중',
      '간식',
    ],
    'zh-Hans': <String>[
      '最常用',
      '未找到食物',
      '创建并保存收藏，以便更快记录。',
      '已添加到饮食日记',
      '无法添加食物',
      '没有已验证食物与此条形码匹配',
      '条形码查询失败',
      '快速添加已保存在本机。',
      '选择一份',
      '搜索食物、品牌、口味…',
      '暂不',
      '正在加载营养数据',
      '加餐',
    ],
    'zh-Hant': <String>[
      '最常用',
      '找不到食物',
      '建立並儲存收藏，讓記錄更快速。',
      '已加入飲食日誌',
      '無法加入食物',
      '沒有已驗證食物與此條碼相符',
      '條碼查詢失敗',
      '快速加入已儲存在本機。',
      '選擇一份',
      '搜尋食物、品牌、口味…',
      '暫時不要',
      '正在載入營養資料',
      '加餐',
    ],
    'ru': <String>[
      'Самые популярные',
      'Продукты не найдены',
      'Создавайте и сохраняйте избранное, чтобы быстрее вести дневник.',
      'Добавлено в дневник',
      'Не удалось добавить продукт',
      'Для этого штрихкода нет проверенного продукта',
      'Не удалось найти штрихкод',
      'Быстрое добавление сохранено локально.',
      'Выберите порцию',
      'Искать продукты, бренды, вкусы…',
      'Не сейчас',
      'Загрузка данных о питании',
      'Перекус',
    ],
    'bn': <String>[
      'সবচেয়ে জনপ্রিয়',
      'কোনো খাবার পাওয়া যায়নি',
      'দ্রুত লগ করার জন্য পছন্দের খাবার তৈরি করে সংরক্ষণ করুন।',
      'ডায়েরিতে যোগ হয়েছে',
      'খাবার যোগ করা যায়নি',
      'এই বারকোডের সঙ্গে কোনো যাচাইকৃত খাবার মেলেনি',
      'বারকোড খোঁজা ব্যর্থ হয়েছে',
      'কুইক অ্যাড স্থানীয়ভাবে সংরক্ষিত হয়েছে।',
      'একটি পরিবেশন বেছে নিন',
      'খাবার, ব্র্যান্ড, স্বাদ খুঁজুন…',
      'এখন নয়',
      'পুষ্টি তথ্য লোড হচ্ছে',
      'হালকা খাবার',
    ],
    'vi': <String>[
      'Phổ biến nhất',
      'Không tìm thấy thực phẩm',
      'Tạo và lưu món yêu thích để ghi nhanh hơn.',
      'Đã thêm vào nhật ký',
      'Không thể thêm thực phẩm',
      'Không có thực phẩm đã xác minh khớp mã vạch này',
      'Tra cứu mã vạch thất bại',
      'Thêm nhanh đã được lưu trên thiết bị.',
      'Chọn một khẩu phần',
      'Tìm thực phẩm, thương hiệu, hương vị…',
      'Để sau',
      'Đang tải dữ liệu dinh dưỡng',
      'Bữa phụ',
    ],
    'th': <String>[
      'ยอดนิยม',
      'ไม่พบอาหาร',
      'สร้างและบันทึกรายการโปรดเพื่อบันทึกอาหารได้เร็วขึ้น',
      'เพิ่มลงในไดอารีแล้ว',
      'ไม่สามารถเพิ่มอาหารได้',
      'ไม่พบอาหารที่ยืนยันแล้วตรงกับบาร์โค้ดนี้',
      'ค้นหาบาร์โค้ดไม่สำเร็จ',
      'บันทึกการเพิ่มด่วนไว้ในเครื่องแล้ว',
      'เลือกหนึ่งหน่วยบริโภค',
      'ค้นหาอาหาร แบรนด์ หรือรสชาติ…',
      'ไว้ก่อน',
      'กำลังโหลดข้อมูลโภชนาการ',
      'ของว่าง',
    ],
    'pl': <String>[
      'Najpopularniejsze',
      'Nie znaleziono produktów',
      'Twórz i zapisuj ulubione produkty, aby szybciej je rejestrować.',
      'Dodano do dziennika',
      'Nie udało się dodać produktu',
      'Żaden zweryfikowany produkt nie pasuje do tego kodu kreskowego',
      'Wyszukiwanie kodu kreskowego nie powiodło się',
      'Szybkie dodawanie zapisano lokalnie.',
      'Wybierz porcję',
      'Szukaj produktów, marek, smaków…',
      'Nie teraz',
      'Ładowanie danych żywieniowych',
      'Przekąska',
    ],
    'nl': <String>[
      'Populairst',
      'Geen voedingsmiddelen gevonden',
      'Maak en bewaar favorieten om sneller te registreren.',
      'Toegevoegd aan dagboek',
      'Voedingsmiddel kon niet worden toegevoegd',
      'Geen geverifieerd voedingsmiddel past bij deze barcode',
      'Barcode opzoeken mislukt',
      'Snel toevoegen is lokaal opgeslagen.',
      'Kies een portie',
      'Zoek voedingsmiddelen, merken, smaken…',
      'Niet nu',
      'Voedingsgegevens laden',
      'Tussendoortje',
    ],
    'uk': <String>[
      'Найпопулярніше',
      'Продуктів не знайдено',
      'Створюйте й зберігайте обране для швидшого ведення щоденника.',
      'Додано до щоденника',
      'Не вдалося додати продукт',
      'Жоден перевірений продукт не відповідає цьому штрихкоду',
      'Пошук штрихкоду не вдався',
      'Швидке додавання збережено локально.',
      'Виберіть порцію',
      'Шукайте продукти, бренди, смаки…',
      'Не зараз',
      'Завантаження даних про харчування',
      'Перекус',
    ],
  };

  static String? resolve(String source, String localeTag) {
    final index = sources.indexOf(source);
    if (index < 0) return null;
    final tag = BilLocalePolicy.canonicalSupportedTag(localeTag);
    if (tag == null) return null;
    final row = rows[tag];
    if (row == null || row.length != sources.length) {
      throw StateError('Missing Food Log copy for $tag.');
    }
    return row[index];
  }

  static bool get balanced =>
      supported.length == 25 &&
      rows.keys.toSet().containsAll(supported) &&
      supported.containsAll(rows.keys) &&
      rows.values.every(
        (row) =>
            row.length == sources.length &&
            row.every((value) => value.trim().isNotEmpty),
      ) &&
      _sameValues(rows['en'], sources);

  static bool _sameValues(List<String>? left, List<String> right) {
    if (left == null || left.length != right.length) return false;
    for (var index = 0; index < right.length; index++) {
      if (left[index] != right[index]) return false;
    }
    return true;
  }
}
