part of 'runtime_copy_coach_food_cards.dart';

const _coachFoodCardRows3 = <String, List<String>>{
  "bn": [
    "অজানা",
    "আনুমানিক",
    "খাবারের বিস্তারিত",
    "পুষ্টি উপাদানের বিস্তারিত",
    "রসিদের কার্যক্রম",
    "আনুমানিক পরিমাণ",
    "ফটো অনুপলব্ধ",
    "হ্যাঁ, নথিভুক্ত করুন",
    "সংশোধন করুন",
    "কাজ চলছে…",
    "উৎস",
    "উৎসের ওপর আস্থা",
    "খাবার শনাক্তকরণের ওপর আস্থা",
    "পরিমাণের ওপর আস্থা",
    "দৈনিক লগে দেখুন",
    "এই খাবারের রসিদ পাওয়া যাচ্ছে না। আপনার দৈনিক লগ দেখুন।",
    "আপনার অ্যাকাউন্ট বদলেছে। চালিয়ে যেতে কোচে ফিরে যান।",
    "কাজটি সম্পন্ন করা যায়নি। আপনার পর্যালোচনা সংরক্ষিত আছে।",
    "এই খাবার বদলেছে। সম্পাদনা বা পূর্বাবস্থায় ফেরানোর আগে বর্তমান এন্ট্রি দেখুন।",
    "এই পর্যালোচনা বন্ধ হয়েছে।",
    "এন্ট্রি পূর্বাবস্থায় ফেরানো হয়েছে",
    "খাবার হালনাগাদ করা হয়েছে",
    "এন্ট্রি সরানো হয়েছে",
    "খাবার স্থানান্তর করা হয়েছে",
    "ক্যালরির এন্ট্রি সংরক্ষিত হয়েছে",
    "পুষ্টি উপাদানের এন্ট্রি সংরক্ষিত হয়েছে",
    "অজানা খাবার",
    "খাবার",
    "ঠিক আছে! আমি আপনার {meal} নথিভুক্ত করব। আমি যা বুঝেছি:",
    "এটি কি আপনার {meal}-এ নথিভুক্ত করব?",
    "{meal} নথিভুক্ত হয়েছে",
    "তথ্যসূত্র",
    "খাবারের লেবেল",
    "আপনার নির্ধারিত মান",
    "হিসাব করা রেসিপি",
    "প্রোটিন",
    "শর্করা",
    "মোটা",
    "চিনি",
    "ক্যালসিয়াম",
    "ফসফরাস",
    "আয়রন",
    "ভিটামিন সি",
    "মিলি",
    "1টি",
    "{count}টি",
    "গ্রাম",
  ],
  "vi": [
    "Chưa biết",
    "Ước tính",
    "Chi tiết thực phẩm",
    "Chi tiết dinh dưỡng",
    "Thao tác với biên nhận",
    "Khẩu phần ước tính",
    "Không có ảnh",
    "Có, ghi lại",
    "Điều chỉnh",
    "Đang xử lý…",
    "Nguồn",
    "Độ tin cậy của nguồn",
    "Độ tin cậy khi nhận diện thực phẩm",
    "Độ tin cậy của lượng",
    "Xem trong nhật ký hằng ngày",
    "Biên nhận thực phẩm này không khả dụng. Hãy xem nhật ký hằng ngày của bạn.",
    "Tài khoản của bạn đã thay đổi. Hãy quay lại Huấn luyện viên để tiếp tục.",
    "Không thể hoàn tất thao tác. Nội dung xem lại của bạn vẫn được giữ.",
    "Bữa ăn này đã thay đổi. Hãy xem bản ghi hiện tại trước khi sửa hoặc hoàn tác.",
    "Lượt xem lại này đã đóng.",
    "Đã hoàn tác bản ghi",
    "Đã cập nhật bữa ăn",
    "Đã xóa bản ghi",
    "Đã chuyển bữa ăn",
    "Đã lưu bản ghi calo",
    "Đã lưu bản ghi dinh dưỡng",
    "Món ăn không xác định",
    "Bữa ăn",
    "Được rồi! Tôi sẽ ghi lại {meal} của bạn. Đây là nội dung tôi đã hiểu:",
    "Tôi ghi nội dung này vào {meal} của bạn nhé?",
    "Đã ghi {meal}",
    "Tài liệu tham khảo",
    "Nhãn thực phẩm",
    "Giá trị cố định của bạn",
    "Công thức đã tính toán",
    "chất đạm",
    "Carb",
    "Chất béo",
    "đường",
    "canxi",
    "Phốt pho",
    "Sắt",
    "Vitamin C",
    "ml",
    "1 đơn vị",
    "{count} đơn vị",
    "g",
  ],
  "th": [
    "ไม่ทราบ",
    "ค่าประมาณ",
    "รายละเอียดอาหาร",
    "รายละเอียดสารอาหาร",
    "การดำเนินการกับใบยืนยัน",
    "ปริมาณโดยประมาณ",
    "รูปภาพไม่พร้อมใช้งาน",
    "ใช่ บันทึกเลย",
    "ปรับแก้",
    "กำลังดำเนินการ…",
    "แหล่งข้อมูล",
    "ความเชื่อมั่นในแหล่งข้อมูล",
    "ความเชื่อมั่นในการระบุอาหาร",
    "ความเชื่อมั่นในปริมาณ",
    "ดูในบันทึกประจำวัน",
    "ใบยืนยันการบันทึกอาหารนี้ไม่พร้อมใช้งาน โปรดตรวจสอบบันทึกประจำวัน",
    "บัญชีของคุณเปลี่ยนไปแล้ว โปรดกลับไปที่โค้ชเพื่อดำเนินการต่อ",
    "ไม่สามารถดำเนินการให้เสร็จได้ ข้อมูลที่คุณตรวจทานยังคงอยู่",
    "มื้อนี้มีการเปลี่ยนแปลง โปรดตรวจสอบรายการปัจจุบันก่อนแก้ไขหรือเลิกทำ",
    "การตรวจทานนี้ปิดแล้ว",
    "เลิกทำรายการแล้ว",
    "อัปเดตมื้ออาหารแล้ว",
    "ลบรายการแล้ว",
    "ย้ายมื้ออาหารแล้ว",
    "บันทึกรายการแคลอรีแล้ว",
    "บันทึกรายการสารอาหารแล้ว",
    "อาหารที่ไม่รู้จัก",
    "มื้ออาหาร",
    "ได้เลย! ฉันจะบันทึก{meal}ของคุณ นี่คือสิ่งที่ฉันเข้าใจ:",
    "ให้ฉันบันทึกข้อมูลนี้ใน{meal}ของคุณไหม?",
    "บันทึก{meal}แล้ว",
    "ข้อมูลอ้างอิง",
    "ฉลากอาหาร",
    "ค่าคงที่ของคุณ",
    "สูตรอาหารที่คำนวณแล้ว",
    "โปรตีน",
    "คาร์โบไฮเดรต",
    "อ้วน",
    "น้ำตาล",
    "แคลเซียม",
    "ฟอสฟอรัส",
    "เหล็ก",
    "วิตามินซี",
    "มล",
    "1 ชิ้น",
    "{count} ชิ้น",
    "กรัม",
  ],
  "pl": [
    "Nieznane",
    "Szacunkowe",
    "Szczegóły produktu",
    "Szczegóły wartości odżywczych",
    "Działania na potwierdzeniu",
    "Szacunkowa porcja",
    "Zdjęcie niedostępne",
    "Tak, zapisz",
    "Dostosuj",
    "Przetwarzanie…",
    "Źródła",
    "Pewność źródła",
    "Pewność identyfikacji produktu",
    "Pewność ilości",
    "Zobacz w dzienniku",
    "Potwierdzenie zapisu tego produktu jest niedostępne. Sprawdź dziennik.",
    "Twoje konto się zmieniło. Wróć do Trenera, aby kontynuować.",
    "Nie udało się ukończyć działania. Dane do sprawdzenia zostały zachowane.",
    "Ten posiłek się zmienił. Sprawdź aktualny wpis przed edycją lub cofnięciem.",
    "To sprawdzenie zostało zakończone.",
    "Wpis cofnięty",
    "Posiłek zaktualizowany",
    "Wpis usunięty",
    "Posiłek przeniesiony",
    "Wpis kalorii zapisany",
    "Wpis wartości odżywczych zapisany",
    "Nieznane jedzenie",
    "Posiłek",
    "Dobrze! Zapiszę posiłek „{meal}”. Oto, co udało mi się ustalić:",
    "Czy zapisać to jako „{meal}”?",
    "{meal}: zapisano",
    "Źródło referencyjne",
    "Etykieta produktu",
    "Twoje stałe wartości",
    "Obliczony przepis",
    "Białko",
    "Węglowodany",
    "Gruby",
    "Cukier",
    "Wapń",
    "Fosfor",
    "Żelazo",
    "Witamina C",
    "ml",
    "1 sztuka",
    "Liczba sztuk: {count}",
    "g",
  ],
  "nl": [
    "Onbekend",
    "Geschat",
    "Voedingsmiddeldetails",
    "Voedingswaardedetails",
    "Acties voor het bewijs",
    "Geschatte portie",
    "Foto niet beschikbaar",
    "Ja, vastleggen",
    "Aanpassen",
    "Bezig…",
    "Bronnen",
    "Zekerheid over de bron",
    "Zekerheid over de voedselidentificatie",
    "Zekerheid over de hoeveelheid",
    "Bekijken in het dagboek",
    "Dit bewijs van je voedingsinvoer is niet beschikbaar. Bekijk je dagboek.",
    "Je account is gewijzigd. Ga terug naar Coach om door te gaan.",
    "De actie kon niet worden voltooid. Je controle is bewaard.",
    "Deze maaltijd is gewijzigd. Controleer de huidige invoer voordat je deze bewerkt of ongedaan maakt.",
    "Deze controle is gesloten.",
    "Invoer ongedaan gemaakt",
    "Maaltijd bijgewerkt",
    "Invoer verwijderd",
    "Maaltijd verplaatst",
    "Calorie-invoer opgeslagen",
    "Voedingswaarde-invoer opgeslagen",
    "Onbekend eten",
    "Maaltijd",
    "Prima! Ik zal je {meal} vastleggen. Dit heb ik begrepen:",
    "Zal ik dit aan je {meal} toevoegen?",
    "{meal} vastgelegd",
    "Referentie",
    "Voedingsetiket",
    "Je vaste waarden",
    "Berekend recept",
    "Eiwit",
    "Koolhydraten",
    "Vet",
    "Suiker",
    "Kalk",
    "Fosfor",
    "Ijzer",
    "Vitamine C",
    "ml",
    "1 stuk",
    "{count} stuks",
    "g",
  ],
  "uk": [
    "Невідомо",
    "Оцінка",
    "Відомості про продукт",
    "Відомості про поживну цінність",
    "Дії з підтвердженням",
    "Приблизна порція",
    "Фото недоступне",
    "Так, записати",
    "Уточнити",
    "Обробка…",
    "Джерела",
    "Впевненість у джерелі",
    "Впевненість у визначенні продукту",
    "Впевненість у кількості",
    "Переглянути в щоденнику",
    "Підтвердження запису цього продукту недоступне. Перевірте щоденник.",
    "Обліковий запис змінився. Поверніться до тренера, щоб продовжити.",
    "Не вдалося завершити дію. Дані перевірки збережено.",
    "Цей прийом їжі змінився. Перевірте поточний запис перед редагуванням або скасуванням.",
    "Цю перевірку завершено.",
    "Запис скасовано",
    "Прийом їжі оновлено",
    "Запис видалено",
    "Прийом їжі перенесено",
    "Запис калорій збережено",
    "Запис поживної цінності збережено",
    "Невідома їжа",
    "Харчування",
    "Гаразд! Я запишу ваш прийом їжі «{meal}». Ось як я вас зрозумів:",
    "Записати це як «{meal}»?",
    "{meal}: записано",
    "Довідкове джерело",
    "Етикетка продукту",
    "Ваші фіксовані значення",
    "Розрахований рецепт",
    "білок",
    "вуглеводи",
    "Жир",
    "цукор",
    "Кальцій",
    "Фосфор",
    "Залізо",
    "Вітамін C",
    "мл",
    "1 штука",
    "Кількість штук: {count}",
    "г",
  ],
};
