/// Copy for the human-facing recipe editor. Columns follow [keys] exactly.
abstract final class RecipeEditorRuntimeCopy {
  static const keys = [
    'Prep time (min)',
    'Cook time (min)',
    'Check the required fields, quantities, units, times, and steps.',
    'Review recipe',
    'Nutrition not included',
    'No nutrition values will be inferred or invented.',
    'Nutrition with provenance',
    'This recipe is already saved.',
    'The recipe could not be saved.',
    'This is your confirmation, not professional nutrition verification.',
    'One or more ingredients still need an exact food-record match.',
    'Nutrition values need review.',
  ];

  static const translations = <String, List<String>>{
    'en': keys,
    'ar': [
      'وقت التحضير (دقيقة)',
      'وقت الطهي (دقيقة)',
      'تحقق من الحقول المطلوبة والكميات والوحدات والأوقات والخطوات.',
      'مراجعة الوصفة',
      'لا توجد قيم غذائية',
      'لن تُقدّر أو تُختلق أي قيم غذائية.',
      'قيم غذائية مع مصدرها',
      'هذه الوصفة محفوظة بالفعل.',
      'تعذر حفظ الوصفة.',
      'هذا تأكيدك الشخصي، وليس تحققًا غذائيًا مهنيًا.',
      'ما زال مكوّن أو أكثر يحتاج إلى مطابقة دقيقة مع سجل الطعام.',
      'القيم الغذائية تحتاج إلى مراجعة.',
    ],
    'fr': [
      'Préparation (min)',
      'Cuisson (min)',
      'Vérifiez les champs requis, quantités, unités, durées et étapes.',
      'Vérifier la recette',
      'Valeurs nutritionnelles absentes',
      'Aucune valeur nutritionnelle ne sera estimée ni inventée.',
      'Valeurs nutritionnelles avec source',
      'Cette recette est déjà enregistrée.',
      'Impossible d’enregistrer la recette.',
      'Il s’agit de votre confirmation, pas d’une vérification nutritionnelle professionnelle.',
      'Un ou plusieurs ingrédients nécessitent encore une correspondance exacte avec une fiche alimentaire.',
      'Les valeurs nutritionnelles doivent être vérifiées.',
    ],
    'es': [
      'Preparación (min)',
      'Cocción (min)',
      'Revisa los campos obligatorios, cantidades, unidades, tiempos y pasos.',
      'Revisar receta',
      'Sin valores nutricionales',
      'No se estimarán ni inventarán valores nutricionales.',
      'Valores nutricionales con su fuente',
      'Esta receta ya está guardada.',
      'No se pudo guardar la receta.',
      'Esta es tu confirmación, no una verificación nutricional profesional.',
      'Uno o más ingredientes aún necesitan una coincidencia exacta con un registro de alimentos.',
      'Es necesario revisar los valores nutricionales.',
    ],
    'tr': [
      'Hazırlık süresi (dk)',
      'Pişirme süresi (dk)',
      'Zorunlu alanları, miktarları, birimleri, süreleri ve adımları kontrol edin.',
      'Tarifi incele',
      'Besin değerleri yok',
      'Besin değerleri tahmin edilmeyecek veya uydurulmayacaktır.',
      'Kaynağı belirtilen besin değerleri',
      'Bu tarif zaten kayıtlı.',
      'Tarif kaydedilemedi.',
      'Bu sizin onayınızdır; profesyonel beslenme doğrulaması değildir.',
      'Bir veya daha fazla malzeme hâlâ bir gıda kaydıyla tam eşleşme gerektiriyor.',
      'Besin değerlerinin incelenmesi gerekiyor.',
    ],
    'de': [
      'Vorbereitung (Min.)',
      'Garzeit (Min.)',
      'Prüfe Pflichtfelder, Mengen, Einheiten, Zeiten und Schritte.',
      'Rezept prüfen',
      'Keine Nährwerte enthalten',
      'Es werden keine Nährwerte geschätzt oder erfunden.',
      'Nährwerte mit Quellenangabe',
      'Dieses Rezept ist bereits gespeichert.',
      'Das Rezept konnte nicht gespeichert werden.',
      'Dies ist deine Bestätigung, keine professionelle Nährwertprüfung.',
      'Mindestens eine Zutat muss noch genau einem Lebensmitteldatensatz zugeordnet werden.',
      'Die Nährwerte müssen überprüft werden.',
    ],
    'it': [
      'Preparazione (min)',
      'Cottura (min)',
      'Controlla campi obbligatori, quantità, unità, tempi e passaggi.',
      'Rivedi ricetta',
      'Valori nutrizionali assenti',
      'Nessun valore nutrizionale sarà stimato o inventato.',
      'Valori nutrizionali con fonte',
      'Questa ricetta è già salvata.',
      'Impossibile salvare la ricetta.',
      'Questa è la tua conferma, non una verifica nutrizionale professionale.',
      'Uno o più ingredienti richiedono ancora una corrispondenza esatta con una scheda alimentare.',
      'I valori nutrizionali devono essere verificati.',
    ],
    'pt-BR': [
      'Preparo (min)',
      'Cozimento (min)',
      'Confira os campos obrigatórios, quantidades, unidades, tempos e etapas.',
      'Revisar receita',
      'Sem valores nutricionais',
      'Nenhum valor nutricional será estimado ou inventado.',
      'Valores nutricionais com fonte',
      'Esta receita já está salva.',
      'Não foi possível salvar a receita.',
      'Esta é a sua confirmação, não uma verificação nutricional profissional.',
      'Um ou mais ingredientes ainda precisam corresponder exatamente a um registro de alimento.',
      'Os valores nutricionais precisam de revisão.',
    ],
    'pt-PT': [
      'Preparação (min)',
      'Cozedura (min)',
      'Verifique os campos obrigatórios, quantidades, unidades, tempos e passos.',
      'Rever receita',
      'Sem valores nutricionais',
      'Nenhum valor nutricional será estimado ou inventado.',
      'Valores nutricionais com fonte',
      'Esta receita já está guardada.',
      'Não foi possível guardar a receita.',
      'Esta é a sua confirmação, não uma verificação nutricional profissional.',
      'Um ou mais ingredientes ainda precisam de corresponder exatamente a um registo alimentar.',
      'Os valores nutricionais precisam de revisão.',
    ],
    'ur': [
      'تیاری کا وقت (منٹ)',
      'پکانے کا وقت (منٹ)',
      'ضروری خانے، مقداریں، اکائیاں، اوقات اور مراحل چیک کریں۔',
      'ترکیب کا جائزہ لیں',
      'غذائی قدریں شامل نہیں',
      'غذائی قدریں اندازے سے یا من گھڑت نہیں بنائی جائیں گی۔',
      'ماخذ کے ساتھ غذائی قدریں',
      'یہ ترکیب پہلے سے محفوظ ہے۔',
      'ترکیب محفوظ نہیں ہو سکی۔',
      'یہ آپ کی تصدیق ہے، پیشہ ورانہ غذائی جانچ نہیں۔',
      'ایک یا زیادہ اجزاء کو اب بھی خوراک کے ریکارڈ سے درست ملانا ضروری ہے۔',
      'غذائی قدروں کا جائزہ ضروری ہے۔',
    ],
    'fa': [
      'زمان آماده‌سازی (دقیقه)',
      'زمان پخت (دقیقه)',
      'فیلدهای ضروری، مقدارها، واحدها، زمان‌ها و مراحل را بررسی کنید.',
      'بررسی دستور غذا',
      'ارزش غذایی درج نشده',
      'هیچ ارزش غذایی تخمین زده یا ساخته نمی‌شود.',
      'ارزش غذایی همراه با منبع',
      'این دستور غذا قبلاً ذخیره شده است.',
      'دستور غذا ذخیره نشد.',
      'این تأیید شماست، نه بررسی حرفه‌ای ارزش غذایی.',
      'یک یا چند ماده هنوز نیازمند تطبیق دقیق با رکورد غذایی است.',
      'ارزش غذایی نیاز به بررسی دارد.',
    ],
    'hi': [
      'तैयारी का समय (मिनट)',
      'पकाने का समय (मिनट)',
      'ज़रूरी फ़ील्ड, मात्राएँ, इकाइयाँ, समय और चरण जाँचें।',
      'रेसिपी की समीक्षा करें',
      'पोषण मान शामिल नहीं हैं',
      'पोषण मानों का अनुमान नहीं लगाया जाएगा या उन्हें गढ़ा नहीं जाएगा।',
      'स्रोत सहित पोषण मान',
      'यह रेसिपी पहले से सहेजी गई है।',
      'रेसिपी सहेजी नहीं जा सकी।',
      'यह आपकी पुष्टि है, पेशेवर पोषण सत्यापन नहीं।',
      'एक या अधिक सामग्रियों का अभी खाद्य रिकॉर्ड से सटीक मिलान करना बाकी है।',
      'पोषण मानों की समीक्षा आवश्यक है।',
    ],
    'id': [
      'Waktu persiapan (mnt)',
      'Waktu memasak (mnt)',
      'Periksa kolom wajib, jumlah, satuan, waktu, dan langkah.',
      'Tinjau resep',
      'Nilai gizi belum tersedia',
      'Tidak ada nilai gizi yang akan diperkirakan atau dikarang.',
      'Nilai gizi beserta sumbernya',
      'Resep ini sudah disimpan.',
      'Resep tidak dapat disimpan.',
      'Ini konfirmasi Anda, bukan verifikasi gizi profesional.',
      'Satu atau beberapa bahan masih perlu dicocokkan secara tepat dengan catatan makanan.',
      'Nilai gizi perlu ditinjau.',
    ],
    'ms': [
      'Masa penyediaan (min)',
      'Masa memasak (min)',
      'Semak medan wajib, kuantiti, unit, masa dan langkah.',
      'Semak resipi',
      'Nilai pemakanan tidak disertakan',
      'Tiada nilai pemakanan akan dianggarkan atau direka.',
      'Nilai pemakanan berserta sumber',
      'Resipi ini telah disimpan.',
      'Resipi tidak dapat disimpan.',
      'Ini pengesahan anda, bukan pengesahan pemakanan profesional.',
      'Satu atau lebih ramuan masih memerlukan padanan tepat dengan rekod makanan.',
      'Nilai pemakanan perlu disemak.',
    ],
    'bn': [
      'প্রস্তুতির সময় (মিনিট)',
      'রান্নার সময় (মিনিট)',
      'আবশ্যিক ঘর, পরিমাণ, একক, সময় ও ধাপগুলো পরীক্ষা করুন।',
      'রেসিপি পর্যালোচনা করুন',
      'পুষ্টির মান অন্তর্ভুক্ত নেই',
      'কোনো পুষ্টির মান অনুমান বা বানানো হবে না।',
      'উৎসসহ পুষ্টির মান',
      'এই রেসিপি ইতিমধ্যে সংরক্ষিত আছে।',
      'রেসিপি সংরক্ষণ করা যায়নি।',
      'এটি আপনার নিশ্চিতকরণ, পেশাদার পুষ্টি যাচাই নয়।',
      'এক বা একাধিক উপাদানের এখনও খাদ্য রেকর্ডের সঙ্গে নির্ভুল মিল প্রয়োজন।',
      'পুষ্টির মান পর্যালোচনা করা প্রয়োজন।',
    ],
    'ru': [
      'Подготовка (мин)',
      'Приготовление (мин)',
      'Проверьте обязательные поля, количества, единицы, время и шаги.',
      'Проверить рецепт',
      'Пищевая ценность не указана',
      'Пищевая ценность не будет оцениваться или выдумываться.',
      'Пищевая ценность с указанием источника',
      'Этот рецепт уже сохранён.',
      'Не удалось сохранить рецепт.',
      'Это ваше подтверждение, а не профессиональная проверка пищевой ценности.',
      'Для одного или нескольких ингредиентов ещё требуется точное соответствие записи о продукте.',
      'Пищевая ценность требует проверки.',
    ],
    'ja': [
      '準備時間（分）',
      '調理時間（分）',
      '必須項目、分量、単位、時間、手順を確認してください。',
      'レシピを確認',
      '栄養値は未記載',
      '栄養値の推測や捏造は行いません。',
      '出典付きの栄養値',
      'このレシピは保存済みです。',
      'レシピを保存できませんでした。',
      'これはご自身による確認であり、専門家による栄養値の検証ではありません。',
      '一部の材料は食品レコードとの正確な照合がまだ必要です。',
      '栄養値の確認が必要です。',
    ],
    'ko': [
      '준비 시간(분)',
      '조리 시간(분)',
      '필수 항목, 수량, 단위, 시간 및 단계를 확인하세요.',
      '레시피 검토',
      '영양 정보 없음',
      '영양 수치를 추정하거나 만들어 내지 않습니다.',
      '출처가 표시된 영양 정보',
      '이미 저장된 레시피입니다.',
      '레시피를 저장하지 못했습니다.',
      '사용자 본인의 확인이며, 전문가의 영양 검증이 아닙니다.',
      '하나 이상의 재료를 식품 기록과 정확히 일치시켜야 합니다.',
      '영양 수치를 검토해야 합니다.',
    ],
    'zh-Hans': [
      '准备时间（分钟）',
      '烹饪时间（分钟）',
      '请检查必填项、用量、单位、时间和步骤。',
      '检查食谱',
      '未包含营养数值',
      '不会推测或编造任何营养数值。',
      '附有来源的营养数值',
      '此食谱已保存。',
      '无法保存食谱。',
      '这是您的个人确认，并非专业营养核验。',
      '一个或多个食材仍需与食品记录精确匹配。',
      '营养数值需要核查。',
    ],
    'zh-Hant': [
      '準備時間（分鐘）',
      '烹飪時間（分鐘）',
      '請檢查必填欄位、用量、單位、時間和步驟。',
      '檢查食譜',
      '未包含營養數值',
      '不會推測或編造任何營養數值。',
      '附有來源的營養數值',
      '此食譜已儲存。',
      '無法儲存食譜。',
      '這是您的個人確認，並非專業營養核驗。',
      '一個或多個食材仍需與食品記錄精確配對。',
      '營養數值需要核查。',
    ],
    'th': [
      'เวลาเตรียม (นาที)',
      'เวลาปรุง (นาที)',
      'ตรวจสอบช่องที่จำเป็น ปริมาณ หน่วย เวลา และขั้นตอน',
      'ตรวจสอบสูตรอาหาร',
      'ไม่มีค่าทางโภชนาการ',
      'จะไม่มีการประมาณหรือแต่งค่าทางโภชนาการขึ้นเอง',
      'ค่าทางโภชนาการพร้อมแหล่งอ้างอิง',
      'บันทึกสูตรนี้ไว้แล้ว',
      'ไม่สามารถบันทึกสูตรอาหารได้',
      'นี่เป็นการยืนยันของคุณ ไม่ใช่การตรวจสอบโภชนาการโดยผู้เชี่ยวชาญ',
      'วัตถุดิบอย่างน้อยหนึ่งรายการยังต้องจับคู่กับระเบียนอาหารให้ตรงกัน',
      'ค่าทางโภชนาการต้องได้รับการตรวจสอบ',
    ],
    'vi': [
      'Thời gian chuẩn bị (phút)',
      'Thời gian nấu (phút)',
      'Kiểm tra các trường bắt buộc, lượng, đơn vị, thời gian và các bước.',
      'Xem lại công thức',
      'Chưa có giá trị dinh dưỡng',
      'Không ước tính hoặc bịa ra giá trị dinh dưỡng.',
      'Giá trị dinh dưỡng có nguồn',
      'Công thức này đã được lưu.',
      'Không thể lưu công thức.',
      'Đây là xác nhận của bạn, không phải kiểm chứng dinh dưỡng chuyên môn.',
      'Một hoặc nhiều nguyên liệu vẫn cần khớp chính xác với hồ sơ thực phẩm.',
      'Cần kiểm tra lại giá trị dinh dưỡng.',
    ],
    'pl': [
      'Przygotowanie (min)',
      'Gotowanie (min)',
      'Sprawdź wymagane pola, ilości, jednostki, czasy i kroki.',
      'Sprawdź przepis',
      'Brak wartości odżywczych',
      'Wartości odżywcze nie będą szacowane ani wymyślane.',
      'Wartości odżywcze ze źródłem',
      'Ten przepis jest już zapisany.',
      'Nie udało się zapisać przepisu.',
      'To Twoje potwierdzenie, a nie profesjonalna weryfikacja wartości odżywczych.',
      'Co najmniej jeden składnik nadal wymaga dokładnego dopasowania do rekordu żywności.',
      'Wartości odżywcze wymagają sprawdzenia.',
    ],
    'nl': [
      'Voorbereiding (min)',
      'Bereidingstijd (min)',
      'Controleer verplichte velden, hoeveelheden, eenheden, tijden en stappen.',
      'Recept controleren',
      'Geen voedingswaarden opgenomen',
      'Er worden geen voedingswaarden geschat of verzonnen.',
      'Voedingswaarden met bron',
      'Dit recept is al opgeslagen.',
      'Het recept kon niet worden opgeslagen.',
      'Dit is jouw bevestiging, geen professionele controle van voedingswaarden.',
      'Een of meer ingrediënten moeten nog exact aan een voedingsrecord worden gekoppeld.',
      'De voedingswaarden moeten worden gecontroleerd.',
    ],
    'uk': [
      'Підготовка (хв)',
      'Приготування (хв)',
      'Перевірте обов’язкові поля, кількості, одиниці, час і кроки.',
      'Перевірити рецепт',
      'Харчову цінність не вказано',
      'Харчову цінність не буде оцінено або вигадано.',
      'Харчова цінність із джерелом',
      'Цей рецепт уже збережено.',
      'Не вдалося зберегти рецепт.',
      'Це ваше підтвердження, а не професійна перевірка харчової цінності.',
      'Один або кілька інгредієнтів ще потребують точного зіставлення із записом продукту.',
      'Харчова цінність потребує перевірки.',
    ],
  };

  static String? resolve(String english, String locale) {
    const basic = <String, Map<String, String>>{
      'Name': {'ar': 'الاسم', 'fr': 'Nom', 'es': 'Nombre', 'tr': 'Ad'},
      'Servings': {
        'ar': 'الحصص',
        'fr': 'Portions',
        'es': 'Porciones',
        'tr': 'Porsiyon',
      },
      'Remove': {
        'ar': 'إزالة',
        'fr': 'Supprimer',
        'es': 'Quitar',
        'tr': 'Kaldır',
      },
      'Add': {'ar': 'إضافة', 'fr': 'Ajouter', 'es': 'Añadir', 'tr': 'Ekle'},
    };
    final base = basic[english]?[locale.split(RegExp('[-_]')).first];
    if (base != null) return base;
    final index = keys.indexOf(english);
    if (index < 0) return null;
    final normalized = locale.replaceAll('_', '-').toLowerCase();
    for (final entry in translations.entries) {
      if (entry.key.toLowerCase() == normalized) return entry.value[index];
    }
    return null;
  }
}
