import 'bil_locale_rollout_manifest.dart';

/// Typed copy keys for the complete meal voice-entry journey.
///
/// Keeping these as an enum prevents a missing or misspelled English source
/// sentence from silently falling back at runtime.
enum MealVoiceCopyKey {
  title,
  instructions,
  reviewLabel,
  cancel,
  useForSearch,
  unavailable,
  ok,
  permissionDenied,
  microphonePermissionTitle,
  microphonePermissionRationale,
  speechPermissionTitle,
  speechPermissionRationale,
  microphoneSettingsRecovery,
  speechSettingsRecovery,
  openSettings,
  continueLabel,
  timeout,
  noMatch,
  localeUnavailable,
  recognizerUnavailable,
  unknown,
}

/// Complete, feature-owned runtime copy for meal voice entry.
///
/// Rows follow [MealVoiceCopyKey] order. The catalog intentionally contains
/// exactly the 25 production locale tags. Regional and script variants remain
/// distinct instead of being collapsed to a language code.
abstract final class MealVoiceRuntimeCopy {
  static const productionLocaleTags = BilLocaleRolloutManifest.releaseTargets25;

  static const _rows = <String, List<String>>{
    'en': <String>[
      'Say the food name',
      'Speak a food and optional amount. Edit the recognized words, then approve them for search. Nothing is logged automatically.',
      'Review recognized words',
      'Cancel',
      'Use for food search',
      'Voice input unavailable',
      'OK',
      'Microphone or speech permission was denied.',
      'Allow microphone access for this action?',
      'BIL uses the microphone only after you choose voice food entry. You can review the recognized text before search, and nothing is logged automatically.',
      'Allow speech recognition for this action?',
      'BIL uses speech recognition only after you choose voice food entry. You can review the recognized text before search, and nothing is logged automatically.',
      'Microphone access is off. Enable it in system settings to use voice food entry; manual entry remains available.',
      'Speech recognition access is off. Enable it in system settings to use voice food entry; manual entry remains available.',
      'Open system settings',
      'Continue',
      'No speech was detected before the time limit.',
      'No usable food phrase was recognized.',
      'This device has no recognizer for the selected app language.',
      'This device has no available speech recognition service.',
      'Speech recognition stopped unexpectedly.',
    ],
    'ar': <String>[
      'قل اسم الطعام',
      'اذكر الطعام والكمية إن رغبت. عدّل الكلمات المتعرّف عليها ثم وافق لاستخدامها في البحث. لن يُسجل شيء تلقائيًا.',
      'مراجعة الكلمات المتعرّف عليها',
      'إلغاء',
      'استخدامها في بحث الطعام',
      'الإدخال الصوتي غير متاح',
      'حسنًا',
      'رُفض إذن الميكروفون أو التعرف على الكلام.',
      'السماح بالوصول إلى الميكروفون لهذا الإجراء؟',
      'يستخدم BIL الميكروفون فقط بعد اختيار إدخال الطعام صوتيًا. يمكنك مراجعة النص قبل البحث، ولن يُسجل شيء تلقائيًا.',
      'السماح بالتعرف على الكلام لهذا الإجراء؟',
      'يستخدم BIL التعرف على الكلام فقط بعد اختيار إدخال الطعام صوتيًا. يمكنك مراجعة النص قبل البحث، ولن يُسجل شيء تلقائيًا.',
      'إذن الميكروفون متوقف. فعّله في إعدادات النظام لاستخدام إدخال الطعام صوتيًا؛ ويظل الإدخال اليدوي متاحًا.',
      'إذن التعرف على الكلام متوقف. فعّله في إعدادات النظام لاستخدام إدخال الطعام صوتيًا؛ ويظل الإدخال اليدوي متاحًا.',
      'فتح إعدادات النظام',
      'متابعة',
      'لم يُكتشف كلام قبل انتهاء المهلة.',
      'لم يتم التعرف على عبارة طعام صالحة.',
      'لا يحتوي الجهاز على متعرّف للغة التطبيق المختارة.',
      'لا تتوفر خدمة تعرف صوتي على هذا الجهاز.',
      'توقف التعرف على الكلام بشكل غير متوقع.',
    ],
    'fr': <String>[
      'Dites le nom de l’aliment',
      'Dictez un aliment et une quantité facultative. Modifiez le texte, puis validez-le pour la recherche. Rien n’est enregistré automatiquement.',
      'Vérifier les mots reconnus',
      'Annuler',
      'Utiliser pour la recherche d’aliments',
      'Saisie vocale indisponible',
      'OK',
      'L’autorisation du micro ou de la reconnaissance vocale a été refusée.',
      'Autoriser l’accès au micro pour cette action ?',
      'BIL utilise le micro uniquement après votre choix de saisie vocale. Vous pouvez vérifier le texte avant la recherche et rien n’est enregistré automatiquement.',
      'Autoriser la reconnaissance vocale pour cette action ?',
      'BIL utilise la reconnaissance vocale uniquement après votre choix de saisie vocale. Vous pouvez vérifier le texte avant la recherche et rien n’est enregistré automatiquement.',
      'L’accès au microphone est désactivé. Activez-le dans les réglages pour utiliser la saisie vocale des aliments ; la saisie manuelle reste disponible.',
      'L’accès à la reconnaissance vocale est désactivé. Activez-le dans les réglages pour utiliser la saisie vocale des aliments ; la saisie manuelle reste disponible.',
      'Ouvrir les réglages système',
      'Continuer',
      'Aucune parole détectée avant la fin du délai.',
      'Aucune expression alimentaire utilisable reconnue.',
      'Aucun module vocal pour la langue choisie sur cet appareil.',
      'Aucun service de reconnaissance vocale disponible.',
      'La reconnaissance vocale s’est arrêtée inopinément.',
    ],
    'es': <String>[
      'Di el nombre del alimento',
      'Di un alimento y una cantidad opcional. Edita el texto y apruébalo para buscar. Nada se registra automáticamente.',
      'Revisar palabras reconocidas',
      'Cancelar',
      'Usar para buscar alimentos',
      'Entrada de voz no disponible',
      'Aceptar',
      'Se denegó el permiso del micrófono o reconocimiento de voz.',
      '¿Permitir el acceso al micrófono para esta acción?',
      'BIL usa el micrófono solo después de elegir la entrada de alimentos por voz. Puedes revisar el texto antes de buscar y nada se registra automáticamente.',
      '¿Permitir el reconocimiento de voz para esta acción?',
      'BIL usa el reconocimiento de voz solo después de elegir la entrada de alimentos por voz. Puedes revisar el texto antes de buscar y nada se registra automáticamente.',
      'El acceso al micrófono está desactivado. Actívalo en los ajustes para usar la entrada de alimentos por voz; la entrada manual sigue disponible.',
      'El acceso al reconocimiento de voz está desactivado. Actívalo en los ajustes para usar la entrada de alimentos por voz; la entrada manual sigue disponible.',
      'Abrir ajustes del sistema',
      'Continuar',
      'No se detectó voz antes del límite de tiempo.',
      'No se reconoció una frase de alimento válida.',
      'El dispositivo no tiene reconocimiento para el idioma elegido.',
      'No hay servicio de reconocimiento de voz disponible.',
      'El reconocimiento de voz se detuvo inesperadamente.',
    ],
    'tr': <String>[
      'Yiyeceğin adını söyleyin',
      'Yiyeceği ve isteğe bağlı miktarı söyleyin. Metni düzenleyip arama için onaylayın. Hiçbir şey otomatik kaydedilmez.',
      'Algılanan sözcükleri incele',
      'İptal',
      'Yiyecek aramasında kullan',
      'Sesli giriş kullanılamıyor',
      'Tamam',
      'Mikrofon veya konuşma tanıma izni reddedildi.',
      'Bu işlem için mikrofon erişimine izin verilsin mi?',
      'BIL mikrofonu yalnızca sesli yiyecek girişini seçtikten sonra kullanır. Aramadan önce metni inceleyebilirsiniz ve hiçbir şey otomatik kaydedilmez.',
      'Bu işlem için konuşma tanımaya izin verilsin mi?',
      'BIL konuşma tanımayı yalnızca sesli yiyecek girişini seçtikten sonra kullanır. Aramadan önce metni inceleyebilirsiniz ve hiçbir şey otomatik kaydedilmez.',
      'Mikrofon erişimi kapalı. Sesli yiyecek girişini kullanmak için sistem ayarlarından açın; manuel giriş kullanılabilir.',
      'Konuşma tanıma erişimi kapalı. Sesli yiyecek girişini kullanmak için sistem ayarlarından açın; manuel giriş kullanılabilir.',
      'Sistem ayarlarını aç',
      'Devam',
      'Süre dolmadan konuşma algılanmadı.',
      'Kullanılabilir bir yiyecek ifadesi algılanmadı.',
      'Bu cihazda seçilen dil için tanıyıcı yok.',
      'Bu cihazda konuşma tanıma hizmeti yok.',
      'Konuşma tanıma beklenmedik şekilde durdu.',
    ],
    'de': <String>[
      'Sag den Namen des Lebensmittels',
      'Nenne ein Lebensmittel und optional eine Menge. Bearbeite den erkannten Text und bestätige ihn für die Suche. Nichts wird automatisch protokolliert.',
      'Erkannten Text prüfen',
      'Abbrechen',
      'Für Lebensmittelsuche verwenden',
      'Spracheingabe nicht verfügbar',
      'OK',
      'Die Mikrofon- oder Spracherkennungsberechtigung wurde verweigert.',
      'Mikrofonzugriff für diese Aktion erlauben?',
      'BIL verwendet das Mikrofon erst, wenn du die Spracheingabe für Lebensmittel wählst. Du kannst den Text vor der Suche prüfen; nichts wird automatisch protokolliert.',
      'Spracherkennung für diese Aktion erlauben?',
      'BIL verwendet die Spracherkennung erst, wenn du die Spracheingabe für Lebensmittel wählst. Du kannst den Text vor der Suche prüfen; nichts wird automatisch protokolliert.',
      'Der Mikrofonzugriff ist deaktiviert. Aktiviere ihn in den Systemeinstellungen für die Spracheingabe; die manuelle Eingabe bleibt verfügbar.',
      'Die Spracherkennung ist deaktiviert. Aktiviere sie in den Systemeinstellungen für die Spracheingabe; die manuelle Eingabe bleibt verfügbar.',
      'Systemeinstellungen öffnen',
      'Weiter',
      'Vor Ablauf der Zeit wurde keine Sprache erkannt.',
      'Es wurde kein verwendbarer Lebensmittelbegriff erkannt.',
      'Dieses Gerät hat keine Erkennung für die gewählte App-Sprache.',
      'Auf diesem Gerät ist keine Spracherkennung verfügbar.',
      'Die Spracherkennung wurde unerwartet beendet.',
    ],
    'it': <String>[
      'Pronuncia il nome dell’alimento',
      'Pronuncia un alimento e, se vuoi, una quantità. Modifica il testo riconosciuto e confermalo per la ricerca. Nulla viene registrato automaticamente.',
      'Controlla le parole riconosciute',
      'Annulla',
      'Usa per cercare alimenti',
      'Inserimento vocale non disponibile',
      'OK',
      'L’autorizzazione al microfono o al riconoscimento vocale è stata negata.',
      'Consentire l’accesso al microfono per questa azione?',
      'BIL usa il microfono solo dopo che scegli l’inserimento vocale degli alimenti. Puoi controllare il testo prima della ricerca e nulla viene registrato automaticamente.',
      'Consentire il riconoscimento vocale per questa azione?',
      'BIL usa il riconoscimento vocale solo dopo che scegli l’inserimento vocale degli alimenti. Puoi controllare il testo prima della ricerca e nulla viene registrato automaticamente.',
      'L’accesso al microfono è disattivato. Attivalo nelle impostazioni di sistema per usare l’inserimento vocale; l’inserimento manuale resta disponibile.',
      'Il riconoscimento vocale è disattivato. Attivalo nelle impostazioni di sistema per usare l’inserimento vocale; l’inserimento manuale resta disponibile.',
      'Apri le impostazioni di sistema',
      'Continua',
      'Non è stata rilevata alcuna voce entro il limite di tempo.',
      'Non è stata riconosciuta una frase alimentare utilizzabile.',
      'Il dispositivo non dispone del riconoscimento per la lingua scelta.',
      'Il dispositivo non dispone di un servizio di riconoscimento vocale.',
      'Il riconoscimento vocale si è interrotto inaspettatamente.',
    ],
    'pt-BR': <String>[
      'Diga o nome do alimento',
      'Diga um alimento e uma quantidade opcional. Edite o texto reconhecido e confirme para pesquisar. Nada é registrado automaticamente.',
      'Revisar palavras reconhecidas',
      'Cancelar',
      'Usar na busca de alimentos',
      'Entrada de voz indisponível',
      'OK',
      'A permissão do microfone ou do reconhecimento de fala foi negada.',
      'Permitir acesso ao microfone nesta ação?',
      'O BIL usa o microfone somente depois que você escolhe a entrada de alimentos por voz. Você pode revisar o texto antes da busca e nada é registrado automaticamente.',
      'Permitir reconhecimento de fala nesta ação?',
      'O BIL usa o reconhecimento de fala somente depois que você escolhe a entrada de alimentos por voz. Você pode revisar o texto antes da busca e nada é registrado automaticamente.',
      'O acesso ao microfone está desativado. Ative-o nos ajustes do sistema para usar a entrada por voz; a entrada manual continua disponível.',
      'O reconhecimento de fala está desativado. Ative-o nos ajustes do sistema para usar a entrada por voz; a entrada manual continua disponível.',
      'Abrir ajustes do sistema',
      'Continuar',
      'Nenhuma fala foi detectada antes do limite de tempo.',
      'Nenhuma expressão de alimento utilizável foi reconhecida.',
      'Este dispositivo não tem reconhecimento para o idioma escolhido no app.',
      'Este dispositivo não tem serviço de reconhecimento de fala disponível.',
      'O reconhecimento de fala parou inesperadamente.',
    ],
    'pt-PT': <String>[
      'Diga o nome do alimento',
      'Diga um alimento e uma quantidade opcional. Edite o texto reconhecido e confirme-o para pesquisar. Nada é registado automaticamente.',
      'Rever palavras reconhecidas',
      'Cancelar',
      'Usar na pesquisa de alimentos',
      'Introdução por voz indisponível',
      'OK',
      'A permissão do microfone ou do reconhecimento de voz foi recusada.',
      'Permitir o acesso ao microfone nesta ação?',
      'O BIL utiliza o microfone apenas depois de escolher a introdução de alimentos por voz. Pode rever o texto antes da pesquisa e nada é registado automaticamente.',
      'Permitir o reconhecimento de voz nesta ação?',
      'O BIL utiliza o reconhecimento de voz apenas depois de escolher a introdução de alimentos por voz. Pode rever o texto antes da pesquisa e nada é registado automaticamente.',
      'O acesso ao microfone está desativado. Ative-o nas definições do sistema para usar a introdução por voz; a introdução manual continua disponível.',
      'O reconhecimento de voz está desativado. Ative-o nas definições do sistema para usar a introdução por voz; a introdução manual continua disponível.',
      'Abrir definições do sistema',
      'Continuar',
      'Não foi detetada fala antes do limite de tempo.',
      'Não foi reconhecida uma expressão de alimento utilizável.',
      'Este dispositivo não tem reconhecimento para o idioma escolhido na aplicação.',
      'Este dispositivo não tem um serviço de reconhecimento de voz disponível.',
      'O reconhecimento de voz parou inesperadamente.',
    ],
    'ur': <String>[
      'کھانے کا نام بولیں',
      'کھانے اور اختیاری مقدار کا نام بولیں۔ پہچانے گئے الفاظ میں ترمیم کریں، پھر تلاش کے لیے منظور کریں۔ کچھ بھی خودکار طور پر درج نہیں ہوگا۔',
      'پہچانے گئے الفاظ کا جائزہ لیں',
      'منسوخ کریں',
      'کھانے کی تلاش کے لیے استعمال کریں',
      'صوتی اندراج دستیاب نہیں',
      'ٹھیک ہے',
      'مائیکروفون یا آواز کی شناخت کی اجازت مسترد کر دی گئی۔',
      'اس کارروائی کے لیے مائیکروفون کی اجازت دیں؟',
      'BIL مائیکروفون صرف آپ کے صوتی کھانا اندراج منتخب کرنے کے بعد استعمال کرتا ہے۔ تلاش سے پہلے متن کا جائزہ لے سکتے ہیں اور کچھ بھی خودکار طور پر درج نہیں ہوگا۔',
      'اس کارروائی کے لیے آواز کی شناخت کی اجازت دیں؟',
      'BIL آواز کی شناخت صرف آپ کے صوتی کھانا اندراج منتخب کرنے کے بعد استعمال کرتا ہے۔ تلاش سے پہلے متن کا جائزہ لے سکتے ہیں اور کچھ بھی خودکار طور پر درج نہیں ہوگا۔',
      'مائیکروفون کی رسائی بند ہے۔ صوتی کھانا اندراج کے لیے اسے سسٹم ترتیبات میں فعال کریں؛ دستی اندراج دستیاب رہے گا۔',
      'آواز کی شناخت کی رسائی بند ہے۔ صوتی کھانا اندراج کے لیے اسے سسٹم ترتیبات میں فعال کریں؛ دستی اندراج دستیاب رہے گا۔',
      'سسٹم ترتیبات کھولیں',
      'جاری رکھیں',
      'وقت ختم ہونے سے پہلے کوئی آواز نہیں ملی۔',
      'کھانے کا کوئی قابل استعمال فقرہ پہچانا نہیں گیا۔',
      'اس آلے میں منتخب ایپ زبان کے لیے شناخت کار موجود نہیں۔',
      'اس آلے میں آواز کی شناخت کی کوئی خدمت دستیاب نہیں۔',
      'آواز کی شناخت غیر متوقع طور پر رک گئی۔',
    ],
    'fa': <String>[
      'نام غذا را بگویید',
      'نام غذا و در صورت تمایل مقدار آن را بگویید. متن تشخیص‌داده‌شده را ویرایش و سپس برای جستجو تأیید کنید. چیزی خودکار ثبت نمی‌شود.',
      'بازبینی واژه‌های تشخیص‌داده‌شده',
      'لغو',
      'استفاده برای جستجوی غذا',
      'ورودی صوتی در دسترس نیست',
      'تأیید',
      'مجوز میکروفون یا تشخیص گفتار رد شد.',
      'دسترسی به میکروفون برای این اقدام مجاز باشد؟',
      'BIL فقط پس از انتخاب ورود صوتی غذا از میکروفون استفاده می‌کند. می‌توانید متن را پیش از جستجو بازبینی کنید و چیزی خودکار ثبت نمی‌شود.',
      'تشخیص گفتار برای این اقدام مجاز باشد؟',
      'BIL فقط پس از انتخاب ورود صوتی غذا از تشخیص گفتار استفاده می‌کند. می‌توانید متن را پیش از جستجو بازبینی کنید و چیزی خودکار ثبت نمی‌شود.',
      'دسترسی میکروفون خاموش است. برای ورود صوتی غذا آن را در تنظیمات سیستم فعال کنید؛ ورود دستی همچنان در دسترس است.',
      'دسترسی تشخیص گفتار خاموش است. برای ورود صوتی غذا آن را در تنظیمات سیستم فعال کنید؛ ورود دستی همچنان در دسترس است.',
      'باز کردن تنظیمات سیستم',
      'ادامه',
      'تا پایان زمان هیچ گفتاری تشخیص داده نشد.',
      'عبارت غذایی قابل استفاده‌ای تشخیص داده نشد.',
      'این دستگاه برای زبان انتخابی برنامه تشخیص‌دهنده ندارد.',
      'در این دستگاه سرویس تشخیص گفتار در دسترس نیست.',
      'تشخیص گفتار به‌طور غیرمنتظره متوقف شد.',
    ],
    'hi': <String>[
      'खाने का नाम बोलें',
      'खाने और वैकल्पिक मात्रा को बोलें। पहचाने गए शब्दों को संपादित करें, फिर खोज के लिए स्वीकृत करें। कुछ भी अपने-आप दर्ज नहीं होगा।',
      'पहचाने गए शब्द जाँचें',
      'रद्द करें',
      'खाना खोजने के लिए उपयोग करें',
      'वॉइस इनपुट उपलब्ध नहीं है',
      'ठीक है',
      'माइक्रोफ़ोन या वाक् पहचान की अनुमति अस्वीकार कर दी गई।',
      'इस कार्रवाई के लिए माइक्रोफ़ोन की अनुमति दें?',
      'BIL माइक्रोफ़ोन का उपयोग तभी करता है जब आप वॉइस से खाना दर्ज करना चुनते हैं। खोज से पहले टेक्स्ट जाँच सकते हैं और कुछ भी अपने-आप दर्ज नहीं होगा।',
      'इस कार्रवाई के लिए वाक् पहचान की अनुमति दें?',
      'BIL वाक् पहचान का उपयोग तभी करता है जब आप वॉइस से खाना दर्ज करना चुनते हैं। खोज से पहले टेक्स्ट जाँच सकते हैं और कुछ भी अपने-आप दर्ज नहीं होगा।',
      'माइक्रोफ़ोन पहुँच बंद है। वॉइस से खाना दर्ज करने के लिए इसे सिस्टम सेटिंग में चालू करें; मैन्युअल प्रविष्टि उपलब्ध रहेगी।',
      'वाक् पहचान पहुँच बंद है। वॉइस से खाना दर्ज करने के लिए इसे सिस्टम सेटिंग में चालू करें; मैन्युअल प्रविष्टि उपलब्ध रहेगी।',
      'सिस्टम सेटिंग खोलें',
      'जारी रखें',
      'समय सीमा से पहले कोई वाणी नहीं मिली।',
      'खाने का कोई उपयोगी वाक्यांश नहीं पहचाना गया।',
      'इस डिवाइस में चुनी गई ऐप भाषा का पहचानकर्ता नहीं है।',
      'इस डिवाइस में वाक् पहचान सेवा उपलब्ध नहीं है।',
      'वाक् पहचान अनपेक्षित रूप से रुक गई।',
    ],
    'id': <String>[
      'Ucapkan nama makanan',
      'Ucapkan makanan dan jumlah opsional. Edit kata yang dikenali, lalu setujui untuk pencarian. Tidak ada yang dicatat otomatis.',
      'Tinjau kata yang dikenali',
      'Batal',
      'Gunakan untuk mencari makanan',
      'Input suara tidak tersedia',
      'OK',
      'Izin mikrofon atau pengenalan ucapan ditolak.',
      'Izinkan akses mikrofon untuk tindakan ini?',
      'BIL memakai mikrofon hanya setelah Anda memilih input makanan dengan suara. Anda dapat meninjau teks sebelum mencari dan tidak ada yang dicatat otomatis.',
      'Izinkan pengenalan ucapan untuk tindakan ini?',
      'BIL memakai pengenalan ucapan hanya setelah Anda memilih input makanan dengan suara. Anda dapat meninjau teks sebelum mencari dan tidak ada yang dicatat otomatis.',
      'Akses mikrofon dimatikan. Aktifkan di pengaturan sistem untuk memakai input makanan dengan suara; input manual tetap tersedia.',
      'Akses pengenalan ucapan dimatikan. Aktifkan di pengaturan sistem untuk memakai input makanan dengan suara; input manual tetap tersedia.',
      'Buka pengaturan sistem',
      'Lanjutkan',
      'Tidak ada ucapan yang terdeteksi sebelum batas waktu.',
      'Tidak ada frasa makanan yang dapat digunakan yang dikenali.',
      'Perangkat ini tidak memiliki pengenal untuk bahasa aplikasi yang dipilih.',
      'Perangkat ini tidak memiliki layanan pengenalan ucapan yang tersedia.',
      'Pengenalan ucapan berhenti tiba-tiba.',
    ],
    'ms': <String>[
      'Sebut nama makanan',
      'Sebut makanan dan jumlah pilihan. Edit perkataan yang dikenal pasti, kemudian sahkan untuk carian. Tiada apa-apa direkod secara automatik.',
      'Semak perkataan yang dikenal pasti',
      'Batal',
      'Gunakan untuk carian makanan',
      'Input suara tidak tersedia',
      'OK',
      'Kebenaran mikrofon atau pengecaman pertuturan ditolak.',
      'Benarkan akses mikrofon untuk tindakan ini?',
      'BIL menggunakan mikrofon hanya selepas anda memilih input makanan melalui suara. Anda boleh menyemak teks sebelum carian dan tiada apa-apa direkod secara automatik.',
      'Benarkan pengecaman pertuturan untuk tindakan ini?',
      'BIL menggunakan pengecaman pertuturan hanya selepas anda memilih input makanan melalui suara. Anda boleh menyemak teks sebelum carian dan tiada apa-apa direkod secara automatik.',
      'Akses mikrofon dimatikan. Aktifkannya dalam tetapan sistem untuk input makanan melalui suara; input manual kekal tersedia.',
      'Akses pengecaman pertuturan dimatikan. Aktifkannya dalam tetapan sistem untuk input makanan melalui suara; input manual kekal tersedia.',
      'Buka tetapan sistem',
      'Teruskan',
      'Tiada pertuturan dikesan sebelum had masa.',
      'Tiada frasa makanan yang boleh digunakan dikenal pasti.',
      'Peranti ini tiada pengecam untuk bahasa aplikasi yang dipilih.',
      'Peranti ini tiada perkhidmatan pengecaman pertuturan yang tersedia.',
      'Pengecaman pertuturan terhenti tanpa dijangka.',
    ],
    'ja': <String>[
      '食べ物の名前を話してください',
      '食べ物と必要に応じて量を話してください。認識された言葉を編集し、検索への使用を承認します。自動では記録されません。',
      '認識された言葉を確認',
      'キャンセル',
      '食品検索に使用',
      '音声入力を利用できません',
      'OK',
      'マイクまたは音声認識の権限が拒否されました。',
      'この操作でマイクへのアクセスを許可しますか？',
      'BIL は音声での食品入力を選んだ後にのみマイクを使用します。検索前にテキストを確認でき、自動では記録されません。',
      'この操作で音声認識を許可しますか？',
      'BIL は音声での食品入力を選んだ後にのみ音声認識を使用します。検索前にテキストを確認でき、自動では記録されません。',
      'マイクへのアクセスがオフです。音声で食品を入力するにはシステム設定で有効にしてください。手動入力は引き続き利用できます。',
      '音声認識へのアクセスがオフです。音声で食品を入力するにはシステム設定で有効にしてください。手動入力は引き続き利用できます。',
      'システム設定を開く',
      '続ける',
      '制限時間内に音声が検出されませんでした。',
      '使用できる食品の語句を認識できませんでした。',
      'この端末には選択したアプリ言語の認識機能がありません。',
      'この端末で利用できる音声認識サービスがありません。',
      '音声認識が予期せず停止しました。',
    ],
    'ko': <String>[
      '음식 이름을 말하세요',
      '음식과 선택적으로 양을 말하세요. 인식된 문구를 수정한 뒤 검색에 사용하도록 승인하세요. 자동으로 기록되지 않습니다.',
      '인식된 문구 검토',
      '취소',
      '음식 검색에 사용',
      '음성 입력을 사용할 수 없음',
      '확인',
      '마이크 또는 음성 인식 권한이 거부되었습니다.',
      '이 작업에 마이크 접근을 허용할까요?',
      'BIL은 음성 음식 입력을 선택한 후에만 마이크를 사용합니다. 검색 전에 텍스트를 검토할 수 있으며 자동으로 기록되지 않습니다.',
      '이 작업에 음성 인식을 허용할까요?',
      'BIL은 음성 음식 입력을 선택한 후에만 음성 인식을 사용합니다. 검색 전에 텍스트를 검토할 수 있으며 자동으로 기록되지 않습니다.',
      '마이크 접근이 꺼져 있습니다. 음성 음식 입력을 사용하려면 시스템 설정에서 켜세요. 수동 입력은 계속 사용할 수 있습니다.',
      '음성 인식 접근이 꺼져 있습니다. 음성 음식 입력을 사용하려면 시스템 설정에서 켜세요. 수동 입력은 계속 사용할 수 있습니다.',
      '시스템 설정 열기',
      '계속',
      '제한 시간 전에 음성이 감지되지 않았습니다.',
      '사용할 수 있는 음식 문구가 인식되지 않았습니다.',
      '이 기기에는 선택한 앱 언어용 인식기가 없습니다.',
      '이 기기에서 사용할 수 있는 음성 인식 서비스가 없습니다.',
      '음성 인식이 예기치 않게 중단되었습니다.',
    ],
    'zh-Hans': <String>[
      '说出食物名称',
      '说出食物以及可选的份量。编辑识别出的文字，然后确认用于搜索。不会自动记录任何内容。',
      '检查识别出的文字',
      '取消',
      '用于搜索食物',
      '语音输入不可用',
      '确定',
      '麦克风或语音识别权限已被拒绝。',
      '允许此操作访问麦克风吗？',
      'BIL 仅在你选择语音输入食物后使用麦克风。你可以在搜索前检查文字，且不会自动记录任何内容。',
      '允许此操作使用语音识别吗？',
      'BIL 仅在你选择语音输入食物后使用语音识别。你可以在搜索前检查文字，且不会自动记录任何内容。',
      '麦克风访问已关闭。请在系统设置中启用，以使用语音输入食物；手动输入仍可使用。',
      '语音识别访问已关闭。请在系统设置中启用，以使用语音输入食物；手动输入仍可使用。',
      '打开系统设置',
      '继续',
      '在时间限制内未检测到语音。',
      '未识别出可用的食物短语。',
      '此设备没有所选应用语言的识别器。',
      '此设备没有可用的语音识别服务。',
      '语音识别意外停止。',
    ],
    'zh-Hant': <String>[
      '說出食物名稱',
      '說出食物以及選填的份量。編輯辨識出的文字，然後確認用於搜尋。不會自動記錄任何內容。',
      '檢查辨識出的文字',
      '取消',
      '用於搜尋食物',
      '語音輸入無法使用',
      '確定',
      '麥克風或語音辨識權限已被拒絕。',
      '允許此操作取用麥克風嗎？',
      'BIL 僅在你選擇語音輸入食物後使用麥克風。你可以在搜尋前檢查文字，且不會自動記錄任何內容。',
      '允許此操作使用語音辨識嗎？',
      'BIL 僅在你選擇語音輸入食物後使用語音辨識。你可以在搜尋前檢查文字，且不會自動記錄任何內容。',
      '麥克風取用已關閉。請在系統設定中啟用，以使用語音輸入食物；手動輸入仍可使用。',
      '語音辨識取用已關閉。請在系統設定中啟用，以使用語音輸入食物；手動輸入仍可使用。',
      '開啟系統設定',
      '繼續',
      '在時間限制內未偵測到語音。',
      '未辨識出可用的食物詞句。',
      '此裝置沒有所選應用程式語言的辨識器。',
      '此裝置沒有可用的語音辨識服務。',
      '語音辨識意外停止。',
    ],
    'ru': <String>[
      'Произнесите название продукта',
      'Назовите продукт и при желании количество. Отредактируйте распознанный текст и подтвердите его для поиска. Ничего не записывается автоматически.',
      'Проверьте распознанный текст',
      'Отмена',
      'Использовать для поиска продуктов',
      'Голосовой ввод недоступен',
      'ОК',
      'Разрешение на микрофон или распознавание речи отклонено.',
      'Разрешить доступ к микрофону для этого действия?',
      'BIL использует микрофон только после выбора голосового ввода еды. Перед поиском можно проверить текст; ничего не записывается автоматически.',
      'Разрешить распознавание речи для этого действия?',
      'BIL использует распознавание речи только после выбора голосового ввода еды. Перед поиском можно проверить текст; ничего не записывается автоматически.',
      'Доступ к микрофону отключен. Включите его в настройках системы для голосового ввода еды; ручной ввод остается доступен.',
      'Доступ к распознаванию речи отключен. Включите его в настройках системы для голосового ввода еды; ручной ввод остается доступен.',
      'Открыть настройки системы',
      'Продолжить',
      'Речь не обнаружена до истечения времени.',
      'Не удалось распознать подходящую фразу о продукте.',
      'На устройстве нет распознавания для выбранного языка приложения.',
      'На устройстве нет доступной службы распознавания речи.',
      'Распознавание речи неожиданно остановилось.',
    ],
    'bn': <String>[
      'খাবারের নাম বলুন',
      'খাবার এবং চাইলে পরিমাণ বলুন। শনাক্ত শব্দ সম্পাদনা করে অনুসন্ধানের জন্য অনুমোদন করুন। কিছুই স্বয়ংক্রিয়ভাবে নথিভুক্ত হবে না।',
      'শনাক্ত শব্দ পর্যালোচনা করুন',
      'বাতিল',
      'খাবার অনুসন্ধানে ব্যবহার করুন',
      'ভয়েস ইনপুট পাওয়া যাচ্ছে না',
      'ঠিক আছে',
      'মাইক্রোফোন বা কথন শনাক্তকরণের অনুমতি প্রত্যাখ্যান করা হয়েছে।',
      'এই কাজের জন্য মাইক্রোফোন ব্যবহারের অনুমতি দেবেন?',
      'আপনি ভয়েসে খাবার লেখা বেছে নেওয়ার পরেই BIL মাইক্রোফোন ব্যবহার করে। অনুসন্ধানের আগে লেখা পর্যালোচনা করতে পারবেন এবং কিছুই স্বয়ংক্রিয়ভাবে নথিভুক্ত হবে না।',
      'এই কাজের জন্য কথন শনাক্তকরণের অনুমতি দেবেন?',
      'আপনি ভয়েসে খাবার লেখা বেছে নেওয়ার পরেই BIL কথন শনাক্তকরণ ব্যবহার করে। অনুসন্ধানের আগে লেখা পর্যালোচনা করতে পারবেন এবং কিছুই স্বয়ংক্রিয়ভাবে নথিভুক্ত হবে না।',
      'মাইক্রোফোনের অ্যাক্সেস বন্ধ। ভয়েসে খাবার লেখার জন্য সিস্টেম সেটিংসে এটি চালু করুন; হাতে লেখা এখনও পাওয়া যাবে।',
      'কথন শনাক্তকরণের অ্যাক্সেস বন্ধ। ভয়েসে খাবার লেখার জন্য সিস্টেম সেটিংসে এটি চালু করুন; হাতে লেখা এখনও পাওয়া যাবে।',
      'সিস্টেম সেটিংস খুলুন',
      'চালিয়ে যান',
      'সময়সীমার আগে কোনো কথা শনাক্ত হয়নি।',
      'ব্যবহারযোগ্য কোনো খাবারের বাক্যাংশ শনাক্ত হয়নি।',
      'এই ডিভাইসে নির্বাচিত অ্যাপ ভাষার শনাক্তকারী নেই।',
      'এই ডিভাইসে কোনো কথন শনাক্তকরণ পরিষেবা পাওয়া যাচ্ছে না।',
      'কথন শনাক্তকরণ অপ্রত্যাশিতভাবে থেমে গেছে।',
    ],
    'vi': <String>[
      'Nói tên thực phẩm',
      'Nói một thực phẩm và lượng nếu muốn. Chỉnh sửa từ đã nhận dạng rồi xác nhận để tìm kiếm. Không có gì được tự động ghi lại.',
      'Xem lại từ đã nhận dạng',
      'Hủy',
      'Dùng để tìm thực phẩm',
      'Không thể nhập bằng giọng nói',
      'OK',
      'Quyền dùng micrô hoặc nhận dạng giọng nói đã bị từ chối.',
      'Cho phép truy cập micrô cho thao tác này?',
      'BIL chỉ dùng micrô sau khi bạn chọn nhập thực phẩm bằng giọng nói. Bạn có thể xem lại văn bản trước khi tìm và không có gì được tự động ghi lại.',
      'Cho phép nhận dạng giọng nói cho thao tác này?',
      'BIL chỉ dùng nhận dạng giọng nói sau khi bạn chọn nhập thực phẩm bằng giọng nói. Bạn có thể xem lại văn bản trước khi tìm và không có gì được tự động ghi lại.',
      'Quyền truy cập micrô đang tắt. Hãy bật trong cài đặt hệ thống để nhập thực phẩm bằng giọng nói; nhập thủ công vẫn dùng được.',
      'Quyền nhận dạng giọng nói đang tắt. Hãy bật trong cài đặt hệ thống để nhập thực phẩm bằng giọng nói; nhập thủ công vẫn dùng được.',
      'Mở cài đặt hệ thống',
      'Tiếp tục',
      'Không phát hiện giọng nói trước khi hết thời gian.',
      'Không nhận dạng được cụm từ thực phẩm có thể dùng.',
      'Thiết bị này không có bộ nhận dạng cho ngôn ngữ ứng dụng đã chọn.',
      'Thiết bị này không có dịch vụ nhận dạng giọng nói khả dụng.',
      'Nhận dạng giọng nói dừng đột ngột.',
    ],
    'th': <String>[
      'พูดชื่ออาหาร',
      'พูดชื่ออาหารและปริมาณถ้าต้องการ แก้ไขคำที่ระบบรู้จำ แล้วอนุมัติเพื่อค้นหา จะไม่มีการบันทึกอัตโนมัติ',
      'ตรวจสอบคำที่รู้จำ',
      'ยกเลิก',
      'ใช้ค้นหาอาหาร',
      'ไม่พร้อมใช้งานการป้อนข้อมูลด้วยเสียง',
      'ตกลง',
      'สิทธิ์ไมโครโฟนหรือการรู้จำเสียงถูกปฏิเสธ',
      'อนุญาตการเข้าถึงไมโครโฟนสำหรับการทำงานนี้หรือไม่',
      'BIL ใช้ไมโครโฟนหลังจากคุณเลือกป้อนอาหารด้วยเสียงเท่านั้น คุณตรวจสอบข้อความก่อนค้นหาได้ และจะไม่มีการบันทึกอัตโนมัติ',
      'อนุญาตการรู้จำเสียงสำหรับการทำงานนี้หรือไม่',
      'BIL ใช้การรู้จำเสียงหลังจากคุณเลือกป้อนอาหารด้วยเสียงเท่านั้น คุณตรวจสอบข้อความก่อนค้นหาได้ และจะไม่มีการบันทึกอัตโนมัติ',
      'การเข้าถึงไมโครโฟนปิดอยู่ เปิดในการตั้งค่าระบบเพื่อป้อนอาหารด้วยเสียง การป้อนด้วยตนเองยังใช้ได้',
      'การเข้าถึงการรู้จำเสียงปิดอยู่ เปิดในการตั้งค่าระบบเพื่อป้อนอาหารด้วยเสียง การป้อนด้วยตนเองยังใช้ได้',
      'เปิดการตั้งค่าระบบ',
      'ดำเนินการต่อ',
      'ไม่พบเสียงพูดก่อนหมดเวลา',
      'ไม่รู้จำวลีอาหารที่ใช้งานได้',
      'อุปกรณ์นี้ไม่มีตัวรู้จำสำหรับภาษาของแอปที่เลือก',
      'อุปกรณ์นี้ไม่มีบริการรู้จำเสียงที่พร้อมใช้งาน',
      'การรู้จำเสียงหยุดลงโดยไม่คาดคิด',
    ],
    'pl': <String>[
      'Powiedz nazwę produktu',
      'Powiedz nazwę produktu i opcjonalnie ilość. Edytuj rozpoznany tekst i zatwierdź go do wyszukania. Nic nie zostanie zapisane automatycznie.',
      'Sprawdź rozpoznany tekst',
      'Anuluj',
      'Użyj do wyszukiwania produktów',
      'Wprowadzanie głosowe jest niedostępne',
      'OK',
      'Odmówiono dostępu do mikrofonu lub rozpoznawania mowy.',
      'Zezwolić na dostęp do mikrofonu dla tej czynności?',
      'BIL używa mikrofonu dopiero po wybraniu głosowego dodawania jedzenia. Przed wyszukaniem możesz sprawdzić tekst; nic nie zostanie zapisane automatycznie.',
      'Zezwolić na rozpoznawanie mowy dla tej czynności?',
      'BIL używa rozpoznawania mowy dopiero po wybraniu głosowego dodawania jedzenia. Przed wyszukaniem możesz sprawdzić tekst; nic nie zostanie zapisane automatycznie.',
      'Dostęp do mikrofonu jest wyłączony. Włącz go w ustawieniach systemu, aby dodawać jedzenie głosem; ręczne wprowadzanie pozostaje dostępne.',
      'Dostęp do rozpoznawania mowy jest wyłączony. Włącz go w ustawieniach systemu, aby dodawać jedzenie głosem; ręczne wprowadzanie pozostaje dostępne.',
      'Otwórz ustawienia systemowe',
      'Kontynuuj',
      'Nie wykryto mowy przed upływem limitu czasu.',
      'Nie rozpoznano użytecznej frazy dotyczącej produktu.',
      'To urządzenie nie ma modułu dla wybranego języka aplikacji.',
      'Na tym urządzeniu nie ma dostępnej usługi rozpoznawania mowy.',
      'Rozpoznawanie mowy nieoczekiwanie się zatrzymało.',
    ],
    'nl': <String>[
      'Zeg de naam van het voedingsmiddel',
      'Noem een voedingsmiddel en eventueel een hoeveelheid. Bewerk de herkende woorden en keur ze goed voor zoeken. Er wordt niets automatisch vastgelegd.',
      'Herkende woorden controleren',
      'Annuleren',
      'Gebruiken om voeding te zoeken',
      'Spraakinvoer niet beschikbaar',
      'OK',
      'Toegang tot microfoon of spraakherkenning is geweigerd.',
      'Microfoontoegang toestaan voor deze actie?',
      'BIL gebruikt de microfoon pas nadat je spraakinvoer voor voeding kiest. Je kunt de tekst vóór het zoeken controleren; niets wordt automatisch vastgelegd.',
      'Spraakherkenning toestaan voor deze actie?',
      'BIL gebruikt spraakherkenning pas nadat je spraakinvoer voor voeding kiest. Je kunt de tekst vóór het zoeken controleren; niets wordt automatisch vastgelegd.',
      'Microfoontoegang staat uit. Schakel deze in via de systeeminstellingen voor spraakinvoer; handmatige invoer blijft beschikbaar.',
      'Spraakherkenning staat uit. Schakel deze in via de systeeminstellingen voor spraakinvoer; handmatige invoer blijft beschikbaar.',
      'Systeeminstellingen openen',
      'Doorgaan',
      'Er is geen spraak gedetecteerd vóór de tijdslimiet.',
      'Er is geen bruikbare voedingszin herkend.',
      'Dit apparaat heeft geen herkenning voor de gekozen app-taal.',
      'Dit apparaat heeft geen beschikbare spraakherkenningsdienst.',
      'Spraakherkenning is onverwacht gestopt.',
    ],
    'uk': <String>[
      'Назвіть продукт',
      'Назвіть продукт і за бажанням кількість. Відредагуйте розпізнаний текст і підтвердьте його для пошуку. Нічого не записується автоматично.',
      'Перевірте розпізнаний текст',
      'Скасувати',
      'Використати для пошуку продуктів',
      'Голосове введення недоступне',
      'OK',
      'Дозвіл на мікрофон або розпізнавання мовлення відхилено.',
      'Дозволити доступ до мікрофона для цієї дії?',
      'BIL використовує мікрофон лише після вибору голосового введення їжі. Перед пошуком можна перевірити текст; нічого не записується автоматично.',
      'Дозволити розпізнавання мовлення для цієї дії?',
      'BIL використовує розпізнавання мовлення лише після вибору голосового введення їжі. Перед пошуком можна перевірити текст; нічого не записується автоматично.',
      'Доступ до мікрофона вимкнено. Увімкніть його в системних налаштуваннях для голосового введення їжі; ручне введення залишається доступним.',
      'Доступ до розпізнавання мовлення вимкнено. Увімкніть його в системних налаштуваннях для голосового введення їжі; ручне введення залишається доступним.',
      'Відкрити системні налаштування',
      'Продовжити',
      'До завершення часу мовлення не виявлено.',
      'Не розпізнано придатної фрази про продукт.',
      'На пристрої немає розпізнавання для вибраної мови застосунку.',
      'На пристрої немає доступної служби розпізнавання мовлення.',
      'Розпізнавання мовлення несподівано зупинилося.',
    ],
  };

  static String resolve(MealVoiceCopyKey key, String localeTag) {
    final tag = resolvedLocaleTag(localeTag);
    return _rows[tag]![key.index];
  }

  /// Returns the exact production variant when supplied. Bare Portuguese and
  /// Chinese use explicit defaults without erasing exact regional/script tags.
  static String resolvedLocaleTag(String rawTag) {
    final normalized = rawTag.trim().replaceAll('_', '-').toLowerCase();
    for (final tag in productionLocaleTags) {
      if (tag.toLowerCase() == normalized) return tag;
    }
    final language = normalized.split('-').first;
    if (language == 'pt') return 'pt-BR';
    if (language == 'zh') return 'zh-Hans';
    final matches = productionLocaleTags
        .where((tag) => tag.toLowerCase().split('-').first == language)
        .toList(growable: false);
    return matches.length == 1 ? matches.single : 'en';
  }

  static bool get balanced {
    final keys = _rows.keys.toSet();
    return keys.containsAll(productionLocaleTags) &&
        productionLocaleTags.containsAll(keys) &&
        _rows.values.every(
          (row) =>
              row.length == MealVoiceCopyKey.values.length &&
              row.every((value) => value.trim().isNotEmpty),
        );
  }
}
