part of 'runtime_copy_coach_controls.dart';

const _coachControlsRows0 = <String, List<String>>{
  "ar": [
    "تم تحديث مظهر التطبيق.",
    "تم تحديث لغة التطبيق.",
    "اسأل قبل الكتابة",
    "يستخدم BIL خدمة Google Gemini، وهي خدمة ذكاء اصطناعي تابعة لجهة خارجية وتديرها Google، فقط لإنشاء الإجابة التي تطلبها.",
    "محادثة",
    "يُحفظ سجل المحادثات محليًا على هذا الجهاز.",
    "المحادثات",
    "المحادثة الحالية",
    "إنهاء المكالمة",
    "صورة الطعام",
    "احفظ هذه المحادثة في السجل وابدأ محادثة فارغة.",
    "محادثة جديدة",
    "لا توجد محادثات سابقة بعد.",
    "فقط السياق الذي تختاره",
    "لا يتم إرسال صوت الميكروفون الخام",
    "قراءة فقط",
    "جارٍ الإرسال",
    "تم تسجيل الخروج بنجاح.",
    "تم إلغاء الإجراء المعلّق. لم يتغير شيء.",
    "تم التراجع عن الإجراء السابق.",
    "لا يوجد إجراء حديث قابل للتراجع.",
    "يحتاج هذا الإجراء إلى إذن كتابة. غيّر إعداد الدرع للمتابعة.",
    "يبقى التعرف على الصوت منفصلًا عن موافقة الذكاء الاصطناعي عن بُعد.",
    "الكتابة مسموحة",
    "يمكنك الرفض ومتابعة استخدام ميزات BIL المحلية، أو سحب هذه الموافقة لاحقًا من إعدادات AI Coach.",
    "التحكم يبقى بيدك",
    "سؤالك؛ وما تختاره من الوزن والأهداف والقياسات؛ والوجبات والتغذية والماء والتفضيلات؛ والنشاط والتدريب؛ والنوم والعادات؛ إضافة إلى ما يصل إلى آخر 12 رسالة.",
    "لم يُنفذ الإجراء. بقيت بياناتك دون تغيير؛ راجع القيمة وحاول مجددًا.",
  ],
  "fr": [
    "L’apparence de l’application a été mise à jour.",
    "La langue de l’application a été mise à jour.",
    "Demander avant toute écriture",
    "BIL utilise Google Gemini, un service d’IA tiers exploité par Google, uniquement pour générer la réponse que vous demandez.",
    "Discussion",
    "L’historique des conversations est stocké localement sur cet appareil.",
    "Discussions",
    "Conversation actuelle",
    "Terminer l’appel en direct",
    "Photo de nourriture",
    "Conserver cette conversation dans l’historique et en commencer une vide.",
    "Nouvelle conversation",
    "Aucune conversation précédente pour le moment.",
    "Uniquement le contexte que vous choisissez",
    "Le son brut du microphone n’est pas envoyé",
    "Lecture seule",
    "Envoi en cours",
    "Déconnexion réussie.",
    "L’action en attente a été annulée. Rien n’a été modifié.",
    "L’action précédente a été annulée.",
    "Aucune action récente ne peut être annulée.",
    "Cette action nécessite une autorisation d’écriture. Modifiez le réglage du bouclier pour continuer.",
    "La reconnaissance vocale reste distincte de ce consentement à l’IA distante.",
    "Écriture autorisée",
    "Vous pouvez refuser et continuer à utiliser les fonctions locales de BIL, ou retirer ce consentement plus tard dans les paramètres du coach IA.",
    "Vous gardez le contrôle",
    "Votre question ; le poids, les objectifs et les mesures sélectionnés ; les repas, la nutrition, l’eau et les préférences ; l’activité et l’entraînement ; le sommeil et les habitudes ; ainsi que les 12 derniers messages de conversation au maximum.",
    "L’action n’a pas été effectuée. Vos données sont restées inchangées ; vérifiez la valeur et réessayez.",
  ],
  "es": [
    "Se actualizó la apariencia de la aplicación.",
    "Se actualizó el idioma de la aplicación.",
    "Preguntar antes de escribir",
    "BIL usa Google Gemini, un servicio de IA de terceros operado por Google, solo para generar la respuesta que solicitas.",
    "Conversación",
    "El historial de conversaciones se guarda localmente en este dispositivo.",
    "Conversaciones",
    "Conversación actual",
    "Finalizar llamada en directo",
    "Foto de comida",
    "Guardar esta conversación en el historial y empezar una vacía.",
    "Nueva conversación",
    "Aún no hay conversaciones anteriores.",
    "Solo el contexto que elijas",
    "No se envía el audio sin procesar del micrófono",
    "Solo lectura",
    "Enviando",
    "Se cerró la sesión correctamente.",
    "Se canceló la acción pendiente. No se cambió nada.",
    "Se deshizo la acción anterior.",
    "No hay ninguna acción reciente que se pueda deshacer.",
    "Esta acción necesita permiso de escritura. Cambia el ajuste del escudo para continuar.",
    "El reconocimiento de voz sigue siendo independiente de este consentimiento para la IA remota.",
    "Escritura permitida",
    "Puedes rechazarlo y seguir usando las funciones locales de BIL, o retirar este consentimiento más tarde en los ajustes del entrenador de IA.",
    "Tú mantienes el control",
    "Tu pregunta; el peso, los objetivos y las medidas seleccionados; comidas, nutrición, agua y preferencias; actividad y entrenamiento; sueño y hábitos; además de hasta 12 mensajes recientes de la conversación.",
    "La acción no se completó. Tus datos no cambiaron; revisa el valor e inténtalo de nuevo.",
  ],
  "tr": [
    "Uygulama görünümü güncellendi.",
    "Uygulama dili güncellendi.",
    "Yazmadan önce sor",
    "BIL, Google tarafından işletilen üçüncü taraf yapay zekâ hizmeti Google Gemini’yi yalnızca istediğiniz yanıtı oluşturmak için kullanır.",
    "Sohbet",
    "Sohbet geçmişi bu cihazda yerel olarak saklanır.",
    "Sohbetler",
    "Mevcut sohbet",
    "Canlı aramayı sonlandır",
    "Yemek fotoğrafı",
    "Bu sohbeti geçmişte tut ve boş bir sohbet başlat.",
    "Yeni sohbet",
    "Henüz önceki sohbet yok.",
    "Yalnızca seçtiğiniz bağlam",
    "Ham mikrofon sesi gönderilmez",
    "Yalnızca okuma",
    "Gönderiliyor",
    "Başarıyla çıkış yapıldı.",
    "Bekleyen işlem iptal edildi. Hiçbir şey değiştirilmedi.",
    "Önceki işlem geri alındı.",
    "Geri alınabilecek yakın tarihli bir işlem yok.",
    "Bu işlem yazma izni gerektiriyor. Devam etmek için kalkan ayarını değiştirin.",
    "Ses tanıma, bu uzak yapay zekâ izninden ayrı kalır.",
    "Yazmaya izin veriliyor",
    "Reddedip BIL’in yerel özelliklerini kullanmaya devam edebilir veya bu izni daha sonra yapay zekâ koçu ayarlarından geri çekebilirsiniz.",
    "Kontrol sizde kalır",
    "Sorunuz; seçilen kilo, hedefler ve ölçümler; öğünler, beslenme, su ve tercihler; aktivite ve antrenman; uyku ve alışkanlıklar; ayrıca en fazla son 12 sohbet mesajı.",
    "İşlem tamamlanmadı. Verileriniz değişmedi; değeri kontrol edip tekrar deneyin.",
  ],
  "de": [
    "Das Erscheinungsbild der App wurde aktualisiert.",
    "Die App-Sprache wurde aktualisiert.",
    "Vor dem Schreiben fragen",
    "BIL nutzt Google Gemini, einen von Google betriebenen KI-Dienst eines Drittanbieters, ausschließlich zum Erstellen der von dir angeforderten Antwort.",
    "Gespräch",
    "Der Gesprächsverlauf wird lokal auf diesem Gerät gespeichert.",
    "Gespräche",
    "Aktuelles Gespräch",
    "Live-Gespräch beenden",
    "Essensfoto",
    "Dieses Gespräch im Verlauf behalten und ein leeres beginnen.",
    "Neues Gespräch",
    "Noch keine früheren Gespräche.",
    "Nur der von dir ausgewählte Kontext",
    "Unverarbeitete Mikrofonaufnahmen werden nicht gesendet",
    "Nur lesen",
    "Wird gesendet",
    "Erfolgreich abgemeldet.",
    "Die ausstehende Aktion wurde abgebrochen. Es wurde nichts geändert.",
    "Die vorherige Aktion wurde rückgängig gemacht.",
    "Es gibt keine kürzlich ausgeführte Aktion, die rückgängig gemacht werden kann.",
    "Diese Aktion benötigt eine Schreibberechtigung. Ändere zum Fortfahren die Einstellung am Schildsymbol.",
    "Die Spracherkennung bleibt von dieser Einwilligung zur externen KI getrennt.",
    "Schreiben erlaubt",
    "Du kannst ablehnen und die lokalen BIL-Funktionen weiterverwenden oder diese Einwilligung später in den Einstellungen des KI-Coachs widerrufen.",
    "Du behältst die Kontrolle",
    "Deine Frage; ausgewählte Angaben zu Gewicht, Zielen und Messwerten; Mahlzeiten, Ernährung, Wasser und Vorlieben; Aktivität und Training; Schlaf und Gewohnheiten; sowie bis zu 12 der letzten Gesprächsbeiträge.",
    "Die Aktion wurde nicht abgeschlossen. Deine Daten blieben unverändert; prüfe den Wert und versuche es erneut.",
  ],
  "it": [
    "L’aspetto dell’app è stato aggiornato.",
    "La lingua dell’app è stata aggiornata.",
    "Chiedi prima di scrivere",
    "BIL usa Google Gemini, un servizio di IA di terze parti gestito da Google, solo per generare la risposta che richiedi.",
    "Conversazione",
    "La cronologia delle conversazioni è conservata localmente su questo dispositivo.",
    "Conversazioni",
    "Conversazione attuale",
    "Termina chiamata in diretta",
    "Foto del cibo",
    "Conserva questa conversazione nella cronologia e iniziane una vuota.",
    "Nuova conversazione",
    "Non ci sono ancora conversazioni precedenti.",
    "Solo il contesto che scegli",
    "L’audio grezzo del microfono non viene inviato",
    "Sola lettura",
    "Invio in corso",
    "Disconnessione riuscita.",
    "L’azione in attesa è stata annullata. Non è stato modificato nulla.",
    "L’azione precedente è stata annullata.",
    "Non ci sono azioni recenti che si possano annullare.",
    "Questa azione richiede il permesso di scrittura. Modifica l’impostazione dello scudo per continuare.",
    "Il riconoscimento vocale resta separato da questo consenso all’IA remota.",
    "Scrittura consentita",
    "Puoi rifiutare e continuare a usare le funzioni locali di BIL, oppure ritirare questo consenso in seguito nelle impostazioni del coach IA.",
    "Mantieni il controllo",
    "La tua domanda; peso, obiettivi e misurazioni selezionati; pasti, nutrizione, acqua e preferenze; attività e allenamento; sonno e abitudini; più un massimo di 12 messaggi recenti della conversazione.",
    "L’azione non è stata completata. I tuoi dati sono rimasti invariati; controlla il valore e riprova.",
  ],
};
