part of 'runtime_copy_community_reference.dart';

const _communityReferenceWestRows = <String, List<String>>{
  "fr": <String>[
    "Ajouter un hashtag",
    "Ajoutez quelque chose avant d’enregistrer un brouillon.",
    "Ajoutez jusqu’à 10 hashtags recherchables.",
    "Apprécié",
    "Moments approuvés",
    "Profil Communauté BIL",
    "BIL reviendra à la couverture de Communauté avec l’identité visuelle de la marque.",
    "Insignes",
    "Accréditation",
    "Certification révoquée",
    "Créateur certifié",
    "Choisissez une image JPEG, PNG ou WebP valide de 5 Mo maximum.",
    "Collaboration acceptée.",
    "Collaboration refusée.",
    "Invitation à collaborer",
    "Invitation à collaborer acceptée",
    "Collaboration — facultatif",
    "Commentaires reçus",
    "Badges de la Communauté",
    "Bâtisseur de communauté",
    "Accueil de la Communauté",
    "Créateur de liens",
    "Contributeur",
    "Lanceur de conversation",
    "Impossible de supprimer ce brouillon.",
    "Impossible d’ouvrir le partage pour le moment.",
    "Impossible d’ouvrir ce brouillon. Réessayez.",
    "Impossible de supprimer la couverture du profil.",
    "Impossible d’enregistrer ce brouillon. Rien n’a été publié.",
    "Impossible de rechercher des collaborateurs pour le moment.",
    "Impossible de mettre à jour l’état du suivi.",
    "Impossible de mettre à jour la couverture du profil.",
    "Impossible de mettre à jour cette collaboration. Réessayez.",
    "Centre des créateurs",
    "Récompenses des créateurs",
    "Outils du créateur",
    "Refusée",
    "Supprimer le brouillon",
    "Brouillon enregistré en toute sécurité.",
    "Brouillons",
    "Premier moment",
    "Vous suit",
    "Donnez un titre clair à ce moment",
    "Hashtags — facultatif",
    "Invitez jusqu’à 3 membres de la Communauté. Les invitations ne sont envoyées qu’après validation humaine, et un collaborateur n’apparaît publiquement qu’après avoir accepté.",
    "J’aime reçus",
    "Verrouillé",
    "Instants",
    "Les moments sont privés sur ce profil.",
    "Nouveaux abonnés",
    "Aucune certification de créateur BIL n’a été accordée à ce profil.",
    "Aucun avis approuvé pour le moment.",
    "Aucun brouillon enregistré pour le moment.",
    "Aucun moment visible pour le moment.",
    "Non certifié",
    "Ouvrir",
    "Brouillon photo",
    "Couverture du profil mise à jour.",
    "Publié",
    "Parrainages qualifiés",
    "Supprimer la couverture du profil ?",
    "Avis",
    "Les avis sont privés sur ce profil.",
    "Enregistrer le brouillon",
    "Enregistrez les publications de Communauté inachevées et reprenez-les plus tard.",
    "Brouillon de Communauté enregistré",
    "Brouillon enregistré",
    "Rechercher par nom ou @identifiant",
    "Rechercher des collaborateurs",
    "Partager le profil",
    "Centre des tâches",
    "La transcription vocale dépasserait la limite de 1 200 caractères de la publication.",
    "Ce Cercle est indisponible pour le moment.",
    "Cette certification est vérifiée par l’autorité serveur de BIL.",
    "Ce profil ne possède actuellement aucune certification active.",
    "Ce sujet est indisponible pour le moment.",
    "Titre",
    "Brouillon sans titre",
    "Mettre à jour le brouillon",
    "Mises à jour",
    "Utilisez un seul hashtag sans espaces, jusqu’à 40 caractères.",
    "Avec",
    "Vous pouvez ajouter jusqu’à 10 hashtags.",
    "{actor} a accepté votre invitation à collaborer",
    "{actor} vous a invité à collaborer sur une publication",
    "Niveau de Communauté configuré le plus élevé atteint",
    "{xp} XP · Suivant : niv. {level} à {target} XP",
    "Progression vers le niv. {level} · objectif {target} XP",
  ],
  "es": <String>[
    "Añadir hashtag",
    "Añade algo antes de guardar un borrador.",
    "Añade hasta 10 hashtags que se puedan buscar.",
    "Valorado",
    "Momentos aprobados",
    "Perfil de la Comunidad BIL",
    "BIL volverá a la portada de Comunidad con la identidad de la marca.",
    "Insignias",
    "Certificación",
    "Certificación revocada",
    "Creador certificado",
    "Elige una imagen JPEG, PNG o WebP válida de hasta 5 MB.",
    "Colaboración aceptada.",
    "Colaboración rechazada.",
    "Invitación a colaborar",
    "Invitación a colaborar aceptada",
    "Colaboración — opcional",
    "Comentarios recibidos",
    "Insignias de la Comunidad",
    "Constructor de comunidad",
    "Inicio de la Comunidad",
    "Conector",
    "Colaborador",
    "Iniciador de conversaciones",
    "No se pudo eliminar este borrador.",
    "No se puede abrir la opción de compartir ahora.",
    "No se pudo abrir este borrador. Inténtalo de nuevo.",
    "No se pudo eliminar la portada del perfil.",
    "No se pudo guardar este borrador. No se publicó nada.",
    "No se pueden buscar colaboradores ahora.",
    "No se pudo actualizar el estado de seguimiento.",
    "No se pudo actualizar la portada del perfil.",
    "No se pudo actualizar esta colaboración. Inténtalo de nuevo.",
    "Centro de creadores",
    "Recompensas para creadores",
    "Herramientas del creador",
    "Rechazada",
    "Eliminar borrador",
    "Borrador guardado de forma segura.",
    "Borradores",
    "Primer momento",
    "Te sigue",
    "Ponle un título claro a este momento",
    "Hashtags — opcional",
    "Invita a hasta 3 miembros de la Comunidad. Las invitaciones se envían solo después de la aprobación humana, y un colaborador solo aparece públicamente después de aceptar.",
    "Me gusta recibidos",
    "Bloqueado",
    "Momentos",
    "Los momentos son privados en este perfil.",
    "Nuevos seguidores",
    "Este perfil no ha recibido ninguna certificación de creador de BIL.",
    "Aún no hay reseñas aprobadas.",
    "Aún no hay borradores guardados.",
    "Aún no hay momentos visibles.",
    "Sin certificación",
    "Abrir",
    "Borrador con fotos",
    "Portada del perfil actualizada.",
    "Publicado",
    "Referidos cualificados",
    "¿Eliminar la portada del perfil?",
    "Reseñas",
    "Las reseñas son privadas en este perfil.",
    "Guardar borrador",
    "Guarda publicaciones de Comunidad sin terminar y continúa más tarde.",
    "Borrador de Comunidad guardado",
    "Borrador guardado",
    "Buscar por nombre o @usuario",
    "Buscar colaboradores",
    "Compartir perfil",
    "Centro de tareas",
    "La transcripción de voz superaría el límite de 1200 caracteres de la publicación.",
    "Este Círculo no está disponible ahora.",
    "Esta certificación está verificada por la autoridad del servidor de BIL.",
    "Este perfil no tiene actualmente una certificación activa.",
    "Este tema no está disponible ahora.",
    "Título",
    "Borrador sin título",
    "Actualizar borrador",
    "Actualizaciones",
    "Usa un solo hashtag sin espacios, de hasta 40 caracteres.",
    "Con",
    "Puedes añadir hasta 10 hashtags.",
    "{actor} aceptó tu invitación a colaborar",
    "{actor} te invitó a colaborar en una publicación",
    "Se alcanzó el nivel de Comunidad configurado más alto",
    "{xp} XP · Siguiente: Nv. {level} con {target} XP",
    "Progreso hacia Nv. {level} · objetivo {target} XP",
  ],
  "tr": <String>[
    "Etiket ekle",
    "Taslak kaydetmeden önce bir şey ekleyin.",
    "Aranabilir en fazla 10 etiket ekleyin.",
    "Takdir edilen",
    "Onaylanan anlar",
    "BIL Topluluk profili",
    "BIL, markalı Topluluk kapağına geri dönecek.",
    "Rozetler",
    "Sertifika",
    "Sertifika iptal edildi",
    "Sertifikalı içerik üreticisi",
    "En fazla 5 MB boyutunda geçerli bir JPEG, PNG veya WebP görseli seçin.",
    "İş birliği kabul edildi.",
    "İş birliği reddedildi.",
    "İş birliği daveti",
    "İş birliği daveti kabul edildi",
    "İş birliği — isteğe bağlı",
    "Alınan yorumlar",
    "Topluluk rozetleri",
    "Topluluk geliştiricisi",
    "Topluluk ana sayfası",
    "Bağ kurucu",
    "Katkıda bulunan",
    "Sohbet başlatıcı",
    "Bu taslak silinemedi.",
    "Paylaşım şu anda açılamıyor.",
    "Bu taslak açılamadı. Tekrar deneyin.",
    "Profil kapağı kaldırılamadı.",
    "Bu taslak kaydedilemedi. Hiçbir şey yayımlanmadı.",
    "Şu anda iş birliği yapan kişiler aranamadı.",
    "Takip durumu güncellenemedi.",
    "Profil kapağı güncellenemedi.",
    "Bu iş birliği güncellenemedi. Tekrar deneyin.",
    "İçerik Üretici Merkezi",
    "İçerik Üretici Ödülleri",
    "İçerik üretici araçları",
    "Reddedildi",
    "Taslağı sil",
    "Taslak güvenle kaydedildi.",
    "Taslaklar",
    "İlk an",
    "Seni takip ediyor",
    "Bu ana net bir başlık verin",
    "Etiketler — isteğe bağlı",
    "En fazla 3 Topluluk üyesini davet edin. Davetler yalnızca insan onayından sonra gönderilir ve bir iş birliği yapan kişi yalnızca kabul ettikten sonra herkese açık görünür.",
    "Alınan beğeniler",
    "Kilitli",
    "Anlar",
    "Bu profilde anlar gizlidir.",
    "Yeni takipçiler",
    "Bu profile BIL içerik üretici sertifikası verilmemiş.",
    "Henüz onaylanmış inceleme yok.",
    "Henüz kaydedilmiş taslak yok.",
    "Henüz görünür an yok.",
    "Sertifikalı değil",
    "Aç",
    "Fotoğraflı taslak",
    "Profil kapağı güncellendi.",
    "Yayımlandı",
    "Uygun yönlendirmeler",
    "Profil kapağı kaldırılsın mı?",
    "İncelemeler",
    "Bu profilde incelemeler gizlidir.",
    "Taslağı kaydet",
    "Tamamlanmamış Topluluk gönderilerini kaydedin ve daha sonra devam edin.",
    "Kaydedilmiş Topluluk taslağı",
    "Kaydedilmiş taslak",
    "Ad veya @kullanıcıadı ile ara",
    "İş birliği yapanları ara",
    "Profili paylaş",
    "Görev Merkezi",
    "Sesli metin, gönderinin 1200 karakter sınırını aşacak.",
    "Bu Çevre şu anda kullanılamıyor.",
    "Bu sertifika BIL sunucu yetkisi tarafından doğrulanmıştır.",
    "Bu profil şu anda etkin bir sertifikaya sahip değil.",
    "Bu konu şu anda kullanılamıyor.",
    "Başlık",
    "Başlıksız taslak",
    "Taslağı güncelle",
    "Güncellemeler",
    "Boşluksuz, en fazla 40 karakterlik tek bir etiket kullanın.",
    "Birlikte",
    "En fazla 10 etiket ekleyebilirsiniz.",
    "{actor} iş birliği davetinizi kabul etti",
    "{actor} sizi bir gönderide iş birliği yapmaya davet etti",
    "Yapılandırılmış en yüksek Topluluk seviyesine ulaşıldı",
    "{xp} XP · Sonraki: Sv. {level}, {target} XP",
    "Sv. {level} yolunda ilerleme · hedef {target} XP",
  ],
  "de": <String>[
    "Hashtag hinzufügen",
    "Füge etwas hinzu, bevor du einen Entwurf speicherst.",
    "Füge bis zu 10 durchsuchbare Hashtags hinzu.",
    "Geschätzt",
    "Genehmigte Momente",
    "BIL Community-Profil",
    "BIL kehrt zum gebrandeten Community-Titelbild zurück.",
    "Abzeichen",
    "Zertifizierung",
    "Zertifizierung widerrufen",
    "Zertifizierter Creator",
    "Wähle ein gültiges JPEG-, PNG- oder WebP-Bild mit bis zu 5 MB.",
    "Zusammenarbeit angenommen.",
    "Zusammenarbeit abgelehnt.",
    "Einladung zur Zusammenarbeit",
    "Einladung zur Zusammenarbeit angenommen",
    "Zusammenarbeit — optional",
    "Erhaltene Kommentare",
    "Community-Abzeichen",
    "Community-Gestalter",
    "Community-Startseite",
    "Vernetzer",
    "Mitwirkender",
    "Gesprächsstarter",
    "Dieser Entwurf konnte nicht gelöscht werden.",
    "Teilen kann derzeit nicht geöffnet werden.",
    "Dieser Entwurf konnte nicht geöffnet werden. Versuche es erneut.",
    "Das Profil-Titelbild konnte nicht entfernt werden.",
    "Dieser Entwurf konnte nicht gespeichert werden. Es wurde nichts veröffentlicht.",
    "Mitwirkende können derzeit nicht gesucht werden.",
    "Der Folgestatus konnte nicht aktualisiert werden.",
    "Das Profil-Titelbild konnte nicht aktualisiert werden.",
    "Diese Zusammenarbeit konnte nicht aktualisiert werden. Versuche es erneut.",
    "Creator-Zentrale",
    "Creator-Belohnungen",
    "Creator-Werkzeuge",
    "Abgelehnt",
    "Entwurf löschen",
    "Entwurf sicher gespeichert.",
    "Entwürfe",
    "Erster Moment",
    "Folgt dir",
    "Gib diesem Moment einen klaren Titel",
    "Hashtags — freiwillig",
    "Lade bis zu 3 Community-Mitglieder ein. Einladungen werden erst nach menschlicher Freigabe gesendet, und ein Mitwirkender erscheint erst nach der Annahme öffentlich.",
    "Erhaltene Likes",
    "Gesperrt",
    "Momente",
    "Momente sind in diesem Profil privat.",
    "Neue Follower",
    "Diesem Profil wurde keine BIL-Creator-Zertifizierung erteilt.",
    "Noch keine genehmigten Bewertungen.",
    "Noch keine gespeicherten Entwürfe.",
    "Noch keine sichtbaren Momente.",
    "Nicht zertifiziert",
    "Öffnen",
    "Fotoentwurf",
    "Profil-Titelbild aktualisiert.",
    "Veröffentlicht",
    "Qualifizierte Empfehlungen",
    "Profil-Titelbild entfernen?",
    "Bewertungen",
    "Bewertungen sind in diesem Profil privat.",
    "Entwurf speichern",
    "Speichere unfertige Community-Beiträge und setze sie später fort.",
    "Gespeicherter Community-Entwurf",
    "Gespeicherter Entwurf",
    "Nach Name oder @Handle suchen",
    "Mitwirkende suchen",
    "Profil teilen",
    "Aufgabencenter",
    "Das Sprachtranskript würde das Limit von 1200 Zeichen für Beiträge überschreiten.",
    "Dieser Circle ist derzeit nicht verfügbar.",
    "Diese Zertifizierung wurde von der BIL-Serverautorität verifiziert.",
    "Dieses Profil hat derzeit keine aktive Zertifizierung.",
    "Dieses Thema ist derzeit nicht verfügbar.",
    "Titel",
    "Entwurf ohne Titel",
    "Entwurf aktualisieren",
    "Aktualisierungen",
    "Verwende einen Hashtag ohne Leerzeichen mit bis zu 40 Zeichen.",
    "Mit",
    "Du kannst bis zu 10 Hashtags hinzufügen.",
    "{actor} hat deine Einladung zur Zusammenarbeit angenommen",
    "{actor} hat dich eingeladen, an einem Beitrag mitzuarbeiten",
    "Höchste konfigurierte Community-Stufe erreicht",
    "{xp} XP · Nächste Stufe: {level} bei {target} XP",
    "Fortschritt zu Stufe {level} · Ziel {target} XP",
  ],
  "it": <String>[
    "Aggiungi hashtag",
    "Aggiungi qualcosa prima di salvare una bozza.",
    "Aggiungi fino a 10 hashtag ricercabili.",
    "Apprezzato",
    "Momenti approvati",
    "Profilo Community BIL",
    "BIL tornerà alla copertina Community con il marchio.",
    "Badge",
    "Certificazione",
    "Certificazione revocata",
    "Creator certificato",
    "Scegli un'immagine JPEG, PNG o WebP valida fino a 5 MB.",
    "Collaborazione accettata.",
    "Collaborazione rifiutata.",
    "Invito alla collaborazione",
    "Invito alla collaborazione accettato",
    "Collaborazione — facoltativa",
    "Commenti ricevuti",
    "Badge della Community",
    "Costruttore della community",
    "Home della Community",
    "Connettore",
    "Collaboratore",
    "Avviatore di conversazioni",
    "Impossibile eliminare questa bozza.",
    "Impossibile aprire la condivisione in questo momento.",
    "Impossibile aprire questa bozza. Riprova.",
    "Impossibile rimuovere la copertina del profilo.",
    "Impossibile salvare questa bozza. Non è stato pubblicato nulla.",
    "Impossibile cercare collaboratori in questo momento.",
    "Impossibile aggiornare lo stato di follow.",
    "Impossibile aggiornare la copertina del profilo.",
    "Impossibile aggiornare questa collaborazione. Riprova.",
    "Centro Creator",
    "Ricompense Creator",
    "Strumenti Creator",
    "Rifiutata",
    "Elimina bozza",
    "Bozza salvata in modo sicuro.",
    "Bozze",
    "Primo momento",
    "Ti segue",
    "Dai a questo momento un titolo chiaro",
    "Hashtag — facoltativi",
    "Invita fino a 3 membri della Community. Gli inviti vengono inviati solo dopo l'approvazione umana e un collaboratore appare pubblicamente solo dopo aver accettato.",
    "Mi piace ricevuti",
    "Bloccato",
    "Momenti",
    "I momenti sono privati su questo profilo.",
    "Nuovi follower",
    "A questo profilo non è stata concessa alcuna certificazione Creator BIL.",
    "Non ci sono ancora recensioni approvate.",
    "Non ci sono ancora bozze salvate.",
    "Non ci sono ancora momenti visibili.",
    "Non certificato",
    "Apri",
    "Bozza con foto",
    "Copertina del profilo aggiornata.",
    "Pubblicato",
    "Referral qualificati",
    "Rimuovere la copertina del profilo?",
    "Recensioni",
    "Le recensioni sono private su questo profilo.",
    "Salva bozza",
    "Salva i post Community non completati e riprendi più tardi.",
    "Bozza Community salvata",
    "Bozza salvata",
    "Cerca per nome o @handle",
    "Cerca collaboratori",
    "Condividi profilo",
    "Centro attività",
    "La trascrizione vocale supererebbe il limite di 1200 caratteri del post.",
    "Questo Circle non è disponibile al momento.",
    "Questa certificazione è verificata dall'autorità server BIL.",
    "Questo profilo non dispone attualmente di una certificazione attiva.",
    "Questo argomento non è disponibile al momento.",
    "Titolo",
    "Bozza senza titolo",
    "Aggiorna bozza",
    "Aggiornamenti",
    "Usa un solo hashtag senza spazi, fino a 40 caratteri.",
    "Con",
    "Puoi aggiungere fino a 10 hashtag.",
    "{actor} ha accettato il tuo invito alla collaborazione",
    "{actor} ti ha invitato a collaborare a un post",
    "Raggiunto il livello Community configurato più alto",
    "{xp} XP · Successivo: Lv {level} a {target} XP",
    "Avanzamento verso Lv {level} · obiettivo {target} XP",
  ],
};
