/// Reviewed publication metadata for the official BIL legal documents.
abstract final class LegalStatusRuntimeCopy {
  static const supported = <String>{
    'ar',
    'en',
    'fr',
    'es',
    'tr',
    'de',
    'it',
    'pt-BR',
    'pt-PT',
    'ur',
    'fa',
    'hi',
    'id',
    'ms',
    'ja',
    'ko',
    'zh-Hans',
    'zh-Hant',
    'ru',
    'bn',
    'vi',
    'th',
    'pl',
    'nl',
    'uk',
  };

  static const values = <String, Map<String, String>>{
    'Last updated: 22 August 2026 • BIL Health': {
      'ar': 'آخر تحديث: 22 أغسطس 2026 • BIL Health',
      'en': 'Last updated: 22 August 2026 • BIL Health',
      'fr': 'Dernière mise à jour : 22 août 2026 • BIL Health',
      'es': 'Última actualización: 22 de agosto de 2026 • BIL Health',
      'tr': 'Son güncelleme: 22 Ağustos 2026 • BIL Health',
      'de': 'Zuletzt aktualisiert: 22. August 2026 • BIL Health',
      'it': 'Ultimo aggiornamento: 22 agosto 2026 • BIL Health',
      'pt-BR': 'Última atualização: 22 de agosto de 2026 • BIL Health',
      'pt-PT': 'Última atualização: 22 de agosto de 2026 • BIL Health',
      'ur': 'آخری تازہ کاری: 22 اگست 2026 • BIL Health',
      'fa': 'آخرین به‌روزرسانی: ۲۲ اوت ۲۰۲۶ • BIL Health',
      'hi': 'अंतिम अपडेट: 22 अगस्त 2026 • BIL Health',
      'id': 'Terakhir diperbarui: 22 Agustus 2026 • BIL Health',
      'ms': 'Kemas kini terakhir: 22 Ogos 2026 • BIL Health',
      'ja': '最終更新日：2026年8月22日 • BIL Health',
      'ko': '최종 업데이트: 2026년 8월 22일 • BIL Health',
      'zh-Hans': '最后更新：2026年8月22日 • BIL Health',
      'zh-Hant': '最後更新：2026年8月22日 • BIL Health',
      'ru': 'Последнее обновление: 22 августа 2026 г. • BIL Health',
      'bn': 'সর্বশেষ আপডেট: ২২ আগস্ট ২০২৬ • BIL Health',
      'vi': 'Cập nhật lần cuối: 22 tháng 8, 2026 • BIL Health',
      'th': 'อัปเดตล่าสุด: 22 สิงหาคม 2026 • BIL Health',
      'pl': 'Ostatnia aktualizacja: 22 sierpnia 2026 • BIL Health',
      'nl': 'Laatst bijgewerkt: 22 augustus 2026 • BIL Health',
      'uk': 'Останнє оновлення: 22 серпня 2026 р. • BIL Health',
    },
  };
}
