// Reviewed Profile copy catalog shard C.
const profileRuntimeCopyCatalogC = <String, Map<String, String>>{
  'Current weight': {
    'ar': 'الوزن الحالي',
    'en': 'Current weight',
    'fr': 'Poids actuel',
    'es': 'Peso actual',
    'tr': 'Mevcut kilo',
    'de': 'Aktuelles Gewicht',
    'it': 'Peso attuale',
    'pt-BR': 'Peso atual',
    'pt-PT': 'Peso atual',
    'ur': 'موجودہ وزن',
    'fa': 'وزن فعلی',
    'hi': 'वर्तमान वज़न',
    'id': 'Berat badan saat ini',
    'ms': 'Berat semasa',
    'ja': '現在の体重',
    'ko': '현재 체중',
    'zh-Hans': '当前体重',
    'zh-Hant': '目前體重',
    'ru': 'Текущий вес',
    'bn': 'বর্তমান ওজন',
    'vi': 'Cân nặng hiện tại',
    'th': 'น้ำหนักปัจจุบัน',
    'pl': 'Aktualna masa ciała',
    'nl': 'Huidig gewicht',
    'uk': 'Поточна вага',
  },
  'Goal weight': {
    'ar': 'الوزن المستهدف',
    'en': 'Goal weight',
    'fr': 'Poids cible',
    'es': 'Peso objetivo',
    'tr': 'Hedef kilo',
    'de': 'Zielgewicht',
    'it': 'Peso obiettivo',
    'pt-BR': 'Peso-alvo',
    'pt-PT': 'Peso-alvo',
    'ur': 'ہدف وزن',
    'fa': 'وزن هدف',
    'hi': 'लक्ष्य वज़न',
    'id': 'Berat badan target',
    'ms': 'Berat sasaran',
    'ja': '目標体重',
    'ko': '목표 체중',
    'zh-Hans': '目标体重',
    'zh-Hant': '目標體重',
    'ru': 'Целевой вес',
    'bn': 'লক্ষ্য ওজন',
    'vi': 'Cân nặng mục tiêu',
    'th': 'น้ำหนักเป้าหมาย',
    'pl': 'Docelowa masa ciała',
    'nl': 'Streefgewicht',
    'uk': 'Цільова вага',
  },
  'Sedentary': {
    'ar': 'حركة محدودة',
    'en': 'Sedentary',
    'fr': 'Sédentaire',
    'es': 'Sedentario',
    'tr': 'Hareketsiz',
    'de': 'Sitzend',
    'it': 'Sedentario',
    'pt-BR': 'Sedentário',
    'pt-PT': 'Sedentário',
    'ur': 'غیر فعال',
    'fa': 'کم‌تحرک',
    'hi': 'निष्क्रिय',
    'id': 'Sedenter',
    'ms': 'Tidak aktif',
    'ja': '座りがち',
    'ko': '좌식 생활',
    'zh-Hans': '久坐少动',
    'zh-Hant': '久坐少動',
    'ru': 'Малоподвижный',
    'bn': 'নিষ্ক্রিয়',
    'vi': 'Ít vận động',
    'th': 'ไม่ค่อยเคลื่อนไหว',
    'pl': 'Siedzący tryb życia',
    'nl': 'Zittend',
    'uk': 'Малорухливий',
  },
  'Lightly active': {
    'ar': 'نشاط خفيف',
    'en': 'Lightly active',
    'fr': 'Légèrement actif',
    'es': 'Actividad ligera',
    'tr': 'Hafif aktif',
    'de': 'Leicht aktiv',
    'it': 'Leggermente attivo',
    'pt-BR': 'Ligeiramente ativo',
    'pt-PT': 'Ligeiramente ativo',
    'ur': 'ہلکی سرگرمی',
    'fa': 'کمی فعال',
    'hi': 'हल्का सक्रिय',
    'id': 'Sedikit aktif',
    'ms': 'Aktif ringan',
    'ja': '軽い活動',
    'ko': '가벼운 활동',
    'zh-Hans': '轻度活动',
    'zh-Hant': '輕度活動',
    'ru': 'Низкая активность',
    'bn': 'হালকা সক্রিয়',
    'vi': 'Hoạt động nhẹ',
    'th': 'ออกกำลังกายเล็กน้อย',
    'pl': 'Lekko aktywny',
    'nl': 'Licht actief',
    'uk': 'Легка активність',
  },
  'Moderately active': {
    'ar': 'نشاط متوسط',
    'en': 'Moderately active',
    'fr': 'Modérément actif',
    'es': 'Actividad moderada',
    'tr': 'Orta aktif',
    'de': 'Mäßig aktiv',
    'it': 'Moderatamente attivo',
    'pt-BR': 'Moderadamente ativo',
    'pt-PT': 'Moderadamente ativo',
    'ur': 'معتدل سرگرمی',
    'fa': 'فعالیت متوسط',
    'hi': 'मध्यम सक्रिय',
    'id': 'Cukup aktif',
    'ms': 'Aktif sederhana',
    'ja': '中程度の活動',
    'ko': '보통 활동',
    'zh-Hans': '中度活动',
    'zh-Hant': '中度活動',
    'ru': 'Умеренная активность',
    'bn': 'মাঝারি সক্রিয়',
    'vi': 'Hoạt động vừa',
    'th': 'ออกกำลังกายปานกลาง',
    'pl': 'Umiarkowanie aktywny',
    'nl': 'Gemiddeld actief',
    'uk': 'Помірна активність',
  },
  'Very active': {
    'ar': 'نشاط مكثف',
    'en': 'Very active',
    'fr': 'Très actif',
    'es': 'Muy activo',
    'tr': 'Çok aktif',
    'de': 'Sehr aktiv',
    'it': 'Molto attivo',
    'pt-BR': 'Muito ativo',
    'pt-PT': 'Muito ativo',
    'ur': 'بہت زیادہ سرگرم',
    'fa': 'بسیار فعال',
    'hi': 'बहुत सक्रिय',
    'id': 'Sangat aktif',
    'ms': 'Sangat aktif',
    'ja': '非常に活発',
    'ko': '매우 활동적',
    'zh-Hans': '高度活跃',
    'zh-Hant': '高度活躍',
    'ru': 'Очень высокая активность',
    'bn': 'খুব সক্রিয়',
    'vi': 'Hoạt động nhiều',
    'th': 'ออกกำลังกายมาก',
    'pl': 'Bardzo aktywny',
    'nl': 'Zeer actief',
    'uk': 'Дуже активний',
  },
  'Save health profile': {
    'ar': 'حفظ الملف الصحي',
    'en': 'Save health profile',
    'fr': 'Enregistrer le profil santé',
    'es': 'Guardar perfil de salud',
    'tr': 'Sağlık profilini kaydet',
    'de': 'Gesundheitsprofil speichern',
    'it': 'Salva profilo salute',
    'pt-BR': 'Salvar perfil de saúde',
    'pt-PT': 'Guardar perfil de saúde',
    'ur': 'صحت کا پروفائل محفوظ کریں',
    'fa': 'ذخیره نمایه سلامت',
    'hi': 'स्वास्थ्य प्रोफ़ाइल सेव करें',
    'id': 'Simpan profil kesehatan',
    'ms': 'Simpan profil kesihatan',
    'ja': '健康プロフィールを保存',
    'ko': '건강 프로필 저장',
    'zh-Hans': '保存健康档案',
    'zh-Hant': '儲存健康檔案',
    'ru': 'Сохранить профиль здоровья',
    'bn': 'স্বাস্থ্য প্রোফাইল সংরক্ষণ করুন',
    'vi': 'Lưu hồ sơ sức khỏe',
    'th': 'บันทึกโปรไฟล์สุขภาพ',
    'pl': 'Zapisz profil zdrowotny',
    'nl': 'Gezondheidsprofiel opslaan',
    'uk': 'Зберегти профіль здоров’я',
  },
  'Omnivore': {
    'ar': 'نظام متنوع',
    'en': 'Omnivore',
    'fr': 'Omnivore',
    'es': 'Omnívoro',
    'tr': 'Hepçil',
    'de': 'Allesesser',
    'it': 'Onnivoro',
    'pt-BR': 'Onívoro',
    'pt-PT': 'Omnívoro',
    'ur': 'ہمہ خور',
    'fa': 'همه‌چیزخوار',
    'hi': 'सर्वाहारी',
    'id': 'Omnivora',
    'ms': 'Omnivor',
    'ja': '雑食',
    'ko': '잡식',
    'zh-Hans': '杂食',
    'zh-Hant': '雜食',
    'ru': 'Всеядный',
    'bn': 'সর্বভুক',
    'vi': 'Ăn tạp',
    'th': 'กินได้ทุกประเภท',
    'pl': 'Wszystkożerny',
    'nl': 'Alleseter',
    'uk': 'Всеїдний',
  },
  'Pescatarian': {
    'ar': 'نباتي مع الأسماك',
    'en': 'Pescatarian',
    'fr': 'Pescétarien',
    'es': 'Pescetariano',
    'tr': 'Pesketaryen',
    'de': 'Pescetarisch',
    'it': 'Pescetariano',
    'pt-BR': 'Pescetariano',
    'pt-PT': 'Pescetariano',
    'ur': 'مچھلی خور سبزی پسند',
    'fa': 'ماهی‌خوار',
    'hi': 'मत्स्याहारी',
    'id': 'Peskatarian',
    'ms': 'Pescatarian',
    'ja': 'ペスカタリアン',
    'ko': '페스코 베지테리언',
    'zh-Hans': '鱼素',
    'zh-Hant': '魚素',
    'ru': 'Пескетарианский',
    'bn': 'মাছসহ নিরামিষ',
    'vi': 'Ăn chay có cá',
    'th': 'มังสวิรัติที่กินปลา',
    'pl': 'Peskatariański',
    'nl': 'Pescotarisch',
    'uk': 'Пескетаріанський',
  },
  'Vegetarian': {
    'ar': 'نباتي',
    'en': 'Vegetarian',
    'fr': 'Végétarien',
    'es': 'Vegetariano',
    'tr': 'Vejetaryen',
    'de': 'Vegetarisch',
    'it': 'Vegetariano',
    'pt-BR': 'Vegetariano',
    'pt-PT': 'Vegetariano',
    'ur': 'سبزی خور',
    'fa': 'گیاه‌خوار',
    'hi': 'शाकाहारी',
    'id': 'Vegetarian',
    'ms': 'Vegetarian',
    'ja': 'ベジタリアン',
    'ko': '채식',
    'zh-Hans': '素食',
    'zh-Hant': '素食',
    'ru': 'Вегетарианский',
    'bn': 'নিরামিষ',
    'vi': 'Ăn chay',
    'th': 'มังสวิรัติ',
    'pl': 'Wegetariański',
    'nl': 'Vegetarisch',
    'uk': 'Вегетаріанський',
  },
  'Vegan': {
    'ar': 'نباتي صرف',
    'en': 'Vegan',
    'fr': 'Végane',
    'es': 'Vegano',
    'tr': 'Vegan',
    'de': 'Vegan',
    'it': 'Vegano',
    'pt-BR': 'Vegano',
    'pt-PT': 'Vegano',
    'ur': 'خالص نباتاتی',
    'fa': 'وگان',
    'hi': 'वीगन',
    'id': 'Vegan',
    'ms': 'Vegan',
    'ja': 'ヴィーガン',
    'ko': '비건',
    'zh-Hans': '纯素',
    'zh-Hant': '純素',
    'ru': 'Веганский',
    'bn': 'ভেগান',
    'vi': 'Thuần chay',
    'th': 'วีแกน',
    'pl': 'Wegański',
    'nl': 'Veganistisch',
    'uk': 'Веганський',
  },
  'Balanced': {
    'ar': 'متوازن',
    'en': 'Balanced',
    'fr': 'Équilibré',
    'es': 'Equilibrado',
    'tr': 'Dengeli',
    'de': 'Ausgewogen',
    'it': 'Bilanciato',
    'pt-BR': 'Equilibrado',
    'pt-PT': 'Equilibrado',
    'ur': 'متوازن',
    'fa': 'متعادل',
    'hi': 'संतुलित',
    'id': 'Seimbang',
    'ms': 'Seimbang',
    'ja': 'バランス重視',
    'ko': '균형식',
    'zh-Hans': '均衡',
    'zh-Hant': '均衡',
    'ru': 'Сбалансированный',
    'bn': 'সুষম',
    'vi': 'Cân bằng',
    'th': 'สมดุล',
    'pl': 'Zbilansowany',
    'nl': 'Gebalanceerd',
    'uk': 'Збалансований',
  },
  'High protein': {
    'ar': 'عالي البروتين',
    'en': 'High protein',
    'fr': 'Riche en protéines',
    'es': 'Alto en proteínas',
    'tr': 'Yüksek protein',
    'de': 'Proteinreich',
    'it': 'Ricco di proteine',
    'pt-BR': 'Rico em proteína',
    'pt-PT': 'Rico em proteína',
    'ur': 'زیادہ پروٹین',
    'fa': 'پرپروتئین',
    'hi': 'उच्च प्रोटीन',
    'id': 'Tinggi protein',
    'ms': 'Tinggi protein',
    'ja': '高たんぱく',
    'ko': '고단백',
    'zh-Hans': '高蛋白',
    'zh-Hant': '高蛋白',
    'ru': 'Высокобелковый',
    'bn': 'উচ্চ প্রোটিন',
    'vi': 'Giàu protein',
    'th': 'โปรตีนสูง',
    'pl': 'Wysokobiałkowy',
    'nl': 'Eiwitrijk',
    'uk': 'Високобілковий',
  },
  'Low carb': {
    'ar': 'منخفض الكربوهيدرات',
    'en': 'Low carb',
    'fr': 'Faible en glucides',
    'es': 'Bajo en carbohidratos',
    'tr': 'Düşük karbonhidrat',
    'de': 'Kohlenhydratarm',
    'it': 'A basso contenuto di carboidrati',
    'pt-BR': 'Baixo teor de carboidratos',
    'pt-PT': 'Baixo teor de hidratos de carbono',
    'ur': 'کم کاربوہائیڈریٹ',
    'fa': 'کم‌کربوهیدرات',
    'hi': 'कम कार्ब',
    'id': 'Rendah karbohidrat',
    'ms': 'Rendah karbohidrat',
    'ja': '低炭水化物',
    'ko': '저탄수화물',
    'zh-Hans': '低碳水',
    'zh-Hant': '低碳水',
    'ru': 'Низкоуглеводный',
    'bn': 'কম কার্ব',
    'vi': 'Ít carb',
    'th': 'คาร์โบไฮเดรตต่ำ',
    'pl': 'Niskowęglowodanowy',
    'nl': 'Koolhydraatarm',
    'uk': 'Низьковуглеводний',
  },
  'Keto': {
    'ar': 'كيتو',
    'en': 'Keto',
    'fr': 'Cétogène',
    'es': 'Cetogénico',
    'tr': 'Ketojenik',
    'de': 'Ketogen',
    'it': 'Chetogenico',
    'pt-BR': 'Cetogênico',
    'pt-PT': 'Cetogénico',
    'ur': 'کیٹو',
    'fa': 'کتوژنیک',
    'hi': 'कीटो',
    'id': 'Ketogenik',
    'ms': 'Ketogenik',
    'ja': 'ケトジェニック',
    'ko': '키토',
    'zh-Hans': '生酮',
    'zh-Hant': '生酮',
    'ru': 'Кето',
    'bn': 'কিটো',
    'vi': 'Keto',
    'th': 'คีโต',
    'pl': 'Ketogeniczny',
    'nl': 'Ketogeen',
    'uk': 'Кето',
  },
  'Mediterranean': {
    'ar': 'متوسطي',
    'en': 'Mediterranean',
    'fr': 'Méditerranéen',
    'es': 'Mediterráneo',
    'tr': 'Akdeniz',
    'de': 'Mediterran',
    'it': 'Mediterraneo',
    'pt-BR': 'Mediterrâneo',
    'pt-PT': 'Mediterrânico',
    'ur': 'بحیرۂ روم',
    'fa': 'مدیترانه‌ای',
    'hi': 'भूमध्यसागरीय',
    'id': 'Mediterania',
    'ms': 'Mediterranean',
    'ja': '地中海式',
    'ko': '지중해식',
    'zh-Hans': '地中海式',
    'zh-Hant': '地中海式',
    'ru': 'Средиземноморский',
    'bn': 'ভূমধ্যসাগরীয়',
    'vi': 'Địa Trung Hải',
    'th': 'เมดิเตอร์เรเนียน',
    'pl': 'Śródziemnomorski',
    'nl': 'Mediterraan',
    'uk': 'Середземноморський',
  },
  'Plant-forward': {
    'ar': 'يركز على النباتات',
    'en': 'Plant-forward',
    'fr': 'À dominante végétale',
    'es': 'Centrado en plantas',
    'tr': 'Bitki ağırlıklı',
    'de': 'Pflanzenbetont',
    'it': 'A prevalenza vegetale',
    'pt-BR': 'Predominantemente vegetal',
    'pt-PT': 'Predominantemente vegetal',
    'ur': 'نباتات پر مرکوز',
    'fa': 'گیاه‌محور',
    'hi': 'पौध-प्रधान',
    'id': 'Dominan nabati',
    'ms': 'Berasaskan tumbuhan',
    'ja': '植物性食品中心',
    'ko': '식물성 중심',
    'zh-Hans': '植物为主',
    'zh-Hant': '植物為主',
    'ru': 'С акцентом на растительную пищу',
    'bn': 'উদ্ভিদ-প্রধান',
    'vi': 'Ưu tiên thực vật',
    'th': 'เน้นพืชเป็นหลัก',
    'pl': 'Z przewagą roślin',
    'nl': 'Plantaardig gericht',
    'uk': 'З акцентом на рослинну їжу',
  },
};
