part of 'runtime_copy_next_workspace.dart';

const _nextWorkspaceSupplementalRows1 = <String, List<String>>{
  "ms": [
    "Gambaran keseluruhan",
    "Foto siaran",
    "Laman utama",
    "Siaran peribadi yang belum selesai",
    "Simpan profil dan cipta Kod BIL",
    "Log masuk untuk membuka draf peribadi anda.",
    "Kebenaran tindakan jurulatih",
    "Statistik",
    "{count} foto",
    "Kelulusan",
    "Padam {count} draf?",
    "Padam yang dipilih ({count})",
    "Tindakan draf",
    "Draf ({count})",
    "Kali terakhir disimpan {count} hari lalu",
    "Kali terakhir disimpan {count} jam lalu",
    "Kali terakhir disimpan {count} minit lalu",
    "Sebutan",
    "Kelulusan, sebutan dan komen baharu akan muncul di sini.",
    "Belum ada draf yang disimpan",
    "Tetapan pemberitahuan",
    "Pemberitahuan tidak tersedia",
    "Sekarang",
    "Ganjaran ditambahkan pada baki AI anda",
    "Simpan siaran yang belum selesai dan sambung di sini kemudian.",
    "Baru sahaja disimpan",
    "Pilih",
    "Ini hanya memadamkan draf peribadi yang dipilih.",
    "Anda sudah melihat semua pemberitahuan terkini",
    "Terdahulu",
    "Akaun anda telah berubah. Kembali ke Komuniti untuk meneruskan.",
    "Hadkan teks kepada 1200 aksara. Teks anda dikekalkan.",
  ],
  "ja": [
    "概要",
    "投稿の写真",
    "ホーム",
    "作成途中の非公開投稿",
    "プロフィールを保存してBILコードを作成",
    "非公開の下書きを開くにはログインしてください。",
    "コーチの操作権限",
    "統計",
    "{count}枚の写真",
    "承認",
    "下書きを{count}件削除しますか？",
    "選択した下書きを削除（{count}件）",
    "下書きの操作",
    "下書き（{count}件）",
    "最終保存：{count}日前",
    "最終保存：{count}時間前",
    "最終保存：{count}分前",
    "メンション",
    "新しい承認、メンション、コメントがここに表示されます。",
    "保存された下書きはまだありません",
    "通知設定",
    "通知を利用できません",
    "今",
    "報酬がAI残高に追加されました",
    "作成途中の投稿を保存し、後でここから再開できます。",
    "たった今保存しました",
    "選択",
    "選択した非公開の下書きだけが削除されます。",
    "すべての新しい通知を確認しました",
    "以前の通知",
    "アカウントが変更されました。続けるにはコミュニティに戻ってください。",
    "文字数を1200文字以内にしてください。入力した内容は保持されています。",
  ],
  "ko": [
    "개요",
    "게시물 사진",
    "홈",
    "작성 중인 비공개 게시물",
    "프로필 저장 및 BIL 코드 생성",
    "비공개 초안을 열려면 로그인하세요.",
    "코치 작업 권한",
    "통계",
    "사진 {count}장",
    "승인",
    "초안 {count}개를 삭제할까요?",
    "선택 항목 삭제 ({count})",
    "초안 작업",
    "초안 ({count})",
    "마지막 저장: {count}일 전",
    "마지막 저장: {count}시간 전",
    "마지막 저장: {count}분 전",
    "언급",
    "새 승인, 언급 및 댓글이 여기에 표시됩니다.",
    "아직 저장된 초안이 없습니다",
    "알림 설정",
    "알림을 사용할 수 없습니다",
    "지금",
    "보상이 AI 잔액에 추가되었습니다",
    "작성 중인 게시물을 저장하고 나중에 여기서 이어서 작성하세요.",
    "방금 저장됨",
    "선택",
    "선택한 비공개 초안만 삭제합니다.",
    "새 알림을 모두 확인했습니다",
    "이전 알림",
    "계정이 변경되었습니다. 계속하려면 커뮤니티로 돌아가세요.",
    "텍스트를 1200자 이내로 줄여 주세요. 입력한 내용은 유지됩니다.",
  ],
  "zh-Hans": [
    "概览",
    "帖子照片",
    "首页",
    "尚未完成的私密帖子",
    "保存个人资料并创建 BIL 代码",
    "登录以打开你的私密草稿。",
    "教练操作权限",
    "统计",
    "{count} 张照片",
    "审批",
    "删除 {count} 篇草稿？",
    "删除所选（{count}）",
    "草稿操作",
    "草稿（{count}）",
    "上次保存于 {count} 天前",
    "上次保存于 {count} 小时前",
    "上次保存于 {count} 分钟前",
    "提及",
    "新的审批、提及和评论将显示在这里。",
    "还没有已保存的草稿",
    "通知设置",
    "通知不可用",
    "现在",
    "奖励已添加到你的 AI 余额",
    "保存未完成的帖子，以后在这里继续编辑。",
    "刚刚保存",
    "选择",
    "此操作仅删除所选的私密草稿。",
    "你已查看所有新通知",
    "更早",
    "你的账号已切换。请返回社区继续。",
    "请将文本控制在1200个字符以内。你输入的文本已保留。",
  ],
  "zh-Hant": [
    "總覽",
    "貼文照片",
    "首頁",
    "尚未完成的私人貼文",
    "儲存個人檔案並建立 BIL 代碼",
    "登入以開啟你的私人草稿。",
    "教練操作權限",
    "統計",
    "{count} 張照片",
    "審核",
    "刪除 {count} 篇草稿？",
    "刪除所選（{count}）",
    "草稿操作",
    "草稿（{count}）",
    "上次儲存於 {count} 天前",
    "上次儲存於 {count} 小時前",
    "上次儲存於 {count} 分鐘前",
    "提及",
    "新的審核、提及和留言將顯示在這裡。",
    "還沒有已儲存的草稿",
    "通知設定",
    "通知無法使用",
    "現在",
    "獎勵已加入你的 AI 餘額",
    "儲存未完成的貼文，稍後在這裡繼續編輯。",
    "剛剛儲存",
    "選取",
    "此操作只會刪除所選的私人草稿。",
    "你已查看所有新通知",
    "更早",
    "你的帳號已切換。請返回社群繼續。",
    "請將文字控制在1200個字元以內。你輸入的文字已保留。",
  ],
  "ru": [
    "Обзор",
    "Фотографии публикации",
    "Главная",
    "Незавершённые приватные публикации",
    "Сохранить профиль и создать код BIL",
    "Войдите, чтобы открыть свои приватные черновики.",
    "Разрешения на действия тренера",
    "Статистика",
    "Фото: {count}",
    "Одобрения",
    "Удалить черновики: {count}?",
    "Удалить выбранные ({count})",
    "Действия с черновиком",
    "Черновики ({count})",
    "Последнее сохранение: {count} дн. назад",
    "Последнее сохранение: {count} ч назад",
    "Последнее сохранение: {count} мин назад",
    "Упоминания",
    "Здесь появятся новые одобрения, упоминания и комментарии.",
    "Сохранённых черновиков пока нет",
    "Настройки уведомлений",
    "Уведомления недоступны",
    "Сейчас",
    "Награда добавлена на ваш баланс ИИ",
    "Сохраняйте незавершённые публикации и продолжайте их здесь позже.",
    "Только что сохранено",
    "Выбрать",
    "Будут удалены только выбранные приватные черновики.",
    "Вы просмотрели все новые уведомления",
    "Ранее",
    "Аккаунт изменился. Вернитесь в сообщество, чтобы продолжить.",
    "Ограничьте текст 1200 символами. Ваш текст сохранён.",
  ],
  "bn": [
    "সারসংক্ষেপ",
    "পোস্টের ছবি",
    "প্রধান পাতা",
    "ব্যক্তিগত অসমাপ্ত পোস্ট",
    "প্রোফাইল সংরক্ষণ করুন এবং BIL কোড তৈরি করুন",
    "আপনার ব্যক্তিগত খসড়া খুলতে সাইন ইন করুন।",
    "কোচের কাজের অনুমতি",
    "পরিসংখ্যান",
    "{count}টি ছবি",
    "অনুমোদন",
    "{count}টি খসড়া মুছবেন?",
    "নির্বাচিতগুলো মুছুন ({count})",
    "খসড়ার কাজ",
    "খসড়া ({count})",
    "শেষবার {count} দিন আগে সংরক্ষিত",
    "শেষবার {count} ঘণ্টা আগে সংরক্ষিত",
    "শেষবার {count} মিনিট আগে সংরক্ষিত",
    "উল্লেখ",
    "নতুন অনুমোদন, উল্লেখ এবং মন্তব্য এখানে দেখা যাবে।",
    "এখনও কোনো খসড়া সংরক্ষণ করা হয়নি",
    "বিজ্ঞপ্তির সেটিংস",
    "বিজ্ঞপ্তি পাওয়া যাচ্ছে না",
    "এখন",
    "পুরস্কার আপনার AI ব্যালেন্সে যোগ করা হয়েছে",
    "অসমাপ্ত পোস্ট সংরক্ষণ করুন এবং পরে এখান থেকে চালিয়ে যান।",
    "এইমাত্র সংরক্ষিত",
    "নির্বাচন করুন",
    "এতে কেবল নির্বাচিত ব্যক্তিগত খসড়াগুলো মুছে যাবে।",
    "আপনি সব নতুন বিজ্ঞপ্তি দেখে নিয়েছেন",
    "আগের বিজ্ঞপ্তি",
    "আপনার অ্যাকাউন্ট বদলে গেছে। চালিয়ে যেতে কমিউনিটিতে ফিরে যান।",
    "লেখাটি 1200 অক্ষরের মধ্যে রাখুন। আপনার লেখা অক্ষত রাখা হয়েছে।",
  ],
  "vi": [
    "Tổng quan",
    "Ảnh bài viết",
    "Trang chủ",
    "Bài viết riêng tư chưa hoàn thành",
    "Lưu hồ sơ và tạo mã BIL",
    "Đăng nhập để mở bản nháp riêng tư của bạn.",
    "Quyền thực hiện thao tác của huấn luyện viên",
    "Thống kê",
    "{count} ảnh",
    "Phê duyệt",
    "Xóa {count} bản nháp?",
    "Xóa mục đã chọn ({count})",
    "Thao tác với bản nháp",
    "Bản nháp ({count})",
    "Lưu lần cuối {count} ngày trước",
    "Lưu lần cuối {count} giờ trước",
    "Lưu lần cuối {count} phút trước",
    "Lượt nhắc đến",
    "Các phê duyệt, lượt nhắc đến và bình luận mới sẽ xuất hiện ở đây.",
    "Chưa có bản nháp đã lưu",
    "Cài đặt thông báo",
    "Thông báo không khả dụng",
    "Bây giờ",
    "Phần thưởng đã được thêm vào số dư AI của bạn",
    "Lưu bài viết chưa hoàn thành và tiếp tục tại đây sau.",
    "Vừa lưu",
    "Chọn",
    "Thao tác này chỉ xóa các bản nháp riêng tư đã chọn.",
    "Bạn đã xem hết thông báo mới",
    "Trước đó",
    "Tài khoản của bạn đã thay đổi. Hãy quay lại Cộng đồng để tiếp tục.",
    "Giới hạn nội dung trong 1200 ký tự. Nội dung bạn nhập vẫn được giữ lại.",
  ],
  "th": [
    "ภาพรวม",
    "รูปภาพของโพสต์",
    "หน้าหลัก",
    "โพสต์ส่วนตัวที่ยังไม่เสร็จ",
    "บันทึกโปรไฟล์และสร้างรหัส BIL",
    "ลงชื่อเข้าใช้เพื่อเปิดฉบับร่างส่วนตัวของคุณ",
    "สิทธิ์การดำเนินการของโค้ช",
    "สถิติ",
    "รูปภาพ {count} รูป",
    "การอนุมัติ",
    "ลบฉบับร่าง {count} รายการหรือไม่?",
    "ลบรายการที่เลือก ({count})",
    "การดำเนินการกับฉบับร่าง",
    "ฉบับร่าง ({count})",
    "บันทึกครั้งล่าสุด {count} วันที่แล้ว",
    "บันทึกครั้งล่าสุด {count} ชั่วโมงที่แล้ว",
    "บันทึกครั้งล่าสุด {count} นาทีที่แล้ว",
    "การกล่าวถึง",
    "การอนุมัติ การกล่าวถึง และความคิดเห็นใหม่จะปรากฏที่นี่",
    "ยังไม่มีฉบับร่างที่บันทึกไว้",
    "การตั้งค่าการแจ้งเตือน",
    "การแจ้งเตือนไม่พร้อมใช้งาน",
    "ตอนนี้",
    "เพิ่มรางวัลในยอดคงเหลือ AI ของคุณแล้ว",
    "บันทึกโพสต์ที่ยังไม่เสร็จและกลับมาทำต่อที่นี่ภายหลัง",
    "เพิ่งบันทึก",
    "เลือก",
    "การดำเนินการนี้จะลบเฉพาะฉบับร่างส่วนตัวที่เลือกไว้เท่านั้น",
    "คุณดูการแจ้งเตือนใหม่ทั้งหมดแล้ว",
    "ก่อนหน้านี้",
    "บัญชีของคุณเปลี่ยนแล้ว กลับไปที่ชุมชนเพื่อดำเนินการต่อ",
    "จำกัดข้อความไม่เกิน 1200 อักขระ ข้อความของคุณยังคงอยู่",
  ],
  "pl": [
    "Przegląd",
    "Zdjęcia wpisu",
    "Strona główna",
    "Prywatne, niedokończone wpisy",
    "Zapisz profil i utwórz kod BIL",
    "Zaloguj się, aby otworzyć swoje prywatne wersje robocze.",
    "Uprawnienia do działań trenera",
    "Statystyki",
    "Zdjęcia: {count}",
    "Zatwierdzenia",
    "Usunąć wersje robocze ({count})?",
    "Usuń wybrane ({count})",
    "Działania na wersji roboczej",
    "Wersje robocze ({count})",
    "Ostatni zapis: {count} dni temu",
    "Ostatni zapis: {count} godz. temu",
    "Ostatni zapis: {count} min temu",
    "Wzmianki",
    "Tutaj pojawią się nowe zatwierdzenia, wzmianki i komentarze.",
    "Nie ma jeszcze zapisanych wersji roboczych",
    "Ustawienia powiadomień",
    "Powiadomienia są niedostępne",
    "Teraz",
    "Nagroda została dodana do Twojego salda AI",
    "Zapisuj niedokończone wpisy i wracaj do nich tutaj później.",
    "Zapisano przed chwilą",
    "Wybierz",
    "To usunie tylko wybrane prywatne wersje robocze.",
    "Wszystkie nowe powiadomienia zostały wyświetlone",
    "Wcześniejsze",
    "Twoje konto się zmieniło. Wróć do Społeczności, aby kontynuować.",
    "Ogranicz tekst do 1200 znaków. Twój tekst został zachowany.",
  ],
  "nl": [
    "Overzicht",
    "Berichtfoto’s",
    "Startpagina",
    "Onvoltooide privéberichten",
    "Profiel opslaan en BIL-code maken",
    "Log in om je privéconcepten te openen.",
    "Machtigingen voor coachacties",
    "Statistieken",
    "{count} foto’s",
    "Goedkeuringen",
    "{count} concepten verwijderen?",
    "Geselecteerde verwijderen ({count})",
    "Conceptacties",
    "Concepten ({count})",
    "Laatst opgeslagen: {count} d geleden",
    "Laatst opgeslagen: {count} u geleden",
    "Laatst opgeslagen: {count} min geleden",
    "Vermeldingen",
    "Nieuwe goedkeuringen, vermeldingen en reacties verschijnen hier.",
    "Nog geen opgeslagen concepten",
    "Meldingsinstellingen",
    "Meldingen zijn niet beschikbaar",
    "Nu",
    "Beloning toegevoegd aan je AI-tegoed",
    "Sla onvoltooide berichten op en ga hier later verder.",
    "Zojuist opgeslagen",
    "Selecteren",
    "Dit verwijdert alleen de geselecteerde privéconcepten.",
    "Je bent helemaal bij",
    "Eerder",
    "Je account is gewijzigd. Ga terug naar de Community om verder te gaan.",
    "Beperk de tekst tot 1200 tekens. Je tekst blijft behouden.",
  ],
  "uk": [
    "Огляд",
    "Фотографії допису",
    "Головна",
    "Незавершені приватні дописи",
    "Зберегти профіль і створити код BIL",
    "Увійдіть, щоб відкрити свої приватні чернетки.",
    "Дозволи на дії тренера",
    "Статистика",
    "Фото: {count}",
    "Схвалення",
    "Видалити чернетки: {count}?",
    "Видалити вибрані ({count})",
    "Дії з чернеткою",
    "Чернетки ({count})",
    "Останнє збереження: {count} дн. тому",
    "Останнє збереження: {count} год тому",
    "Останнє збереження: {count} хв тому",
    "Згадки",
    "Тут з’являться нові схвалення, згадки та коментарі.",
    "Збережених чернеток ще немає",
    "Налаштування сповіщень",
    "Сповіщення недоступні",
    "Зараз",
    "Нагороду додано до вашого балансу ШІ",
    "Зберігайте незавершені дописи й продовжуйте їх тут пізніше.",
    "Щойно збережено",
    "Вибрати",
    "Буде видалено лише вибрані приватні чернетки.",
    "Ви переглянули всі нові сповіщення",
    "Раніше",
    "Обліковий запис змінився. Поверніться до спільноти, щоб продовжити.",
    "Обмежте текст 1200 символами. Ваш текст збережено.",
  ],
};
