import 'package:flutter/widgets.dart';
import 'package:intl/intl.dart';

import 'bil_locale_policy.dart';

/// Reviewed copy owned by the scheduled nutrition-goal editor.
///
/// Rows are positional so a missing label cannot silently fall back to
/// English in any of BIL's 25 production locales.
abstract final class NutritionGoalScheduleRuntimeCopy {
  static const scheduledGoals = 'Scheduled goals';
  static const goalsUnavailable = 'Goals unavailable';
  static const differentGoalsByDay = 'Different goals by day';
  static const goalsByMeal = 'Goals by meal';
  static const useDefaultGoal = 'Use default goal';
  static const useDefault = 'Use default';
  static const editGoal = 'Edit goal';
  static const calories = 'Calories';
  static const carbohydratesGrams = 'Carbohydrates (g)';
  static const proteinGrams = 'Protein (g)';
  static const fatGrams = 'Fat (g)';
  static const enterValidNumbers = 'Enter valid numbers';
  static const macroGramsMustMatchCalories = 'Macro grams must match calories';
  static const goalCouldNotBeSaved =
      'Could not save the goal. Your previous goal is unchanged.';
  static const save = 'Save';
  static const breakfast = 'Breakfast';
  static const lunch = 'Lunch';
  static const dinner = 'Dinner';
  static const snack = 'Snack';
  static const goalSummary =
      '{calories} kcal · {carbs} g C · {protein} g P · {fat} g F';

  static const sources = <String>[
    scheduledGoals,
    goalsUnavailable,
    differentGoalsByDay,
    goalsByMeal,
    useDefaultGoal,
    useDefault,
    editGoal,
    calories,
    carbohydratesGrams,
    proteinGrams,
    fatGrams,
    enterValidNumbers,
    macroGramsMustMatchCalories,
    goalCouldNotBeSaved,
    save,
    breakfast,
    lunch,
    dinner,
    snack,
    goalSummary,
  ];

  static const supported = BilLocalePolicy.productionTags;

  static const rows = <String, List<String>>{
    'ar': <String>[
      'الأهداف المجدولة',
      'تعذر عرض الأهداف',
      'أهداف مختلفة حسب اليوم',
      'الأهداف حسب الوجبة',
      'استخدام الهدف الافتراضي',
      'استخدام الافتراضي',
      'تعديل الهدف',
      'السعرات',
      'الكربوهيدرات (غ)',
      'البروتين (غ)',
      'الدهون (غ)',
      'أدخل أرقامًا صحيحة',
      'يجب أن تتوافق غرامات المغذيات الكبرى مع السعرات',
      'تعذر حفظ الهدف. لم يتغير هدفك السابق.',
      'حفظ',
      'الإفطار',
      'الغداء',
      'العشاء',
      'وجبة خفيفة',
      '{calories} سعرة · {carbs} غ ك · {protein} غ ب · {fat} غ د',
    ],
    'en': <String>[
      scheduledGoals,
      goalsUnavailable,
      differentGoalsByDay,
      goalsByMeal,
      useDefaultGoal,
      useDefault,
      editGoal,
      calories,
      carbohydratesGrams,
      proteinGrams,
      fatGrams,
      enterValidNumbers,
      macroGramsMustMatchCalories,
      goalCouldNotBeSaved,
      save,
      breakfast,
      lunch,
      dinner,
      snack,
      goalSummary,
    ],
    'fr': <String>[
      'Objectifs planifiés',
      'Objectifs indisponibles',
      'Objectifs selon le jour',
      'Objectifs par repas',
      'Utiliser l’objectif par défaut',
      'Par défaut',
      'Modifier l’objectif',
      'Calories',
      'Glucides (g)',
      'Protéines (g)',
      'Lipides (g)',
      'Saisissez des nombres valides',
      'Les grammes des macronutriments doivent correspondre aux calories',
      'Impossible d’enregistrer l’objectif. L’objectif précédent est inchangé.',
      'Enregistrer',
      'Petit-déjeuner',
      'Déjeuner',
      'Dîner',
      'Collation',
      '{calories} kcal · {carbs} g G · {protein} g P · {fat} g L',
    ],
    'es': <String>[
      'Objetivos programados',
      'Objetivos no disponibles',
      'Objetivos según el día',
      'Objetivos por comida',
      'Usar objetivo predeterminado',
      'Usar predeterminado',
      'Editar objetivo',
      'Calorías',
      'Carbohidratos (g)',
      'Proteína (g)',
      'Grasa (g)',
      'Introduce números válidos',
      'Los gramos de macronutrientes deben coincidir con las calorías',
      'No se pudo guardar el objetivo. El objetivo anterior no cambió.',
      'Guardar',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Tentempié',
      '{calories} kcal · {carbs} g C · {protein} g P · {fat} g G',
    ],
    'tr': <String>[
      'Planlanmış hedefler',
      'Hedefler kullanılamıyor',
      'Güne göre farklı hedefler',
      'Öğün hedefleri',
      'Varsayılan hedefi kullan',
      'Varsayılanı kullan',
      'Hedefi düzenle',
      'Kalori',
      'Karbonhidrat (g)',
      'Protein (g)',
      'Yağ (g)',
      'Geçerli sayılar girin',
      'Makro gramları kalorilerle eşleşmelidir',
      'Hedef kaydedilemedi. Önceki hedefiniz değiştirilmedi.',
      'Kaydet',
      'Kahvaltı',
      'Öğle yemeği',
      'Akşam yemeği',
      'Ara öğün',
      '{calories} kcal · {carbs} g K · {protein} g P · {fat} g Y',
    ],
    'de': <String>[
      'Geplante Ziele',
      'Ziele nicht verfügbar',
      'Unterschiedliche Ziele nach Wochentag',
      'Ziele nach Mahlzeit',
      'Standardziel verwenden',
      'Standard verwenden',
      'Ziel bearbeiten',
      'Kalorien',
      'Kohlenhydrate (g)',
      'Protein (g)',
      'Fett (g)',
      'Geben Sie gültige Zahlen ein',
      'Die Makronährstoffmengen müssen den Kalorien entsprechen',
      'Das Ziel konnte nicht gespeichert werden. Ihr vorheriges Ziel bleibt unverändert.',
      'Speichern',
      'Frühstück',
      'Mittagessen',
      'Abendessen',
      'Snack',
      '{calories} kcal · {carbs} g KH · {protein} g P · {fat} g F',
    ],
    'it': <String>[
      'Obiettivi programmati',
      'Obiettivi non disponibili',
      'Obiettivi diversi per giorno',
      'Obiettivi per pasto',
      'Usa obiettivo predefinito',
      'Usa predefinito',
      'Modifica obiettivo',
      'Calorie',
      'Carboidrati (g)',
      'Proteine (g)',
      'Grassi (g)',
      'Inserisci numeri validi',
      'I grammi dei macronutrienti devono corrispondere alle calorie',
      'Impossibile salvare l’obiettivo. L’obiettivo precedente non è stato modificato.',
      'Salva',
      'Colazione',
      'Pranzo',
      'Cena',
      'Spuntino',
      '{calories} kcal · {carbs} g C · {protein} g P · {fat} g G',
    ],
    'pt-BR': <String>[
      'Metas programadas',
      'Metas indisponíveis',
      'Metas diferentes por dia',
      'Metas por refeição',
      'Usar meta padrão',
      'Usar padrão',
      'Editar meta',
      'Calorias',
      'Carboidratos (g)',
      'Proteínas (g)',
      'Gorduras (g)',
      'Insira números válidos',
      'Os gramas de macronutrientes devem corresponder às calorias',
      'Não foi possível salvar a meta. Sua meta anterior não foi alterada.',
      'Salvar',
      'Café da manhã',
      'Almoço',
      'Jantar',
      'Lanche',
      '{calories} kcal · {carbs} g C · {protein} g P · {fat} g G',
    ],
    'pt-PT': <String>[
      'Objetivos programados',
      'Objetivos indisponíveis',
      'Objetivos diferentes por dia',
      'Objetivos por refeição',
      'Usar objetivo predefinido',
      'Usar predefinição',
      'Editar objetivo',
      'Calorias',
      'Hidratos de carbono (g)',
      'Proteínas (g)',
      'Gorduras (g)',
      'Introduza números válidos',
      'Os gramas de macronutrientes devem corresponder às calorias',
      'Não foi possível guardar o objetivo. O objetivo anterior não foi alterado.',
      'Guardar',
      'Pequeno-almoço',
      'Almoço',
      'Jantar',
      'Lanche',
      '{calories} kcal · {carbs} g HC · {protein} g P · {fat} g G',
    ],
    'ur': <String>[
      'طے شدہ اہداف',
      'اہداف دستیاب نہیں ہیں',
      'دن کے لحاظ سے مختلف اہداف',
      'کھانے کے لحاظ سے اہداف',
      'پہلے سے طے شدہ ہدف استعمال کریں',
      'پہلے سے طے شدہ استعمال کریں',
      'ہدف میں ترمیم کریں',
      'کیلوریز',
      'کاربوہائیڈریٹس (گرام)',
      'پروٹین (گرام)',
      'چکنائی (گرام)',
      'درست اعداد درج کریں',
      'میکرو غذائی اجزا کے گرام کیلوریز کے مطابق ہونے چاہییں',
      'ہدف محفوظ نہیں ہو سکا۔ آپ کا پچھلا ہدف تبدیل نہیں ہوا۔',
      'محفوظ کریں',
      'ناشتہ',
      'دوپہر کا کھانا',
      'رات کا کھانا',
      'ہلکا کھانا',
      '{calories} کلو کیلوری · {carbs} گرام کارب · {protein} گرام پروٹین · {fat} گرام چکنائی',
    ],
    'fa': <String>[
      'اهداف زمان‌بندی‌شده',
      'اهداف در دسترس نیستند',
      'اهداف متفاوت برای هر روز',
      'اهداف بر اساس وعده',
      'استفاده از هدف پیش‌فرض',
      'استفاده از پیش‌فرض',
      'ویرایش هدف',
      'کالری',
      'کربوهیدرات (گرم)',
      'پروتئین (گرم)',
      'چربی (گرم)',
      'عددهای معتبر وارد کنید',
      'گرم‌های درشت‌مغذی باید با کالری‌ها مطابقت داشته باشند',
      'هدف ذخیره نشد. هدف قبلی شما بدون تغییر ماند.',
      'ذخیره',
      'صبحانه',
      'ناهار',
      'شام',
      'میان‌وعده',
      '{calories} کیلوکالری · {carbs} گرم کربوهیدرات · {protein} گرم پروتئین · {fat} گرم چربی',
    ],
    'hi': <String>[
      'निर्धारित लक्ष्य',
      'लक्ष्य उपलब्ध नहीं हैं',
      'दिन के अनुसार अलग लक्ष्य',
      'भोजन के अनुसार लक्ष्य',
      'डिफ़ॉल्ट लक्ष्य का उपयोग करें',
      'डिफ़ॉल्ट का उपयोग करें',
      'लक्ष्य संपादित करें',
      'कैलोरी',
      'कार्बोहाइड्रेट (ग्रा)',
      'प्रोटीन (ग्रा)',
      'वसा (ग्रा)',
      'मान्य संख्याएँ दर्ज करें',
      'मैक्रो के ग्राम कैलोरी से मेल खाने चाहिए',
      'लक्ष्य सेव नहीं हो सका। आपका पिछला लक्ष्य नहीं बदला है।',
      'सेव करें',
      'नाश्ता',
      'दोपहर का भोजन',
      'रात का भोजन',
      'अल्पाहार',
      '{calories} किलो कैलोरी · {carbs} ग्रा कार्ब · {protein} ग्रा प्रोटीन · {fat} ग्रा वसा',
    ],
    'id': <String>[
      'Target terjadwal',
      'Target tidak tersedia',
      'Target berbeda menurut hari',
      'Target menurut waktu makan',
      'Gunakan target default',
      'Gunakan default',
      'Edit target',
      'Kalori',
      'Karbohidrat (g)',
      'Protein (g)',
      'Lemak (g)',
      'Masukkan angka yang valid',
      'Gram makro harus sesuai dengan kalori',
      'Target tidak dapat disimpan. Target sebelumnya tidak berubah.',
      'Simpan',
      'Sarapan',
      'Makan siang',
      'Makan malam',
      'Camilan',
      '{calories} kkal · {carbs} g K · {protein} g P · {fat} g L',
    ],
    'ms': <String>[
      'Matlamat berjadual',
      'Matlamat tidak tersedia',
      'Matlamat berbeza mengikut hari',
      'Matlamat mengikut waktu makan',
      'Gunakan matlamat lalai',
      'Gunakan lalai',
      'Edit matlamat',
      'Kalori',
      'Karbohidrat (g)',
      'Protein (g)',
      'Lemak (g)',
      'Masukkan nombor yang sah',
      'Gram makro mesti sepadan dengan kalori',
      'Matlamat tidak dapat disimpan. Matlamat sebelumnya tidak berubah.',
      'Simpan',
      'Sarapan',
      'Makan tengah hari',
      'Makan malam',
      'Snek',
      '{calories} kcal · {carbs} g K · {protein} g P · {fat} g L',
    ],
    'ja': <String>[
      'スケジュール済みの目標',
      '目標を利用できません',
      '曜日ごとに異なる目標',
      '食事ごとの目標',
      'デフォルトの目標を使用',
      'デフォルトを使用',
      '目標を編集',
      'カロリー',
      '炭水化物（g）',
      'たんぱく質（g）',
      '脂質（g）',
      '有効な数値を入力してください',
      'マクロ栄養素のグラム数をカロリーと一致させてください',
      '目標を保存できませんでした。以前の目標は変更されていません。',
      '保存',
      '朝食',
      '昼食',
      '夕食',
      '間食',
      '{calories} kcal · 炭水化物 {carbs} g · たんぱく質 {protein} g · 脂質 {fat} g',
    ],
    'ko': <String>[
      '예약된 목표',
      '목표를 사용할 수 없음',
      '요일별 목표',
      '식사별 목표',
      '기본 목표 사용',
      '기본값 사용',
      '목표 편집',
      '칼로리',
      '탄수화물(g)',
      '단백질(g)',
      '지방(g)',
      '올바른 숫자를 입력하세요',
      '매크로 영양소의 그램 합계가 칼로리와 일치해야 합니다',
      '목표를 저장하지 못했습니다. 이전 목표는 변경되지 않았습니다.',
      '저장',
      '아침 식사',
      '점심',
      '저녁 식사',
      '간식',
      '{calories} kcal · 탄수화물 {carbs} g · 단백질 {protein} g · 지방 {fat} g',
    ],
    'zh-Hans': <String>[
      '计划目标',
      '目标不可用',
      '按日期设置不同目标',
      '按餐次设置目标',
      '使用默认目标',
      '使用默认值',
      '编辑目标',
      '热量',
      '碳水化合物（克）',
      '蛋白质（克）',
      '脂肪（克）',
      '请输入有效数字',
      '宏量营养素克数必须与热量相符',
      '无法保存目标。之前的目标未更改。',
      '保存',
      '早餐',
      '午餐',
      '晚餐',
      '加餐',
      '{calories} 千卡 · 碳水 {carbs} 克 · 蛋白质 {protein} 克 · 脂肪 {fat} 克',
    ],
    'zh-Hant': <String>[
      '排定目標',
      '無法使用目標',
      '依日期設定不同目標',
      '依餐次設定目標',
      '使用預設目標',
      '使用預設值',
      '編輯目標',
      '熱量',
      '碳水化合物（克）',
      '蛋白質（克）',
      '脂肪（克）',
      '請輸入有效數字',
      '巨量營養素克數必須與熱量相符',
      '無法儲存目標。先前的目標未變更。',
      '儲存',
      '早餐',
      '午餐',
      '晚餐',
      '點心',
      '{calories} 大卡 · 碳水 {carbs} 克 · 蛋白質 {protein} 克 · 脂肪 {fat} 克',
    ],
    'ru': <String>[
      'Запланированные цели',
      'Цели недоступны',
      'Разные цели по дням',
      'Цели по приёмам пищи',
      'Использовать цель по умолчанию',
      'Использовать по умолчанию',
      'Изменить цель',
      'Калории',
      'Углеводы (г)',
      'Белки (г)',
      'Жиры (г)',
      'Введите допустимые числа',
      'Количество макронутриентов в граммах должно соответствовать калориям',
      'Не удалось сохранить цель. Предыдущая цель не изменилась.',
      'Сохранить',
      'Завтрак',
      'Обед',
      'Ужин',
      'Перекус',
      '{calories} ккал · {carbs} г У · {protein} г Б · {fat} г Ж',
    ],
    'bn': <String>[
      'নির্ধারিত লক্ষ্য',
      'লক্ষ্য পাওয়া যাচ্ছে না',
      'দিন অনুযায়ী ভিন্ন লক্ষ্য',
      'খাবার অনুযায়ী লক্ষ্য',
      'ডিফল্ট লক্ষ্য ব্যবহার করুন',
      'ডিফল্ট ব্যবহার করুন',
      'লক্ষ্য সম্পাদনা করুন',
      'ক্যালোরি',
      'কার্বোহাইড্রেট (গ্রাম)',
      'প্রোটিন (গ্রাম)',
      'চর্বি (গ্রাম)',
      'সঠিক সংখ্যা লিখুন',
      'ম্যাক্রোর গ্রাম ক্যালোরির সঙ্গে মিলতে হবে',
      'লক্ষ্য সংরক্ষণ করা যায়নি। আপনার আগের লক্ষ্য অপরিবর্তিত আছে।',
      'সংরক্ষণ করুন',
      'সকালের নাস্তা',
      'দুপুরের খাবার',
      'রাতের খাবার',
      'জলখাবার',
      '{calories} কিলোক্যালোরি · {carbs} গ্রাম কার্ব · {protein} গ্রাম প্রোটিন · {fat} গ্রাম চর্বি',
    ],
    'vi': <String>[
      'Mục tiêu đã lên lịch',
      'Không thể tải mục tiêu',
      'Mục tiêu khác nhau theo ngày',
      'Mục tiêu theo bữa ăn',
      'Dùng mục tiêu mặc định',
      'Dùng mặc định',
      'Chỉnh sửa mục tiêu',
      'Calo',
      'Carbohydrate (g)',
      'Protein (g)',
      'Chất béo (g)',
      'Nhập số hợp lệ',
      'Số gam chất đa lượng phải khớp với lượng calo',
      'Không thể lưu mục tiêu. Mục tiêu trước đó của bạn không thay đổi.',
      'Lưu',
      'Bữa sáng',
      'Bữa trưa',
      'Bữa tối',
      'Bữa phụ',
      '{calories} kcal · {carbs} g C · {protein} g P · {fat} g B',
    ],
    'th': <String>[
      'เป้าหมายที่กำหนดเวลาไว้',
      'ไม่สามารถใช้เป้าหมายได้',
      'เป้าหมายที่ต่างกันในแต่ละวัน',
      'เป้าหมายตามมื้ออาหาร',
      'ใช้เป้าหมายเริ่มต้น',
      'ใช้ค่าเริ่มต้น',
      'แก้ไขเป้าหมาย',
      'แคลอรี',
      'คาร์โบไฮเดรต (กรัม)',
      'โปรตีน (กรัม)',
      'ไขมัน (กรัม)',
      'ป้อนตัวเลขที่ถูกต้อง',
      'กรัมของสารอาหารหลักต้องสอดคล้องกับแคลอรี',
      'บันทึกเป้าหมายไม่ได้ เป้าหมายก่อนหน้าของคุณไม่มีการเปลี่ยนแปลง',
      'บันทึก',
      'อาหารเช้า',
      'อาหารกลางวัน',
      'อาหารเย็น',
      'ของว่าง',
      '{calories} กิโลแคลอรี · คาร์บ {carbs} กรัม · โปรตีน {protein} กรัม · ไขมัน {fat} กรัม',
    ],
    'pl': <String>[
      'Zaplanowane cele',
      'Cele są niedostępne',
      'Różne cele w poszczególne dni',
      'Cele według posiłków',
      'Użyj celu domyślnego',
      'Użyj domyślnego',
      'Edytuj cel',
      'Kalorie',
      'Węglowodany (g)',
      'Białko (g)',
      'Tłuszcz (g)',
      'Wprowadź prawidłowe liczby',
      'Gramy makroskładników muszą odpowiadać kaloriom',
      'Nie udało się zapisać celu. Poprzedni cel nie został zmieniony.',
      'Zapisz',
      'Śniadanie',
      'Obiad',
      'Kolacja',
      'Przekąska',
      '{calories} kcal · {carbs} g W · {protein} g B · {fat} g T',
    ],
    'nl': <String>[
      'Geplande doelen',
      'Doelen niet beschikbaar',
      'Verschillende doelen per dag',
      'Doelen per maaltijd',
      'Standaarddoel gebruiken',
      'Standaard gebruiken',
      'Doel bewerken',
      'Calorieën',
      'Koolhydraten (g)',
      'Eiwit (g)',
      'Vet (g)',
      'Voer geldige getallen in',
      'De macrogrammen moeten overeenkomen met de calorieën',
      'Het doel kon niet worden opgeslagen. Uw vorige doel is niet gewijzigd.',
      'Opslaan',
      'Ontbijt',
      'Lunch',
      'Avondeten',
      'Tussendoortje',
      '{calories} kcal · {carbs} g KH · {protein} g E · {fat} g V',
    ],
    'uk': <String>[
      'Заплановані цілі',
      'Цілі недоступні',
      'Різні цілі за днями',
      'Цілі за прийомами їжі',
      'Використовувати типову ціль',
      'Використовувати типове значення',
      'Редагувати ціль',
      'Калорії',
      'Вуглеводи (г)',
      'Білки (г)',
      'Жири (г)',
      'Введіть припустимі числа',
      'Кількість макронутрієнтів у грамах має відповідати калоріям',
      'Не вдалося зберегти ціль. Попередня ціль не змінилася.',
      'Зберегти',
      'Сніданок',
      'Обід',
      'Вечеря',
      'Перекус',
      '{calories} ккал · {carbs} г В · {protein} г Б · {fat} г Ж',
    ],
  };

  static String? resolve(String source, String localeTag) {
    final index = sources.indexOf(source);
    if (index < 0) return null;
    final tag = BilLocalePolicy.canonicalSupportedTag(localeTag);
    if (tag == null) return null;
    final row = rows[tag];
    if (row == null || row.length != sources.length) {
      throw StateError('Missing scheduled-goal copy for $tag.');
    }
    return row[index];
  }

  static String text(String source, Locale locale) =>
      resolve(source, BilLocalePolicy.canonicalTag(locale)) ?? source;

  static String formatGoalSummary({
    required Locale locale,
    required num calories,
    required num carbs,
    required num protein,
    required num fat,
  }) => text(goalSummary, locale)
      .replaceAll('{calories}', formatNumber(calories, locale, maxDigits: 0))
      .replaceAll('{carbs}', formatNumber(carbs, locale))
      .replaceAll('{protein}', formatNumber(protein, locale))
      .replaceAll('{fat}', formatNumber(fat, locale));

  static String formatNumber(num value, Locale locale, {int maxDigits = 1}) {
    final digits = maxDigits == 0 || (value - value.round()).abs() < 0.05
        ? 0
        : maxDigits;
    return NumberFormat.decimalPatternDigits(
      locale: BilLocalePolicy.canonicalTag(locale),
      decimalDigits: digits,
    ).format(value);
  }

  static bool get balanced =>
      supported.length == 25 &&
      rows.keys.toSet().containsAll(supported) &&
      supported.containsAll(rows.keys) &&
      rows.values.every(
        (row) =>
            row.length == sources.length &&
            row.every((value) => value.trim().isNotEmpty) &&
            _samePlaceholders(row.last, goalSummary),
      ) &&
      _sameValues(rows['en'], sources);

  static bool _sameValues(List<String>? left, List<String> right) {
    if (left == null || left.length != right.length) return false;
    for (var index = 0; index < right.length; index++) {
      if (left[index] != right[index]) return false;
    }
    return true;
  }

  static bool _samePlaceholders(String localized, String source) {
    final pattern = RegExp(r'\{[^}]+\}');
    final localizedTokens = pattern
        .allMatches(localized)
        .map((match) => match.group(0))
        .toSet();
    final sourceTokens = pattern
        .allMatches(source)
        .map((match) => match.group(0))
        .toSet();
    return localizedTokens.length == sourceTokens.length &&
        localizedTokens.containsAll(sourceTokens);
  }
}
