part of 'runtime_copy_community_reference.dart';

const _communityReferenceEuropeRows = <String, List<String>>{
  "pt-BR": <String>[
    "Adicionar hashtag",
    "Adicione algo antes de salvar um rascunho.",
    "Adicione até 10 hashtags pesquisáveis.",
    "Valorizado",
    "Momentos aprovados",
    "Perfil da Comunidade BIL",
    "O BIL voltará para a capa da Comunidade com a identidade da marca.",
    "Selos",
    "Certificação",
    "Certificação revogada",
    "Criador certificado",
    "Escolha uma imagem JPEG, PNG ou WebP válida de até 5 MB.",
    "Colaboração aceita.",
    "Colaboração recusada.",
    "Convite para colaboração",
    "Convite para colaboração aceito",
    "Colaboração — opcional",
    "Comentários recebidos",
    "Selos da Comunidade",
    "Construtor da comunidade",
    "Início da Comunidade",
    "Conector",
    "Colaborador",
    "Iniciador de conversas",
    "Não foi possível excluir este rascunho.",
    "Não foi possível abrir o compartilhamento agora.",
    "Não foi possível abrir este rascunho. Tente novamente.",
    "Não foi possível remover a capa do perfil.",
    "Não foi possível salvar este rascunho. Nada foi publicado.",
    "Não foi possível pesquisar colaboradores agora.",
    "Não foi possível atualizar o status de seguir.",
    "Não foi possível atualizar a capa do perfil.",
    "Não foi possível atualizar esta colaboração. Tente novamente.",
    "Central do Criador",
    "Recompensas do Criador",
    "Ferramentas do criador",
    "Recusada",
    "Excluir rascunho",
    "Rascunho salvo com segurança.",
    "Rascunhos",
    "Primeiro momento",
    "Segue você",
    "Dê um título claro a este momento",
    "Hashtags — opcional",
    "Convide até 3 membros da Comunidade. Os convites só são enviados após aprovação humana, e um colaborador só aparece publicamente depois de aceitar.",
    "Curtidas recebidas",
    "Bloqueado",
    "Momentos",
    "Os momentos são privados neste perfil.",
    "Novos seguidores",
    "Nenhuma certificação de criador BIL foi concedida a este perfil.",
    "Ainda não há avaliações aprovadas.",
    "Ainda não há rascunhos salvos.",
    "Ainda não há momentos visíveis.",
    "Não certificado",
    "Abrir",
    "Rascunho com foto",
    "Capa do perfil atualizada.",
    "Publicado",
    "Indicações qualificadas",
    "Remover a capa do perfil?",
    "Avaliações",
    "As avaliações são privadas neste perfil.",
    "Salvar rascunho",
    "Salve publicações inacabadas da Comunidade e continue mais tarde.",
    "Rascunho da Comunidade salvo",
    "Rascunho salvo",
    "Pesquisar por nome ou @identificador",
    "Pesquisar colaboradores",
    "Compartilhar perfil",
    "Central de Tarefas",
    "A transcrição de voz excederia o limite de 1200 caracteres da publicação.",
    "Este Círculo não está disponível agora.",
    "Esta certificação é verificada pela autoridade do servidor BIL.",
    "Este perfil não possui uma certificação ativa no momento.",
    "Este tópico não está disponível agora.",
    "Título",
    "Rascunho sem título",
    "Atualizar rascunho",
    "Atualizações",
    "Use uma única hashtag sem espaços, com até 40 caracteres.",
    "Com",
    "Você pode adicionar até 10 hashtags.",
    "{actor} aceitou seu convite para colaborar",
    "{actor} convidou você para colaborar em uma publicação",
    "Nível máximo configurado da Comunidade alcançado",
    "{xp} XP · Próximo: Nv. {level} com {target} XP",
    "Progresso para o Nv. {level} · meta de {target} XP",
  ],
  "pt-PT": <String>[
    "Adicionar hashtag",
    "Adicione algo antes de guardar um rascunho.",
    "Adicione até 10 hashtags pesquisáveis.",
    "Valorizado",
    "Momentos aprovados",
    "Perfil da Comunidade BIL",
    "O BIL regressará à capa da Comunidade com a identidade da marca.",
    "Distintivos",
    "Certificação",
    "Certificação revogada",
    "Criador certificado",
    "Escolha uma imagem JPEG, PNG ou WebP válida até 5 MB.",
    "Colaboração aceite.",
    "Colaboração recusada.",
    "Convite para colaboração",
    "Convite para colaboração aceite",
    "Colaboração — opcional",
    "Comentários recebidos",
    "Distintivos da Comunidade",
    "Construtor da comunidade",
    "Início da Comunidade",
    "Conector",
    "Colaborador",
    "Iniciador de conversas",
    "Não foi possível eliminar este rascunho.",
    "Não foi possível abrir a partilha neste momento.",
    "Não foi possível abrir este rascunho. Tente novamente.",
    "Não foi possível remover a capa do perfil.",
    "Não foi possível guardar este rascunho. Nada foi publicado.",
    "Não foi possível pesquisar colaboradores neste momento.",
    "Não foi possível atualizar o estado de seguimento.",
    "Não foi possível atualizar a capa do perfil.",
    "Não foi possível atualizar esta colaboração. Tente novamente.",
    "Centro do Criador",
    "Recompensas do Criador",
    "Ferramentas do criador",
    "Recusada",
    "Eliminar rascunho",
    "Rascunho guardado em segurança.",
    "Rascunhos",
    "Primeiro momento",
    "Segue-o",
    "Dê um título claro a este momento",
    "Hashtags — opcional",
    "Convide até 3 membros da Comunidade. Os convites só são enviados após aprovação humana, e um colaborador só aparece publicamente depois de aceitar.",
    "Gostos recebidos",
    "Bloqueado",
    "Momentos",
    "Os momentos são privados neste perfil.",
    "Novos seguidores",
    "Não foi concedida a este perfil qualquer certificação de criador BIL.",
    "Ainda não existem avaliações aprovadas.",
    "Ainda não existem rascunhos guardados.",
    "Ainda não existem momentos visíveis.",
    "Não certificado",
    "Abrir",
    "Rascunho com fotografia",
    "Capa do perfil atualizada.",
    "Publicado",
    "Referências qualificadas",
    "Remover a capa do perfil?",
    "Avaliações",
    "As avaliações são privadas neste perfil.",
    "Guardar rascunho",
    "Guarde publicações inacabadas da Comunidade e continue mais tarde.",
    "Rascunho da Comunidade guardado",
    "Rascunho guardado",
    "Pesquisar por nome ou @identificador",
    "Pesquisar colaboradores",
    "Partilhar perfil",
    "Centro de Tarefas",
    "A transcrição de voz excederia o limite de 1200 caracteres da publicação.",
    "Este Círculo não está disponível neste momento.",
    "Esta certificação é verificada pela autoridade do servidor BIL.",
    "Este perfil não possui atualmente uma certificação ativa.",
    "Este tópico não está disponível neste momento.",
    "Título",
    "Rascunho sem título",
    "Atualizar rascunho",
    "Atualizações",
    "Use uma única hashtag sem espaços, até 40 caracteres.",
    "Com",
    "Pode adicionar até 10 hashtags.",
    "{actor} aceitou o seu convite para colaborar",
    "{actor} convidou-o a colaborar numa publicação",
    "Nível máximo configurado da Comunidade alcançado",
    "{xp} XP · Seguinte: Nv. {level} aos {target} XP",
    "Progresso para o Nv. {level} · objetivo de {target} XP",
  ],
  "ru": <String>[
    "Добавить хэштег",
    "Добавьте что-нибудь перед сохранением черновика.",
    "Добавьте до 10 доступных для поиска хэштегов.",
    "Ценимый участник",
    "Одобренные моменты",
    "Профиль сообщества BIL",
    "BIL вернёт фирменную обложку сообщества.",
    "Значки",
    "Сертификация",
    "Сертификация отозвана",
    "Сертифицированный автор",
    "Выберите корректное изображение JPEG, PNG или WebP размером до 5 МБ.",
    "Сотрудничество принято.",
    "Сотрудничество отклонено.",
    "Приглашение к сотрудничеству",
    "Приглашение к сотрудничеству принято",
    "Сотрудничество — необязательно",
    "Полученные комментарии",
    "Значки сообщества",
    "Создатель сообщества",
    "Главная сообщества",
    "Связующее звено",
    "Участник",
    "Инициатор обсуждений",
    "Не удалось удалить этот черновик.",
    "Сейчас не удалось открыть меню публикации.",
    "Не удалось открыть этот черновик. Повторите попытку.",
    "Не удалось удалить обложку профиля.",
    "Не удалось сохранить этот черновик. Ничего не опубликовано.",
    "Сейчас не удалось найти соавторов.",
    "Не удалось обновить статус подписки.",
    "Не удалось обновить обложку профиля.",
    "Не удалось обновить это сотрудничество. Повторите попытку.",
    "Центр авторов",
    "Награды авторов",
    "Инструменты автора",
    "Отклонено",
    "Удалить черновик",
    "Черновик надёжно сохранён.",
    "Черновики",
    "Первый момент",
    "Подписан на вас",
    "Дайте этому моменту понятный заголовок",
    "Хэштеги — необязательно",
    "Пригласите до 3 участников сообщества. Приглашения отправляются только после проверки человеком, а соавтор появляется публично только после принятия.",
    "Полученные отметки «Нравится»",
    "Заблокировано",
    "Моменты",
    "Моменты в этом профиле скрыты.",
    "Новые подписчики",
    "Этому профилю не предоставлена сертификация автора BIL.",
    "Одобренных отзывов пока нет.",
    "Сохранённых черновиков пока нет.",
    "Видимых моментов пока нет.",
    "Не сертифицирован",
    "Открыть",
    "Фоточерновик",
    "Обложка профиля обновлена.",
    "Опубликовано",
    "Квалифицированные приглашения",
    "Удалить обложку профиля?",
    "Отзывы",
    "Отзывы в этом профиле скрыты.",
    "Сохранить черновик",
    "Сохраняйте незавершённые публикации сообщества и продолжайте позже.",
    "Сохранённый черновик сообщества",
    "Сохранённый черновик",
    "Поиск по имени или @имени",
    "Найти соавторов",
    "Поделиться профилем",
    "Центр заданий",
    "Распознанный голосовой текст превысит лимит публикации в 1200 символов.",
    "Этот круг сейчас недоступен.",
    "Эта сертификация подтверждена серверной системой BIL.",
    "У этого профиля сейчас нет активной сертификации.",
    "Эта тема сейчас недоступна.",
    "Заголовок",
    "Черновик без заголовка",
    "Обновить черновик",
    "Обновления",
    "Используйте один хэштег без пробелов длиной до 40 символов.",
    "С",
    "Можно добавить до 10 хэштегов.",
    "{actor} принял ваше приглашение к сотрудничеству",
    "{actor} пригласил вас стать соавтором публикации",
    "Достигнут максимальный настроенный уровень сообщества",
    "{xp} XP · Далее: ур. {level} при {target} XP",
    "Прогресс к ур. {level} · цель {target} XP",
  ],
  "pl": <String>[
    "Dodaj hashtag",
    "Dodaj coś przed zapisaniem wersji roboczej.",
    "Dodaj maksymalnie 10 wyszukiwalnych hashtagów.",
    "Doceniany",
    "Zatwierdzone momenty",
    "Profil Społeczności BIL",
    "BIL przywróci markową okładkę Społeczności.",
    "Odznaki",
    "Certyfikacja",
    "Certyfikacja cofnięta",
    "Certyfikowany twórca",
    "Wybierz prawidłowy obraz JPEG, PNG lub WebP o rozmiarze do 5 MB.",
    "Współpraca zaakceptowana.",
    "Współpraca odrzucona.",
    "Zaproszenie do współpracy",
    "Zaproszenie do współpracy zaakceptowane",
    "Współpraca — opcjonalnie",
    "Otrzymane komentarze",
    "Odznaki Społeczności",
    "Budowniczy społeczności",
    "Strona główna Społeczności",
    "Łącznik",
    "Współtwórca",
    "Inicjator rozmów",
    "Nie udało się usunąć tej wersji roboczej.",
    "Nie można teraz otworzyć udostępniania.",
    "Nie udało się otworzyć tej wersji roboczej. Spróbuj ponownie.",
    "Nie udało się usunąć okładki profilu.",
    "Nie udało się zapisać tej wersji roboczej. Nic nie opublikowano.",
    "Nie można teraz wyszukać współtwórców.",
    "Nie udało się zaktualizować stanu obserwowania.",
    "Nie udało się zaktualizować okładki profilu.",
    "Nie udało się zaktualizować tej współpracy. Spróbuj ponownie.",
    "Centrum twórcy",
    "Nagrody twórcy",
    "Narzędzia twórcy",
    "Odrzucono",
    "Usuń wersję roboczą",
    "Wersja robocza została bezpiecznie zapisana.",
    "Wersje robocze",
    "Pierwszy moment",
    "Obserwuje Cię",
    "Nadaj temu momentowi jasny tytuł",
    "Hashtagi — opcjonalnie",
    "Zaproś do 3 członków Społeczności. Zaproszenia są wysyłane dopiero po weryfikacji przez człowieka, a współtwórca jest widoczny publicznie dopiero po zaakceptowaniu.",
    "Otrzymane polubienia",
    "Zablokowano",
    "Momenty",
    "Momenty są prywatne w tym profilu.",
    "Nowi obserwujący",
    "Ten profil nie otrzymał certyfikacji twórcy BIL.",
    "Nie ma jeszcze zatwierdzonych recenzji.",
    "Nie ma jeszcze zapisanych wersji roboczych.",
    "Nie ma jeszcze widocznych momentów.",
    "Brak certyfikacji",
    "Otwórz",
    "Wersja robocza ze zdjęciem",
    "Okładka profilu została zaktualizowana.",
    "Opublikowano",
    "Zakwalifikowane polecenia",
    "Usunąć okładkę profilu?",
    "Recenzje",
    "Recenzje są prywatne w tym profilu.",
    "Zapisz wersję roboczą",
    "Zapisuj niedokończone posty Społeczności i wracaj do nich później.",
    "Zapisana wersja robocza Społeczności",
    "Zapisana wersja robocza",
    "Szukaj po nazwie lub @identyfikatorze",
    "Szukaj współtwórców",
    "Udostępnij profil",
    "Centrum zadań",
    "Transkrypcja głosowa przekroczyłaby limit 1200 znaków posta.",
    "Ten Krąg jest teraz niedostępny.",
    "Ta certyfikacja została zweryfikowana przez system serwerowy BIL.",
    "Ten profil nie ma obecnie aktywnej certyfikacji.",
    "Ten temat jest teraz niedostępny.",
    "Tytuł",
    "Wersja robocza bez tytułu",
    "Zaktualizuj wersję roboczą",
    "Aktualizacje",
    "Użyj jednego hashtagu bez spacji, maksymalnie 40 znaków.",
    "Z",
    "Możesz dodać maksymalnie 10 hashtagów.",
    "{actor} zaakceptował Twoje zaproszenie do współpracy",
    "{actor} zaprosił Cię do współpracy nad postem",
    "Osiągnięto najwyższy skonfigurowany poziom Społeczności",
    "{xp} XP · Następny: poz. {level} przy {target} XP",
    "Postęp do poz. {level} · cel {target} XP",
  ],
  "nl": <String>[
    "Hashtag toevoegen",
    "Voeg iets toe voordat je een concept opslaat.",
    "Voeg maximaal 10 doorzoekbare hashtags toe.",
    "Gewaardeerd",
    "Goedgekeurde momenten",
    "BIL Community-profiel",
    "BIL keert terug naar de Community-omslag in de merkstijl.",
    "Insignes",
    "Certificering",
    "Certificering ingetrokken",
    "Gecertificeerde maker",
    "Kies een geldige JPEG-, PNG- of WebP-afbeelding van maximaal 5 MB.",
    "Samenwerking geaccepteerd.",
    "Samenwerking afgewezen.",
    "Uitnodiging voor samenwerking",
    "Uitnodiging voor samenwerking geaccepteerd",
    "Samenwerking — optioneel",
    "Ontvangen reacties",
    "Community-badges",
    "Communitybouwer",
    "Community-startpagina",
    "Verbinder",
    "Bijdrager",
    "Gespreksstarter",
    "Dit concept kon niet worden verwijderd.",
    "Delen kan nu niet worden geopend.",
    "Dit concept kon niet worden geopend. Probeer het opnieuw.",
    "De profielomslag kon niet worden verwijderd.",
    "Dit concept kon niet worden opgeslagen. Er is niets gepubliceerd.",
    "Er kan nu niet naar medewerkers worden gezocht.",
    "De volgstatus kon niet worden bijgewerkt.",
    "De profielomslag kon niet worden bijgewerkt.",
    "Deze samenwerking kon niet worden bijgewerkt. Probeer het opnieuw.",
    "Creatorcentrum",
    "Creatorbeloningen",
    "Creatortools",
    "Afgewezen",
    "Concept verwijderen",
    "Concept veilig opgeslagen.",
    "Concepten",
    "Eerste moment",
    "Volgt jou",
    "Geef dit moment een duidelijke titel",
    "Hashtags — optioneel",
    "Nodig maximaal 3 Community-leden uit. Uitnodigingen worden pas na menselijke goedkeuring verzonden en een medewerker verschijnt pas openbaar na acceptatie.",
    "Ontvangen likes",
    "Vergrendeld",
    "Momenten",
    "Momenten zijn privé op dit profiel.",
    "Nieuwe volgers",
    "Dit profiel heeft geen BIL-creatorcertificering gekregen.",
    "Nog geen goedgekeurde beoordelingen.",
    "Nog geen opgeslagen concepten.",
    "Nog geen zichtbare momenten.",
    "Niet gecertificeerd",
    "Openen",
    "Fotoconcept",
    "Profielomslag bijgewerkt.",
    "Gepubliceerd",
    "Gekwalificeerde verwijzingen",
    "Profielomslag verwijderen?",
    "Beoordelingen",
    "Beoordelingen zijn privé op dit profiel.",
    "Concept opslaan",
    "Sla onafgemaakte Community-berichten op en ga later verder.",
    "Opgeslagen Community-concept",
    "Opgeslagen concept",
    "Zoeken op naam of @gebruikersnaam",
    "Medewerkers zoeken",
    "Profiel delen",
    "Taakcentrum",
    "De spraaktranscriptie zou de limiet van 1200 tekens voor berichten overschrijden.",
    "Deze Circle is nu niet beschikbaar.",
    "Deze certificering is geverifieerd door de BIL-serverautoriteit.",
    "Dit profiel heeft momenteel geen actieve certificering.",
    "Dit onderwerp is nu niet beschikbaar.",
    "Titel",
    "Concept zonder titel",
    "Concept bijwerken",
    "Nieuwsoverzicht",
    "Gebruik één hashtag zonder spaties, maximaal 40 tekens.",
    "Met",
    "Je kunt maximaal 10 hashtags toevoegen.",
    "{actor} heeft je uitnodiging voor samenwerking geaccepteerd",
    "{actor} heeft je uitgenodigd om aan een bericht mee te werken",
    "Hoogste geconfigureerde Community-niveau bereikt",
    "{xp} XP · Volgende: niv. {level} bij {target} XP",
    "Voortgang naar niv. {level} · doel {target} XP",
  ],
  "uk": <String>[
    "Додати хештег",
    "Додайте щось перед збереженням чернетки.",
    "Додайте до 10 хештегів, доступних для пошуку.",
    "Цінований учасник",
    "Схвалені моменти",
    "Профіль Спільноти BIL",
    "BIL поверне фірмову обкладинку Спільноти.",
    "Відзнаки",
    "Сертифікація",
    "Сертифікацію відкликано",
    "Сертифікований автор",
    "Виберіть коректне зображення JPEG, PNG або WebP розміром до 5 МБ.",
    "Співпрацю прийнято.",
    "Співпрацю відхилено.",
    "Запрошення до співпраці",
    "Запрошення до співпраці прийнято",
    "Співпраця — необов’язково",
    "Отримані коментарі",
    "Відзнаки Спільноти",
    "Розбудовувач спільноти",
    "Головна Спільноти",
    "Об’єднувач",
    "Учасник",
    "Ініціатор розмов",
    "Не вдалося видалити цю чернетку.",
    "Не вдалося відкрити поширення зараз.",
    "Не вдалося відкрити цю чернетку. Спробуйте ще раз.",
    "Не вдалося видалити обкладинку профілю.",
    "Не вдалося зберегти цю чернетку. Нічого не опубліковано.",
    "Не вдалося знайти співавторів зараз.",
    "Не вдалося оновити стан підписки.",
    "Не вдалося оновити обкладинку профілю.",
    "Не вдалося оновити цю співпрацю. Спробуйте ще раз.",
    "Центр авторів",
    "Нагороди авторів",
    "Інструменти автора",
    "Відхилено",
    "Видалити чернетку",
    "Чернетку безпечно збережено.",
    "Чернетки",
    "Перший момент",
    "Підписаний на вас",
    "Дайте цьому моменту зрозумілий заголовок",
    "Хештеги — необов’язково",
    "Запросіть до 3 учасників Спільноти. Запрошення надсилаються лише після перевірки людиною, а співавтор з’являється публічно лише після прийняття.",
    "Отримані вподобання",
    "Заблоковано",
    "Моменти",
    "Моменти в цьому профілі приватні.",
    "Нові підписники",
    "Цьому профілю не надано сертифікацію автора BIL.",
    "Схвалених відгуків поки немає.",
    "Збережених чернеток поки немає.",
    "Видимих моментів поки немає.",
    "Не сертифіковано",
    "Відкрити",
    "Чернетка з фото",
    "Обкладинку профілю оновлено.",
    "Опубліковано",
    "Кваліфіковані запрошення",
    "Видалити обкладинку профілю?",
    "Відгуки",
    "Відгуки в цьому профілі приватні.",
    "Зберегти чернетку",
    "Зберігайте незавершені дописи Спільноти та продовжуйте пізніше.",
    "Збережена чернетка Спільноти",
    "Збережена чернетка",
    "Шукати за ім’ям або @ідентифікатором",
    "Шукати співавторів",
    "Поділитися профілем",
    "Центр завдань",
    "Розпізнаний голосовий текст перевищить ліміт допису в 1200 символів.",
    "Це Коло зараз недоступне.",
    "Цю сертифікацію підтверджено серверною системою BIL.",
    "Цей профіль зараз не має активної сертифікації.",
    "Ця тема зараз недоступна.",
    "Заголовок",
    "Чернетка без заголовка",
    "Оновити чернетку",
    "Оновлення",
    "Використовуйте один хештег без пробілів, до 40 символів.",
    "З",
    "Можна додати до 10 хештегів.",
    "{actor} прийняв ваше запрошення до співпраці",
    "{actor} запросив вас стати співавтором допису",
    "Досягнуто найвищого налаштованого рівня Спільноти",
    "{xp} XP · Далі: рів. {level} при {target} XP",
    "Прогрес до рів. {level} · ціль {target} XP",
  ],
};
