import 'bil_locale_policy.dart';

/// Authored copy for Community creation controls in all 25 release locales.
abstract final class CommunityCreationRuntimeCopy {
  static const sources = <String>[
    "Create a Post",
    "Add a title (optional)",
    "Share your thoughts, experience, or tips...\nWhat's on your mind?",
    "Add location",
    "Choose circles",
    "Mention people",
    "Add hashtags",
    "Add photos",
    "(optional)",
    "Could not open drafts. Try again.",
    "Your story",
    "AI Help",
  ];

  static const rows = <String, List<String>>{
    'en': sources,
    "ar": [
      "إنشاء منشور",
      "أضف عنوانًا (اختياري)",
      "شارك أفكارك أو تجربتك أو نصائحك...\nما الذي يشغل بالك؟",
      "إضافة موقع",
      "اختيار الدوائر",
      "الإشارة إلى أشخاص",
      "إضافة وسوم",
      "إضافة صور",
      "(اختياري)",
      "تعذر فتح المسودات. حاول مجددًا.",
      "قصتك",
      "مساعدة AI",
    ],
    "fr": [
      "Créer une publication",
      "Ajouter un titre (facultatif)",
      "Partagez vos idées, votre expérience ou vos conseils…\nÀ quoi pensez-vous ?",
      "Ajouter un lieu",
      "Choisir des cercles",
      "Mentionner des personnes",
      "Ajouter des hashtags",
      "Ajouter des photos",
      "(facultatif)",
      "Impossible d’ouvrir les brouillons. Réessayez.",
      "Votre story",
      "Aide IA",
    ],
    "es": [
      "Crear publicación",
      "Añade un título (opcional)",
      "Comparte tus ideas, experiencias o consejos…\n¿Qué tienes en mente?",
      "Añadir ubicación",
      "Elegir círculos",
      "Mencionar personas",
      "Añadir hashtags",
      "Añadir fotos",
      "(opcional)",
      "No se pudieron abrir los borradores. Inténtalo de nuevo.",
      "Tu historia",
      "Ayuda de IA",
    ],
    "tr": [
      "Gönderi oluştur",
      "Başlık ekleyin (isteğe bağlı)",
      "Düşüncelerinizi, deneyimlerinizi veya ipuçlarınızı paylaşın…\nAklınızda ne var?",
      "Konum ekle",
      "Çevreleri seç",
      "Kişilerden bahset",
      "Etiket ekle",
      "Fotoğraf ekle",
      "(isteğe bağlı)",
      "Taslaklar açılamadı. Tekrar deneyin.",
      "Hikâyen",
      "Yapay zekâ yardımı",
    ],
    "de": [
      "Beitrag erstellen",
      "Titel hinzufügen (optional)",
      "Teile deine Gedanken, Erfahrungen oder Tipps…\nWas beschäftigt dich?",
      "Ort hinzufügen",
      "Kreise auswählen",
      "Personen erwähnen",
      "Hashtags hinzufügen",
      "Fotos hinzufügen",
      "(optional)",
      "Entwürfe konnten nicht geöffnet werden. Versuche es erneut.",
      "Deine Story",
      "KI-Hilfe",
    ],
    "it": [
      "Crea un post",
      "Aggiungi un titolo (facoltativo)",
      "Condividi idee, esperienze o consigli…\nA cosa stai pensando?",
      "Aggiungi un luogo",
      "Scegli le cerchie",
      "Menziona persone",
      "Aggiungi hashtag",
      "Aggiungi foto",
      "(facoltativo)",
      "Impossibile aprire le bozze. Riprova.",
      "La tua storia",
      "Aiuto IA",
    ],
    "pt-BR": [
      "Criar publicação",
      "Adicione um título (opcional)",
      "Compartilhe ideias, experiências ou dicas…\nNo que você está pensando?",
      "Adicionar localização",
      "Escolher círculos",
      "Mencionar pessoas",
      "Adicionar hashtags",
      "Adicionar fotos",
      "(opcional)",
      "Não foi possível abrir os rascunhos. Tente novamente.",
      "Sua história",
      "Ajuda de IA",
    ],
    "pt-PT": [
      "Criar publicação",
      "Adicione um título (opcional)",
      "Partilhe ideias, experiências ou dicas…\nEm que está a pensar?",
      "Adicionar localização",
      "Escolher círculos",
      "Mencionar pessoas",
      "Adicionar hashtags",
      "Adicionar fotografias",
      "(opcional)",
      "Não foi possível abrir os rascunhos. Tente novamente.",
      "A sua história",
      "Ajuda de IA",
    ],
    "ur": [
      "پوسٹ بنائیں",
      "عنوان شامل کریں (اختیاری)",
      "اپنے خیالات، تجربات یا مشورے شیئر کریں…\nآپ کے ذہن میں کیا ہے؟",
      "مقام شامل کریں",
      "حلقے منتخب کریں",
      "لوگوں کا ذکر کریں",
      "ہیش ٹیگ شامل کریں",
      "تصاویر شامل کریں",
      "(اختیاری)",
      "مسودے نہیں کھل سکے۔ دوبارہ کوشش کریں۔",
      "آپ کی اسٹوری",
      "AI کی مدد",
    ],
    "fa": [
      "ایجاد پست",
      "عنوان اضافه کنید (اختیاری)",
      "افکار، تجربه‌ها یا نکته‌هایتان را به اشتراک بگذارید…\nچه چیزی در ذهن دارید؟",
      "افزودن مکان",
      "انتخاب حلقه‌ها",
      "اشاره به افراد",
      "افزودن هشتگ",
      "افزودن عکس",
      "(اختیاری)",
      "پیش‌نویس‌ها باز نشدند. دوباره تلاش کنید.",
      "داستان شما",
      "کمک هوش مصنوعی",
    ],
    "hi": [
      "पोस्ट बनाएँ",
      "शीर्षक जोड़ें (वैकल्पिक)",
      "अपने विचार, अनुभव या सुझाव साझा करें…\nआप क्या सोच रहे हैं?",
      "स्थान जोड़ें",
      "सर्कल चुनें",
      "लोगों का उल्लेख करें",
      "हैशटैग जोड़ें",
      "फ़ोटो जोड़ें",
      "(वैकल्पिक)",
      "ड्राफ़्ट नहीं खुल सके। फिर से कोशिश करें।",
      "आपकी स्टोरी",
      "AI सहायता",
    ],
    "id": [
      "Buat postingan",
      "Tambahkan judul (opsional)",
      "Bagikan pemikiran, pengalaman, atau tips…\nApa yang Anda pikirkan?",
      "Tambahkan lokasi",
      "Pilih lingkaran",
      "Sebut orang",
      "Tambahkan tagar",
      "Tambahkan foto",
      "(opsional)",
      "Draf tidak dapat dibuka. Coba lagi.",
      "Cerita Anda",
      "Bantuan AI",
    ],
    "ms": [
      "Cipta siaran",
      "Tambah tajuk (pilihan)",
      "Kongsi fikiran, pengalaman atau petua…\nApa yang anda fikirkan?",
      "Tambah lokasi",
      "Pilih lingkungan",
      "Sebut orang",
      "Tambah tanda pagar",
      "Tambah foto",
      "(pilihan)",
      "Draf tidak dapat dibuka. Cuba lagi.",
      "Cerita anda",
      "Bantuan AI",
    ],
    "ja": [
      "投稿を作成",
      "タイトルを追加（任意）",
      "考えや経験、ヒントを共有しましょう…\n今、何を考えていますか？",
      "場所を追加",
      "サークルを選択",
      "ユーザーをメンション",
      "ハッシュタグを追加",
      "写真を追加",
      "（任意）",
      "下書きを開けませんでした。もう一度お試しください。",
      "あなたのストーリー",
      "AIヘルプ",
    ],
    "ko": [
      "게시물 작성",
      "제목 추가(선택 사항)",
      "생각, 경험 또는 팁을 공유해 보세요…\n무슨 생각을 하고 있나요?",
      "위치 추가",
      "서클 선택",
      "사람 언급",
      "해시태그 추가",
      "사진 추가",
      "(선택 사항)",
      "임시 저장 글을 열 수 없습니다. 다시 시도하세요.",
      "내 스토리",
      "AI 도움말",
    ],
    "zh-Hans": [
      "创建帖子",
      "添加标题（选填）",
      "分享你的想法、经历或建议……\n你在想什么？",
      "添加位置",
      "选择圈子",
      "提及他人",
      "添加话题标签",
      "添加照片",
      "（选填）",
      "无法打开草稿，请重试。",
      "你的动态",
      "AI 帮助",
    ],
    "zh-Hant": [
      "建立貼文",
      "新增標題（選填）",
      "分享你的想法、經驗或建議……\n你在想什麼？",
      "新增位置",
      "選擇圈子",
      "提及他人",
      "新增主題標籤",
      "新增相片",
      "（選填）",
      "無法開啟草稿，請再試一次。",
      "你的限時動態",
      "AI 協助",
    ],
    "ru": [
      "Создать публикацию",
      "Добавьте заголовок (необязательно)",
      "Поделитесь мыслями, опытом или советами…\nО чём вы думаете?",
      "Добавить место",
      "Выбрать круги",
      "Упомянуть людей",
      "Добавить хештеги",
      "Добавить фото",
      "(необязательно)",
      "Не удалось открыть черновики. Попробуйте ещё раз.",
      "Ваша история",
      "Помощь ИИ",
    ],
    "bn": [
      "পোস্ট তৈরি করুন",
      "শিরোনাম যোগ করুন (ঐচ্ছিক)",
      "আপনার ভাবনা, অভিজ্ঞতা বা পরামর্শ শেয়ার করুন…\nআপনার মনে কী আছে?",
      "অবস্থান যোগ করুন",
      "সার্কেল বেছে নিন",
      "লোকজনকে উল্লেখ করুন",
      "হ্যাশট্যাগ যোগ করুন",
      "ছবি যোগ করুন",
      "(ঐচ্ছিক)",
      "খসড়া খোলা যায়নি। আবার চেষ্টা করুন।",
      "আপনার স্টোরি",
      "AI সহায়তা",
    ],
    "vi": [
      "Tạo bài viết",
      "Thêm tiêu đề (không bắt buộc)",
      "Chia sẻ suy nghĩ, trải nghiệm hoặc mẹo của bạn…\nBạn đang nghĩ gì?",
      "Thêm địa điểm",
      "Chọn nhóm",
      "Nhắc đến mọi người",
      "Thêm hashtag",
      "Thêm ảnh",
      "(không bắt buộc)",
      "Không thể mở bản nháp. Hãy thử lại.",
      "Tin của bạn",
      "Trợ giúp AI",
    ],
    "th": [
      "สร้างโพสต์",
      "เพิ่มชื่อเรื่อง (ไม่บังคับ)",
      "แบ่งปันความคิด ประสบการณ์ หรือเคล็ดลับ…\nคุณกำลังคิดอะไรอยู่?",
      "เพิ่มสถานที่",
      "เลือกแวดวง",
      "กล่าวถึงบุคคล",
      "เพิ่มแฮชแท็ก",
      "เพิ่มรูปภาพ",
      "(ไม่บังคับ)",
      "เปิดฉบับร่างไม่ได้ โปรดลองอีกครั้ง",
      "สตอรี่ของคุณ",
      "ความช่วยเหลือ AI",
    ],
    "pl": [
      "Utwórz post",
      "Dodaj tytuł (opcjonalnie)",
      "Podziel się przemyśleniami, doświadczeniami lub wskazówkami…\nO czym myślisz?",
      "Dodaj lokalizację",
      "Wybierz kręgi",
      "Wspomnij osoby",
      "Dodaj hasztagi",
      "Dodaj zdjęcia",
      "(opcjonalnie)",
      "Nie udało się otworzyć wersji roboczych. Spróbuj ponownie.",
      "Twoja relacja",
      "Pomoc AI",
    ],
    "nl": [
      "Bericht maken",
      "Voeg een titel toe (optioneel)",
      "Deel je gedachten, ervaringen of tips…\nWaar denk je aan?",
      "Locatie toevoegen",
      "Kringen kiezen",
      "Personen vermelden",
      "Hashtags toevoegen",
      "Foto’s toevoegen",
      "(optioneel)",
      "Concepten konden niet worden geopend. Probeer het opnieuw.",
      "Je verhaal",
      "AI-hulp",
    ],
    "uk": [
      "Створити допис",
      "Додайте заголовок (необов’язково)",
      "Поділіться думками, досвідом або порадами…\nПро що ви думаєте?",
      "Додати місце",
      "Вибрати кола",
      "Згадати людей",
      "Додати хештеги",
      "Додати фото",
      "(необов’язково)",
      "Не вдалося відкрити чернетки. Спробуйте ще раз.",
      "Ваша історія",
      "Допомога ШІ",
    ],
  };

  static String? resolve(String source, String localeTag) {
    final index = sources.indexOf(source);
    if (index < 0) return null;
    final tag = BilLocalePolicy.canonicalSupportedTag(localeTag);
    final row = rows[tag];
    if (row == null) return null;
    if (row.length != sources.length) {
      throw StateError('Incomplete Community creation copy for $tag');
    }
    return row[index];
  }
}
