part of 'runtime_copy_next_workspace.dart';

const _nextWorkspaceRows1 = <String, List<String>>{
  'pt-BR': [
    'Não foi possível confirmar a leitura destas atualizações. Tente novamente.',
    'Marcar esta página como lida',
    'Vamos fazer o dia valer a pena.',
    'Foco de hoje',
    'Uma pequena ação de cada vez. Seu coach ajuda você a registrar, refletir e planejar.',
    'Ferramentas do plano',
    'Registrar refeição',
    'Registro por voz',
    'Basta falar',
    'Em segundos',
    'Escanear produto',
    'Código de barras / Rótulo',
    'Entenda melhor cada refeição',
    'Tire uma foto para revisar os alimentos e as porções antes de adicioná-los ao diário.',
    'Experimentar registro por foto  ›',
    'Seu histórico de saúde',
    'Refeições registradas',
    '{count} refeições no seu diário real',
    'Atividade sincronizada',
    'Seus registros verificados aparecerão aqui.',
    'Pequenas ações constantes geram um progresso significativo.\n— Coach IA BIL',
    'Seu parceiro de saúde, sempre com você',
    'Pesquisar conversas',
  ],
  'pt-PT': [
    'Não foi possível confirmar a leitura destas atualizações. Tenta novamente.',
    'Marcar esta página como lida',
    'Vamos fazer o dia valer a pena.',
    'Foco de hoje',
    'Uma pequena ação de cada vez. O teu coach ajuda-te a registar, refletir e planear.',
    'Ferramentas do plano',
    'Registar refeição',
    'Registo por voz',
    'Basta falar',
    'Em segundos',
    'Digitalizar produto',
    'Código de barras / Rótulo',
    'Compreende melhor cada refeição',
    'Tira uma fotografia para rever os alimentos e as porções antes de os adicionares ao diário.',
    'Experimentar registo por fotografia  ›',
    'O teu histórico de saúde',
    'Refeições registadas',
    '{count} refeições no teu diário real',
    'Atividade sincronizada',
    'Os teus registos verificados aparecerão aqui.',
    'Pequenas ações constantes geram progressos significativos.\n— Coach IA BIL',
    'O teu parceiro de saúde, sempre contigo',
    'Pesquisar conversas',
  ],
  'ur': [
    'ان اپ ڈیٹس کو پڑھا ہوا نشان زد کرنے کی تصدیق نہیں ہو سکی۔ دوبارہ کوشش کریں۔',
    'اس صفحے کو پڑھا ہوا نشان زد کریں',
    'آج کے دن کو بہتر بنائیں۔',
    'آج کی توجہ',
    'ایک وقت میں ایک چھوٹا قدم۔ آپ کا کوچ اندراج، جائزے اور منصوبہ بندی میں مدد کرتا ہے۔',
    'منصوبے کے اوزار',
    'کھانا درج کریں',
    'آواز سے اندراج',
    'بس بولیں',
    'چند سیکنڈ میں',
    'پروڈکٹ اسکین کریں',
    'بارکوڈ / لیبل',
    'ہر کھانے کو بہتر سمجھیں',
    'ڈائری میں شامل کرنے سے پہلے خوراک اور مقدار کا جائزہ لینے کے لیے تصویر لیں۔',
    'تصویر سے اندراج آزمائیں  ‹',
    'آپ کی صحت کی تاریخ',
    'درج کیے گئے کھانے',
    'آپ کی اصل ڈائری میں کھانے کے {count} اندراجات',
    'سرگرمی ہم وقت ہو گئی',
    'آپ کے تصدیق شدہ اندراجات یہاں نظر آئیں گے۔',
    'چھوٹے مگر مسلسل اقدامات بامعنی ترقی لاتے ہیں۔\n— BIL اے آئی کوچ',
    'آپ کا صحت کا ساتھی، ہمیشہ آپ کے ساتھ',
    'گفتگو تلاش کریں',
  ],
  'fa': [
    'خوانده‌شدن این به‌روزرسانی‌ها تأیید نشد. دوباره تلاش کنید.',
    'علامت‌گذاری این صفحه به‌عنوان خوانده‌شده',
    'بیایید امروز را پربار کنیم.',
    'تمرکز امروز',
    'هر بار یک گام کوچک. مربی شما برای ثبت، مرور و برنامه‌ریزی کنارتان است.',
    'ابزارهای برنامه',
    'ثبت وعده غذایی',
    'ثبت صوتی',
    'فقط صحبت کنید',
    'در چند ثانیه',
    'اسکن محصول',
    'بارکد / برچسب',
    'هر وعده را بهتر بشناسید',
    'برای بررسی غذا و اندازه وعده‌ها پیش از افزودن به دفترتان عکس بگیرید.',
    'ثبت با عکس را امتحان کنید  ‹',
    'روند سلامت شما',
    'وعده‌های ثبت‌شده',
    '{count} وعده در دفتر واقعی شما',
    'فعالیت همگام شد',
    'ثبت‌های تأییدشده شما اینجا نمایش داده می‌شوند.',
    'گام‌های کوچک و پیوسته پیشرفتی واقعی می‌سازند.\n— مربی هوش مصنوعی BIL',
    'همراه سلامت شما، همیشه در کنارتان',
    'جست‌وجوی گفتگوها',
  ],
  'hi': [
    'इन अपडेट को पढ़ा हुआ चिह्नित करने की पुष्टि नहीं हो सकी। फिर कोशिश करें।',
    'इस पेज को पढ़ा हुआ चिह्नित करें',
    'आइए आज का दिन बेहतर बनाएं।',
    'आज का ध्यान',
    'एक समय में एक छोटा कदम। आपका कोच रिकॉर्ड करने, समीक्षा करने और योजना बनाने में मदद करता है।',
    'योजना के टूल',
    'भोजन दर्ज करें',
    'आवाज़ से दर्ज करें',
    'बस बोलें',
    'कुछ सेकंड में',
    'उत्पाद स्कैन करें',
    'बारकोड / लेबल',
    'हर भोजन को बेहतर समझें',
    'डायरी में जोड़ने से पहले भोजन और मात्रा की समीक्षा के लिए फोटो लें।',
    'फोटो से दर्ज करना आज़माएं  ›',
    'आपकी स्वास्थ्य समयरेखा',
    'दर्ज किए गए भोजन',
    'आपकी वास्तविक डायरी में भोजन की {count} प्रविष्टियां',
    'गतिविधि सिंक हुई',
    'आपकी सत्यापित प्रविष्टियां यहां दिखाई देंगी।',
    'छोटे लेकिन नियमित कदम सार्थक प्रगति लाते हैं।\n— BIL एआई कोच',
    'आपका स्वास्थ्य साथी, हमेशा आपके साथ',
    'बातचीत खोजें',
  ],
  'id': [
    'Tidak dapat mengonfirmasi pembaruan ini sebagai sudah dibaca. Coba lagi.',
    'Tandai halaman ini sudah dibaca',
    'Mari manfaatkan hari ini.',
    'Fokus hari ini',
    'Satu langkah kecil setiap kali. Coach membantu Anda mencatat, meninjau, dan merencanakan.',
    'Alat rencana',
    'Catat makanan',
    'Catat dengan suara',
    'Cukup bicara',
    'Dalam hitungan detik',
    'Pindai produk',
    'Kode batang / Label',
    'Pahami setiap makanan lebih baik',
    'Ambil foto untuk meninjau makanan dan porsinya sebelum menambahkannya ke jurnal.',
    'Coba pencatatan foto  ›',
    'Linimasa kesehatan Anda',
    'Makanan tercatat',
    '{count} catatan makanan dalam jurnal Anda',
    'Aktivitas disinkronkan',
    'Catatan terverifikasi Anda akan muncul di sini.',
    'Langkah kecil yang konsisten menghasilkan kemajuan berarti.\n— Coach AI BIL',
    'Mitra kesehatan Anda, selalu bersama Anda',
    'Cari percakapan',
  ],
};
