part of 'runtime_copy_community_social.dart';

const _communitySocialCoreRows = <String, List<String>>{
  'ar': <String>[
    'أضف @{handle} على BIL: {uri}',
    'إضافة صديق',
    'حظر',
    'حظر هذا العضو؟',
    'الوصول إلى الكاميرا مرفوض أو مقيّد. فعّله من إعدادات النظام ثم حاول مجددًا.',
    'إلغاء الرد',
    'يتطلب مسح الرمز كاميرا iOS أو Android.',
    'لم يُرسل التعليق. تم الاحتفاظ بنصك؛ أعد المحاولة بأمان.',
    'التعليقات',
    'تعذر تحميل المنشورات الأقدم. حاول مجددًا.',
    'تعذر تحديث المنشورات المحفوظة. حاول مجددًا.',
    'تعذر تحديث هذا التفاعل. حاول مجددًا.',
    'تعذر إرسال طلب الصداقة. حاول مجددًا.',
    'دع صديقًا يمسح هذا الرمز. فهو يعرّف بملفك العام في المجتمع فقط ولا يمكنه تسجيل دخول أي شخص.',
    'تحميل المزيد',
    'تحميل المزيد من التعليقات',
    'تحميل منشورات أقدم',
    'تم حظر العضو.',
    'رمز BIL الخاص بي',
    'لا توجد تعليقات بعد. ابدأ حوارًا محترمًا.',
    'وجّه الكاميرا إلى رمز صديق BIL. لا يتم رفع أي شيء.',
    'منشور',
    'المنشورات التي تحفظها خاصة وتظهر هنا.',
    'إزالة من المحفوظات',
    'استبدال الرمز',
    'استبدال هذا الرمز',
    'استبدال رمز BIL الخاص بك؟',
    'رد',
    'الرد على {member}',
    'تم إرسال البلاغ للمراجعة البشرية.',
    'إعادة محاولة الكاميرا',
    'مراجعة الطلب',
    'حفظ المنشور',
    'المنشورات المحفوظة',
    'مسح رمز صديق',
    'إرسال التعليق',
    'مشاركة الرمز',
    'مشاركة المنشور',
    'عرض أقل',
    'عرض المزيد',
    'هذا الرمز غير صالح أو منتهي الصلاحية أو خاص أو غير متاح.',
    'هذا ليس رمز صديق BIL حاليًا.',
    'اكتب تعليقًا',
    'اكتب تعليقًا أولًا.',
    'لن يعود بإمكان أي منكما رؤية الآخر في المجتمع أو الرسائل.',
    'رمز BIL غير متاح الآن. حاول مجددًا.',
    'رمز BIL غير متاح. سجّل الدخول وأكمل ملف المجتمع ثم حاول مجددًا.',
    'سيتوقف الرمز القديم عن العمل. سيحتاج الأصدقاء إلى الرمز الجديد.',
  ],
  'en': CommunitySocialRuntimeCopy.sources,
  'fr': <String>[
    'Ajoutez @{handle} sur BIL : {uri}',
    'Ajouter comme ami',
    'Bloquer',
    'Bloquer ce membre ?',
    'L’accès à l’appareil photo est refusé ou limité. Autorisez-le dans les réglages système, puis réessayez.',
    'Annuler la réponse',
    'La lecture du code nécessite l’appareil photo d’un appareil iOS ou Android.',
    'Le commentaire n’a pas été envoyé. Votre texte est conservé ; réessayez en toute sécurité.',
    'Commentaires',
    'Impossible de charger les publications plus anciennes. Réessayez.',
    'Impossible de mettre à jour les publications enregistrées. Réessayez.',
    'Impossible de mettre à jour cette réaction. Réessayez.',
    'Impossible d’envoyer la demande d’ami. Réessayez.',
    'Faites scanner ce code par un ami. Il identifie uniquement votre profil public dans la Communauté ; il ne permet à personne de se connecter.',
    'Charger plus',
    'Charger plus de commentaires',
    'Charger les publications précédentes',
    'Membre bloqué.',
    'Mon code BIL',
    'Aucun commentaire pour le moment. Lancez une conversation respectueuse.',
    'Dirigez l’appareil photo vers un code d’ami BIL. Aucun contenu n’est envoyé.',
    'Publication',
    'Les publications que vous enregistrez sont privées et apparaissent ici.',
    'Retirer des éléments enregistrés',
    'Remplacer le code',
    'Remplacer ce code',
    'Remplacer votre code BIL ?',
    'Répondre',
    'Réponse à {member}',
    'Signalement envoyé pour examen humain.',
    'Réessayer avec l’appareil photo',
    'Examiner la demande',
    'Enregistrer la publication',
    'Publications enregistrées',
    'Scanner le code d’un ami',
    'Envoyer le commentaire',
    'Partager le code',
    'Partager la publication',
    'Afficher moins',
    'Afficher plus',
    'Ce code est incorrect, expiré, privé ou indisponible.',
    'Ceci n’est pas un code d’ami BIL actuel.',
    'Écrire un commentaire',
    'Écrivez d’abord un commentaire.',
    'Vous ne vous verrez plus dans la Communauté ni dans les messages.',
    'Votre code BIL est momentanément indisponible. Réessayez.',
    'Votre code BIL est indisponible. Connectez-vous, complétez votre profil Communauté, puis réessayez.',
    'Votre ancien code cessera de fonctionner. Vos amis devront utiliser le nouveau.',
  ],
  'es': <String>[
    'Añade a @{handle} en BIL: {uri}',
    'Añadir amigo',
    'Bloquear',
    '¿Bloquear a este miembro?',
    'El acceso a la cámara está denegado o restringido. Actívalo en los ajustes del sistema y vuelve a intentarlo.',
    'Cancelar respuesta',
    'Para escanear el código se necesita una cámara de iOS o Android.',
    'No se envió el comentario. Tu texto se conserva; vuelve a intentarlo de forma segura.',
    'Comentarios',
    'No se pudieron cargar publicaciones anteriores. Inténtalo de nuevo.',
    'No se pudieron actualizar las publicaciones guardadas. Inténtalo de nuevo.',
    'No se pudo actualizar esta reacción. Inténtalo de nuevo.',
    'No se pudo enviar la solicitud de amistad. Inténtalo de nuevo.',
    'Pide a un amigo que escanee este código. Solo identifica tu perfil público de la Comunidad; no permite que nadie inicie sesión.',
    'Cargar más',
    'Cargar más comentarios',
    'Cargar publicaciones anteriores',
    'Miembro bloqueado.',
    'Mi código BIL',
    'Aún no hay comentarios. Inicia una conversación respetuosa.',
    'Apunta la cámara a un código de amigo de BIL. No se sube nada.',
    'Publicación',
    'Las publicaciones que guardas son privadas y aparecen aquí.',
    'Quitar de guardados',
    'Reemplazar código',
    'Reemplazar este código',
    '¿Reemplazar tu código BIL?',
    'Responder',
    'Respondiendo a {member}',
    'Denuncia enviada para revisión humana.',
    'Reintentar con la cámara',
    'Revisar solicitud',
    'Guardar publicación',
    'Publicaciones guardadas',
    'Escanear código de amigo',
    'Enviar comentario',
    'Compartir código',
    'Compartir publicación',
    'Mostrar menos',
    'Mostrar más',
    'Este código no es válido, ha caducado, es privado o no está disponible.',
    'Este no es un código de amigo de BIL vigente.',
    'Escribe un comentario',
    'Escribe primero un comentario.',
    'Ya no podréis veros en la Comunidad ni en los mensajes.',
    'Tu código BIL no está disponible ahora. Inténtalo de nuevo.',
    'Tu código BIL no está disponible. Inicia sesión, completa tu perfil de la Comunidad y vuelve a intentarlo.',
    'Tu código anterior dejará de funcionar. Tus amigos necesitarán el nuevo.',
  ],
  'tr': <String>[
    'BIL’de @{handle} kişisini ekleyin: {uri}',
    'Arkadaş ekle',
    'Engelle',
    'Bu üye engellensin mi?',
    'Kamera erişimi reddedilmiş veya kısıtlanmış. Sistem ayarlarından etkinleştirip tekrar deneyin.',
    'Yanıtı iptal et',
    'Kod taramak için iOS veya Android kamerası gerekir.',
    'Yorum gönderilmedi. Metniniz korundu; güvenle tekrar deneyin.',
    'Yorumlar',
    'Eski gönderiler yüklenemedi. Tekrar deneyin.',
    'Kaydedilen gönderiler güncellenemedi. Tekrar deneyin.',
    'Bu tepki güncellenemedi. Tekrar deneyin.',
    'Arkadaşlık isteği gönderilemedi. Tekrar deneyin.',
    'Bir arkadaşınız bu kodu tarasın. Kod yalnızca herkese açık Topluluk profilinizi tanımlar; kimsenin oturum açmasını sağlamaz.',
    'Daha fazla yükle',
    'Daha fazla yorum yükle',
    'Eski gönderileri yükle',
    'Üye engellendi.',
    'BIL Kodum',
    'Henüz yorum yok. Saygılı bir sohbet başlatın.',
    'Kamerayı bir BIL arkadaş koduna doğrultun. Hiçbir şey yüklenmez.',
    'Gönderi',
    'Kaydettiğiniz gönderiler özeldir ve burada görünür.',
    'Kaydedilenlerden kaldır',
    'Kodu değiştir',
    'Bu kodu değiştir',
    'BIL Kodunuz değiştirilsin mi?',
    'Yanıtla',
    '{member} adlı üyeye yanıt veriliyor',
    'Bildirim insan incelemesine gönderildi.',
    'Kamerayı tekrar dene',
    'İsteği incele',
    'Gönderiyi kaydet',
    'Kaydedilen gönderiler',
    'Arkadaş Kodunu Tara',
    'Yorumu gönder',
    'Kodu paylaş',
    'Gönderiyi paylaş',
    'Daha az göster',
    'Daha fazla göster',
    'Bu kod geçersiz, süresi dolmuş, özel veya kullanılamıyor.',
    'Bu, güncel bir BIL arkadaş kodu değil.',
    'Yorum yaz',
    'Önce bir yorum yazın.',
    'Artık Toplulukta veya mesajlarda birbirinizi göremezsiniz.',
    'BIL Kodunuz şu anda kullanılamıyor. Tekrar deneyin.',
    'BIL Kodunuz kullanılamıyor. Oturum açın, Topluluk profilinizi tamamlayın ve tekrar deneyin.',
    'Eski kodunuz çalışmayı durduracak. Arkadaşlarınızın yeni koda ihtiyacı olacak.',
  ],
  'de': <String>[
    'Füge @{handle} auf BIL hinzu: {uri}',
    'Freund hinzufügen',
    'Blockieren',
    'Dieses Mitglied blockieren?',
    'Der Kamerazugriff wurde verweigert oder eingeschränkt. Aktiviere ihn in den Systemeinstellungen und versuche es erneut.',
    'Antwort abbrechen',
    'Zum Scannen des Codes ist eine iOS- oder Android-Kamera erforderlich.',
    'Der Kommentar wurde nicht gesendet. Dein Text bleibt erhalten; versuche es sicher erneut.',
    'Kommentare',
    'Ältere Beiträge konnten nicht geladen werden. Versuche es erneut.',
    'Gespeicherte Beiträge konnten nicht aktualisiert werden. Versuche es erneut.',
    'Diese Reaktion konnte nicht aktualisiert werden. Versuche es erneut.',
    'Die Freundschaftsanfrage konnte nicht gesendet werden. Versuche es erneut.',
    'Lass diesen Code von einem Freund scannen. Er identifiziert nur dein öffentliches Community-Profil und kann niemanden anmelden.',
    'Mehr laden',
    'Weitere Kommentare laden',
    'Ältere Beiträge laden',
    'Mitglied blockiert.',
    'Mein BIL-Code',
    'Noch keine Kommentare. Beginne eine respektvolle Unterhaltung.',
    'Richte die Kamera auf einen BIL-Freundescode. Es wird nichts hochgeladen.',
    'Beitrag',
    'Gespeicherte Beiträge sind privat und werden hier angezeigt.',
    'Aus Gespeichert entfernen',
    'Code ersetzen',
    'Diesen Code ersetzen',
    'Deinen BIL-Code ersetzen?',
    'Antworten',
    'Antwort an {member}',
    'Meldung zur menschlichen Prüfung gesendet.',
    'Kamera erneut versuchen',
    'Anfrage prüfen',
    'Beitrag speichern',
    'Gespeicherte Beiträge',
    'Freundescode scannen',
    'Kommentar senden',
    'Code teilen',
    'Beitrag teilen',
    'Weniger anzeigen',
    'Mehr anzeigen',
    'Dieser Code ist ungültig, abgelaufen, privat oder nicht verfügbar.',
    'Dies ist kein aktueller BIL-Freundescode.',
    'Kommentar schreiben',
    'Schreibe zuerst einen Kommentar.',
    'Ihr könnt euch in der Community und in Nachrichten nicht mehr sehen.',
    'Dein BIL-Code ist derzeit nicht verfügbar. Versuche es erneut.',
    'Dein BIL-Code ist nicht verfügbar. Melde dich an, vervollständige dein Community-Profil und versuche es erneut.',
    'Dein alter Code funktioniert danach nicht mehr. Freunde benötigen den neuen Code.',
  ],
};
