part of 'runtime_copy_next_workspace.dart';

const _nextWorkspaceSupplementalRows0 = <String, List<String>>{
  "ar": [
    "نظرة عامة",
    "صور المنشور",
    "الرئيسية",
    "منشورات غير مكتملة وخاصة",
    "احفظ الملف وأنشئ رمز BIL",
    "سجّل الدخول لفتح مسوداتك الخاصة.",
    "صلاحيات إجراءات المدرب",
    "الإحصاءات",
    "{count} صور",
    "الموافقات",
    "حذف {count} من المسودات؟",
    "حذف المحدد ({count})",
    "إجراءات المسودة",
    "المسودات ({count})",
    "آخر حفظ قبل {count} ي",
    "آخر حفظ قبل {count} س",
    "آخر حفظ قبل {count} د",
    "الإشارات",
    "ستظهر الموافقات والإشارات والتعليقات الجديدة هنا.",
    "لا توجد مسودات محفوظة بعد",
    "إعدادات الإشعارات",
    "الإشعارات غير متاحة",
    "الآن",
    "أُضيفت المكافأة إلى رصيد الذكاء الاصطناعي",
    "احفظ المنشورات غير المكتملة وتابعها هنا لاحقًا.",
    "حُفظت الآن",
    "تحديد",
    "سيؤدي هذا إلى حذف المسودات الخاصة المحددة فقط.",
    "أنت مطّلع على كل جديد",
    "سابقًا",
    "تغير الحساب. ارجع إلى المجتمع للمتابعة.",
    "اجعل النص في حدود 1200 حرف. احتفظنا بالنص كاملًا.",
    "تعذر التحقق من الإجراء. اطلب من المدرب إعداده مرة أخرى.",
    "هذا اليوم مغلق. أعد فتحه في السجل اليومي قبل التعديل.",
    "تغيّرت هذه الوجبة منذ تجهيز الإجراء. راجعها مجددًا.",
    "تغيّر الحساب. افتح المدرب الذكي مجددًا وحاول مرة أخرى.",
    "سبق التراجع عن هذا الإجراء. لم تُضف البيانات مجددًا.",
    "تعذر إكمال التراجع. راجع بياناتك الحالية.",
    "حُفظ إدخال السعرات فقط. المغذيات الأخرى غير معروفة.",
    "حُفظ التغيير، لكن تعذر تحميل الإيصال. أعد المحاولة لقراءة النتيجة المحفوظة.",
    "حُفظ إدخال المغذيات. السعرات غير معروفة.",
    "تغير هذا السجل منذ تجهيز الإجراء. راجعه مجددًا.",
    "تغير حسابك. جهز هذا الإجراء مجددًا للحساب الحالي.",
    "حُفظ الإجراء، لكن تعذر التحقق من حالته الحالية. راجع بياناتك قبل المحاولة مجددًا.",
  ],
  "fr": [
    "Vue d’ensemble",
    "Photos de la publication",
    "Accueil",
    "Publications privées inachevées",
    "Enregistrer le profil et créer le code BIL",
    "Connectez-vous pour ouvrir vos brouillons privés.",
    "Autorisations des actions du coach",
    "Statistiques",
    "Photos : {count}",
    "Approbations",
    "Supprimer {count} brouillons ?",
    "Supprimer la sélection ({count})",
    "Actions sur le brouillon",
    "Brouillons ({count})",
    "Dernière sauvegarde il y a {count} j",
    "Dernière sauvegarde il y a {count} h",
    "Dernière sauvegarde il y a {count} min",
    "Mentions reçues",
    "Les nouvelles approbations, mentions et commentaires apparaîtront ici.",
    "Aucun brouillon enregistré pour le moment",
    "Paramètres des notifications",
    "Les notifications sont indisponibles",
    "Maintenant",
    "Récompense ajoutée à votre solde IA",
    "Enregistrez les publications inachevées pour les reprendre ici plus tard.",
    "Enregistré à l’instant",
    "Sélectionner",
    "Seuls les brouillons privés sélectionnés seront supprimés.",
    "Vous avez tout vu",
    "Plus tôt",
    "Votre compte a changé. Revenez à la communauté pour continuer.",
    "Limitez le texte à 1200 caractères. Votre texte est conservé.",
    "L’action n’a pas pu être validée. Demandez au coach de la préparer à nouveau.",
    "Cette journée est clôturée. Rouvrez-la dans le journal quotidien avant de faire des modifications.",
    "Ce repas a changé depuis la préparation de l’action. Vérifiez-le à nouveau.",
    "Le compte a changé. Rouvrez le coach IA et réessayez.",
    "Cette action a déjà été annulée. Rien n’a été ajouté à nouveau.",
    "L’annulation n’a pas pu être effectuée. Vérifiez vos données actuelles.",
    "Entrée de calories seules enregistrée. Les autres nutriments sont inconnus.",
    "La modification a été enregistrée, mais son reçu n’a pas pu être chargé. Réessayez pour lire le résultat enregistré.",
    "Entrée de macronutriments enregistrée. Les calories sont inconnues.",
    "Cette entrée a changé depuis la préparation de l’action. Vérifiez-la à nouveau.",
    "Votre compte a changé. Préparez à nouveau cette action pour le compte actuel.",
    "L’action a été enregistrée, mais son état actuel n’a pas pu être vérifié. Vérifiez vos données avant de réessayer.",
  ],
  "es": [
    "Resumen",
    "Fotos de la publicación",
    "Inicio",
    "Publicaciones privadas sin terminar",
    "Guardar perfil y crear código BIL",
    "Inicia sesión para abrir tus borradores privados.",
    "Permisos de las acciones del entrenador",
    "Estadísticas",
    "{count} fotos",
    "Aprobaciones",
    "¿Eliminar {count} borradores?",
    "Eliminar seleccionados ({count})",
    "Acciones del borrador",
    "Borradores ({count})",
    "Último guardado hace {count} d",
    "Último guardado hace {count} h",
    "Último guardado hace {count} min",
    "Menciones",
    "Las nuevas aprobaciones, menciones y comentarios aparecerán aquí.",
    "Aún no hay borradores guardados",
    "Ajustes de notificaciones",
    "Las notificaciones no están disponibles",
    "Ahora",
    "Recompensa añadida a tu saldo de IA",
    "Guarda publicaciones sin terminar y continúa aquí más tarde.",
    "Guardado ahora mismo",
    "Seleccionar",
    "Esto elimina solo los borradores privados seleccionados.",
    "Estás al día",
    "Anteriores",
    "Tu cuenta ha cambiado. Vuelve a la comunidad para continuar.",
    "Limita el texto a 1200 caracteres. Tu texto se conserva.",
    "No se pudo validar la acción. Pide al entrenador que la prepare de nuevo.",
    "Este día está cerrado. Vuelve a abrirlo en el registro diario antes de hacer cambios.",
    "Esta comida cambió desde que se preparó la acción. Revísala de nuevo.",
    "La cuenta cambió. Vuelve a abrir el entrenador IA e inténtalo de nuevo.",
    "Esta acción ya se había deshecho. No se añadió nada de nuevo.",
    "No se pudo completar la acción de deshacer. Revisa tus datos actuales.",
    "Se guardó una entrada de solo calorías. Los demás nutrientes son desconocidos.",
    "El cambio se guardó, pero no se pudo cargar su recibo. Vuelve a intentarlo para leer el resultado guardado.",
    "Entrada de macronutrientes guardada. Las calorías son desconocidas.",
    "Este registro cambió desde que se preparó la acción. Revísalo de nuevo.",
    "Tu cuenta ha cambiado. Prepara esta acción de nuevo para la cuenta actual.",
    "La acción se guardó, pero no se pudo verificar su estado actual. Revisa tus datos antes de volver a intentarlo.",
  ],
  "tr": [
    "Genel bakış",
    "Gönderi fotoğrafları",
    "Ana sayfa",
    "Tamamlanmamış özel gönderiler",
    "Profili kaydet ve BIL Kodu oluştur",
    "Özel taslaklarını açmak için giriş yap.",
    "Koç eylemi izinleri",
    "İstatistikler",
    "{count} fotoğraf",
    "Onaylar",
    "{count} taslak silinsin mi?",
    "Seçilenleri sil ({count})",
    "Taslak işlemleri",
    "Taslaklar ({count})",
    "Son kayıt {count} gün önce",
    "Son kayıt {count} saat önce",
    "Son kayıt {count} dk önce",
    "Bahsetmeler",
    "Yeni onaylar, bahsetmeler ve yorumlar burada görünecek.",
    "Henüz kayıtlı taslak yok",
    "Bildirim ayarları",
    "Bildirimlere ulaşılamıyor",
    "Şimdi",
    "Ödül yapay zekâ bakiyene eklendi",
    "Tamamlanmamış gönderileri kaydet ve daha sonra buradan devam et.",
    "Az önce kaydedildi",
    "Seç",
    "Bu işlem yalnızca seçilen özel taslakları siler.",
    "Tüm bildirimleri gördün",
    "Daha önce",
    "Hesabınız değişti. Devam etmek için Topluluk’a dönün.",
    "Metni 1200 karakterle sınırlayın. Metniniz korunuyor.",
    "İşlem doğrulanamadı. Koçtan işlemi yeniden hazırlamasını isteyin.",
    "Bu gün kapatılmış. Değişiklik yapmadan önce Günlük Kayıt bölümünden yeniden açın.",
    "İşlem hazırlandıktan sonra bu öğün değişti. Yeniden gözden geçirin.",
    "Hesap değişti. Yapay Zekâ Koçunu yeniden açıp tekrar deneyin.",
    "Bu işlem zaten geri alınmıştı. Hiçbir şey yeniden eklenmedi.",
    "Geri alma tamamlanamadı. Mevcut verilerinizi inceleyin.",
    "Yalnızca kalori içeren kayıt kaydedildi. Diğer besin değerleri bilinmiyor.",
    "Değişiklik kaydedildi ancak işlem özeti yüklenemedi. Kaydedilen sonucu okumak için yeniden deneyin.",
    "Makro besin kaydı kaydedildi. Kalori miktarı bilinmiyor.",
    "Bu kayıt, işlem hazırlandıktan sonra değişti. Yeniden inceleyin.",
    "Hesabınız değişti. Bu işlemi mevcut hesap için yeniden hazırlayın.",
    "İşlem kaydedildi ancak mevcut durumu doğrulanamadı. Yeniden denemeden önce verilerinizi inceleyin.",
  ],
  "de": [
    "Übersicht",
    "Beitragsfotos",
    "Startseite",
    "Private, unfertige Beiträge",
    "Profil speichern und BIL-Code erstellen",
    "Melde dich an, um deine privaten Entwürfe zu öffnen.",
    "Berechtigungen für Coach-Aktionen",
    "Statistiken",
    "{count} Fotos",
    "Genehmigungen",
    "{count} Entwürfe löschen?",
    "Auswahl löschen ({count})",
    "Entwurfsaktionen",
    "Entwürfe ({count})",
    "Zuletzt vor {count} T. gespeichert",
    "Zuletzt vor {count} Std. gespeichert",
    "Zuletzt vor {count} Min. gespeichert",
    "Erwähnungen",
    "Neue Genehmigungen, Erwähnungen und Kommentare erscheinen hier.",
    "Noch keine gespeicherten Entwürfe",
    "Benachrichtigungseinstellungen",
    "Benachrichtigungen sind nicht verfügbar",
    "Jetzt",
    "Belohnung deinem KI-Guthaben hinzugefügt",
    "Speichere unfertige Beiträge und setze sie später hier fort.",
    "Gerade gespeichert",
    "Auswählen",
    "Dadurch werden nur die ausgewählten privaten Entwürfe gelöscht.",
    "Du bist auf dem neuesten Stand",
    "Früher",
    "Dein Konto hat sich geändert. Kehre zur Community zurück, um fortzufahren.",
    "Begrenze den Text auf 1200 Zeichen. Dein Text bleibt erhalten.",
    "Die Aktion konnte nicht bestätigt werden. Bitte den Coach, sie erneut vorzubereiten.",
    "Dieser Tag ist abgeschlossen. Öffne ihn vor Änderungen wieder im Tagesprotokoll.",
    "Diese Mahlzeit wurde seit der Vorbereitung der Aktion geändert. Prüfe sie erneut.",
    "Das Konto wurde gewechselt. Öffne den KI-Coach erneut und versuche es noch einmal.",
    "Diese Aktion wurde bereits rückgängig gemacht. Es wurde nichts erneut hinzugefügt.",
    "Das Rückgängigmachen konnte nicht abgeschlossen werden. Prüfe deine aktuellen Daten.",
    "Ein Eintrag nur mit Kalorien wurde gespeichert. Die anderen Nährstoffe sind unbekannt.",
    "Die Änderung wurde gespeichert, aber der Beleg konnte nicht geladen werden. Versuche es erneut, um das gespeicherte Ergebnis zu lesen.",
    "Makronährstoffeintrag gespeichert. Die Kalorien sind unbekannt.",
    "Dieser Eintrag hat sich seit der Vorbereitung der Aktion geändert. Prüfe ihn erneut.",
    "Dein Konto hat sich geändert. Bereite diese Aktion erneut für das aktuelle Konto vor.",
    "Die Aktion wurde gespeichert, aber ihr aktueller Zustand konnte nicht überprüft werden. Prüfe deine Daten, bevor du es erneut versuchst.",
  ],
  "it": [
    "Panoramica",
    "Foto del post",
    "Pagina iniziale",
    "Post privati incompleti",
    "Salva il profilo e crea il codice BIL",
    "Accedi per aprire le tue bozze private.",
    "Autorizzazioni per le azioni del coach",
    "Statistiche",
    "{count} foto",
    "Approvazioni",
    "Eliminare {count} bozze?",
    "Elimina selezionate ({count})",
    "Azioni sulla bozza",
    "Bozze ({count})",
    "Ultimo salvataggio {count} g fa",
    "Ultimo salvataggio {count} h fa",
    "Ultimo salvataggio {count} min fa",
    "Menzioni",
    "Le nuove approvazioni, menzioni e i nuovi commenti appariranno qui.",
    "Nessuna bozza salvata per ora",
    "Impostazioni delle notifiche",
    "Le notifiche non sono disponibili",
    "Ora",
    "Ricompensa aggiunta al tuo saldo IA",
    "Salva i post incompleti e riprendili qui più tardi.",
    "Salvato proprio ora",
    "Seleziona",
    "Questa operazione elimina solo le bozze private selezionate.",
    "Hai visto tutti gli aggiornamenti",
    "In precedenza",
    "Il tuo account è cambiato. Torna alla Community per continuare.",
    "Mantieni il testo entro 1200 caratteri. Il testo viene conservato.",
    "Non è stato possibile convalidare l’azione. Chiedi al coach di prepararla di nuovo.",
    "Questo giorno è chiuso. Riaprilo nel diario giornaliero prima di apportare modifiche.",
    "Questo pasto è cambiato da quando è stata preparata l’azione. Controllalo di nuovo.",
    "L’account è cambiato. Riapri il coach IA e riprova.",
    "Questa azione era già stata annullata. Non è stato aggiunto nulla di nuovo.",
    "Non è stato possibile completare l’annullamento. Controlla i tuoi dati attuali.",
    "Voce con sole calorie salvata. Gli altri nutrienti sono sconosciuti.",
    "La modifica è stata salvata, ma non è stato possibile caricare la ricevuta. Riprova per leggere il risultato salvato.",
    "Voce dei macronutrienti salvata. Le calorie sono sconosciute.",
    "Questa voce è cambiata da quando è stata preparata l’azione. Controllala di nuovo.",
    "Il tuo account è cambiato. Prepara di nuovo questa azione per l’account attuale.",
    "L’azione è stata salvata, ma non è stato possibile verificarne lo stato attuale. Controlla i tuoi dati prima di riprovare.",
  ],
  "pt-BR": [
    "Visão geral",
    "Fotos da publicação",
    "Início",
    "Publicações privadas inacabadas",
    "Salvar perfil e criar código BIL",
    "Entre para abrir seus rascunhos privados.",
    "Permissões para ações do treinador",
    "Estatísticas",
    "{count} fotos",
    "Aprovações",
    "Excluir {count} rascunhos?",
    "Excluir selecionados ({count})",
    "Ações do rascunho",
    "Rascunhos ({count})",
    "Último salvamento há {count} d",
    "Último salvamento há {count} h",
    "Último salvamento há {count} min",
    "Menções",
    "Novas aprovações, menções e comentários aparecerão aqui.",
    "Ainda não há rascunhos salvos",
    "Configurações de notificações",
    "As notificações estão indisponíveis",
    "Agora",
    "Recompensa adicionada ao seu saldo de IA",
    "Salve publicações inacabadas e continue aqui mais tarde.",
    "Salvo agora mesmo",
    "Selecionar",
    "Isso exclui apenas os rascunhos privados selecionados.",
    "Você está em dia",
    "Anteriores",
    "Sua conta mudou. Volte à Comunidade para continuar.",
    "Limite o texto a 1200 caracteres. Seu texto está preservado.",
    "Não foi possível validar a ação. Peça ao coach para prepará-la novamente.",
    "Este dia está fechado. Reabra-o no registro diário antes de fazer alterações.",
    "Esta refeição mudou desde que a ação foi preparada. Revise-a novamente.",
    "A conta mudou. Abra novamente o coach de IA e tente de novo.",
    "Esta ação já havia sido desfeita. Nada foi adicionado novamente.",
    "Não foi possível concluir a ação de desfazer. Confira seus dados atuais.",
    "Registro de somente calorias salvo. Os outros nutrientes são desconhecidos.",
    "A alteração foi salva, mas não foi possível carregar o comprovante. Tente novamente para ler o resultado salvo.",
    "Registro de macronutrientes salvo. As calorias são desconhecidas.",
    "Este registro mudou desde que a ação foi preparada. Confira-o novamente.",
    "Sua conta mudou. Prepare esta ação novamente para a conta atual.",
    "A ação foi salva, mas não foi possível verificar seu estado atual. Confira seus dados antes de tentar novamente.",
  ],
  "pt-PT": [
    "Visão geral",
    "Fotografias da publicação",
    "Início",
    "Publicações privadas inacabadas",
    "Guardar perfil e criar código BIL",
    "Inicia sessão para abrir os teus rascunhos privados.",
    "Permissões para ações do treinador",
    "Estatísticas",
    "{count} fotografias",
    "Aprovações",
    "Eliminar {count} rascunhos?",
    "Eliminar selecionados ({count})",
    "Ações do rascunho",
    "Rascunhos ({count})",
    "Guardado pela última vez há {count} d",
    "Guardado pela última vez há {count} h",
    "Guardado pela última vez há {count} min",
    "Menções",
    "As novas aprovações, menções e comentários vão aparecer aqui.",
    "Ainda não há rascunhos guardados",
    "Definições de notificações",
    "As notificações estão indisponíveis",
    "Agora",
    "Recompensa adicionada ao teu saldo de IA",
    "Guarda publicações inacabadas e continua aqui mais tarde.",
    "Guardado agora mesmo",
    "Selecionar",
    "Isto elimina apenas os rascunhos privados selecionados.",
    "Estás a par de tudo",
    "Anteriores",
    "A tua conta mudou. Regressa à Comunidade para continuar.",
    "Limita o texto a 1200 carateres. O teu texto foi preservado.",
    "Não foi possível validar a ação. Pede ao treinador para a preparar novamente.",
    "Este dia está fechado. Reabre-o no registo diário antes de fazer alterações.",
    "Esta refeição mudou desde que a ação foi preparada. Revê-a novamente.",
    "A conta mudou. Volta a abrir o treinador de IA e tenta novamente.",
    "Esta ação já tinha sido anulada. Nada foi adicionado novamente.",
    "Não foi possível concluir a anulação. Reveja os seus dados atuais.",
    "Registo apenas de calorias guardado. Os restantes nutrientes são desconhecidos.",
    "A alteração foi guardada, mas não foi possível carregar o comprovativo. Tente novamente para ler o resultado guardado.",
    "Registo de macronutrientes guardado. As calorias são desconhecidas.",
    "Este registo mudou desde que a ação foi preparada. Reveja-o novamente.",
    "A sua conta mudou. Prepare esta ação novamente para a conta atual.",
    "A ação foi guardada, mas não foi possível verificar o seu estado atual. Reveja os seus dados antes de tentar novamente.",
  ],
  "ur": [
    "جائزہ",
    "پوسٹ کی تصاویر",
    "مرکزی صفحہ",
    "نجی نامکمل پوسٹس",
    "پروفائل محفوظ کریں اور BIL کوڈ بنائیں",
    "اپنے نجی مسودے کھولنے کے لیے سائن اِن کریں۔",
    "کوچ کے اقدامات کی اجازتیں",
    "اعداد و شمار",
    "{count} تصاویر",
    "منظوریاں",
    "کیا {count} مسودے حذف کریں؟",
    "منتخب حذف کریں ({count})",
    "مسودے کے اقدامات",
    "مسودے ({count})",
    "آخری بار {count} دن پہلے محفوظ کیا گیا",
    "آخری بار {count} گھنٹے پہلے محفوظ کیا گیا",
    "آخری بار {count} منٹ پہلے محفوظ کیا گیا",
    "تذکرے",
    "نئی منظوریاں، تذکرے اور تبصرے یہاں ظاہر ہوں گے۔",
    "ابھی کوئی محفوظ مسودہ نہیں",
    "اطلاعات کی ترتیبات",
    "اطلاعات دستیاب نہیں ہیں",
    "ابھی",
    "انعام آپ کے AI بیلنس میں شامل کر دیا گیا",
    "نامکمل پوسٹس محفوظ کریں اور بعد میں یہیں سے جاری رکھیں۔",
    "ابھی محفوظ کیا گیا",
    "منتخب کریں",
    "اس سے صرف منتخب نجی مسودے حذف ہوں گے۔",
    "آپ نے تمام نئی اطلاعات دیکھ لی ہیں",
    "پہلے کی اطلاعات",
    "آپ کا اکاؤنٹ بدل گیا ہے۔ جاری رکھنے کے لیے کمیونٹی میں واپس جائیں۔",
    "متن 1200 حروف تک رکھیں۔ آپ کا متن محفوظ ہے۔",
    "کارروائی کی تصدیق نہیں ہو سکی۔ کوچ سے اسے دوبارہ تیار کرنے کو کہیں۔",
    "یہ دن بند ہے۔ تبدیلی سے پہلے اسے روزانہ لاگ میں دوبارہ کھولیں۔",
    "کارروائی تیار ہونے کے بعد یہ کھانا بدل گیا ہے۔ اسے دوبارہ دیکھیں۔",
    "اکاؤنٹ بدل گیا ہے۔ AI کوچ دوبارہ کھولیں اور پھر کوشش کریں۔",
    "اس کارروائی کو پہلے ہی واپس لیا جا چکا ہے۔ کچھ دوبارہ شامل نہیں کیا گیا۔",
    "واپسی مکمل نہیں ہو سکی۔ اپنا موجودہ ڈیٹا دیکھیں۔",
    "صرف کیلوریز کا اندراج محفوظ ہو گیا۔ دیگر غذائی اجزا نامعلوم ہیں۔",
    "تبدیلی محفوظ ہو گئی، لیکن اس کی رسید لوڈ نہیں ہو سکی۔ محفوظ نتیجہ پڑھنے کے لیے دوبارہ کوشش کریں۔",
    "بڑے غذائی اجزا کا اندراج محفوظ ہو گیا۔ کیلوریز معلوم نہیں ہیں۔",
    "کارروائی تیار ہونے کے بعد یہ ریکارڈ بدل گیا ہے۔ اسے دوبارہ دیکھیں۔",
    "آپ کا اکاؤنٹ بدل گیا ہے۔ موجودہ اکاؤنٹ کے لیے یہ کارروائی دوبارہ تیار کریں۔",
    "کارروائی محفوظ ہو گئی، لیکن اس کی موجودہ حالت کی تصدیق نہیں ہو سکی۔ دوبارہ کوشش کرنے سے پہلے اپنا ڈیٹا دیکھیں۔",
  ],
  "fa": [
    "نمای کلی",
    "عکس‌های پست",
    "خانه",
    "پست‌های خصوصی ناتمام",
    "ذخیرهٔ پروفایل و ایجاد کد BIL",
    "برای باز کردن پیش‌نویس‌های خصوصی‌تان وارد شوید.",
    "مجوزهای اقدامات مربی",
    "آمار",
    "{count} عکس",
    "تأییدها",
    "{count} پیش‌نویس حذف شود؟",
    "حذف انتخاب‌شده‌ها ({count})",
    "عملیات پیش‌نویس",
    "پیش‌نویس‌ها ({count})",
    "آخرین ذخیره {count} روز پیش",
    "آخرین ذخیره {count} ساعت پیش",
    "آخرین ذخیره {count} دقیقه پیش",
    "اشاره‌ها",
    "تأییدها، اشاره‌ها و نظرهای جدید اینجا نمایش داده می‌شوند.",
    "هنوز پیش‌نویسی ذخیره نشده است",
    "تنظیمات اعلان‌ها",
    "اعلان‌ها در دسترس نیستند",
    "اکنون",
    "پاداش به موجودی هوش مصنوعی شما افزوده شد",
    "پست‌های ناتمام را ذخیره کنید و بعداً از همین‌جا ادامه دهید.",
    "همین الان ذخیره شد",
    "انتخاب",
    "این کار فقط پیش‌نویس‌های خصوصی انتخاب‌شده را حذف می‌کند.",
    "همهٔ اعلان‌های جدید را دیده‌اید",
    "پیش‌تر",
    "حساب شما تغییر کرده است. برای ادامه به انجمن برگردید.",
    "متن را به 1200 نویسه محدود کنید. متن شما حفظ شده است.",
    "اعتبارسنجی اقدام انجام نشد. از مربی بخواهید آن را دوباره آماده کند.",
    "این روز بسته شده است. پیش از تغییر، آن را در گزارش روزانه دوباره باز کنید.",
    "این وعده از زمان آماده‌سازی اقدام تغییر کرده است. دوباره آن را بررسی کنید.",
    "حساب تغییر کرده است. مربی هوش مصنوعی را دوباره باز کنید و تلاش کنید.",
    "این اقدام قبلاً برگردانده شده بود. چیزی دوباره اضافه نشد.",
    "لغو تغییر کامل نشد. داده‌های فعلی خود را بررسی کنید.",
    "ورودی فقط کالری ذخیره شد. سایر مواد مغذی نامشخص هستند.",
    "تغییر ذخیره شد، اما رسید آن بارگیری نشد. برای خواندن نتیجهٔ ذخیره‌شده دوباره تلاش کنید.",
    "ورودی درشت‌مغذی‌ها ذخیره شد. کالری نامشخص است.",
    "این رکورد از زمان آماده‌سازی عملیات تغییر کرده است. دوباره آن را بررسی کنید.",
    "حساب شما تغییر کرده است. این عملیات را برای حساب فعلی دوباره آماده کنید.",
    "عملیات ذخیره شد، اما وضعیت فعلی آن قابل تأیید نبود. پیش از تلاش دوباره، داده‌های خود را بررسی کنید.",
  ],
  "hi": [
    "अवलोकन",
    "पोस्ट की तस्वीरें",
    "मुख्य पृष्ठ",
    "निजी अधूरी पोस्ट",
    "प्रोफ़ाइल सहेजें और BIL कोड बनाएँ",
    "अपने निजी ड्राफ़्ट खोलने के लिए साइन इन करें।",
    "कोच की कार्रवाइयों की अनुमतियाँ",
    "आँकड़े",
    "{count} तस्वीरें",
    "स्वीकृतियाँ",
    "{count} ड्राफ़्ट मिटाएँ?",
    "चुने हुए मिटाएँ ({count})",
    "ड्राफ़्ट की कार्रवाइयाँ",
    "ड्राफ़्ट ({count})",
    "आखिरी बार {count} दिन पहले सहेजा गया",
    "आखिरी बार {count} घंटे पहले सहेजा गया",
    "आखिरी बार {count} मिनट पहले सहेजा गया",
    "उल्लेख",
    "नई स्वीकृतियाँ, उल्लेख और टिप्पणियाँ यहाँ दिखाई देंगी।",
    "अभी कोई ड्राफ़्ट सहेजा नहीं गया है",
    "सूचना सेटिंग",
    "सूचनाएँ उपलब्ध नहीं हैं",
    "अभी",
    "इनाम आपके AI बैलेंस में जोड़ दिया गया",
    "अधूरी पोस्ट सहेजें और बाद में यहीं से जारी रखें।",
    "अभी-अभी सहेजा गया",
    "चुनें",
    "इससे केवल चुने हुए निजी ड्राफ़्ट मिटेंगे।",
    "आपने सभी नई सूचनाएँ देख ली हैं",
    "पहले की सूचनाएँ",
    "आपका खाता बदल गया है। जारी रखने के लिए समुदाय में लौटें।",
    "टेक्स्ट को 1200 वर्णों तक सीमित रखें। आपका टेक्स्ट सुरक्षित रखा गया है।",
    "कार्रवाई की पुष्टि नहीं हो सकी। कोच से इसे फिर से तैयार करने को कहें।",
    "यह दिन बंद है। बदलाव करने से पहले इसे दैनिक लॉग में दोबारा खोलें।",
    "कार्रवाई तैयार होने के बाद यह भोजन बदल गया है। इसकी फिर से समीक्षा करें।",
    "खाता बदल गया है। AI कोच दोबारा खोलें और फिर कोशिश करें।",
    "यह कार्रवाई पहले ही वापस ली जा चुकी है। कुछ भी दोबारा नहीं जोड़ा गया।",
    "पूर्ववत करना पूरा नहीं हो सका। अपना मौजूदा डेटा देखें।",
    "केवल कैलोरी वाली प्रविष्टि सहेजी गई। अन्य पोषक तत्व अज्ञात हैं।",
    "बदलाव सेव हो गया, लेकिन उसकी रसीद लोड नहीं हो सकी। सेव किया गया परिणाम पढ़ने के लिए फिर कोशिश करें।",
    "मैक्रोन्यूट्रिएंट की प्रविष्टि सेव हो गई। कैलोरी अज्ञात हैं।",
    "कार्रवाई तैयार होने के बाद यह रिकॉर्ड बदल गया है। इसे फिर से देखें।",
    "आपका खाता बदल गया है। मौजूदा खाते के लिए इस कार्रवाई को फिर तैयार करें।",
    "कार्रवाई सेव हो गई, लेकिन उसकी मौजूदा स्थिति सत्यापित नहीं हो सकी। फिर कोशिश करने से पहले अपना डेटा देखें।",
  ],
  "id": [
    "Ringkasan",
    "Foto postingan",
    "Beranda",
    "Postingan pribadi yang belum selesai",
    "Simpan profil dan buat Kode BIL",
    "Masuk untuk membuka draf pribadi Anda.",
    "Izin tindakan pelatih",
    "Statistik",
    "{count} foto",
    "Persetujuan",
    "Hapus {count} draf?",
    "Hapus yang dipilih ({count})",
    "Tindakan draf",
    "Draf ({count})",
    "Terakhir disimpan {count} hari lalu",
    "Terakhir disimpan {count} jam lalu",
    "Terakhir disimpan {count} menit lalu",
    "Sebutan",
    "Persetujuan, sebutan, dan komentar baru akan muncul di sini.",
    "Belum ada draf tersimpan",
    "Pengaturan notifikasi",
    "Notifikasi tidak tersedia",
    "Sekarang",
    "Hadiah ditambahkan ke saldo AI Anda",
    "Simpan postingan yang belum selesai dan lanjutkan di sini nanti.",
    "Baru saja disimpan",
    "Pilih",
    "Ini hanya menghapus draf pribadi yang dipilih.",
    "Anda sudah melihat semua notifikasi terbaru",
    "Sebelumnya",
    "Akun Anda telah berubah. Kembali ke Komunitas untuk melanjutkan.",
    "Batasi teks hingga 1200 karakter. Teks Anda tetap dipertahankan.",
    "Tindakan tidak dapat divalidasi. Minta Pelatih menyiapkannya kembali.",
    "Hari tersebut telah ditutup. Buka kembali di Catatan Harian sebelum membuat perubahan.",
    "Makanan ini berubah sejak tindakan disiapkan. Tinjau kembali.",
    "Akun telah berganti. Buka kembali Pelatih AI dan coba lagi.",
    "Tindakan ini sudah dibatalkan sebelumnya. Tidak ada yang ditambahkan kembali.",
    "Pembatalan tidak dapat diselesaikan. Tinjau data Anda saat ini.",
    "Entri khusus kalori disimpan. Zat gizi lainnya tidak diketahui.",
    "Perubahan telah disimpan, tetapi bukti pencatatannya tidak dapat dimuat. Coba lagi untuk membaca hasil yang tersimpan.",
    "Entri makronutrien disimpan. Kalori belum diketahui.",
    "Catatan ini berubah sejak tindakan disiapkan. Tinjau kembali.",
    "Akun Anda berubah. Siapkan tindakan ini lagi untuk akun saat ini.",
    "Tindakan telah disimpan, tetapi statusnya saat ini tidak dapat diverifikasi. Tinjau data Anda sebelum mencoba lagi.",
  ],
};
