part of 'runtime_copy_integration_gap.dart';

const _integrationSouth = <String, List<String>>{
  "ur": [
    "سرور کی رسید سے +5 AI ٹوکن کی تصدیق ہوئی",
    "منظور شدہ اہل پوسٹ کو +5 AI ٹوکن صرف اسی صورت میں مل سکتے ہیں جب سرور کی انعامی رسید اس کی تصدیق کرے۔ صرف منظوری انعام کی ضمانت نہیں؛ روزانہ کی حد لاگو ہو سکتی ہے۔ AI ٹوکن BIL Gold نہیں اور انہیں نقد نہیں کیا جا سکتا۔ مسودہ کھولنے یا محفوظ کرنے سے کچھ نہیں ملتا۔",
    "منظور شدہ · AI ٹوکن ملنے کی تصدیق نہیں ہوئی",
    "منسوخ کریں — محفوظ نہ کریں",
    "ڈسپلے کی اکائیاں اپ ڈیٹ ہو گئیں۔",
    "یہ یادداشت بھلا دیں؟",
    "پوشیدہ",
    "پسند کردہ پوسٹ",
    "پسندیدگیاں نجی ہیں۔ صرف یہ رکن انہیں دیکھ سکتا ہے۔",
    "مزید پسندیدگیاں لوڈ کریں",
    "مزید میڈیا لوڈ کریں",
    "اس پروفائل پر میڈیا نجی ہے۔",
    "متعدد انتخاب",
    "ابھی کوئی نظر آنے والی پسند کردہ پوسٹ نہیں۔",
    "ابھی کوئی نظر آنے والا میڈیا نہیں۔",
    "ابھی کوئی نظر آنے والا جواب نہیں۔",
    "اطلاعات کی اجازت نہیں ملی، اس لیے یاد دہانی نہیں بدلی۔",
    "صرف منتخب کردہ یادداشت حذف ہوگی۔",
    "نگرانی کا نتیجہ دیکھنے کے لیے پوسٹ کھولیں",
    "پوسٹ منظور ہوگئی۔ اس فیصلے پر AI ٹوکن دینے کی تصدیق نہیں ہوئی۔",
    "پوسٹ کے جائزے کا نتیجہ",
    "صرف پڑھنے کا موڈ۔ کوئی کھانا درج نہیں ہوا۔",
    "یاد دہانی اپ ڈیٹ اور تصدیق ہوگئی۔",
    "اس پروفائل پر جوابات نجی ہیں۔",
    "محفوظ شدہ نتیجہ پڑھنے کے لیے جائزہ دوبارہ آزمائیں۔",
    "واحد انتخاب",
    "ڈیوائس شیڈیولر میں یاد دہانی کی تصدیق نہ ہوسکی۔ پچھلی ترتیب بحال کردی گئی۔",
    "جائزے کے بعد یہ یادداشت بدل گئی ہے۔ ریفریش کرکے دوبارہ منتخب کریں۔",
    "موجودہ اکاؤنٹ کے لیے یہ پوسٹ لوڈ نہ ہوسکی۔",
    "اس کارروائی کے دوران لکھنے کی اجازت بدل گئی۔ حفاظتی ترتیب دیکھیں اور کارروائی دوبارہ تیار کریں۔",
    "آپ کی پوسٹ میں تبدیلیاں درکار ہیں",
    "آپ کی پوسٹ منظور ہوگئی",
    "آپ کی پوسٹ منظور ہوگئی · +5 AI ٹوکن",
  ],
  "fa": [
    "+5 توکن هوش مصنوعی با رسید سرور تأیید شد",
    "یک پست تأییدشده و واجد شرایط تنها زمانی ممکن است +5 توکن هوش مصنوعی بگیرد که رسید پاداش سرور اعطا را تأیید کند. تأیید پست به‌تنهایی تضمین پاداش نیست و محدودیت روزانه ممکن است اعمال شود. توکن‌های هوش مصنوعی BIL Gold نیستند و نقد نمی‌شوند. باز کردن یا ذخیرهٔ پیش‌نویس پاداشی ندارد.",
    "تأیید شد · اعطای توکن هوش مصنوعی تأیید نشده",
    "لغو — ذخیره نکن",
    "واحدهای نمایش به‌روزرسانی شد.",
    "این خاطره فراموش شود؟",
    "پنهان",
    "پست پسندیده‌شده",
    "پسندیدن‌ها خصوصی هستند. فقط همین عضو آن‌ها را می‌بیند.",
    "بارگیری پسندیدن‌های بیشتر",
    "بارگیری رسانه‌های بیشتر",
    "رسانه‌ها در این نمایه خصوصی‌اند.",
    "چندگزینه‌ای",
    "هنوز پست پسندیده‌شدهٔ قابل‌نمایشی نیست.",
    "هنوز رسانهٔ قابل‌نمایشی نیست.",
    "هنوز پاسخی برای نمایش نیست.",
    "مجوز اعلان داده نشد، پس یادآور تغییر نکرد.",
    "فقط خاطرهٔ انتخاب‌شده حذف می‌شود.",
    "برای بررسی نتیجهٔ نظارت، پست را باز کنید",
    "پست تأیید شد. اعطای توکن هوش مصنوعی برای این تصمیم تأیید نشده است.",
    "نتیجهٔ بررسی پست",
    "حالت فقط‌خواندنی. غذایی ثبت نشد.",
    "یادآور به‌روزرسانی و تأیید شد.",
    "پاسخ‌ها در این نمایه خصوصی‌اند.",
    "برای خواندن نتیجهٔ ذخیره‌شده، بررسی را دوباره انجام دهید.",
    "تک‌گزینه‌ای",
    "تأیید یادآور در زمان‌بند دستگاه ممکن نشد. تنظیم قبلی بازیابی شد.",
    "این خاطره پس از بررسی تغییر کرده است. تازه‌سازی کنید و دوباره انتخاب کنید.",
    "این پست برای حساب فعلی بارگیری نشد.",
    "مجوز نوشتن در حین عملیات تغییر کرد. تنظیم حفاظتی را بررسی و عملیات را دوباره آماده کنید.",
    "پست شما نیاز به تغییر دارد",
    "پست شما تأیید شد",
    "پست شما تأیید شد · +5 توکن هوش مصنوعی",
  ],
  "hi": [
    "सर्वर रसीद से +5 AI टोकन की पुष्टि हुई",
    "स्वीकृत पात्र पोस्ट को +5 AI टोकन तभी मिल सकते हैं जब सर्वर की पुरस्कार रसीद उनकी मंज़ूरी की पुष्टि करे। केवल पोस्ट स्वीकृत होना टोकन की गारंटी नहीं है; दैनिक सीमा लागू हो सकती है। AI टोकन BIL Gold नहीं हैं और नकद नहीं किए जा सकते। ड्राफ़्ट खोलने या सहेजने पर कोई पुरस्कार नहीं मिलता।",
    "स्वीकृत · AI टोकन मिलने की पुष्टि नहीं हुई",
    "रद्द करें — सहेजें नहीं",
    "प्रदर्शन की इकाइयाँ अपडेट कर दी गई हैं।",
    "इस स्मृति को भूल जाएँ?",
    "छिपा हुआ",
    "पसंद किया गया पोस्ट",
    "लाइक निजी हैं। केवल यह सदस्य इन्हें देख सकता है।",
    "और लाइक लोड करें",
    "और मीडिया लोड करें",
    "इस प्रोफ़ाइल का मीडिया निजी है।",
    "एक से अधिक विकल्प",
    "अभी कोई दिखाई देने वाला पसंद किया गया पोस्ट नहीं है।",
    "अभी कोई दिखाई देने वाला मीडिया नहीं है।",
    "अभी कोई दिखाई देने वाला उत्तर नहीं है।",
    "सूचनाओं की अनुमति नहीं मिली, इसलिए रिमाइंडर नहीं बदला गया।",
    "केवल चुनी गई स्मृति हटाई जाएगी।",
    "मॉडरेशन का परिणाम देखने के लिए पोस्ट खोलें",
    "पोस्ट स्वीकृत। इस निर्णय के लिए AI टोकन दिए जाने की पुष्टि नहीं हुई।",
    "पोस्ट समीक्षा का परिणाम",
    "केवल-पढ़ने का मोड। कोई भोजन दर्ज नहीं हुआ।",
    "रिमाइंडर अपडेट और सत्यापित किया गया।",
    "इस प्रोफ़ाइल पर उत्तर निजी हैं।",
    "सहेजा गया परिणाम देखने के लिए समीक्षा फिर आज़माएँ।",
    "एकल विकल्प",
    "डिवाइस शेड्यूलर में रिमाइंडर सत्यापित नहीं हो सका। पिछली सेटिंग बहाल कर दी गई।",
    "समीक्षा के बाद यह स्मृति बदल गई है। रीफ़्रेश करके फिर चुनें।",
    "वर्तमान खाते के लिए यह पोस्ट लोड नहीं हो सका।",
    "कार्रवाई के दौरान लिखने की अनुमति बदल गई। सुरक्षा सेटिंग जाँचकर कार्रवाई दोबारा तैयार करें।",
    "आपके पोस्ट में बदलाव ज़रूरी हैं",
    "आपका पोस्ट स्वीकृत हो गया",
    "आपका पोस्ट स्वीकृत हो गया · +5 AI टोकन",
  ],
  "bn": [
    "সার্ভারের রসিদে +5 AI টোকেন নিশ্চিত হয়েছে",
    "অনুমোদিত যোগ্য পোস্ট কেবল সার্ভারের পুরস্কারের রসিদে বরাদ্দ নিশ্চিত হলে +5 AI টোকেন পেতে পারে। শুধু অনুমোদন পুরস্কারের নিশ্চয়তা দেয় না; দৈনিক সীমা প্রযোজ্য হতে পারে। AI টোকেন BIL Gold নয় এবং নগদে ভাঙানো যায় না। খসড়া খোলা বা সংরক্ষণে কোনো পুরস্কার মেলে না।",
    "অনুমোদিত · AI টোকেন দেওয়া নিশ্চিত হয়নি",
    "বাতিল — সংরক্ষণ করবেন না",
    "প্রদর্শনের একক আপডেট হয়েছে।",
    "এই স্মৃতি ভুলে যাবেন?",
    "লুকানো",
    "পছন্দ করা পোস্ট",
    "লাইক ব্যক্তিগত। শুধু এই সদস্য সেগুলো দেখতে পারবেন।",
    "আরও লাইক লোড করুন",
    "আরও মিডিয়া লোড করুন",
    "এই প্রোফাইলের মিডিয়া ব্যক্তিগত।",
    "একাধিক বিকল্প",
    "এখনও কোনো দৃশ্যমান পছন্দ করা পোস্ট নেই।",
    "এখনও কোনো দৃশ্যমান মিডিয়া নেই।",
    "এখনও কোনো দৃশ্যমান উত্তর নেই।",
    "বিজ্ঞপ্তির অনুমতি দেওয়া হয়নি, তাই রিমাইন্ডার বদলানো হয়নি।",
    "শুধু আপনার নির্বাচিত স্মৃতিটিই মুছে ফেলা হবে।",
    "মডারেশনের ফল দেখতে পোস্টটি খুলুন",
    "পোস্ট অনুমোদিত। এই সিদ্ধান্তে AI টোকেন দেওয়ার নিশ্চয়তা মেলেনি।",
    "পোস্ট পর্যালোচনার ফলাফল",
    "শুধু-পাঠ মোড। কোনো খাবার নথিভুক্ত হয়নি।",
    "রিমাইন্ডার আপডেট ও যাচাই হয়েছে।",
    "এই প্রোফাইলে উত্তর ব্যক্তিগত।",
    "সংরক্ষিত ফল পড়তে এই পর্যালোচনা আবার চেষ্টা করুন।",
    "একটি বিকল্প",
    "ডিভাইসের শিডিউলারে রিমাইন্ডার যাচাই করা যায়নি। আগের সেটিং ফিরিয়ে দেওয়া হয়েছে।",
    "পর্যালোচনার পরে স্মৃতি বদলেছে। রিফ্রেশ করে আবার নির্বাচন করুন।",
    "বর্তমান অ্যাকাউন্টে এই পোস্ট লোড করা যায়নি।",
    "কাজ চলাকালে লেখার অনুমতি বদলেছে। সুরক্ষা সেটিং দেখে আবার প্রস্তুত করুন।",
    "আপনার পোস্টে পরিবর্তন প্রয়োজন",
    "আপনার পোস্ট অনুমোদিত হয়েছে",
    "আপনার পোস্ট অনুমোদিত হয়েছে · +5 AI টোকেন",
  ],
  "id": [
    "+5 token AI dikonfirmasi melalui bukti server",
    "Postingan yang layak dan disetujui hanya dapat memperoleh +5 token AI jika bukti hadiah server mengonfirmasi pemberiannya. Persetujuan saja tidak menjamin token; batas harian mungkin berlaku. Token AI bukan BIL Gold dan tidak dapat diuangkan. Membuka atau menyimpan draf tidak memberikan hadiah.",
    "Disetujui · pemberian token AI belum dikonfirmasi",
    "Batal — jangan simpan",
    "Satuan tampilan diperbarui.",
    "Lupakan memori ini?",
    "Tersembunyi",
    "Postingan yang disukai",
    "Suka bersifat privat. Hanya anggota ini yang dapat melihatnya.",
    "Muat lebih banyak suka",
    "Muat lebih banyak media",
    "Media di profil ini bersifat privat.",
    "Pilihan ganda",
    "Belum ada postingan disukai yang terlihat.",
    "Belum ada media yang terlihat.",
    "Belum ada balasan yang terlihat.",
    "Izin notifikasi tidak diberikan sehingga pengingat tidak diubah.",
    "Hanya memori yang dipilih yang akan dihapus.",
    "Buka postingan untuk meninjau hasil moderasi",
    "Postingan disetujui. Pemberian token AI untuk keputusan ini belum dikonfirmasi.",
    "Hasil peninjauan postingan",
    "Mode hanya-baca. Tidak ada makanan yang dicatat.",
    "Pengingat diperbarui dan diverifikasi.",
    "Balasan bersifat privat di profil ini.",
    "Coba lagi peninjauan ini untuk membaca hasil yang tersimpan.",
    "Pilihan tunggal",
    "Pengingat tidak dapat diverifikasi di penjadwal perangkat. Pengaturan sebelumnya dipulihkan.",
    "Memori ini berubah setelah ditinjau. Segarkan dan pilih lagi.",
    "Postingan ini tidak dapat dimuat untuk akun saat ini.",
    "Izin menulis berubah selama tindakan ini. Periksa pengaturan perlindungan dan siapkan ulang tindakan.",
    "Postingan Anda perlu diperbaiki",
    "Postingan Anda disetujui",
    "Postingan Anda disetujui · +5 token AI",
  ],
  "ms": [
    "+5 token AI disahkan melalui resit pelayan",
    "Siaran yang layak dan diluluskan hanya boleh menerima +5 token AI jika resit ganjaran pelayan mengesahkan pemberiannya. Kelulusan sahaja tidak menjamin token; had harian mungkin dikenakan. Token AI bukan BIL Gold dan tidak boleh ditukar kepada wang tunai. Membuka atau menyimpan draf tidak memberi ganjaran.",
    "Diluluskan · pemberian token AI belum disahkan",
    "Batal — jangan simpan",
    "Unit paparan dikemas kini.",
    "Lupakan memori ini?",
    "Tersembunyi",
    "Siaran yang disukai",
    "Tanda suka adalah peribadi. Hanya ahli ini boleh melihatnya.",
    "Muatkan lagi tanda suka",
    "Muatkan lagi media",
    "Media pada profil ini adalah peribadi.",
    "Pilihan berbilang",
    "Belum ada siaran disukai yang kelihatan.",
    "Belum ada media yang kelihatan.",
    "Belum ada balasan yang kelihatan.",
    "Kebenaran pemberitahuan tidak diberikan, jadi peringatan tidak diubah.",
    "Hanya memori yang dipilih akan dipadamkan.",
    "Buka siaran untuk menyemak keputusan penyederhanaan",
    "Siaran diluluskan. Pemberian token AI bagi keputusan ini belum disahkan.",
    "Keputusan semakan siaran",
    "Mod baca sahaja. Tiada makanan direkodkan.",
    "Peringatan dikemas kini dan disahkan.",
    "Balasan adalah peribadi pada profil ini.",
    "Cuba semakan ini sekali lagi untuk membaca keputusan tersimpan.",
    "Pilihan tunggal",
    "Peringatan tidak dapat disahkan dalam penjadual peranti. Tetapan sebelumnya dipulihkan.",
    "Memori ini berubah selepas semakan. Segar semula dan pilih sekali lagi.",
    "Siaran ini tidak dapat dimuatkan untuk akaun semasa.",
    "Kebenaran menulis berubah semasa tindakan. Semak tetapan perlindungan dan sediakan tindakan semula.",
    "Siaran anda perlu diubah",
    "Siaran anda telah diluluskan",
    "Siaran anda telah diluluskan · +5 token AI",
  ],
  "vi": [
    "+5 token AI đã được xác nhận qua biên nhận máy chủ",
    "Bài đăng đủ điều kiện và được phê duyệt chỉ có thể nhận +5 token AI khi biên nhận thưởng từ máy chủ xác nhận việc cấp thưởng. Chỉ được phê duyệt không đảm bảo nhận token; có thể áp dụng giới hạn hằng ngày. Token AI không phải BIL Gold và không thể đổi ra tiền. Mở hoặc lưu bản nháp không nhận được thưởng.",
    "Đã duyệt · chưa xác nhận cấp token AI",
    "Hủy — không lưu",
    "Đã cập nhật đơn vị hiển thị.",
    "Quên ký ức này?",
    "Đã ẩn",
    "Bài đăng đã thích",
    "Lượt thích là riêng tư. Chỉ thành viên này xem được.",
    "Tải thêm lượt thích",
    "Tải thêm phương tiện",
    "Phương tiện trên hồ sơ này là riêng tư.",
    "Chọn nhiều đáp án",
    "Chưa có bài đăng đã thích nào hiển thị.",
    "Chưa có phương tiện nào hiển thị.",
    "Chưa có câu trả lời nào hiển thị.",
    "Chưa được cấp quyền thông báo nên lời nhắc không thay đổi.",
    "Chỉ ký ức bạn đã chọn sẽ bị xóa.",
    "Mở bài đăng để xem kết quả kiểm duyệt",
    "Bài đăng được phê duyệt. Chưa xác nhận cấp token AI cho quyết định này.",
    "Kết quả duyệt bài đăng",
    "Chế độ chỉ đọc. Chưa ghi nhận món ăn nào.",
    "Đã cập nhật và xác minh lời nhắc.",
    "Các câu trả lời trên hồ sơ này là riêng tư.",
    "Thử xem lại để đọc kết quả đã lưu.",
    "Chọn một đáp án",
    "Không thể xác minh lời nhắc trong bộ lập lịch của thiết bị. Đã khôi phục cài đặt trước đó.",
    "Ký ức này đã thay đổi sau khi xem xét. Làm mới và chọn lại.",
    "Không thể tải bài đăng này cho tài khoản hiện tại.",
    "Quyền ghi thay đổi trong khi thực hiện. Kiểm tra thiết lập bảo vệ rồi chuẩn bị lại thao tác.",
    "Bài đăng của bạn cần chỉnh sửa",
    "Bài đăng của bạn đã được duyệt",
    "Bài đăng của bạn đã được duyệt · +5 token AI",
  ],
  "th": [
    "ยืนยัน +5 โทเคน AI ด้วยใบรับรองจากเซิร์ฟเวอร์",
    "โพสต์ที่มีสิทธิ์และได้รับการอนุมัติจะได้ +5 โทเคน AI ก็ต่อเมื่อใบรับรองรางวัลจากเซิร์ฟเวอร์ยืนยันการมอบรางวัล การอนุมัติเพียงอย่างเดียวไม่รับประกันว่าจะได้โทเคน และอาจมีขีดจำกัดรายวัน โทเคน AI ไม่ใช่ BIL Gold และไม่สามารถแลกเป็นเงินสด การเปิดหรือบันทึกฉบับร่างไม่ได้รางวัล",
    "อนุมัติแล้ว · ยังไม่ยืนยันการมอบโทเคน AI",
    "ยกเลิก — ไม่บันทึก",
    "อัปเดตหน่วยที่แสดงแล้ว",
    "ลืมความทรงจำนี้หรือไม่?",
    "ซ่อนอยู่",
    "โพสต์ที่ถูกใจ",
    "การถูกใจเป็นส่วนตัว มีเพียงสมาชิกคนนี้เท่านั้นที่ดูได้",
    "โหลดการถูกใจเพิ่มเติม",
    "โหลดสื่อเพิ่มเติม",
    "สื่อในโปรไฟล์นี้เป็นส่วนตัว",
    "เลือกได้หลายข้อ",
    "ยังไม่มีโพสต์ที่ถูกใจที่มองเห็นได้",
    "ยังไม่มีสื่อที่มองเห็นได้",
    "ยังไม่มีคำตอบที่มองเห็นได้",
    "ไม่ได้รับอนุญาตให้แจ้งเตือน จึงไม่ได้เปลี่ยนการเตือนความจำ",
    "จะลบเฉพาะความทรงจำที่คุณเลือกเท่านั้น",
    "เปิดโพสต์เพื่อดูผลการตรวจสอบเนื้อหา",
    "โพสต์ได้รับอนุมัติ แต่ยังไม่ยืนยันการมอบโทเคน AI สำหรับการตัดสินใจนี้",
    "ผลการตรวจสอบโพสต์",
    "โหมดอ่านอย่างเดียว ไม่มีการบันทึกอาหาร",
    "อัปเดตและยืนยันการเตือนความจำแล้ว",
    "การตอบกลับในโปรไฟล์นี้เป็นส่วนตัว",
    "ลองตรวจสอบอีกครั้งเพื่ออ่านผลที่บันทึกไว้",
    "เลือกได้ข้อเดียว",
    "ไม่สามารถยืนยันการเตือนความจำในตัวกำหนดเวลาของอุปกรณ์ได้ จึงคืนค่าการตั้งค่าก่อนหน้า",
    "ความทรงจำนี้เปลี่ยนหลังการตรวจสอบ โปรดรีเฟรชแล้วเลือกอีกครั้ง",
    "ไม่สามารถโหลดโพสต์นี้สำหรับบัญชีปัจจุบัน",
    "สิทธิ์เขียนเปลี่ยนระหว่างการทำงาน โปรดตรวจสอบการตั้งค่าการป้องกันแล้วเตรียมดำเนินการใหม่",
    "โพสต์ของคุณต้องแก้ไข",
    "โพสต์ของคุณได้รับอนุมัติแล้ว",
    "โพสต์ของคุณได้รับอนุมัติแล้ว · +5 โทเคน AI",
  ],
};
