import 'bil_locale_policy.dart';

/// Copy introduced by the reference-parity and Coach starter surfaces.
/// Rows use the same order as sources; no missing row falls back to English.
abstract final class ReferenceDeltaRuntimeCopy {
  static const sources = <String>[
    "Based on my selected BIL context, what is the single best thing to focus on next and why?",
    "Check nutrition",
    "Choose a starting point. The Coach uses only the context available to it.",
    "Circle",
    "Collab",
    "Community profile and actions",
    "Community reward task",
    "Creator rewards",
    "Explain my recorded sleep trend and what it may mean for today, without inventing missing data.",
    "Explain sleep",
    "Media",
    "Next best focus",
    "Open rewards",
    "Review my day from my saved BIL data and tell me the most useful next step.",
    "Review today’s nutrition from my saved BIL data. What stands out and what should I focus on next?",
    "Start with your real BIL data",
    "Topics you might like",
  ];

  static const rows = <String, List<String>>{
    'ar': [
      "بناءً على سياق BIL الذي اخترته، ما أفضل شيء واحد أركز عليه الآن ولماذا؟",
      "راجع التغذية",
      "اختر نقطة بداية. يستخدم المدرب فقط السياق المتاح له.",
      "الدائرة",
      "تعاون",
      "ملف المجتمع وإجراءاته",
      "مهمة مكافآت المجتمع",
      "مكافآت صانع المحتوى",
      "اشرح اتجاه نومي المسجل وما قد يعنيه لليوم، من دون اختراع بيانات مفقودة.",
      "اشرح نومي",
      "وسائط",
      "أفضل تركيز تالٍ",
      "فتح المكافآت",
      "راجع يومي من بيانات BIL المحفوظة وأخبرني بأكثر خطوة مفيدة الآن.",
      "راجع تغذية اليوم من بيانات BIL المحفوظة. ما الأبرز وما الذي أركز عليه الآن؟",
      "ابدأ من بيانات BIL الحقيقية",
      "مواضيع قد تعجبك",
    ],
    'fr': [
      "D’après le contexte BIL que j’ai sélectionné, quelle est la priorité la plus utile maintenant, et pourquoi ?",
      "Examiner la nutrition",
      "Choisissez un point de départ. Le coach utilise uniquement le contexte dont il dispose.",
      "Cercle",
      "Collaboration",
      "Profil et actions de la communauté",
      "Mission de récompense communautaire",
      "Récompenses des créateurs",
      "Explique la tendance de mon sommeil enregistré et ce qu’elle peut signifier pour aujourd’hui, sans inventer les données manquantes.",
      "Expliquer mon sommeil",
      "Contenu multimédia",
      "Ma prochaine priorité",
      "Ouvrir les récompenses",
      "Fais le bilan de ma journée à partir de mes données BIL enregistrées et indique-moi la prochaine étape la plus utile.",
      "Examine ma nutrition d’aujourd’hui à partir de mes données BIL enregistrées. Que remarques-tu et quelle devrait être ma prochaine priorité ?",
      "Partez de vos données BIL réelles",
      "Des sujets qui pourraient vous plaire",
    ],
    'es': [
      "Según el contexto de BIL que he seleccionado, ¿cuál es la prioridad más útil ahora y por qué?",
      "Revisar la nutrición",
      "Elige un punto de partida. El entrenador solo utiliza el contexto disponible.",
      "Círculo",
      "Colaboración",
      "Perfil y acciones de la comunidad",
      "Tarea de recompensa de la comunidad",
      "Recompensas para creadores",
      "Explica la tendencia de mi sueño registrado y lo que podría significar para hoy, sin inventar datos que falten.",
      "Explicar mi sueño",
      "Multimedia",
      "Mi próxima prioridad",
      "Abrir recompensas",
      "Revisa mi día a partir de mis datos guardados en BIL e indícame el siguiente paso más útil.",
      "Revisa la nutrición de hoy a partir de mis datos guardados en BIL. ¿Qué destaca y en qué debería centrarme ahora?",
      "Empieza con tus datos reales de BIL",
      "Temas que podrían gustarte",
    ],
    'tr': [
      "Seçtiğim BIL bağlamına göre şimdi odaklanmam gereken en yararlı tek şey nedir ve neden?",
      "Beslenmeyi incele",
      "Bir başlangıç noktası seçin. Koç yalnızca mevcut bağlamı kullanır.",
      "Çevre",
      "İş birliği",
      "Topluluk profili ve işlemleri",
      "Topluluk ödül görevi",
      "İçerik üreticisi ödülleri",
      "Eksik verileri uydurmadan, kayıtlı uyku eğilimimi ve bugün için ne anlama gelebileceğini açıkla.",
      "Uykumu açıkla",
      "Medya",
      "Sıradaki önceliğim",
      "Ödülleri aç",
      "Kayıtlı BIL verilerimden günümü değerlendir ve sıradaki en yararlı adımı söyle.",
      "Kayıtlı BIL verilerimden bugünkü beslenmemi incele. Ne dikkat çekiyor ve şimdi neye odaklanmalıyım?",
      "Gerçek BIL verilerinizle başlayın",
      "İlginizi çekebilecek konular",
    ],
    'de': [
      "Was sollte auf Grundlage meines ausgewählten BIL-Kontexts meine nächste wichtigste Priorität sein, und warum?",
      "Ernährung prüfen",
      "Wähle einen Einstieg. Der Coach verwendet nur den verfügbaren Kontext.",
      "Gruppe",
      "Zusammenarbeit",
      "Community-Profil und Aktionen",
      "Community-Belohnungsaufgabe",
      "Belohnungen für Beitragende",
      "Erkläre meinen aufgezeichneten Schlaftrend und was er für heute bedeuten könnte, ohne fehlende Daten zu erfinden.",
      "Meinen Schlaf erklären",
      "Medien",
      "Meine nächste Priorität",
      "Belohnungen öffnen",
      "Werte meinen Tag anhand meiner gespeicherten BIL-Daten aus und nenne mir den nächsten sinnvollen Schritt.",
      "Prüfe meine heutige Ernährung anhand meiner gespeicherten BIL-Daten. Was fällt auf und worauf sollte ich mich als Nächstes konzentrieren?",
      "Starte mit deinen tatsächlichen BIL-Daten",
      "Themen, die dir gefallen könnten",
    ],
    'it': [
      "In base al contesto BIL che ho selezionato, qual è la singola priorità più utile adesso e perché?",
      "Esamina l’alimentazione",
      "Scegli un punto di partenza. Il coach usa solo il contesto disponibile.",
      "Cerchia",
      "Collaborazione",
      "Profilo e azioni della community",
      "Attività premio della community",
      "Premi per i creator",
      "Spiega l’andamento del mio sonno registrato e cosa potrebbe significare per oggi, senza inventare i dati mancanti.",
      "Spiega il mio sonno",
      "Contenuti multimediali",
      "La prossima priorità",
      "Apri i premi",
      "Esamina la mia giornata usando i miei dati BIL salvati e indicami il prossimo passo più utile.",
      "Esamina l’alimentazione di oggi usando i miei dati BIL salvati. Cosa emerge e su cosa dovrei concentrarmi adesso?",
      "Inizia dai tuoi dati BIL reali",
      "Argomenti che potrebbero piacerti",
    ],
    'pt-BR': [
      "Com base no contexto do BIL que selecionei, qual deve ser minha próxima prioridade mais útil e por quê?",
      "Revisar a alimentação",
      "Escolha um ponto de partida. O coach usa apenas o contexto disponível.",
      "Círculo",
      "Colaboração",
      "Perfil e ações da comunidade",
      "Tarefa de recompensa da comunidade",
      "Recompensas para criadores",
      "Explique a tendência do meu sono registrado e o que ela pode significar para hoje, sem inventar dados ausentes.",
      "Explicar meu sono",
      "Mídia",
      "Minha próxima prioridade",
      "Abrir recompensas",
      "Revise meu dia usando meus dados salvos no BIL e indique o próximo passo mais útil.",
      "Revise a alimentação de hoje usando meus dados salvos no BIL. O que se destaca e em que devo focar agora?",
      "Comece com seus dados reais do BIL",
      "Assuntos que podem interessar a você",
    ],
    'pt-PT': [
      "Com base no contexto do BIL que selecionei, qual deve ser a minha próxima prioridade mais útil e porquê?",
      "Rever a alimentação",
      "Escolhe um ponto de partida. O coach utiliza apenas o contexto disponível.",
      "Círculo",
      "Colaboração",
      "Perfil e ações da comunidade",
      "Tarefa de recompensa da comunidade",
      "Recompensas para criadores",
      "Explica a tendência do meu sono registado e o que pode significar para hoje, sem inventar dados em falta.",
      "Explicar o meu sono",
      "Multimédia",
      "A minha próxima prioridade",
      "Abrir recompensas",
      "Revê o meu dia usando os meus dados guardados no BIL e indica o próximo passo mais útil.",
      "Revê a alimentação de hoje usando os meus dados guardados no BIL. O que se destaca e em que me devo concentrar agora?",
      "Começa pelos teus dados reais do BIL",
      "Temas que te podem interessar",
    ],
    'ur': [
      "میرے منتخب کردہ BIL سیاق کی بنیاد پر، اب مجھے کس ایک سب سے مفید چیز پر توجہ دینی چاہیے اور کیوں؟",
      "غذائیت کا جائزہ لیں",
      "شروع کرنے کے لیے ایک موضوع منتخب کریں۔ کوچ صرف دستیاب سیاق استعمال کرتا ہے۔",
      "حلقہ",
      "اشتراک",
      "کمیونٹی پروفائل اور اقدامات",
      "کمیونٹی انعامی کام",
      "تخلیق کاروں کے انعامات",
      "میرے ریکارڈ شدہ نیند کے رجحان اور آج کے لیے اس کے ممکنہ مطلب کی وضاحت کریں، غائب ڈیٹا گھڑے بغیر۔",
      "میری نیند کی وضاحت کریں",
      "میڈیا",
      "میری اگلی ترجیح",
      "انعامات کھولیں",
      "میرے محفوظ BIL ڈیٹا سے میرے دن کا جائزہ لیں اور اگلا سب سے مفید قدم بتائیں۔",
      "میرے محفوظ BIL ڈیٹا سے آج کی غذائیت کا جائزہ لیں۔ کیا نمایاں ہے اور اب مجھے کس چیز پر توجہ دینی چاہیے؟",
      "اپنے حقیقی BIL ڈیٹا سے شروع کریں",
      "وہ موضوعات جو آپ کو پسند آ سکتے ہیں",
    ],
    'fa': [
      "بر اساس زمینهٔ BIL که انتخاب کرده‌ام، اکنون مفیدترین اولویت برای تمرکز من چیست و چرا؟",
      "بررسی تغذیه",
      "یک نقطهٔ شروع انتخاب کنید. مربی فقط از زمینهٔ موجود استفاده می‌کند.",
      "گروه",
      "همکاری",
      "نمایه و اقدامات انجمن",
      "کار پاداش‌دار انجمن",
      "پاداش‌های تولیدکنندگان محتوا",
      "روند خواب ثبت‌شده‌ام و معنای احتمالی آن برای امروز را توضیح بده، بدون ساختن داده‌های مفقود.",
      "خوابم را توضیح بده",
      "رسانه",
      "اولویت بعدی من",
      "باز کردن پاداش‌ها",
      "روزم را بر اساس داده‌های ذخیره‌شدهٔ BIL بررسی کن و مفیدترین گام بعدی را بگو.",
      "تغذیهٔ امروز را بر اساس داده‌های ذخیره‌شدهٔ BIL بررسی کن. چه چیزی برجسته است و اکنون باید روی چه چیزی تمرکز کنم؟",
      "با داده‌های واقعی BIL خود شروع کنید",
      "موضوعاتی که شاید بپسندید",
    ],
    'hi': [
      "मेरे चुने हुए BIL संदर्भ के आधार पर, अब ध्यान देने के लिए सबसे उपयोगी एक चीज़ क्या है और क्यों?",
      "पोषण की समीक्षा करें",
      "शुरुआत के लिए एक विषय चुनें। कोच केवल उपलब्ध संदर्भ का उपयोग करता है।",
      "समूह",
      "सहयोग",
      "समुदाय प्रोफ़ाइल और कार्रवाइयाँ",
      "समुदाय पुरस्कार कार्य",
      "रचनाकारों के पुरस्कार",
      "मेरी दर्ज नींद के रुझान और आज के लिए उसके संभावित अर्थ को समझाएँ, बिना गायब डेटा गढ़े।",
      "मेरी नींद समझाएँ",
      "मीडिया",
      "मेरी अगली प्राथमिकता",
      "पुरस्कार खोलें",
      "मेरे सहेजे गए BIL डेटा से मेरे दिन की समीक्षा करें और सबसे उपयोगी अगला कदम बताएँ।",
      "मेरे सहेजे गए BIL डेटा से आज के पोषण की समीक्षा करें। क्या खास दिखता है और अब मुझे किस पर ध्यान देना चाहिए?",
      "अपने वास्तविक BIL डेटा से शुरुआत करें",
      "वे विषय जो आपको पसंद आ सकते हैं",
    ],
    'id': [
      "Berdasarkan konteks BIL yang saya pilih, apa satu hal paling bermanfaat untuk saya fokuskan berikutnya dan mengapa?",
      "Tinjau nutrisi",
      "Pilih titik awal. Pelatih hanya menggunakan konteks yang tersedia.",
      "Lingkaran",
      "Kolaborasi",
      "Profil dan tindakan komunitas",
      "Tugas hadiah komunitas",
      "Hadiah kreator",
      "Jelaskan tren tidur saya yang tercatat dan kemungkinan artinya untuk hari ini, tanpa mengarang data yang tidak tersedia.",
      "Jelaskan tidur saya",
      "Foto dan media",
      "Fokus terbaik berikutnya",
      "Buka hadiah",
      "Tinjau hari saya dari data BIL yang tersimpan dan beri tahu langkah berikutnya yang paling bermanfaat.",
      "Tinjau nutrisi hari ini dari data BIL yang tersimpan. Apa yang menonjol dan apa yang sebaiknya saya fokuskan berikutnya?",
      "Mulai dari data BIL Anda yang sebenarnya",
      "Topik yang mungkin Anda sukai",
    ],
    'ms': [
      "Berdasarkan konteks BIL yang saya pilih, apakah satu perkara paling berguna untuk diberi tumpuan seterusnya dan mengapa?",
      "Semak pemakanan",
      "Pilih titik permulaan. Jurulatih hanya menggunakan konteks yang tersedia.",
      "Kumpulan",
      "Kerjasama",
      "Profil dan tindakan komuniti",
      "Tugas ganjaran komuniti",
      "Ganjaran pencipta",
      "Terangkan trend tidur saya yang direkodkan dan maknanya yang mungkin untuk hari ini, tanpa mereka-reka data yang tiada.",
      "Terangkan tidur saya",
      "Foto dan media",
      "Tumpuan terbaik seterusnya",
      "Buka ganjaran",
      "Semak hari saya menggunakan data BIL yang disimpan dan beritahu langkah seterusnya yang paling berguna.",
      "Semak pemakanan hari ini menggunakan data BIL yang disimpan. Apakah yang menonjol dan apakah yang patut saya tumpukan seterusnya?",
      "Mulakan dengan data BIL anda yang sebenar",
      "Topik yang mungkin anda sukai",
    ],
    'ja': [
      "選択したBILの情報に基づいて、次に最も優先すべきことを一つ挙げ、その理由を教えてください。",
      "栄養を確認",
      "最初に確認したい項目を選んでください。コーチは利用可能な情報のみを使います。",
      "サークル",
      "コラボ",
      "コミュニティのプロフィールと操作",
      "コミュニティ報酬タスク",
      "クリエイター報酬",
      "記録された睡眠の傾向と、それが今日にとって意味する可能性を、欠けているデータを作り上げずに説明してください。",
      "睡眠を説明",
      "メディア",
      "次の最優先事項",
      "報酬を開く",
      "保存済みのBILデータから今日を振り返り、次に取るべき最も役立つ行動を教えてください。",
      "保存済みのBILデータから今日の栄養を確認してください。目立つ点と、次に重点を置くべきことは何ですか？",
      "実際のBILデータから始める",
      "おすすめのトピック",
    ],
    'ko': [
      "제가 선택한 BIL 맥락을 바탕으로 다음에 집중할 가장 유용한 한 가지는 무엇이며, 그 이유는 무엇인가요?",
      "영양 살펴보기",
      "시작할 주제를 선택하세요. 코치는 이용 가능한 맥락만 사용합니다.",
      "모임",
      "공동 작업",
      "커뮤니티 프로필 및 작업",
      "커뮤니티 보상 과제",
      "크리에이터 보상",
      "누락된 데이터를 지어내지 말고, 기록된 수면 추세와 그것이 오늘 어떤 의미를 가질 수 있는지 설명해 주세요.",
      "수면 설명하기",
      "미디어",
      "다음 최우선 과제",
      "보상 열기",
      "저장된 BIL 데이터로 제 하루를 살펴보고 가장 유용한 다음 단계를 알려 주세요.",
      "저장된 BIL 데이터로 오늘의 영양을 살펴봐 주세요. 무엇이 눈에 띄며 다음에는 어디에 집중해야 할까요?",
      "실제 BIL 데이터로 시작하세요",
      "관심 있을 만한 주제",
    ],
    'zh-Hans': [
      "根据我选择的 BIL 背景信息，接下来最值得关注的一件事是什么？为什么？",
      "查看营养",
      "选择一个起点。教练仅使用可用的背景信息。",
      "圈子",
      "协作",
      "社区个人资料与操作",
      "社区奖励任务",
      "创作者奖励",
      "请解释我记录的睡眠趋势及其对今天可能意味着什么，不要编造缺失的数据。",
      "解读睡眠",
      "媒体",
      "下一步重点",
      "打开奖励",
      "请根据我保存的 BIL 数据回顾我的一天，并告诉我接下来最有帮助的一步。",
      "请根据我保存的 BIL 数据查看今天的营养。有什么值得注意，接下来应该重点关注什么？",
      "从你的真实 BIL 数据开始",
      "你可能感兴趣的话题",
    ],
    'zh-Hant': [
      "根據我選擇的 BIL 背景資訊，接下來最值得關注的一件事是什麼？為什麼？",
      "查看營養",
      "選擇一個起點。教練僅使用可用的背景資訊。",
      "圈子",
      "協作",
      "社群個人資料與操作",
      "社群獎勵任務",
      "創作者獎勵",
      "請解釋我記錄的睡眠趨勢及其對今天可能意味著什麼，不要編造缺少的資料。",
      "解讀睡眠",
      "媒體",
      "下一步重點",
      "開啟獎勵",
      "請根據我儲存的 BIL 資料回顧我的一天，並告訴我接下來最有幫助的一步。",
      "請根據我儲存的 BIL 資料查看今天的營養。有什麼值得注意，接下來應該重點關注什麼？",
      "從你的真實 BIL 資料開始",
      "你可能感興趣的話題",
    ],
    'ru': [
      "На основе выбранного мной контекста BIL, на чём одном полезнее всего сосредоточиться дальше и почему?",
      "Проверить питание",
      "Выберите, с чего начать. Тренер использует только доступный контекст.",
      "Круг",
      "Совместная работа",
      "Профиль сообщества и действия",
      "Задание с наградой в сообществе",
      "Награды авторам",
      "Объясни тенденцию моего записанного сна и что она может означать для сегодняшнего дня, не выдумывая недостающие данные.",
      "Объяснить мой сон",
      "Медиа",
      "Следующий приоритет",
      "Открыть награды",
      "Проанализируй мой день по сохранённым данным BIL и подскажи наиболее полезный следующий шаг.",
      "Проанализируй сегодняшнее питание по сохранённым данным BIL. Что выделяется и на чём мне сосредоточиться дальше?",
      "Начните с ваших реальных данных BIL",
      "Темы, которые могут вам понравиться",
    ],
    'bn': [
      "আমার বেছে নেওয়া BIL প্রসঙ্গ অনুযায়ী, এরপর মনোযোগ দেওয়ার জন্য সবচেয়ে উপকারী একটি বিষয় কী এবং কেন?",
      "পুষ্টি পর্যালোচনা করুন",
      "শুরু করার জন্য একটি বিষয় বেছে নিন। কোচ শুধু উপলভ্য প্রসঙ্গ ব্যবহার করেন।",
      "গোষ্ঠী",
      "সহযোগিতা",
      "কমিউনিটি প্রোফাইল ও কার্যক্রম",
      "কমিউনিটির পুরস্কারের কাজ",
      "নির্মাতাদের পুরস্কার",
      "অনুপস্থিত তথ্য বানিয়ে না বলে, আমার নথিভুক্ত ঘুমের প্রবণতা এবং আজকের জন্য তার সম্ভাব্য অর্থ ব্যাখ্যা করুন।",
      "আমার ঘুম ব্যাখ্যা করুন",
      "মিডিয়া",
      "আমার পরবর্তী অগ্রাধিকার",
      "পুরস্কার খুলুন",
      "আমার সংরক্ষিত BIL তথ্য থেকে দিনটি পর্যালোচনা করুন এবং সবচেয়ে উপকারী পরবর্তী পদক্ষেপটি বলুন।",
      "আমার সংরক্ষিত BIL তথ্য থেকে আজকের পুষ্টি পর্যালোচনা করুন। কী লক্ষণীয় এবং এরপর কিসে মনোযোগ দেওয়া উচিত?",
      "আপনার বাস্তব BIL তথ্য দিয়ে শুরু করুন",
      "আপনার পছন্দ হতে পারে এমন বিষয়",
    ],
    'vi': [
      "Dựa trên ngữ cảnh BIL tôi đã chọn, điều hữu ích nhất cần tập trung tiếp theo là gì và vì sao?",
      "Xem lại dinh dưỡng",
      "Chọn điểm bắt đầu. Huấn luyện viên chỉ dùng ngữ cảnh hiện có.",
      "Nhóm",
      "Cộng tác",
      "Hồ sơ và thao tác cộng đồng",
      "Nhiệm vụ nhận thưởng cộng đồng",
      "Phần thưởng cho nhà sáng tạo",
      "Giải thích xu hướng giấc ngủ đã ghi lại của tôi và ý nghĩa có thể có đối với hôm nay, không bịa ra dữ liệu còn thiếu.",
      "Giải thích giấc ngủ",
      "Nội dung đa phương tiện",
      "Ưu tiên tiếp theo",
      "Mở phần thưởng",
      "Xem lại ngày của tôi từ dữ liệu BIL đã lưu và cho tôi biết bước tiếp theo hữu ích nhất.",
      "Xem lại dinh dưỡng hôm nay từ dữ liệu BIL đã lưu. Điều gì nổi bật và tôi nên tập trung vào đâu tiếp theo?",
      "Bắt đầu từ dữ liệu BIL thực tế của bạn",
      "Chủ đề bạn có thể thích",
    ],
    'th': [
      "จากบริบท BIL ที่ฉันเลือก สิ่งที่มีประโยชน์ที่สุดเพียงอย่างเดียวที่ควรให้ความสำคัญต่อไปคืออะไร และเพราะเหตุใด?",
      "ทบทวนโภชนาการ",
      "เลือกจุดเริ่มต้น โค้ชจะใช้เฉพาะบริบทที่มีอยู่เท่านั้น",
      "กลุ่ม",
      "ทำงานร่วมกัน",
      "โปรไฟล์และการดำเนินการในชุมชน",
      "ภารกิจรับรางวัลของชุมชน",
      "รางวัลสำหรับครีเอเตอร์",
      "อธิบายแนวโน้มการนอนที่บันทึกไว้ของฉันและความหมายที่อาจมีต่อวันนี้ โดยไม่แต่งข้อมูลที่ขาดหายขึ้นมา",
      "อธิบายการนอน",
      "สื่อ",
      "สิ่งสำคัญถัดไป",
      "เปิดรางวัล",
      "ทบทวนวันของฉันจากข้อมูล BIL ที่บันทึกไว้ และบอกขั้นตอนถัดไปที่มีประโยชน์ที่สุด",
      "ทบทวนโภชนาการวันนี้จากข้อมูล BIL ที่บันทึกไว้ มีอะไรโดดเด่นและฉันควรให้ความสำคัญกับอะไรต่อไป?",
      "เริ่มจากข้อมูล BIL จริงของคุณ",
      "หัวข้อที่คุณอาจชอบ",
    ],
    'pl': [
      "Na podstawie wybranego przeze mnie kontekstu BIL, na czym jednym najlepiej skupić się teraz i dlaczego?",
      "Przejrzyj odżywianie",
      "Wybierz punkt wyjścia. Trener korzysta tylko z dostępnego kontekstu.",
      "Krąg",
      "Współpraca",
      "Profil społeczności i działania",
      "Zadanie z nagrodą w społeczności",
      "Nagrody dla twórców",
      "Wyjaśnij trend mojego zapisanego snu i co może oznaczać na dziś, bez wymyślania brakujących danych.",
      "Wyjaśnij mój sen",
      "Multimedia",
      "Kolejny priorytet",
      "Otwórz nagrody",
      "Przeanalizuj mój dzień na podstawie zapisanych danych BIL i wskaż najbardziej przydatny następny krok.",
      "Przeanalizuj dzisiejsze odżywianie na podstawie zapisanych danych BIL. Co się wyróżnia i na czym mam się teraz skupić?",
      "Zacznij od swoich rzeczywistych danych BIL",
      "Tematy, które mogą Ci się spodobać",
    ],
    'nl': [
      "Wat is op basis van mijn geselecteerde BIL-context de nuttigste volgende prioriteit, en waarom?",
      "Voeding bekijken",
      "Kies een beginpunt. De coach gebruikt alleen de beschikbare context.",
      "Kring",
      "Samenwerking",
      "Communityprofiel en acties",
      "Communitytaak met beloning",
      "Beloningen voor makers",
      "Leg mijn vastgelegde slaaptrend uit en wat die voor vandaag kan betekenen, zonder ontbrekende gegevens te verzinnen.",
      "Mijn slaap uitleggen",
      "Mediabestanden",
      "Mijn volgende prioriteit",
      "Beloningen openen",
      "Bekijk mijn dag aan de hand van mijn opgeslagen BIL-gegevens en vertel me wat de nuttigste volgende stap is.",
      "Bekijk de voeding van vandaag aan de hand van mijn opgeslagen BIL-gegevens. Wat valt op en waarop moet ik me nu richten?",
      "Begin met je echte BIL-gegevens",
      "Onderwerpen die je misschien leuk vindt",
    ],
    'uk': [
      "На основі вибраного мною контексту BIL, на чому одному найкорисніше зосередитися далі й чому?",
      "Переглянути харчування",
      "Виберіть, із чого почати. Тренер використовує лише доступний контекст.",
      "Коло",
      "Співпраця",
      "Профіль спільноти та дії",
      "Завдання з винагородою у спільноті",
      "Винагороди авторам",
      "Поясни тенденцію мого записаного сну та що вона може означати для сьогодні, не вигадуючи відсутні дані.",
      "Пояснити мій сон",
      "Медіа",
      "Наступний пріоритет",
      "Відкрити винагороди",
      "Переглянь мій день за збереженими даними BIL та підкажи найкорисніший наступний крок.",
      "Переглянь сьогоднішнє харчування за збереженими даними BIL. Що вирізняється і на чому мені зосередитися далі?",
      "Почніть зі своїх справжніх даних BIL",
      "Теми, які можуть вам сподобатися",
    ],
  };

  static Set<String> get supported => {'en', ...rows.keys};

  static bool get balanced {
    final expected = BilLocalePolicy.productionTags.toSet();
    return expected.length == supported.length &&
        supported.containsAll(expected) &&
        sources.toSet().length == sources.length &&
        rows.values.every(
          (row) =>
              row.length == sources.length &&
              row.every((value) => value.trim().isNotEmpty),
        );
  }

  static String? resolve(String source, String localeTag) {
    final index = sources.indexOf(source);
    if (index < 0) return null;
    var tag = BilLocalePolicy.canonicalSupportedTag(localeTag);
    if (tag == null) {
      final language = localeTag.replaceAll('_', '-').toLowerCase().split('-').first;
      final matches = supported.where(
        (candidate) => candidate.toLowerCase() == language,
      );
      if (matches.length == 1) tag = matches.single;
    }
    if (tag == 'en') return source;
    if (tag == null || !supported.contains(tag)) return null;
    final row = rows[tag];
    if (row == null || row.length != sources.length) {
      throw StateError('Incomplete reference delta copy for $tag.');
    }
    return row[index];
  }
}
