part of 'runtime_copy_coach_food_cards.dart';

const _coachFoodCardRows0 = <String, List<String>>{
  "ar": [
    "غير معروف",
    "تقديري",
    "تفاصيل الطعام",
    "تفاصيل المغذيات",
    "إجراءات الإيصال",
    "كمية تقديرية",
    "الصورة غير متاحة",
    "نعم، سجّلها",
    "تعديل",
    "جارٍ التنفيذ…",
    "المصادر",
    "الثقة في المصدر",
    "الثقة في هوية الطعام",
    "الثقة في الكمية",
    "عرض في السجل اليومي",
    "إيصال الطعام هذا غير متاح. راجع سجلك اليومي.",
    "تغير حسابك. ارجع إلى المدرب للمتابعة.",
    "تعذر إكمال الإجراء. احتفظنا بمراجعتك.",
    "تغيّرت هذه الوجبة. راجع الإدخال الحالي قبل التعديل أو التراجع.",
    "هذه المراجعة مغلقة.",
    "تم التراجع عن الإدخال",
    "تم تحديث الوجبة",
    "تم حذف الإدخال",
    "تم نقل الوجبة",
    "تم حفظ إدخال السعرات",
    "تم حفظ إدخال المغذيات",
    "طعام غير معروف",
    "وجبة",
    "حسنًا! سأسجّل {meal}. هذا ما فهمته:",
    "هل أسجّل هذا في {meal}؟",
    "تم تسجيل {meal}",
    "مرجع",
    "ملصق غذائي",
    "قيمك الثابتة",
    "وصفة محسوبة",
    "البروتين",
    "الكربوهيدرات",
    "الدهون",
    "السكر",
    "الكالسيوم",
    "الفوسفور",
    "الحديد",
    "فيتامين ج",
    "مل",
    "حبة واحدة",
    "عدد الحبات: {count}",
    "غ",
  ],
  "fr": [
    "Inconnu",
    "Estimé",
    "Détails de l’aliment",
    "Détails nutritionnels",
    "Actions du reçu",
    "Portion estimée",
    "Photo indisponible",
    "Oui, enregistrer",
    "Ajuster",
    "En cours…",
    "Sources",
    "Confiance dans la source",
    "Confiance dans l’identification de l’aliment",
    "Confiance dans la quantité",
    "Voir dans le journal quotidien",
    "Ce reçu alimentaire est indisponible. Consultez votre journal quotidien.",
    "Votre compte a changé. Revenez au Coach pour continuer.",
    "L’action n’a pas pu être terminée. Votre révision est conservée.",
    "Ce repas a changé. Consultez l’entrée actuelle avant de la modifier ou de l’annuler.",
    "Cette révision est terminée.",
    "Entrée annulée",
    "Repas mis à jour",
    "Entrée supprimée",
    "Repas déplacé",
    "Entrée de calories enregistrée",
    "Entrée nutritionnelle enregistrée",
    "Aliment inconnu",
    "Repas",
    "Très bien ! Je vais enregistrer votre {meal}. Voici ce que j’ai compris :",
    "Dois-je ajouter ceci à votre {meal} ?",
    "{meal} enregistré",
    "Référence",
    "Étiquette alimentaire",
    "Vos valeurs fixes",
    "Recette calculée",
    "Protéines",
    "Glucides",
    "Lipides",
    "Sucres",
    "Calcium",
    "Phosphore",
    "Fer",
    "Vitamine C",
    "ml",
    "1 unité",
    "{count} unités",
    "g",
  ],
  "es": [
    "Desconocido",
    "Estimado",
    "Detalles del alimento",
    "Detalles nutricionales",
    "Acciones del recibo",
    "Porción estimada",
    "Foto no disponible",
    "Sí, registrarlo",
    "Ajustar",
    "En curso…",
    "Fuentes",
    "Confianza en la fuente",
    "Confianza en la identificación del alimento",
    "Confianza en la cantidad",
    "Ver en el registro diario",
    "Este recibo de alimentos no está disponible. Revisa tu registro diario.",
    "Tu cuenta ha cambiado. Vuelve al Coach para continuar.",
    "No se pudo completar la acción. Se conserva tu revisión.",
    "Esta comida ha cambiado. Revisa la entrada actual antes de editarla o deshacerla.",
    "Esta revisión está cerrada.",
    "Entrada deshecha",
    "Comida actualizada",
    "Entrada eliminada",
    "Comida movida",
    "Entrada de calorías guardada",
    "Entrada nutricional guardada",
    "Alimento desconocido",
    "Comida",
    "¡Bien! Registraré tu {meal}. Esto es lo que he entendido:",
    "¿Lo registro en tu {meal}?",
    "{meal} registrado",
    "Referencia",
    "Etiqueta del alimento",
    "Tus valores fijos",
    "Receta calculada",
    "Proteína",
    "Carbohidratos",
    "Grasa",
    "Azúcar",
    "Calcio",
    "Fósforo",
    "Hierro",
    "Vitamina C",
    "ml",
    "1 unidad",
    "{count} unidades",
    "g",
  ],
  "tr": [
    "Bilinmiyor",
    "Tahmini",
    "Besin ayrıntıları",
    "Besin değeri ayrıntıları",
    "Kayıt fişi işlemleri",
    "Tahmini porsiyon",
    "Fotoğraf kullanılamıyor",
    "Evet, kaydet",
    "Düzenle",
    "İşleniyor…",
    "Kaynaklar",
    "Kaynağa güven düzeyi",
    "Besin tanımlamasına güven düzeyi",
    "Miktara güven düzeyi",
    "Günlük kayıtta görüntüle",
    "Bu besin kayıt fişi kullanılamıyor. Günlük kaydınızı inceleyin.",
    "Hesabınız değişti. Devam etmek için Koç’a dönün.",
    "İşlem tamamlanamadı. İncelemeniz korundu.",
    "Bu öğün değişti. Düzenlemeden veya geri almadan önce mevcut kaydı inceleyin.",
    "Bu inceleme kapatıldı.",
    "Kayıt geri alındı",
    "Öğün güncellendi",
    "Kayıt silindi",
    "Öğün taşındı",
    "Kalori kaydı kaydedildi",
    "Besin değeri kaydı kaydedildi",
    "Bilinmeyen besin",
    "Öğün",
    "Tamam! {meal} kaydınızı oluşturacağım. Anladıklarım şöyle:",
    "Bunu {meal} öğününüze kaydedeyim mi?",
    "{meal} kaydedildi",
    "Referans",
    "Besin etiketi",
    "Sabit değerleriniz",
    "Hesaplanmış tarif",
    "Protein",
    "Karbonhidrat",
    "Yağ",
    "Şeker",
    "Kalsiyum",
    "Fosfor",
    "Demir",
    "C vitamini",
    "ml",
    "1 adet",
    "{count} adet",
    "g",
  ],
  "de": [
    "Unbekannt",
    "Geschätzt",
    "Lebensmitteldetails",
    "Nährwertdetails",
    "Aktionen zum Beleg",
    "Geschätzte Portion",
    "Foto nicht verfügbar",
    "Ja, eintragen",
    "Anpassen",
    "Wird bearbeitet…",
    "Quellen",
    "Vertrauen in die Quelle",
    "Vertrauen in die Lebensmittelzuordnung",
    "Vertrauen in die Mengenangabe",
    "Im Tagesprotokoll ansehen",
    "Dieser Lebensmittelbeleg ist nicht verfügbar. Prüfe dein Tagesprotokoll.",
    "Dein Konto hat sich geändert. Kehre zum Coach zurück, um fortzufahren.",
    "Die Aktion konnte nicht abgeschlossen werden. Deine Überprüfung bleibt erhalten.",
    "Diese Mahlzeit hat sich geändert. Prüfe den aktuellen Eintrag, bevor du ihn bearbeitest oder rückgängig machst.",
    "Diese Überprüfung ist abgeschlossen.",
    "Eintrag rückgängig gemacht",
    "Mahlzeit aktualisiert",
    "Eintrag entfernt",
    "Mahlzeit verschoben",
    "Kalorieneintrag gespeichert",
    "Nährwerteintrag gespeichert",
    "Unbekanntes Essen",
    "Mahlzeit",
    "Gut! Ich werde {meal} eintragen. So habe ich dich verstanden:",
    "Soll ich dies bei {meal} eintragen?",
    "{meal} eingetragen",
    "Referenz",
    "Lebensmitteletikett",
    "Deine festen Werte",
    "Berechnetes Rezept",
    "Eiweiß",
    "Kohlenhydrate",
    "Fett",
    "Zucker",
    "Kalzium",
    "Phosphor",
    "Eisen",
    "Vitamin C",
    "ml",
    "1 Stück",
    "{count} Stück",
    "g",
  ],
  "it": [
    "Sconosciuto",
    "Stimato",
    "Dettagli dell’alimento",
    "Dettagli nutrizionali",
    "Azioni della ricevuta",
    "Porzione stimata",
    "Foto non disponibile",
    "Sì, registra",
    "Modifica",
    "Operazione in corso…",
    "Fonti",
    "Affidabilità della fonte",
    "Affidabilità dell’identificazione dell’alimento",
    "Affidabilità della quantità",
    "Visualizza nel diario giornaliero",
    "Questa ricevuta alimentare non è disponibile. Controlla il diario giornaliero.",
    "Il tuo account è cambiato. Torna al Coach per continuare.",
    "Impossibile completare l’azione. La tua revisione è stata conservata.",
    "Questo pasto è cambiato. Controlla la voce attuale prima di modificarla o annullarla.",
    "Questa revisione è chiusa.",
    "Voce annullata",
    "Pasto aggiornato",
    "Voce rimossa",
    "Pasto spostato",
    "Voce calorica salvata",
    "Voce nutrizionale salvata",
    "Cibo sconosciuto",
    "Pasto",
    "Bene! Registrerò {meal}. Ecco cosa ho capito:",
    "Vuoi che registri questo in {meal}?",
    "{meal} registrato",
    "Riferimento",
    "Etichetta alimentare",
    "I tuoi valori fissi",
    "Ricetta calcolata",
    "Proteine",
    "Carboidrati",
    "Grasso",
    "Zucchero",
    "Calcio",
    "Fosforo",
    "Ferro",
    "Vitamina C",
    "ml",
    "1 pezzo",
    "{count} pezzi",
    "g",
  ],
};
