part of 'runtime_copy_integration_gap.dart';

const _integrationEurope = <String, List<String>>{
  "ar": [
    "+5 توكنات AI مؤكدة بإيصال الخادم",
    "يمكن للمنشور الموافق عليه والمؤهل أن يكسب +5 توكنات AI فقط عند تأكيد إيصال المكافأة من الخادم. الموافقة وحدها لا تضمن المكافأة، وقد تنطبق حدود يومية. توكنات AI ليست BIL Gold ولا يمكن صرفها نقدًا. فتح مسودة أو حفظها لا يمنح أي مكافأة.",
    "تمت الموافقة · لم تُؤكَّد مكافأة توكنات AI",
    "إلغاء — عدم الحفظ",
    "تم تحديث وحدات العرض.",
    "هل تريد نسيان هذه الذكرى؟",
    "مخفي",
    "منشور أعجبت به",
    "الإعجابات خاصة؛ لا يمكن لأحد غير هذا العضو رؤيتها.",
    "تحميل المزيد من الإعجابات",
    "تحميل المزيد من الوسائط",
    "الوسائط خاصة في هذا الملف الشخصي.",
    "اختيارات متعددة",
    "لا توجد منشورات معجب بها ظاهرة بعد.",
    "لا توجد وسائط ظاهرة بعد.",
    "لا توجد ردود ظاهرة بعد.",
    "لم يُمنح إذن الإشعارات، لذلك لم يتغير التذكير.",
    "ستُحذف الذكرى التي حددتها فقط.",
    "افتح المنشور لمراجعة نتيجة الإشراف",
    "تمت الموافقة على المنشور، لكن لم تُؤكَّد مكافأة توكنات AI لهذا القرار.",
    "نتيجة مراجعة المنشور",
    "وضع القراءة فقط. لم يُسجَّل أي طعام.",
    "تم تحديث التذكير والتحقق منه.",
    "الردود خاصة في هذا الملف الشخصي.",
    "أعد محاولة قراءة هذه المراجعة لاسترجاع نتيجتها المحفوظة.",
    "اختيار واحد",
    "تعذر التحقق من التذكير في مجدول الجهاز؛ أُعيد الإعداد السابق.",
    "تغيرت هذه الذكرى بعد المراجعة. حدّث الصفحة وحددها مرة أخرى.",
    "تعذر تحميل هذا المنشور للحساب الحالي.",
    "تغير إذن الكتابة أثناء الإجراء. راجع إعداد الحماية وجهّز الإجراء من جديد.",
    "منشورك بحاجة إلى تعديلات",
    "تمت الموافقة على منشورك",
    "تمت الموافقة على منشورك · +5 توكنات AI",
  ],
  "fr": [
    "+5 jetons IA confirmés par le reçu du serveur",
    "Une publication admissible et approuvée ne peut obtenir +5 jetons IA que si le reçu de récompense du serveur confirme l’attribution. L’approbation seule ne garantit rien ; des limites quotidiennes peuvent s’appliquer. Les jetons IA ne sont pas du BIL Gold et ne sont pas échangeables contre de l’argent. Ouvrir ou enregistrer un brouillon ne rapporte rien.",
    "Approuvée · aucun octroi de jetons IA confirmé",
    "Annuler — ne pas enregistrer",
    "Unités d’affichage mises à jour.",
    "Oublier ce souvenir ?",
    "Masqué",
    "Publication aimée",
    "Les mentions J’aime sont privées. Seul ce membre peut les voir.",
    "Charger plus de mentions J’aime",
    "Charger plus de médias",
    "Les médias sont privés sur ce profil.",
    "Choix multiples",
    "Aucune publication aimée visible pour l’instant.",
    "Aucun média visible pour l’instant.",
    "Aucune réponse visible pour l’instant.",
    "L’autorisation de notification a été refusée ; le rappel n’a donc pas été modifié.",
    "Seul le souvenir sélectionné sera supprimé.",
    "Ouvrez la publication pour consulter le résultat de la modération",
    "Publication approuvée. Aucun octroi de jetons IA n’a été confirmé pour cette décision.",
    "Résultat de la modération",
    "Mode lecture seule. Aucun aliment enregistré.",
    "Rappel mis à jour et vérifié.",
    "Les réponses sont privées sur ce profil.",
    "Réessayez cette consultation pour lire son résultat enregistré.",
    "Choix unique",
    "Impossible de vérifier le rappel dans le planificateur de l’appareil. Le réglage précédent a été rétabli.",
    "Ce souvenir a changé après vérification. Actualisez et sélectionnez-le à nouveau.",
    "Impossible de charger cette publication pour le compte actuel.",
    "L’autorisation d’écriture a changé pendant cette action. Vérifiez le réglage de protection et recommencez.",
    "Votre publication nécessite des modifications",
    "Votre publication a été approuvée",
    "Votre publication a été approuvée · +5 jetons IA",
  ],
  "es": [
    "+5 tokens de IA confirmados por el recibo del servidor",
    "Una publicación aprobada y apta solo puede obtener +5 tokens de IA si el recibo de recompensa del servidor confirma la concesión. La aprobación por sí sola no garantiza tokens; pueden aplicarse límites diarios. Los tokens de IA no son BIL Gold ni se pueden canjear por dinero. Abrir o guardar un borrador no otorga recompensas.",
    "Aprobada · no se confirmó la entrega de tokens de IA",
    "Cancelar — no guardar",
    "Unidades de visualización actualizadas.",
    "¿Olvidar este recuerdo?",
    "Oculto",
    "Publicación que te gustó",
    "Los Me gusta son privados. Solo este miembro puede verlos.",
    "Cargar más Me gusta",
    "Cargar más archivos multimedia",
    "Los archivos multimedia son privados en este perfil.",
    "Selección múltiple",
    "Aún no hay publicaciones que te hayan gustado visibles.",
    "Aún no hay contenido multimedia visible.",
    "Aún no hay respuestas visibles.",
    "No se concedió el permiso de notificaciones, por lo que el recordatorio no se modificó.",
    "Solo se eliminará el recuerdo seleccionado.",
    "Abre la publicación para revisar el resultado de moderación",
    "Publicación aprobada. No se confirmó ninguna concesión de tokens de IA para esta decisión.",
    "Resultado de la revisión de la publicación",
    "Modo de solo lectura. No se registró ningún alimento.",
    "Recordatorio actualizado y verificado.",
    "Las respuestas son privadas en este perfil.",
    "Vuelve a intentar esta revisión para leer el resultado guardado.",
    "Selección única",
    "No se pudo verificar el recordatorio en el programador del dispositivo. Se restauró la configuración anterior.",
    "Este recuerdo cambió después de la revisión. Actualiza y selecciónalo de nuevo.",
    "No se pudo cargar esta publicación para la cuenta actual.",
    "El permiso de escritura cambió durante la acción. Revisa la configuración de protección y prepara la acción de nuevo.",
    "Tu publicación necesita cambios",
    "Tu publicación fue aprobada",
    "Tu publicación fue aprobada · +5 tokens de IA",
  ],
  "tr": [
    "Sunucu makbuzuyla onaylanan +5 yapay zekâ tokeni",
    "Onaylanan uygun bir gönderi, yalnızca sunucu ödül makbuzu verildiğini doğrularsa +5 yapay zekâ tokeni kazanabilir. Yalnızca onay almak ödülü garanti etmez; günlük sınırlar uygulanabilir. Yapay zekâ tokenleri BIL Gold değildir ve nakde çevrilemez. Taslak açmak veya kaydetmek ödül kazandırmaz.",
    "Onaylandı · yapay zekâ tokeni verildiği doğrulanmadı",
    "İptal et — kaydetme",
    "Görüntüleme birimleri güncellendi.",
    "Bu anı unutulsun mu?",
    "Gizli",
    "Beğenilen gönderi",
    "Beğeniler gizlidir. Yalnızca bu üye görebilir.",
    "Daha fazla beğeni yükle",
    "Daha fazla medya yükle",
    "Bu profildeki medya gizlidir.",
    "Çoklu seçim",
    "Henüz görünür beğenilen gönderi yok.",
    "Henüz görünür medya yok.",
    "Henüz görünür yanıt yok.",
    "Bildirim izni verilmediğinden hatırlatıcı değiştirilmedi.",
    "Yalnızca seçtiğiniz anı silinecektir.",
    "Moderasyon sonucunu incelemek için gönderiyi açın",
    "Gönderi onaylandı. Bu karar için yapay zekâ tokeni verildiği doğrulanmadı.",
    "Gönderi inceleme sonucu",
    "Salt okunur mod. Hiçbir yiyecek kaydedilmedi.",
    "Hatırlatıcı güncellendi ve doğrulandı.",
    "Bu profilde yanıtlar gizlidir.",
    "Kaydedilen sonucu okumak için incelemeyi yeniden deneyin.",
    "Tek seçim",
    "Hatırlatıcı cihaz zamanlayıcısında doğrulanamadı. Önceki ayar geri yüklendi.",
    "Bu anı incelemeden sonra değişti. Yenileyip tekrar seçin.",
    "Bu gönderi geçerli hesap için yüklenemedi.",
    "Yazma izni işlem sırasında değişti. Koruma ayarını gözden geçirip işlemi yeniden hazırlayın.",
    "Gönderinizin düzenlenmesi gerekiyor",
    "Gönderiniz onaylandı",
    "Gönderiniz onaylandı · +5 yapay zekâ tokeni",
  ],
  "de": [
    "+5 KI-Token durch Serverbeleg bestätigt",
    "Ein geeigneter, genehmigter Beitrag kann nur dann +5 KI-Token erhalten, wenn der Belohnungsbeleg des Servers die Vergabe bestätigt. Die Genehmigung allein garantiert keine Token; tägliche Limits können gelten. KI-Token sind kein BIL Gold und nicht auszahlbar. Das Öffnen oder Speichern eines Entwurfs bringt keine Belohnung.",
    "Genehmigt · keine KI-Token-Vergabe bestätigt",
    "Abbrechen — nicht speichern",
    "Anzeigeeinheiten aktualisiert.",
    "Diese Erinnerung vergessen?",
    "Ausgeblendet",
    "Mit „Gefällt mir“ markierter Beitrag",
    "„Gefällt mir“-Angaben sind privat. Nur dieses Mitglied kann sie sehen.",
    "Weitere Likes laden",
    "Weitere Medien laden",
    "Medien sind auf diesem Profil privat.",
    "Mehrfachauswahl",
    "Noch keine sichtbaren gelikten Beiträge.",
    "Noch keine sichtbaren Medien.",
    "Noch keine sichtbaren Antworten.",
    "Die Benachrichtigungsberechtigung wurde nicht erteilt. Die Erinnerung wurde nicht geändert.",
    "Nur die ausgewählte Erinnerung wird gelöscht.",
    "Beitrag öffnen, um das Moderationsergebnis zu prüfen",
    "Beitrag genehmigt. Für diese Entscheidung wurde keine Vergabe von KI-Token bestätigt.",
    "Ergebnis der Beitragsprüfung",
    "Schreibgeschützter Modus. Kein Essen wurde erfasst.",
    "Erinnerung aktualisiert und bestätigt.",
    "Antworten sind auf diesem Profil privat.",
    "Prüfung wiederholen, um das gespeicherte Ergebnis zu lesen.",
    "Einfachauswahl",
    "Die Erinnerung konnte im Geräteplaner nicht bestätigt werden. Die vorherige Einstellung wurde wiederhergestellt.",
    "Diese Erinnerung hat sich nach der Prüfung geändert. Aktualisieren und erneut auswählen.",
    "Dieser Beitrag konnte für das aktuelle Konto nicht geladen werden.",
    "Die Schreibberechtigung hat sich während der Aktion geändert. Schutzeinstellung prüfen und Aktion erneut vorbereiten.",
    "Dein Beitrag muss überarbeitet werden",
    "Dein Beitrag wurde genehmigt",
    "Dein Beitrag wurde genehmigt · +5 KI-Token",
  ],
  "it": [
    "+5 token IA confermati dalla ricevuta del server",
    "Un post idoneo e approvato può ottenere +5 token IA solo se la ricevuta del server conferma l'assegnazione. L'approvazione da sola non garantisce i token; possono applicarsi limiti giornalieri. I token IA non sono BIL Gold e non sono convertibili in denaro. Aprire o salvare una bozza non dà ricompense.",
    "Approvato · nessuna assegnazione di token IA confermata",
    "Annulla — non salvare",
    "Unità di visualizzazione aggiornate.",
    "Dimenticare questo ricordo?",
    "Nascosto",
    "Post che ti piace",
    "I Mi piace sono privati. Solo questo membro può vederli.",
    "Carica altri Mi piace",
    "Carica altri contenuti multimediali",
    "I contenuti multimediali sono privati in questo profilo.",
    "Scelta multipla",
    "Non ci sono ancora post con Mi piace visibili.",
    "Non ci sono ancora contenuti multimediali visibili.",
    "Non ci sono ancora risposte visibili.",
    "Il permesso per le notifiche non è stato concesso, quindi il promemoria non è stato modificato.",
    "Verrà eliminato solo il ricordo selezionato.",
    "Apri il post per esaminare l'esito della moderazione",
    "Post approvato. Nessuna assegnazione di token IA è stata confermata per questa decisione.",
    "Esito della revisione del post",
    "Modalità sola lettura. Nessun alimento registrato.",
    "Promemoria aggiornato e verificato.",
    "Le risposte sono private in questo profilo.",
    "Riprova questa verifica per leggere il risultato salvato.",
    "Scelta singola",
    "Impossibile verificare il promemoria nel programma del dispositivo. È stata ripristinata l'impostazione precedente.",
    "Questo ricordo è cambiato dopo la verifica. Aggiorna e selezionalo nuovamente.",
    "Impossibile caricare questo post per l'account corrente.",
    "Il permesso di scrittura è cambiato durante l'azione. Controlla l'impostazione di protezione e riprova.",
    "Il tuo post richiede modifiche",
    "Il tuo post è stato approvato",
    "Il tuo post è stato approvato · +5 token IA",
  ],
  "pt-BR": [
    "+5 tokens de IA confirmados pelo recibo do servidor",
    "Uma publicação elegível e aprovada só pode ganhar +5 tokens de IA quando o recibo do servidor confirmar a concessão. A aprovação por si só não garante tokens; limites diários podem se aplicar. Tokens de IA não são BIL Gold e não podem ser convertidos em dinheiro. Abrir ou salvar um rascunho não gera recompensa.",
    "Aprovada · nenhuma concessão de tokens de IA confirmada",
    "Cancelar — não salvar",
    "Unidades de exibição atualizadas.",
    "Esquecer esta memória?",
    "Oculto",
    "Publicação curtida",
    "As curtidas são privadas. Somente este membro pode vê-las.",
    "Carregar mais curtidas",
    "Carregar mais mídias",
    "As mídias são privadas neste perfil.",
    "Múltipla escolha",
    "Ainda não há publicações curtidas visíveis.",
    "Ainda não há mídias visíveis.",
    "Ainda não há respostas visíveis.",
    "A permissão de notificações não foi concedida, portanto o lembrete não foi alterado.",
    "Somente a memória selecionada será excluída.",
    "Abra a publicação para analisar o resultado da moderação",
    "Publicação aprovada. Nenhuma concessão de tokens de IA foi confirmada para esta decisão.",
    "Resultado da análise da publicação",
    "Modo somente leitura. Nenhum alimento foi registrado.",
    "Lembrete atualizado e verificado.",
    "As respostas são privadas neste perfil.",
    "Tente novamente esta consulta para ler o resultado salvo.",
    "Escolha única",
    "Não foi possível verificar o lembrete no agendador do dispositivo. A configuração anterior foi restaurada.",
    "Esta memória mudou após a análise. Atualize e selecione-a novamente.",
    "Não foi possível carregar esta publicação para a conta atual.",
    "A permissão de escrita mudou durante a ação. Revise a configuração de proteção e prepare a ação novamente.",
    "Sua publicação precisa de alterações",
    "Sua publicação foi aprovada",
    "Sua publicação foi aprovada · +5 tokens de IA",
  ],
  "pt-PT": [
    "+5 tokens de IA confirmados pelo recibo do servidor",
    "Uma publicação elegível e aprovada só pode receber +5 tokens de IA se o recibo do servidor confirmar a atribuição. A aprovação por si só não garante tokens; podem aplicar-se limites diários. Os tokens de IA não são BIL Gold nem podem ser convertidos em dinheiro. Abrir ou guardar um rascunho não dá recompensa.",
    "Aprovada · nenhuma atribuição de tokens de IA confirmada",
    "Cancelar — não guardar",
    "Unidades de apresentação atualizadas.",
    "Esquecer esta memória?",
    "Oculto",
    "Publicação de que gostaste",
    "Os gostos são privados. Só este membro os pode ver.",
    "Carregar mais gostos",
    "Carregar mais conteúdos multimédia",
    "Os conteúdos multimédia são privados neste perfil.",
    "Escolha múltipla",
    "Ainda não existem publicações de que gostaste visíveis.",
    "Ainda não existem conteúdos multimédia visíveis.",
    "Ainda não existem respostas visíveis.",
    "A permissão para notificações não foi concedida, pelo que o lembrete não foi alterado.",
    "Só a memória selecionada será eliminada.",
    "Abre a publicação para rever o resultado da moderação",
    "Publicação aprovada. Não foi confirmada nenhuma atribuição de tokens de IA para esta decisão.",
    "Resultado da revisão da publicação",
    "Modo só de leitura. Nenhum alimento foi registado.",
    "Lembrete atualizado e verificado.",
    "As respostas são privadas neste perfil.",
    "Repete esta consulta para ler o resultado guardado.",
    "Escolha única",
    "Não foi possível verificar o lembrete no agendador do dispositivo. Foi restaurada a definição anterior.",
    "Esta memória mudou após a revisão. Atualiza e volta a selecioná-la.",
    "Não foi possível carregar esta publicação para a conta atual.",
    "A permissão de escrita mudou durante a ação. Revê a definição de proteção e prepara novamente a ação.",
    "A tua publicação precisa de alterações",
    "A tua publicação foi aprovada",
    "A tua publicação foi aprovada · +5 tokens de IA",
  ],
  "ru": [
    "+5 токенов ИИ подтверждены квитанцией сервера",
    "Одобренная подходящая публикация может получить +5 токенов ИИ только при подтверждении выдачи серверной квитанцией о награде. Одобрение само по себе не гарантирует токены; могут действовать дневные ограничения. Токены ИИ не являются BIL Gold и не обмениваются на деньги. Открытие или сохранение черновика не приносит награды.",
    "Одобрено · выдача токенов ИИ не подтверждена",
    "Отменить — не сохранять",
    "Единицы отображения обновлены.",
    "Забыть это воспоминание?",
    "Скрыто",
    "Понравившаяся публикация",
    "Отметки «Нравится» приватны. Их видит только этот участник.",
    "Загрузить ещё отметки «Нравится»",
    "Загрузить ещё медиа",
    "Медиа в этом профиле закрыты.",
    "Множественный выбор",
    "Пока нет видимых понравившихся публикаций.",
    "Пока нет видимых медиа.",
    "Пока нет видимых ответов.",
    "Разрешение на уведомления не предоставлено, поэтому напоминание не изменено.",
    "Будет удалено только выбранное воспоминание.",
    "Откройте публикацию, чтобы посмотреть результат модерации",
    "Публикация одобрена. Выдача токенов ИИ по этому решению не подтверждена.",
    "Результат проверки публикации",
    "Режим только для чтения. Еда не записана.",
    "Напоминание обновлено и проверено.",
    "Ответы в этом профиле закрыты.",
    "Повторите проверку, чтобы прочитать сохранённый результат.",
    "Одиночный выбор",
    "Не удалось проверить напоминание в планировщике устройства. Предыдущая настройка восстановлена.",
    "Это воспоминание изменилось после проверки. Обновите и выберите его снова.",
    "Не удалось загрузить эту публикацию для текущего аккаунта.",
    "Право записи изменилось во время действия. Проверьте настройки защиты и подготовьте действие заново.",
    "Вашу публикацию необходимо исправить",
    "Ваша публикация одобрена",
    "Ваша публикация одобрена · +5 токенов ИИ",
  ],
  "uk": [
    "+5 токенів ШІ підтверджено квитанцією сервера",
    "Схвалений допис, що відповідає умовам, може отримати +5 токенів ШІ лише після підтвердження видачі серверною квитанцією. Саме схвалення не гарантує токенів; можуть діяти денні обмеження. Токени ШІ не є BIL Gold і не обмінюються на гроші. Відкриття або збереження чернетки не приносить винагороди.",
    "Схвалено · видачу токенів ШІ не підтверджено",
    "Скасувати — не зберігати",
    "Одиниці відображення оновлено.",
    "Забути цей спогад?",
    "Приховано",
    "Уподобаний допис",
    "Вподобання приватні. Їх бачить лише цей учасник.",
    "Завантажити більше вподобань",
    "Завантажити більше медіа",
    "Медіа в цьому профілі приватні.",
    "Множинний вибір",
    "Поки немає видимих уподобаних дописів.",
    "Поки немає видимих медіа.",
    "Поки немає видимих відповідей.",
    "Дозвіл на сповіщення не надано, тому нагадування не змінено.",
    "Буде видалено лише вибраний спогад.",
    "Відкрийте допис, щоб переглянути результат модерації",
    "Допис схвалено. Видачу токенів ШІ за цим рішенням не підтверджено.",
    "Результат перевірки допису",
    "Режим лише читання. Їжу не записано.",
    "Нагадування оновлено та перевірено.",
    "Відповіді в цьому профілі приватні.",
    "Повторіть перевірку, щоб прочитати збережений результат.",
    "Одиночний вибір",
    "Не вдалося перевірити нагадування в планувальнику пристрою. Попереднє налаштування відновлено.",
    "Цей спогад змінився після перевірки. Оновіть і виберіть його знову.",
    "Не вдалося завантажити цей допис для поточного облікового запису.",
    "Право запису змінилося під час дії. Перевірте налаштування захисту та підготуйте дію знову.",
    "Ваш допис потребує змін",
    "Ваш допис схвалено",
    "Ваш допис схвалено · +5 токенів ШІ",
  ],
  "pl": [
    "+5 tokenów AI potwierdzone pokwitowaniem serwera",
    "Zatwierdzony post spełniający warunki może otrzymać +5 tokenów AI tylko wtedy, gdy pokwitowanie serwera potwierdzi przyznanie nagrody. Samo zatwierdzenie nie gwarantuje tokenów; mogą obowiązywać limity dzienne. Tokeny AI to nie BIL Gold i nie można ich wypłacić. Otwarcie ani zapisanie szkicu nie daje nagrody.",
    "Zatwierdzono · nie potwierdzono przyznania tokenów AI",
    "Anuluj — nie zapisuj",
    "Zaktualizowano jednostki wyświetlania.",
    "Zapomnieć to wspomnienie?",
    "Ukryte",
    "Polubiony post",
    "Polubienia są prywatne. Widzi je tylko ten użytkownik.",
    "Wczytaj więcej polubień",
    "Wczytaj więcej multimediów",
    "Multimedia na tym profilu są prywatne.",
    "Wybór wielokrotny",
    "Na razie brak widocznych polubionych postów.",
    "Na razie brak widocznych multimediów.",
    "Na razie brak widocznych odpowiedzi.",
    "Nie przyznano uprawnienia do powiadomień, więc przypomnienie nie zostało zmienione.",
    "Zostanie usunięte tylko wybrane wspomnienie.",
    "Otwórz post, aby sprawdzić wynik moderacji",
    "Post zatwierdzono. Nie potwierdzono przyznania tokenów AI za tę decyzję.",
    "Wynik przeglądu posta",
    "Tryb tylko do odczytu. Nie zapisano jedzenia.",
    "Przypomnienie zaktualizowano i zweryfikowano.",
    "Odpowiedzi na tym profilu są prywatne.",
    "Ponów przegląd, aby odczytać zapisany wynik.",
    "Wybór pojedynczy",
    "Nie udało się zweryfikować przypomnienia w harmonogramie urządzenia. Przywrócono poprzednie ustawienie.",
    "To wspomnienie zmieniło się po przeglądzie. Odśwież i wybierz je ponownie.",
    "Nie udało się załadować tego posta dla bieżącego konta.",
    "Uprawnienie do zapisu zmieniło się w trakcie działania. Sprawdź ustawienia ochrony i przygotuj działanie ponownie.",
    "Twój post wymaga poprawek",
    "Twój post został zatwierdzony",
    "Twój post został zatwierdzony · +5 tokenów AI",
  ],
  "nl": [
    "+5 AI-tokens bevestigd door serverbewijs",
    "Een geschikt, goedgekeurd bericht kan alleen +5 AI-tokens verdienen als het serverbewijs de toekenning bevestigt. Goedkeuring alleen garandeert geen tokens; er kunnen daglimieten gelden. AI-tokens zijn geen BIL Gold en kunnen niet worden uitbetaald. Een concept openen of opslaan levert niets op.",
    "Goedgekeurd · geen toekenning van AI-tokens bevestigd",
    "Annuleren — niet opslaan",
    "Weergave-eenheden bijgewerkt.",
    "Deze herinnering vergeten?",
    "Verborgen",
    "Geliket bericht",
    "Vind-ik-leuks zijn privé. Alleen dit lid kan ze zien.",
    "Meer vind-ik-leuks laden",
    "Meer media laden",
    "Media zijn privé op dit profiel.",
    "Meerkeuze",
    "Nog geen zichtbare gelikete berichten.",
    "Nog geen zichtbare media.",
    "Nog geen zichtbare reacties.",
    "Er is geen toestemming voor meldingen gegeven; de herinnering is daarom niet gewijzigd.",
    "Alleen de geselecteerde herinnering wordt verwijderd.",
    "Open het bericht om het moderatieresultaat te bekijken",
    "Bericht goedgekeurd. Er is geen toekenning van AI-tokens bevestigd voor deze beslissing.",
    "Resultaat berichtbeoordeling",
    "Alleen-lezenmodus. Er is geen eten geregistreerd.",
    "Herinnering bijgewerkt en gecontroleerd.",
    "Reacties zijn privé op dit profiel.",
    "Probeer deze beoordeling opnieuw om het opgeslagen resultaat te lezen.",
    "Enkele keuze",
    "De herinnering kon niet worden gecontroleerd in de apparaatplanner. De vorige instelling is hersteld.",
    "Deze herinnering is na de beoordeling gewijzigd. Vernieuw en selecteer opnieuw.",
    "Dit bericht kon niet worden geladen voor het huidige account.",
    "De schrijfrechten veranderden tijdens deze actie. Controleer de beveiligingsinstelling en bereid de actie opnieuw voor.",
    "Je bericht moet worden aangepast",
    "Je bericht is goedgekeurd",
    "Je bericht is goedgekeurd · +5 AI-tokens",
  ],
};
