import 'bil_locale_policy.dart';

/// Native access states and measurement units, reviewed for all release locales.
abstract final class HealthDeviceStatusCopy {
  static const sources = <String>[
    'The health provider must be installed or updated.',
    'BIL needs explicit permission before reading health data.',
    'Permission was denied. You can grant it later in system settings.',
    'The Health access request completed. Apple does not reveal read permission status; only records it provides will appear.',
    'Ready to synchronize.',
    'Synchronizing now.',
    'Connected and synchronized.',
    'The native source could not be reached. Local data was not affected.',
    'h',
    'm',
    'ms',
  ];
  static const rows = <String, List<String>>{
    'en': [
      'The health provider must be installed or updated.',
      'BIL needs explicit permission before reading health data.',
      'Permission was denied. You can grant it later in system settings.',
      'The Health access request completed. Apple does not reveal read permission status; only records it provides will appear.',
      'Ready to synchronize.',
      'Synchronizing now.',
      'Connected and synchronized.',
      'The native source could not be reached. Local data was not affected.',
      'h',
      'm',
      'ms',
    ],
    'ar': [
      'يلزم تثبيت مصدر الصحة أو تحديثه.',
      'يحتاج BIL إلى إذن صريح قبل قراءة البيانات الصحية.',
      'تم رفض الإذن. يمكنك منحه لاحقًا من إعدادات النظام.',
      'اكتمل طلب الوصول إلى الصحة. لا تكشف Apple حالة إذن القراءة؛ لن تظهر إلا السجلات التي يوفرها النظام.',
      'جاهز للمزامنة.',
      'تتم المزامنة الآن.',
      'متصل ومتزامن.',
      'تعذر الوصول إلى المصدر الأصلي. البيانات المحلية لم تتأثر.',
      'س',
      'م',
      'مللي ثانية',
    ],
    'fr': [
      'Installez ou mettez à jour le service de santé.',
      'BIL nécessite votre autorisation explicite pour lire les données de santé.',
      'Autorisation refusée. Vous pourrez l’accorder dans les réglages système.',
      'La demande d’accès Santé est terminée. Apple ne révèle pas l’autorisation de lecture ; seuls les enregistrements fournis apparaîtront.',
      'Prêt à synchroniser.',
      'Synchronisation en cours.',
      'Connecté et synchronisé.',
      'La source native est inaccessible. Les données locales sont intactes.',
      'h',
      'm',
      'ms',
    ],
    'es': [
      'Instala o actualiza el proveedor de salud.',
      'BIL necesita permiso explícito para leer datos de salud.',
      'Permiso denegado. Puedes concederlo después en los ajustes del sistema.',
      'La solicitud de acceso a Salud ha terminado. Apple no revela el permiso de lectura; solo aparecerán los registros que proporcione.',
      'Listo para sincronizar.',
      'Sincronizando ahora.',
      'Conectado y sincronizado.',
      'No se pudo acceder a la fuente nativa. Los datos locales están intactos.',
      'h',
      'm',
      'ms',
    ],
    'tr': [
      'Sağlık sağlayıcısı yüklenmeli veya güncellenmeli.',
      'BIL, sağlık verilerini okumadan önce açık izninizi ister.',
      'İzin reddedildi. Daha sonra sistem ayarlarından verebilirsiniz.',
      'Sağlık erişim isteği tamamlandı. Apple okuma izni durumunu açıklamaz; yalnızca sağladığı kayıtlar görünür.',
      'Eşitlemeye hazır.',
      'Şimdi eşitleniyor.',
      'Bağlı ve eşitlenmiş.',
      'Yerel sağlık kaynağına ulaşılamadı. Kayıtlı veriler etkilenmedi.',
      'sa',
      'm',
      'ms',
    ],
    'de': [
      'Der Gesundheitsdienst muss installiert oder aktualisiert werden.',
      'BIL benötigt vor dem Lesen von Gesundheitsdaten Ihre ausdrückliche Erlaubnis.',
      'Berechtigung verweigert. Sie können sie später in den Systemeinstellungen erteilen.',
      'Die Health-Zugriffsanfrage ist abgeschlossen. Apple legt den Leseberechtigungsstatus nicht offen; nur bereitgestellte Datensätze erscheinen.',
      'Bereit zur Synchronisierung.',
      'Synchronisierung läuft.',
      'Verbunden und synchronisiert.',
      'Die native Quelle ist nicht erreichbar. Lokale Daten bleiben unverändert.',
      'Std.',
      'm',
      'ms',
    ],
    'it': [
      'Installa o aggiorna il servizio salute.',
      'BIL richiede un’autorizzazione esplicita prima di leggere dati sanitari.',
      'Autorizzazione negata. Puoi concederla in seguito nelle impostazioni di sistema.',
      'La richiesta di accesso a Salute è terminata. Apple non rivela lo stato del permesso di lettura; appariranno solo i dati forniti.',
      'Pronto per la sincronizzazione.',
      'Sincronizzazione in corso.',
      'Connesso e sincronizzato.',
      'La fonte nativa non è raggiungibile. I dati locali sono intatti.',
      'h',
      'm',
      'ms',
    ],
    'pt-BR': [
      'Instale ou atualize o provedor de saúde.',
      'O BIL precisa de permissão explícita antes de ler dados de saúde.',
      'Permissão negada. Você pode concedê-la depois nas configurações do sistema.',
      'A solicitação de acesso ao Saúde foi concluída. A Apple não revela a permissão de leitura; apenas os registros fornecidos aparecerão.',
      'Pronto para sincronizar.',
      'Sincronizando agora.',
      'Conectado e sincronizado.',
      'Não foi possível acessar a fonte nativa. Os dados locais não foram afetados.',
      'h',
      'm',
      'ms',
    ],
    'pt-PT': [
      'Instale ou atualize o fornecedor de saúde.',
      'O BIL precisa de autorização explícita antes de ler dados de saúde.',
      'Autorização recusada. Pode concedê-la mais tarde nas definições do sistema.',
      'O pedido de acesso à Saúde terminou. A Apple não revela a autorização de leitura; apenas os registos fornecidos serão apresentados.',
      'Pronto para sincronizar.',
      'A sincronizar agora.',
      'Ligado e sincronizado.',
      'Não foi possível aceder à fonte nativa. Os dados locais não foram afetados.',
      'h',
      'm',
      'ms',
    ],
    'ur': [
      'صحت کی سروس انسٹال یا اپ ڈیٹ کرنا ضروری ہے۔',
      'صحت کا ڈیٹا پڑھنے سے پہلے BIL کو واضح اجازت چاہیے۔',
      'اجازت نہیں ملی۔ آپ بعد میں سسٹم کی ترتیبات میں دے سکتے ہیں۔',
      'صحت تک رسائی کی درخواست مکمل ہوئی۔ Apple پڑھنے کی اجازت کی حالت نہیں بتاتا؛ صرف فراہم کردہ ریکارڈ نظر آئیں گے۔',
      'ہم وقت کرنے کے لیے تیار۔',
      'ابھی ہم وقت ہو رہا ہے۔',
      'منسلک اور ہم وقت ہے۔',
      'صحت کے مقامی ماخذ تک رسائی نہ ہو سکی۔ محفوظ ڈیٹا متاثر نہیں ہوا۔',
      'گھنٹے',
      'میٹر',
      'ملی سیکنڈ',
    ],
    'fa': [
      'سرویس سلامت باید نصب یا به‌روزرسانی شود.',
      'BIL پیش از خواندن داده‌های سلامت به اجازهٔ صریح شما نیاز دارد.',
      'اجازه رد شد. می‌توانید بعداً در تنظیمات سیستم آن را بدهید.',
      'درخواست دسترسی به سلامت کامل شد. Apple وضعیت اجازهٔ خواندن را اعلام نمی‌کند؛ فقط سوابق ارائه‌شده نمایش داده می‌شوند.',
      'آمادهٔ همگام‌سازی.',
      'اکنون در حال همگام‌سازی.',
      'متصل و همگام‌شده.',
      'دسترسی به منبع بومی ممکن نشد. داده‌های محلی تغییری نکردند.',
      'ساعت',
      'متر',
      'میلی‌ثانیه',
    ],
    'hi': [
      'स्वास्थ्य सेवा को इंस्टॉल या अपडेट करना ज़रूरी है।',
      'स्वास्थ्य डेटा पढ़ने से पहले BIL को स्पष्ट अनुमति चाहिए।',
      'अनुमति नहीं मिली। आप बाद में सिस्टम सेटिंग में दे सकते हैं।',
      'स्वास्थ्य एक्सेस का अनुरोध पूरा हुआ। Apple पढ़ने की अनुमति की स्थिति नहीं बताता; केवल उपलब्ध कराए गए रिकॉर्ड दिखेंगे।',
      'सिंक करने के लिए तैयार।',
      'अभी सिंक हो रहा है।',
      'कनेक्ट और सिंक है।',
      'मूल स्वास्थ्य स्रोत उपलब्ध नहीं है। स्थानीय डेटा प्रभावित नहीं हुआ।',
      'घं',
      'मी',
      'मि.से.',
    ],
    'id': [
      'Penyedia kesehatan perlu dipasang atau diperbarui.',
      'BIL memerlukan izin eksplisit sebelum membaca data kesehatan.',
      'Izin ditolak. Anda dapat memberikannya nanti melalui pengaturan sistem.',
      'Permintaan akses Kesehatan selesai. Apple tidak mengungkap status izin baca; hanya catatan yang disediakan akan ditampilkan.',
      'Siap menyinkronkan.',
      'Sedang menyinkronkan.',
      'Terhubung dan tersinkron.',
      'Sumber native tidak dapat diakses. Data lokal tidak terpengaruh.',
      'j',
      'm',
      'md',
    ],
    'ms': [
      'Penyedia kesihatan perlu dipasang atau dikemas kini.',
      'BIL memerlukan kebenaran jelas sebelum membaca data kesihatan.',
      'Kebenaran ditolak. Anda boleh memberikannya kemudian dalam tetapan sistem.',
      'Permintaan akses Kesihatan selesai. Apple tidak mendedahkan status kebenaran membaca; hanya rekod yang dibekalkan akan dipaparkan.',
      'Sedia untuk disegerakkan.',
      'Sedang menyegerakkan.',
      'Disambungkan dan disegerakkan.',
      'Sumber natif tidak dapat dicapai. Data setempat tidak terjejas.',
      'j',
      'm',
      'ms',
    ],
    'ja': [
      'ヘルスケアサービスのインストールまたは更新が必要です。',
      '健康データを読むには、BILへの明示的な許可が必要です。',
      '許可されませんでした。後でシステム設定から許可できます。',
      'ヘルスケアへのアクセス要求が完了しました。Appleは読み取り許可の状態を公開しないため、提供された記録のみ表示されます。',
      '同期の準備ができました。',
      '同期しています。',
      '接続・同期済み。',
      'ネイティブのデータ元に接続できません。ローカルデータは保持されています。',
      '時間',
      'm',
      'ミリ秒',
    ],
    'ko': [
      '건강 서비스를 설치하거나 업데이트해야 합니다.',
      'BIL이 건강 데이터를 읽으려면 명시적인 권한이 필요합니다.',
      '권한이 거부되었습니다. 나중에 시스템 설정에서 허용할 수 있습니다.',
      '건강 접근 요청이 완료되었습니다. Apple은 읽기 권한 상태를 공개하지 않으므로 제공된 기록만 표시됩니다.',
      '동기화할 준비가 되었습니다.',
      '동기화하고 있습니다.',
      '연결 및 동기화됨.',
      '기본 건강 데이터 소스에 연결할 수 없습니다. 로컬 데이터는 유지됩니다.',
      '시간',
      'm',
      '밀리초',
    ],
    'zh-Hans': [
      '请安装或更新健康数据服务。',
      'BIL 读取健康数据前需要您的明确授权。',
      '权限被拒绝。您可以稍后在系统设置中授予权限。',
      '健康访问请求已完成。Apple 不公开读取权限状态；只会显示系统提供的记录。',
      '已准备好同步。',
      '正在同步。',
      '已连接并同步。',
      '无法访问原生数据源。本地数据未受影响。',
      '小时',
      '米',
      '毫秒',
    ],
    'zh-Hant': [
      '請安裝或更新健康資料服務。',
      'BIL 讀取健康資料前需要您的明確授權。',
      '權限遭拒。您可以稍後在系統設定中授予權限。',
      '健康存取請求已完成。Apple 不公開讀取權限狀態；只會顯示系統提供的紀錄。',
      '已準備好同步。',
      '正在同步。',
      '已連線並同步。',
      '無法存取原生資料來源。本機資料未受影響。',
      '小時',
      '公尺',
      '毫秒',
    ],
    'ru': [
      'Установите или обновите сервис здоровья.',
      'BIL требуется явное разрешение на чтение данных о здоровье.',
      'В разрешении отказано. Его можно предоставить позже в настройках системы.',
      'Запрос доступа к Здоровью завершён. Apple не раскрывает статус разрешения на чтение; появятся только предоставленные записи.',
      'Готово к синхронизации.',
      'Идёт синхронизация.',
      'Подключено и синхронизировано.',
      'Нативный источник недоступен. Локальные данные не затронуты.',
      'ч',
      'м',
      'мс',
    ],
    'bn': [
      'স্বাস্থ্য পরিষেবাটি ইনস্টল বা আপডেট করতে হবে।',
      'স্বাস্থ্যের ডেটা পড়ার আগে BIL-এর স্পষ্ট অনুমতি প্রয়োজন।',
      'অনুমতি দেওয়া হয়নি। পরে সিস্টেম সেটিংসে দিতে পারবেন।',
      'স্বাস্থ্য অ্যাক্সেসের অনুরোধ সম্পন্ন হয়েছে। Apple পড়ার অনুমতির অবস্থা জানায় না; শুধু সরবরাহ করা রেকর্ড দেখানো হবে।',
      'সিঙ্ক করার জন্য প্রস্তুত।',
      'এখন সিঙ্ক হচ্ছে।',
      'সংযুক্ত ও সিঙ্ক হয়েছে।',
      'মূল স্বাস্থ্য উৎসে পৌঁছানো যায়নি। স্থানীয় ডেটা প্রভাবিত হয়নি।',
      'ঘণ্টা',
      'মি',
      'মিলিসেকেন্ড',
    ],
    'vi': [
      'Cần cài đặt hoặc cập nhật dịch vụ sức khỏe.',
      'BIL cần sự cho phép rõ ràng trước khi đọc dữ liệu sức khỏe.',
      'Quyền đã bị từ chối. Bạn có thể cấp quyền sau trong cài đặt hệ thống.',
      'Yêu cầu truy cập Sức khỏe đã hoàn tất. Apple không tiết lộ trạng thái quyền đọc; chỉ các bản ghi được cung cấp mới xuất hiện.',
      'Sẵn sàng đồng bộ.',
      'Đang đồng bộ.',
      'Đã kết nối và đồng bộ.',
      'Không thể truy cập nguồn dữ liệu gốc. Dữ liệu cục bộ không bị ảnh hưởng.',
      'giờ',
      'm',
      'ms',
    ],
    'th': [
      'ต้องติดตั้งหรืออัปเดตบริการสุขภาพ',
      'BIL ต้องได้รับอนุญาตอย่างชัดเจนก่อนอ่านข้อมูลสุขภาพ',
      'ไม่ได้รับอนุญาต คุณสามารถอนุญาตภายหลังในการตั้งค่าระบบ',
      'คำขอเข้าถึงสุขภาพเสร็จสิ้นแล้ว Apple ไม่เปิดเผยสถานะสิทธิ์การอ่าน จะแสดงเฉพาะบันทึกที่ระบบให้มา',
      'พร้อมซิงค์',
      'กำลังซิงค์',
      'เชื่อมต่อและซิงค์แล้ว',
      'ไม่สามารถเข้าถึงแหล่งข้อมูลของระบบ ข้อมูลในเครื่องไม่ได้รับผลกระทบ',
      'ชม.',
      'ม.',
      'มิลลิวินาที',
    ],
    'pl': [
      'Zainstaluj lub zaktualizuj usługę zdrowotną.',
      'BIL wymaga wyraźnej zgody przed odczytem danych zdrowotnych.',
      'Odmówiono uprawnień. Możesz je później przyznać w ustawieniach systemu.',
      'Żądanie dostępu do Zdrowia zakończone. Apple nie ujawnia stanu uprawnień do odczytu; pojawią się tylko udostępnione rekordy.',
      'Gotowe do synchronizacji.',
      'Trwa synchronizacja.',
      'Połączono i zsynchronizowano.',
      'Natywne źródło jest niedostępne. Dane lokalne nie zostały naruszone.',
      'godz.',
      'm',
      'ms',
    ],
    'nl': [
      'Installeer of werk de gezondheidsdienst bij.',
      'BIL heeft expliciete toestemming nodig om gezondheidsgegevens te lezen.',
      'Toestemming geweigerd. U kunt deze later geven in de systeeminstellingen.',
      'Het verzoek om toegang tot Gezondheid is afgerond. Apple onthult de leesrechten niet; alleen verstrekte gegevens verschijnen.',
      'Klaar om te synchroniseren.',
      'Bezig met synchroniseren.',
      'Verbonden en gesynchroniseerd.',
      'De native bron is niet bereikbaar. Lokale gegevens zijn niet aangetast.',
      'u',
      'm',
      'ms',
    ],
    'uk': [
      'Установіть або оновіть службу здоров’я.',
      'BIL потребує явного дозволу перед читанням даних про здоров’я.',
      'У дозволі відмовлено. Ви зможете надати його пізніше в налаштуваннях системи.',
      'Запит доступу до Здоров’я завершено. Apple не розкриває стан дозволу на читання; з’являться лише надані записи.',
      'Готово до синхронізації.',
      'Триває синхронізація.',
      'Підключено та синхронізовано.',
      'Нативне джерело недоступне. Локальні дані не змінені.',
      'год',
      'м',
      'мс',
    ],
  };
  static String? resolve(String source, String tag) {
    final index = sources.indexOf(source);
    if (index < 0) return null;
    final canonical = BilLocalePolicy.canonicalTag(
      BilLocalePolicy.localeFromTag(tag),
    );
    return rows[canonical]?[index];
  }

  static bool get balanced =>
      rows.length == 25 &&
      rows.values.every(
        (row) =>
            row.length == sources.length &&
            row.every((text) => text.trim().isNotEmpty),
      );
}
