/// Reviewed publication metadata for the official BIL legal documents.
abstract final class LegalStatusRuntimeCopy {
  static const supported = <String>{
    'ar',
    'en',
    'fr',
    'es',
    'tr',
    'de',
    'it',
    'pt-BR',
    'pt-PT',
    'ur',
    'fa',
    'hi',
    'id',
    'ms',
    'ja',
    'ko',
    'zh-Hans',
    'zh-Hant',
    'ru',
    'bn',
    'vi',
    'th',
    'pl',
    'nl',
    'uk',
  };

  static const values = <String, Map<String, String>>{
    'Terms of Use': {
      'en': 'Terms of Use',
      'ar': 'شروط الاستخدام',
      'fr': "Conditions d'utilisation",
      'es': 'Términos de uso',
      'tr': 'Kullanım Koşulları',
      'de': 'Nutzungsbedingungen',
      'it': "Condizioni d'uso",
      'pt-BR': 'Termos de Uso',
      'pt-PT': 'Termos de Utilização',
      'ur': 'استعمال کی شرائط',
      'fa': 'شرایط استفاده',
      'hi': 'उपयोग की शर्तें',
      'id': 'Ketentuan Penggunaan',
      'ms': 'Syarat Penggunaan',
      'ja': '利用規約',
      'ko': '이용약관',
      'zh-Hans': '使用条款',
      'zh-Hant': '使用條款',
      'ru': 'Условия использования',
      'bn': 'ব্যবহারের শর্তাবলী',
      'vi': 'Điều khoản sử dụng',
      'th': 'เงื่อนไขการใช้งาน',
      'pl': 'Warunki użytkowania',
      'nl': 'Gebruiksvoorwaarden',
      'uk': 'Умови використання',
    },
    'Last updated: 5 September 2026 • BIL Health': {
      'ar': 'آخر تحديث: 5 سبتمبر 2026 • BIL Health',
      'en': 'Last updated: 5 September 2026 • BIL Health',
      'fr': 'Dernière mise à jour : 5 septembre 2026 • BIL Health',
      'es': 'Última actualización: 5 de septiembre de 2026 • BIL Health',
      'tr': 'Son güncelleme: 5 Eylül 2026 • BIL Health',
      'de': 'Zuletzt aktualisiert: 5. September 2026 • BIL Health',
      'it': 'Ultimo aggiornamento: 5 settembre 2026 • BIL Health',
      'pt-BR': 'Última atualização: 5 de setembro de 2026 • BIL Health',
      'pt-PT': 'Última atualização: 5 de setembro de 2026 • BIL Health',
      'ur': 'آخری تازہ کاری: 5 ستمبر 2026 • BIL Health',
      'fa': 'آخرین به‌روزرسانی: ۵ سپتامبر ۲۰۲۶ • BIL Health',
      'hi': 'अंतिम अपडेट: 5 सितंबर 2026 • BIL Health',
      'id': 'Terakhir diperbarui: 5 September 2026 • BIL Health',
      'ms': 'Kemas kini terakhir: 5 September 2026 • BIL Health',
      'ja': '最終更新日：2026年9月5日 • BIL Health',
      'ko': '최종 업데이트: 2026년 9월 5일 • BIL Health',
      'zh-Hans': '最后更新：2026年9月5日 • BIL Health',
      'zh-Hant': '最後更新：2026年9月5日 • BIL Health',
      'ru': 'Последнее обновление: 5 сентября 2026 г. • BIL Health',
      'bn': 'সর্বশেষ আপডেট: ৫ সেপ্টেম্বর ২০২৬ • BIL Health',
      'vi': 'Cập nhật lần cuối: 5 tháng 9, 2026 • BIL Health',
      'th': 'อัปเดตล่าสุด: 5 กันยายน 2026 • BIL Health',
      'pl': 'Ostatnia aktualizacja: 5 września 2026 • BIL Health',
      'nl': 'Laatst bijgewerkt: 5 september 2026 • BIL Health',
      'uk': 'Останнє оновлення: 5 вересня 2026 р. • BIL Health',
    },
  };
}
