/// Core reviewed runtime translations. Kept separate to preserve the
/// architecture source-size ceiling.
abstract final class RuntimeCopyPrimary {
  static const values = <String, Map<String, String>>{
    'Today': {
      'ar': 'اليوم',
      'en': 'Today',
      'fr': "Aujourd’hui",
      'es': 'Hoy',
      'tr': 'Bugün',
    },
    'Diary': {
      'ar': 'اليوميات',
      'en': 'Diary',
      'fr': 'Journal',
      'es': 'Diario',
      'tr': 'Günlük',
    },
    'Discover': {
      'ar': 'اكتشف',
      'en': 'Discover',
      'fr': 'Découvrir',
      'es': 'Descubrir',
      'tr': 'Keşfet',
    },
    'Progress': {
      'ar': 'التقدم',
      'en': 'Progress',
      'fr': 'Progrès',
      'es': 'Progreso',
      'tr': 'İlerleme',
    },
    'Insights': {
      'ar': 'الرؤى',
      'en': 'Insights',
      'fr': 'Analyses',
      'es': 'Perspectivas',
      'tr': 'İçgörüler',
    },
    'More': {
      'ar': 'المزيد',
      'en': 'More',
      'fr': 'Plus',
      'es': 'Más',
      'tr': 'Daha fazla',
    },
    'Quick Add': {
      'ar': 'إضافة سريعة',
      'en': 'Quick Add',
      'fr': 'Ajout rapide',
      'es': 'Añadir rápido',
      'tr': 'Hızlı ekle',
    },
    'Quick Add navigation': {
      'ar': 'إضافة',
      'en': 'Add',
      'fr': 'Ajouter',
      'es': 'Añadir',
      'tr': 'Ekle',
    },
    'Settings': {
      'ar': 'الإعدادات',
      'en': 'Settings',
      'fr': 'Paramètres',
      'es': 'Ajustes',
      'tr': 'Ayarlar',
    },
    'Language': {
      'ar': 'اللغة',
      'en': 'Language',
      'fr': 'Langue',
      'es': 'Idioma',
      'tr': 'Dil',
    },
    'Appearance': {
      'ar': 'المظهر',
      'en': 'Appearance',
      'fr': 'Apparence',
      'es': 'Apariencia',
      'tr': 'Görünüm',
    },
    'Privacy': {
      'ar': 'الخصوصية',
      'en': 'Privacy',
      'fr': 'Confidentialité',
      'es': 'Privacidad',
      'tr': 'Gizlilik',
    },
    'Save': {
      'ar': 'حفظ',
      'en': 'Save',
      'fr': 'Enregistrer',
      'es': 'Guardar',
      'tr': 'Kaydet',
    },
    'Cancel': {
      'ar': 'إلغاء',
      'en': 'Cancel',
      'fr': 'Annuler',
      'es': 'Cancelar',
      'tr': 'İptal',
    },
    'Delete': {
      'ar': 'حذف',
      'en': 'Delete',
      'fr': 'Supprimer',
      'es': 'Eliminar',
      'tr': 'Sil',
    },
    'Edit': {
      'ar': 'تعديل',
      'en': 'Edit',
      'fr': 'Modifier',
      'es': 'Editar',
      'tr': 'Düzenle',
    },
    'Update': {
      'ar': 'تحديث',
      'en': 'Update',
      'fr': 'Mettre à jour',
      'es': 'Actualizar',
      'tr': 'Güncelle',
    },
    'Search': {
      'ar': 'بحث',
      'en': 'Search',
      'fr': 'Rechercher',
      'es': 'Buscar',
      'tr': 'Ara',
    },
    'Try again': {
      'ar': 'حاول مرة أخرى',
      'en': 'Try again',
      'fr': 'Réessayer',
      'es': 'Intentar de nuevo',
      'tr': 'Tekrar dene',
    },
    'Unavailable': {
      'ar': 'غير متاح',
      'en': 'Unavailable',
      'fr': 'Indisponible',
      'es': 'No disponible',
      'tr': 'Kullanılamıyor',
    },
    'Add weight': {
      'ar': 'إضافة وزن',
      'en': 'Add weight',
      'fr': 'Ajouter un poids',
      'es': 'Añadir peso',
      'tr': 'Kilo ekle',
    },
    'Add water': {
      'ar': 'إضافة ماء',
      'en': 'Add water',
      'fr': 'Ajouter de l’eau',
      'es': 'Añadir agua',
      'tr': 'Su ekle',
    },
    'Add food': {
      'ar': 'إضافة طعام',
      'en': 'Add food',
      'fr': 'Ajouter un aliment',
      'es': 'Añadir alimento',
      'tr': 'Yiyecek ekle',
    },
    'Weight': {
      'ar': 'الوزن',
      'en': 'Weight',
      'fr': 'Poids',
      'es': 'Peso',
      'tr': 'Kilo',
    },
    'Water': {
      'ar': 'الماء',
      'en': 'Water',
      'fr': 'Eau',
      'es': 'Agua',
      'tr': 'Su',
    },
    'Source': {
      'ar': 'المصدر',
      'en': 'Source',
      'fr': 'Source',
      'es': 'Fuente',
      'tr': 'Kaynak',
    },
    'Evidence': {
      'ar': 'الأدلة',
      'en': 'Evidence',
      'fr': 'Preuves',
      'es': 'Evidencia',
      'tr': 'Kanıt',
    },
    'Confidence': {
      'ar': 'الثقة',
      'en': 'Confidence',
      'fr': 'Confiance',
      'es': 'Confianza',
      'tr': 'Güven',
    },
    'Low': {
      'ar': 'منخفضة',
      'en': 'Low',
      'fr': 'Faible',
      'es': 'Baja',
      'tr': 'Düşük',
    },
    'Moderate': {
      'ar': 'متوسطة',
      'en': 'Moderate',
      'fr': 'Modérée',
      'es': 'Moderada',
      'tr': 'Orta',
    },
    'High': {
      'ar': 'مرتفعة',
      'en': 'High',
      'fr': 'Élevée',
      'es': 'Alta',
      'tr': 'Yüksek',
    },
    'Insufficient data': {
      'ar': 'بيانات غير كافية',
      'en': 'Insufficient data',
      'fr': 'Données insuffisantes',
      'es': 'Datos insuficientes',
      'tr': 'Yetersiz veri',
    },
    'More data needed': {
      'ar': 'نحتاج إلى مزيد من البيانات',
      'en': 'More data needed',
      'fr': 'Davantage de données sont nécessaires',
      'es': 'Se necesitan más datos',
      'tr': 'Daha fazla veri gerekli',
    },
    'Breakfast': {
      'ar': 'الإفطار',
      'en': 'Breakfast',
      'fr': 'Petit-déjeuner',
      'es': 'Desayuno',
      'tr': 'Kahvaltı',
    },
    'Lunch': {
      'ar': 'الغداء',
      'en': 'Lunch',
      'fr': 'Déjeuner',
      'es': 'Almuerzo',
      'tr': 'Öğle yemeği',
    },
    'Dinner': {
      'ar': 'العشاء',
      'en': 'Dinner',
      'fr': 'Dîner',
      'es': 'Cena',
      'tr': 'Akşam yemeği',
    },
    'Snack': {
      'ar': 'وجبة خفيفة',
      'en': 'Snack',
      'fr': 'Collation',
      'es': 'Tentempié',
      'tr': 'Atıştırmalık',
    },
    'Meal type': {
      'ar': 'نوع الوجبة',
      'en': 'Meal type',
      'fr': 'Type de repas',
      'es': 'Tipo de comida',
      'tr': 'Öğün türü',
    },
    'Quantity': {
      'ar': 'الكمية',
      'en': 'Quantity',
      'fr': 'Quantité',
      'es': 'Cantidad',
      'tr': 'Miktar',
    },
    'Save meal': {
      'ar': 'حفظ الوجبة',
      'en': 'Save meal',
      'fr': 'Enregistrer le repas',
      'es': 'Guardar comida',
      'tr': 'Öğünü kaydet',
    },
    'Meal saved locally.': {
      'ar': 'تم حفظ الوجبة محليًا.',
      'en': 'Meal saved locally.',
      'fr': 'Repas enregistré localement.',
      'es': 'Comida guardada localmente.',
      'tr': 'Öğün yerel olarak kaydedildi.',
    },
    'No meals for this day.': {
      'ar': 'لا توجد وجبات لهذا اليوم.',
      'en': 'No meals for this day.',
      'fr': 'Aucun repas pour ce jour.',
      'es': 'No hay comidas para este día.',
      'tr': 'Bu gün için öğün yok.',
    },
    'No foods logged yet': {
      'ar': 'لم تُسجل أطعمة بعد',
      'en': 'No foods logged yet',
      'fr': 'Aucun aliment enregistré',
      'es': 'Aún no hay alimentos registrados',
      'tr': 'Henüz yiyecek kaydedilmedi',
    },
    'Custom food': {
      'ar': 'طعام مخصص',
      'en': 'Custom food',
      'fr': 'Aliment personnalisé',
      'es': 'Alimento personalizado',
      'tr': 'Özel yiyecek',
    },
    'Calculated nutrition': {
      'ar': 'التغذية المحسوبة',
      'en': 'Calculated nutrition',
      'fr': 'Nutrition calculée',
      'es': 'Nutrición calculada',
      'tr': 'Hesaplanan beslenme',
    },
    'Scan food barcode': {
      'ar': 'مسح باركود الطعام',
      'en': 'Scan food barcode',
      'fr': 'Scanner le code-barres',
      'es': 'Escanear código de barras',
      'tr': 'Yiyecek barkodunu tara',
    },
    'Scan with camera': {
      'ar': 'المسح بالكاميرا',
      'en': 'Scan with camera',
      'fr': 'Scanner avec la caméra',
      'es': 'Escanear con cámara',
      'tr': 'Kamerayla tara',
    },
    'Enter barcode manually': {
      'ar': 'إدخال الباركود يدويًا',
      'en': 'Enter barcode manually',
      'fr': 'Saisir le code-barres',
      'es': 'Introducir código manualmente',
      'tr': 'Barkodu elle gir',
    },
    'Invalid barcode': {
      'ar': 'باركود غير صالح',
      'en': 'Invalid barcode',
      'fr': 'Code-barres invalide',
      'es': 'Código de barras no válido',
      'tr': 'Geçersiz barkod',
    },
    'Manual barcode lookup': {
      'ar': 'البحث اليدوي بالباركود',
      'en': 'Manual barcode lookup',
      'fr': 'Recherche manuelle du code-barres',
      'es': 'Búsqueda manual de código',
      'tr': 'Elle barkod arama',
    },
    'Barcode digits': {
      'ar': 'أرقام الباركود',
      'en': 'Barcode digits',
      'fr': 'Chiffres du code-barres',
      'es': 'Dígitos del código',
      'tr': 'Barkod rakamları',
    },
    'Weight history': {
      'ar': 'سجل الوزن',
      'en': 'Weight history',
      'fr': 'Historique du poids',
      'es': 'Historial de peso',
      'tr': 'Kilo geçmişi',
    },
    'Weight trend': {
      'ar': 'اتجاه الوزن',
      'en': 'Weight trend',
      'fr': 'Tendance du poids',
      'es': 'Tendencia del peso',
      'tr': 'Kilo eğilimi',
    },
    'Loading weight history': {
      'ar': 'جارٍ تحميل سجل الوزن',
      'en': 'Loading weight history',
      'fr': 'Chargement de l’historique',
      'es': 'Cargando historial de peso',
      'tr': 'Kilo geçmişi yükleniyor',
    },
    'Could not load weight history': {
      'ar': 'تعذر تحميل سجل الوزن',
      'en': 'Could not load weight history',
      'fr': 'Impossible de charger l’historique du poids',
      'es': 'No se pudo cargar el historial de peso',
      'tr': 'Kilo geçmişi yüklenemedi',
    },
    'No local weight measurements in this range.': {
      'ar': 'لا توجد قياسات وزن محلية في هذه الفترة.',
      'en': 'No local weight measurements in this range.',
      'fr': 'Aucune mesure de poids locale sur cette période.',
      'es': 'No hay mediciones locales de peso en este intervalo.',
      'tr': 'Bu aralıkta yerel kilo ölçümü yok.',
    },
    'Health disclaimer': {
      'ar': 'إخلاء المسؤولية الصحية',
      'en': 'Health disclaimer',
      'fr': 'Avertissement santé',
      'es': 'Aviso de salud',
      'tr': 'Sağlık uyarısı',
    },
  };
}
