// Reviewed Profile copy catalog shard A.
const profileRuntimeCopyCatalogA = <String, Map<String, String>>{
  'Email address': {
    'ar': 'البريد الإلكتروني',
    'en': 'Email address',
    'fr': 'Adresse e-mail',
    'es': 'Correo electrónico',
    'tr': 'E-posta adresi',
    'de': 'E-Mail-Adresse',
    'it': 'Indirizzo e-mail',
    'pt-BR': 'Endereço de e-mail',
    'pt-PT': 'Endereço de e-mail',
    'ur': 'ای میل پتہ',
    'fa': 'نشانی ایمیل',
    'hi': 'ईमेल पता',
    'id': 'Alamat email',
    'ms': 'Alamat e-mel',
    'ja': 'メールアドレス',
    'ko': '이메일 주소',
    'zh-Hans': '电子邮箱地址',
    'zh-Hant': '電子郵件地址',
    'ru': 'Адрес электронной почты',
    'bn': 'ইমেইল ঠিকানা',
    'vi': 'Địa chỉ email',
    'th': 'ที่อยู่อีเมล',
    'pl': 'Adres e-mail',
    'nl': 'E-mailadres',
    'uk': 'Адреса електронної пошти',
  },
  'Goals': {
    'ar': 'الأهداف',
    'en': 'Goals',
    'fr': 'Objectifs',
    'es': 'Objetivos',
    'tr': 'Hedefler',
    'de': 'Ziele',
    'it': 'Obiettivi',
    'pt-BR': 'Metas',
    'pt-PT': 'Objetivos',
    'ur': 'اہداف',
    'fa': 'اهداف',
    'hi': 'लक्ष्य',
    'id': 'Sasaran',
    'ms': 'Matlamat',
    'ja': '目標',
    'ko': '목표',
    'zh-Hans': '目标',
    'zh-Hant': '目標',
    'ru': 'Цели',
    'bn': 'লক্ষ্যসমূহ',
    'vi': 'Mục tiêu',
    'th': 'เป้าหมาย',
    'pl': 'Cele',
    'nl': 'Doelen',
    'uk': 'Цілі',
  },
  'Update weight, nutrition, and fitness goals': {
    'ar': 'حدّث أهداف الوزن والتغذية واللياقة',
    'en': 'Update weight, nutrition, and fitness goals',
    'fr':
        'Mettre à jour les objectifs de poids, de nutrition et de forme physique',
    'es': 'Actualiza los objetivos de peso, nutrición y actividad física',
    'tr': 'Kilo, beslenme ve fitness hedeflerini güncelle',
    'de': 'Ziele für Gewicht, Ernährung und Fitness aktualisieren',
    'it': 'Aggiorna gli obiettivi di peso, alimentazione e forma fisica',
    'pt-BR': 'Atualize suas metas de peso, nutrição e condicionamento físico',
    'pt-PT': 'Atualize os objetivos de peso, nutrição e condição física',
    'ur': 'وزن، غذائیت اور فٹنس کے اہداف اپ ڈیٹ کریں',
    'fa': 'اهداف وزن، تغذیه و تناسب اندام را به‌روزرسانی کنید',
    'hi': 'वज़न, पोषण और फ़िटनेस के लक्ष्य अपडेट करें',
    'id': 'Perbarui target berat badan, nutrisi, dan kebugaran',
    'ms': 'Kemas kini matlamat berat badan, pemakanan dan kecergasan',
    'ja': '体重・栄養・フィットネスの目標を更新',
    'ko': '체중, 영양 및 피트니스 목표 업데이트',
    'zh-Hans': '更新体重、营养和健身目标',
    'zh-Hant': '更新體重、營養與健身目標',
    'ru': 'Обновите цели по весу, питанию и физической форме',
    'bn': 'ওজন, পুষ্টি ও ফিটনেসের লক্ষ্য হালনাগাদ করুন',
    'vi': 'Cập nhật mục tiêu cân nặng, dinh dưỡng và thể chất',
    'th': 'อัปเดตเป้าหมายน้ำหนัก โภชนาการ และการออกกำลังกาย',
    'pl': 'Zaktualizuj cele dotyczące masy ciała, odżywiania i sprawności',
    'nl': 'Werk doelen voor gewicht, voeding en fitness bij',
    'uk': 'Оновіть цілі щодо ваги, харчування та фізичної форми',
  },
  'Calories & macro plan': {
    'ar': 'خطة السعرات والماكروز',
    'en': 'Calories & macro plan',
    'fr': 'Plan calories et macronutriments',
    'es': 'Plan de calorías y macros',
    'tr': 'Kalori ve makro planı',
    'de': 'Kalorien- und Makroplan',
    'it': 'Piano calorie e macronutrienti',
    'pt-BR': 'Plano de calorias e macronutrientes',
    'pt-PT': 'Plano de calorias e macronutrientes',
    'ur': 'کیلوریز اور میکروز کا منصوبہ',
    'fa': 'برنامه کالری و درشت‌مغذی‌ها',
    'hi': 'कैलोरी और मैक्रो योजना',
    'id': 'Rencana kalori dan makro',
    'ms': 'Pelan kalori dan makro',
    'ja': 'カロリーとマクロ栄養素のプラン',
    'ko': '칼로리 및 매크로 계획',
    'zh-Hans': '热量与宏量营养素计划',
    'zh-Hant': '熱量與巨量營養素計畫',
    'ru': 'План калорий и макронутриентов',
    'bn': 'ক্যালোরি ও ম্যাক্রো পরিকল্পনা',
    'vi': 'Kế hoạch calo và chất dinh dưỡng đa lượng',
    'th': 'แผนแคลอรีและสารอาหารหลัก',
    'pl': 'Plan kalorii i makroskładników',
    'nl': 'Calorie- en macroplan',
    'uk': 'План калорій і макронутрієнтів',
  },
  'Plan details & recommendations': {
    'ar': 'تفاصيل الخطة والتوصيات',
    'en': 'Plan details & recommendations',
    'fr': 'Détails et recommandations du plan',
    'es': 'Detalles y recomendaciones del plan',
    'tr': 'Plan ayrıntıları ve öneriler',
    'de': 'Plandetails und Empfehlungen',
    'it': 'Dettagli e consigli del piano',
    'pt-BR': 'Detalhes e recomendações do plano',
    'pt-PT': 'Detalhes e recomendações do plano',
    'ur': 'منصوبے کی تفصیلات اور سفارشات',
    'fa': 'جزئیات و توصیه‌های برنامه',
    'hi': 'योजना का विवरण और सुझाव',
    'id': 'Detail dan rekomendasi rencana',
    'ms': 'Butiran dan cadangan pelan',
    'ja': 'プランの詳細とおすすめ',
    'ko': '계획 세부 정보 및 권장 사항',
    'zh-Hans': '计划详情与建议',
    'zh-Hant': '計畫詳情與建議',
    'ru': 'Подробности плана и рекомендации',
    'bn': 'পরিকল্পনার বিস্তারিত ও পরামর্শ',
    'vi': 'Chi tiết và đề xuất của kế hoạch',
    'th': 'รายละเอียดแผนและคำแนะนำ',
    'pl': 'Szczegóły planu i zalecenia',
    'nl': 'Plandetails en aanbevelingen',
    'uk': 'Деталі плану та рекомендації',
  },
  'Calorie & macro goals': {
    'ar': 'أهداف السعرات والماكروز',
    'en': 'Calorie & macro goals',
    'fr': 'Objectifs de calories et macronutriments',
    'es': 'Objetivos de calorías y macronutrientes',
    'tr': 'Kalori ve makro hedefleri',
    'de': 'Kalorien- und Makroziele',
    'it': 'Obiettivi calorici e dei macronutrienti',
    'pt-BR': 'Metas de calorias e macronutrientes',
    'pt-PT': 'Objetivos de calorias e macronutrientes',
    'ur': 'کیلوری اور میکرو اہداف',
    'fa': 'اهداف کالری و درشت‌مغذی‌ها',
    'hi': 'कैलोरी और मैक्रो लक्ष्य',
    'id': 'Target kalori dan makro',
    'ms': 'Matlamat kalori dan makro',
    'ja': 'カロリーとマクロの目標',
    'ko': '칼로리 및 매크로 목표',
    'zh-Hans': '热量与宏量营养素目标',
    'zh-Hant': '熱量與巨量營養素目標',
    'ru': 'Цели по калориям и макронутриентам',
    'bn': 'ক্যালোরি ও ম্যাক্রো লক্ষ্য',
    'vi': 'Mục tiêu calo và chất dinh dưỡng đa lượng',
    'th': 'เป้าหมายแคลอรีและสารอาหารหลัก',
    'pl': 'Cele kalorii i makroskładników',
    'nl': 'Calorie- en macronutriëntdoelen',
    'uk': 'Цілі за калоріями та макронутрієнтами',
  },
  'Default goal': {
    'ar': 'الهدف الافتراضي',
    'en': 'Default goal',
    'fr': 'Objectif par défaut',
    'es': 'Objetivo predeterminado',
    'tr': 'Varsayılan hedef',
    'de': 'Standardziel',
    'it': 'Obiettivo predefinito',
    'pt-BR': 'Meta padrão',
    'pt-PT': 'Objetivo predefinido',
    'ur': 'پہلے سے طے شدہ ہدف',
    'fa': 'هدف پیش‌فرض',
    'hi': 'डिफ़ॉल्ट लक्ष्य',
    'id': 'Target default',
    'ms': 'Matlamat lalai',
    'ja': 'デフォルトの目標',
    'ko': '기본 목표',
    'zh-Hans': '默认目标',
    'zh-Hant': '預設目標',
    'ru': 'Цель по умолчанию',
    'bn': 'ডিফল্ট লক্ষ্য',
    'vi': 'Mục tiêu mặc định',
    'th': 'เป้าหมายเริ่มต้น',
    'pl': 'Cel domyślny',
    'nl': 'Standaarddoel',
    'uk': 'Ціль за замовчуванням',
  },
  'Custom daily goals': {
    'ar': 'الأهداف اليومية المخصصة',
    'en': 'Custom daily goals',
    'fr': 'Objectifs quotidiens personnalisés',
    'es': 'Objetivos diarios personalizados',
    'tr': 'Özel günlük hedefler',
    'de': 'Benutzerdefinierte Tagesziele',
    'it': 'Obiettivi giornalieri personalizzati',
    'pt-BR': 'Metas diárias personalizadas',
    'pt-PT': 'Objetivos diários personalizados',
    'ur': 'حسب ضرورت روزانہ اہداف',
    'fa': 'اهداف روزانه سفارشی',
    'hi': 'कस्टम दैनिक लक्ष्य',
    'id': 'Target harian khusus',
    'ms': 'Matlamat harian tersuai',
    'ja': 'カスタムの毎日の目標',
    'ko': '맞춤 일일 목표',
    'zh-Hans': '自定义每日目标',
    'zh-Hant': '自訂每日目標',
    'ru': 'Пользовательские цели на день',
    'bn': 'কাস্টম দৈনিক লক্ষ্য',
    'vi': 'Mục tiêu hằng ngày tùy chỉnh',
    'th': 'เป้าหมายรายวันที่กำหนดเอง',
    'pl': 'Niestandardowe cele dzienne',
    'nl': 'Aangepaste dagelijkse doelen',
    'uk': 'Власні щоденні цілі',
  },
  'Activity factor': {
    'ar': 'معامل النشاط',
    'en': 'Activity factor',
    'fr': 'Facteur d’activité',
    'es': 'Factor de actividad',
    'tr': 'Aktivite katsayısı',
    'de': 'Aktivitätsfaktor',
    'it': 'Fattore di attività',
    'pt-BR': 'Fator de atividade',
    'pt-PT': 'Fator de atividade',
    'ur': 'سرگرمی کا عامل',
    'fa': 'ضریب فعالیت',
    'hi': 'गतिविधि कारक',
    'id': 'Faktor aktivitas',
    'ms': 'Faktor aktiviti',
    'ja': '活動係数',
    'ko': '활동 계수',
    'zh-Hans': '活动系数',
    'zh-Hant': '活動係數',
    'ru': 'Коэффициент активности',
    'bn': 'কার্যকলাপের গুণক',
    'vi': 'Hệ số hoạt động',
    'th': 'ปัจจัยกิจกรรม',
    'pl': 'Współczynnik aktywności',
    'nl': 'Activiteitsfactor',
    'uk': 'Коефіцієнт активності',
  },
  'Goal direction': {
    'ar': 'اتجاه الهدف',
    'en': 'Goal direction',
    'fr': 'Orientation de l’objectif',
    'es': 'Dirección del objetivo',
    'tr': 'Hedef yönü',
    'de': 'Zielrichtung',
    'it': 'Direzione dell’obiettivo',
    'pt-BR': 'Direção da meta',
    'pt-PT': 'Direção do objetivo',
    'ur': 'ہدف کی سمت',
    'fa': 'جهت هدف',
    'hi': 'लक्ष्य की दिशा',
    'id': 'Arah target',
    'ms': 'Arah matlamat',
    'ja': '目標の方向',
    'ko': '목표 방향',
    'zh-Hans': '目标方向',
    'zh-Hant': '目標方向',
    'ru': 'Направление цели',
    'bn': 'লক্ষ্যের দিক',
    'vi': 'Hướng mục tiêu',
    'th': 'ทิศทางเป้าหมาย',
    'pl': 'Kierunek celu',
    'nl': 'Richting van het doel',
    'uk': 'Напрямок цілі',
  },
  'Dietary approach': {
    'ar': 'النهج الغذائي',
    'en': 'Dietary approach',
    'fr': 'Approche alimentaire',
    'es': 'Enfoque alimentario',
    'tr': 'Beslenme yaklaşımı',
    'de': 'Ernährungsansatz',
    'it': 'Approccio alimentare',
    'pt-BR': 'Abordagem alimentar',
    'pt-PT': 'Abordagem alimentar',
    'ur': 'غذائی طریقہ',
    'fa': 'رویکرد غذایی',
    'hi': 'आहार का तरीका',
    'id': 'Pendekatan pola makan',
    'ms': 'Pendekatan pemakanan',
    'ja': '食事の方針',
    'ko': '식단 방식',
    'zh-Hans': '饮食方式',
    'zh-Hant': '飲食方式',
    'ru': 'Подход к питанию',
    'bn': 'খাদ্যাভ্যাসের পদ্ধতি',
    'vi': 'Cách tiếp cận dinh dưỡng',
    'th': 'แนวทางโภชนาการ',
    'pl': 'Podejście żywieniowe',
    'nl': 'Voedingsaanpak',
    'uk': 'Підхід до харчування',
  },
  'Food selection does not change nutrient requirements': {
    'ar': 'لا يغيّر اختيار الطعام الاحتياجات الغذائية',
    'en': 'Food selection does not change nutrient requirements',
    'fr': 'Le choix des aliments ne modifie pas les besoins nutritionnels',
    'es': 'La selección de alimentos no cambia las necesidades nutricionales',
    'tr': 'Yiyecek seçimi besin gereksinimlerini değiştirmez',
    'de': 'Die Lebensmittelauswahl ändert den Nährstoffbedarf nicht',
    'it': 'La scelta degli alimenti non modifica il fabbisogno nutrizionale',
    'pt-BR': 'A escolha dos alimentos não altera as necessidades nutricionais',
    'pt-PT': 'A escolha dos alimentos não altera as necessidades nutricionais',
    'ur': 'غذا کا انتخاب غذائی ضروریات کو تبدیل نہیں کرتا',
    'fa': 'انتخاب غذا نیازهای مواد مغذی را تغییر نمی‌دهد',
    'hi': 'भोजन का चयन पोषक तत्वों की ज़रूरतें नहीं बदलता',
    'id': 'Pilihan makanan tidak mengubah kebutuhan zat gizi',
    'ms': 'Pilihan makanan tidak mengubah keperluan nutrien',
    'ja': '食品の選択によって栄養素の必要量は変わりません',
    'ko': '음식 선택은 영양소 필요량을 바꾸지 않습니다',
    'zh-Hans': '食物选择不会改变营养需求',
    'zh-Hant': '食物選擇不會改變營養需求',
    'ru': 'Выбор продуктов не меняет потребности в питательных веществах',
    'bn': 'খাবার নির্বাচন পুষ্টির চাহিদা পরিবর্তন করে না',
    'vi': 'Lựa chọn thực phẩm không làm thay đổi nhu cầu dinh dưỡng',
    'th': 'การเลือกอาหารไม่เปลี่ยนความต้องการสารอาหาร',
    'pl': 'Wybór żywności nie zmienia zapotrzebowania na składniki odżywcze',
    'nl': 'De voedselkeuze verandert de voedingsbehoeften niet',
    'uk': 'Вибір їжі не змінює потреби в поживних речовинах',
  },
  'Mifflin-St Jeor BMR using the saved age, sex, height, and current weight': {
    'ar':
        'معادلة ميفلين–سانت جيور باستخدام العمر والجنس والطول والوزن الحالي المحفوظ',
    'en':
        'Mifflin–St Jeor BMR using the saved age, sex, height, and current weight',
    'fr':
        'Métabolisme basal de Mifflin–St Jeor calculé avec l’âge, le sexe, la taille et le poids actuel enregistrés',
    'es':
        'TMB de Mifflin–St Jeor usando la edad, el sexo, la altura y el peso actual guardados',
    'tr':
        'Kaydedilen yaş, cinsiyet, boy ve mevcut kilo kullanılarak Mifflin–St Jeor BMH hesabı',
    'de':
        'BMR nach Mifflin–St Jeor anhand von gespeichertem Alter, Geschlecht, Größe und aktuellem Gewicht',
    'it':
        'BMR di Mifflin–St Jeor usando età, sesso, altezza e peso attuale salvati',
    'pt-BR':
        'BMR de Mifflin–St Jeor usando idade, sexo, altura e peso atual salvos',
    'pt-PT':
        'BMR de Mifflin–St Jeor usando a idade, o sexo, a altura e o peso atual guardados',
    'ur': 'محفوظ عمر، جنس، قد اور موجودہ وزن کے ساتھ Mifflin–St Jeor BMR',
    'fa':
        'BMR مایفلین–سنت ژئور با استفاده از سن، جنسیت، قد و وزن فعلی ذخیره‌شده',
    'hi': 'सहेजी गई उम्र, लिंग, लंबाई और वर्तमान वज़न से Mifflin–St Jeor BMR',
    'id':
        'BMR Mifflin–St Jeor menggunakan usia, jenis kelamin, tinggi, dan berat saat ini yang tersimpan',
    'ms':
        'BMR Mifflin–St Jeor menggunakan umur, jantina, tinggi dan berat semasa yang disimpan',
    'ja': '保存された年齢・性別・身長・現在の体重によるMifflin–St Jeor基礎代謝量',
    'ko': '저장된 나이, 성별, 키와 현재 체중을 사용한 Mifflin–St Jeor 기초대사량',
    'zh-Hans': '使用已保存的年龄、性别、身高和当前体重计算 Mifflin–St Jeor 基础代谢率',
    'zh-Hant': '使用已儲存的年齡、性別、身高和目前體重計算 Mifflin–St Jeor 基礎代謝率',
    'ru':
        'БМР по Mifflin–St Jeor с использованием сохранённых возраста, пола, роста и текущего веса',
    'bn':
        'সংরক্ষিত বয়স, লিঙ্গ, উচ্চতা ও বর্তমান ওজন ব্যবহার করে Mifflin–St Jeor BMR',
    'vi':
        'BMR Mifflin–St Jeor dùng tuổi, giới tính, chiều cao và cân nặng hiện tại đã lưu',
    'th':
        'BMR ตาม Mifflin–St Jeor โดยใช้อายุ เพศ ส่วนสูง และน้ำหนักปัจจุบันที่บันทึกไว้',
    'pl':
        'BMR Mifflina–St Jeora na podstawie zapisanego wieku, płci, wzrostu i aktualnej masy ciała',
    'nl':
        'BMR volgens Mifflin–St Jeor met opgeslagen leeftijd, geslacht, lengte en huidig gewicht',
    'uk':
        'БМР за Mifflin–St Jeor із використанням збережених віку, статі, зросту та поточної ваги',
  },
  'maintain': {
    'ar': 'ثبات',
    'en': 'maintain',
    'fr': 'maintien',
    'es': 'mantenimiento',
    'tr': 'koruma',
    'de': 'Erhalt',
    'it': 'mantenimento',
    'pt-BR': 'manutenção',
    'pt-PT': 'manutenção',
    'ur': 'برقرار رکھنا',
    'fa': 'حفظ',
    'hi': 'बनाए रखना',
    'id': 'pemeliharaan',
    'ms': 'pengekalan',
    'ja': '維持',
    'ko': '유지',
    'zh-Hans': '维持',
    'zh-Hant': '維持',
    'ru': 'поддержание',
    'bn': 'বজায় রাখা',
    'vi': 'duy trì',
    'th': 'รักษาน้ำหนัก',
    'pl': 'utrzymanie',
    'nl': 'behoud',
    'uk': 'підтримання',
  },
  'Dietary system': {
    'ar': 'النظام الغذائي',
    'en': 'Dietary system',
    'fr': 'Système alimentaire',
    'es': 'Sistema alimentario',
    'tr': 'Beslenme sistemi',
    'de': 'Ernährungssystem',
    'it': 'Sistema alimentare',
    'pt-BR': 'Sistema alimentar',
    'pt-PT': 'Sistema alimentar',
    'ur': 'غذائی نظام',
    'fa': 'نظام غذایی',
    'hi': 'आहार प्रणाली',
    'id': 'Sistem pola makan',
    'ms': 'Sistem pemakanan',
    'ja': '食事管理',
    'ko': '식단 시스템',
    'zh-Hans': '饮食体系',
    'zh-Hant': '飲食體系',
    'ru': 'Система питания',
    'bn': 'খাদ্যব্যবস্থা',
    'vi': 'Chế độ dinh dưỡng',
    'th': 'ระบบการรับประทานอาหาร',
    'pl': 'System żywieniowy',
    'nl': 'Voedingssysteem',
    'uk': 'Система харчування',
  },
  'Estimated time to goal': {
    'ar': 'الوقت التقديري للوصول إلى الهدف',
    'en': 'Estimated time to goal',
    'fr': 'Durée estimée pour atteindre l’objectif',
    'es': 'Tiempo estimado para alcanzar el objetivo',
    'tr': 'Hedefe ulaşmak için tahmini süre',
    'de': 'Geschätzte Zeit bis zum Ziel',
    'it': 'Tempo stimato per raggiungere l’obiettivo',
    'pt-BR': 'Tempo estimado até a meta',
    'pt-PT': 'Tempo estimado até ao objetivo',
    'ur': 'ہدف تک پہنچنے کا تخمینی وقت',
    'fa': 'زمان تخمینی تا رسیدن به هدف',
    'hi': 'लक्ष्य तक पहुँचने का अनुमानित समय',
    'id': 'Perkiraan waktu untuk mencapai target',
    'ms': 'Anggaran masa untuk mencapai matlamat',
    'ja': '目標達成までの推定期間',
    'ko': '목표 달성까지 예상 시간',
    'zh-Hans': '达成目标的预计时间',
    'zh-Hant': '達成目標的預估時間',
    'ru': 'Расчётное время до достижения цели',
    'bn': 'লক্ষ্য অর্জনের আনুমানিক সময়',
    'vi': 'Thời gian dự kiến để đạt mục tiêu',
    'th': 'ระยะเวลาโดยประมาณที่จะถึงเป้าหมาย',
    'pl': 'Szacowany czas do osiągnięcia celu',
    'nl': 'Geschatte tijd tot het doel',
    'uk': 'Орієнтовний час до досягнення цілі',
  },
  'Goal timeline': {
    'ar': 'الجدول الزمني للهدف',
    'en': 'Goal timeline',
    'fr': 'Calendrier de l’objectif',
    'es': 'Cronograma del objetivo',
    'tr': 'Hedef zaman çizelgesi',
    'de': 'Zeitplan zum Ziel',
    'it': 'Tempistica dell’obiettivo',
    'pt-BR': 'Cronograma da meta',
    'pt-PT': 'Cronograma do objetivo',
    'ur': 'ہدف کی مدت',
    'fa': 'جدول زمانی هدف',
    'hi': 'लक्ष्य की समयरेखा',
    'id': 'Linimasa target',
    'ms': 'Garis masa matlamat',
    'ja': '目標達成スケジュール',
    'ko': '목표 일정',
    'zh-Hans': '目标时间表',
    'zh-Hant': '目標時間表',
    'ru': 'Срок достижения цели',
    'bn': 'লক্ষ্য অর্জনের সময়রেখা',
    'vi': 'Tiến trình mục tiêu',
    'th': 'กรอบเวลาสู่เป้าหมาย',
    'pl': 'Harmonogram celu',
    'nl': 'Tijdlijn naar je doel',
    'uk': 'Термін досягнення цілі',
  },
  'Already at goal': {
    'ar': 'أنت عند الهدف بالفعل',
    'en': 'Already at goal',
    'fr': 'Objectif déjà atteint',
    'es': 'Ya estás en el objetivo',
    'tr': 'Hedefe zaten ulaştın',
    'de': 'Ziel bereits erreicht',
    'it': 'Obiettivo già raggiunto',
    'pt-BR': 'Meta já alcançada',
    'pt-PT': 'Objetivo já alcançado',
    'ur': 'ہدف پہلے ہی حاصل ہے',
    'fa': 'هم‌اکنون به هدف رسیده‌اید',
    'hi': 'लक्ष्य पहले ही हासिल है',
    'id': 'Target sudah tercapai',
    'ms': 'Matlamat sudah dicapai',
    'ja': 'すでに目標を達成しています',
    'ko': '이미 목표를 달성했습니다',
    'zh-Hans': '已达到目标',
    'zh-Hant': '已達成目標',
    'ru': 'Цель уже достигнута',
    'bn': 'লক্ষ্য ইতিমধ্যে অর্জিত',
    'vi': 'Đã đạt mục tiêu',
    'th': 'ถึงเป้าหมายแล้ว',
    'pl': 'Cel został już osiągnięty',
    'nl': 'Doel al bereikt',
    'uk': 'Цілі вже досягнуто',
  },
};
