import 'bil_locale_policy.dart';

/// Circle discovery and membership copy in every supported release locale.
abstract final class CommunityCirclesRuntimeCopy {
  static const sources = <String>[
    'My circles',
    'Search circles',
    'Search the circles loaded on this page.',
    'No circles are available yet.',
    'No circles match your search.',
    'You have not joined a circle yet.',
    'Description unavailable.',
    'Circle rules are unavailable.',
    'Invitation required',
    'Membership unavailable',
    'Requested',
    'Cancel request',
    'Joined',
  ];

  static const rows = <String, List<String>>{
    'en': sources,
    'ar': [
      'دوائري',
      'ابحث عن دائرة',
      'ابحث ضمن الدوائر المحمّلة في هذه الصفحة.',
      'لا توجد دوائر متاحة بعد.',
      'لا توجد دوائر تطابق بحثك.',
      'لم تنضم إلى أي دائرة بعد.',
      'الوصف غير متاح.',
      'قواعد الدائرة غير متاحة.',
      'تحتاج إلى دعوة',
      'العضوية غير متاحة',
      'الطلب مُرسل',
      'إلغاء الطلب',
      'منضم',
    ],
    'fr': [
      'Mes cercles',
      'Rechercher des cercles',
      'Recherchez parmi les cercles chargés sur cette page.',
      'Aucun cercle disponible pour le moment.',
      'Aucun cercle ne correspond à votre recherche.',
      'Vous n’avez pas encore rejoint de cercle.',
      'Description indisponible.',
      'Les règles du cercle sont indisponibles.',
      'Invitation requise',
      'Adhésion indisponible',
      'Demande envoyée',
      'Annuler la demande',
      'Membre',
    ],
    'es': [
      'Mis círculos',
      'Buscar círculos',
      'Busca entre los círculos cargados en esta página.',
      'Aún no hay círculos disponibles.',
      'Ningún círculo coincide con tu búsqueda.',
      'Aún no te has unido a ningún círculo.',
      'Descripción no disponible.',
      'Las reglas del círculo no están disponibles.',
      'Se requiere invitación',
      'Membresía no disponible',
      'Solicitud enviada',
      'Cancelar solicitud',
      'Miembro',
    ],
    'tr': [
      'Çevrelerim',
      'Çevrelerde ara',
      'Bu sayfada yüklenen çevrelerde arayın.',
      'Henüz kullanılabilir çevre yok.',
      'Aramanızla eşleşen çevre yok.',
      'Henüz bir çevreye katılmadınız.',
      'Açıklama mevcut değil.',
      'Çevre kuralları mevcut değil.',
      'Davet gerekiyor',
      'Üyelik kullanılamıyor',
      'İstek gönderildi',
      'İsteği iptal et',
      'Katıldınız',
    ],
    'de': [
      'Meine Kreise',
      'Kreise suchen',
      'Suche in den auf dieser Seite geladenen Kreisen.',
      'Es sind noch keine Kreise verfügbar.',
      'Keine Kreise entsprechen deiner Suche.',
      'Du bist noch keinem Kreis beigetreten.',
      'Beschreibung nicht verfügbar.',
      'Die Kreisregeln sind nicht verfügbar.',
      'Einladung erforderlich',
      'Mitgliedschaft nicht verfügbar',
      'Angefragt',
      'Anfrage zurückziehen',
      'Beigetreten',
    ],
    'it': [
      'Le mie cerchie',
      'Cerca cerchie',
      'Cerca tra le cerchie caricate in questa pagina.',
      'Non ci sono ancora cerchie disponibili.',
      'Nessuna cerchia corrisponde alla ricerca.',
      'Non fai ancora parte di una cerchia.',
      'Descrizione non disponibile.',
      'Le regole della cerchia non sono disponibili.',
      'Invito necessario',
      'Iscrizione non disponibile',
      'Richiesta inviata',
      'Annulla richiesta',
      'Membro',
    ],
    'pt-BR': [
      'Meus círculos',
      'Buscar círculos',
      'Busque entre os círculos carregados nesta página.',
      'Ainda não há círculos disponíveis.',
      'Nenhum círculo corresponde à sua busca.',
      'Você ainda não entrou em nenhum círculo.',
      'Descrição indisponível.',
      'As regras do círculo estão indisponíveis.',
      'Convite necessário',
      'Participação indisponível',
      'Solicitação enviada',
      'Cancelar solicitação',
      'Participando',
    ],
    'pt-PT': [
      'Os meus círculos',
      'Pesquisar círculos',
      'Pesquise entre os círculos carregados nesta página.',
      'Ainda não há círculos disponíveis.',
      'Nenhum círculo corresponde à sua pesquisa.',
      'Ainda não aderiu a nenhum círculo.',
      'Descrição indisponível.',
      'As regras do círculo estão indisponíveis.',
      'É necessário um convite',
      'Adesão indisponível',
      'Pedido enviado',
      'Cancelar pedido',
      'Aderiu',
    ],
    'ur': [
      'میرے حلقے',
      'حلقے تلاش کریں',
      'اس صفحے پر لوڈ کیے گئے حلقوں میں تلاش کریں۔',
      'ابھی کوئی حلقہ دستیاب نہیں ہے۔',
      'آپ کی تلاش سے کوئی حلقہ مطابقت نہیں رکھتا۔',
      'آپ ابھی کسی حلقے میں شامل نہیں ہوئے۔',
      'تفصیل دستیاب نہیں ہے۔',
      'حلقے کے اصول دستیاب نہیں ہیں۔',
      'دعوت ضروری ہے',
      'رکنیت دستیاب نہیں',
      'درخواست بھیج دی گئی',
      'درخواست منسوخ کریں',
      'شامل ہیں',
    ],
    'fa': [
      'حلقه‌های من',
      'جستجوی حلقه‌ها',
      'در حلقه‌های بارگیری‌شده در این صفحه جستجو کنید.',
      'هنوز حلقه‌ای در دسترس نیست.',
      'هیچ حلقه‌ای با جستجوی شما مطابقت ندارد.',
      'هنوز به هیچ حلقه‌ای نپیوسته‌اید.',
      'توضیحات در دسترس نیست.',
      'قوانین حلقه در دسترس نیست.',
      'دعوت لازم است',
      'عضویت در دسترس نیست',
      'درخواست ارسال شد',
      'لغو درخواست',
      'عضو هستید',
    ],
    'hi': [
      'मेरे सर्कल',
      'सर्कल खोजें',
      'इस पेज पर लोड किए गए सर्कल में खोजें।',
      'अभी कोई सर्कल उपलब्ध नहीं है।',
      'आपकी खोज से कोई सर्कल मेल नहीं खाता।',
      'आप अभी किसी सर्कल में शामिल नहीं हुए हैं।',
      'विवरण उपलब्ध नहीं है।',
      'सर्कल के नियम उपलब्ध नहीं हैं।',
      'आमंत्रण आवश्यक है',
      'सदस्यता उपलब्ध नहीं है',
      'अनुरोध भेजा गया',
      'अनुरोध रद्द करें',
      'शामिल हैं',
    ],
    'id': [
      'Lingkaran saya',
      'Cari lingkaran',
      'Cari di antara lingkaran yang dimuat di halaman ini.',
      'Belum ada lingkaran yang tersedia.',
      'Tidak ada lingkaran yang cocok dengan pencarian Anda.',
      'Anda belum bergabung dengan lingkaran mana pun.',
      'Deskripsi tidak tersedia.',
      'Aturan lingkaran tidak tersedia.',
      'Undangan diperlukan',
      'Keanggotaan tidak tersedia',
      'Permintaan terkirim',
      'Batalkan permintaan',
      'Bergabung',
    ],
    'ms': [
      'Lingkungan saya',
      'Cari lingkungan',
      'Cari dalam lingkungan yang dimuatkan di halaman ini.',
      'Belum ada lingkungan yang tersedia.',
      'Tiada lingkungan sepadan dengan carian anda.',
      'Anda belum menyertai mana-mana lingkungan.',
      'Penerangan tidak tersedia.',
      'Peraturan lingkungan tidak tersedia.',
      'Jemputan diperlukan',
      'Keahlian tidak tersedia',
      'Permintaan dihantar',
      'Batalkan permintaan',
      'Telah menyertai',
    ],
    'ja': [
      '参加中のサークル',
      'サークルを検索',
      'このページに読み込まれたサークルを検索します。',
      '利用できるサークルはまだありません。',
      '検索条件に一致するサークルはありません。',
      'まだサークルに参加していません。',
      '説明はありません。',
      'サークルのルールは表示できません。',
      '招待が必要です',
      '参加できません',
      '申請済み',
      '申請を取り消す',
      '参加中',
    ],
    'ko': [
      '내 서클',
      '서클 검색',
      '이 페이지에 불러온 서클에서 검색합니다.',
      '아직 이용 가능한 서클이 없습니다.',
      '검색과 일치하는 서클이 없습니다.',
      '아직 가입한 서클이 없습니다.',
      '설명을 볼 수 없습니다.',
      '서클 규칙을 볼 수 없습니다.',
      '초대 필요',
      '가입 불가',
      '요청됨',
      '요청 취소',
      '가입됨',
    ],
    'zh-Hans': [
      '我的圈子',
      '搜索圈子',
      '搜索本页已加载的圈子。',
      '暂无可用圈子。',
      '没有符合搜索条件的圈子。',
      '你还没有加入任何圈子。',
      '暂无描述。',
      '暂时无法查看圈子规则。',
      '需要邀请',
      '无法加入',
      '已申请',
      '取消申请',
      '已加入',
    ],
    'zh-Hant': [
      '我的圈子',
      '搜尋圈子',
      '搜尋本頁已載入的圈子。',
      '暫無可用的圈子。',
      '沒有符合搜尋條件的圈子。',
      '你還沒有加入任何圈子。',
      '暫無描述。',
      '暫時無法查看圈子規則。',
      '需要邀請',
      '無法加入',
      '已申請',
      '取消申請',
      '已加入',
    ],
    'ru': [
      'Мои круги',
      'Поиск кругов',
      'Поиск среди кругов, загруженных на этой странице.',
      'Доступных кругов пока нет.',
      'По вашему запросу кругов не найдено.',
      'Вы пока не вступили ни в один круг.',
      'Описание недоступно.',
      'Правила круга недоступны.',
      'Требуется приглашение',
      'Участие недоступно',
      'Запрос отправлен',
      'Отменить запрос',
      'Вы участник',
    ],
    'bn': [
      'আমার সার্কেল',
      'সার্কেল খুঁজুন',
      'এই পৃষ্ঠায় লোড হওয়া সার্কেলগুলির মধ্যে খুঁজুন।',
      'এখনও কোনও সার্কেল উপলব্ধ নেই।',
      'আপনার অনুসন্ধানের সঙ্গে কোনও সার্কেল মেলেনি।',
      'আপনি এখনও কোনও সার্কেলে যোগ দেননি।',
      'বিবরণ উপলব্ধ নেই।',
      'সার্কেলের নিয়ম উপলব্ধ নেই।',
      'আমন্ত্রণ প্রয়োজন',
      'সদস্যতা উপলব্ধ নেই',
      'অনুরোধ পাঠানো হয়েছে',
      'অনুরোধ বাতিল করুন',
      'যোগ দিয়েছেন',
    ],
    'vi': [
      'Nhóm của tôi',
      'Tìm nhóm',
      'Tìm trong các nhóm đã tải trên trang này.',
      'Chưa có nhóm nào khả dụng.',
      'Không có nhóm phù hợp với tìm kiếm của bạn.',
      'Bạn chưa tham gia nhóm nào.',
      'Chưa có mô tả.',
      'Chưa xem được quy tắc của nhóm.',
      'Cần lời mời',
      'Không thể tham gia',
      'Đã gửi yêu cầu',
      'Hủy yêu cầu',
      'Đã tham gia',
    ],
    'th': [
      'กลุ่มของฉัน',
      'ค้นหากลุ่ม',
      'ค้นหาในกลุ่มที่โหลดไว้ในหน้านี้',
      'ยังไม่มีกลุ่มที่พร้อมใช้งาน',
      'ไม่มีกลุ่มที่ตรงกับการค้นหาของคุณ',
      'คุณยังไม่ได้เข้าร่วมกลุ่มใด',
      'ไม่มีคำอธิบาย',
      'ไม่สามารถดูข้อกำหนดของกลุ่มได้',
      'ต้องมีคำเชิญ',
      'ไม่สามารถเข้าร่วมได้',
      'ส่งคำขอแล้ว',
      'ยกเลิกคำขอ',
      'เข้าร่วมแล้ว',
    ],
    'pl': [
      'Moje kręgi',
      'Szukaj kręgów',
      'Szukaj wśród kręgów wczytanych na tej stronie.',
      'Nie ma jeszcze dostępnych kręgów.',
      'Żaden krąg nie pasuje do wyszukiwania.',
      'Nie należysz jeszcze do żadnego kręgu.',
      'Opis jest niedostępny.',
      'Zasady kręgu są niedostępne.',
      'Wymagane zaproszenie',
      'Członkostwo niedostępne',
      'Wysłano prośbę',
      'Anuluj prośbę',
      'Dołączono',
    ],
    'nl': [
      'Mijn kringen',
      'Kringen zoeken',
      'Zoek in de kringen die op deze pagina zijn geladen.',
      'Er zijn nog geen kringen beschikbaar.',
      'Geen kringen komen overeen met je zoekopdracht.',
      'Je bent nog niet bij een kring aangesloten.',
      'Beschrijving niet beschikbaar.',
      'De kringregels zijn niet beschikbaar.',
      'Uitnodiging vereist',
      'Lidmaatschap niet beschikbaar',
      'Aangevraagd',
      'Aanvraag annuleren',
      'Lid',
    ],
    'uk': [
      'Мої кола',
      'Пошук кіл',
      'Шукайте серед кіл, завантажених на цій сторінці.',
      'Доступних кіл поки немає.',
      'За вашим запитом кіл не знайдено.',
      'Ви ще не приєдналися до жодного кола.',
      'Опис недоступний.',
      'Правила кола недоступні.',
      'Потрібне запрошення',
      'Участь недоступна',
      'Запит надіслано',
      'Скасувати запит',
      'Ви учасник',
    ],
  };

  static String? resolve(String source, String localeTag) {
    final index = sources.indexOf(source);
    if (index < 0) return null;
    final tag = BilLocalePolicy.canonicalSupportedTag(localeTag);
    final row = rows[tag];
    if (row == null) return null;
    if (row.length != sources.length) {
      throw StateError('Incomplete Community Circles copy for $tag');
    }
    return row[index];
  }
}
