part of 'runtime_copy_community_reference.dart';

const _communityReferenceSoutheastAsiaRows = <String, List<String>>{
  "id": <String>[
    "Tambahkan hashtag",
    "Tambahkan sesuatu sebelum menyimpan draf.",
    "Tambahkan hingga 10 hashtag yang dapat dicari.",
    "Dihargai",
    "Momen yang disetujui",
    "Profil Komunitas BIL",
    "BIL akan kembali ke sampul Komunitas bermerek.",
    "Lencana",
    "Sertifikasi",
    "Sertifikasi dicabut",
    "Kreator tersertifikasi",
    "Pilih gambar JPEG, PNG, atau WebP yang valid hingga 5 MB.",
    "Kolaborasi diterima.",
    "Kolaborasi ditolak.",
    "Undangan kolaborasi",
    "Undangan kolaborasi diterima",
    "Kolaborasi — opsional",
    "Komentar diterima",
    "Lencana Komunitas",
    "Pembangun komunitas",
    "Beranda Komunitas",
    "Penghubung",
    "Kontributor",
    "Pemulai percakapan",
    "Draf ini tidak dapat dihapus.",
    "Berbagi tidak dapat dibuka saat ini.",
    "Draf ini tidak dapat dibuka. Coba lagi.",
    "Sampul profil tidak dapat dihapus.",
    "Draf ini tidak dapat disimpan. Tidak ada yang dipublikasikan.",
    "Kolaborator tidak dapat dicari saat ini.",
    "Status mengikuti tidak dapat diperbarui.",
    "Sampul profil tidak dapat diperbarui.",
    "Kolaborasi ini tidak dapat diperbarui. Coba lagi.",
    "Pusat Kreator",
    "Hadiah Kreator",
    "Alat kreator",
    "Ditolak",
    "Hapus draf",
    "Draf disimpan dengan aman.",
    "Draf",
    "Momen pertama",
    "Mengikuti Anda",
    "Beri momen ini judul yang jelas",
    "Hashtag — opsional",
    "Undang hingga 3 anggota Komunitas. Undangan hanya dikirim setelah persetujuan manusia, dan kolaborator hanya tampil secara publik setelah menerima.",
    "Suka diterima",
    "Terkunci",
    "Momen",
    "Momen bersifat pribadi di profil ini.",
    "Pengikut baru",
    "Profil ini belum menerima sertifikasi kreator BIL.",
    "Belum ada ulasan yang disetujui.",
    "Belum ada draf tersimpan.",
    "Belum ada momen yang terlihat.",
    "Belum tersertifikasi",
    "Buka",
    "Draf foto",
    "Sampul profil diperbarui.",
    "Telah dipublikasikan",
    "Rujukan yang memenuhi syarat",
    "Hapus sampul profil?",
    "Ulasan",
    "Ulasan bersifat pribadi di profil ini.",
    "Simpan draf",
    "Simpan postingan Komunitas yang belum selesai dan lanjutkan nanti.",
    "Draf Komunitas tersimpan",
    "Draf tersimpan",
    "Cari berdasarkan nama atau @handle",
    "Cari kolaborator",
    "Bagikan profil",
    "Pusat Tugas",
    "Transkrip suara akan melebihi batas 1200 karakter postingan.",
    "Circle ini tidak tersedia saat ini.",
    "Sertifikasi ini diverifikasi oleh otoritas server BIL.",
    "Profil ini saat ini tidak memiliki sertifikasi aktif.",
    "Topik ini tidak tersedia saat ini.",
    "Judul",
    "Draf tanpa judul",
    "Perbarui draf",
    "Pembaruan",
    "Gunakan satu hashtag tanpa spasi, maksimal 40 karakter.",
    "Dengan",
    "Anda dapat menambahkan hingga 10 hashtag.",
    "{actor} menerima undangan kolaborasi Anda",
    "{actor} mengundang Anda untuk berkolaborasi pada sebuah postingan",
    "Level Komunitas tertinggi yang dikonfigurasi telah tercapai",
    "{xp} XP · Berikutnya: Lv {level} pada {target} XP",
    "Progres menuju Lv {level} · target {target} XP",
  ],
  "ms": <String>[
    "Tambah hashtag",
    "Tambah sesuatu sebelum menyimpan draf.",
    "Tambah sehingga 10 hashtag yang boleh dicari.",
    "Dihargai",
    "Momen yang diluluskan",
    "Profil Komuniti BIL",
    "BIL akan kembali kepada kulit Komuniti berjenama.",
    "Lencana",
    "Pensijilan",
    "Pensijilan ditarik balik",
    "Pencipta diperakui",
    "Pilih imej JPEG, PNG atau WebP yang sah sehingga 5 MB.",
    "Kerjasama diterima.",
    "Kerjasama ditolak.",
    "Jemputan kerjasama",
    "Jemputan kerjasama diterima",
    "Kerjasama — pilihan",
    "Komen diterima",
    "Lencana Komuniti",
    "Pembina komuniti",
    "Halaman utama Komuniti",
    "Penghubung",
    "Penyumbang",
    "Pemula perbualan",
    "Draf ini tidak dapat dipadamkan.",
    "Perkongsian tidak dapat dibuka sekarang.",
    "Draf ini tidak dapat dibuka. Cuba lagi.",
    "Penutup profil tidak dapat dibuang.",
    "Draf ini tidak dapat disimpan. Tiada apa-apa diterbitkan.",
    "Kolaborator tidak dapat dicari sekarang.",
    "Status mengikuti tidak dapat dikemas kini.",
    "Penutup profil tidak dapat dikemas kini.",
    "Kerjasama ini tidak dapat dikemas kini. Cuba lagi.",
    "Pusat Pencipta",
    "Ganjaran Pencipta",
    "Alat pencipta",
    "Ditolak",
    "Padam draf",
    "Draf disimpan dengan selamat.",
    "Draf",
    "Momen pertama",
    "Mengikuti anda",
    "Beri momen ini tajuk yang jelas",
    "Hashtag — pilihan",
    "Jemput sehingga 3 ahli Komuniti. Jemputan hanya dihantar selepas kelulusan manusia, dan kolaborator hanya dipaparkan secara umum selepas menerima.",
    "Suka diterima",
    "Dikunci",
    "Momen",
    "Momen adalah peribadi pada profil ini.",
    "Pengikut baharu",
    "Profil ini belum diberikan pensijilan pencipta BIL.",
    "Belum ada ulasan yang diluluskan.",
    "Belum ada draf tersimpan.",
    "Belum ada momen yang kelihatan.",
    "Belum diperakui",
    "Buka",
    "Draf foto",
    "Penutup profil dikemas kini.",
    "Diterbitkan",
    "Rujukan yang layak",
    "Buang penutup profil?",
    "Ulasan",
    "Ulasan adalah peribadi pada profil ini.",
    "Simpan draf",
    "Simpan siaran Komuniti yang belum siap dan sambung kemudian.",
    "Draf Komuniti tersimpan",
    "Draf tersimpan",
    "Cari mengikut nama atau @handle",
    "Cari kolaborator",
    "Kongsi profil",
    "Pusat Tugasan",
    "Transkrip suara akan melebihi had 1200 aksara siaran.",
    "Circle ini tidak tersedia sekarang.",
    "Pensijilan ini disahkan oleh autoriti pelayan BIL.",
    "Profil ini tidak mempunyai pensijilan aktif pada masa ini.",
    "Topik ini tidak tersedia sekarang.",
    "Tajuk",
    "Draf tanpa tajuk",
    "Kemas kini draf",
    "Kemas kini",
    "Gunakan satu hashtag tanpa ruang, sehingga 40 aksara.",
    "Dengan",
    "Anda boleh menambah sehingga 10 hashtag.",
    "{actor} menerima jemputan kerjasama anda",
    "{actor} menjemput anda untuk bekerjasama pada satu siaran",
    "Tahap Komuniti tertinggi yang dikonfigurasi telah dicapai",
    "{xp} XP · Seterusnya: Lv {level} pada {target} XP",
    "Kemajuan menuju Lv {level} · sasaran {target} XP",
  ],
  "vi": <String>[
    "Thêm hashtag",
    "Thêm nội dung trước khi lưu bản nháp.",
    "Thêm tối đa 10 hashtag có thể tìm kiếm.",
    "Được ghi nhận",
    "Khoảnh khắc đã duyệt",
    "Hồ sơ Cộng đồng BIL",
    "BIL sẽ quay lại ảnh bìa Cộng đồng mang thương hiệu.",
    "Huy hiệu",
    "Chứng nhận",
    "Chứng nhận đã bị thu hồi",
    "Nhà sáng tạo đã được chứng nhận",
    "Chọn ảnh JPEG, PNG hoặc WebP hợp lệ có dung lượng tối đa 5 MB.",
    "Đã chấp nhận cộng tác.",
    "Đã từ chối cộng tác.",
    "Lời mời cộng tác",
    "Đã chấp nhận lời mời cộng tác",
    "Cộng tác — không bắt buộc",
    "Bình luận đã nhận",
    "Huy hiệu Cộng đồng",
    "Người xây dựng cộng đồng",
    "Trang chủ Cộng đồng",
    "Người kết nối",
    "Người đóng góp",
    "Người khởi xướng trò chuyện",
    "Không thể xóa bản nháp này.",
    "Hiện không thể mở tính năng chia sẻ.",
    "Không thể mở bản nháp này. Hãy thử lại.",
    "Không thể xóa ảnh bìa hồ sơ.",
    "Không thể lưu bản nháp này. Chưa có nội dung nào được đăng.",
    "Hiện không thể tìm người cộng tác.",
    "Không thể cập nhật trạng thái theo dõi.",
    "Không thể cập nhật ảnh bìa hồ sơ.",
    "Không thể cập nhật cộng tác này. Hãy thử lại.",
    "Trung tâm Nhà sáng tạo",
    "Phần thưởng Nhà sáng tạo",
    "Công cụ nhà sáng tạo",
    "Đã từ chối",
    "Xóa bản nháp",
    "Đã lưu bản nháp an toàn.",
    "Bản nháp",
    "Khoảnh khắc đầu tiên",
    "Đang theo dõi bạn",
    "Đặt tiêu đề rõ ràng cho khoảnh khắc này",
    "Hashtag — không bắt buộc",
    "Mời tối đa 3 thành viên Cộng đồng. Lời mời chỉ được gửi sau khi có phê duyệt của con người, và người cộng tác chỉ xuất hiện công khai sau khi chấp nhận.",
    "Lượt thích đã nhận",
    "Đã khóa",
    "Khoảnh khắc",
    "Khoảnh khắc trên hồ sơ này là riêng tư.",
    "Người theo dõi mới",
    "Hồ sơ này chưa được cấp chứng nhận nhà sáng tạo BIL.",
    "Chưa có đánh giá nào được duyệt.",
    "Chưa có bản nháp nào được lưu.",
    "Chưa có khoảnh khắc nào hiển thị.",
    "Chưa được chứng nhận",
    "Mở",
    "Bản nháp ảnh",
    "Đã cập nhật ảnh bìa hồ sơ.",
    "Đã đăng",
    "Lượt giới thiệu đủ điều kiện",
    "Xóa ảnh bìa hồ sơ?",
    "Đánh giá",
    "Đánh giá trên hồ sơ này là riêng tư.",
    "Lưu bản nháp",
    "Lưu các bài đăng Cộng đồng chưa hoàn tất và tiếp tục sau.",
    "Bản nháp Cộng đồng đã lưu",
    "Bản nháp đã lưu",
    "Tìm theo tên hoặc @handle",
    "Tìm người cộng tác",
    "Chia sẻ hồ sơ",
    "Trung tâm Nhiệm vụ",
    "Bản chép lời bằng giọng nói sẽ vượt quá giới hạn 1200 ký tự của bài đăng.",
    "Circle này hiện không khả dụng.",
    "Chứng nhận này được xác minh bởi cơ quan máy chủ BIL.",
    "Hồ sơ này hiện không có chứng nhận đang hoạt động.",
    "Chủ đề này hiện không khả dụng.",
    "Tiêu đề",
    "Bản nháp chưa có tiêu đề",
    "Cập nhật bản nháp",
    "Cập nhật",
    "Dùng một hashtag không có khoảng trắng, tối đa 40 ký tự.",
    "Cùng với",
    "Bạn có thể thêm tối đa 10 hashtag.",
    "{actor} đã chấp nhận lời mời cộng tác của bạn",
    "{actor} đã mời bạn cộng tác trên một bài đăng",
    "Đã đạt cấp Cộng đồng cao nhất được cấu hình",
    "{xp} XP · Tiếp theo: Cấp {level} tại {target} XP",
    "Tiến độ tới Cấp {level} · mục tiêu {target} XP",
  ],
  "th": <String>[
    "เพิ่มแฮชแท็ก",
    "เพิ่มเนื้อหาก่อนบันทึกร่าง",
    "เพิ่มแฮชแท็กที่ค้นหาได้สูงสุด 10 รายการ",
    "ได้รับการชื่นชม",
    "โมเมนต์ที่อนุมัติแล้ว",
    "โปรไฟล์ชุมชน BIL",
    "BIL จะกลับไปใช้ภาพปกชุมชนที่มีแบรนด์",
    "เหรียญตรา",
    "การรับรอง",
    "เพิกถอนการรับรองแล้ว",
    "ครีเอเตอร์ที่ได้รับการรับรอง",
    "เลือกรูป JPEG, PNG หรือ WebP ที่ถูกต้อง ขนาดไม่เกิน 5 MB",
    "ยอมรับการร่วมงานแล้ว",
    "ปฏิเสธการร่วมงานแล้ว",
    "คำเชิญร่วมงาน",
    "ยอมรับคำเชิญร่วมงานแล้ว",
    "การร่วมงาน — ไม่บังคับ",
    "ความคิดเห็นที่ได้รับ",
    "เหรียญตราชุมชน",
    "ผู้สร้างชุมชน",
    "หน้าหลักชุมชน",
    "ผู้เชื่อมโยง",
    "ผู้มีส่วนร่วม",
    "ผู้เริ่มบทสนทนา",
    "ลบร่างนี้ไม่ได้",
    "เปิดการแชร์ไม่ได้ในขณะนี้",
    "เปิดร่างนี้ไม่ได้ ลองอีกครั้ง",
    "ลบภาพปกโปรไฟล์ไม่ได้",
    "บันทึกร่างนี้ไม่ได้ ไม่มีสิ่งใดถูกเผยแพร่",
    "ค้นหาผู้ร่วมงานไม่ได้ในขณะนี้",
    "อัปเดตสถานะการติดตามไม่ได้",
    "อัปเดตภาพปกโปรไฟล์ไม่ได้",
    "อัปเดตการร่วมงานนี้ไม่ได้ ลองอีกครั้ง",
    "ศูนย์ครีเอเตอร์",
    "รางวัลครีเอเตอร์",
    "เครื่องมือครีเอเตอร์",
    "ปฏิเสธแล้ว",
    "ลบร่าง",
    "บันทึกร่างอย่างปลอดภัยแล้ว",
    "ร่าง",
    "โมเมนต์แรก",
    "ติดตามคุณ",
    "ตั้งชื่อที่ชัดเจนให้โมเมนต์นี้",
    "แฮชแท็ก — ไม่บังคับ",
    "เชิญสมาชิกชุมชนได้สูงสุด 3 คน ระบบจะส่งคำเชิญหลังการอนุมัติโดยมนุษย์เท่านั้น และผู้ร่วมงานจะแสดงต่อสาธารณะหลังจากยอมรับแล้วเท่านั้น",
    "ยอดถูกใจที่ได้รับ",
    "ล็อกอยู่",
    "โมเมนต์",
    "โมเมนต์ในโปรไฟล์นี้เป็นส่วนตัว",
    "ผู้ติดตามใหม่",
    "โปรไฟล์นี้ยังไม่ได้รับการรับรองครีเอเตอร์จาก BIL",
    "ยังไม่มีรีวิวที่อนุมัติ",
    "ยังไม่มีร่างที่บันทึกไว้",
    "ยังไม่มีโมเมนต์ที่มองเห็นได้",
    "ยังไม่ได้รับการรับรอง",
    "เปิด",
    "ร่างรูปภาพ",
    "อัปเดตภาพปกโปรไฟล์แล้ว",
    "เผยแพร่แล้ว",
    "การแนะนำที่ผ่านเกณฑ์",
    "ลบภาพปกโปรไฟล์หรือไม่",
    "รีวิว",
    "รีวิวในโปรไฟล์นี้เป็นส่วนตัว",
    "บันทึกร่าง",
    "บันทึกโพสต์ชุมชนที่ยังไม่เสร็จและกลับมาทำต่อภายหลัง",
    "ร่างชุมชนที่บันทึกไว้",
    "ร่างที่บันทึกไว้",
    "ค้นหาด้วยชื่อหรือ @handle",
    "ค้นหาผู้ร่วมงาน",
    "แชร์โปรไฟล์",
    "ศูนย์งาน",
    "ข้อความถอดเสียงจะเกินขีดจำกัดโพสต์ 1200 อักขระ",
    "Circle นี้ใช้งานไม่ได้ในขณะนี้",
    "การรับรองนี้ได้รับการตรวจสอบโดยระบบเซิร์ฟเวอร์ BIL",
    "โปรไฟล์นี้ไม่มีการรับรองที่ใช้งานอยู่ในขณะนี้",
    "หัวข้อนี้ใช้งานไม่ได้ในขณะนี้",
    "ชื่อเรื่อง",
    "ร่างไม่มีชื่อ",
    "อัปเดตร่าง",
    "อัปเดต",
    "ใช้แฮชแท็กเดียวโดยไม่มีช่องว่าง สูงสุด 40 อักขระ",
    "ร่วมกับ",
    "คุณเพิ่มแฮชแท็กได้สูงสุด 10 รายการ",
    "{actor} ยอมรับคำเชิญร่วมงานของคุณแล้ว",
    "{actor} เชิญคุณให้ร่วมงานในโพสต์",
    "ถึงระดับชุมชนสูงสุดที่กำหนดค่าไว้แล้ว",
    "{xp} XP · ถัดไป: Lv {level} ที่ {target} XP",
    "ความคืบหน้าสู่ Lv {level} · เป้าหมาย {target} XP",
  ],
};
