part of 'runtime_copy_community_social.dart';

const _communitySocialEuropeRows = <String, List<String>>{
  'it': <String>[
    'Aggiungi @{handle} su BIL: {uri}',
    'Aggiungi amico',
    'Blocca',
    'Bloccare questo membro?',
    'L’accesso alla fotocamera è negato o limitato. Abilitalo nelle impostazioni di sistema e riprova.',
    'Annulla risposta',
    'La scansione del codice richiede una fotocamera iOS o Android.',
    'Il commento non è stato inviato. Il testo è conservato; riprova in sicurezza.',
    'Commenti',
    'Impossibile caricare i post meno recenti. Riprova.',
    'Impossibile aggiornare i post salvati. Riprova.',
    'Impossibile aggiornare questa reazione. Riprova.',
    'Impossibile inviare la richiesta di amicizia. Riprova.',
    'Chiedi a un amico di scansionare questo codice. Identifica soltanto il tuo profilo pubblico della Community; non può far accedere nessuno.',
    'Carica altro',
    'Carica altri commenti',
    'Carica post meno recenti',
    'Membro bloccato.',
    'Il mio codice BIL',
    'Non ci sono ancora commenti. Inizia una conversazione rispettosa.',
    'Inquadra un codice amico BIL con la fotocamera. Non viene caricato nulla.',
    'Pubblicazione',
    'I post che salvi sono privati e vengono visualizzati qui.',
    'Rimuovi dai salvati',
    'Sostituisci codice',
    'Sostituisci questo codice',
    'Sostituire il tuo codice BIL?',
    'Rispondi',
    'Risposta a {member}',
    'Segnalazione inviata per la revisione umana.',
    'Riprova con la fotocamera',
    'Esamina richiesta',
    'Salva post',
    'Post salvati',
    'Scansiona codice amico',
    'Invia commento',
    'Condividi codice',
    'Condividi post',
    'Mostra meno',
    'Mostra altro',
    'Questo codice non è valido, è scaduto, privato o non disponibile.',
    'Questo non è un codice amico BIL attuale.',
    'Scrivi un commento',
    'Prima scrivi un commento.',
    'Non vi vedrete più nella Community o nei messaggi.',
    'Il tuo codice BIL non è disponibile al momento. Riprova.',
    'Il tuo codice BIL non è disponibile. Accedi, completa il profilo della Community e riprova.',
    'Il tuo vecchio codice smetterà di funzionare. Gli amici dovranno usare quello nuovo.',
  ],
  'pt-BR': <String>[
    'Adicione @{handle} no BIL: {uri}',
    'Adicionar amigo',
    'Bloquear',
    'Bloquear este membro?',
    'O acesso à câmera foi negado ou está restrito. Ative-o nas configurações do sistema e tente novamente.',
    'Cancelar resposta',
    'A leitura do código precisa de uma câmera em um dispositivo iOS ou Android.',
    'O comentário não foi enviado. Seu texto foi mantido; tente novamente com segurança.',
    'Comentários',
    'Não foi possível carregar publicações mais antigas. Tente novamente.',
    'Não foi possível atualizar as publicações salvas. Tente novamente.',
    'Não foi possível atualizar esta reação. Tente novamente.',
    'Não foi possível enviar a solicitação de amizade. Tente novamente.',
    'Peça a um amigo para ler este código. Ele identifica apenas seu perfil público na Comunidade e não permite que ninguém entre na sua conta.',
    'Carregar mais',
    'Carregar mais comentários',
    'Carregar publicações mais antigas',
    'Membro bloqueado.',
    'Meu código BIL',
    'Ainda não há comentários. Inicie uma conversa respeitosa.',
    'Aponte a câmera para um código de amigo do BIL. Nada é enviado.',
    'Publicação',
    'As publicações salvas são privadas e aparecem aqui.',
    'Remover dos salvos',
    'Substituir código',
    'Substituir este código',
    'Substituir seu código BIL?',
    'Responder',
    'Respondendo a {member}',
    'Denúncia enviada para análise humana.',
    'Tentar a câmera novamente',
    'Analisar solicitação',
    'Salvar publicação',
    'Publicações salvas',
    'Ler código de amigo',
    'Enviar comentário',
    'Compartilhar código',
    'Compartilhar publicação',
    'Mostrar menos',
    'Mostrar mais',
    'Este código é inválido, expirou, é privado ou está indisponível.',
    'Este não é um código de amigo atual do BIL.',
    'Escreva um comentário',
    'Escreva um comentário primeiro.',
    'Vocês não se verão mais na Comunidade nem nas mensagens.',
    'Seu código BIL está indisponível no momento. Tente novamente.',
    'Seu código BIL está indisponível. Entre na conta, complete seu perfil da Comunidade e tente novamente.',
    'Seu código antigo deixará de funcionar. Seus amigos precisarão do novo.',
  ],
  'pt-PT': <String>[
    'Adicione @{handle} no BIL: {uri}',
    'Adicionar amigo',
    'Bloquear',
    'Bloquear este membro?',
    'O acesso à câmara foi recusado ou está limitado. Ative-o nas definições do sistema e tente novamente.',
    'Cancelar resposta',
    'A leitura do código requer uma câmara num dispositivo iOS ou Android.',
    'O comentário não foi enviado. O seu texto foi mantido; tente novamente em segurança.',
    'Comentários',
    'Não foi possível carregar publicações mais antigas. Tente novamente.',
    'Não foi possível atualizar as publicações guardadas. Tente novamente.',
    'Não foi possível atualizar esta reação. Tente novamente.',
    'Não foi possível enviar o pedido de amizade. Tente novamente.',
    'Peça a um amigo para ler este código. Este identifica apenas o seu perfil público na Comunidade e não permite que ninguém inicie sessão.',
    'Carregar mais',
    'Carregar mais comentários',
    'Carregar publicações mais antigas',
    'Membro bloqueado.',
    'O meu código BIL',
    'Ainda não há comentários. Inicie uma conversa respeitosa.',
    'Aponte a câmara para um código de amigo do BIL. Nada é carregado.',
    'Publicação',
    'As publicações que guarda são privadas e aparecem aqui.',
    'Remover dos guardados',
    'Substituir código',
    'Substituir este código',
    'Substituir o seu código BIL?',
    'Responder',
    'A responder a {member}',
    'Denúncia enviada para análise humana.',
    'Tentar novamente com a câmara',
    'Analisar pedido',
    'Guardar publicação',
    'Publicações guardadas',
    'Ler código de amigo',
    'Enviar comentário',
    'Partilhar código',
    'Partilhar publicação',
    'Mostrar menos',
    'Mostrar mais',
    'Este código é inválido, expirou, é privado ou está indisponível.',
    'Este não é um código de amigo atual do BIL.',
    'Escreva um comentário',
    'Escreva primeiro um comentário.',
    'Deixarão de se ver na Comunidade e nas mensagens.',
    'O seu código BIL está indisponível neste momento. Tente novamente.',
    'O seu código BIL está indisponível. Inicie sessão, complete o perfil da Comunidade e tente novamente.',
    'O seu código antigo deixará de funcionar. Os amigos precisarão do novo.',
  ],
  'pl': <String>[
    'Dodaj @{handle} w BIL: {uri}',
    'Dodaj znajomego',
    'Zablokuj',
    'Zablokować tego użytkownika?',
    'Odmówiono dostępu do aparatu lub dostęp jest ograniczony. Włącz go w ustawieniach systemu i spróbuj ponownie.',
    'Anuluj odpowiedź',
    'Skanowanie kodu wymaga aparatu urządzenia z systemem iOS lub Android.',
    'Komentarz nie został wysłany. Twój tekst zachowano; możesz bezpiecznie spróbować ponownie.',
    'Komentarze',
    'Nie udało się wczytać starszych postów. Spróbuj ponownie.',
    'Nie udało się zaktualizować zapisanych postów. Spróbuj ponownie.',
    'Nie udało się zaktualizować tej reakcji. Spróbuj ponownie.',
    'Nie udało się wysłać zaproszenia do znajomych. Spróbuj ponownie.',
    'Poproś znajomego o zeskanowanie tego kodu. Kod tylko identyfikuje Twój publiczny profil społeczności i nie pozwala nikomu się zalogować.',
    'Wczytaj więcej',
    'Wczytaj więcej komentarzy',
    'Wczytaj starsze posty',
    'Użytkownik został zablokowany.',
    'Mój kod BIL',
    'Nie ma jeszcze komentarzy. Rozpocznij rozmowę z szacunkiem.',
    'Skieruj aparat na kod znajomego BIL. Żadne dane nie zostaną przesłane.',
    'Wpis',
    'Zapisane przez Ciebie posty są prywatne i pojawiają się tutaj.',
    'Usuń z zapisanych',
    'Zastąp kod',
    'Zastąp ten kod',
    'Zastąpić Twój kod BIL?',
    'Odpowiedz',
    'Odpowiedź do: {member}',
    'Zgłoszenie wysłano do weryfikacji przez człowieka.',
    'Ponów próbę użycia aparatu',
    'Sprawdź zaproszenie',
    'Zapisz post',
    'Zapisane posty',
    'Skanuj kod znajomego',
    'Wyślij komentarz',
    'Udostępnij kod',
    'Udostępnij post',
    'Pokaż mniej',
    'Pokaż więcej',
    'Ten kod jest nieprawidłowy, wygasł, jest prywatny lub niedostępny.',
    'To nie jest aktualny kod znajomego BIL.',
    'Napisz komentarz',
    'Najpierw napisz komentarz.',
    'Nie będziecie się już widzieć w społeczności ani w wiadomościach.',
    'Twój kod BIL jest teraz niedostępny. Spróbuj ponownie.',
    'Twój kod BIL jest niedostępny. Zaloguj się, uzupełnij profil społeczności i spróbuj ponownie.',
    'Twój stary kod przestanie działać. Znajomi będą potrzebować nowego.',
  ],
  'nl': <String>[
    'Voeg @{handle} toe op BIL: {uri}',
    'Vriend toevoegen',
    'Blokkeren',
    'Dit lid blokkeren?',
    'Toegang tot de camera is geweigerd of beperkt. Schakel deze in via de systeeminstellingen en probeer het opnieuw.',
    'Antwoord annuleren',
    'Voor het scannen van codes is een camera van een iOS- of Android-apparaat nodig.',
    'De opmerking is niet verzonden. Je tekst is bewaard; probeer het gerust opnieuw.',
    'Opmerkingen',
    'Oudere berichten konden niet worden geladen. Probeer het opnieuw.',
    'Opgeslagen berichten konden niet worden bijgewerkt. Probeer het opnieuw.',
    'Deze reactie kon niet worden bijgewerkt. Probeer het opnieuw.',
    'Het vriendschapsverzoek kon niet worden verzonden. Probeer het opnieuw.',
    'Laat een vriend deze code scannen. De code identificeert alleen je openbare communityprofiel en kan niemand aanmelden.',
    'Meer laden',
    'Meer opmerkingen laden',
    'Oudere berichten laden',
    'Lid geblokkeerd.',
    'Mijn BIL-code',
    'Nog geen opmerkingen. Begin een respectvol gesprek.',
    'Richt de camera op een BIL-vriendencode. Er wordt niets geüpload.',
    'Bericht',
    'Berichten die je opslaat zijn privé en verschijnen hier.',
    'Verwijderen uit opgeslagen items',
    'Code vervangen',
    'Deze code vervangen',
    'Je BIL-code vervangen?',
    'Antwoorden',
    'Je antwoordt op {member}',
    'Melding verzonden voor menselijke beoordeling.',
    'Camera opnieuw proberen',
    'Verzoek beoordelen',
    'Bericht opslaan',
    'Opgeslagen berichten',
    'Vriendencode scannen',
    'Opmerking verzenden',
    'Code delen',
    'Bericht delen',
    'Minder weergeven',
    'Meer weergeven',
    'Deze code is ongeldig, verlopen, privé of niet beschikbaar.',
    'Dit is geen actuele BIL-vriendencode.',
    'Een opmerking schrijven',
    'Schrijf eerst een opmerking.',
    'Jullie zien elkaar niet meer in de community of in berichten.',
    'Je BIL-code is momenteel niet beschikbaar. Probeer het opnieuw.',
    'Je BIL-code is niet beschikbaar. Meld je aan, voltooi je communityprofiel en probeer het opnieuw.',
    'Je oude code werkt niet meer. Vrienden hebben de nieuwe nodig.',
  ],
  'uk': <String>[
    'Додати @{handle} у BIL: {uri}',
    'Додати в друзі',
    'Заблокувати',
    'Заблокувати цього учасника?',
    'Доступ до камери заборонено або обмежено. Увімкніть його в системних налаштуваннях і повторіть спробу.',
    'Скасувати відповідь',
    'Для сканування коду потрібна камера пристрою з iOS або Android.',
    'Коментар не надіслано. Ваш текст збережено; можна безпечно повторити спробу.',
    'Коментарі',
    'Не вдалося завантажити давніші дописи. Повторіть спробу.',
    'Не вдалося оновити збережені дописи. Повторіть спробу.',
    'Не вдалося оновити цю реакцію. Повторіть спробу.',
    'Не вдалося надіслати запит на додавання в друзі. Повторіть спробу.',
    'Попросіть друга відсканувати цей код. Він лише ідентифікує ваш загальнодоступний профіль спільноти й не дає нікому ввійти в обліковий запис.',
    'Завантажити ще',
    'Завантажити ще коментарі',
    'Завантажити давніші дописи',
    'Учасника заблоковано.',
    'Мій код BIL',
    'Коментарів ще немає. Розпочніть шанобливу розмову.',
    'Наведіть камеру на код друга BIL. Нічого не завантажується.',
    'Допис',
    'Збережені вами дописи приватні й відображаються тут.',
    'Видалити зі збережених',
    'Замінити код',
    'Замінити цей код',
    'Замінити ваш код BIL?',
    'Відповісти',
    'Відповідь для {member}',
    'Скаргу надіслано на перевірку людиною.',
    'Повторити спробу з камерою',
    'Переглянути запит',
    'Зберегти допис',
    'Збережені дописи',
    'Сканувати код друга',
    'Надіслати коментар',
    'Поділитися кодом',
    'Поділитися дописом',
    'Згорнути',
    'Показати більше',
    'Цей код недійсний, прострочений, приватний або недоступний.',
    'Це не чинний код друга BIL.',
    'Написати коментар',
    'Спочатку напишіть коментар.',
    'Ви більше не бачитимете одне одного в спільноті та повідомленнях.',
    'Ваш код BIL зараз недоступний. Повторіть спробу.',
    'Ваш код BIL недоступний. Увійдіть, заповніть профіль спільноти й повторіть спробу.',
    'Старий код перестане працювати. Друзям знадобиться новий.',
  ],
};
