import 'bil_locale_policy.dart';

/// Reviewed copy shared by every Profile surface.
///
/// Keep the regional Portuguese and scripted Chinese tags separate. Profile
/// previously rebuilt locales from [Locale.languageCode], which collapsed
/// these variants and exposed English fallback copy.
abstract final class ProfileRuntimeCopy {
  static const supported = <String>{
    'ar',
    'en',
    'fr',
    'es',
    'tr',
    'de',
    'it',
    'pt-BR',
    'pt-PT',
    'ur',
    'fa',
    'hi',
    'id',
    'ms',
    'ja',
    'ko',
    'zh-Hans',
    'zh-Hant',
    'ru',
    'bn',
    'vi',
    'th',
    'pl',
    'nl',
    'uk',
  };

  static const values = <String, Map<String, String>>{
    'Email address': {
      'ar': 'البريد الإلكتروني',
      'en': 'Email address',
      'fr': 'Adresse e-mail',
      'es': 'Correo electrónico',
      'tr': 'E-posta adresi',
      'de': 'E-Mail-Adresse',
      'it': 'Indirizzo e-mail',
      'pt-BR': 'Endereço de e-mail',
      'pt-PT': 'Endereço de e-mail',
      'ur': 'ای میل پتہ',
      'fa': 'نشانی ایمیل',
      'hi': 'ईमेल पता',
      'id': 'Alamat email',
      'ms': 'Alamat e-mel',
      'ja': 'メールアドレス',
      'ko': '이메일 주소',
      'zh-Hans': '电子邮箱地址',
      'zh-Hant': '電子郵件地址',
      'ru': 'Адрес электронной почты',
      'bn': 'ইমেইল ঠিকানা',
      'vi': 'Địa chỉ email',
      'th': 'ที่อยู่อีเมล',
      'pl': 'Adres e-mail',
      'nl': 'E-mailadres',
      'uk': 'Адреса електронної пошти',
    },
    'Goals': {
      'ar': 'الأهداف',
      'en': 'Goals',
      'fr': 'Objectifs',
      'es': 'Objetivos',
      'tr': 'Hedefler',
      'de': 'Ziele',
      'it': 'Obiettivi',
      'pt-BR': 'Metas',
      'pt-PT': 'Objetivos',
      'ur': 'اہداف',
      'fa': 'اهداف',
      'hi': 'लक्ष्य',
      'id': 'Sasaran',
      'ms': 'Matlamat',
      'ja': '目標',
      'ko': '목표',
      'zh-Hans': '目标',
      'zh-Hant': '目標',
      'ru': 'Цели',
      'bn': 'লক্ষ্যসমূহ',
      'vi': 'Mục tiêu',
      'th': 'เป้าหมาย',
      'pl': 'Cele',
      'nl': 'Doelen',
      'uk': 'Цілі',
    },
    'Update weight, nutrition, and fitness goals': {
      'ar': 'حدّث أهداف الوزن والتغذية واللياقة',
      'en': 'Update weight, nutrition, and fitness goals',
      'fr':
          'Mettre à jour les objectifs de poids, de nutrition et de forme physique',
      'es': 'Actualiza los objetivos de peso, nutrición y actividad física',
      'tr': 'Kilo, beslenme ve fitness hedeflerini güncelle',
      'de': 'Ziele für Gewicht, Ernährung und Fitness aktualisieren',
      'it': 'Aggiorna gli obiettivi di peso, alimentazione e forma fisica',
      'pt-BR': 'Atualize suas metas de peso, nutrição e condicionamento físico',
      'pt-PT': 'Atualize os objetivos de peso, nutrição e condição física',
      'ur': 'وزن، غذائیت اور فٹنس کے اہداف اپ ڈیٹ کریں',
      'fa': 'اهداف وزن، تغذیه و تناسب اندام را به‌روزرسانی کنید',
      'hi': 'वज़न, पोषण और फ़िटनेस के लक्ष्य अपडेट करें',
      'id': 'Perbarui target berat badan, nutrisi, dan kebugaran',
      'ms': 'Kemas kini matlamat berat badan, pemakanan dan kecergasan',
      'ja': '体重・栄養・フィットネスの目標を更新',
      'ko': '체중, 영양 및 피트니스 목표 업데이트',
      'zh-Hans': '更新体重、营养和健身目标',
      'zh-Hant': '更新體重、營養與健身目標',
      'ru': 'Обновите цели по весу, питанию и физической форме',
      'bn': 'ওজন, পুষ্টি ও ফিটনেসের লক্ষ্য হালনাগাদ করুন',
      'vi': 'Cập nhật mục tiêu cân nặng, dinh dưỡng và thể chất',
      'th': 'อัปเดตเป้าหมายน้ำหนัก โภชนาการ และการออกกำลังกาย',
      'pl': 'Zaktualizuj cele dotyczące masy ciała, odżywiania i sprawności',
      'nl': 'Werk doelen voor gewicht, voeding en fitness bij',
      'uk': 'Оновіть цілі щодо ваги, харчування та фізичної форми',
    },
    'Calories & macro plan': {
      'ar': 'خطة السعرات والماكروز',
      'en': 'Calories & macro plan',
      'fr': 'Plan calories et macronutriments',
      'es': 'Plan de calorías y macros',
      'tr': 'Kalori ve makro planı',
      'de': 'Kalorien- und Makroplan',
      'it': 'Piano calorie e macronutrienti',
      'pt-BR': 'Plano de calorias e macronutrientes',
      'pt-PT': 'Plano de calorias e macronutrientes',
      'ur': 'کیلوریز اور میکروز کا منصوبہ',
      'fa': 'برنامه کالری و درشت‌مغذی‌ها',
      'hi': 'कैलोरी और मैक्रो योजना',
      'id': 'Rencana kalori dan makro',
      'ms': 'Pelan kalori dan makro',
      'ja': 'カロリーとマクロ栄養素のプラン',
      'ko': '칼로리 및 매크로 계획',
      'zh-Hans': '热量与宏量营养素计划',
      'zh-Hant': '熱量與巨量營養素計畫',
      'ru': 'План калорий и макронутриентов',
      'bn': 'ক্যালোরি ও ম্যাক্রো পরিকল্পনা',
      'vi': 'Kế hoạch calo và chất dinh dưỡng đa lượng',
      'th': 'แผนแคลอรีและสารอาหารหลัก',
      'pl': 'Plan kalorii i makroskładników',
      'nl': 'Calorie- en macroplan',
      'uk': 'План калорій і макронутрієнтів',
    },
    'Plan details & recommendations': {
      'ar': 'تفاصيل الخطة والتوصيات',
      'en': 'Plan details & recommendations',
      'fr': 'Détails et recommandations du plan',
      'es': 'Detalles y recomendaciones del plan',
      'tr': 'Plan ayrıntıları ve öneriler',
      'de': 'Plandetails und Empfehlungen',
      'it': 'Dettagli e consigli del piano',
      'pt-BR': 'Detalhes e recomendações do plano',
      'pt-PT': 'Detalhes e recomendações do plano',
      'ur': 'منصوبے کی تفصیلات اور سفارشات',
      'fa': 'جزئیات و توصیه‌های برنامه',
      'hi': 'योजना का विवरण और सुझाव',
      'id': 'Detail dan rekomendasi rencana',
      'ms': 'Butiran dan cadangan pelan',
      'ja': 'プランの詳細とおすすめ',
      'ko': '계획 세부 정보 및 권장 사항',
      'zh-Hans': '计划详情与建议',
      'zh-Hant': '計畫詳情與建議',
      'ru': 'Подробности плана и рекомендации',
      'bn': 'পরিকল্পনার বিস্তারিত ও পরামর্শ',
      'vi': 'Chi tiết và đề xuất của kế hoạch',
      'th': 'รายละเอียดแผนและคำแนะนำ',
      'pl': 'Szczegóły planu i zalecenia',
      'nl': 'Plandetails en aanbevelingen',
      'uk': 'Деталі плану та рекомендації',
    },
    'Dietary system': {
      'ar': 'النظام الغذائي',
      'en': 'Dietary system',
      'fr': 'Système alimentaire',
      'es': 'Sistema alimentario',
      'tr': 'Beslenme sistemi',
      'de': 'Ernährungssystem',
      'it': 'Sistema alimentare',
      'pt-BR': 'Sistema alimentar',
      'pt-PT': 'Sistema alimentar',
      'ur': 'غذائی نظام',
      'fa': 'نظام غذایی',
      'hi': 'आहार प्रणाली',
      'id': 'Sistem pola makan',
      'ms': 'Sistem pemakanan',
      'ja': '食事管理',
      'ko': '식단 시스템',
      'zh-Hans': '饮食体系',
      'zh-Hant': '飲食體系',
      'ru': 'Система питания',
      'bn': 'খাদ্যব্যবস্থা',
      'vi': 'Chế độ dinh dưỡng',
      'th': 'ระบบการรับประทานอาหาร',
      'pl': 'System żywieniowy',
      'nl': 'Voedingssysteem',
      'uk': 'Система харчування',
    },
    'Estimated time to goal': {
      'ar': 'الوقت التقديري للوصول إلى الهدف',
      'en': 'Estimated time to goal',
      'fr': 'Durée estimée pour atteindre l’objectif',
      'es': 'Tiempo estimado para alcanzar el objetivo',
      'tr': 'Hedefe ulaşmak için tahmini süre',
      'de': 'Geschätzte Zeit bis zum Ziel',
      'it': 'Tempo stimato per raggiungere l’obiettivo',
      'pt-BR': 'Tempo estimado até a meta',
      'pt-PT': 'Tempo estimado até ao objetivo',
      'ur': 'ہدف تک پہنچنے کا تخمینی وقت',
      'fa': 'زمان تخمینی تا رسیدن به هدف',
      'hi': 'लक्ष्य तक पहुँचने का अनुमानित समय',
      'id': 'Perkiraan waktu untuk mencapai target',
      'ms': 'Anggaran masa untuk mencapai matlamat',
      'ja': '目標達成までの推定期間',
      'ko': '목표 달성까지 예상 시간',
      'zh-Hans': '达成目标的预计时间',
      'zh-Hant': '達成目標的預估時間',
      'ru': 'Расчётное время до достижения цели',
      'bn': 'লক্ষ্য অর্জনের আনুমানিক সময়',
      'vi': 'Thời gian dự kiến để đạt mục tiêu',
      'th': 'ระยะเวลาโดยประมาณที่จะถึงเป้าหมาย',
      'pl': 'Szacowany czas do osiągnięcia celu',
      'nl': 'Geschatte tijd tot het doel',
      'uk': 'Орієнтовний час до досягнення цілі',
    },
    'Goal timeline': {
      'ar': 'الجدول الزمني للهدف',
      'en': 'Goal timeline',
      'fr': 'Calendrier de l’objectif',
      'es': 'Cronograma del objetivo',
      'tr': 'Hedef zaman çizelgesi',
      'de': 'Zeitplan zum Ziel',
      'it': 'Tempistica dell’obiettivo',
      'pt-BR': 'Cronograma da meta',
      'pt-PT': 'Cronograma do objetivo',
      'ur': 'ہدف کی مدت',
      'fa': 'جدول زمانی هدف',
      'hi': 'लक्ष्य की समयरेखा',
      'id': 'Linimasa target',
      'ms': 'Garis masa matlamat',
      'ja': '目標達成スケジュール',
      'ko': '목표 일정',
      'zh-Hans': '目标时间表',
      'zh-Hant': '目標時間表',
      'ru': 'Срок достижения цели',
      'bn': 'লক্ষ্য অর্জনের সময়রেখা',
      'vi': 'Tiến trình mục tiêu',
      'th': 'กรอบเวลาสู่เป้าหมาย',
      'pl': 'Harmonogram celu',
      'nl': 'Tijdlijn naar je doel',
      'uk': 'Термін досягнення цілі',
    },
    'Already at goal': {
      'ar': 'أنت عند الهدف بالفعل',
      'en': 'Already at goal',
      'fr': 'Objectif déjà atteint',
      'es': 'Ya estás en el objetivo',
      'tr': 'Hedefe zaten ulaştın',
      'de': 'Ziel bereits erreicht',
      'it': 'Obiettivo già raggiunto',
      'pt-BR': 'Meta já alcançada',
      'pt-PT': 'Objetivo já alcançado',
      'ur': 'ہدف پہلے ہی حاصل ہے',
      'fa': 'هم‌اکنون به هدف رسیده‌اید',
      'hi': 'लक्ष्य पहले ही हासिल है',
      'id': 'Target sudah tercapai',
      'ms': 'Matlamat sudah dicapai',
      'ja': 'すでに目標を達成しています',
      'ko': '이미 목표를 달성했습니다',
      'zh-Hans': '已达到目标',
      'zh-Hant': '已達成目標',
      'ru': 'Цель уже достигнута',
      'bn': 'লক্ষ্য ইতিমধ্যে অর্জিত',
      'vi': 'Đã đạt mục tiêu',
      'th': 'ถึงเป้าหมายแล้ว',
      'pl': 'Cel został już osiągnięty',
      'nl': 'Doel al bereikt',
      'uk': 'Цілі вже досягнуто',
    },
    'Maintenance plan · no countdown': {
      'ar': 'خطة تثبيت · بلا عدّ تنازلي',
      'en': 'Maintenance plan · no countdown',
      'fr': 'Plan de maintien · aucun compte à rebours',
      'es': 'Plan de mantenimiento · sin cuenta atrás',
      'tr': 'Koruma planı · geri sayım yok',
      'de': 'Gewicht halten · kein Countdown',
      'it': 'Piano di mantenimento · nessun conto alla rovescia',
      'pt-BR': 'Plano de manutenção · sem contagem regressiva',
      'pt-PT': 'Plano de manutenção · sem contagem decrescente',
      'ur': 'وزن برقرار رکھنے کا منصوبہ · کوئی الٹی گنتی نہیں',
      'fa': 'برنامه تثبیت · بدون شمارش معکوس',
      'hi': 'वज़न बनाए रखने की योजना · कोई उलटी गिनती नहीं',
      'id': 'Rencana mempertahankan berat · tanpa hitung mundur',
      'ms': 'Pelan mengekalkan berat · tiada kira detik',
      'ja': '維持プラン · カウントダウンなし',
      'ko': '유지 계획 · 카운트다운 없음',
      'zh-Hans': '维持计划 · 无倒计时',
      'zh-Hant': '維持計畫 · 無倒數',
      'ru': 'План поддержания · без обратного отсчёта',
      'bn': 'ওজন ধরে রাখার পরিকল্পনা · কোনো কাউন্টডাউন নেই',
      'vi': 'Kế hoạch duy trì · không đếm ngược',
      'th': 'แผนรักษาน้ำหนัก · ไม่มีการนับถอยหลัง',
      'pl': 'Plan utrzymania · bez odliczania',
      'nl': 'Onderhoudsplan · geen aftelling',
      'uk': 'План підтримання · без зворотного відліку',
    },
    'Current weight is within the goal range. This is an estimate, not a guarantee.': {
      'ar': 'الوزن الحالي ضمن نطاق الهدف. هذا تقدير وليس ضمانًا.',
      'en':
          'Current weight is within the goal range. This is an estimate, not a guarantee.',
      'fr':
          'Le poids actuel se situe dans la plage cible. Il s’agit d’une estimation, sans garantie.',
      'es':
          'El peso actual está dentro del rango objetivo. Es una estimación, no una garantía.',
      'tr': 'Mevcut kilo hedef aralığında. Bu bir tahmindir, garanti değildir.',
      'de':
          'Das aktuelle Gewicht liegt im Zielbereich. Dies ist eine Schätzung, keine Garantie.',
      'it':
          'Il peso attuale rientra nell’intervallo obiettivo. È una stima, non una garanzia.',
      'pt-BR':
          'O peso atual está dentro da faixa da meta. Esta é uma estimativa, não uma garantia.',
      'pt-PT':
          'O peso atual está dentro do intervalo do objetivo. É uma estimativa, não uma garantia.',
      'ur': 'موجودہ وزن ہدف کی حد میں ہے۔ یہ ایک تخمینہ ہے، ضمانت نہیں۔',
      'fa': 'وزن فعلی در محدوده هدف است. این فقط یک برآورد است، نه تضمین.',
      'hi': 'मौजूदा वज़न लक्ष्य की सीमा में है। यह एक अनुमान है, गारंटी नहीं।',
      'id':
          'Berat saat ini berada dalam rentang target. Ini perkiraan, bukan jaminan.',
      'ms':
          'Berat semasa berada dalam julat matlamat. Ini anggaran, bukan jaminan.',
      'ja': '現在の体重は目標範囲内です。これは推定値であり、保証ではありません。',
      'ko': '현재 체중이 목표 범위 안에 있습니다. 이는 예상치이며 보장되지 않습니다.',
      'zh-Hans': '当前体重在目标范围内。这只是估算，并非保证。',
      'zh-Hant': '目前體重在目標範圍內。這只是估算，並非保證。',
      'ru':
          'Текущий вес находится в целевом диапазоне. Это оценка, а не гарантия.',
      'bn':
          'বর্তমান ওজন লক্ষ্যসীমার মধ্যে আছে। এটি একটি আনুমানিক হিসাব, নিশ্চয়তা নয়।',
      'vi':
          'Cân nặng hiện tại nằm trong phạm vi mục tiêu. Đây là ước tính, không phải cam kết.',
      'th':
          'น้ำหนักปัจจุบันอยู่ในช่วงเป้าหมาย นี่เป็นเพียงค่าประมาณ ไม่ใช่การรับประกัน',
      'pl':
          'Obecna masa ciała mieści się w zakresie celu. To szacunek, nie gwarancja.',
      'nl':
          'Je huidige gewicht ligt binnen het doelbereik. Dit is een schatting, geen garantie.',
      'uk':
          'Поточна вага перебуває в цільовому діапазоні. Це оцінка, а не гарантія.',
    },
    'Maintenance has no completion date. This is an estimate, not a guarantee.': {
      'ar': 'التثبيت ليس له تاريخ اكتمال. هذا تقدير وليس ضمانًا.',
      'en':
          'Maintenance has no completion date. This is an estimate, not a guarantee.',
      'fr':
          'Le maintien n’a pas de date de fin. Il s’agit d’une estimation, sans garantie.',
      'es':
          'El mantenimiento no tiene fecha de finalización. Es una estimación, no una garantía.',
      'tr':
          'Korumanın tamamlanma tarihi yoktur. Bu bir tahmindir, garanti değildir.',
      'de':
          'Für die Gewichtserhaltung gibt es kein Abschlussdatum. Dies ist eine Schätzung, keine Garantie.',
      'it':
          'Il mantenimento non ha una data di completamento. È una stima, non una garanzia.',
      'pt-BR':
          'A manutenção não tem data de conclusão. Esta é uma estimativa, não uma garantia.',
      'pt-PT':
          'A manutenção não tem data de conclusão. É uma estimativa, não uma garantia.',
      'ur':
          'وزن برقرار رکھنے کی کوئی تکمیل کی تاریخ نہیں۔ یہ ایک تخمینہ ہے، ضمانت نہیں۔',
      'fa': 'تثبیت تاریخ پایان ندارد. این فقط یک برآورد است، نه تضمین.',
      'hi':
          'वज़न बनाए रखने की कोई पूरी होने की तारीख नहीं है। यह एक अनुमान है, गारंटी नहीं।',
      'id':
          'Mempertahankan berat tidak memiliki tanggal selesai. Ini perkiraan, bukan jaminan.',
      'ms':
          'Mengekalkan berat tiada tarikh selesai. Ini anggaran, bukan jaminan.',
      'ja': '維持プランに完了日はありません。これは推定であり、保証ではありません。',
      'ko': '유지 계획에는 완료일이 없습니다. 이는 예상치이며 보장되지 않습니다.',
      'zh-Hans': '维持计划没有完成日期。这只是估算，并非保证。',
      'zh-Hant': '維持計畫沒有完成日期。這只是估算，並非保證。',
      'ru':
          'У поддержания веса нет даты завершения. Это оценка, а не гарантия.',
      'bn':
          'ওজন ধরে রাখার কোনো সমাপ্তির তারিখ নেই। এটি একটি আনুমানিক হিসাব, নিশ্চয়তা নয়।',
      'vi':
          'Duy trì cân nặng không có ngày hoàn thành. Đây là ước tính, không phải cam kết.',
      'th':
          'การรักษาน้ำหนักไม่มีวันที่เสร็จสิ้น นี่เป็นเพียงค่าประมาณ ไม่ใช่การรับประกัน',
      'pl':
          'Utrzymanie masy ciała nie ma daty zakończenia. To szacunek, nie gwarancja.',
      'nl':
          'Gewichtsbehoud heeft geen einddatum. Dit is een schatting, geen garantie.',
      'uk':
          'Підтримання ваги не має дати завершення. Це оцінка, а не гарантія.',
    },
    'loss': {
      'ar': 'نزول',
      'en': 'loss',
      'fr': 'perte',
      'es': 'pérdida',
      'tr': 'kayıp',
      'de': 'Abnahme',
      'it': 'perdita',
      'pt-BR': 'perda',
      'pt-PT': 'perda',
      'ur': 'کمی',
      'fa': 'کاهش',
      'hi': 'कमी',
      'id': 'penurunan',
      'ms': 'penurunan',
      'ja': '減量',
      'ko': '감량',
      'zh-Hans': '减重',
      'zh-Hant': '減重',
      'ru': 'снижение',
      'bn': 'হ্রাস',
      'vi': 'giảm cân',
      'th': 'การลดน้ำหนัก',
      'pl': 'spadku',
      'nl': 'gewichtsverlies',
      'uk': 'зниження',
    },
    'gain': {
      'ar': 'زيادة',
      'en': 'gain',
      'fr': 'prise',
      'es': 'aumento',
      'tr': 'artış',
      'de': 'Zunahme',
      'it': 'aumento',
      'pt-BR': 'ganho',
      'pt-PT': 'aumento',
      'ur': 'اضافہ',
      'fa': 'افزایش',
      'hi': 'बढ़ोतरी',
      'id': 'kenaikan',
      'ms': 'peningkatan',
      'ja': '増量',
      'ko': '증량',
      'zh-Hans': '增重',
      'zh-Hant': '增重',
      'ru': 'набор',
      'bn': 'বৃদ্ধি',
      'vi': 'tăng cân',
      'th': 'การเพิ่มน้ำหนัก',
      'pl': 'wzrostu',
      'nl': 'gewichtstoename',
      'uk': 'збільшення',
    },
    'Personal details': {
      'ar': 'البيانات الشخصية',
      'en': 'Personal details',
      'fr': 'Informations personnelles',
      'es': 'Datos personales',
      'tr': 'Kişisel bilgiler',
      'de': 'Persönliche Angaben',
      'it': 'Dati personali',
      'pt-BR': 'Dados pessoais',
      'pt-PT': 'Dados pessoais',
      'ur': 'ذاتی تفصیلات',
      'fa': 'اطلاعات شخصی',
      'hi': 'व्यक्तिगत विवरण',
      'id': 'Detail pribadi',
      'ms': 'Butiran peribadi',
      'ja': '個人情報',
      'ko': '개인 정보',
      'zh-Hans': '个人信息',
      'zh-Hant': '個人資料',
      'ru': 'Личные данные',
      'bn': 'ব্যক্তিগত তথ্য',
      'vi': 'Thông tin cá nhân',
      'th': 'ข้อมูลส่วนตัว',
      'pl': 'Dane osobowe',
      'nl': 'Persoonlijke gegevens',
      'uk': 'Особисті дані',
    },
    'Change photo': {
      'ar': 'تغيير الصورة',
      'en': 'Change photo',
      'fr': 'Modifier la photo',
      'es': 'Cambiar foto',
      'tr': 'Fotoğrafı değiştir',
      'de': 'Foto ändern',
      'it': 'Cambia foto',
      'pt-BR': 'Alterar foto',
      'pt-PT': 'Alterar foto',
      'ur': 'تصویر تبدیل کریں',
      'fa': 'تغییر عکس',
      'hi': 'फ़ोटो बदलें',
      'id': 'Ubah foto',
      'ms': 'Tukar foto',
      'ja': '写真を変更',
      'ko': '사진 변경',
      'zh-Hans': '更换照片',
      'zh-Hant': '變更照片',
      'ru': 'Изменить фото',
      'bn': 'ছবি পরিবর্তন করুন',
      'vi': 'Đổi ảnh',
      'th': 'เปลี่ยนรูปภาพ',
      'pl': 'Zmień zdjęcie',
      'nl': 'Foto wijzigen',
      'uk': 'Змінити фото',
    },
    'Not added': {
      'ar': 'غير مضاف',
      'en': 'Not added',
      'fr': 'Non ajouté',
      'es': 'No añadido',
      'tr': 'Eklenmedi',
      'de': 'Nicht hinzugefügt',
      'it': 'Non aggiunto',
      'pt-BR': 'Não adicionado',
      'pt-PT': 'Não adicionado',
      'ur': 'شامل نہیں کیا گیا',
      'fa': 'اضافه نشده',
      'hi': 'जोड़ा नहीं गया',
      'id': 'Belum ditambahkan',
      'ms': 'Belum ditambah',
      'ja': '未追加',
      'ko': '추가되지 않음',
      'zh-Hans': '未添加',
      'zh-Hant': '尚未新增',
      'ru': 'Не добавлено',
      'bn': 'যোগ করা হয়নি',
      'vi': 'Chưa thêm',
      'th': 'ยังไม่ได้เพิ่ม',
      'pl': 'Nie dodano',
      'nl': 'Niet toegevoegd',
      'uk': 'Не додано',
    },
    'Body details': {
      'ar': 'بيانات الجسم',
      'en': 'Body details',
      'fr': 'Données corporelles',
      'es': 'Datos corporales',
      'tr': 'Vücut bilgileri',
      'de': 'Körperdaten',
      'it': 'Dati corporei',
      'pt-BR': 'Dados corporais',
      'pt-PT': 'Dados corporais',
      'ur': 'جسمانی تفصیلات',
      'fa': 'اطلاعات بدن',
      'hi': 'शरीर का विवरण',
      'id': 'Detail tubuh',
      'ms': 'Butiran badan',
      'ja': '身体情報',
      'ko': '신체 정보',
      'zh-Hans': '身体信息',
      'zh-Hant': '身體資料',
      'ru': 'Данные тела',
      'bn': 'শরীরের তথ্য',
      'vi': 'Thông tin cơ thể',
      'th': 'ข้อมูลร่างกาย',
      'pl': 'Dane ciała',
      'nl': 'Lichaamsgegevens',
      'uk': 'Дані тіла',
    },
    'Sex': {
      'ar': 'الجنس',
      'en': 'Sex',
      'fr': 'Sexe',
      'es': 'Sexo',
      'tr': 'Cinsiyet',
      'de': 'Geschlecht',
      'it': 'Sesso',
      'pt-BR': 'Sexo',
      'pt-PT': 'Sexo',
      'ur': 'جنس',
      'fa': 'جنسیت',
      'hi': 'लिंग',
      'id': 'Jenis kelamin',
      'ms': 'Jantina',
      'ja': '性別',
      'ko': '성별',
      'zh-Hans': '性别',
      'zh-Hant': '性別',
      'ru': 'Пол',
      'bn': 'লিঙ্গ',
      'vi': 'Giới tính',
      'th': 'เพศ',
      'pl': 'Płeć',
      'nl': 'Geslacht',
      'uk': 'Стать',
    },
    'Location & preferences': {
      'ar': 'الموقع والتفضيلات',
      'en': 'Location & preferences',
      'fr': 'Lieu et préférences',
      'es': 'Ubicación y preferencias',
      'tr': 'Konum ve tercihler',
      'de': 'Standort und Einstellungen',
      'it': 'Posizione e preferenze',
      'pt-BR': 'Localização e preferências',
      'pt-PT': 'Localização e preferências',
      'ur': 'مقام اور ترجیحات',
      'fa': 'مکان و ترجیحات',
      'hi': 'स्थान और प्राथमिकताएँ',
      'id': 'Lokasi & preferensi',
      'ms': 'Lokasi & pilihan',
      'ja': '場所と設定',
      'ko': '위치 및 환경설정',
      'zh-Hans': '位置与偏好',
      'zh-Hant': '位置與偏好設定',
      'ru': 'Местоположение и предпочтения',
      'bn': 'অবস্থান ও পছন্দসমূহ',
      'vi': 'Vị trí & tùy chọn',
      'th': 'ตำแหน่งและการตั้งค่า',
      'pl': 'Lokalizacja i preferencje',
      'nl': 'Locatie en voorkeuren',
      'uk': 'Місцезнаходження та налаштування',
    },
    'Location': {
      'ar': 'الموقع',
      'en': 'Location',
      'fr': 'Lieu',
      'es': 'Ubicación',
      'tr': 'Konum',
      'de': 'Standort',
      'it': 'Posizione',
      'pt-BR': 'Localização',
      'pt-PT': 'Localização',
      'ur': 'مقام',
      'fa': 'مکان',
      'hi': 'स्थान',
      'id': 'Lokasi',
      'ms': 'Lokasi',
      'ja': '場所',
      'ko': '위치',
      'zh-Hans': '位置',
      'zh-Hant': '位置',
      'ru': 'Местоположение',
      'bn': 'অবস্থান',
      'vi': 'Vị trí',
      'th': 'ตำแหน่ง',
      'pl': 'Lokalizacja',
      'nl': 'Locatie',
      'uk': 'Місцезнаходження',
    },
    'Postal code': {
      'ar': 'الرمز البريدي',
      'en': 'Postal code',
      'fr': 'Code postal',
      'es': 'Código postal',
      'tr': 'Posta kodu',
      'de': 'Postleitzahl',
      'it': 'Codice postale',
      'pt-BR': 'CEP',
      'pt-PT': 'Código postal',
      'ur': 'پوسٹل کوڈ',
      'fa': 'کد پستی',
      'hi': 'पिन कोड',
      'id': 'Kode pos',
      'ms': 'Poskod',
      'ja': '郵便番号',
      'ko': '우편번호',
      'zh-Hans': '邮政编码',
      'zh-Hant': '郵遞區號',
      'ru': 'Почтовый индекс',
      'bn': 'পোস্টাল কোড',
      'vi': 'Mã bưu chính',
      'th': 'รหัสไปรษณีย์',
      'pl': 'Kod pocztowy',
      'nl': 'Postcode',
      'uk': 'Поштовий індекс',
    },
    'Time zone': {
      'ar': 'المنطقة الزمنية',
      'en': 'Time zone',
      'fr': 'Fuseau horaire',
      'es': 'Zona horaria',
      'tr': 'Saat dilimi',
      'de': 'Zeitzone',
      'it': 'Fuso orario',
      'pt-BR': 'Fuso horário',
      'pt-PT': 'Fuso horário',
      'ur': 'ٹائم زون',
      'fa': 'منطقه زمانی',
      'hi': 'समय क्षेत्र',
      'id': 'Zona waktu',
      'ms': 'Zon waktu',
      'ja': 'タイムゾーン',
      'ko': '시간대',
      'zh-Hans': '时区',
      'zh-Hant': '時區',
      'ru': 'Часовой пояс',
      'bn': 'সময় অঞ্চল',
      'vi': 'Múi giờ',
      'th': 'เขตเวลา',
      'pl': 'Strefa czasowa',
      'nl': 'Tijdzone',
      'uk': 'Часовий пояс',
    },
    'Metric · kg, cm, ml': {
      'ar': 'متري · كغ، سم، مل',
      'en': 'Metric · kg, cm, ml',
      'fr': 'Métrique · kg, cm, ml',
      'es': 'Métrico · kg, cm, ml',
      'tr': 'Metrik · kg, cm, ml',
      'de': 'Metrisch · kg, cm, ml',
      'it': 'Metrico · kg, cm, ml',
      'pt-BR': 'Métrico · kg, cm, ml',
      'pt-PT': 'Métrico · kg, cm, ml',
      'ur': 'میٹرک · کلوگرام، سینٹی میٹر، ملی لیٹر',
      'fa': 'متریک · کیلوگرم، سانتی‌متر، میلی‌لیتر',
      'hi': 'मीट्रिक · किग्रा, सेमी, मिली',
      'id': 'Metrik · kg, cm, ml',
      'ms': 'Metrik · kg, cm, ml',
      'ja': 'メートル法 · kg、cm、ml',
      'ko': '미터법 · kg, cm, ml',
      'zh-Hans': '公制 · 千克、厘米、毫升',
      'zh-Hant': '公制 · 公斤、公分、毫升',
      'ru': 'Метрическая · кг, см, мл',
      'bn': 'মেট্রিক · কেজি, সেমি, মিলি',
      'vi': 'Hệ mét · kg, cm, ml',
      'th': 'เมตริก · กก., ซม., มล.',
      'pl': 'Metryczny · kg, cm, ml',
      'nl': 'Metrisch · kg, cm, ml',
      'uk': 'Метрична · кг, см, мл',
    },
    'Imperial · lb, ft': {
      'ar': 'إمبراطوري · رطل، قدم',
      'en': 'Imperial · lb, ft',
      'fr': 'Impérial · lb, ft',
      'es': 'Sistema imperial · lb, ft',
      'tr': 'İngiliz · lb, ft',
      'de': 'Angloamerikanisch · lb, ft',
      'it': 'Imperiale · lb, ft',
      'pt-BR': 'Sistema imperial · lb, ft',
      'pt-PT': 'Sistema imperial · lb, ft',
      'ur': 'امپیریل · پاؤنڈ، فٹ',
      'fa': 'امپریال · پوند، فوت',
      'hi': 'इम्पीरियल · पौंड, फ़ुट',
      'id': 'Satuan imperial · lb, ft',
      'ms': 'Imperial · lb, kaki',
      'ja': 'ヤード・ポンド法 · lb、ft',
      'ko': '야드파운드법 · lb, ft',
      'zh-Hans': '英制 · 磅、英尺',
      'zh-Hant': '英制 · 磅、英尺',
      'ru': 'Имперская · фунты, футы',
      'bn': 'ইম্পেরিয়াল · পাউন্ড, ফুট',
      'vi': 'Hệ Anh · lb, ft',
      'th': 'อิมพีเรียล · ปอนด์, ฟุต',
      'pl': 'Imperialny · lb, ft',
      'nl': 'Imperiaal · lb, ft',
      'uk': 'Імперська · фунти, фути',
    },
    'Loading…': {
      'ar': 'جارٍ التحميل…',
      'en': 'Loading…',
      'fr': 'Chargement…',
      'es': 'Cargando…',
      'tr': 'Yükleniyor…',
      'de': 'Wird geladen…',
      'it': 'Caricamento…',
      'pt-BR': 'Carregando…',
      'pt-PT': 'A carregar…',
      'ur': 'لوڈ ہو رہا ہے…',
      'fa': 'در حال بارگذاری…',
      'hi': 'लोड हो रहा है…',
      'id': 'Memuat…',
      'ms': 'Memuatkan…',
      'ja': '読み込み中…',
      'ko': '불러오는 중…',
      'zh-Hans': '加载中…',
      'zh-Hant': '載入中…',
      'ru': 'Загрузка…',
      'bn': 'লোড হচ্ছে…',
      'vi': 'Đang tải…',
      'th': 'กำลังโหลด…',
      'pl': 'Wczytywanie…',
      'nl': 'Laden…',
      'uk': 'Завантаження…',
    },
    'Health goals': {
      'ar': 'الأهداف الصحية',
      'en': 'Health goals',
      'fr': 'Objectifs de santé',
      'es': 'Objetivos de salud',
      'tr': 'Sağlık hedefleri',
      'de': 'Gesundheitsziele',
      'it': 'Obiettivi di salute',
      'pt-BR': 'Metas de saúde',
      'pt-PT': 'Objetivos de saúde',
      'ur': 'صحت کے اہداف',
      'fa': 'اهداف سلامت',
      'hi': 'स्वास्थ्य लक्ष्य',
      'id': 'Sasaran kesehatan',
      'ms': 'Matlamat kesihatan',
      'ja': '健康目標',
      'ko': '건강 목표',
      'zh-Hans': '健康目标',
      'zh-Hant': '健康目標',
      'ru': 'Цели здоровья',
      'bn': 'স্বাস্থ্য লক্ষ্য',
      'vi': 'Mục tiêu sức khỏe',
      'th': 'เป้าหมายสุขภาพ',
      'pl': 'Cele zdrowotne',
      'nl': 'Gezondheidsdoelen',
      'uk': 'Цілі здоров’я',
    },
    'Current weight': {
      'ar': 'الوزن الحالي',
      'en': 'Current weight',
      'fr': 'Poids actuel',
      'es': 'Peso actual',
      'tr': 'Mevcut kilo',
      'de': 'Aktuelles Gewicht',
      'it': 'Peso attuale',
      'pt-BR': 'Peso atual',
      'pt-PT': 'Peso atual',
      'ur': 'موجودہ وزن',
      'fa': 'وزن فعلی',
      'hi': 'वर्तमान वज़न',
      'id': 'Berat badan saat ini',
      'ms': 'Berat semasa',
      'ja': '現在の体重',
      'ko': '현재 체중',
      'zh-Hans': '当前体重',
      'zh-Hant': '目前體重',
      'ru': 'Текущий вес',
      'bn': 'বর্তমান ওজন',
      'vi': 'Cân nặng hiện tại',
      'th': 'น้ำหนักปัจจุบัน',
      'pl': 'Aktualna masa ciała',
      'nl': 'Huidig gewicht',
      'uk': 'Поточна вага',
    },
    'Goal weight': {
      'ar': 'الوزن المستهدف',
      'en': 'Goal weight',
      'fr': 'Poids cible',
      'es': 'Peso objetivo',
      'tr': 'Hedef kilo',
      'de': 'Zielgewicht',
      'it': 'Peso obiettivo',
      'pt-BR': 'Peso-alvo',
      'pt-PT': 'Peso-alvo',
      'ur': 'ہدف وزن',
      'fa': 'وزن هدف',
      'hi': 'लक्ष्य वज़न',
      'id': 'Berat badan target',
      'ms': 'Berat sasaran',
      'ja': '目標体重',
      'ko': '목표 체중',
      'zh-Hans': '目标体重',
      'zh-Hant': '目標體重',
      'ru': 'Целевой вес',
      'bn': 'লক্ষ্য ওজন',
      'vi': 'Cân nặng mục tiêu',
      'th': 'น้ำหนักเป้าหมาย',
      'pl': 'Docelowa masa ciała',
      'nl': 'Streefgewicht',
      'uk': 'Цільова вага',
    },
    'Sedentary': {
      'ar': 'حركة محدودة',
      'en': 'Sedentary',
      'fr': 'Sédentaire',
      'es': 'Sedentario',
      'tr': 'Hareketsiz',
      'de': 'Sitzend',
      'it': 'Sedentario',
      'pt-BR': 'Sedentário',
      'pt-PT': 'Sedentário',
      'ur': 'غیر فعال',
      'fa': 'کم‌تحرک',
      'hi': 'निष्क्रिय',
      'id': 'Sedenter',
      'ms': 'Tidak aktif',
      'ja': '座りがち',
      'ko': '좌식 생활',
      'zh-Hans': '久坐少动',
      'zh-Hant': '久坐少動',
      'ru': 'Малоподвижный',
      'bn': 'নিষ্ক্রিয়',
      'vi': 'Ít vận động',
      'th': 'ไม่ค่อยเคลื่อนไหว',
      'pl': 'Siedzący tryb życia',
      'nl': 'Zittend',
      'uk': 'Малорухливий',
    },
    'Lightly active': {
      'ar': 'نشاط خفيف',
      'en': 'Lightly active',
      'fr': 'Légèrement actif',
      'es': 'Actividad ligera',
      'tr': 'Hafif aktif',
      'de': 'Leicht aktiv',
      'it': 'Leggermente attivo',
      'pt-BR': 'Ligeiramente ativo',
      'pt-PT': 'Ligeiramente ativo',
      'ur': 'ہلکی سرگرمی',
      'fa': 'کمی فعال',
      'hi': 'हल्का सक्रिय',
      'id': 'Sedikit aktif',
      'ms': 'Aktif ringan',
      'ja': '軽い活動',
      'ko': '가벼운 활동',
      'zh-Hans': '轻度活动',
      'zh-Hant': '輕度活動',
      'ru': 'Низкая активность',
      'bn': 'হালকা সক্রিয়',
      'vi': 'Hoạt động nhẹ',
      'th': 'ออกกำลังกายเล็กน้อย',
      'pl': 'Lekko aktywny',
      'nl': 'Licht actief',
      'uk': 'Легка активність',
    },
    'Moderately active': {
      'ar': 'نشاط متوسط',
      'en': 'Moderately active',
      'fr': 'Modérément actif',
      'es': 'Actividad moderada',
      'tr': 'Orta aktif',
      'de': 'Mäßig aktiv',
      'it': 'Moderatamente attivo',
      'pt-BR': 'Moderadamente ativo',
      'pt-PT': 'Moderadamente ativo',
      'ur': 'معتدل سرگرمی',
      'fa': 'فعالیت متوسط',
      'hi': 'मध्यम सक्रिय',
      'id': 'Cukup aktif',
      'ms': 'Aktif sederhana',
      'ja': '中程度の活動',
      'ko': '보통 활동',
      'zh-Hans': '中度活动',
      'zh-Hant': '中度活動',
      'ru': 'Умеренная активность',
      'bn': 'মাঝারি সক্রিয়',
      'vi': 'Hoạt động vừa',
      'th': 'ออกกำลังกายปานกลาง',
      'pl': 'Umiarkowanie aktywny',
      'nl': 'Gemiddeld actief',
      'uk': 'Помірна активність',
    },
    'Very active': {
      'ar': 'نشاط مكثف',
      'en': 'Very active',
      'fr': 'Très actif',
      'es': 'Muy activo',
      'tr': 'Çok aktif',
      'de': 'Sehr aktiv',
      'it': 'Molto attivo',
      'pt-BR': 'Muito ativo',
      'pt-PT': 'Muito ativo',
      'ur': 'بہت زیادہ سرگرم',
      'fa': 'بسیار فعال',
      'hi': 'बहुत सक्रिय',
      'id': 'Sangat aktif',
      'ms': 'Sangat aktif',
      'ja': '非常に活発',
      'ko': '매우 활동적',
      'zh-Hans': '高度活跃',
      'zh-Hant': '高度活躍',
      'ru': 'Очень высокая активность',
      'bn': 'খুব সক্রিয়',
      'vi': 'Hoạt động nhiều',
      'th': 'ออกกำลังกายมาก',
      'pl': 'Bardzo aktywny',
      'nl': 'Zeer actief',
      'uk': 'Дуже активний',
    },
    'Save health profile': {
      'ar': 'حفظ الملف الصحي',
      'en': 'Save health profile',
      'fr': 'Enregistrer le profil santé',
      'es': 'Guardar perfil de salud',
      'tr': 'Sağlık profilini kaydet',
      'de': 'Gesundheitsprofil speichern',
      'it': 'Salva profilo salute',
      'pt-BR': 'Salvar perfil de saúde',
      'pt-PT': 'Guardar perfil de saúde',
      'ur': 'صحت کا پروفائل محفوظ کریں',
      'fa': 'ذخیره نمایه سلامت',
      'hi': 'स्वास्थ्य प्रोफ़ाइल सेव करें',
      'id': 'Simpan profil kesehatan',
      'ms': 'Simpan profil kesihatan',
      'ja': '健康プロフィールを保存',
      'ko': '건강 프로필 저장',
      'zh-Hans': '保存健康档案',
      'zh-Hant': '儲存健康檔案',
      'ru': 'Сохранить профиль здоровья',
      'bn': 'স্বাস্থ্য প্রোফাইল সংরক্ষণ করুন',
      'vi': 'Lưu hồ sơ sức khỏe',
      'th': 'บันทึกโปรไฟล์สุขภาพ',
      'pl': 'Zapisz profil zdrowotny',
      'nl': 'Gezondheidsprofiel opslaan',
      'uk': 'Зберегти профіль здоров’я',
    },
    'Omnivore': {
      'ar': 'نظام متنوع',
      'en': 'Omnivore',
      'fr': 'Omnivore',
      'es': 'Omnívoro',
      'tr': 'Hepçil',
      'de': 'Allesesser',
      'it': 'Onnivoro',
      'pt-BR': 'Onívoro',
      'pt-PT': 'Omnívoro',
      'ur': 'ہمہ خور',
      'fa': 'همه‌چیزخوار',
      'hi': 'सर्वाहारी',
      'id': 'Omnivora',
      'ms': 'Omnivor',
      'ja': '雑食',
      'ko': '잡식',
      'zh-Hans': '杂食',
      'zh-Hant': '雜食',
      'ru': 'Всеядный',
      'bn': 'সর্বভুক',
      'vi': 'Ăn tạp',
      'th': 'กินได้ทุกประเภท',
      'pl': 'Wszystkożerny',
      'nl': 'Alleseter',
      'uk': 'Всеїдний',
    },
    'Pescatarian': {
      'ar': 'نباتي مع الأسماك',
      'en': 'Pescatarian',
      'fr': 'Pescétarien',
      'es': 'Pescetariano',
      'tr': 'Pesketaryen',
      'de': 'Pescetarisch',
      'it': 'Pescetariano',
      'pt-BR': 'Pescetariano',
      'pt-PT': 'Pescetariano',
      'ur': 'مچھلی خور سبزی پسند',
      'fa': 'ماهی‌خوار',
      'hi': 'मत्स्याहारी',
      'id': 'Peskatarian',
      'ms': 'Pescatarian',
      'ja': 'ペスカタリアン',
      'ko': '페스코 베지테리언',
      'zh-Hans': '鱼素',
      'zh-Hant': '魚素',
      'ru': 'Пескетарианский',
      'bn': 'মাছসহ নিরামিষ',
      'vi': 'Ăn chay có cá',
      'th': 'มังสวิรัติที่กินปลา',
      'pl': 'Peskatariański',
      'nl': 'Pescotarisch',
      'uk': 'Пескетаріанський',
    },
    'Vegetarian': {
      'ar': 'نباتي',
      'en': 'Vegetarian',
      'fr': 'Végétarien',
      'es': 'Vegetariano',
      'tr': 'Vejetaryen',
      'de': 'Vegetarisch',
      'it': 'Vegetariano',
      'pt-BR': 'Vegetariano',
      'pt-PT': 'Vegetariano',
      'ur': 'سبزی خور',
      'fa': 'گیاه‌خوار',
      'hi': 'शाकाहारी',
      'id': 'Vegetarian',
      'ms': 'Vegetarian',
      'ja': 'ベジタリアン',
      'ko': '채식',
      'zh-Hans': '素食',
      'zh-Hant': '素食',
      'ru': 'Вегетарианский',
      'bn': 'নিরামিষ',
      'vi': 'Ăn chay',
      'th': 'มังสวิรัติ',
      'pl': 'Wegetariański',
      'nl': 'Vegetarisch',
      'uk': 'Вегетаріанський',
    },
    'Vegan': {
      'ar': 'نباتي صرف',
      'en': 'Vegan',
      'fr': 'Végane',
      'es': 'Vegano',
      'tr': 'Vegan',
      'de': 'Vegan',
      'it': 'Vegano',
      'pt-BR': 'Vegano',
      'pt-PT': 'Vegano',
      'ur': 'خالص نباتاتی',
      'fa': 'وگان',
      'hi': 'वीगन',
      'id': 'Vegan',
      'ms': 'Vegan',
      'ja': 'ヴィーガン',
      'ko': '비건',
      'zh-Hans': '纯素',
      'zh-Hant': '純素',
      'ru': 'Веганский',
      'bn': 'ভেগান',
      'vi': 'Thuần chay',
      'th': 'วีแกน',
      'pl': 'Wegański',
      'nl': 'Veganistisch',
      'uk': 'Веганський',
    },
    'Balanced': {
      'ar': 'متوازن',
      'en': 'Balanced',
      'fr': 'Équilibré',
      'es': 'Equilibrado',
      'tr': 'Dengeli',
      'de': 'Ausgewogen',
      'it': 'Bilanciato',
      'pt-BR': 'Equilibrado',
      'pt-PT': 'Equilibrado',
      'ur': 'متوازن',
      'fa': 'متعادل',
      'hi': 'संतुलित',
      'id': 'Seimbang',
      'ms': 'Seimbang',
      'ja': 'バランス重視',
      'ko': '균형식',
      'zh-Hans': '均衡',
      'zh-Hant': '均衡',
      'ru': 'Сбалансированный',
      'bn': 'সুষম',
      'vi': 'Cân bằng',
      'th': 'สมดุล',
      'pl': 'Zbilansowany',
      'nl': 'Gebalanceerd',
      'uk': 'Збалансований',
    },
    'High protein': {
      'ar': 'عالي البروتين',
      'en': 'High protein',
      'fr': 'Riche en protéines',
      'es': 'Alto en proteínas',
      'tr': 'Yüksek protein',
      'de': 'Proteinreich',
      'it': 'Ricco di proteine',
      'pt-BR': 'Rico em proteína',
      'pt-PT': 'Rico em proteína',
      'ur': 'زیادہ پروٹین',
      'fa': 'پرپروتئین',
      'hi': 'उच्च प्रोटीन',
      'id': 'Tinggi protein',
      'ms': 'Tinggi protein',
      'ja': '高たんぱく',
      'ko': '고단백',
      'zh-Hans': '高蛋白',
      'zh-Hant': '高蛋白',
      'ru': 'Высокобелковый',
      'bn': 'উচ্চ প্রোটিন',
      'vi': 'Giàu protein',
      'th': 'โปรตีนสูง',
      'pl': 'Wysokobiałkowy',
      'nl': 'Eiwitrijk',
      'uk': 'Високобілковий',
    },
    'Low carb': {
      'ar': 'منخفض الكربوهيدرات',
      'en': 'Low carb',
      'fr': 'Faible en glucides',
      'es': 'Bajo en carbohidratos',
      'tr': 'Düşük karbonhidrat',
      'de': 'Kohlenhydratarm',
      'it': 'A basso contenuto di carboidrati',
      'pt-BR': 'Baixo teor de carboidratos',
      'pt-PT': 'Baixo teor de hidratos de carbono',
      'ur': 'کم کاربوہائیڈریٹ',
      'fa': 'کم‌کربوهیدرات',
      'hi': 'कम कार्ब',
      'id': 'Rendah karbohidrat',
      'ms': 'Rendah karbohidrat',
      'ja': '低炭水化物',
      'ko': '저탄수화물',
      'zh-Hans': '低碳水',
      'zh-Hant': '低碳水',
      'ru': 'Низкоуглеводный',
      'bn': 'কম কার্ব',
      'vi': 'Ít carb',
      'th': 'คาร์โบไฮเดรตต่ำ',
      'pl': 'Niskowęglowodanowy',
      'nl': 'Koolhydraatarm',
      'uk': 'Низьковуглеводний',
    },
    'Keto': {
      'ar': 'كيتو',
      'en': 'Keto',
      'fr': 'Cétogène',
      'es': 'Cetogénico',
      'tr': 'Ketojenik',
      'de': 'Ketogen',
      'it': 'Chetogenico',
      'pt-BR': 'Cetogênico',
      'pt-PT': 'Cetogénico',
      'ur': 'کیٹو',
      'fa': 'کتوژنیک',
      'hi': 'कीटो',
      'id': 'Ketogenik',
      'ms': 'Ketogenik',
      'ja': 'ケトジェニック',
      'ko': '키토',
      'zh-Hans': '生酮',
      'zh-Hant': '生酮',
      'ru': 'Кето',
      'bn': 'কিটো',
      'vi': 'Keto',
      'th': 'คีโต',
      'pl': 'Ketogeniczny',
      'nl': 'Ketogeen',
      'uk': 'Кето',
    },
    'Mediterranean': {
      'ar': 'متوسطي',
      'en': 'Mediterranean',
      'fr': 'Méditerranéen',
      'es': 'Mediterráneo',
      'tr': 'Akdeniz',
      'de': 'Mediterran',
      'it': 'Mediterraneo',
      'pt-BR': 'Mediterrâneo',
      'pt-PT': 'Mediterrânico',
      'ur': 'بحیرۂ روم',
      'fa': 'مدیترانه‌ای',
      'hi': 'भूमध्यसागरीय',
      'id': 'Mediterania',
      'ms': 'Mediterranean',
      'ja': '地中海式',
      'ko': '지중해식',
      'zh-Hans': '地中海式',
      'zh-Hant': '地中海式',
      'ru': 'Средиземноморский',
      'bn': 'ভূমধ্যসাগরীয়',
      'vi': 'Địa Trung Hải',
      'th': 'เมดิเตอร์เรเนียน',
      'pl': 'Śródziemnomorski',
      'nl': 'Mediterraan',
      'uk': 'Середземноморський',
    },
    'Plant-forward': {
      'ar': 'يركز على النباتات',
      'en': 'Plant-forward',
      'fr': 'À dominante végétale',
      'es': 'Centrado en plantas',
      'tr': 'Bitki ağırlıklı',
      'de': 'Pflanzenbetont',
      'it': 'A prevalenza vegetale',
      'pt-BR': 'Predominantemente vegetal',
      'pt-PT': 'Predominantemente vegetal',
      'ur': 'نباتات پر مرکوز',
      'fa': 'گیاه‌محور',
      'hi': 'पौध-प्रधान',
      'id': 'Dominan nabati',
      'ms': 'Berasaskan tumbuhan',
      'ja': '植物性食品中心',
      'ko': '식물성 중심',
      'zh-Hans': '植物为主',
      'zh-Hant': '植物為主',
      'ru': 'С акцентом на растительную пищу',
      'bn': 'উদ্ভিদ-প্রধান',
      'vi': 'Ưu tiên thực vật',
      'th': 'เน้นพืชเป็นหลัก',
      'pl': 'Z przewagą roślin',
      'nl': 'Plantaardig gericht',
      'uk': 'З акцентом на рослинну їжу',
    },
  };

  static String? resolve(String english, String localeTag) {
    final canonical = BilLocalePolicy.canonicalSupportedTag(localeTag);
    if (canonical == null) return null;
    return values[english]?[canonical];
  }

  static bool get balanced =>
      supported.length == 25 &&
      values.values.every(
        (translations) =>
            translations.length == supported.length &&
            translations.keys.toSet().containsAll(supported) &&
            supported.containsAll(translations.keys) &&
            translations.values.every((value) => value.trim().isNotEmpty),
      );
}
