part of 'runtime_copy_next_workspace.dart';

const _nextWorkspaceRows3 = <String, List<String>>{
  'bn': [
    'এই আপডেটগুলো পড়া হয়েছে বলে নিশ্চিত করা যায়নি। আবার চেষ্টা করুন।',
    'এই পৃষ্ঠাটি পড়া হয়েছে হিসেবে চিহ্নিত করুন', 'আজকের দিনটি কাজে লাগাই।', 'আজকের লক্ষ্য',
    'একবারে একটি ছোট পদক্ষেপ। আপনার কোচ নথিভুক্ত করা, পর্যালোচনা ও পরিকল্পনায় সাহায্য করেন।',
    'পরিকল্পনার সরঞ্জাম', 'খাবার নথিভুক্ত করুন', 'কণ্ঠে নথিভুক্ত করুন', 'শুধু বলুন', 'কয়েক সেকেন্ডে', 'পণ্য স্ক্যান করুন', 'বারকোড / লেবেল', 'প্রতিটি খাবার আরও ভালোভাবে বুঝুন',
    'ডায়েরিতে যোগ করার আগে খাবার ও পরিমাণ যাচাই করতে ছবি তুলুন।',
    'ছবি দিয়ে নথিভুক্ত করুন  ›', 'আপনার স্বাস্থ্যের সময়রেখা', 'নথিভুক্ত খাবার', 'আপনার আসল ডায়েরিতে খাবারের {count}টি এন্ট্রি', 'কার্যকলাপ সিঙ্ক হয়েছে', 'আপনার যাচাই করা তথ্য এখানে দেখা যাবে।',
    'ছোট কিন্তু নিয়মিত পদক্ষেপ অর্থপূর্ণ অগ্রগতি আনে।\n— BIL এআই কোচ', 'আপনার স্বাস্থ্যের সঙ্গী, সবসময় পাশে', 'কথোপকথন খুঁজুন',
  ],
  'vi': [
    'Không thể xác nhận các cập nhật này đã được đọc. Vui lòng thử lại.',
    'Đánh dấu trang này đã đọc', 'Hãy làm cho hôm nay thật ý nghĩa.', 'Trọng tâm hôm nay',
    'Mỗi lần một hành động nhỏ. Huấn luyện viên giúp bạn ghi chép, nhìn lại và lập kế hoạch.',
    'Công cụ kế hoạch', 'Ghi lại bữa ăn', 'Ghi bằng giọng nói', 'Chỉ cần nói', 'Trong vài giây', 'Quét sản phẩm', 'Mã vạch / Nhãn', 'Hiểu rõ hơn mỗi bữa ăn',
    'Chụp ảnh để kiểm tra thực phẩm và khẩu phần trước khi thêm vào nhật ký.',
    'Thử ghi bằng ảnh  ›', 'Dòng thời gian sức khỏe', 'Bữa ăn đã ghi', '{count} mục bữa ăn trong nhật ký thực tế của bạn', 'Hoạt động đã đồng bộ', 'Các mục đã xác minh của bạn sẽ xuất hiện ở đây.',
    'Những hành động nhỏ đều đặn tạo nên tiến bộ ý nghĩa.\n— Huấn luyện viên AI BIL', 'Người bạn sức khỏe, luôn bên bạn', 'Tìm cuộc trò chuyện',
  ],
  'th': [
    'ไม่สามารถยืนยันว่าอ่านการอัปเดตเหล่านี้แล้ว โปรดลองอีกครั้ง',
    'ทำเครื่องหมายหน้านี้ว่าอ่านแล้ว', 'มาทำวันนี้ให้มีความหมายกัน', 'จุดเน้นวันนี้',
    'ก้าวเล็ก ๆ ทีละก้าว โค้ชพร้อมช่วยคุณบันทึก ทบทวน และวางแผน',
    'เครื่องมือวางแผน', 'บันทึกมื้ออาหาร', 'บันทึกด้วยเสียง', 'แค่พูด', 'ในไม่กี่วินาที', 'สแกนผลิตภัณฑ์', 'บาร์โค้ด / ฉลาก', 'เข้าใจทุกมื้อได้ดีขึ้น',
    'ถ่ายภาพเพื่อตรวจสอบอาหารและปริมาณก่อนเพิ่มลงในบันทึก',
    'ลองบันทึกด้วยภาพ  ›', 'ไทม์ไลน์สุขภาพของคุณ', 'มื้ออาหารที่บันทึก', 'รายการมื้ออาหารในบันทึกจริงของคุณ {count} รายการ', 'ซิงค์กิจกรรมแล้ว', 'รายการที่ยืนยันแล้วของคุณจะแสดงที่นี่',
    'การทำสิ่งเล็ก ๆ อย่างสม่ำเสมอสร้างความก้าวหน้าที่มีความหมาย\n— โค้ช AI BIL', 'เพื่อนคู่สุขภาพที่อยู่เคียงข้างคุณเสมอ', 'ค้นหาบทสนทนา',
  ],
  'pl': [
    'Nie udało się potwierdzić odczytania tych aktualizacji. Spróbuj ponownie.',
    'Oznacz tę stronę jako przeczytaną', 'Wykorzystajmy dzisiejszy dzień.', 'Cel na dziś',
    'Jeden mały krok naraz. Twój trener pomaga zapisywać, analizować i planować.',
    'Narzędzia planu', 'Zapisz posiłek', 'Zapis głosowy', 'Po prostu mów', 'W kilka sekund', 'Skanuj produkt', 'Kod kreskowy / Etykieta', 'Lepiej poznaj każdy posiłek',
    'Zrób zdjęcie, aby sprawdzić produkty i porcje przed dodaniem do dziennika.',
    'Wypróbuj zapis ze zdjęcia  ›', 'Twoja historia zdrowia', 'Zapisane posiłki', 'Liczba zapisów posiłków w Twoim dzienniku: {count}', 'Aktywność zsynchronizowana', 'Twoje potwierdzone wpisy pojawią się tutaj.',
    'Małe, regularne działania prowadzą do znaczących postępów.\n— Trener AI BIL', 'Twój partner w dbaniu o zdrowie, zawsze obok', 'Szukaj rozmów',
  ],
  'nl': [
    'Deze updates konden niet als gelezen worden bevestigd. Probeer het opnieuw.',
    'Deze pagina als gelezen markeren', 'Laten we er vandaag iets moois van maken.', 'Focus voor vandaag',
    'Eén kleine stap tegelijk. Je coach helpt je vastleggen, terugkijken en plannen.',
    'Planhulpmiddelen', 'Maaltijd vastleggen', 'Spraakinvoer', 'Praat gewoon', 'In enkele seconden', 'Product scannen', 'Barcode / Etiket', 'Begrijp elke maaltijd beter',
    'Maak een foto om het eten en de porties te controleren voordat je ze aan je dagboek toevoegt.',
    'Vastleggen met foto proberen  ›', 'Je gezondheidstijdlijn', 'Vastgelegde maaltijden', '{count} maaltijdregistraties in je echte dagboek', 'Activiteit gesynchroniseerd', 'Je bevestigde registraties verschijnen hier.',
    'Kleine, regelmatige stappen zorgen voor betekenisvolle vooruitgang.\n— BIL AI-coach', 'Je gezondheidspartner, altijd aan je zijde', 'Gesprekken doorzoeken',
  ],
  'uk': [
    'Не вдалося підтвердити прочитання цих оновлень. Спробуйте ще раз.',
    'Позначити цю сторінку як прочитану', 'Проведімо цей день із користю.', 'Головне на сьогодні',
    'Один невеликий крок за раз. Ваш тренер допомагає вести записи, оцінювати результати й планувати.',
    'Інструменти плану', 'Записати прийом їжі', 'Голосовий запис', 'Просто говоріть', 'За кілька секунд', 'Сканувати продукт', 'Штрихкод / Етикетка', 'Дізнайтеся більше про кожен прийом їжі',
    'Зробіть фото, щоб перевірити продукти й порції перед додаванням до щоденника.',
    'Спробувати запис за фото  ›', 'Ваша історія здоров’я', 'Записані прийоми їжі', 'Записів про їжу у вашому щоденнику: {count}', 'Активність синхронізовано', 'Тут з’являться ваші підтверджені записи.',
    'Невеликі регулярні дії ведуть до значущого прогресу.\n— ШІ-тренер BIL', 'Ваш партнер зі здоров’я, завжди поруч', 'Пошук розмов',
  ],
};
