part of 'runtime_copy_coach_controls.dart';

const _coachControlsRows3 = <String, List<String>>{
  "bn": [
    "অ্যাপের চেহারা আপডেট করা হয়েছে।",
    "অ্যাপের ভাষা আপডেট করা হয়েছে।",
    "লেখার আগে জিজ্ঞাসা করুন",
    "BIL শুধুমাত্র আপনার অনুরোধ করা উত্তর তৈরি করতে Google পরিচালিত তৃতীয় পক্ষের AI পরিষেবা Google Gemini ব্যবহার করে।",
    "কথোপকথন",
    "কথোপকথনের ইতিহাস এই ডিভাইসে স্থানীয়ভাবে সংরক্ষিত থাকে।",
    "কথোপকথনের তালিকা",
    "বর্তমান কথোপকথন",
    "লাইভ কল শেষ করুন",
    "খাবারের ছবি",
    "এই কথোপকথনটি ইতিহাসে রেখে একটি খালি কথোপকথন শুরু করুন।",
    "নতুন কথোপকথন",
    "এখনও আগের কোনো কথোপকথন নেই।",
    "শুধু আপনার বেছে নেওয়া প্রেক্ষাপট",
    "মাইক্রোফোনের কাঁচা অডিও পাঠানো হয় না",
    "শুধু পড়া",
    "পাঠানো হচ্ছে",
    "সফলভাবে সাইন আউট হয়েছে।",
    "অপেক্ষমাণ কাজটি বাতিল করা হয়েছে। কিছুই বদলানো হয়নি।",
    "আগের কাজটি পূর্বাবস্থায় ফেরানো হয়েছে।",
    "পূর্বাবস্থায় ফেরানো যায় এমন কোনো সাম্প্রতিক কাজ নেই।",
    "এই কাজের জন্য লেখার অনুমতি দরকার। চালিয়ে যেতে ঢালের সেটিং বদলান।",
    "কণ্ঠস্বর শনাক্তকরণ এই দূরবর্তী AI সম্মতি থেকে আলাদা থাকে।",
    "লেখার অনুমতি আছে",
    "আপনি প্রত্যাখ্যান করে BIL-এর স্থানীয় বৈশিষ্ট্যগুলি ব্যবহার করতে পারেন, অথবা পরে AI কোচের সেটিংসে এই সম্মতি প্রত্যাহার করতে পারেন।",
    "নিয়ন্ত্রণ আপনার হাতেই থাকে",
    "আপনার প্রশ্ন; নির্বাচিত ওজন, লক্ষ্য ও পরিমাপ; খাবার, পুষ্টি, পানি ও পছন্দ; কার্যকলাপ ও প্রশিক্ষণ; ঘুম ও অভ্যাস; সঙ্গে কথোপকথনের সর্বশেষ সর্বোচ্চ 12টি বার্তা।",
    "কাজটি সম্পন্ন হয়নি। আপনার তথ্য অপরিবর্তিত রয়েছে; মানটি পর্যালোচনা করে আবার চেষ্টা করুন।",
  ],
  "vi": [
    "Đã cập nhật giao diện ứng dụng.",
    "Đã cập nhật ngôn ngữ ứng dụng.",
    "Hỏi trước khi ghi",
    "BIL sử dụng Google Gemini, một dịch vụ AI bên thứ ba do Google vận hành, chỉ để tạo câu trả lời bạn yêu cầu.",
    "Cuộc trò chuyện",
    "Lịch sử trò chuyện được lưu cục bộ trên thiết bị này.",
    "Các cuộc trò chuyện",
    "Cuộc trò chuyện hiện tại",
    "Kết thúc cuộc gọi trực tiếp",
    "Ảnh món ăn",
    "Giữ cuộc trò chuyện này trong lịch sử và bắt đầu một cuộc trò chuyện trống.",
    "Cuộc trò chuyện mới",
    "Chưa có cuộc trò chuyện trước đó.",
    "Chỉ ngữ cảnh bạn chọn",
    "Âm thanh thô từ micrô không được gửi đi",
    "Chỉ đọc",
    "Đang gửi",
    "Đã đăng xuất thành công.",
    "Đã hủy hành động đang chờ. Không có gì thay đổi.",
    "Đã hoàn tác hành động trước đó.",
    "Không có hành động gần đây nào có thể hoàn tác.",
    "Hành động này cần quyền ghi. Hãy đổi cài đặt biểu tượng khiên để tiếp tục.",
    "Nhận dạng giọng nói vẫn tách biệt với sự đồng ý sử dụng AI từ xa này.",
    "Cho phép ghi",
    "Bạn có thể từ chối và tiếp tục dùng các tính năng cục bộ của BIL, hoặc rút lại sự đồng ý này sau trong cài đặt Huấn luyện viên AI.",
    "Bạn vẫn nắm quyền kiểm soát",
    "Câu hỏi của bạn; cân nặng, mục tiêu và số đo đã chọn; bữa ăn, dinh dưỡng, nước và tùy chọn; hoạt động và tập luyện; giấc ngủ và thói quen; cùng tối đa 12 tin nhắn trò chuyện gần đây.",
    "Hành động chưa hoàn tất. Dữ liệu của bạn không thay đổi; hãy kiểm tra giá trị rồi thử lại.",
  ],
  "th": [
    "อัปเดตรูปลักษณ์ของแอปแล้ว",
    "อัปเดตภาษาของแอปแล้ว",
    "ถามก่อนเขียนข้อมูล",
    "BIL ใช้ Google Gemini ซึ่งเป็นบริการ AI ของบุคคลที่สามที่ดำเนินการโดย Google เพื่อสร้างคำตอบที่คุณขอเท่านั้น",
    "การสนทนา",
    "ประวัติการสนทนาจัดเก็บไว้ภายในอุปกรณ์นี้",
    "รายการสนทนา",
    "การสนทนาปัจจุบัน",
    "จบการโทรสด",
    "รูปอาหาร",
    "เก็บการสนทนานี้ไว้ในประวัติและเริ่มการสนทนาใหม่ที่ว่างเปล่า",
    "การสนทนาใหม่",
    "ยังไม่มีการสนทนาก่อนหน้า",
    "เฉพาะบริบทที่คุณเลือก",
    "ไม่มีการส่งเสียงดิบจากไมโครโฟน",
    "อ่านอย่างเดียว",
    "กำลังส่ง",
    "ออกจากระบบเรียบร้อยแล้ว",
    "ยกเลิกการดำเนินการที่รออยู่แล้ว ไม่มีสิ่งใดเปลี่ยนแปลง",
    "เลิกทำการดำเนินการก่อนหน้าแล้ว",
    "ไม่มีการดำเนินการล่าสุดที่เลิกทำได้",
    "การดำเนินการนี้ต้องมีสิทธิ์เขียนข้อมูล เปลี่ยนการตั้งค่ารูปโล่เพื่อดำเนินการต่อ",
    "การรู้จำเสียงยังคงแยกจากความยินยอมใช้ AI ระยะไกลนี้",
    "อนุญาตให้เขียนข้อมูล",
    "คุณสามารถปฏิเสธและใช้ฟีเจอร์ภายในอุปกรณ์ของ BIL ต่อไป หรือถอนความยินยอมนี้ภายหลังในการตั้งค่าโค้ช AI",
    "คุณยังคงเป็นผู้ควบคุม",
    "คำถามของคุณ น้ำหนัก เป้าหมาย และค่าที่วัดที่เลือกไว้ มื้ออาหาร โภชนาการ น้ำ และค่ากำหนด กิจกรรมและการฝึก การนอนและนิสัย รวมถึงข้อความสนทนาล่าสุดไม่เกิน 12 ข้อความ",
    "การดำเนินการไม่สำเร็จ ข้อมูลของคุณไม่เปลี่ยนแปลง โปรดตรวจสอบค่าแล้วลองอีกครั้ง",
  ],
  "pl": [
    "Zaktualizowano wygląd aplikacji.",
    "Zaktualizowano język aplikacji.",
    "Pytaj przed zapisem",
    "BIL korzysta z Google Gemini, zewnętrznej usługi AI obsługiwanej przez Google, wyłącznie w celu wygenerowania żądanej odpowiedzi.",
    "Rozmowa",
    "Historia rozmów jest przechowywana lokalnie na tym urządzeniu.",
    "Rozmowy",
    "Bieżąca rozmowa",
    "Zakończ połączenie na żywo",
    "Zdjęcie jedzenia",
    "Zachowaj tę rozmowę w historii i rozpocznij pustą.",
    "Nowa rozmowa",
    "Nie ma jeszcze wcześniejszych rozmów.",
    "Tylko wybrany przez Ciebie kontekst",
    "Surowy dźwięk z mikrofonu nie jest wysyłany",
    "Tylko odczyt",
    "Wysyłanie",
    "Wylogowano pomyślnie.",
    "Anulowano oczekującą czynność. Nic nie zmieniono.",
    "Cofnięto poprzednią czynność.",
    "Nie ma ostatniej czynności, którą można cofnąć.",
    "Ta czynność wymaga uprawnień do zapisu. Zmień ustawienie tarczy, aby kontynuować.",
    "Rozpoznawanie mowy pozostaje niezależne od tej zgody na zdalną AI.",
    "Zapis dozwolony",
    "Możesz odmówić i nadal korzystać z lokalnych funkcji BIL albo później wycofać tę zgodę w ustawieniach trenera AI.",
    "Zachowujesz kontrolę",
    "Twoje pytanie; wybrane dane o wadze, celach i pomiarach; posiłki, odżywianie, woda i preferencje; aktywność i trening; sen i nawyki; a także maksymalnie 12 ostatnich wiadomości rozmowy.",
    "Czynność nie została ukończona. Twoje dane pozostały bez zmian; sprawdź wartość i spróbuj ponownie.",
  ],
  "nl": [
    "De appweergave is bijgewerkt.",
    "De app-taal is bijgewerkt.",
    "Vragen vóór schrijven",
    "BIL gebruikt Google Gemini, een externe AI-dienst van Google, uitsluitend om het antwoord te maken waar je om vraagt.",
    "Gesprek",
    "De gespreksgeschiedenis wordt lokaal op dit apparaat opgeslagen.",
    "Gesprekken",
    "Huidig gesprek",
    "Livegesprek beëindigen",
    "Foto van eten",
    "Bewaar dit gesprek in de geschiedenis en begin een leeg gesprek.",
    "Nieuw gesprek",
    "Er zijn nog geen eerdere gesprekken.",
    "Alleen de context die jij kiest",
    "Onbewerkte microfoonaudio wordt niet verzonden",
    "Alleen lezen",
    "Bezig met verzenden",
    "Je bent uitgelogd.",
    "De wachtende actie is geannuleerd. Er is niets gewijzigd.",
    "De vorige actie is ongedaan gemaakt.",
    "Er is geen recente actie die ongedaan kan worden gemaakt.",
    "Voor deze actie is schrijfrecht nodig. Wijzig de schildinstelling om door te gaan.",
    "Spraakherkenning blijft losstaan van deze toestemming voor externe AI.",
    "Schrijven toegestaan",
    "Je kunt weigeren en de lokale BIL-functies blijven gebruiken, of deze toestemming later intrekken in de instellingen van de AI-coach.",
    "Jij houdt de controle",
    "Je vraag; geselecteerd gewicht, doelen en metingen; maaltijden, voeding, water en voorkeuren; activiteit en training; slaap en gewoonten; plus maximaal 12 recente gespreksberichten.",
    "De actie is niet voltooid. Je gegevens bleven ongewijzigd; controleer de waarde en probeer het opnieuw.",
  ],
  "uk": [
    "Оформлення застосунку оновлено.",
    "Мову застосунку оновлено.",
    "Запитувати перед записом",
    "BIL використовує Google Gemini, сторонній сервіс ШІ під керуванням Google, лише для створення запитаної вами відповіді.",
    "Розмова",
    "Історія розмов зберігається локально на цьому пристрої.",
    "Розмови",
    "Поточна розмова",
    "Завершити розмову наживо",
    "Фото їжі",
    "Зберегти цю розмову в історії та почати порожню.",
    "Нова розмова",
    "Попередніх розмов ще немає.",
    "Лише вибраний вами контекст",
    "Необроблений звук мікрофона не надсилається",
    "Лише читання",
    "Надсилання",
    "Вихід виконано успішно.",
    "Дію в очікуванні скасовано. Нічого не змінено.",
    "Попередню дію скасовано.",
    "Немає нещодавньої дії, яку можна скасувати.",
    "Ця дія потребує дозволу на запис. Змініть налаштування щита, щоб продовжити.",
    "Розпізнавання мовлення залишається окремим від цієї згоди на віддалений ШІ.",
    "Запис дозволено",
    "Ви можете відмовитися й далі користуватися локальними функціями BIL або відкликати цю згоду пізніше в налаштуваннях ШІ-тренера.",
    "Ви зберігаєте контроль",
    "Ваше запитання; вибрані дані про вагу, цілі й вимірювання; прийоми їжі, харчування, вода та вподобання; активність і тренування; сон і звички; а також до 12 останніх повідомлень розмови.",
    "Дію не завершено. Ваші дані залишилися без змін; перевірте значення та спробуйте ще раз.",
  ],
};
