/// Final runtime copy added during the Google Play locale gate.
///
/// This compact row catalog keeps every release locale explicit while the
/// source list remains the single ordering contract. Placeholder and brand
/// preservation are enforced by localization tests.
abstract final class ReleaseClosureRuntimeCopy {
  static const supported = <String>{
    "ar",
    "en",
    "fr",
    "es",
    "tr",
    "de",
    "it",
    "pt-BR",
    "pt-PT",
    "ur",
    "fa",
    "hi",
    "id",
    "ms",
    "ja",
    "ko",
    "zh-Hans",
    "zh-Hant",
    "ru",
    "bn",
    "vi",
    "th",
    "pl",
    "nl",
    "uk",
  };

  static const sources = <String>[
    "Allow camera for this action?",
    "Allow voice input for this action?",
    "Answer confidence: {confidence}",
    "BIL only uses the camera after you choose barcode or meal-photo capture. Enable camera access in system settings, or continue with manual entry.",
    "BIL starts listening only after you choose voice weight entry. Review the recognized value before saving.",
    "Camera access is off",
    "Cancel waiting",
    "Discard",
    "Discard changes?",
    "Eating pattern",
    "Eating pattern controls compatible foods. Plan style shapes meal suggestions; neither changes allergy safeguards.",
    "End call",
    "Keep editing",
    "Live call transcript · pause to send",
    "Microphone access is off. Enable it in system settings to add weight by voice; manual entry remains available.",
    "Open {label}",
    "Pause live call",
    "Plan style",
    "Preparing your answer…",
    "Reasoning",
    "Report answer",
    "Report this AI answer?",
    "Report unsafe or offensive answer",
    "Resume live call",
    "Searching your BIL context…",
    "Start live call",
    "Still missing",
    "Thanks — this answer was reported for safety review.",
    "The camera opens only for the barcode or meal photo you selected. BIL does not request access at startup.",
    "The reply did not complete. Try again.",
    "Use this for unsafe, offensive, hateful, sexual, deceptive, or otherwise harmful content. BIL records the response ID and safety category, not your question or the answer text.",
    "Voice stays on this device",
    "Why BIL answered this way",
    "Writing your words · pause to send",
    "You have unsaved changes.",
    "Your device turns speech into text. Only that recognized text can be sent to Gemini.",
  ];

  static const rows = <String, List<String>>{
    "ar": <String>[
      "السماح بالكاميرا لهذا الإجراء؟",
      "السماح بالإدخال الصوتي لهذا الإجراء؟",
      "ثقة الإجابة: {confidence}",
      "لا يستخدم BIL الكاميرا إلا بعد اختيار مسح الرمز الشريطي أو تصوير الوجبة. فعّل الكاميرا من إعدادات النظام، أو تابع الإدخال اليدوي.",
      "يبدأ BIL الاستماع فقط بعد اختيار إدخال الوزن صوتيًا. راجع القيمة التي تم التعرف عليها قبل الحفظ.",
      "الوصول إلى الكاميرا متوقف",
      "إلغاء الانتظار",
      "تجاهل",
      "تجاهل التغييرات؟",
      "نمط الأكل",
      "يتحكم نمط الأكل في الأطعمة المتوافقة. يحدد أسلوب الخطة اقتراحات الوجبات؛ ولا يغيّر أي منهما احتياطات الحساسية.",
      "إنهاء المكالمة",
      "متابعة التعديل",
      "نص المكالمة المباشرة · توقّف مؤقتًا للإرسال",
      "الوصول إلى الميكروفون متوقف. فعّله من إعدادات النظام لإضافة الوزن صوتيًا؛ يظل الإدخال اليدوي متاحًا.",
      "فتح {label}",
      "إيقاف المكالمة المباشرة مؤقتًا",
      "أسلوب الخطة",
      "جارٍ تجهيز إجابتك…",
      "الاستدلال",
      "الإبلاغ عن الإجابة",
      "الإبلاغ عن إجابة الذكاء الاصطناعي؟",
      "الإبلاغ عن إجابة غير آمنة أو مسيئة",
      "استئناف المكالمة المباشرة",
      "جارٍ البحث في سياق BIL…",
      "بدء مكالمة مباشرة",
      "ما يزال ناقصًا",
      "شكرًا — تم الإبلاغ عن هذه الإجابة لمراجعة السلامة.",
      "تفتح الكاميرا فقط للرمز الشريطي أو صورة الوجبة التي اخترتها. لا يطلب BIL الوصول عند بدء التشغيل.",
      "لم تكتمل الإجابة. حاول مجددًا.",
      "استخدم هذا للمحتوى غير الآمن أو المسيء أو المحرّض على الكراهية أو الجنسي أو المخادع أو الضار بأي شكل. يسجل BIL معرّف الرد وفئة السلامة فقط، وليس سؤالك أو نص الإجابة.",
      "يبقى الصوت على هذا الجهاز",
      "لماذا أجاب BIL بهذه الطريقة",
      "جارٍ كتابة كلماتك · توقّف مؤقتًا للإرسال",
      "لديك تغييرات غير محفوظة.",
      "يحوّل جهازك الكلام إلى نص. لا يمكن إرسال سوى النص المتعرّف عليه إلى Gemini.",
    ],
    "en": <String>[
      "Allow camera for this action?",
      "Allow voice input for this action?",
      "Answer confidence: {confidence}",
      "BIL only uses the camera after you choose barcode or meal-photo capture. Enable camera access in system settings, or continue with manual entry.",
      "BIL starts listening only after you choose voice weight entry. Review the recognized value before saving.",
      "Camera access is off",
      "Cancel waiting",
      "Discard",
      "Discard changes?",
      "Eating pattern",
      "Eating pattern controls compatible foods. Plan style shapes meal suggestions; neither changes allergy safeguards.",
      "End call",
      "Keep editing",
      "Live call transcript · pause to send",
      "Microphone access is off. Enable it in system settings to add weight by voice; manual entry remains available.",
      "Open {label}",
      "Pause live call",
      "Plan style",
      "Preparing your answer…",
      "Reasoning",
      "Report answer",
      "Report this AI answer?",
      "Report unsafe or offensive answer",
      "Resume live call",
      "Searching your BIL context…",
      "Start live call",
      "Still missing",
      "Thanks — this answer was reported for safety review.",
      "The camera opens only for the barcode or meal photo you selected. BIL does not request access at startup.",
      "The reply did not complete. Try again.",
      "Use this for unsafe, offensive, hateful, sexual, deceptive, or otherwise harmful content. BIL records the response ID and safety category, not your question or the answer text.",
      "Voice stays on this device",
      "Why BIL answered this way",
      "Writing your words · pause to send",
      "You have unsaved changes.",
      "Your device turns speech into text. Only that recognized text can be sent to Gemini.",
    ],
    "fr": <String>[
      "Autoriser la caméra pour cette action ?",
      "Autoriser la saisie vocale pour cette action ?",
      "Niveau de confiance : {confidence}",
      "BIL n'utilise l'appareil photo qu'après avoir choisi la capture d'un code-barres ou d'une photo de repas. Activez l’accès à la caméra dans les paramètres système ou poursuivez la saisie manuelle.",
      "BIL ne commence à écouter qu'après avoir choisi la saisie du poids vocal. Vérifiez la valeur reconnue avant de sauvegarder.",
      "L'accès à la caméra est désactivé",
      "Annuler l'attente",
      "Jeter",
      "Supprimer les modifications ?",
      "Modèle alimentaire",
      "Les habitudes alimentaires contrôlent les aliments compatibles. Le style du plan façonne les suggestions de repas ; ni l’un ni l’autre ne modifie les mesures de protection contre les allergies.",
      "Terminer l'appel",
      "Continuer à éditer",
      "Transcription d'appel en direct · pause pour envoyer",
      "L'accès au microphone est désactivé. Activez-le dans les paramètres système pour ajouter du poids par la voix ; la saisie manuelle reste disponible.",
      "Ouvrir {label}",
      "Suspendre l'appel en direct",
      "Style de plan",
      "Préparez votre réponse…",
      "Raisonnement",
      "Signaler la réponse",
      "Signaler cette réponse de l'IA ?",
      "Signaler une réponse dangereuse ou offensante",
      "Reprendre l'appel en direct",
      "Recherche dans votre contexte BIL…",
      "Démarrer un appel en direct",
      "Toujours manquant",
      "Merci - cette réponse a été signalée pour examen de sécurité.",
      "L'appareil photo s'ouvre uniquement pour le code-barres ou la photo du repas que vous avez sélectionné. BIL ne demande pas d'accès au démarrage.",
      "La réponse n'est pas complète. Essayer à nouveau.",
      "Utilisez-le pour du contenu dangereux, offensant, haineux, sexuel, trompeur ou autrement préjudiciable. BIL enregistre l'ID de réponse et la catégorie de sécurité, pas votre question ou le texte de la réponse.",
      "La voix reste sur cet appareil",
      "Pourquoi BIL a répondu de cette façon",
      "Écrire vos mots · pause pour envoyer",
      "Vous avez des modifications non enregistrées.",
      "Votre appareil transforme la parole en texte. Seul ce texte reconnu peut être envoyé à Gemini.",
    ],
    "es": <String>[
      "¿Permitir cámara para esta acción?",
      "¿Permitir entrada de voz para esta acción?",
      "Confianza de la respuesta: {confidence}",
      "BIL solo usa la cámara después de elegir la captura de código de barras o foto de comida. Habilite el acceso a la cámara en la configuración del sistema o continúe con la entrada manual.",
      "BIL comienza a escuchar solo después de elegir la entrada de peso de voz. Revise el valor reconocido antes de guardar.",
      "El acceso a la cámara está desactivado",
      "Cancelar espera",
      "Descartar",
      "¿Descartar cambios?",
      "patrón de alimentación",
      "El patrón de alimentación controla los alimentos compatibles. El estilo del plan da forma a las sugerencias de comidas; Ninguno de los dos cambia las protecciones contra las alergias.",
      "finalizar llamada",
      "Sigue editando",
      "Transcripción de llamada en vivo · pausar para enviar",
      "El acceso al micrófono está desactivado. Habilítelo en la configuración del sistema para agregar peso mediante voz; la entrada manual permanece disponible.",
      "Abrir {label}",
      "Pausar llamada en vivo",
      "Estilo del plano",
      "Preparando tu respuesta...",
      "Razonamiento",
      "Informar respuesta",
      "¿Informar esta respuesta de IA?",
      "Reportar respuesta insegura u ofensiva",
      "Reanudar llamada en vivo",
      "Buscando en su contexto BIL...",
      "Iniciar llamada en vivo",
      "Aún falta",
      "Gracias. Esta respuesta se informó para una revisión de seguridad.",
      "La cámara se abre solo para el código de barras o la foto de comida que seleccionó. BIL no solicita acceso al inicio.",
      "La respuesta no se completó. Intentar otra vez.",
      "Úselo para contenido inseguro, ofensivo, que incite al odio, sexual, engañoso o de otro modo dañino. BIL registra el ID de respuesta y la categoría de seguridad, no su pregunta ni el texto de la respuesta.",
      "La voz permanece en este dispositivo",
      "Por qué BIL respondió de esta manera",
      "Escribiendo tus palabras · pausa para enviar",
      "Tienes cambios sin guardar.",
      "Su dispositivo convierte la voz en texto. Sólo ese texto reconocido se puede enviar a Gemini.",
    ],
    "tr": <String>[
      "Bu işlem için kameraya izin verilsin mi?",
      "Bu işlem için ses girişine izin verilsin mi?",
      "Yanıt güveni: {confidence}",
      "BIL kamerayı yalnızca siz barkod veya yemek fotoğrafı çekmeyi seçtikten sonra kullanır. Sistem ayarlarında kamera erişimini etkinleştirin veya manuel girişle devam edin.",
      "BIL yalnızca ses ağırlığı girişini seçmenizden sonra dinlemeye başlar. Kaydetmeden önce tanınan değeri inceleyin.",
      "Kamera erişimi kapalı",
      "Beklemeyi iptal et",
      "At",
      "Değişiklikler silinsin mi?",
      "Yeme düzeni",
      "Yeme düzeni uyumlu yiyecekleri kontrol eder. Plan tarzı yemek önerilerini şekillendirir; ikisi de alerji önlemlerini değiştirmez.",
      "Aramayı sonlandır",
      "Düzenlemeye devam et",
      "Canlı çağrı metni · göndermek için duraklatın",
      "Mikrofon erişimi kapalı. Sesle ağırlık eklemek için sistem ayarlarında bunu etkinleştirin; manuel giriş kullanılabilir durumda kalır.",
      "{label}'ı aç",
      "Canlı aramayı duraklat",
      "Plan stili",
      "Cevabınız hazırlanıyor…",
      "muhakeme",
      "Yanıtı bildir",
      "Bu AI yanıtı rapor edilsin mi?",
      "Güvenli olmayan veya rahatsız edici yanıtı bildirin",
      "Canlı görüşmeyi devam ettir",
      "BIL bağlamınız aranıyor…",
      "Canlı aramayı başlat",
      "Hâlâ eksik",
      "Teşekkürler — bu yanıt güvenlik incelemesi için bildirildi.",
      "Kamera yalnızca seçtiğiniz barkod veya yemek fotoğrafı için açılır. BIL başlangıçta erişim talebinde bulunmuyor.",
      "Cevap tamamlanmadı. Tekrar deneyin.",
      "Bunu güvenli olmayan, saldırgan, nefret dolu, cinsel, aldatıcı veya başka şekilde zararlı içerik için kullanın. BIL sorunuzu veya cevap metnini değil, yanıt kimliğini ve güvenlik kategorisini kaydeder.",
      "Ses bu cihazda kalır",
      "Neden BIL bu şekilde yanıt verdi?",
      "Kelimelerinizi yazma · göndermek için duraklatın",
      "Kaydedilmemiş değişiklikleriniz var.",
      "Cihazınız konuşmayı metne dönüştürür. Yalnızca tanınan metin Gemini adresine gönderilebilir.",
    ],
    "de": <String>[
      "Kamera für diese Aktion zulassen?",
      "Spracheingabe für diese Aktion zulassen?",
      "Konfidenz der Antwort: {confidence}",
      "BIL verwendet die Kamera erst, nachdem Sie sich für die Barcode- oder Essensfotoaufnahme entschieden haben. Aktivieren Sie den Kamerazugriff in den Systemeinstellungen oder fahren Sie mit der manuellen Eingabe fort.",
      "BIL beginnt erst mit dem Zuhören, nachdem Sie die Eingabe der Sprachgewichtung ausgewählt haben. Überprüfen Sie den erkannten Wert vor dem Speichern.",
      "Der Kamerazugriff ist deaktiviert",
      "Warten abbrechen",
      "Verwerfen",
      "Änderungen verwerfen?",
      "Essmuster",
      "Das Essverhalten steuert kompatible Lebensmittel. Der Planstil prägt Essensvorschläge; Beides ändert nichts an den Allergieschutzmaßnahmen.",
      "Anruf beenden",
      "Bearbeiten Sie weiter",
      "Live-Anruftranskript · Pause zum Senden",
      "Der Mikrofonzugriff ist deaktiviert. Aktivieren Sie es in den Systemeinstellungen, um das Gewicht per Stimme hinzuzufügen. Die manuelle Eingabe bleibt weiterhin möglich.",
      "Öffnen Sie {label}",
      "Live-Anruf unterbrechen",
      "Planstil",
      "Bereiten Sie Ihre Antwort vor ...",
      "Begründung",
      "Antwort melden",
      "Diese KI-Antwort melden?",
      "Melden Sie unsichere oder beleidigende Antworten",
      "Live-Anruf fortsetzen",
      "Durchsuchen Sie Ihren BIL-Kontext…",
      "Live-Anruf starten",
      "Fehlt noch",
      "Danke – diese Antwort wurde zur Sicherheitsüberprüfung gemeldet.",
      "Die Kamera öffnet sich nur für den von Ihnen ausgewählten Barcode oder das Essensfoto. BIL fordert beim Start keinen Zugriff an.",
      "Die Antwort wurde nicht abgeschlossen. Versuchen Sie es erneut.",
      "Verwenden Sie dies für unsichere, beleidigende, hasserfüllte, sexuelle, irreführende oder anderweitig schädliche Inhalte. BIL zeichnet die Antwort-ID und die Sicherheitskategorie auf, nicht Ihre Frage oder den Antworttext.",
      "Die Stimme bleibt auf diesem Gerät",
      "Warum BIL so geantwortet hat",
      "Schreiben Sie Ihre Worte · Pause zum Senden",
      "Sie haben nicht gespeicherte Änderungen.",
      "Ihr Gerät wandelt Sprache in Text um. Nur dieser erkannte Text kann an Gemini gesendet werden.",
    ],
    "it": <String>[
      "Consentire la fotocamera per questa azione?",
      "Consentire l'input vocale per questa azione?",
      "Affidabilità della risposta: {confidence}",
      "BIL utilizza la fotocamera solo dopo aver scelto l'acquisizione del codice a barre o della foto del pasto. Abilita l'accesso alla telecamera nelle impostazioni di sistema o continua con l'inserimento manuale.",
      "BIL inizia ad ascoltare solo dopo aver scelto l'immissione del peso della voce. Rivedere il valore riconosciuto prima di salvare.",
      "L'accesso alla fotocamera è disattivato",
      "Annulla l'attesa",
      "Scartare",
      "Eliminare le modifiche?",
      "Modello alimentare",
      "Il modello alimentare controlla gli alimenti compatibili. Lo stile del piano modella i suggerimenti sui pasti; nessuno dei due cambia le misure di protezione contro le allergie.",
      "Termina chiamata",
      "Continua a modificare",
      "Trascrizione della chiamata in tempo reale · pausa per inviare",
      "L'accesso al microfono è disattivato. Abilitalo nelle impostazioni di sistema per aggiungere peso tramite voce; l'immissione manuale rimane disponibile.",
      "Apri {label}",
      "Metti in pausa la chiamata dal vivo",
      "Stile del piano",
      "Preparare la risposta...",
      "Ragionamento",
      "Riporta la risposta",
      "Segnalare questa risposta AI?",
      "Segnala una risposta non sicura o offensiva",
      "Riprendi la chiamata dal vivo",
      "Ricerca nel contesto BIL…",
      "Avvia la chiamata dal vivo",
      "Ancora mancante",
      "Grazie: questa risposta è stata segnalata per la revisione della sicurezza.",
      "La fotocamera si apre solo per il codice a barre o la foto del pasto selezionato. BIL non richiede l'accesso all'avvio.",
      "La risposta non è stata completata. Riprova.",
      "Utilizzalo per contenuti non sicuri, offensivi, che incitano all'odio, a sfondo sessuale, ingannevoli o altrimenti dannosi. BIL registra l'ID della risposta e la categoria di sicurezza, non la domanda o il testo della risposta.",
      "La voce rimane su questo dispositivo",
      "Perché BIL ha risposto in questo modo",
      "Scrivere le tue parole · fare una pausa per inviare",
      "Sono presenti modifiche non salvate.",
      "Il tuo dispositivo trasforma la voce in testo. Solo il testo riconosciuto può essere inviato a Gemini.",
    ],
    "pt-BR": <String>[
      "Permitir câmera para esta ação?",
      "Permitir entrada de voz para esta ação?",
      "Confiança da resposta: {confidence}",
      "BIL só usa a câmera depois que você escolhe a captura de código de barras ou foto de refeição. Ative o acesso à câmera nas configurações do sistema ou continue com a entrada manual.",
      "BIL começa a ouvir somente depois que você escolhe a entrada de peso de voz. Revise o valor reconhecido antes de salvar.",
      "O acesso à câmera está desativado",
      "Cancelar espera",
      "Descartar",
      "Descartar alterações?",
      "Padrão alimentar",
      "O padrão alimentar controla os alimentos compatíveis. O estilo do plano molda sugestões de refeições; nenhum deles altera as salvaguardas contra alergias.",
      "Encerrar chamada",
      "Continue editando",
      "Transcrição da chamada ao vivo · pausar para enviar",
      "O acesso ao microfone está desativado. Habilite-o nas configurações do sistema para adicionar peso por voz; a entrada manual permanece disponível.",
      "Abra {label}",
      "Pausar chamada ao vivo",
      "Estilo de plano",
      "Preparando sua resposta…",
      "Raciocínio",
      "Denunciar resposta",
      "Denunciar esta resposta de IA?",
      "Denunciar resposta insegura ou ofensiva",
      "Retomar chamada ao vivo",
      "Pesquisando seu contexto BIL…",
      "Iniciar chamada ao vivo",
      "Ainda falta",
      "Obrigado – esta resposta foi relatada para revisão de segurança.",
      "A câmera abre apenas para o código de barras ou foto da refeição selecionada. BIL não solicita acesso na inicialização.",
      "A resposta não foi concluída. Tente novamente.",
      "Use-o para conteúdo inseguro, ofensivo, odioso, sexual, enganoso ou de outra forma prejudicial. BIL registra o ID da resposta e a categoria de segurança, não sua pergunta ou o texto da resposta.",
      "A voz permanece neste dispositivo",
      "Por que BIL respondeu desta forma",
      "Escrevendo suas palavras · faça uma pausa para enviar",
      "Você tem alterações não salvas.",
      "Seu dispositivo transforma fala em texto. Somente esse texto reconhecido pode ser enviado para Gemini.",
    ],
    "pt-PT": <String>[
      "Permitir câmara para esta ação?",
      "Permitir a entrada de voz para esta ação?",
      "Confiança da resposta: {confidence}",
      "BIL só utiliza a câmara depois de escolher a captura de código de barras ou foto de refeição. Ative o acesso à câmara nas definições do sistema ou continue com a introdução manual.",
      "BIL começa a ouvir apenas depois de escolher a entrada de peso de voz. Reveja o valor reconhecido antes de guardar.",
      "O acesso à câmara está desativado",
      "Cancelar espera",
      "Descartar",
      "Descartar alterações?",
      "Padrão alimentar",
      "O padrão alimentar controla os alimentos compatíveis. O estilo do plano dá forma às sugestões de refeições; nenhum deles altera as salvaguardas contra as alergias.",
      "Encerrar chamada",
      "Continue a editar",
      "Transcrição da chamada em direto · pausar para enviar",
      "O acesso ao microfone está desativado. Active-o nas definições do sistema para adicionar peso por voz; a introdução manual permanece disponível.",
      "Abrir {label}",
      "Pausar chamada em direto",
      "Estilo de plano",
      "Preparando a sua resposta…",
      "Raciocínio",
      "Denunciar resposta",
      "Denunciar esta resposta de IA?",
      "Denunciar resposta insegura ou ofensiva",
      "Retomar chamada em direto",
      "Pesquisando o seu contexto BIL…",
      "Iniciar chamada em direto",
      "Ainda falta",
      "Obrigado – esta resposta foi reportada para revisão de segurança.",
      "A câmara abre apenas para o código de barras ou fotografia da refeição selecionada. BIL não solicita acesso no arranque.",
      "A resposta não foi concluída. Tente novamente.",
      "Utilize-o para conteúdo inseguro, ofensivo, odioso, sexual, enganador ou de outra forma prejudicial. BIL regista o ID da resposta e a categoria de segurança, e não a sua pergunta ou o texto da resposta.",
      "A voz permanece neste dispositivo",
      "Porque é que BIL respondeu desta forma",
      "Escrever as suas palavras · faça uma pausa para enviar",
      "Tem alterações não guardadas.",
      "O seu dispositivo transforma a fala em texto. Apenas este texto reconhecido pode ser enviado para Gemini.",
    ],
    "ur": <String>[
      "اس کارروائی کے لیے کیمرے کی اجازت دیں؟",
      "اس کارروائی کے لیے صوتی ان پٹ کی اجازت دیں؟",
      "جواب پر اعتماد: {confidence}",
      "BIL آپ کے بار کوڈ یا کھانے کی تصویر کیپچر کا انتخاب کرنے کے بعد ہی کیمرہ استعمال کرتا ہے۔ سسٹم کی ترتیبات میں کیمرے تک رسائی کو فعال کریں، یا دستی اندراج کے ساتھ جاری رکھیں۔",
      "BIL آپ کے آواز کے وزن کے اندراج کا انتخاب کرنے کے بعد ہی سننا شروع ہوتا ہے۔ محفوظ کرنے سے پہلے تسلیم شدہ قدر کا جائزہ لیں۔",
      "کیمرے تک رسائی بند ہے۔",
      "انتظار منسوخ کریں۔",
      "رد کر دیں۔",
      "تبدیلیوں کو مسترد کریں؟",
      "کھانے کا نمونہ",
      "کھانے کا انداز ہم آہنگ کھانے کو کنٹرول کرتا ہے۔ پلان اسٹائل کھانے کی تجاویز کو شکل دیتا ہے۔ نہ ہی الرجی کے تحفظات کو تبدیل کرتا ہے۔",
      "کال ختم کریں۔",
      "ترمیم کرتے رہیں",
      "لائیو کال ٹرانسکرپٹ · بھیجنے کے لیے موقوف کریں۔",
      "مائیکروفون تک رسائی بند ہے۔ آواز کے ذریعے وزن بڑھانے کے لیے اسے سسٹم کی ترتیبات میں فعال کریں۔ دستی اندراج دستیاب ہے۔",
      "کھولیں {label}",
      "لائیو کال موقوف کریں۔",
      "منصوبہ بندی کا انداز",
      "آپ کا جواب تیار ہو رہا ہے…",
      "استدلال",
      "جواب کی اطلاع دیں۔",
      "اس AI جواب کی اطلاع دیں؟",
      "غیر محفوظ یا جارحانہ جواب کی اطلاع دیں۔",
      "لائیو کال دوبارہ شروع کریں۔",
      "آپ کا BIL سیاق و سباق تلاش کیا جا رہا ہے…",
      "لائیو کال شروع کریں۔",
      "ابھی بھی نامکمل",
      "شکریہ — یہ جواب حفاظتی جائزہ کے لیے رپورٹ کیا گیا تھا۔",
      "کیمرہ صرف آپ کی منتخب کردہ بارکوڈ یا کھانے کی تصویر کے لیے کھلتا ہے۔ BIL آغاز پر رسائی کی درخواست نہیں کرتا ہے۔",
      "جواب مکمل نہیں ہوا۔ دوبارہ کوشش کریں۔",
      "اسے غیر محفوظ، جارحانہ، نفرت انگیز، جنسی، گمراہ کن، یا بصورت دیگر نقصان دہ مواد کے لیے استعمال کریں۔ BIL جوابی ID اور حفاظتی زمرہ کو ریکارڈ کرتا ہے، نہ کہ آپ کے سوال یا جواب کا متن۔",
      "آواز اس آلہ پر رہتی ہے۔",
      "کیوں BIL نے اس طرح جواب دیا۔",
      "اپنے الفاظ لکھنا · بھیجنے کے لیے وقفہ کریں۔",
      "آپ کے پاس غیر محفوظ شدہ تبدیلیاں ہیں۔",
      "آپ کا آلہ تقریر کو متن میں بدل دیتا ہے۔ صرف وہی تسلیم شدہ متن Gemini پر بھیجا جا سکتا ہے۔",
    ],
    "fa": <String>[
      "دوربین برای این عمل مجاز است؟",
      "ورودی صوتی برای این عمل مجاز است؟",
      "اطمینان پاسخ: {confidence}",
      "BIL فقط پس از انتخاب بارکد یا عکس گرفتن از غذا از دوربین استفاده می کند. دسترسی به دوربین را در تنظیمات سیستم فعال کنید یا با ورود دستی ادامه دهید.",
      "BIL فقط پس از انتخاب ورودی وزن صدا شروع به گوش دادن می کند. قبل از ذخیره، مقدار شناسایی شده را مرور کنید.",
      "دسترسی به دوربین خاموش است",
      "لغو انتظار",
      "دور انداختن",
      "از تغییرات صرفنظر شود؟",
      "الگوی غذا خوردن",
      "الگوی غذا خوردن غذاهای سازگار را کنترل می کند. سبک طرح پیشنهادات غذایی را شکل می دهد. هیچ یک از اقدامات حفاظتی آلرژی را تغییر نمی دهد.",
      "پایان تماس",
      "به ویرایش ادامه دهید",
      "رونوشت تماس زنده · مکث برای ارسال",
      "دسترسی به میکروفون خاموش است. آن را در تنظیمات سیستم فعال کنید تا وزن را با صدا اضافه کنید. ورود دستی در دسترس باقی می ماند.",
      "{label} را باز کنید",
      "مکث تماس زنده",
      "سبک طرح",
      "در حال آماده سازی پاسخ شما…",
      "استدلال",
      "پاسخ را گزارش کنید",
      "این پاسخ هوش مصنوعی را گزارش کنید؟",
      "پاسخ ناامن یا توهین آمیز را گزارش دهید",
      "از سرگیری تماس زنده",
      "در حال جستجوی زمینه BIL شما…",
      "شروع تماس زنده",
      "هنوز ناقص است",
      "با تشکر - این پاسخ برای بررسی ایمنی گزارش شد.",
      "دوربین فقط برای بارکد یا عکس غذایی که انتخاب کرده اید باز می شود. BIL هنگام راه اندازی درخواست دسترسی نمی کند.",
      "پاسخ کامل نشد. دوباره امتحان کنید.",
      "از این برای محتوای ناامن، توهین‌آمیز، نفرت‌انگیز، جنسی، فریبنده یا مضر استفاده کنید. BIL شناسه پاسخ و دسته ایمنی را ثبت می کند، نه سوال شما یا متن پاسخ را.",
      "صدا در این دستگاه باقی می ماند",
      "چرا BIL اینگونه پاسخ داد",
      "نوشتن کلمات خود · مکث برای ارسال",
      "شما تغییرات ذخیره نشده ای دارید.",
      "دستگاه شما گفتار را به متن تبدیل می کند. فقط آن متن شناسایی شده را می توان به Gemini ارسال کرد.",
    ],
    "hi": <String>[
      "इस क्रिया के लिए कैमरे की अनुमति दें?",
      "इस क्रिया के लिए ध्वनि इनपुट की अनुमति दें?",
      "उत्तर का भरोसा: {confidence}",
      "BIL आपके द्वारा बारकोड या भोजन-फोटो कैप्चर चुनने के बाद ही कैमरे का उपयोग करता है। सिस्टम सेटिंग्स में कैमरा एक्सेस सक्षम करें, या मैन्युअल प्रविष्टि जारी रखें।",
      "BIL आपके द्वारा वॉयस वेट एंट्री चुनने के बाद ही सुनना शुरू होता है। सहेजने से पहले मान्यता प्राप्त मूल्य की समीक्षा करें।",
      "कैमरा पहुंच बंद है",
      "प्रतीक्षा रद्द करें",
      "त्यागें",
      "परिवर्तन त्यागें?",
      "खाने का पैटर्न",
      "खाने का पैटर्न संगत खाद्य पदार्थों को नियंत्रित करता है। योजना शैली भोजन सुझावों को आकार देती है; न ही एलर्जी सुरक्षा उपाय बदलता है।",
      "कॉल समाप्त करें",
      "संपादन करते रहें",
      "लाइव कॉल ट्रांस्क्रिप्ट · भेजने के लिए रुकें",
      "माइक्रोफ़ोन पहुंच बंद है. आवाज द्वारा वजन जोड़ने के लिए इसे सिस्टम सेटिंग्स में सक्षम करें; मैन्युअल प्रविष्टि उपलब्ध रहती है।",
      "{label} खोलें",
      "लाइव कॉल रोकें",
      "योजना शैली",
      "आपका उत्तर तैयार किया जा रहा है...",
      "तर्क",
      "उत्तर रिपोर्ट करें",
      "इस AI उत्तर की रिपोर्ट करें?",
      "असुरक्षित या आपत्तिजनक उत्तर की रिपोर्ट करें",
      "लाइव कॉल फिर से शुरू करें",
      "आपका BIL संदर्भ खोजा जा रहा है...",
      "लाइव कॉल प्रारंभ करें",
      "अभी भी अनुपलब्ध",
      "धन्यवाद - यह उत्तर सुरक्षा समीक्षा के लिए रिपोर्ट किया गया था।",
      "कैमरा केवल आपके द्वारा चयनित बारकोड या भोजन फ़ोटो के लिए खुलता है। BIL स्टार्टअप पर पहुंच का अनुरोध नहीं करता है।",
      "उत्तर पूरा नहीं हुआ. पुनः प्रयास करें।",
      "इसका उपयोग असुरक्षित, आपत्तिजनक, घृणित, यौन, भ्रामक या अन्यथा हानिकारक सामग्री के लिए करें। BIL प्रतिक्रिया आईडी और सुरक्षा श्रेणी को रिकॉर्ड करता है, न कि आपके प्रश्न या उत्तर पाठ को।",
      "आवाज इस डिवाइस पर रहती है",
      "BIL ने इस तरह उत्तर क्यों दिया",
      "अपने शब्द लिखना · भेजने के लिए रुकें",
      "आपके पास सहेजे नहीं गए परिवर्तन हैं.",
      "आपका उपकरण वाणी को पाठ में बदल देता है। केवल वह मान्यता प्राप्त टेक्स्ट ही Gemini पर भेजा जा सकता है।",
    ],
    "id": <String>[
      "Izinkan kamera untuk tindakan ini?",
      "Izinkan masukan suara untuk tindakan ini?",
      "Tingkat keyakinan jawaban: {confidence}",
      "BIL hanya menggunakan kamera setelah Anda memilih kode batang atau pengambilan foto makanan. Aktifkan akses kamera di pengaturan sistem, atau lanjutkan dengan entri manual.",
      "BIL mulai mendengarkan hanya setelah Anda memilih entri bobot suara. Tinjau nilai yang diakui sebelum disimpan.",
      "Akses kamera tidak aktif",
      "Batalkan menunggu",
      "Buang",
      "Hapus perubahan?",
      "Pola makan",
      "Pola makan mengontrol makanan yang cocok. Rencanakan gaya bentuk saran makanan; tidak ada yang mengubah perlindungan alergi.",
      "Akhiri panggilan",
      "Lanjutkan mengedit",
      "Transkrip panggilan langsung · jeda untuk mengirim",
      "Akses mikrofon tidak aktif. Aktifkan di pengaturan sistem untuk menambah bobot dengan suara; entri manual tetap tersedia.",
      "Buka {label}",
      "Jeda panggilan langsung",
      "Gaya rencana",
      "Mempersiapkan jawaban Anda…",
      "Penalaran",
      "Laporkan jawaban",
      "Laporkan jawaban AI ini?",
      "Laporkan jawaban yang tidak aman atau menyinggung",
      "Lanjutkan panggilan langsung",
      "Menelusuri konteks BIL Anda…",
      "Mulai panggilan langsung",
      "Masih belum ada",
      "Terima kasih — jawaban ini dilaporkan untuk tinjauan keamanan.",
      "Kamera terbuka hanya untuk barcode atau foto makanan yang Anda pilih. BIL tidak meminta akses saat startup.",
      "Jawabannya tidak lengkap. Coba lagi.",
      "Gunakan ini untuk konten yang tidak aman, menyinggung, penuh kebencian, seksual, menipu, atau berbahaya. BIL mencatat ID respons dan kategori keamanan, bukan pertanyaan atau teks jawaban Anda.",
      "Suara tetap ada di perangkat ini",
      "Mengapa BIL menjawab seperti ini",
      "Menulis kata-kata Anda · jeda untuk mengirim",
      "Anda memiliki perubahan yang belum disimpan.",
      "Perangkat Anda mengubah ucapan menjadi teks. Hanya teks yang dikenali tersebut yang dapat dikirim ke Gemini.",
    ],
    "ms": <String>[
      "Benarkan kamera untuk tindakan ini?",
      "Benarkan input suara untuk tindakan ini?",
      "Tahap keyakinan jawapan: {confidence}",
      "BIL hanya menggunakan kamera selepas anda memilih kod bar atau tangkapan foto makanan. Dayakan akses kamera dalam tetapan sistem, atau teruskan dengan kemasukan manual.",
      "BIL mula mendengar hanya selepas anda memilih masukan berat suara. Semak nilai yang diiktiraf sebelum menyimpan.",
      "Akses kamera dimatikan",
      "Batal menunggu",
      "Buang",
      "Buang perubahan?",
      "Corak pemakanan",
      "Corak pemakanan mengawal makanan yang serasi. Merancang gaya bentuk cadangan hidangan; tidak mengubah perlindungan alahan.",
      "Tamatkan panggilan",
      "Teruskan mengedit",
      "Transkrip panggilan langsung · jeda untuk menghantar",
      "Akses mikrofon dimatikan. Dayakannya dalam tetapan sistem untuk menambah berat melalui suara; kemasukan manual masih tersedia.",
      "Buka {label}",
      "Jeda panggilan langsung",
      "Gaya rancangan",
      "Menyediakan jawapan anda…",
      "Penaakulan",
      "Laporkan jawapan",
      "Laporkan jawapan AI ini?",
      "Laporkan jawapan yang tidak selamat atau menyinggung perasaan",
      "Sambung semula panggilan langsung",
      "Mencari konteks BIL anda…",
      "Mulakan panggilan langsung",
      "Masih belum lengkap",
      "Terima kasih — jawapan ini dilaporkan untuk semakan keselamatan.",
      "Kamera dibuka hanya untuk kod bar atau foto makanan yang anda pilih. BIL tidak meminta akses pada permulaan.",
      "Jawapannya tidak lengkap. Cuba lagi.",
      "Gunakan ini untuk kandungan yang tidak selamat, menyinggung perasaan, kebencian, seksual, memperdaya atau sebaliknya berbahaya. BIL merekodkan ID respons dan kategori keselamatan, bukan soalan anda atau teks jawapan.",
      "Suara kekal pada peranti ini",
      "Mengapa BIL menjawab dengan cara ini",
      "Menulis perkataan anda · jeda untuk menghantar",
      "Anda mempunyai perubahan yang belum disimpan.",
      "Peranti anda menukar pertuturan kepada teks. Hanya teks yang dikenali itu boleh dihantar ke Gemini.",
    ],
    "ja": <String>[
      "このアクションに対してカメラを許可しますか?",
      "このアクションに対して音声入力を許可しますか?",
      "回答の信頼度: {confidence}",
      "BIL は、バーコードまたは食事写真のキャプチャを選択した後にのみカメラを使用します。システム設定でカメラへのアクセスを有効にするか、手動入力を続行します。",
      "BIL は、音声ウェイトの入力を選択した後にのみ聞き始めます。保存する前に、認識された値を確認してください。",
      "カメラアクセスがオフになっています",
      "待機をキャンセル",
      "廃棄する",
      "変更を破棄しますか?",
      "食事のパターン",
      "食事パターンは相性の良い食べ物をコントロールします。プランスタイルは食事の提案を形作ります。どちらもアレルギー予防策を変更しません。",
      "通話を終了する",
      "編集を続ける",
      "ライブ通話のトランスクリプト · 送信のために一時停止します",
      "マイクアクセスがオフになっています。システム設定で有効にすると、音声による重みが追加されます。手動入力は引き続き利用可能です。",
      "{label} を開く",
      "ライブ通話を一時停止する",
      "プランスタイル",
      "回答を準備しています…",
      "推論",
      "回答を報告する",
      "この AI の回答を報告しますか?",
      "安全でないまたは攻撃的な回答を報告する",
      "ライブ通話を再開する",
      "BIL コンテキストを検索しています…",
      "ライブ通話を開始する",
      "不足している情報",
      "ありがとう — この回答は安全性レビューのために報告されました。",
      "カメラは、選択したバーコードまたは食事の写真に対してのみ開きます。 BIL は起動時にアクセスを要求しません。",
      "返信が完了しませんでした。もう一度やり直してください。",
      "これは、安全でない、攻撃的、憎悪に満ちた、性的、欺瞞的、またはその他の有害なコンテンツに使用してください。 BIL は、質問や回答テキストではなく、回答 ID と安​​全性カテゴリを記録します。",
      "音声はこのデバイスに残ります",
      "BIL がこのように答えた理由",
      "言葉を書く · 送信するために一時停止する",
      "未保存の変更があります。",
      "デバイスは音声をテキストに変換します。認識されたテキストのみを Gemini に送信できます。",
    ],
    "ko": <String>[
      "이 작업에 카메라를 허용하시겠습니까?",
      "이 작업에 음성 입력을 허용하시겠습니까?",
      "답변 신뢰도: {confidence}",
      "BIL에서는 바코드 또는 식사 사진 캡처를 선택한 후에만 카메라를 사용합니다. 시스템 설정에서 카메라 액세스를 활성화하거나 수동 입력을 계속하세요.",
      "BIL은 음성 가중치 항목을 선택한 후에만 듣기를 시작합니다. 저장하기 전에 인식된 값을 검토하세요.",
      "카메라 액세스가 사용 중지되었습니다.",
      "대기 취소",
      "폐기",
      "변경사항을 삭제하시겠습니까?",
      "식사 패턴",
      "먹는 패턴은 호환 가능한 음식을 제어합니다. 계획 스타일은 식사 제안을 형성합니다. 알레르기 보호 조치도 변경되지 않습니다.",
      "통화 종료",
      "계속 수정하세요",
      "실시간 통화 기록 · 보내기 위해 일시중지",
      "마이크 액세스가 꺼져 있습니다. 음성으로 가중치를 추가하려면 시스템 설정에서 활성화하세요. 수동 입력은 계속 가능합니다.",
      "{label} 열기",
      "실시간 통화 일시중지",
      "계획 스타일",
      "답변 준비 중…",
      "추론",
      "답변 신고",
      "이 AI 답변을 신고하시겠습니까?",
      "안전하지 않거나 불쾌한 답변 신고",
      "실시간 통화 재개",
      "BIL 컨텍스트 검색 중…",
      "실시간 통화 시작",
      "아직 부족한 정보",
      "감사합니다. 이 답변은 안전 검토를 위해 보고되었습니다.",
      "선택한 바코드 또는 식사 사진에 대해서만 카메라가 열립니다. BIL은 시작 시 액세스를 요청하지 않습니다.",
      "답변이 완료되지 않았습니다. 다시 시도해 보세요.",
      "안전하지 않거나 모욕적이거나 증오심이 많거나 성적이거나 기만적이거나 기타 유해한 콘텐츠에 이 옵션을 사용하세요. BIL은 질문이나 답변 텍스트가 아닌 응답 ID와 안전 카테고리를 기록합니다.",
      "음성은 이 기기에 유지됩니다.",
      "BIL이 이렇게 대답한 이유",
      "단어 쓰기 · 보내기를 잠시 멈추세요",
      "저장되지 않은 변경사항이 있습니다.",
      "장치는 음성을 텍스트로 변환합니다. 인식된 텍스트만 Gemini로 보낼 수 있습니다.",
    ],
    "zh-Hans": <String>[
      "允许摄像头执行此操作吗？",
      "允许进行此操作的语音输入吗？",
      "回答可信度：{confidence}",
      "BIL 仅在您选择条形码或餐食照片捕获后才使用相机。在系统设置中启用摄像头访问，或继续手动输入。",
      "BIL 仅在您选择语音权重输入后才开始收听。保存前检查已识别的值。",
      "相机访问已关闭",
      "取消等待",
      "丢弃",
      "放弃更改？",
      "饮食模式",
      "饮食模式控制相容的食物。计划风格决定膳食建议；两者都不会改变过敏保障措施。",
      "结束通话",
      "继续编辑",
      "实时通话记录 · 暂停发送",
      "麦克风访问已关闭。在系统设置中启用语音增重；手动输入仍然可用。",
      "打开{label}",
      "暂停实时通话",
      "方案风格",
      "正在准备你的答案...",
      "推理",
      "报告答案",
      "举报这个人工智能答案吗？",
      "报告不安全或冒犯性的答案",
      "恢复实时通话",
      "搜索您的 BIL 上下文...",
      "开始实时通话",
      "仍缺少",
      "谢谢——这个答案已报告用于安全审查。",
      "相机仅针对您选择的条形码或餐食照片打开。 BIL 在启动时不请求访问。",
      "回复未完成。再试一次。",
      "将此用于不安全、攻击性、仇恨、性、欺骗性或其他有害内容。 BIL 记录响应 ID 和安全类别，而不是您的问题或答案文本。",
      "语音保留在此设备上",
      "为什么 BIL 这样回答",
      "写下你的话 · 暂停发送",
      "您有未保存的更改。",
      "您的设备将语音转换为文本。只有识别出的文本才能发送到 Gemini。",
    ],
    "zh-Hant": <String>[
      "允許攝影機執行此操作嗎？",
      "允許進行此操作的語音輸入嗎？",
      "回答可信度：{confidence}",
      "BIL 僅在您選擇條碼或餐點照片擷取後才使用相機。在系統設定中啟用攝影機訪問，或繼續手動輸入。",
      "BIL 僅在您選擇語音權重輸入後才開始收聽。儲存前檢查已識別的值。",
      "相機訪問已關閉",
      "取消等待",
      "丟棄",
      "放棄更改？",
      "飲食模式",
      "飲食模式控制相容的食物。計劃風格決定膳食建議；兩者都不會改變過敏保障措施。",
      "結束通話",
      "繼續編輯",
      "即時通話記錄 · 暫停發送",
      "麥克風存取已關閉。在系統設定中啟用語音增重；手動輸入仍然可用。",
      "開啟{label}",
      "暫停即時通話",
      "方案風格",
      "正在準備你的答案...",
      "推理",
      "報告答案",
      "檢舉這個人工智慧答案嗎？",
      "報告不安全或冒犯性的答案",
      "恢復即時通話",
      "搜尋您的 BIL 上下文...",
      "開始即時通話",
      "仍缺少",
      "謝謝——這個答案已報告用於安全審查。",
      "相機僅針對您選擇的條碼或餐點照片開啟。 BIL 在啟動時不請求存取。",
      "回復未完成。再試一次。",
      "將此用於不安全、攻擊性、仇恨、性、欺騙性或其他有害內容。 BIL 記錄回應 ID 和安全類別，而不是您的問題或答案文字。",
      "語音保留在此設備上",
      "為什麼 BIL 這樣回答",
      "寫下你的話 · 暫停發送",
      "您有未儲存的變更。",
      "您的裝置將語音轉換為文字。只有辨識出的文字才能傳送到 Gemini。",
    ],
    "ru": <String>[
      "Разрешить камеру для этого действия?",
      "Разрешить голосовой ввод для этого действия?",
      "Уверенность в ответе: {confidence}",
      "BIL использует камеру только после того, как вы выберете захват штрих-кода или фотографии еды. Включите доступ к камере в настройках системы или продолжите ввод вручную.",
      "BIL начнет слушать только после того, как вы выберете ввод веса голоса. Перед сохранением просмотрите распознанное значение.",
      "Доступ к камере отключен",
      "Отменить ожидание",
      "Отбросить",
      "Отменить изменения?",
      "Режим питания",
      "Режим питания контролирует совместимые продукты. Стиль планирования формирует предложения по еде; ни один из них не меняет меры защиты от аллергии.",
      "Завершить вызов",
      "Продолжайте редактировать",
      "Расшифровка разговора в реальном времени · пауза для отправки",
      "Доступ к микрофону отключен. Включите его в настройках системы, чтобы добавлять вес голосом; ручной ввод остается доступным.",
      "Открыть {label}",
      "Приостановить прямой эфир",
      "Стиль плана",
      "Готовим ответ…",
      "Рассуждение",
      "Сообщить об ответе",
      "Пожаловаться на этот ответ ИИ?",
      "Сообщить о небезопасном или оскорбительном ответе",
      "Возобновить прямой эфир",
      "Поиск контекста BIL…",
      "Начать прямой вызов",
      "Всё ещё отсутствует",
      "Спасибо! Этот ответ отправлен на проверку безопасности.",
      "Камера открывается только для выбранного вами штрих-кода или фотографии еды. BIL не запрашивает доступ при запуске.",
      "Ответ не был завершен. Попробуйте еще раз.",
      "Используйте это для небезопасного, оскорбительного, разжигающего ненависть, сексуального, вводящего в заблуждение или иного вредного контента. BIL записывает идентификатор ответа и категорию безопасности, а не ваш вопрос или текст ответа.",
      "Голос останется на этом устройстве",
      "Почему BIL ответил именно так",
      "Написание слов · пауза для отправки",
      "У вас есть несохраненные изменения.",
      "Ваше устройство преобразует речь в текст. Только этот распознанный текст можно отправить на адрес Gemini.",
    ],
    "bn": <String>[
      "এই অ্যাকশনের জন্য ক্যামেরাকে অনুমতি দেবেন?",
      "এই ক্রিয়াকলাপের জন্য ভয়েস ইনপুটের অনুমতি দেবেন?",
      "উত্তরের নির্ভরযোগ্যতা: {confidence}",
      "BIL আপনি বারকোড বা খাবার-ফটো ক্যাপচার বেছে নেওয়ার পরেই কেবল ক্যামেরা ব্যবহার করে৷ সিস্টেম সেটিংসে ক্যামেরা অ্যাক্সেস সক্ষম করুন বা ম্যানুয়াল এন্ট্রি দিয়ে চালিয়ে যান।",
      "BIL আপনি ভয়েস ওয়েট এন্ট্রি বেছে নেওয়ার পরেই শোনা শুরু করে। সংরক্ষণ করার আগে স্বীকৃত মান পর্যালোচনা করুন।",
      "ক্যামেরা অ্যাক্সেস বন্ধ আছে",
      "অপেক্ষা বাতিল করুন",
      "বাতিল করুন",
      "পরিবর্তনগুলি বাতিল করবেন?",
      "খাওয়ার ধরণ",
      "খাওয়ার ধরণ সামঞ্জস্যপূর্ণ খাবার নিয়ন্ত্রণ করে। পরিকল্পনা শৈলী আকৃতি খাবার পরামর্শ; এলার্জি সুরক্ষা ব্যবস্থাও পরিবর্তন করে না।",
      "কল শেষ করুন",
      "সম্পাদনা করতে থাকুন",
      "লাইভ কল ট্রান্সক্রিপ্ট · পাঠাতে বিরতি দিন",
      "মাইক্রোফোন অ্যাক্সেস বন্ধ আছে। ভয়েস দ্বারা ওজন যোগ করতে সিস্টেম সেটিংসে এটি সক্ষম করুন; ম্যানুয়াল এন্ট্রি উপলব্ধ থাকে।",
      "খুলুন {label}",
      "লাইভ কল থামান",
      "পরিকল্পনা শৈলী",
      "আপনার উত্তর প্রস্তুত করা হচ্ছে...",
      "যুক্তি",
      "রিপোর্ট উত্তর",
      "এই AI উত্তর রিপোর্ট?",
      "অনিরাপদ বা আপত্তিকর উত্তর রিপোর্ট করুন",
      "লাইভ কল পুনরায় শুরু করুন",
      "আপনার BIL প্রসঙ্গ অনুসন্ধান করা হচ্ছে…",
      "লাইভ কল শুরু করুন",
      "এখনও অনুপস্থিত",
      "ধন্যবাদ — এই উত্তর নিরাপত্তা পর্যালোচনার জন্য রিপোর্ট করা হয়েছে।",
      "ক্যামেরাটি শুধুমাত্র আপনার নির্বাচিত বারকোড বা খাবারের ছবির জন্য খোলে। BIL স্টার্টআপে অ্যাক্সেসের অনুরোধ করে না।",
      "উত্তর সম্পূর্ণ হয়নি। আবার চেষ্টা করুন",
      "এটি অনিরাপদ, আপত্তিকর, ঘৃণ্য, যৌন, প্রতারণামূলক বা অন্যথায় ক্ষতিকারক সামগ্রীর জন্য ব্যবহার করুন। BIL রেসপন্স আইডি এবং নিরাপত্তা বিভাগ রেকর্ড করে, আপনার প্রশ্ন বা উত্তরের পাঠ্য নয়।",
      "ভয়েস এই ডিভাইসে থেকে যায়",
      "কেন BIL এইভাবে উত্তর দিয়েছে",
      "আপনার শব্দ লেখা · পাঠাতে বিরতি",
      "আপনার অসংরক্ষিত পরিবর্তন আছে.",
      "আপনার ডিভাইস বক্তৃতাকে পাঠ্যে পরিণত করে। শুধুমাত্র সেই স্বীকৃত টেক্সট Gemini এ পাঠানো যাবে।",
    ],
    "vi": <String>[
      "Cho phép máy ảnh thực hiện hành động này?",
      "Cho phép nhập bằng giọng nói cho tác vụ này?",
      "Độ tin cậy của câu trả lời: {confidence}",
      "BIL chỉ sử dụng máy ảnh sau khi bạn chọn mã vạch hoặc chụp ảnh bữa ăn. Cho phép truy cập máy ảnh trong cài đặt hệ thống hoặc tiếp tục nhập thủ công.",
      "BIL chỉ bắt đầu nghe sau khi bạn chọn mục nhập trọng lượng giọng nói. Xem lại giá trị được công nhận trước khi lưu.",
      "Quyền truy cập vào máy ảnh đang tắt",
      "Hủy chờ đợi",
      "Loại bỏ",
      "Hủy thay đổi?",
      "Kiểu ăn uống",
      "Mô hình ăn uống kiểm soát các loại thực phẩm tương thích. Phong cách lập kế hoạch định hình gợi ý bữa ăn; không thay đổi các biện pháp bảo vệ chống dị ứng.",
      "Kết thúc cuộc gọi",
      "Tiếp tục chỉnh sửa",
      "Bản ghi cuộc gọi trực tiếp · tạm dừng để gửi",
      "Quyền truy cập micrô bị tắt. Kích hoạt nó trong cài đặt hệ thống để thêm trọng lượng bằng giọng nói; nhập thủ công vẫn có sẵn.",
      "Mở {label}",
      "Tạm dừng cuộc gọi trực tiếp",
      "phong cách kế hoạch",
      "Đang chuẩn bị câu trả lời của bạn…",
      "Lý luận",
      "Báo cáo câu trả lời",
      "Báo cáo câu trả lời AI này?",
      "Báo cáo câu trả lời không an toàn hoặc xúc phạm",
      "Tiếp tục cuộc gọi trực tiếp",
      "Đang tìm kiếm ngữ cảnh BIL của bạn…",
      "Bắt đầu cuộc gọi trực tiếp",
      "Vẫn còn thiếu",
      "Cảm ơn - câu trả lời này đã được báo cáo để xem xét an toàn.",
      "Máy ảnh chỉ mở cho mã vạch hoặc ảnh bữa ăn bạn đã chọn. BIL không yêu cầu quyền truy cập khi khởi động.",
      "Câu trả lời không hoàn thành. Hãy thử lại.",
      "Sử dụng điều này cho nội dung không an toàn, xúc phạm, hận thù, tình dục, lừa đảo hoặc có hại. BIL ghi lại ID phản hồi và danh mục an toàn chứ không phải câu hỏi hoặc văn bản câu trả lời của bạn.",
      "Giọng nói vẫn còn trên thiết bị này",
      "Tại sao BIL lại trả lời theo cách này",
      "Viết lời của bạn · tạm dừng để gửi",
      "Bạn có những thay đổi chưa được lưu.",
      "Thiết bị của bạn chuyển lời nói thành văn bản. Chỉ văn bản được nhận dạng đó mới có thể được gửi tới Gemini.",
    ],
    "th": <String>[
      "อนุญาตให้กล้องดำเนินการนี้ไหม",
      "อนุญาตให้ป้อนข้อมูลด้วยเสียงสำหรับการดำเนินการนี้หรือไม่",
      "ความมั่นใจของคำตอบ: {confidence}",
      "BIL ใช้กล้องเฉพาะหลังจากที่คุณเลือกบาร์โค้ดหรือการถ่ายภาพมื้ออาหารเท่านั้น เปิดใช้งานการเข้าถึงกล้องในการตั้งค่าระบบหรือดำเนินการต่อด้วยการป้อนข้อมูลด้วยตนเอง",
      "BIL เริ่มฟังหลังจากที่คุณเลือกรายการน้ำหนักเสียงเท่านั้น ตรวจสอบค่าที่รับรู้ก่อนบันทึก",
      "การเข้าถึงกล้องปิดอยู่",
      "ยกเลิกการรอ",
      "ทิ้ง",
      "ยกเลิกการเปลี่ยนแปลงใช่ไหม",
      "รูปแบบการกิน",
      "รูปแบบการกินจะควบคุมอาหารที่เข้ากันได้ รูปแบบการวางแผนคำแนะนำมื้ออาหาร ไม่มีการเปลี่ยนแปลงการป้องกันโรคภูมิแพ้",
      "วางสาย",
      "แก้ไขต่อไป",
      "บันทึกการโทรสด · หยุดชั่วคราวเพื่อส่ง",
      "การเข้าถึงไมโครโฟนปิดอยู่ เปิดใช้งานในการตั้งค่าระบบเพื่อเพิ่มน้ำหนักด้วยเสียง การป้อนด้วยตนเองยังคงมีอยู่",
      "เปิด {label}",
      "หยุดการโทรสดชั่วคราว",
      "แบบแผน",
      "กำลังเตรียมคำตอบของคุณ...",
      "การใช้เหตุผล",
      "รายงานคำตอบ",
      "รายงานคำตอบ AI นี้หรือไม่",
      "รายงานคำตอบที่ไม่ปลอดภัยหรือไม่เหมาะสม",
      "โทรสดต่อ",
      "กำลังค้นหาบริบท BIL ของคุณ...",
      "เริ่มการโทรสด",
      "ยังขาดอยู่",
      "ขอบคุณ — คำตอบนี้ถูกรายงานเพื่อการตรวจสอบด้านความปลอดภัย",
      "กล้องจะเปิดเฉพาะบาร์โค้ดหรือภาพถ่ายอาหารที่คุณเลือกเท่านั้น BIL ไม่ร้องขอการเข้าถึงเมื่อเริ่มต้น",
      "การตอบกลับไม่เสร็จสมบูรณ์ ลองอีกครั้ง",
      "ใช้สิ่งนี้สำหรับเนื้อหาที่ไม่ปลอดภัย น่ารังเกียจ แสดงความเกลียดชัง เรื่องเพศ หลอกลวง หรือเป็นอันตราย BIL บันทึกรหัสคำตอบและหมวดหมู่ความปลอดภัย ไม่ใช่คำถามหรือข้อความคำตอบของคุณ",
      "เสียงจะยังคงอยู่ในอุปกรณ์นี้",
      "ทำไม BIL จึงตอบแบบนี้",
      "การเขียนคำของคุณ · หยุดชั่วคราวเพื่อส่ง",
      "คุณมีการเปลี่ยนแปลงที่ยังไม่ได้บันทึก",
      "อุปกรณ์ของคุณเปลี่ยนคำพูดเป็นข้อความ เฉพาะข้อความที่ได้รับการยอมรับเท่านั้นที่สามารถส่งไปยัง Gemini",
    ],
    "pl": <String>[
      "Zezwolić kamerze na tę czynność?",
      "Zezwolić na wprowadzanie głosowe tej czynności?",
      "Pewność odpowiedzi: {confidence}",
      "BIL używa aparatu dopiero po wybraniu opcji rejestrowania kodu kreskowego lub robienia zdjęć posiłków. Włącz dostęp do kamery w ustawieniach systemu lub kontynuuj wprowadzanie ręczne.",
      "BIL rozpoczyna słuchanie dopiero po wybraniu wprowadzania wagi głosu. Przed zapisaniem sprawdź rozpoznaną wartość.",
      "Dostęp do aparatu jest wyłączony",
      "Anuluj oczekiwanie",
      "Odrzuć",
      "Odrzucić zmiany?",
      "Wzór jedzenia",
      "Wzorzec odżywiania kontroluje zgodną żywność. Styl planu kształtuje sugestie posiłków; żadne z nich nie zmienia zabezpieczeń dla alergików.",
      "Zakończ połączenie",
      "Edytuj dalej",
      "Transkrypcja rozmów na żywo · wstrzymaj, aby wysłać",
      "Dostęp do mikrofonu jest wyłączony. Włącz tę opcję w ustawieniach systemu, aby dodawać wagę za pomocą głosu; ręczne wprowadzanie pozostaje dostępne.",
      "Otwórz {label}",
      "Wstrzymaj połączenie na żywo",
      "Styl planu",
      "Przygotowuję odpowiedź…",
      "Rozumowanie",
      "Zgłoś odpowiedź",
      "Zgłosić tę odpowiedź AI?",
      "Zgłoś niebezpieczną lub obraźliwą odpowiedź",
      "Wznów połączenie na żywo",
      "Przeszukuję kontekst BIL…",
      "Rozpocznij rozmowę na żywo",
      "Nadal brakuje",
      "Dziękujemy — ta odpowiedź została zgłoszona do sprawdzenia pod kątem bezpieczeństwa.",
      "Aparat otwiera się tylko dla wybranego zdjęcia z kodem kreskowym lub posiłkiem. BIL nie żąda dostępu przy uruchomieniu.",
      "Odpowiedź nie została ukończona. Spróbuj ponownie.",
      "Użyj tej opcji w przypadku treści niebezpiecznych, obraźliwych, nienawistnych, seksualnych, zwodniczych lub w inny sposób szkodliwych. BIL rejestruje identyfikator odpowiedzi i kategorię bezpieczeństwa, a nie Twoje pytanie lub tekst odpowiedzi.",
      "Głos pozostanie na tym urządzeniu",
      "Dlaczego BIL odpowiedział w ten sposób",
      "Wpisywanie słów · pauza, aby wysłać",
      "Masz niezapisane zmiany.",
      "Twoje urządzenie zamienia mowę na tekst. Tylko rozpoznany tekst można wysłać do Gemini.",
    ],
    "nl": <String>[
      "Camera toestaan ​​voor deze actie?",
      "Spraakinvoer toestaan voor deze actie?",
      "Betrouwbaarheid van antwoord: {confidence}",
      "BIL gebruikt de camera alleen nadat je hebt gekozen voor het vastleggen van streepjescodes of maaltijdfoto's. Schakel cameratoegang in systeeminstellingen in, of ga door met handmatige invoer.",
      "BIL begint pas te luisteren nadat u de invoer van het stemgewicht hebt gekozen. Controleer de herkende waarde voordat u deze opslaat.",
      "Cameratoegang is uitgeschakeld",
      "Wachten annuleren",
      "Gooi weg",
      "Wijzigingen weggooien?",
      "Eetpatroon",
      "Het eetpatroon controleert compatibele voedingsmiddelen. Planstijl vormt maaltijdsuggesties; geen van beide verandert de allergiewaarborgen.",
      "Beëindig gesprek",
      "Blijf bewerken",
      "Transcript van live oproep · pauzeer om te verzenden",
      "Microfoontoegang is uitgeschakeld. Schakel het in de systeeminstellingen in om met uw stem gewicht toe te voegen; handmatige invoer blijft beschikbaar.",
      "{label} openen",
      "Pauzeer live-oproep",
      "Planstijl",
      "Je antwoord voorbereiden…",
      "Redenering",
      "Rapporteer antwoord",
      "Dit AI-antwoord rapporteren?",
      "Onveilig of aanstootgevend antwoord melden",
      "Live gesprek hervatten",
      "Uw BIL-context doorzoeken…",
      "Livegesprek starten",
      "Ontbreekt nog",
      "Bedankt – dit antwoord is gerapporteerd voor veiligheidsbeoordeling.",
      "De camera wordt alleen geopend voor de streepjescode of maaltijdfoto die u hebt geselecteerd. BIL vraagt ​​geen toegang bij het opstarten.",
      "Het antwoord is niet voltooid. Probeer het opnieuw.",
      "Gebruik dit voor onveilige, aanstootgevende, haatzaaiende, seksuele, bedrieglijke of anderszins schadelijke inhoud. BIL registreert de antwoord-ID en veiligheidscategorie, niet uw vraag of de antwoordtekst.",
      "Stem blijft op dit apparaat",
      "Waarom BIL zo antwoordde",
      "Schrijf uw woorden · pauzeer om te verzenden",
      "U heeft niet-opgeslagen wijzigingen.",
      "Uw apparaat zet spraak om in tekst. Alleen die herkende tekst kan naar Gemini worden verzonden.",
    ],
    "uk": <String>[
      "Дозволити камеру для цієї дії?",
      "Дозволити голосове введення для цієї дії?",
      "Впевненість у відповіді: {confidence}",
      "BIL використовує камеру лише після вибору штрих-коду або зйомки їжі. Увімкніть доступ до камери в налаштуваннях системи або продовжте введення вручну.",
      "BIL починає прослуховувати лише після вибору введення ваги голосу. Перегляньте розпізнане значення перед збереженням.",
      "Доступ до камери вимкнено",
      "Скасувати очікування",
      "Відкинути",
      "Скасувати зміни?",
      "Шаблон харчування",
      "Режим харчування контролює сумісні продукти. Стиль плану формує пропозиції їжі; жодне не змінює гарантій захисту від алергії.",
      "Завершити дзвінок",
      "Продовжуйте редагувати",
      "Стенограма розмови в реальному часі · пауза, щоб надіслати",
      "Доступ до мікрофона вимкнено. Увімкніть його в налаштуваннях системи, щоб додати вагу голосом; введення вручну залишається доступним.",
      "Відкрити {label}",
      "Призупинити живий виклик",
      "Стиль плану",
      "Підготовка вашої відповіді…",
      "Міркування",
      "Повідомити відповідь",
      "Повідомити про цю відповідь ШІ?",
      "Повідомити про небезпечну або образливу відповідь",
      "Відновити живий дзвінок",
      "Пошук у контексті BIL…",
      "Розпочати живий виклик",
      "Досі відсутнє",
      "Дякуємо — цю відповідь надіслано для перевірки безпеки.",
      "Камера відкривається лише для вибраного штрих-коду або фотографії їжі. BIL не запитує доступ під час запуску.",
      "Відповідь не завершена. Спробуйте знову.",
      "Використовуйте це для небезпечного, образливого, ненависті, сексуального, оманливого або іншого шкідливого вмісту. BIL записує ідентифікатор відповіді та категорію безпеки, а не ваше запитання чи текст відповіді.",
      "Голос залишається на цьому пристрої",
      "Чому BIL відповів саме так",
      "Написання слів · пауза, щоб надіслати",
      "У вас є незбережені зміни.",
      "Ваш пристрій перетворює мову на текст. Лише розпізнаний текст можна надіслати на Gemini.",
    ],
  };

  static String? resolve(String english, String localeTag) {
    final normalized = localeTag.replaceAll('_', '-').toLowerCase();
    String? tag;
    for (final candidate in supported) {
      if (candidate.toLowerCase() == normalized) {
        tag = candidate;
        break;
      }
    }
    if (tag == null) {
      final language = normalized.split('-').first;
      final matches = supported
          .where((candidate) => candidate.toLowerCase() == language)
          .toList(growable: false);
      if (matches.length == 1) tag = matches.single;
    }
    if (tag == null) return null;
    final index = sources.indexOf(english);
    if (index < 0) return null;
    return rows[tag]![index];
  }

  static bool get balanced =>
      rows.keys.toSet().containsAll(supported) &&
      supported.containsAll(rows.keys) &&
      rows.values.every(
        (row) =>
            row.length == sources.length &&
            row.every((value) => value.trim().isNotEmpty),
      );
}
