part of 'runtime_copy_next_workspace.dart';

const _nextWorkspaceSupplementalRows0 = <String, List<String>>{
  "ar": [
    "نظرة عامة",
    "صور المنشور",
    "الرئيسية",
    "منشورات غير مكتملة وخاصة",
    "احفظ الملف وأنشئ رمز BIL",
    "سجّل الدخول لفتح مسوداتك الخاصة.",
    "صلاحيات إجراءات المدرب",
    "الإحصاءات",
    "{count} صور",
    "الموافقات",
    "حذف {count} من المسودات؟",
    "حذف المحدد ({count})",
    "إجراءات المسودة",
    "المسودات ({count})",
    "آخر حفظ قبل {count} ي",
    "آخر حفظ قبل {count} س",
    "آخر حفظ قبل {count} د",
    "الإشارات",
    "ستظهر الموافقات والإشارات والتعليقات الجديدة هنا.",
    "لا توجد مسودات محفوظة بعد",
    "إعدادات الإشعارات",
    "الإشعارات غير متاحة",
    "الآن",
    "أُضيفت المكافأة إلى رصيد الذكاء الاصطناعي",
    "احفظ المنشورات غير المكتملة وتابعها هنا لاحقًا.",
    "حُفظت الآن",
    "تحديد",
    "سيؤدي هذا إلى حذف المسودات الخاصة المحددة فقط.",
    "أنت مطّلع على كل جديد",
    "سابقًا",
  ],
  "fr": [
    "Vue d’ensemble",
    "Photos de la publication",
    "Accueil",
    "Publications privées inachevées",
    "Enregistrer le profil et créer le code BIL",
    "Connectez-vous pour ouvrir vos brouillons privés.",
    "Autorisations des actions du coach",
    "Statistiques",
    "Photos : {count}",
    "Approbations",
    "Supprimer {count} brouillons ?",
    "Supprimer la sélection ({count})",
    "Actions sur le brouillon",
    "Brouillons ({count})",
    "Dernière sauvegarde il y a {count} j",
    "Dernière sauvegarde il y a {count} h",
    "Dernière sauvegarde il y a {count} min",
    "Mentions reçues",
    "Les nouvelles approbations, mentions et commentaires apparaîtront ici.",
    "Aucun brouillon enregistré pour le moment",
    "Paramètres des notifications",
    "Les notifications sont indisponibles",
    "Maintenant",
    "Récompense ajoutée à votre solde IA",
    "Enregistrez les publications inachevées pour les reprendre ici plus tard.",
    "Enregistré à l’instant",
    "Sélectionner",
    "Seuls les brouillons privés sélectionnés seront supprimés.",
    "Vous avez tout vu",
    "Plus tôt",
  ],
  "es": [
    "Resumen",
    "Fotos de la publicación",
    "Inicio",
    "Publicaciones privadas sin terminar",
    "Guardar perfil y crear código BIL",
    "Inicia sesión para abrir tus borradores privados.",
    "Permisos de las acciones del entrenador",
    "Estadísticas",
    "{count} fotos",
    "Aprobaciones",
    "¿Eliminar {count} borradores?",
    "Eliminar seleccionados ({count})",
    "Acciones del borrador",
    "Borradores ({count})",
    "Último guardado hace {count} d",
    "Último guardado hace {count} h",
    "Último guardado hace {count} min",
    "Menciones",
    "Las nuevas aprobaciones, menciones y comentarios aparecerán aquí.",
    "Aún no hay borradores guardados",
    "Ajustes de notificaciones",
    "Las notificaciones no están disponibles",
    "Ahora",
    "Recompensa añadida a tu saldo de IA",
    "Guarda publicaciones sin terminar y continúa aquí más tarde.",
    "Guardado ahora mismo",
    "Seleccionar",
    "Esto elimina solo los borradores privados seleccionados.",
    "Estás al día",
    "Anteriores",
  ],
  "tr": [
    "Genel bakış",
    "Gönderi fotoğrafları",
    "Ana sayfa",
    "Tamamlanmamış özel gönderiler",
    "Profili kaydet ve BIL Kodu oluştur",
    "Özel taslaklarını açmak için giriş yap.",
    "Koç eylemi izinleri",
    "İstatistikler",
    "{count} fotoğraf",
    "Onaylar",
    "{count} taslak silinsin mi?",
    "Seçilenleri sil ({count})",
    "Taslak işlemleri",
    "Taslaklar ({count})",
    "Son kayıt {count} gün önce",
    "Son kayıt {count} saat önce",
    "Son kayıt {count} dk önce",
    "Bahsetmeler",
    "Yeni onaylar, bahsetmeler ve yorumlar burada görünecek.",
    "Henüz kayıtlı taslak yok",
    "Bildirim ayarları",
    "Bildirimlere ulaşılamıyor",
    "Şimdi",
    "Ödül yapay zekâ bakiyene eklendi",
    "Tamamlanmamış gönderileri kaydet ve daha sonra buradan devam et.",
    "Az önce kaydedildi",
    "Seç",
    "Bu işlem yalnızca seçilen özel taslakları siler.",
    "Tüm bildirimleri gördün",
    "Daha önce",
  ],
  "de": [
    "Übersicht",
    "Beitragsfotos",
    "Startseite",
    "Private, unfertige Beiträge",
    "Profil speichern und BIL-Code erstellen",
    "Melde dich an, um deine privaten Entwürfe zu öffnen.",
    "Berechtigungen für Coach-Aktionen",
    "Statistiken",
    "{count} Fotos",
    "Genehmigungen",
    "{count} Entwürfe löschen?",
    "Auswahl löschen ({count})",
    "Entwurfsaktionen",
    "Entwürfe ({count})",
    "Zuletzt vor {count} T. gespeichert",
    "Zuletzt vor {count} Std. gespeichert",
    "Zuletzt vor {count} Min. gespeichert",
    "Erwähnungen",
    "Neue Genehmigungen, Erwähnungen und Kommentare erscheinen hier.",
    "Noch keine gespeicherten Entwürfe",
    "Benachrichtigungseinstellungen",
    "Benachrichtigungen sind nicht verfügbar",
    "Jetzt",
    "Belohnung deinem KI-Guthaben hinzugefügt",
    "Speichere unfertige Beiträge und setze sie später hier fort.",
    "Gerade gespeichert",
    "Auswählen",
    "Dadurch werden nur die ausgewählten privaten Entwürfe gelöscht.",
    "Du bist auf dem neuesten Stand",
    "Früher",
  ],
  "it": [
    "Panoramica",
    "Foto del post",
    "Pagina iniziale",
    "Post privati incompleti",
    "Salva il profilo e crea il codice BIL",
    "Accedi per aprire le tue bozze private.",
    "Autorizzazioni per le azioni del coach",
    "Statistiche",
    "{count} foto",
    "Approvazioni",
    "Eliminare {count} bozze?",
    "Elimina selezionate ({count})",
    "Azioni sulla bozza",
    "Bozze ({count})",
    "Ultimo salvataggio {count} g fa",
    "Ultimo salvataggio {count} h fa",
    "Ultimo salvataggio {count} min fa",
    "Menzioni",
    "Le nuove approvazioni, menzioni e i nuovi commenti appariranno qui.",
    "Nessuna bozza salvata per ora",
    "Impostazioni delle notifiche",
    "Le notifiche non sono disponibili",
    "Ora",
    "Ricompensa aggiunta al tuo saldo IA",
    "Salva i post incompleti e riprendili qui più tardi.",
    "Salvato proprio ora",
    "Seleziona",
    "Questa operazione elimina solo le bozze private selezionate.",
    "Hai visto tutti gli aggiornamenti",
    "In precedenza",
  ],
  "pt-BR": [
    "Visão geral",
    "Fotos da publicação",
    "Início",
    "Publicações privadas inacabadas",
    "Salvar perfil e criar código BIL",
    "Entre para abrir seus rascunhos privados.",
    "Permissões para ações do treinador",
    "Estatísticas",
    "{count} fotos",
    "Aprovações",
    "Excluir {count} rascunhos?",
    "Excluir selecionados ({count})",
    "Ações do rascunho",
    "Rascunhos ({count})",
    "Último salvamento há {count} d",
    "Último salvamento há {count} h",
    "Último salvamento há {count} min",
    "Menções",
    "Novas aprovações, menções e comentários aparecerão aqui.",
    "Ainda não há rascunhos salvos",
    "Configurações de notificações",
    "As notificações estão indisponíveis",
    "Agora",
    "Recompensa adicionada ao seu saldo de IA",
    "Salve publicações inacabadas e continue aqui mais tarde.",
    "Salvo agora mesmo",
    "Selecionar",
    "Isso exclui apenas os rascunhos privados selecionados.",
    "Você está em dia",
    "Anteriores",
  ],
  "pt-PT": [
    "Visão geral",
    "Fotografias da publicação",
    "Início",
    "Publicações privadas inacabadas",
    "Guardar perfil e criar código BIL",
    "Inicia sessão para abrir os teus rascunhos privados.",
    "Permissões para ações do treinador",
    "Estatísticas",
    "{count} fotografias",
    "Aprovações",
    "Eliminar {count} rascunhos?",
    "Eliminar selecionados ({count})",
    "Ações do rascunho",
    "Rascunhos ({count})",
    "Guardado pela última vez há {count} d",
    "Guardado pela última vez há {count} h",
    "Guardado pela última vez há {count} min",
    "Menções",
    "As novas aprovações, menções e comentários vão aparecer aqui.",
    "Ainda não há rascunhos guardados",
    "Definições de notificações",
    "As notificações estão indisponíveis",
    "Agora",
    "Recompensa adicionada ao teu saldo de IA",
    "Guarda publicações inacabadas e continua aqui mais tarde.",
    "Guardado agora mesmo",
    "Selecionar",
    "Isto elimina apenas os rascunhos privados selecionados.",
    "Estás a par de tudo",
    "Anteriores",
  ],
  "ur": [
    "جائزہ",
    "پوسٹ کی تصاویر",
    "مرکزی صفحہ",
    "نجی نامکمل پوسٹس",
    "پروفائل محفوظ کریں اور BIL کوڈ بنائیں",
    "اپنے نجی مسودے کھولنے کے لیے سائن اِن کریں۔",
    "کوچ کے اقدامات کی اجازتیں",
    "اعداد و شمار",
    "{count} تصاویر",
    "منظوریاں",
    "کیا {count} مسودے حذف کریں؟",
    "منتخب حذف کریں ({count})",
    "مسودے کے اقدامات",
    "مسودے ({count})",
    "آخری بار {count} دن پہلے محفوظ کیا گیا",
    "آخری بار {count} گھنٹے پہلے محفوظ کیا گیا",
    "آخری بار {count} منٹ پہلے محفوظ کیا گیا",
    "تذکرے",
    "نئی منظوریاں، تذکرے اور تبصرے یہاں ظاہر ہوں گے۔",
    "ابھی کوئی محفوظ مسودہ نہیں",
    "اطلاعات کی ترتیبات",
    "اطلاعات دستیاب نہیں ہیں",
    "ابھی",
    "انعام آپ کے AI بیلنس میں شامل کر دیا گیا",
    "نامکمل پوسٹس محفوظ کریں اور بعد میں یہیں سے جاری رکھیں۔",
    "ابھی محفوظ کیا گیا",
    "منتخب کریں",
    "اس سے صرف منتخب نجی مسودے حذف ہوں گے۔",
    "آپ نے تمام نئی اطلاعات دیکھ لی ہیں",
    "پہلے کی اطلاعات",
  ],
  "fa": [
    "نمای کلی",
    "عکس‌های پست",
    "خانه",
    "پست‌های خصوصی ناتمام",
    "ذخیرهٔ پروفایل و ایجاد کد BIL",
    "برای باز کردن پیش‌نویس‌های خصوصی‌تان وارد شوید.",
    "مجوزهای اقدامات مربی",
    "آمار",
    "{count} عکس",
    "تأییدها",
    "{count} پیش‌نویس حذف شود؟",
    "حذف انتخاب‌شده‌ها ({count})",
    "عملیات پیش‌نویس",
    "پیش‌نویس‌ها ({count})",
    "آخرین ذخیره {count} روز پیش",
    "آخرین ذخیره {count} ساعت پیش",
    "آخرین ذخیره {count} دقیقه پیش",
    "اشاره‌ها",
    "تأییدها، اشاره‌ها و نظرهای جدید اینجا نمایش داده می‌شوند.",
    "هنوز پیش‌نویسی ذخیره نشده است",
    "تنظیمات اعلان‌ها",
    "اعلان‌ها در دسترس نیستند",
    "اکنون",
    "پاداش به موجودی هوش مصنوعی شما افزوده شد",
    "پست‌های ناتمام را ذخیره کنید و بعداً از همین‌جا ادامه دهید.",
    "همین الان ذخیره شد",
    "انتخاب",
    "این کار فقط پیش‌نویس‌های خصوصی انتخاب‌شده را حذف می‌کند.",
    "همهٔ اعلان‌های جدید را دیده‌اید",
    "پیش‌تر",
  ],
  "hi": [
    "अवलोकन",
    "पोस्ट की तस्वीरें",
    "मुख्य पृष्ठ",
    "निजी अधूरी पोस्ट",
    "प्रोफ़ाइल सहेजें और BIL कोड बनाएँ",
    "अपने निजी ड्राफ़्ट खोलने के लिए साइन इन करें।",
    "कोच की कार्रवाइयों की अनुमतियाँ",
    "आँकड़े",
    "{count} तस्वीरें",
    "स्वीकृतियाँ",
    "{count} ड्राफ़्ट मिटाएँ?",
    "चुने हुए मिटाएँ ({count})",
    "ड्राफ़्ट की कार्रवाइयाँ",
    "ड्राफ़्ट ({count})",
    "आखिरी बार {count} दिन पहले सहेजा गया",
    "आखिरी बार {count} घंटे पहले सहेजा गया",
    "आखिरी बार {count} मिनट पहले सहेजा गया",
    "उल्लेख",
    "नई स्वीकृतियाँ, उल्लेख और टिप्पणियाँ यहाँ दिखाई देंगी।",
    "अभी कोई ड्राफ़्ट सहेजा नहीं गया है",
    "सूचना सेटिंग",
    "सूचनाएँ उपलब्ध नहीं हैं",
    "अभी",
    "इनाम आपके AI बैलेंस में जोड़ दिया गया",
    "अधूरी पोस्ट सहेजें और बाद में यहीं से जारी रखें।",
    "अभी-अभी सहेजा गया",
    "चुनें",
    "इससे केवल चुने हुए निजी ड्राफ़्ट मिटेंगे।",
    "आपने सभी नई सूचनाएँ देख ली हैं",
    "पहले की सूचनाएँ",
  ],
  "id": [
    "Ringkasan",
    "Foto postingan",
    "Beranda",
    "Postingan pribadi yang belum selesai",
    "Simpan profil dan buat Kode BIL",
    "Masuk untuk membuka draf pribadi Anda.",
    "Izin tindakan pelatih",
    "Statistik",
    "{count} foto",
    "Persetujuan",
    "Hapus {count} draf?",
    "Hapus yang dipilih ({count})",
    "Tindakan draf",
    "Draf ({count})",
    "Terakhir disimpan {count} hari lalu",
    "Terakhir disimpan {count} jam lalu",
    "Terakhir disimpan {count} menit lalu",
    "Sebutan",
    "Persetujuan, sebutan, dan komentar baru akan muncul di sini.",
    "Belum ada draf tersimpan",
    "Pengaturan notifikasi",
    "Notifikasi tidak tersedia",
    "Sekarang",
    "Hadiah ditambahkan ke saldo AI Anda",
    "Simpan postingan yang belum selesai dan lanjutkan di sini nanti.",
    "Baru saja disimpan",
    "Pilih",
    "Ini hanya menghapus draf pribadi yang dipilih.",
    "Anda sudah melihat semua notifikasi terbaru",
    "Sebelumnya",
  ],
};
