part of 'runtime_copy_community_expansion.dart';

const _communityExpansionWestRows = <String, List<String>>{
  'de': <String>[
    "{actor} hat deine Freundschaftsanfrage angenommen",
    "{actor} hat deinen Beitrag kommentiert",
    "{actor} folgt dir jetzt",
    "{actor} hat deinen Beitrag mit „Gefällt mir“ markiert",
    "{actor} hat dich in einem Beitrag erwähnt",
    "{actor} hat auf deinen Kommentar geantwortet",
    "{actor} hat dir eine Freundschaftsanfrage gesendet",
    "{inviterName} hat dich eingeladen, BIL beizutreten",
    "{total} Stimmen",
    "10.000 Schritte",
    "Ein freundlicher Ort für sichere, schrittweise Fitnessfortschritte.",
    "AI Coach-Nutzung",
    "Einladung annehmen",
    "Beiträge deiner bestätigten Freunde erscheinen hier.",
    "Durch das Annehmen wird gespeichert, wer dich eingeladen hat. Dadurch allein erhältst du kein Gold.",
    "Umfrage hinzufügen",
    "Option hinzufügen",
    "Mehrfachauswahl erlauben",
    "Eine andere Einladung ist bereits mit diesem Konto verknüpft.",
    "Stelle eine Frage mit 2–6 Optionen.",
    "BIL Gold-Aktivität",
    "BIL-Belohnungen",
    "BIL konnte diese Einladung nicht sicher verifizieren.",
    "BIL konnte deinen Belohnungsstatus nicht sicher verifizieren.",
    "BIL-Einladung",
    "Saldoanpassung",
    "Sei respektvoll, vermeide private Gesundheitsdaten und halte dich an die Community-Richtlinie.",
    "Fitness für Einsteiger",
    "Besser schlafen",
    "Baue eine regelmäßige Gehgewohnheit auf und motiviert euch gegenseitig.",
    "Challenge-Update",
    "Wähle eine Option",
    "Wähle eine oder mehrere Optionen",
    "Wähle, welche sozialen Bereiche andere Mitglieder sehen dürfen. Gesundheitsdaten sind nie enthalten.",
    "Kreis — optional",
    "Kreise",
    "Stadt- oder Ortsbezeichnung",
    "Eingelöst",
    "Kommentare & Erwähnungen",
    "Community-Level",
    "Datenschutz des Community-Profils",
    "Community-Aufgabe",
    "Community-Aufgabenbelohnung",
    "Community-Themen",
    "Schließe die verifizierte Community-Aktion ab, um Fortschritt zu machen.",
    "Vervollständige dein Community-Profil",
    "Diese Einladung konnte nicht sicher angenommen werden. Versuche es erneut.",
    "Diese Belohnung konnte nicht sicher eingelöst werden. Versuche es erneut.",
    "Weiterer Verlauf konnte nicht geladen werden.",
    "Deine Stimme konnte nicht gespeichert werden. Versuche es erneut.",
    "Erwähnungen können gerade nicht gesucht werden.",
    "Dieser Kreis konnte nicht sicher aktualisiert werden. Versuche es erneut.",
    "Dieses Thema konnte nicht sicher aktualisiert werden. Versuche es erneut.",
    "Einen wertvollen Beitrag erstellen",
    "Konto erstellen",
    "Täglich",
    "Tauscht euch über Krafttraining, Kontinuität und Erholung aus.",
    "Verdienen",
    "Verdient",
    "Verdiente und verwendete BIL Gold-Einträge erscheinen hier.",
    "Profil bearbeiten",
    "Vervollständige die Umfrage: Füge eine Frage und 2–6 verschiedene Optionen hinzu.",
    "Folgen",
    "Folge Mitgliedern, um ihre genehmigten Beiträge hier zu sehen.",
    "Follower",
    "Gefolgt",
    "Für dich",
    "Freundschaftsanfragen, bestätigte Verbindungen und ungelesene Nachrichten erscheinen hier.",
    "Los",
    "Rasteransicht",
    "Gesunde Ernährung",
    "Antworten ausblenden",
    "Einladung angenommen und Freundschaft erstellt. Gold bleibt an ein neues Konto und serverseitige Integritätsprüfungen gebunden.",
    "Einladung gespeichert.",
    "Einladung nicht verfügbar",
    "Freund einladen",
    "Beitreten",
    "Tritt einem Kreis bei, um darin zu posten.",
    "Verlassen",
    "Likes & gespeicherte Beiträge",
    "Listenansicht",
    "Weitere Kommentar-Threads laden",
    "Weitere Antworten laden",
    "Standort — optional",
    "Personen erwähnen — optional",
    "Erwähne bis zu 10 auffindbare Community-Mitglieder. Sie werden erst benachrichtigt, nachdem der Beitrag genehmigt wurde.",
    "Neu",
    "Neues Abzeichen verdient",
    "Neuer Kommentar zu deinem Beitrag",
    "Neuer Follower",
    "Neue Freundschaftsanfrage",
    "Neuer Beitrag",
    "Neue Antwort auf deinen Kommentar",
    "Kein Kreis",
    "Noch keine Gold-Aktivität",
    "Derzeit keine aktiven Aufgaben",
    "In diesem Kreis gibt es noch keine genehmigten Beiträge.",
    "Zu diesem Thema gibt es noch keine genehmigten Beiträge.",
    "Noch keine genehmigten Beiträge. Starte die erste Unterhaltung.",
    "Noch keine Updates in dieser Kategorie.",
    "Noch keine sichtbaren Beiträge.",
    "Noch nichts personalisiert. Folge Personen, Themen oder Kreisen, um diesen Feed zu gestalten.",
    "Hier gibt es noch nichts zu sehen.",
    "Standardmäßig deaktiviert. BIL Gold und Community XP bleiben von deinem Abonnement getrennt.",
    "Option {index}",
    "Nur optionaler Text. BIL fordert für Community-Beiträge kein GPS an.",
    "Umfrage",
    "Umfrage geschlossen",
    "Umfragefrage",
    "Im Kreis posten",
    "Beiträge sind in diesem Profil privat.",
    "Qualität, Moderation und sinnvolle Interaktion werden zuerst geprüft.",
    "Aufgabe abgeschlossen",
    "Ramadan & Fasten",
    "Bereit zum Einlösen",
    "Option entfernen",
    "Belohnung bereits eingelöst.",
    "Belohnung eingelöst.",
    "Belohnungsregeln werden von BIL erst aktiviert, wenn die serverseitige Verifizierung und Sicherheitsprüfungen bereit sind.",
    "Belohnungen",
    "Belohnungen nicht verfügbar",
    "Belohnungen werden erst freigeschaltet, wenn die verifizierte Freundschaft die Voraussetzungen erfüllt.",
    "Laufen",
    "Benutzernamen suchen",
    "Gesehen",
    "Richte deine öffentliche Identität und Datenschutzeinstellungen ein.",
    "Teile kulturell respektvolle Fastenroutinen und Erfahrungen.",
    "Teile praktische Essensideen und nachhaltige Ernährungsgewohnheiten.",
    "Teile Fortschritte, Routinen und Motivation beim Laufen.",
    "Teile nachhaltige Fortschritte und Unterstützung ohne Vergleichsdruck.",
    "Follower anzeigen",
    "Gefolgte anzeigen",
    "Freunde anzeigen",
    "Mitgliedschaftsstufe anzeigen",
    "Beiträge in meinem Profil anzeigen",
    "Zum Annehmen anmelden",
    "Melde dich an, um BIL Gold und Belohnungen zu sehen.",
    "Melde dich an, um Community-Profile zu sehen.",
    "Jemand hat deinen Beitrag gelikt",
    "Verwendbare Community-Währung",
    "Beitrag starten",
    "Einstieg",
    "Unterstütze bessere Schlafroutinen ohne medizinische Aussagen.",
    "Diese Einladung ist ungültig oder abgelaufen.",
    "Diese Einladung ist ungültig, abgelaufen oder bereits verwendet.",
    "Diese Einladung ist nicht verfügbar.",
    "Diese Einladung wurde bereits verwendet.",
    "Diese Liste ist derzeit nicht verfügbar.",
    "Diese Belohnung ist derzeit nicht verfügbar.",
    "Themen sind derzeit nicht verfügbar. Du kannst trotzdem posten.",
    "Themen — bis zu 3 auswählen",
    "Nachverfolgte BIL-Einladungen sind noch nicht aktiv.",
    "Nachverfolgte Einladungen sind noch nicht aktiv.",
    "Verwendet",
    "{count} Antworten anzeigen",
    "Abstimmen",
    "Wöchentlich",
    "Weg zur Gewichtsabnahme",
    "Du kannst deine eigene Einladung nicht annehmen.",
    "Du hast eine Community-Belohnung verdient",
    "Du wurdest in einem Beitrag erwähnt",
    "Deine Freundschaftsanfrage wurde angenommen",
    "Dein Beitrag wurde gespeichert",
    "Ihr seid Freunde — Profil ansehen",
    "Follower",
    "Mitglieder",
    "Beiträge",
  ],
  'it': <String>[
    "{actor} ha accettato la tua richiesta di amicizia",
    "{actor} ha commentato il tuo post",
    "{actor} ha iniziato a seguirti",
    "{actor} ha messo Mi piace al tuo post",
    "{actor} ti ha menzionato in un post",
    "{actor} ha risposto al tuo commento",
    "{actor} ti ha inviato una richiesta di amicizia",
    "{inviterName} ti ha invitato a unirti a BIL",
    "{total} voti",
    "10.000 passi",
    "Uno spazio accogliente per progressi di fitness sicuri e graduali.",
    "Utilizzo di AI Coach",
    "Accetta invito",
    "I post degli amici accettati appariranno qui.",
    "L’accettazione registra chi ti ha invitato. Da sola non assegna Gold.",
    "Aggiungi un sondaggio",
    "Aggiungi opzione",
    "Consenti scelte multiple",
    "Un altro invito è già collegato a questo account.",
    "Fai una domanda con 2–6 opzioni.",
    "Attività BIL Gold",
    "Ricompense BIL",
    "BIL non ha potuto verificare questo invito in modo sicuro.",
    "BIL non ha potuto verificare in modo sicuro lo stato delle tue ricompense.",
    "Invito BIL",
    "Rettifica del saldo",
    "Sii rispettoso, evita dati sanitari privati e segui le regole della Community.",
    "Fitness per principianti",
    "Dormire meglio",
    "Crea un’abitudine costante alla camminata e incoraggiatevi a vicenda.",
    "Aggiornamento sfida",
    "Scegli un’opzione",
    "Scegli una o più opzioni",
    "Scegli quali sezioni social possono vedere gli altri membri. I dati sanitari non sono mai inclusi.",
    "Cerchio — facoltativo",
    "Cerchi",
    "Etichetta città o luogo",
    "Riscattata",
    "Commenti e menzioni",
    "Livello Community",
    "Privacy del profilo Community",
    "Missione Community",
    "Ricompensa missione Community",
    "Argomenti della Community",
    "Completa l’azione Community verificata per fare progressi.",
    "Completa il tuo profilo Community",
    "Impossibile accettare questo invito in modo sicuro. Riprova.",
    "Impossibile riscattare questa ricompensa in modo sicuro. Riprova.",
    "Impossibile caricare altra cronologia.",
    "Impossibile registrare il tuo voto. Riprova.",
    "Impossibile cercare le menzioni al momento.",
    "Impossibile aggiornare questo Cerchio in modo sicuro. Riprova.",
    "Impossibile aggiornare questo argomento in modo sicuro. Riprova.",
    "Crea un post di valore",
    "Crea un account",
    "Giornaliero",
    "Parla di allenamento di forza, costanza e recupero.",
    "Guadagna",
    "Guadagnato",
    "Le voci BIL Gold guadagnate e utilizzate appariranno qui.",
    "Modifica profilo",
    "Completa il sondaggio: aggiungi una domanda e 2–6 opzioni diverse.",
    "Segui",
    "Segui membri per vedere qui i loro post approvati.",
    "Follower",
    "Seguiti",
    "Per te",
    "Richieste di amicizia, connessioni accettate e messaggi non letti appariranno qui.",
    "Vai",
    "Vista griglia",
    "Alimentazione sana",
    "Nascondi risposte",
    "Invito accettato e amicizia creata. Gold resta subordinato al nuovo account e ai controlli di integrità del server.",
    "Invito salvato.",
    "Invito non disponibile",
    "Invita un amico",
    "Unisciti",
    "Unisciti a un Cerchio per pubblicare al suo interno.",
    "Esci",
    "Mi piace e salvataggi",
    "Vista elenco",
    "Carica altri thread di commenti",
    "Carica altre risposte",
    "Posizione — facoltativa",
    "Menziona persone — facoltativo",
    "Menziona fino a 10 membri Community individuabili. Ricevono una notifica solo dopo l’approvazione del post.",
    "Nuovo",
    "Nuovo badge ottenuto",
    "Nuovo commento al tuo post",
    "Nuovo follower",
    "Nuova richiesta di amicizia",
    "Nuovo post",
    "Nuova risposta al tuo commento",
    "Nessun Cerchio",
    "Nessuna attività Gold per ora",
    "Nessuna missione attiva al momento",
    "Non ci sono ancora post approvati in questo Cerchio.",
    "Non ci sono ancora post approvati in questo argomento.",
    "Non ci sono ancora post approvati. Avvia la prima conversazione.",
    "Nessun aggiornamento in questa categoria per ora.",
    "Nessun post visibile per ora.",
    "Ancora nulla di personalizzato. Segui persone, argomenti o Cerchi per modellare questo feed.",
    "Nulla da mostrare qui per ora.",
    "Disattivato per impostazione predefinita. BIL Gold e Community XP restano separati dal tuo abbonamento.",
    "Opzione {index}",
    "Solo testo facoltativo. BIL non richiede il GPS per i post della Community.",
    "Sondaggio",
    "Sondaggio chiuso",
    "Domanda del sondaggio",
    "Pubblica nel Cerchio",
    "I post sono privati su questo profilo.",
    "Prima vengono controllati qualità, moderazione e coinvolgimento significativo.",
    "Missione completata",
    "Ramadan e digiuno",
    "Pronto da riscattare",
    "Rimuovi opzione",
    "Ricompensa già riscattata.",
    "Ricompensa riscattata.",
    "Le regole delle ricompense vengono attivate da BIL solo dopo la verifica lato server e quando i controlli di sicurezza sono pronti.",
    "Ricompense",
    "Ricompense non disponibili",
    "Le ricompense si sbloccano solo quando la relazione di amicizia verificata è idonea.",
    "Corsa",
    "Cerca nome utente",
    "Visto",
    "Configura la tua identità pubblica e le scelte sulla privacy.",
    "Condividi routine ed esperienze di digiuno nel rispetto delle culture.",
    "Condividi idee pratiche per i pasti e abitudini alimentari sostenibili.",
    "Condividi progressi, routine e incoraggiamento nella corsa.",
    "Condividi progressi sostenibili e supporto senza confronti o pressioni.",
    "Mostra follower",
    "Mostra seguiti",
    "Mostra amici",
    "Mostra livello di iscrizione",
    "Mostra i post sul mio profilo",
    "Accedi per accettare",
    "Accedi per vedere BIL Gold e le ricompense.",
    "Accedi per vedere i profili Community.",
    "Qualcuno ha messo Mi piace al tuo post",
    "Valuta Community spendibile",
    "Inizia un post",
    "Principiante",
    "Sostieni migliori routine del sonno senza affermazioni mediche.",
    "Questo invito non è valido o è scaduto.",
    "Questo invito non è valido, è scaduto o è già stato utilizzato.",
    "Questo invito non è disponibile.",
    "Questo invito è già stato utilizzato.",
    "Questo elenco non è disponibile al momento.",
    "Questa ricompensa non è disponibile al momento.",
    "Gli argomenti non sono disponibili al momento. Puoi comunque pubblicare.",
    "Argomenti — scegli fino a 3",
    "Gli inviti BIL tracciati non sono ancora attivi.",
    "Gli inviti tracciati non sono ancora attivi.",
    "Utilizzato",
    "Vedi {count} risposte",
    "Vota",
    "Settimanale",
    "Percorso di perdita di peso",
    "Non puoi accettare il tuo stesso invito.",
    "Hai ottenuto una ricompensa Community",
    "Sei stato menzionato in un post",
    "La tua richiesta di amicizia è stata accettata",
    "Il tuo post è stato salvato",
    "Siete amici — visualizza profilo",
    "follower",
    "membri",
    "post",
  ],
  'pt-BR': <String>[
    "{actor} aceitou sua solicitação de amizade",
    "{actor} comentou na sua publicação",
    "{actor} começou a seguir você",
    "{actor} curtiu sua publicação",
    "{actor} mencionou você em uma publicação",
    "{actor} respondeu ao seu comentário",
    "{actor} enviou uma solicitação de amizade",
    "{inviterName} convidou você para entrar no BIL",
    "{total} votos",
    "10 mil passos",
    "Um espaço acolhedor para progresso seguro e gradual no condicionamento físico.",
    "Uso do AI Coach",
    "Aceitar convite",
    "As publicações dos amigos aceitos aparecerão aqui.",
    "Aceitar registra quem convidou você. Isso, por si só, não concede Gold.",
    "Adicionar enquete",
    "Adicionar opção",
    "Permitir várias escolhas",
    "Outro convite já está vinculado a esta conta.",
    "Faça uma pergunta com 2–6 opções.",
    "Atividade do BIL Gold",
    "Recompensas BIL",
    "O BIL não conseguiu verificar este convite com segurança.",
    "O BIL não conseguiu verificar com segurança o estado das suas recompensas.",
    "Convite BIL",
    "Ajuste de saldo",
    "Seja respeitoso, evite dados privados de saúde e siga a política da Comunidade.",
    "Fitness para iniciantes",
    "Dormir melhor",
    "Crie um hábito consistente de caminhada e incentivem-se mutuamente.",
    "Atualização do desafio",
    "Escolha uma opção",
    "Escolha uma ou mais opções",
    "Escolha quais seções sociais outros membros podem ver. Dados de saúde nunca são incluídos.",
    "Círculo — opcional",
    "Círculos",
    "Rótulo de cidade ou local",
    "Resgatado",
    "Comentários e menções",
    "Nível da Comunidade",
    "Privacidade do perfil da Comunidade",
    "Missão da Comunidade",
    "Recompensa de missão da Comunidade",
    "Tópicos da Comunidade",
    "Conclua a ação verificada da Comunidade para avançar.",
    "Complete seu perfil da Comunidade",
    "Não foi possível aceitar este convite com segurança. Tente novamente.",
    "Não foi possível resgatar esta recompensa com segurança. Tente novamente.",
    "Não foi possível carregar mais histórico.",
    "Não foi possível registrar seu voto. Tente novamente.",
    "Não foi possível pesquisar menções agora.",
    "Não foi possível atualizar este Círculo com segurança. Tente novamente.",
    "Não foi possível atualizar este tópico com segurança. Tente novamente.",
    "Crie uma publicação valiosa",
    "Criar uma conta",
    "Diário",
    "Converse sobre treino de força, consistência e recuperação.",
    "Ganhar",
    "Ganho",
    "As entradas de BIL Gold ganhas e usadas aparecerão aqui.",
    "Editar perfil",
    "Conclua a enquete: adicione uma pergunta e 2–6 opções diferentes.",
    "Seguir",
    "Siga membros para ver aqui as publicações aprovadas deles.",
    "Seguidores",
    "Seguindo",
    "Para você",
    "Solicitações de amizade, conexões aceitas e mensagens não lidas aparecerão aqui.",
    "Ir",
    "Visualização em grade",
    "Alimentação saudável",
    "Ocultar respostas",
    "Convite aceito e amizade criada. Gold continua condicionado à conta nova e às verificações de integridade do servidor.",
    "Convite salvo.",
    "Convite indisponível",
    "Convidar um amigo",
    "Entrar",
    "Entre em um Círculo para publicar nele.",
    "Sair",
    "Curtidas e salvos",
    "Visualização em lista",
    "Carregar mais tópicos de comentários",
    "Carregar mais respostas",
    "Localização — opcional",
    "Mencionar pessoas — opcional",
    "Mencione até 10 membros descobríveis da Comunidade. Eles só são notificados depois que a publicação é aprovada.",
    "Novo",
    "Novo selo conquistado",
    "Novo comentário na sua publicação",
    "Novo seguidor",
    "Nova solicitação de amizade",
    "Nova publicação",
    "Nova resposta ao seu comentário",
    "Sem Círculo",
    "Nenhuma atividade Gold ainda",
    "Nenhuma missão ativa no momento",
    "Ainda não há publicações aprovadas neste Círculo.",
    "Ainda não há publicações aprovadas neste tópico.",
    "Ainda não há publicações aprovadas. Inicie a primeira conversa.",
    "Ainda não há atualizações nesta categoria.",
    "Ainda não há publicações visíveis.",
    "Ainda não há nada personalizado. Siga pessoas, tópicos ou Círculos para moldar este feed.",
    "Nada para mostrar aqui por enquanto.",
    "Desativado por padrão. BIL Gold e Community XP permanecem separados da sua assinatura.",
    "Opção {index}",
    "Apenas texto opcional. O BIL não solicita GPS para publicações da Comunidade.",
    "Enquete",
    "Enquete encerrada",
    "Pergunta da enquete",
    "Publicar no Círculo",
    "As publicações são privadas neste perfil.",
    "Qualidade, moderação e engajamento significativo são verificados primeiro.",
    "Missão concluída",
    "Ramadã e jejum",
    "Pronto para resgatar",
    "Remover opção",
    "Recompensa já resgatada.",
    "Recompensa resgatada.",
    "As regras de recompensa só são ativadas pelo BIL após verificação no servidor e quando as verificações de segurança estão prontas.",
    "Recompensas",
    "Recompensas indisponíveis",
    "As recompensas só são liberadas quando a relação de amizade verificada se qualifica.",
    "Corrida",
    "Pesquisar nome de usuário",
    "Visto",
    "Configure sua identidade pública e suas escolhas de privacidade.",
    "Compartilhe rotinas e experiências de jejum com respeito cultural.",
    "Compartilhe ideias práticas de refeições e hábitos alimentares sustentáveis.",
    "Compartilhe progresso, rotinas e incentivo na corrida.",
    "Compartilhe progresso sustentável e apoio sem comparação nem pressão.",
    "Mostrar seguidores",
    "Mostrar quem você segue",
    "Mostrar amigos",
    "Mostrar nível de assinatura",
    "Mostrar publicações no meu perfil",
    "Entre para aceitar",
    "Entre para ver BIL Gold e recompensas.",
    "Entre para ver perfis da Comunidade.",
    "Alguém curtiu sua publicação",
    "Moeda da Comunidade utilizável",
    "Iniciar uma publicação",
    "Iniciante",
    "Apoie melhores rotinas de sono sem alegações médicas.",
    "Este convite é inválido ou expirou.",
    "Este convite é inválido, expirou ou já foi usado.",
    "Este convite está indisponível.",
    "Este convite já foi usado.",
    "Esta lista está indisponível no momento.",
    "Esta recompensa não está disponível no momento.",
    "Os tópicos estão indisponíveis no momento. Você ainda pode publicar.",
    "Tópicos — escolha até 3",
    "Os convites BIL rastreados ainda não estão ativos.",
    "Os convites rastreados ainda não estão ativos.",
    "Usado",
    "Ver {count} respostas",
    "Votar",
    "Semanal",
    "Jornada de perda de peso",
    "Você não pode aceitar seu próprio convite.",
    "Você ganhou uma recompensa da Comunidade",
    "Você foi mencionado em uma publicação",
    "Sua solicitação de amizade foi aceita",
    "Sua publicação foi salva",
    "Vocês são amigos — ver perfil",
    "seguidores",
    "membros",
    "publicações",
  ],
};
