// Reviewed Profile copy catalog shard B.
const profileRuntimeCopyCatalogB = <String, Map<String, String>>{
  'Maintenance plan · no countdown': {
    'ar': 'خطة تثبيت · بلا عدّ تنازلي',
    'en': 'Maintenance plan · no countdown',
    'fr': 'Plan de maintien · aucun compte à rebours',
    'es': 'Plan de mantenimiento · sin cuenta atrás',
    'tr': 'Koruma planı · geri sayım yok',
    'de': 'Gewicht halten · kein Countdown',
    'it': 'Piano di mantenimento · nessun conto alla rovescia',
    'pt-BR': 'Plano de manutenção · sem contagem regressiva',
    'pt-PT': 'Plano de manutenção · sem contagem decrescente',
    'ur': 'وزن برقرار رکھنے کا منصوبہ · کوئی الٹی گنتی نہیں',
    'fa': 'برنامه تثبیت · بدون شمارش معکوس',
    'hi': 'वज़न बनाए रखने की योजना · कोई उलटी गिनती नहीं',
    'id': 'Rencana mempertahankan berat · tanpa hitung mundur',
    'ms': 'Pelan mengekalkan berat · tiada kira detik',
    'ja': '維持プラン · カウントダウンなし',
    'ko': '유지 계획 · 카운트다운 없음',
    'zh-Hans': '维持计划 · 无倒计时',
    'zh-Hant': '維持計畫 · 無倒數',
    'ru': 'План поддержания · без обратного отсчёта',
    'bn': 'ওজন ধরে রাখার পরিকল্পনা · কোনো কাউন্টডাউন নেই',
    'vi': 'Kế hoạch duy trì · không đếm ngược',
    'th': 'แผนรักษาน้ำหนัก · ไม่มีการนับถอยหลัง',
    'pl': 'Plan utrzymania · bez odliczania',
    'nl': 'Onderhoudsplan · geen aftelling',
    'uk': 'План підтримання · без зворотного відліку',
  },
  'Current weight is within the goal range. This is an estimate, not a guarantee.': {
    'ar': 'الوزن الحالي ضمن نطاق الهدف. هذا تقدير وليس ضمانًا.',
    'en':
        'Current weight is within the goal range. This is an estimate, not a guarantee.',
    'fr':
        'Le poids actuel se situe dans la plage cible. Il s’agit d’une estimation, sans garantie.',
    'es':
        'El peso actual está dentro del rango objetivo. Es una estimación, no una garantía.',
    'tr': 'Mevcut kilo hedef aralığında. Bu bir tahmindir, garanti değildir.',
    'de':
        'Das aktuelle Gewicht liegt im Zielbereich. Dies ist eine Schätzung, keine Garantie.',
    'it':
        'Il peso attuale rientra nell’intervallo obiettivo. È una stima, non una garanzia.',
    'pt-BR':
        'O peso atual está dentro da faixa da meta. Esta é uma estimativa, não uma garantia.',
    'pt-PT':
        'O peso atual está dentro do intervalo do objetivo. É uma estimativa, não uma garantia.',
    'ur': 'موجودہ وزن ہدف کی حد میں ہے۔ یہ ایک تخمینہ ہے، ضمانت نہیں۔',
    'fa': 'وزن فعلی در محدوده هدف است. این فقط یک برآورد است، نه تضمین.',
    'hi': 'मौजूदा वज़न लक्ष्य की सीमा में है। यह एक अनुमान है, गारंटी नहीं।',
    'id':
        'Berat saat ini berada dalam rentang target. Ini perkiraan, bukan jaminan.',
    'ms':
        'Berat semasa berada dalam julat matlamat. Ini anggaran, bukan jaminan.',
    'ja': '現在の体重は目標範囲内です。これは推定値であり、保証ではありません。',
    'ko': '현재 체중이 목표 범위 안에 있습니다. 이는 예상치이며 보장되지 않습니다.',
    'zh-Hans': '当前体重在目标范围内。这只是估算，并非保证。',
    'zh-Hant': '目前體重在目標範圍內。這只是估算，並非保證。',
    'ru':
        'Текущий вес находится в целевом диапазоне. Это оценка, а не гарантия.',
    'bn':
        'বর্তমান ওজন লক্ষ্যসীমার মধ্যে আছে। এটি একটি আনুমানিক হিসাব, নিশ্চয়তা নয়।',
    'vi':
        'Cân nặng hiện tại nằm trong phạm vi mục tiêu. Đây là ước tính, không phải cam kết.',
    'th':
        'น้ำหนักปัจจุบันอยู่ในช่วงเป้าหมาย นี่เป็นเพียงค่าประมาณ ไม่ใช่การรับประกัน',
    'pl':
        'Obecna masa ciała mieści się w zakresie celu. To szacunek, nie gwarancja.',
    'nl':
        'Je huidige gewicht ligt binnen het doelbereik. Dit is een schatting, geen garantie.',
    'uk':
        'Поточна вага перебуває в цільовому діапазоні. Це оцінка, а не гарантія.',
  },
  'Maintenance has no completion date. This is an estimate, not a guarantee.': {
    'ar': 'التثبيت ليس له تاريخ اكتمال. هذا تقدير وليس ضمانًا.',
    'en':
        'Maintenance has no completion date. This is an estimate, not a guarantee.',
    'fr':
        'Le maintien n’a pas de date de fin. Il s’agit d’une estimation, sans garantie.',
    'es':
        'El mantenimiento no tiene fecha de finalización. Es una estimación, no una garantía.',
    'tr':
        'Korumanın tamamlanma tarihi yoktur. Bu bir tahmindir, garanti değildir.',
    'de':
        'Für die Gewichtserhaltung gibt es kein Abschlussdatum. Dies ist eine Schätzung, keine Garantie.',
    'it':
        'Il mantenimento non ha una data di completamento. È una stima, non una garanzia.',
    'pt-BR':
        'A manutenção não tem data de conclusão. Esta é uma estimativa, não uma garantia.',
    'pt-PT':
        'A manutenção não tem data de conclusão. É uma estimativa, não uma garantia.',
    'ur':
        'وزن برقرار رکھنے کی کوئی تکمیل کی تاریخ نہیں۔ یہ ایک تخمینہ ہے، ضمانت نہیں۔',
    'fa': 'تثبیت تاریخ پایان ندارد. این فقط یک برآورد است، نه تضمین.',
    'hi':
        'वज़न बनाए रखने की कोई पूरी होने की तारीख नहीं है। यह एक अनुमान है, गारंटी नहीं।',
    'id':
        'Mempertahankan berat tidak memiliki tanggal selesai. Ini perkiraan, bukan jaminan.',
    'ms':
        'Mengekalkan berat tiada tarikh selesai. Ini anggaran, bukan jaminan.',
    'ja': '維持プランに完了日はありません。これは推定であり、保証ではありません。',
    'ko': '유지 계획에는 완료일이 없습니다. 이는 예상치이며 보장되지 않습니다.',
    'zh-Hans': '维持计划没有完成日期。这只是估算，并非保证。',
    'zh-Hant': '維持計畫沒有完成日期。這只是估算，並非保證。',
    'ru': 'У поддержания веса нет даты завершения. Это оценка, а не гарантия.',
    'bn':
        'ওজন ধরে রাখার কোনো সমাপ্তির তারিখ নেই। এটি একটি আনুমানিক হিসাব, নিশ্চয়তা নয়।',
    'vi':
        'Duy trì cân nặng không có ngày hoàn thành. Đây là ước tính, không phải cam kết.',
    'th':
        'การรักษาน้ำหนักไม่มีวันที่เสร็จสิ้น นี่เป็นเพียงค่าประมาณ ไม่ใช่การรับประกัน',
    'pl':
        'Utrzymanie masy ciała nie ma daty zakończenia. To szacunek, nie gwarancja.',
    'nl':
        'Gewichtsbehoud heeft geen einddatum. Dit is een schatting, geen garantie.',
    'uk': 'Підтримання ваги не має дати завершення. Це оцінка, а не гарантія.',
  },
  'loss': {
    'ar': 'نزول',
    'en': 'loss',
    'fr': 'perte',
    'es': 'pérdida',
    'tr': 'kayıp',
    'de': 'Abnahme',
    'it': 'perdita',
    'pt-BR': 'perda',
    'pt-PT': 'perda',
    'ur': 'کمی',
    'fa': 'کاهش',
    'hi': 'कमी',
    'id': 'penurunan',
    'ms': 'penurunan',
    'ja': '減量',
    'ko': '감량',
    'zh-Hans': '减重',
    'zh-Hant': '減重',
    'ru': 'снижение',
    'bn': 'হ্রাস',
    'vi': 'giảm cân',
    'th': 'การลดน้ำหนัก',
    'pl': 'spadku',
    'nl': 'gewichtsverlies',
    'uk': 'зниження',
  },
  'gain': {
    'ar': 'زيادة',
    'en': 'gain',
    'fr': 'prise',
    'es': 'aumento',
    'tr': 'artış',
    'de': 'Zunahme',
    'it': 'aumento',
    'pt-BR': 'ganho',
    'pt-PT': 'aumento',
    'ur': 'اضافہ',
    'fa': 'افزایش',
    'hi': 'बढ़ोतरी',
    'id': 'kenaikan',
    'ms': 'peningkatan',
    'ja': '増量',
    'ko': '증량',
    'zh-Hans': '增重',
    'zh-Hant': '增重',
    'ru': 'набор',
    'bn': 'বৃদ্ধি',
    'vi': 'tăng cân',
    'th': 'การเพิ่มน้ำหนัก',
    'pl': 'wzrostu',
    'nl': 'gewichtstoename',
    'uk': 'збільшення',
  },
  'Personal details': {
    'ar': 'البيانات الشخصية',
    'en': 'Personal details',
    'fr': 'Informations personnelles',
    'es': 'Datos personales',
    'tr': 'Kişisel bilgiler',
    'de': 'Persönliche Angaben',
    'it': 'Dati personali',
    'pt-BR': 'Dados pessoais',
    'pt-PT': 'Dados pessoais',
    'ur': 'ذاتی تفصیلات',
    'fa': 'اطلاعات شخصی',
    'hi': 'व्यक्तिगत विवरण',
    'id': 'Detail pribadi',
    'ms': 'Butiran peribadi',
    'ja': '個人情報',
    'ko': '개인 정보',
    'zh-Hans': '个人信息',
    'zh-Hant': '個人資料',
    'ru': 'Личные данные',
    'bn': 'ব্যক্তিগত তথ্য',
    'vi': 'Thông tin cá nhân',
    'th': 'ข้อมูลส่วนตัว',
    'pl': 'Dane osobowe',
    'nl': 'Persoonlijke gegevens',
    'uk': 'Особисті дані',
  },
  'Change photo': {
    'ar': 'تغيير الصورة',
    'en': 'Change photo',
    'fr': 'Modifier la photo',
    'es': 'Cambiar foto',
    'tr': 'Fotoğrafı değiştir',
    'de': 'Foto ändern',
    'it': 'Cambia foto',
    'pt-BR': 'Alterar foto',
    'pt-PT': 'Alterar foto',
    'ur': 'تصویر تبدیل کریں',
    'fa': 'تغییر عکس',
    'hi': 'फ़ोटो बदलें',
    'id': 'Ubah foto',
    'ms': 'Tukar foto',
    'ja': '写真を変更',
    'ko': '사진 변경',
    'zh-Hans': '更换照片',
    'zh-Hant': '變更照片',
    'ru': 'Изменить фото',
    'bn': 'ছবি পরিবর্তন করুন',
    'vi': 'Đổi ảnh',
    'th': 'เปลี่ยนรูปภาพ',
    'pl': 'Zmień zdjęcie',
    'nl': 'Foto wijzigen',
    'uk': 'Змінити фото',
  },
  'Not added': {
    'ar': 'غير مضاف',
    'en': 'Not added',
    'fr': 'Non ajouté',
    'es': 'No añadido',
    'tr': 'Eklenmedi',
    'de': 'Nicht hinzugefügt',
    'it': 'Non aggiunto',
    'pt-BR': 'Não adicionado',
    'pt-PT': 'Não adicionado',
    'ur': 'شامل نہیں کیا گیا',
    'fa': 'اضافه نشده',
    'hi': 'जोड़ा नहीं गया',
    'id': 'Belum ditambahkan',
    'ms': 'Belum ditambah',
    'ja': '未追加',
    'ko': '추가되지 않음',
    'zh-Hans': '未添加',
    'zh-Hant': '尚未新增',
    'ru': 'Не добавлено',
    'bn': 'যোগ করা হয়নি',
    'vi': 'Chưa thêm',
    'th': 'ยังไม่ได้เพิ่ม',
    'pl': 'Nie dodano',
    'nl': 'Niet toegevoegd',
    'uk': 'Не додано',
  },
  'Body details': {
    'ar': 'بيانات الجسم',
    'en': 'Body details',
    'fr': 'Données corporelles',
    'es': 'Datos corporales',
    'tr': 'Vücut bilgileri',
    'de': 'Körperdaten',
    'it': 'Dati corporei',
    'pt-BR': 'Dados corporais',
    'pt-PT': 'Dados corporais',
    'ur': 'جسمانی تفصیلات',
    'fa': 'اطلاعات بدن',
    'hi': 'शरीर का विवरण',
    'id': 'Detail tubuh',
    'ms': 'Butiran badan',
    'ja': '身体情報',
    'ko': '신체 정보',
    'zh-Hans': '身体信息',
    'zh-Hant': '身體資料',
    'ru': 'Данные тела',
    'bn': 'শরীরের তথ্য',
    'vi': 'Thông tin cơ thể',
    'th': 'ข้อมูลร่างกาย',
    'pl': 'Dane ciała',
    'nl': 'Lichaamsgegevens',
    'uk': 'Дані тіла',
  },
  'Sex': {
    'ar': 'الجنس',
    'en': 'Sex',
    'fr': 'Sexe',
    'es': 'Sexo',
    'tr': 'Cinsiyet',
    'de': 'Geschlecht',
    'it': 'Sesso',
    'pt-BR': 'Sexo',
    'pt-PT': 'Sexo',
    'ur': 'جنس',
    'fa': 'جنسیت',
    'hi': 'लिंग',
    'id': 'Jenis kelamin',
    'ms': 'Jantina',
    'ja': '性別',
    'ko': '성별',
    'zh-Hans': '性别',
    'zh-Hant': '性別',
    'ru': 'Пол',
    'bn': 'লিঙ্গ',
    'vi': 'Giới tính',
    'th': 'เพศ',
    'pl': 'Płeć',
    'nl': 'Geslacht',
    'uk': 'Стать',
  },
  'Location & preferences': {
    'ar': 'الموقع والتفضيلات',
    'en': 'Location & preferences',
    'fr': 'Lieu et préférences',
    'es': 'Ubicación y preferencias',
    'tr': 'Konum ve tercihler',
    'de': 'Standort und Einstellungen',
    'it': 'Posizione e preferenze',
    'pt-BR': 'Localização e preferências',
    'pt-PT': 'Localização e preferências',
    'ur': 'مقام اور ترجیحات',
    'fa': 'مکان و ترجیحات',
    'hi': 'स्थान और प्राथमिकताएँ',
    'id': 'Lokasi & preferensi',
    'ms': 'Lokasi & pilihan',
    'ja': '場所と設定',
    'ko': '위치 및 환경설정',
    'zh-Hans': '位置与偏好',
    'zh-Hant': '位置與偏好設定',
    'ru': 'Местоположение и предпочтения',
    'bn': 'অবস্থান ও পছন্দসমূহ',
    'vi': 'Vị trí & tùy chọn',
    'th': 'ตำแหน่งและการตั้งค่า',
    'pl': 'Lokalizacja i preferencje',
    'nl': 'Locatie en voorkeuren',
    'uk': 'Місцезнаходження та налаштування',
  },
  'Location': {
    'ar': 'الموقع',
    'en': 'Location',
    'fr': 'Lieu',
    'es': 'Ubicación',
    'tr': 'Konum',
    'de': 'Standort',
    'it': 'Posizione',
    'pt-BR': 'Localização',
    'pt-PT': 'Localização',
    'ur': 'مقام',
    'fa': 'مکان',
    'hi': 'स्थान',
    'id': 'Lokasi',
    'ms': 'Lokasi',
    'ja': '場所',
    'ko': '위치',
    'zh-Hans': '位置',
    'zh-Hant': '位置',
    'ru': 'Местоположение',
    'bn': 'অবস্থান',
    'vi': 'Vị trí',
    'th': 'ตำแหน่ง',
    'pl': 'Lokalizacja',
    'nl': 'Locatie',
    'uk': 'Місцезнаходження',
  },
  'Postal code': {
    'ar': 'الرمز البريدي',
    'en': 'Postal code',
    'fr': 'Code postal',
    'es': 'Código postal',
    'tr': 'Posta kodu',
    'de': 'Postleitzahl',
    'it': 'Codice postale',
    'pt-BR': 'CEP',
    'pt-PT': 'Código postal',
    'ur': 'پوسٹل کوڈ',
    'fa': 'کد پستی',
    'hi': 'पिन कोड',
    'id': 'Kode pos',
    'ms': 'Poskod',
    'ja': '郵便番号',
    'ko': '우편번호',
    'zh-Hans': '邮政编码',
    'zh-Hant': '郵遞區號',
    'ru': 'Почтовый индекс',
    'bn': 'পোস্টাল কোড',
    'vi': 'Mã bưu chính',
    'th': 'รหัสไปรษณีย์',
    'pl': 'Kod pocztowy',
    'nl': 'Postcode',
    'uk': 'Поштовий індекс',
  },
  'Time zone': {
    'ar': 'المنطقة الزمنية',
    'en': 'Time zone',
    'fr': 'Fuseau horaire',
    'es': 'Zona horaria',
    'tr': 'Saat dilimi',
    'de': 'Zeitzone',
    'it': 'Fuso orario',
    'pt-BR': 'Fuso horário',
    'pt-PT': 'Fuso horário',
    'ur': 'ٹائم زون',
    'fa': 'منطقه زمانی',
    'hi': 'समय क्षेत्र',
    'id': 'Zona waktu',
    'ms': 'Zon waktu',
    'ja': 'タイムゾーン',
    'ko': '시간대',
    'zh-Hans': '时区',
    'zh-Hant': '時區',
    'ru': 'Часовой пояс',
    'bn': 'সময় অঞ্চল',
    'vi': 'Múi giờ',
    'th': 'เขตเวลา',
    'pl': 'Strefa czasowa',
    'nl': 'Tijdzone',
    'uk': 'Часовий пояс',
  },
  'Metric · kg, cm, ml': {
    'ar': 'متري · كغ، سم، مل',
    'en': 'Metric · kg, cm, ml',
    'fr': 'Métrique · kg, cm, ml',
    'es': 'Métrico · kg, cm, ml',
    'tr': 'Metrik · kg, cm, ml',
    'de': 'Metrisch · kg, cm, ml',
    'it': 'Metrico · kg, cm, ml',
    'pt-BR': 'Métrico · kg, cm, ml',
    'pt-PT': 'Métrico · kg, cm, ml',
    'ur': 'میٹرک · کلوگرام، سینٹی میٹر، ملی لیٹر',
    'fa': 'متریک · کیلوگرم، سانتی‌متر، میلی‌لیتر',
    'hi': 'मीट्रिक · किग्रा, सेमी, मिली',
    'id': 'Metrik · kg, cm, ml',
    'ms': 'Metrik · kg, cm, ml',
    'ja': 'メートル法 · kg、cm、ml',
    'ko': '미터법 · kg, cm, ml',
    'zh-Hans': '公制 · 千克、厘米、毫升',
    'zh-Hant': '公制 · 公斤、公分、毫升',
    'ru': 'Метрическая · кг, см, мл',
    'bn': 'মেট্রিক · কেজি, সেমি, মিলি',
    'vi': 'Hệ mét · kg, cm, ml',
    'th': 'เมตริก · กก., ซม., มล.',
    'pl': 'Metryczny · kg, cm, ml',
    'nl': 'Metrisch · kg, cm, ml',
    'uk': 'Метрична · кг, см, мл',
  },
  'Imperial · lb, ft': {
    'ar': 'إمبراطوري · رطل، قدم',
    'en': 'Imperial · lb, ft',
    'fr': 'Impérial · lb, ft',
    'es': 'Sistema imperial · lb, ft',
    'tr': 'İngiliz · lb, ft',
    'de': 'Angloamerikanisch · lb, ft',
    'it': 'Imperiale · lb, ft',
    'pt-BR': 'Sistema imperial · lb, ft',
    'pt-PT': 'Sistema imperial · lb, ft',
    'ur': 'امپیریل · پاؤنڈ، فٹ',
    'fa': 'امپریال · پوند، فوت',
    'hi': 'इम्पीरियल · पौंड, फ़ुट',
    'id': 'Satuan imperial · lb, ft',
    'ms': 'Imperial · lb, kaki',
    'ja': 'ヤード・ポンド法 · lb、ft',
    'ko': '야드파운드법 · lb, ft',
    'zh-Hans': '英制 · 磅、英尺',
    'zh-Hant': '英制 · 磅、英尺',
    'ru': 'Имперская · фунты, футы',
    'bn': 'ইম্পেরিয়াল · পাউন্ড, ফুট',
    'vi': 'Hệ Anh · lb, ft',
    'th': 'อิมพีเรียล · ปอนด์, ฟุต',
    'pl': 'Imperialny · lb, ft',
    'nl': 'Imperiaal · lb, ft',
    'uk': 'Імперська · фунти, фути',
  },
  'Loading…': {
    'ar': 'جارٍ التحميل…',
    'en': 'Loading…',
    'fr': 'Chargement…',
    'es': 'Cargando…',
    'tr': 'Yükleniyor…',
    'de': 'Wird geladen…',
    'it': 'Caricamento…',
    'pt-BR': 'Carregando…',
    'pt-PT': 'A carregar…',
    'ur': 'لوڈ ہو رہا ہے…',
    'fa': 'در حال بارگذاری…',
    'hi': 'लोड हो रहा है…',
    'id': 'Memuat…',
    'ms': 'Memuatkan…',
    'ja': '読み込み中…',
    'ko': '불러오는 중…',
    'zh-Hans': '加载中…',
    'zh-Hant': '載入中…',
    'ru': 'Загрузка…',
    'bn': 'লোড হচ্ছে…',
    'vi': 'Đang tải…',
    'th': 'กำลังโหลด…',
    'pl': 'Wczytywanie…',
    'nl': 'Laden…',
    'uk': 'Завантаження…',
  },
  'Health goals': {
    'ar': 'الأهداف الصحية',
    'en': 'Health goals',
    'fr': 'Objectifs de santé',
    'es': 'Objetivos de salud',
    'tr': 'Sağlık hedefleri',
    'de': 'Gesundheitsziele',
    'it': 'Obiettivi di salute',
    'pt-BR': 'Metas de saúde',
    'pt-PT': 'Objetivos de saúde',
    'ur': 'صحت کے اہداف',
    'fa': 'اهداف سلامت',
    'hi': 'स्वास्थ्य लक्ष्य',
    'id': 'Sasaran kesehatan',
    'ms': 'Matlamat kesihatan',
    'ja': '健康目標',
    'ko': '건강 목표',
    'zh-Hans': '健康目标',
    'zh-Hant': '健康目標',
    'ru': 'Цели здоровья',
    'bn': 'স্বাস্থ্য লক্ষ্য',
    'vi': 'Mục tiêu sức khỏe',
    'th': 'เป้าหมายสุขภาพ',
    'pl': 'Cele zdrowotne',
    'nl': 'Gezondheidsdoelen',
    'uk': 'Цілі здоров’я',
  },
};
