/// Reviewed cuisine-navigation copy for the five authored app languages.
abstract final class RuntimeCopyCuisines {
  static const values = <String, Map<String, String>>{
    'Ingredients': {
      'ar': 'المكوّنات',
      'en': 'Ingredients',
      'fr': 'Ingrédients',
      'es': 'Ingredientes',
      'tr': 'Malzemeler',
    },
    'Method': {
      'ar': 'الطريقة',
      'en': 'Method',
      'fr': 'Préparation',
      'es': 'Preparación',
      'tr': 'Hazırlanışı',
    },
    'Per serving': {
      'ar': 'لكل حصة',
      'en': 'Per serving',
      'fr': 'Par portion',
      'es': 'Por porción',
      'tr': 'Porsiyon başına',
    },
    'kcal': {
      'ar': 'سعرة حرارية',
      'en': 'kcal',
      'fr': 'kcal',
      'es': 'kcal',
      'tr': 'kcal',
    },
    'Search recipes or tags': {
      'ar': 'ابحث عن وصفة أو وسم',
      'en': 'Search recipes or tags',
      'fr': 'Rechercher des recettes ou des étiquettes',
      'es': 'Buscar recetas o etiquetas',
      'tr': 'Tarif veya etiket ara',
    },
    '{visible} of {total} recipes': {
      'ar': '{visible} من {total} وصفة',
      'en': '{visible} of {total} recipes',
      'fr': '{visible} recettes sur {total}',
      'es': '{visible} de {total} recetas',
      'tr': '{total} tariften {visible} tanesi',
    },
    '{count} min': {
      'ar': '{count} دقيقة',
      'en': '{count} min',
      'fr': '{count} min',
      'es': '{count} min',
      'tr': '{count} dk',
    },
    'All cuisines': {
      'ar': 'جميع المطابخ',
      'en': 'All cuisines',
      'fr': 'Toutes les cuisines',
      'es': 'Todas las cocinas',
      'tr': 'Tüm mutfaklar',
    },
    'Choose cuisine': {
      'ar': 'اختر المطبخ',
      'en': 'Choose cuisine',
      'fr': 'Choisir une cuisine',
      'es': 'Elegir cocina',
      'tr': 'Mutfak seç',
    },
    'Global recipes': {
      'ar': 'وصفات عالمية',
      'en': 'Global recipes',
      'fr': 'Recettes du monde',
      'es': 'Recetas internacionales',
      'tr': 'Dünya mutfağı',
    },
    'Egyptian cuisine': {
      'ar': 'المطبخ المصري',
      'en': 'Egyptian cuisine',
      'fr': 'Cuisine égyptienne',
      'es': 'Cocina egipcia',
      'tr': 'Mısır mutfağı',
    },
    'Levantine cuisine': {
      'ar': 'المطبخ الشامي',
      'en': 'Levantine cuisine',
      'fr': 'Cuisine levantine',
      'es': 'Cocina levantina',
      'tr': 'Levant mutfağı',
    },
    'Palestinian cuisine': {
      'ar': 'المطبخ الفلسطيني',
      'en': 'Palestinian cuisine',
      'fr': 'Cuisine palestinienne',
      'es': 'Cocina palestina',
      'tr': 'Filistin mutfağı',
    },
    'Gulf cuisine': {
      'ar': 'المطبخ الخليجي',
      'en': 'Gulf cuisine',
      'fr': 'Cuisine du Golfe',
      'es': 'Cocina del Golfo',
      'tr': 'Körfez mutfağı',
    },
    'Iraqi cuisine': {
      'ar': 'المطبخ العراقي',
      'en': 'Iraqi cuisine',
      'fr': 'Cuisine irakienne',
      'es': 'Cocina iraquí',
      'tr': 'Irak mutfağı',
    },
    'Maghrebi cuisine': {
      'ar': 'المطبخ المغاربي',
      'en': 'Maghrebi cuisine',
      'fr': 'Cuisine maghrébine',
      'es': 'Cocina magrebí',
      'tr': 'Mağrip mutfağı',
    },
    'Algerian cuisine': {
      'ar': 'المطبخ الجزائري',
      'en': 'Algerian cuisine',
      'fr': 'Cuisine algérienne',
      'es': 'Cocina argelina',
      'tr': 'Cezayir mutfağı',
    },
    'Moroccan cuisine': {
      'ar': 'المطبخ المغربي',
      'en': 'Moroccan cuisine',
      'fr': 'Cuisine marocaine',
      'es': 'Cocina marroquí',
      'tr': 'Fas mutfağı',
    },
    'Tunisian cuisine': {
      'ar': 'المطبخ التونسي',
      'en': 'Tunisian cuisine',
      'fr': 'Cuisine tunisienne',
      'es': 'Cocina tunecina',
      'tr': 'Tunus mutfağı',
    },
    'Spanish cuisine': {
      'ar': 'المطبخ الإسباني',
      'en': 'Spanish cuisine',
      'fr': 'Cuisine espagnole',
      'es': 'Cocina española',
      'tr': 'İspanyol mutfağı',
    },
    'Mexican cuisine': {
      'ar': 'المطبخ المكسيكي',
      'en': 'Mexican cuisine',
      'fr': 'Cuisine mexicaine',
      'es': 'Cocina mexicana',
      'tr': 'Meksika mutfağı',
    },
    'Central American cuisine': {
      'ar': 'مطبخ أمريكا الوسطى',
      'en': 'Central American cuisine',
      'fr': 'Cuisine d’Amérique centrale',
      'es': 'Cocina centroamericana',
      'tr': 'Orta Amerika mutfağı',
    },
    'Costa Rican cuisine': {
      'ar': 'المطبخ الكوستاريكي',
      'en': 'Costa Rican cuisine',
      'fr': 'Cuisine costaricienne',
      'es': 'Cocina costarricense',
      'tr': 'Kosta Rika mutfağı',
    },
    'Honduran cuisine': {
      'ar': 'المطبخ الهندوراسي',
      'en': 'Honduran cuisine',
      'fr': 'Cuisine hondurienne',
      'es': 'Cocina hondureña',
      'tr': 'Honduras mutfağı',
    },
    'South American cuisine': {
      'ar': 'مطبخ أمريكا الجنوبية',
      'en': 'South American cuisine',
      'fr': 'Cuisine sud-américaine',
      'es': 'Cocina sudamericana',
      'tr': 'Güney Amerika mutfağı',
    },
    'Caribbean cuisine': {
      'ar': 'المطبخ الكاريبي',
      'en': 'Caribbean cuisine',
      'fr': 'Cuisine caribéenne',
      'es': 'Cocina caribeña',
      'tr': 'Karayip mutfağı',
    },
    'American cuisine': {
      'ar': 'المطبخ الأمريكي',
      'en': 'American cuisine',
      'fr': 'Cuisine américaine',
      'es': 'Cocina estadounidense',
      'tr': 'Amerikan mutfağı',
    },
    'Canadian cuisine': {
      'ar': 'المطبخ الكندي',
      'en': 'Canadian cuisine',
      'fr': 'Cuisine canadienne',
      'es': 'Cocina canadiense',
      'tr': 'Kanada mutfağı',
    },
    'British cuisine': {
      'ar': 'المطبخ البريطاني',
      'en': 'British cuisine',
      'fr': 'Cuisine britannique',
      'es': 'Cocina británica',
      'tr': 'Britanya mutfağı',
    },
    'Irish cuisine': {
      'ar': 'المطبخ الأيرلندي',
      'en': 'Irish cuisine',
      'fr': 'Cuisine irlandaise',
      'es': 'Cocina irlandesa',
      'tr': 'İrlanda mutfağı',
    },
    'Australian cuisine': {
      'ar': 'المطبخ الأسترالي',
      'en': 'Australian cuisine',
      'fr': 'Cuisine australienne',
      'es': 'Cocina australiana',
      'tr': 'Avustralya mutfağı',
    },
    'New Zealand cuisine': {
      'ar': 'مطبخ نيوزيلندا',
      'en': 'New Zealand cuisine',
      'fr': 'Cuisine néo-zélandaise',
      'es': 'Cocina neozelandesa',
      'tr': 'Yeni Zelanda mutfağı',
    },
    'French cuisine': {
      'ar': 'المطبخ الفرنسي',
      'en': 'French cuisine',
      'fr': 'Cuisine française',
      'es': 'Cocina francesa',
      'tr': 'Fransız mutfağı',
    },
    'Québécois cuisine': {
      'ar': 'مطبخ كيبيك',
      'en': 'Québécois cuisine',
      'fr': 'Cuisine québécoise',
      'es': 'Cocina quebequesa',
      'tr': 'Québec mutfağı',
    },
    'West African cuisine': {
      'ar': 'مطبخ غرب أفريقيا',
      'en': 'West African cuisine',
      'fr': 'Cuisine ouest-africaine',
      'es': 'Cocina de África occidental',
      'tr': 'Batı Afrika mutfağı',
    },
    'Turkish cuisine': {
      'ar': 'المطبخ التركي',
      'en': 'Turkish cuisine',
      'fr': 'Cuisine turque',
      'es': 'Cocina turca',
      'tr': 'Türk mutfağı',
    },
  };
}
