part of 'runtime_copy_coach_food_cards.dart';

const _coachFoodCardRows1 = <String, List<String>>{
  "pt-BR": [
    "Desconhecido",
    "Estimado",
    "Detalhes do alimento",
    "Detalhes nutricionais",
    "Ações do comprovante",
    "Porção estimada",
    "Foto indisponível",
    "Sim, registrar",
    "Ajustar",
    "Processando…",
    "Fontes",
    "Confiança na fonte",
    "Confiança na identificação do alimento",
    "Confiança na quantidade",
    "Ver no registro diário",
    "Este comprovante de alimento não está disponível. Confira seu registro diário.",
    "Sua conta mudou. Volte ao Coach para continuar.",
    "Não foi possível concluir a ação. Sua revisão foi mantida.",
    "Esta refeição mudou. Confira o registro atual antes de editar ou desfazer.",
    "Esta revisão está encerrada.",
    "Registro desfeito",
    "Refeição atualizada",
    "Registro removido",
    "Refeição movida",
    "Registro de calorias salvo",
    "Registro nutricional salvo",
    "Comida desconhecida",
    "Refeição",
    "Certo! Vou registrar {meal}. Veja o que entendi:",
    "Posso registrar isso em {meal}?",
    "{meal} registrado",
    "Referência",
    "Rótulo do alimento",
    "Seus valores fixos",
    "Receita calculada",
    "Proteína",
    "Carboidratos",
    "Gordo",
    "Açúcar",
    "Cálcio",
    "Fósforo",
    "Ferro",
    "Vitamina C",
    "ml",
    "1 unidade",
    "{count} unidades",
    "g",
  ],
  "pt-PT": [
    "Desconhecido",
    "Estimado",
    "Detalhes do alimento",
    "Detalhes nutricionais",
    "Ações do comprovativo",
    "Porção estimada",
    "Foto indisponível",
    "Sim, registar",
    "Ajustar",
    "A processar…",
    "Fontes",
    "Confiança na fonte",
    "Confiança na identificação do alimento",
    "Confiança na quantidade",
    "Ver no registo diário",
    "Este comprovativo alimentar não está disponível. Consulte o seu registo diário.",
    "A sua conta mudou. Volte ao Coach para continuar.",
    "Não foi possível concluir a ação. A sua revisão foi mantida.",
    "Esta refeição mudou. Consulte o registo atual antes de editar ou anular.",
    "Esta revisão está encerrada.",
    "Registo anulado",
    "Refeição atualizada",
    "Registo removido",
    "Refeição movida",
    "Registo de calorias guardado",
    "Registo nutricional guardado",
    "Comida desconhecida",
    "Refeição",
    "Muito bem! Vou registar {meal}. Eis o que percebi:",
    "Devo registar isto em {meal}?",
    "{meal} registado",
    "Referência",
    "Rótulo alimentar",
    "Os seus valores fixos",
    "Receita calculada",
    "Proteína",
    "Carboidratos",
    "Gordo",
    "Açúcar",
    "Cálcio",
    "Fósforo",
    "Ferro",
    "Vitamina C",
    "ml",
    "1 unidade",
    "{count} unidades",
    "g",
  ],
  "ur": [
    "نامعلوم",
    "تخمینی",
    "غذا کی تفصیلات",
    "غذائی اجزا کی تفصیلات",
    "رسید کے اقدامات",
    "تخمینی مقدار",
    "تصویر دستیاب نہیں ہے۔",
    "ہاں، درج کریں",
    "ترمیم کریں",
    "کارروائی جاری ہے…",
    "ماخذ",
    "ماخذ پر اعتماد",
    "غذا کی شناخت پر اعتماد",
    "مقدار پر اعتماد",
    "روزانہ کے ریکارڈ میں دیکھیں",
    "اس غذا کی رسید دستیاب نہیں۔ اپنا روزانہ کا ریکارڈ دیکھیں۔",
    "آپ کا اکاؤنٹ بدل گیا ہے۔ جاری رکھنے کے لیے کوچ پر واپس جائیں۔",
    "کارروائی مکمل نہیں ہو سکی۔ آپ کا جائزہ محفوظ ہے۔",
    "یہ کھانا بدل گیا ہے۔ ترمیم یا واپسی سے پہلے موجودہ اندراج دیکھیں۔",
    "یہ جائزہ بند ہو چکا ہے۔",
    "اندراج واپس لے لیا گیا",
    "کھانا اپ ڈیٹ ہو گیا",
    "اندراج ہٹا دیا گیا",
    "کھانا منتقل کر دیا گیا",
    "کیلوریز کا اندراج محفوظ ہو گیا",
    "غذائی اجزا کا اندراج محفوظ ہو گیا",
    "نامعلوم کھانا",
    "کھانا",
    "ٹھیک ہے! میں آپ کا {meal} درج کروں گا۔ میں نے یہ سمجھا ہے:",
    "کیا اسے آپ کے {meal} میں درج کر دوں؟",
    "{meal} درج ہو گیا",
    "حوالہ",
    "غذا کا لیبل",
    "آپ کی مقررہ قدریں",
    "حساب شدہ ترکیب",
    "پروٹین",
    "کاربوہائیڈریٹ",
    "موٹا",
    "شکر",
    "کیلشیم",
    "فاسفورس",
    "لوہا",
    "وٹامن سی",
    "ملی لیٹر",
    "1 عدد",
    "{count} عدد",
    "گرام",
  ],
  "fa": [
    "نامشخص",
    "تخمینی",
    "جزئیات غذا",
    "جزئیات مواد مغذی",
    "اقدام‌های رسید",
    "مقدار تخمینی",
    "عکس در دسترس نیست",
    "بله، ثبت کن",
    "اصلاح",
    "در حال انجام…",
    "منابع",
    "اطمینان به منبع",
    "اطمینان به تشخیص غذا",
    "اطمینان به مقدار",
    "نمایش در گزارش روزانه",
    "این رسید غذایی در دسترس نیست. گزارش روزانه‌تان را بررسی کنید.",
    "حساب شما تغییر کرده است. برای ادامه به مربی برگردید.",
    "اقدام کامل نشد. بررسی شما حفظ شده است.",
    "این وعده تغییر کرده است. پیش از ویرایش یا لغو، ثبت فعلی را بررسی کنید.",
    "این بررسی بسته شده است.",
    "ثبت لغو شد",
    "وعده به‌روزرسانی شد",
    "ثبت حذف شد",
    "وعده منتقل شد",
    "ثبت کالری ذخیره شد",
    "ثبت مواد مغذی ذخیره شد",
    "غذای ناشناخته",
    "وعده غذایی",
    "بسیار خوب! {meal} شما را ثبت می‌کنم. برداشت من این است:",
    "این را در {meal} شما ثبت کنم؟",
    "{meal} ثبت شد",
    "مرجع",
    "برچسب غذایی",
    "مقادیر ثابت شما",
    "دستور غذای محاسبه‌شده",
    "پروتئین",
    "کربوهیدرات ها",
    "چربی",
    "شکر",
    "کلسیم",
    "فسفر",
    "آهن",
    "ویتامین C",
    "میلی لیتر",
    "1 عدد",
    "{count} عدد",
    "گرم",
  ],
  "hi": [
    "अज्ञात",
    "अनुमानित",
    "खाद्य पदार्थ का विवरण",
    "पोषक तत्वों का विवरण",
    "रसीद की कार्रवाइयाँ",
    "अनुमानित मात्रा",
    "फ़ोटो अनुपलब्ध",
    "हाँ, दर्ज करें",
    "बदलाव करें",
    "कार्रवाई जारी है…",
    "स्रोत",
    "स्रोत पर भरोसा",
    "खाद्य पदार्थ की पहचान पर भरोसा",
    "मात्रा पर भरोसा",
    "दैनिक लॉग में देखें",
    "इस भोजन की रसीद उपलब्ध नहीं है। अपना दैनिक लॉग देखें।",
    "आपका खाता बदल गया है। जारी रखने के लिए कोच पर वापस जाएँ।",
    "कार्रवाई पूरी नहीं हो सकी। आपकी समीक्षा सुरक्षित है।",
    "यह भोजन बदल गया है। बदलाव करने या पूर्ववत करने से पहले मौजूदा प्रविष्टि देखें।",
    "यह समीक्षा बंद हो गई है।",
    "प्रविष्टि पूर्ववत की गई",
    "भोजन अपडेट किया गया",
    "प्रविष्टि हटाई गई",
    "भोजन स्थानांतरित किया गया",
    "कैलोरी की प्रविष्टि सहेजी गई",
    "पोषक तत्वों की प्रविष्टि सहेजी गई",
    "अज्ञात भोजन",
    "भोजन",
    "ठीक है! मैं आपका {meal} दर्ज करूँगा। मैंने यह समझा है:",
    "क्या इसे आपके {meal} में दर्ज करूँ?",
    "{meal} दर्ज किया गया",
    "संदर्भ",
    "खाद्य लेबल",
    "आपके तय मान",
    "गणना की गई रेसिपी",
    "प्रोटीन",
    "कार्ब्स",
    "मोटा",
    "चीनी",
    "कैल्शियम",
    "फास्फोरस",
    "लोहा",
    "विटामिन C",
    "एमएल",
    "1 नग",
    "{count} नग",
    "ग्राम",
  ],
  "id": [
    "Tidak diketahui",
    "Perkiraan",
    "Detail makanan",
    "Detail zat gizi",
    "Tindakan bukti pencatatan",
    "Porsi perkiraan",
    "Foto tidak tersedia",
    "Ya, catat",
    "Sesuaikan",
    "Sedang diproses…",
    "Sumber",
    "Keyakinan pada sumber",
    "Keyakinan pada identifikasi makanan",
    "Keyakinan pada jumlah",
    "Lihat di Catatan Harian",
    "Bukti pencatatan makanan ini tidak tersedia. Periksa Catatan Harian Anda.",
    "Akun Anda telah berubah. Kembali ke Coach untuk melanjutkan.",
    "Tindakan tidak dapat diselesaikan. Tinjauan Anda tetap tersimpan.",
    "Makanan ini telah berubah. Periksa entri saat ini sebelum mengedit atau mengurungkan.",
    "Tinjauan ini telah ditutup.",
    "Entri diurungkan",
    "Makanan diperbarui",
    "Entri dihapus",
    "Makanan dipindahkan",
    "Entri kalori disimpan",
    "Entri zat gizi disimpan",
    "Makanan yang tidak diketahui",
    "Makan",
    "Baik! Saya akan mencatat {meal} Anda. Ini yang saya pahami:",
    "Boleh saya catat ini ke {meal} Anda?",
    "{meal} dicatat",
    "Referensi",
    "Label makanan",
    "Nilai tetap Anda",
    "Resep yang dihitung",
    "Protein",
    "Karbohidrat",
    "Gemuk",
    "Gula",
    "Kalsium",
    "Fosfor",
    "Besi",
    "Vitamin C",
    "ml",
    "1 buah",
    "{count} buah",
    "g",
  ],
};
