part of 'runtime_copy_community_expansion.dart';

const _communityExpansionWestMoreRows = <String, List<String>>{
  'pt-PT': <String>[
    "{actor} aceitou o teu pedido de amizade",
    "{actor} comentou a tua publicação",
    "{actor} começou a seguir-te",
    "{actor} gostou da tua publicação",
    "{actor} mencionou-te numa publicação",
    "{actor} respondeu ao teu comentário",
    "{actor} enviou-te um pedido de amizade",
    "{inviterName} convidou-te a aderir ao BIL",
    "{total} votos",
    "10 mil passos",
    "Um espaço acolhedor para progresso de fitness seguro e gradual.",
    "Utilização do AI Coach",
    "Aceitar convite",
    "As publicações dos teus amigos aceites aparecerão aqui.",
    "Ao aceitar, fica registado quem te convidou. Isto, por si só, não atribui Gold.",
    "Adicionar sondagem",
    "Adicionar opção",
    "Permitir várias escolhas",
    "Já existe outro convite associado a esta conta.",
    "Faz uma pergunta com 2–6 opções.",
    "Atividade BIL Gold",
    "Recompensas BIL",
    "O BIL não conseguiu verificar este convite em segurança.",
    "O BIL não conseguiu verificar em segurança o estado das tuas recompensas.",
    "Convite BIL",
    "Ajuste de saldo",
    "Sê respeitoso, evita dados de saúde privados e segue a política da Comunidade.",
    "Fitness para principiantes",
    "Dormir melhor",
    "Cria um hábito consistente de caminhada e incentivem-se mutuamente.",
    "Atualização do desafio",
    "Escolhe uma opção",
    "Escolhe uma ou mais opções",
    "Escolhe que secções sociais os outros membros podem ver. Os dados de saúde nunca são incluídos.",
    "Círculo — opcional",
    "Círculos",
    "Etiqueta de cidade ou local",
    "Resgatado",
    "Comentários e menções",
    "Nível da Comunidade",
    "Privacidade do perfil da Comunidade",
    "Missão da Comunidade",
    "Recompensa de missão da Comunidade",
    "Tópicos da Comunidade",
    "Conclui a ação verificada da Comunidade para progredir.",
    "Completa o teu perfil da Comunidade",
    "Não foi possível aceitar este convite em segurança. Tenta novamente.",
    "Não foi possível resgatar esta recompensa em segurança. Tenta novamente.",
    "Não foi possível carregar mais histórico.",
    "Não foi possível registar o teu voto. Tenta novamente.",
    "Não foi possível pesquisar menções agora.",
    "Não foi possível atualizar este Círculo em segurança. Tenta novamente.",
    "Não foi possível atualizar este tópico em segurança. Tenta novamente.",
    "Cria uma publicação valiosa",
    "Criar uma conta",
    "Diário",
    "Conversem sobre treino de força, consistência e recuperação.",
    "Ganhar",
    "Ganho",
    "As entradas BIL Gold ganhas e utilizadas aparecerão aqui.",
    "Editar perfil",
    "Conclui a sondagem: adiciona uma pergunta e 2–6 opções diferentes.",
    "Seguir",
    "Segue membros para veres aqui as publicações aprovadas deles.",
    "Seguidores",
    "A seguir",
    "Para ti",
    "Pedidos de amizade, ligações aceites e mensagens não lidas aparecerão aqui.",
    "Ir",
    "Vista em grelha",
    "Alimentação saudável",
    "Ocultar respostas",
    "Convite aceite e amizade criada. Gold continua condicionado a uma conta nova e às verificações de integridade do servidor.",
    "Convite guardado.",
    "Convite indisponível",
    "Convidar um amigo",
    "Aderir",
    "Adere a um Círculo para publicar nele.",
    "Sair",
    "Gostos e guardados",
    "Vista em lista",
    "Carregar mais tópicos de comentários",
    "Carregar mais respostas",
    "Localização — opcional",
    "Mencionar pessoas — opcional",
    "Menciona até 10 membros descobríveis da Comunidade. Só recebem notificação depois de a publicação ser aprovada.",
    "Novo",
    "Novo emblema ganho",
    "Novo comentário na tua publicação",
    "Novo seguidor",
    "Novo pedido de amizade",
    "Nova publicação",
    "Nova resposta ao teu comentário",
    "Sem Círculo",
    "Ainda não há atividade Gold",
    "Não há missões ativas neste momento",
    "Ainda não há publicações aprovadas neste Círculo.",
    "Ainda não há publicações aprovadas neste tópico.",
    "Ainda não há publicações aprovadas. Inicia a primeira conversa.",
    "Ainda não há atualizações nesta categoria.",
    "Ainda não há publicações visíveis.",
    "Ainda não há nada personalizado. Segue pessoas, tópicos ou Círculos para moldares este feed.",
    "Nada para mostrar aqui por agora.",
    "Desativado por predefinição. BIL Gold e Community XP permanecem separados da tua subscrição.",
    "Opção {index}",
    "Apenas texto opcional. O BIL não solicita GPS para publicações da Comunidade.",
    "Sondagem",
    "Sondagem encerrada",
    "Pergunta da sondagem",
    "Publicar no Círculo",
    "As publicações são privadas neste perfil.",
    "A qualidade, a moderação e o envolvimento significativo são verificados primeiro.",
    "Missão concluída",
    "Ramadão e jejum",
    "Pronto para resgatar",
    "Remover opção",
    "Recompensa já resgatada.",
    "Recompensa resgatada.",
    "As regras de recompensa só são ativadas pelo BIL após verificação no servidor e quando as verificações de segurança estão prontas.",
    "Recompensas",
    "Recompensas indisponíveis",
    "As recompensas só são desbloqueadas quando a relação de amizade verificada cumpre os requisitos.",
    "Corrida",
    "Pesquisar nome de utilizador",
    "Visto",
    "Configura a tua identidade pública e as tuas escolhas de privacidade.",
    "Partilha rotinas e experiências de jejum com respeito cultural.",
    "Partilha ideias práticas de refeições e hábitos alimentares sustentáveis.",
    "Partilha progresso, rotinas e incentivo na corrida.",
    "Partilha progresso sustentável e apoio sem comparação nem pressão.",
    "Mostrar seguidores",
    "Mostrar quem segues",
    "Mostrar amigos",
    "Mostrar nível de adesão",
    "Mostrar publicações no meu perfil",
    "Inicia sessão para aceitar",
    "Inicia sessão para ver BIL Gold e recompensas.",
    "Inicia sessão para ver perfis da Comunidade.",
    "Alguém gostou da tua publicação",
    "Moeda da Comunidade utilizável",
    "Iniciar uma publicação",
    "Principiante",
    "Apoia melhores rotinas de sono sem alegações médicas.",
    "Este convite é inválido ou expirou.",
    "Este convite é inválido, expirou ou já foi utilizado.",
    "Este convite está indisponível.",
    "Este convite já foi utilizado.",
    "Esta lista está indisponível neste momento.",
    "Esta recompensa não está disponível neste momento.",
    "Os tópicos estão indisponíveis neste momento. Ainda podes publicar.",
    "Tópicos — escolhe até 3",
    "Os convites BIL rastreados ainda não estão ativos.",
    "Os convites rastreados ainda não estão ativos.",
    "Utilizado",
    "Ver {count} respostas",
    "Votar",
    "Semanal",
    "Percurso de perda de peso",
    "Não podes aceitar o teu próprio convite.",
    "Ganhaste uma recompensa da Comunidade",
    "Foste mencionado numa publicação",
    "O teu pedido de amizade foi aceite",
    "A tua publicação foi guardada",
    "São amigos — ver perfil",
    "seguidores",
    "membros",
    "publicações",
  ],
  'pl': <String>[
    "{actor} zaakceptował(a) Twoją prośbę o dodanie do znajomych",
    "{actor} skomentował(a) Twój post",
    "{actor} obserwuje Cię od teraz",
    "{actor} polubił(a) Twój post",
    "{actor} wspomniał(a) o Tobie w poście",
    "{actor} odpowiedział(a) na Twój komentarz",
    "{actor} wysłał(a) Ci prośbę o dodanie do znajomych",
    "{inviterName} zaprasza Cię do BIL",
    "{total} głosów",
    "10 tys. kroków",
    "Przyjazne miejsce do bezpiecznych i stopniowych postępów w aktywności.",
    "Korzystanie z AI Coach",
    "Zaakceptuj zaproszenie",
    "Posty zaakceptowanych znajomych pojawią się tutaj.",
    "Akceptacja zapisuje, kto Cię zaprosił. Sama w sobie nie przyznaje Gold.",
    "Dodaj ankietę",
    "Dodaj opcję",
    "Zezwalaj na wiele odpowiedzi",
    "Z tym kontem jest już powiązane inne zaproszenie.",
    "Zadaj jedno pytanie z 2–6 opcjami.",
    "Aktywność BIL Gold",
    "Nagrody BIL",
    "BIL nie mógł bezpiecznie zweryfikować tego zaproszenia.",
    "BIL nie mógł bezpiecznie zweryfikować stanu Twoich nagród.",
    "Zaproszenie BIL",
    "Korekta salda",
    "Okazuj szacunek, unikaj prywatnych danych zdrowotnych i przestrzegaj zasad Społeczności.",
    "Fitness dla początkujących",
    "Lepszy sen",
    "Buduj regularny nawyk chodzenia i wspierajcie się nawzajem.",
    "Aktualizacja wyzwania",
    "Wybierz jedną opcję",
    "Wybierz jedną lub więcej opcji",
    "Wybierz, które sekcje społecznościowe mogą widzieć inni członkowie. Dane zdrowotne nigdy nie są dołączane.",
    "Krąg — opcjonalnie",
    "Kręgi",
    "Etykieta miasta lub miejsca",
    "Odebrano",
    "Komentarze i wzmianki",
    "Poziom Społeczności",
    "Prywatność profilu Społeczności",
    "Misja Społeczności",
    "Nagroda za misję Społeczności",
    "Tematy Społeczności",
    "Wykonaj zweryfikowane działanie Społeczności, aby zrobić postęp.",
    "Uzupełnij profil Społeczności",
    "Nie udało się bezpiecznie zaakceptować tego zaproszenia. Spróbuj ponownie.",
    "Nie udało się bezpiecznie odebrać tej nagrody. Spróbuj ponownie.",
    "Nie udało się wczytać dalszej historii.",
    "Nie udało się zapisać Twojego głosu. Spróbuj ponownie.",
    "Nie można teraz wyszukiwać wzmianek.",
    "Nie udało się bezpiecznie zaktualizować tego Kręgu. Spróbuj ponownie.",
    "Nie udało się bezpiecznie zaktualizować tego tematu. Spróbuj ponownie.",
    "Utwórz wartościowy post",
    "Utwórz konto",
    "Codziennie",
    "Rozmawiaj o treningu siłowym, regularności i regeneracji.",
    "Zdobywaj",
    "Zdobyto",
    "Zdobyte i wykorzystane wpisy BIL Gold pojawią się tutaj.",
    "Edytuj profil",
    "Dokończ ankietę: dodaj pytanie i 2–6 różnych opcji.",
    "Obserwuj",
    "Obserwuj członków, aby widzieć tutaj ich zatwierdzone posty.",
    "Obserwujący",
    "Obserwowani",
    "Dla Ciebie",
    "Prośby o dodanie do znajomych, zaakceptowane kontakty i nieprzeczytane wiadomości pojawią się tutaj.",
    "Przejdź",
    "Widok siatki",
    "Zdrowe odżywianie",
    "Ukryj odpowiedzi",
    "Zaproszenie zaakceptowane i znajomość utworzona. Gold nadal wymaga nowego konta i pomyślnego sprawdzenia integralności przez serwer.",
    "Zaproszenie zapisane.",
    "Zaproszenie niedostępne",
    "Zaproś znajomego",
    "Dołącz",
    "Dołącz do Kręgu, aby publikować w jego ramach.",
    "Opuść",
    "Polubienia i zapisane",
    "Widok listy",
    "Wczytaj więcej wątków komentarzy",
    "Wczytaj więcej odpowiedzi",
    "Lokalizacja — opcjonalnie",
    "Wzmianka o osobach — opcjonalnie",
    "Wspomnij maksymalnie 10 widocznych członków Społeczności. Powiadomienie otrzymają dopiero po zatwierdzeniu posta.",
    "Nowe",
    "Zdobyto nową odznakę",
    "Nowy komentarz do Twojego posta",
    "Nowy obserwujący",
    "Nowa prośba o dodanie do znajomych",
    "Nowy post",
    "Nowa odpowiedź na Twój komentarz",
    "Bez Kręgu",
    "Brak aktywności Gold",
    "Brak aktywnych misji",
    "Nie ma jeszcze zatwierdzonych postów w tym Kręgu.",
    "Nie ma jeszcze zatwierdzonych postów w tym temacie.",
    "Nie ma jeszcze zatwierdzonych postów. Rozpocznij pierwszą rozmowę.",
    "Brak aktualizacji w tej kategorii.",
    "Brak widocznych postów.",
    "Brak spersonalizowanych treści. Obserwuj osoby, tematy lub Kręgi, aby kształtować ten kanał.",
    "Na razie nie ma tu nic do pokazania.",
    "Domyślnie wyłączone. BIL Gold i Community XP pozostają oddzielone od subskrypcji.",
    "Opcja {index}",
    "Tylko opcjonalny tekst. BIL nie prosi o GPS w postach Społeczności.",
    "Ankieta",
    "Ankieta zamknięta",
    "Pytanie ankiety",
    "Opublikuj w Kręgu",
    "Posty są prywatne w tym profilu.",
    "Najpierw sprawdzane są jakość, moderacja i wartościowe zaangażowanie.",
    "Misja ukończona",
    "Ramadan i post",
    "Gotowe do odebrania",
    "Usuń opcję",
    "Nagroda została już odebrana.",
    "Nagroda odebrana.",
    "Zasady nagród są aktywowane przez BIL dopiero po weryfikacji serwerowej i przygotowaniu kontroli bezpieczeństwa.",
    "Nagrody",
    "Nagrody są niedostępne",
    "Nagrody odblokowują się dopiero po zakwalifikowaniu zweryfikowanej relacji znajomych.",
    "Bieganie",
    "Szukaj nazwy użytkownika",
    "Widziano",
    "Ustaw swoją publiczną tożsamość i wybory prywatności.",
    "Dziel się kulturowo odpowiednimi rutynami i doświadczeniami związanymi z postem.",
    "Dziel się praktycznymi pomysłami na posiłki i zrównoważonymi nawykami żywieniowymi.",
    "Dziel się postępami, rutynami i wsparciem w bieganiu.",
    "Dziel się trwałymi postępami i wsparciem bez presji porównań.",
    "Pokaż obserwujących",
    "Pokaż obserwowanych",
    "Pokaż znajomych",
    "Pokaż poziom członkostwa",
    "Pokaż posty w moim profilu",
    "Zaloguj się, aby zaakceptować",
    "Zaloguj się, aby zobaczyć BIL Gold i nagrody.",
    "Zaloguj się, aby zobaczyć profile Społeczności.",
    "Ktoś polubił Twój post",
    "Waluta Społeczności do wykorzystania",
    "Rozpocznij post",
    "Początkujący",
    "Wspieraj lepsze rutyny snu bez twierdzeń medycznych.",
    "To zaproszenie jest nieprawidłowe lub wygasło.",
    "To zaproszenie jest nieprawidłowe, wygasło lub zostało już użyte.",
    "To zaproszenie jest niedostępne.",
    "To zaproszenie zostało już użyte.",
    "Ta lista jest teraz niedostępna.",
    "Ta nagroda jest teraz niedostępna.",
    "Tematy są teraz niedostępne. Nadal możesz publikować.",
    "Tematy — wybierz maksymalnie 3",
    "Śledzone zaproszenia BIL nie są jeszcze aktywne.",
    "Śledzone zaproszenia nie są jeszcze aktywne.",
    "Wykorzystano",
    "Zobacz {count} odpowiedzi",
    "Głosuj",
    "Co tydzień",
    "Droga do utraty wagi",
    "Nie możesz zaakceptować własnego zaproszenia.",
    "Zdobyłeś(-aś) nagrodę Społeczności",
    "Wspomniano o Tobie w poście",
    "Twoja prośba o dodanie do znajomych została zaakceptowana",
    "Twój post został zapisany",
    "Jesteście znajomymi — zobacz profil",
    "obserwujący",
    "członkowie",
    "posty",
  ],
  'nl': <String>[
    "{actor} heeft je vriendschapsverzoek geaccepteerd",
    "{actor} heeft op je bericht gereageerd",
    "{actor} volgt je nu",
    "{actor} vindt je bericht leuk",
    "{actor} heeft je genoemd in een bericht",
    "{actor} heeft op je reactie geantwoord",
    "{actor} heeft je een vriendschapsverzoek gestuurd",
    "{inviterName} heeft je uitgenodigd voor BIL",
    "{total} stemmen",
    "10.000 stappen",
    "Een gastvrije plek voor veilige, geleidelijke fitnessvooruitgang.",
    "Gebruik van AI Coach",
    "Uitnodiging accepteren",
    "Berichten van geaccepteerde vrienden verschijnen hier.",
    "Accepteren legt vast wie je heeft uitgenodigd. Het levert op zichzelf geen Gold op.",
    "Poll toevoegen",
    "Optie toevoegen",
    "Meerdere keuzes toestaan",
    "Er is al een andere uitnodiging aan dit account gekoppeld.",
    "Stel één vraag met 2–6 opties.",
    "BIL Gold-activiteit",
    "BIL-beloningen",
    "BIL kon deze uitnodiging niet veilig verifiëren.",
    "BIL kon je beloningsstatus niet veilig verifiëren.",
    "BIL-uitnodiging",
    "Saldoaanpassing",
    "Wees respectvol, vermijd privégezondheidsgegevens en volg het Communitybeleid.",
    "Fitness voor beginners",
    "Beter slapen",
    "Bouw een vaste wandelgewoonte op en moedig elkaar aan.",
    "Challenge-update",
    "Kies één optie",
    "Kies één of meer opties",
    "Kies welke sociale onderdelen andere leden mogen zien. Gezondheidsgegevens worden nooit opgenomen.",
    "Circle — optioneel",
    "Circles",
    "Plaats- of locatielabel",
    "Geclaimd",
    "Reacties en vermeldingen",
    "Communityniveau",
    "Privacy van Communityprofiel",
    "Communitymissie",
    "Beloning voor Communitymissie",
    "Communityonderwerpen",
    "Voltooi de geverifieerde Communityactie om vooruitgang te boeken.",
    "Voltooi je Communityprofiel",
    "Deze uitnodiging kon niet veilig worden geaccepteerd. Probeer het opnieuw.",
    "Deze beloning kon niet veilig worden geclaimd. Probeer het opnieuw.",
    "Meer geschiedenis kon niet worden geladen.",
    "Je stem kon niet worden geregistreerd. Probeer het opnieuw.",
    "Vermeldingen kunnen nu niet worden gezocht.",
    "Deze Circle kon niet veilig worden bijgewerkt. Probeer het opnieuw.",
    "Dit onderwerp kon niet veilig worden bijgewerkt. Probeer het opnieuw.",
    "Maak een waardevol bericht",
    "Account maken",
    "Dagelijks",
    "Praat over krachttraining, consistentie en herstel.",
    "Verdienen",
    "Verdiend",
    "Verdiende en gebruikte BIL Gold-items verschijnen hier.",
    "Profiel bewerken",
    "Maak de poll af: voeg één vraag en 2–6 verschillende opties toe.",
    "Volgen",
    "Volg leden om hun goedgekeurde berichten hier te zien.",
    "Volgers",
    "Volgend",
    "Voor jou",
    "Vriendschapsverzoeken, geaccepteerde connecties en ongelezen berichten verschijnen hier.",
    "Ga",
    "Rasterweergave",
    "Gezond eten",
    "Antwoorden verbergen",
    "Uitnodiging geaccepteerd en vriendschap gemaakt. Gold blijft afhankelijk van een nieuw account en serverintegriteitscontroles.",
    "Uitnodiging opgeslagen.",
    "Uitnodiging niet beschikbaar",
    "Een vriend uitnodigen",
    "Deelnemen",
    "Word lid van een Circle om erin te posten.",
    "Verlaten",
    "Likes en opgeslagen",
    "Lijstweergave",
    "Meer reactiethreads laden",
    "Meer antwoorden laden",
    "Locatie — optioneel",
    "Mensen vermelden — optioneel",
    "Vermeld maximaal 10 vindbare Communityleden. Ze krijgen pas een melding nadat het bericht is goedgekeurd.",
    "Nieuw",
    "Nieuwe badge verdiend",
    "Nieuwe reactie op je bericht",
    "Nieuwe volger",
    "Nieuw vriendschapsverzoek",
    "Nieuw bericht",
    "Nieuw antwoord op je reactie",
    "Geen Circle",
    "Nog geen Gold-activiteit",
    "Momenteel geen actieve missies",
    "Nog geen goedgekeurde berichten in deze Circle.",
    "Nog geen goedgekeurde berichten in dit onderwerp.",
    "Nog geen goedgekeurde berichten. Start het eerste gesprek.",
    "Nog geen updates in deze categorie.",
    "Nog geen zichtbare berichten.",
    "Nog niets gepersonaliseerd. Volg mensen, onderwerpen of Circles om deze feed vorm te geven.",
    "Hier is voorlopig niets te zien.",
    "Standaard uitgeschakeld. BIL Gold en Community XP blijven gescheiden van je abonnement.",
    "Optie {index}",
    "Alleen optionele tekst. BIL vraagt geen GPS voor Communityberichten.",
    "Poll",
    "Poll gesloten",
    "Pollvraag",
    "Posten in Circle",
    "Berichten zijn privé op dit profiel.",
    "Kwaliteit, moderatie en betekenisvolle betrokkenheid worden eerst gecontroleerd.",
    "Missie voltooid",
    "Ramadan en vasten",
    "Klaar om te claimen",
    "Optie verwijderen",
    "Beloning al geclaimd.",
    "Beloning geclaimd.",
    "Beloningsregels worden door BIL pas geactiveerd na serververificatie en wanneer veiligheidscontroles gereed zijn.",
    "Beloningen",
    "Beloningen niet beschikbaar",
    "Beloningen worden alleen ontgrendeld wanneer de geverifieerde vriendschapsrelatie in aanmerking komt.",
    "Hardlopen",
    "Gebruikersnaam zoeken",
    "Gezien",
    "Stel je openbare identiteit en privacykeuzes in.",
    "Deel cultureel respectvolle vastenroutines en ervaringen.",
    "Deel praktische maaltijdideeën en duurzame eetgewoonten.",
    "Deel hardloopvooruitgang, routines en aanmoediging.",
    "Deel duurzame vooruitgang en steun zonder vergelijkingsdruk.",
    "Volgers tonen",
    "Gevolgden tonen",
    "Vrienden tonen",
    "Lidmaatschapsniveau tonen",
    "Berichten op mijn profiel tonen",
    "Meld je aan om te accepteren",
    "Meld je aan om BIL Gold en beloningen te bekijken.",
    "Meld je aan om Communityprofielen te bekijken.",
    "Iemand vindt je bericht leuk",
    "Besteedbare Communityvaluta",
    "Een bericht starten",
    "Beginner",
    "Ondersteun betere slaaproutines zonder medische claims.",
    "Deze uitnodiging is ongeldig of verlopen.",
    "Deze uitnodiging is ongeldig, verlopen of al gebruikt.",
    "Deze uitnodiging is niet beschikbaar.",
    "Deze uitnodiging is al gebruikt.",
    "Deze lijst is momenteel niet beschikbaar.",
    "Deze beloning is momenteel niet beschikbaar.",
    "Onderwerpen zijn momenteel niet beschikbaar. Je kunt nog steeds posten.",
    "Onderwerpen — kies er maximaal 3",
    "Bijgehouden BIL-uitnodigingen zijn nog niet actief.",
    "Bijgehouden uitnodigingen zijn nog niet actief.",
    "Gebruikt",
    "{count} antwoorden bekijken",
    "Stemmen",
    "Wekelijks",
    "Reis naar gewichtsverlies",
    "Je kunt je eigen uitnodiging niet accepteren.",
    "Je hebt een Communitybeloning verdiend",
    "Je bent genoemd in een bericht",
    "Je vriendschapsverzoek is geaccepteerd",
    "Je bericht is opgeslagen",
    "Jullie zijn vrienden — profiel bekijken",
    "volgers",
    "leden",
    "berichten",
  ],
};
