part of 'runtime_copy_coach_controls.dart';

const _coachControlsRows1 = <String, List<String>>{
  "pt-BR": [
    "A aparência do aplicativo foi atualizada.",
    "O idioma do aplicativo foi atualizado.",
    "Perguntar antes de alterar dados",
    "O BIL usa o Google Gemini, um serviço de IA de terceiros operado pelo Google, apenas para gerar a resposta que você solicita.",
    "Conversa",
    "O histórico de conversas é armazenado localmente neste dispositivo.",
    "Conversas",
    "Conversa atual",
    "Encerrar chamada ao vivo",
    "Foto de comida",
    "Manter esta conversa no histórico e começar uma vazia.",
    "Nova conversa",
    "Ainda não há conversas anteriores.",
    "Somente o contexto que você escolher",
    "O áudio bruto do microfone não é enviado",
    "Somente leitura",
    "Enviando",
    "Sessão encerrada com sucesso.",
    "A ação pendente foi cancelada. Nada foi alterado.",
    "A ação anterior foi desfeita.",
    "Não há nenhuma ação recente que possa ser desfeita.",
    "Esta ação precisa de permissão de gravação. Altere a configuração do escudo para continuar.",
    "O reconhecimento de voz continua separado deste consentimento para a IA remota.",
    "Alterações permitidas",
    "Você pode recusar e continuar usando os recursos locais do BIL ou retirar este consentimento mais tarde nas configurações do treinador de IA.",
    "Você mantém o controle",
    "Sua pergunta; peso, metas e medidas selecionados; refeições, nutrição, água e preferências; atividade e treino; sono e hábitos; além de até 12 mensagens recentes da conversa.",
    "A ação não foi concluída. Seus dados permaneceram inalterados; confira o valor e tente novamente.",
  ],
  "pt-PT": [
    "O aspeto da aplicação foi atualizado.",
    "O idioma da aplicação foi atualizado.",
    "Perguntar antes de alterar dados",
    "O BIL utiliza o Google Gemini, um serviço de IA de terceiros operado pela Google, apenas para gerar a resposta que solicita.",
    "Conversa",
    "O histórico de conversas é guardado localmente neste dispositivo.",
    "Conversas",
    "Conversa atual",
    "Terminar chamada em direto",
    "Fotografia de comida",
    "Manter esta conversa no histórico e iniciar uma vazia.",
    "Nova conversa",
    "Ainda não existem conversas anteriores.",
    "Apenas o contexto que escolher",
    "O áudio não processado do microfone não é enviado",
    "Apenas leitura",
    "A enviar",
    "Sessão terminada com êxito.",
    "A ação pendente foi cancelada. Nada foi alterado.",
    "A ação anterior foi anulada.",
    "Não existe nenhuma ação recente que possa ser anulada.",
    "Esta ação requer permissão de escrita. Altere a definição do escudo para continuar.",
    "O reconhecimento de voz permanece separado deste consentimento para a IA remota.",
    "Alterações permitidas",
    "Pode recusar e continuar a utilizar as funcionalidades locais do BIL ou retirar este consentimento mais tarde nas definições do treinador de IA.",
    "Mantém o controlo",
    "A sua pergunta; peso, objetivos e medidas selecionados; refeições, nutrição, água e preferências; atividade e treino; sono e hábitos; além de até 12 mensagens recentes da conversa.",
    "A ação não foi concluída. Os seus dados permaneceram inalterados; reveja o valor e tente novamente.",
  ],
  "ur": [
    "ایپ کی ظاہری شکل اپ ڈیٹ ہو گئی۔",
    "ایپ کی زبان اپ ڈیٹ ہو گئی۔",
    "لکھنے سے پہلے پوچھیں",
    "BIL صرف آپ کے طلب کردہ جواب کو تیار کرنے کے لیے Google Gemini استعمال کرتا ہے، جو Google کی جانب سے چلائی جانے والی تیسرے فریق کی AI سروس ہے۔",
    "گفتگو",
    "گفتگو کی تاریخ اسی آلے پر مقامی طور پر محفوظ ہوتی ہے۔",
    "گفتگوئیں",
    "موجودہ گفتگو",
    "براہ راست کال ختم کریں",
    "کھانے کی تصویر",
    "اس گفتگو کو تاریخ میں رکھیں اور ایک خالی گفتگو شروع کریں۔",
    "نئی گفتگو",
    "ابھی کوئی پچھلی گفتگو نہیں ہے۔",
    "صرف آپ کا منتخب کردہ سیاق",
    "مائیکروفون کی خام آواز نہیں بھیجی جاتی",
    "صرف پڑھنا",
    "بھیجا جا رہا ہے",
    "کامیابی سے سائن آؤٹ ہو گیا۔",
    "زیر التوا کارروائی منسوخ ہو گئی۔ کچھ نہیں بدلا۔",
    "پچھلی کارروائی واپس لے لی گئی۔",
    "کوئی حالیہ کارروائی موجود نہیں جسے واپس لیا جا سکے۔",
    "اس کارروائی کو لکھنے کی اجازت درکار ہے۔ جاری رکھنے کے لیے ڈھال کی ترتیب بدلیں۔",
    "آواز کی شناخت اس ریموٹ AI کی رضامندی سے الگ رہتی ہے۔",
    "لکھنے کی اجازت ہے",
    "آپ انکار کرکے BIL کی مقامی خصوصیات استعمال کرتے رہ سکتے ہیں، یا بعد میں AI کوچ کی ترتیبات میں یہ رضامندی واپس لے سکتے ہیں۔",
    "اختیار آپ کے پاس رہتا ہے",
    "آپ کا سوال؛ منتخب وزن، اہداف اور پیمائشیں؛ کھانے، غذائیت، پانی اور ترجیحات؛ سرگرمی اور تربیت؛ نیند اور عادات؛ نیز گفتگو کے زیادہ سے زیادہ 12 حالیہ پیغامات۔",
    "کارروائی مکمل نہیں ہوئی۔ آپ کا ڈیٹا تبدیل نہیں ہوا؛ قدر کا جائزہ لے کر دوبارہ کوشش کریں۔",
  ],
  "fa": [
    "ظاهر برنامه به‌روز شد.",
    "زبان برنامه به‌روز شد.",
    "پیش از نوشتن بپرس",
    "BIL از Google Gemini، سرویس هوش مصنوعی شخص ثالث که Google آن را اداره می‌کند، فقط برای تولید پاسخ درخواستی شما استفاده می‌کند.",
    "گفتگو",
    "تاریخچهٔ گفتگوها به‌صورت محلی روی این دستگاه ذخیره می‌شود.",
    "گفتگوها",
    "گفتگوی فعلی",
    "پایان تماس زنده",
    "عکس غذا",
    "این گفتگو را در تاریخچه نگه دار و یک گفتگوی خالی شروع کن.",
    "گفتگوی جدید",
    "هنوز گفتگوی قبلی وجود ندارد.",
    "فقط زمینه‌ای که انتخاب می‌کنید",
    "صدای خام میکروفون ارسال نمی‌شود",
    "فقط خواندن",
    "در حال ارسال",
    "خروج با موفقیت انجام شد.",
    "عملیات در انتظار لغو شد. هیچ چیزی تغییر نکرد.",
    "عملیات قبلی به حالت پیشین برگردانده شد.",
    "عملیات اخیر قابل بازگردانی وجود ندارد.",
    "این عملیات به اجازهٔ نوشتن نیاز دارد. برای ادامه، تنظیم سپر را تغییر دهید.",
    "تشخیص گفتار از این رضایت‌نامهٔ هوش مصنوعی راه دور جدا می‌ماند.",
    "نوشتن مجاز است",
    "می‌توانید رد کنید و به استفاده از امکانات محلی BIL ادامه دهید، یا بعداً این رضایت را در تنظیمات مربی هوش مصنوعی پس بگیرید.",
    "کنترل در دست شما می‌ماند",
    "پرسش شما؛ وزن، هدف‌ها و اندازه‌گیری‌های انتخاب‌شده؛ وعده‌ها، تغذیه، آب و ترجیحات؛ فعالیت و تمرین؛ خواب و عادت‌ها؛ به‌علاوه حداکثر 12 پیام اخیر گفتگو.",
    "عملیات کامل نشد. داده‌های شما بدون تغییر باقی ماند؛ مقدار را بررسی کرده و دوباره تلاش کنید.",
  ],
  "hi": [
    "ऐप का रूप अपडेट हो गया।",
    "ऐप की भाषा अपडेट हो गई।",
    "लिखने से पहले पूछें",
    "BIL आपके अनुरोधित उत्तर को तैयार करने के लिए ही Google Gemini का उपयोग करता है, जो Google द्वारा संचालित एक तृतीय-पक्ष AI सेवा है।",
    "बातचीत",
    "बातचीत का इतिहास इस डिवाइस पर स्थानीय रूप से संग्रहीत होता है।",
    "बातचीतें",
    "मौजूदा बातचीत",
    "लाइव कॉल समाप्त करें",
    "खाने की फ़ोटो",
    "इस बातचीत को इतिहास में रखें और एक खाली बातचीत शुरू करें।",
    "नई बातचीत",
    "अभी कोई पिछली बातचीत नहीं है।",
    "केवल आपके चुने हुए संदर्भ",
    "माइक्रोफ़ोन की कच्ची ऑडियो नहीं भेजी जाती",
    "केवल पढ़ना",
    "भेजा जा रहा है",
    "सफलतापूर्वक साइन आउट हो गया।",
    "लंबित कार्रवाई रद्द कर दी गई। कुछ भी नहीं बदला।",
    "पिछली कार्रवाई पूर्ववत कर दी गई।",
    "पूर्ववत की जा सकने वाली कोई हाल की कार्रवाई नहीं है।",
    "इस कार्रवाई के लिए लिखने की अनुमति चाहिए। जारी रखने के लिए शील्ड की सेटिंग बदलें।",
    "आवाज़ की पहचान इस रिमोट AI सहमति से अलग रहती है।",
    "लिखने की अनुमति है",
    "आप मना करके BIL की स्थानीय सुविधाओं का उपयोग जारी रख सकते हैं, या बाद में AI कोच की सेटिंग में यह सहमति वापस ले सकते हैं।",
    "नियंत्रण आपके पास रहता है",
    "आपका प्रश्न; चुना गया वज़न, लक्ष्य और माप; भोजन, पोषण, पानी और प्राथमिकताएँ; गतिविधि और प्रशिक्षण; नींद और आदतें; साथ में बातचीत के अधिकतम 12 हालिया संदेश।",
    "कार्रवाई पूरी नहीं हुई। आपका डेटा अपरिवर्तित रहा; मान की समीक्षा करके फिर कोशिश करें।",
  ],
  "id": [
    "Tampilan aplikasi diperbarui.",
    "Bahasa aplikasi diperbarui.",
    "Tanya sebelum menulis",
    "BIL menggunakan Google Gemini, layanan AI pihak ketiga yang dioperasikan oleh Google, hanya untuk menghasilkan jawaban yang Anda minta.",
    "Percakapan",
    "Riwayat percakapan disimpan secara lokal di perangkat ini.",
    "Daftar percakapan",
    "Percakapan saat ini",
    "Akhiri panggilan langsung",
    "Foto makanan",
    "Simpan percakapan ini dalam riwayat dan mulai percakapan kosong.",
    "Percakapan baru",
    "Belum ada percakapan sebelumnya.",
    "Hanya konteks yang Anda pilih",
    "Audio mentah mikrofon tidak dikirim",
    "Hanya baca",
    "Mengirim",
    "Berhasil keluar.",
    "Tindakan tertunda dibatalkan. Tidak ada yang diubah.",
    "Tindakan sebelumnya telah dibatalkan.",
    "Tidak ada tindakan terbaru yang dapat dibatalkan.",
    "Tindakan ini memerlukan izin menulis. Ubah pengaturan perisai untuk melanjutkan.",
    "Pengenalan suara tetap terpisah dari persetujuan AI jarak jauh ini.",
    "Menulis diizinkan",
    "Anda dapat menolak dan tetap menggunakan fitur lokal BIL, atau mencabut persetujuan ini nanti di pengaturan Pelatih AI.",
    "Anda tetap memegang kendali",
    "Pertanyaan Anda; berat, tujuan, dan pengukuran yang dipilih; makanan, nutrisi, air, dan preferensi; aktivitas dan latihan; tidur dan kebiasaan; serta hingga 12 pesan percakapan terbaru.",
    "Tindakan tidak diselesaikan. Data Anda tetap tidak berubah; tinjau nilainya dan coba lagi.",
  ],
};
