part of 'runtime_copy_community_expansion.dart';

const _communityExpansionWestCoreRows = <String, List<String>>{
  'fr': <String>[
    "{actor} a accepté votre demande d’ami",
    "{actor} a commenté votre publication",
    "{actor} vous suit maintenant",
    "{actor} a aimé votre publication",
    "{actor} vous a mentionné dans une publication",
    "{actor} a répondu à votre commentaire",
    "{actor} vous a envoyé une demande d’ami",
    "{inviterName} vous a invité à rejoindre BIL",
    "{total} votes",
    "10 000 pas",
    "Un espace accueillant pour progresser en forme de manière sûre et graduelle.",
    "Utilisation d’AI Coach",
    "Accepter l’invitation",
    "Les publications de vos amis acceptés apparaîtront ici.",
    "L’acceptation enregistre qui vous a invité. Elle n’accorde pas de Gold à elle seule.",
    "Ajouter un sondage",
    "Ajouter une option",
    "Autoriser plusieurs choix",
    "Une autre invitation est déjà liée à ce compte.",
    "Posez une question avec 2 à 6 options.",
    "Activité BIL Gold",
    "Récompenses BIL",
    "BIL n’a pas pu vérifier cette invitation en toute sécurité.",
    "BIL n’a pas pu vérifier votre état de récompense en toute sécurité.",
    "Invitation BIL",
    "Ajustement du solde",
    "Soyez respectueux, évitez les informations de santé privées et respectez la politique de la Communauté.",
    "Fitness débutant",
    "Mieux dormir",
    "Adoptez une habitude de marche régulière et encouragez-vous mutuellement.",
    "Mise à jour du défi",
    "Choisissez une option",
    "Choisissez une ou plusieurs options",
    "Choisissez quelles sections sociales les autres membres peuvent voir. Les données de santé ne sont jamais incluses.",
    "Cercle — facultatif",
    "Cercles",
    "Libellé de ville ou de lieu",
    "Réclamé",
    "Commentaires et mentions",
    "Niveau Communauté",
    "Confidentialité du profil Communauté",
    "Quête Communauté",
    "Récompense de quête Communauté",
    "Sujets de la Communauté",
    "Effectuez l’action Communauté vérifiée pour progresser.",
    "Complétez votre profil Communauté",
    "Impossible d’accepter cette invitation en toute sécurité. Réessayez.",
    "Impossible de réclamer cette récompense en toute sécurité. Réessayez.",
    "Impossible de charger plus d’historique.",
    "Impossible d’enregistrer votre vote. Réessayez.",
    "Impossible de rechercher les mentions pour le moment.",
    "Impossible de mettre à jour ce Cercle en toute sécurité. Réessayez.",
    "Impossible de mettre à jour ce sujet en toute sécurité. Réessayez.",
    "Créer une publication utile",
    "Créer un compte",
    "Quotidien",
    "Discutez de musculation, de régularité et de récupération.",
    "Gagner",
    "Gagné",
    "Les entrées BIL Gold gagnées et utilisées apparaîtront ici.",
    "Modifier le profil",
    "Terminez le sondage : ajoutez une question et 2 à 6 options différentes.",
    "Suivre",
    "Suivez des membres pour voir ici leurs publications approuvées.",
    "Abonnés",
    "Abonnements",
    "Pour vous",
    "Les demandes d’ami, connexions acceptées et messages non lus apparaîtront ici.",
    "Aller",
    "Vue en grille",
    "Alimentation saine",
    "Masquer les réponses",
    "Invitation acceptée et amitié créée. Gold reste soumis à la condition de nouveau compte et aux contrôles d’intégrité du serveur.",
    "Invitation enregistrée.",
    "Invitation indisponible",
    "Inviter un ami",
    "Rejoindre",
    "Rejoignez un Cercle pour y publier.",
    "Quitter",
    "J’aime et enregistrements",
    "Vue en liste",
    "Charger plus de fils de commentaires",
    "Charger plus de réponses",
    "Lieu — facultatif",
    "Mentionner des personnes — facultatif",
    "Mentionnez jusqu’à 10 membres Communauté découvrables. Ils ne sont notifiés qu’après l’approbation de la publication.",
    "Nouveau",
    "Nouveau badge obtenu",
    "Nouveau commentaire sur votre publication",
    "Nouvel abonné",
    "Nouvelle demande d’ami",
    "Nouvelle publication",
    "Nouvelle réponse à votre commentaire",
    "Aucun Cercle",
    "Aucune activité Gold pour le moment",
    "Aucune quête active pour le moment",
    "Aucune publication approuvée dans ce Cercle pour le moment.",
    "Aucune publication approuvée dans ce sujet pour le moment.",
    "Aucune publication approuvée pour le moment. Lancez la première conversation.",
    "Aucune mise à jour dans cette catégorie pour le moment.",
    "Aucune publication visible pour le moment.",
    "Rien de personnalisé pour le moment. Suivez des personnes, des sujets ou des Cercles pour façonner ce fil.",
    "Rien à afficher ici pour le moment.",
    "Désactivé par défaut. BIL Gold et Community XP restent séparés de votre abonnement.",
    "Option {index}",
    "Texte facultatif uniquement. BIL ne demande pas le GPS pour les publications Communauté.",
    "Sondage",
    "Sondage clôturé",
    "Question du sondage",
    "Publier dans le Cercle",
    "Les publications sont privées sur ce profil.",
    "La qualité, la modération et l’engagement pertinent sont vérifiés en premier.",
    "Quête terminée",
    "Ramadan et jeûne",
    "Prêt à réclamer",
    "Supprimer l’option",
    "Récompense déjà réclamée.",
    "Récompense réclamée.",
    "Les règles de récompense ne sont activées par BIL qu’après vérification côté serveur et préparation des contrôles de sécurité.",
    "Récompenses",
    "Récompenses indisponibles",
    "Les récompenses ne se débloquent qu’après qualification de la relation d’amitié vérifiée.",
    "Course à pied",
    "Rechercher un pseudo",
    "Vu",
    "Configurez votre identité publique et vos choix de confidentialité.",
    "Partagez des routines et expériences de jeûne respectueuses des cultures.",
    "Partagez des idées de repas pratiques et des habitudes alimentaires durables.",
    "Partagez vos progrès, routines et encouragements en course à pied.",
    "Partagez des progrès durables et du soutien sans comparaison ni pression.",
    "Afficher les abonnés",
    "Afficher les abonnements",
    "Afficher les amis",
    "Afficher le niveau d’abonnement",
    "Afficher les publications sur mon profil",
    "Se connecter pour accepter",
    "Connectez-vous pour voir BIL Gold et les récompenses.",
    "Connectez-vous pour voir les profils Communauté.",
    "Quelqu’un a aimé votre publication",
    "Monnaie Communauté utilisable",
    "Commencer une publication",
    "Débutant",
    "Soutenez de meilleures habitudes de sommeil sans allégations médicales.",
    "Cette invitation est invalide ou expirée.",
    "Cette invitation est invalide, expirée ou déjà utilisée.",
    "Cette invitation est indisponible.",
    "Cette invitation a déjà été utilisée.",
    "Cette liste est indisponible pour le moment.",
    "Cette récompense n’est pas disponible pour le moment.",
    "Les sujets sont indisponibles pour le moment. Vous pouvez toujours publier.",
    "Sujets — jusqu’à 3",
    "Les invitations BIL suivies ne sont pas encore actives.",
    "Les invitations suivies ne sont pas encore actives.",
    "Utilisé",
    "Voir {count} réponses",
    "Voter",
    "Hebdomadaire",
    "Parcours de perte de poids",
    "Vous ne pouvez pas accepter votre propre invitation.",
    "Vous avez gagné une récompense Communauté",
    "Vous avez été mentionné dans une publication",
    "Votre demande d’ami a été acceptée",
    "Votre publication a été enregistrée",
    "Vous êtes amis — voir le profil",
    "abonnés",
    "membres",
    "publications",
  ],
  'es': <String>[
    "{actor} aceptó tu solicitud de amistad",
    "{actor} comentó tu publicación",
    "{actor} empezó a seguirte",
    "{actor} indicó que le gusta tu publicación",
    "{actor} te mencionó en una publicación",
    "{actor} respondió a tu comentario",
    "{actor} te envió una solicitud de amistad",
    "{inviterName} te invitó a unirte a BIL",
    "{total} votos",
    "10 mil pasos",
    "Un espacio acogedor para avanzar de forma segura y gradual en tu actividad física.",
    "Uso de AI Coach",
    "Aceptar invitación",
    "Las publicaciones de tus amistades aceptadas aparecerán aquí.",
    "Aceptar registra quién te invitó. Por sí solo no concede Gold.",
    "Añadir una encuesta",
    "Añadir opción",
    "Permitir varias opciones",
    "Ya hay otra invitación vinculada a esta cuenta.",
    "Haz una pregunta con entre 2 y 6 opciones.",
    "Actividad de BIL Gold",
    "Recompensas BIL",
    "BIL no pudo verificar esta invitación de forma segura.",
    "BIL no pudo verificar de forma segura el estado de tus recompensas.",
    "Invitación BIL",
    "Ajuste de saldo",
    "Sé respetuoso, evita los datos de salud privados y sigue la política de la Comunidad.",
    "Fitness para principiantes",
    "Dormir mejor",
    "Crea un hábito constante de caminar y anímense mutuamente.",
    "Actualización del reto",
    "Elige una opción",
    "Elige una o más opciones",
    "Elige qué secciones sociales pueden ver otros miembros. Los datos de salud nunca se incluyen.",
    "Círculo — opcional",
    "Círculos",
    "Etiqueta de ciudad o lugar",
    "Reclamado",
    "Comentarios y menciones",
    "Nivel de Comunidad",
    "Privacidad del perfil de Comunidad",
    "Misión de Comunidad",
    "Recompensa de misión de Comunidad",
    "Temas de la Comunidad",
    "Completa la acción verificada de Comunidad para avanzar.",
    "Completa tu perfil de Comunidad",
    "No se pudo aceptar esta invitación de forma segura. Inténtalo de nuevo.",
    "No se pudo reclamar esta recompensa de forma segura. Inténtalo de nuevo.",
    "No se pudo cargar más historial.",
    "No se pudo registrar tu voto. Inténtalo de nuevo.",
    "No se pueden buscar menciones ahora mismo.",
    "No se pudo actualizar este Círculo de forma segura. Inténtalo de nuevo.",
    "No se pudo actualizar este tema de forma segura. Inténtalo de nuevo.",
    "Crear una publicación valiosa",
    "Crear una cuenta",
    "Diario",
    "Habla sobre entrenamiento de fuerza, constancia y recuperación.",
    "Ganar",
    "Ganado",
    "Las entradas de BIL Gold ganadas y usadas aparecerán aquí.",
    "Editar perfil",
    "Completa la encuesta: añade una pregunta y entre 2 y 6 opciones diferentes.",
    "Seguir",
    "Sigue a miembros para ver aquí sus publicaciones aprobadas.",
    "Seguidores",
    "Siguiendo",
    "Para ti",
    "Las solicitudes de amistad, conexiones aceptadas y mensajes sin leer aparecerán aquí.",
    "Ir",
    "Vista de cuadrícula",
    "Alimentación saludable",
    "Ocultar respuestas",
    "Invitación aceptada y amistad creada. Gold sigue condicionado a que la cuenta sea nueva y a las comprobaciones de integridad del servidor.",
    "Invitación guardada.",
    "Invitación no disponible",
    "Invitar a un amigo",
    "Unirse",
    "Únete a un Círculo para publicar en él.",
    "Salir",
    "Me gusta y guardados",
    "Vista de lista",
    "Cargar más hilos de comentarios",
    "Cargar más respuestas",
    "Ubicación — opcional",
    "Mencionar personas — opcional",
    "Menciona hasta 10 miembros visibles de la Comunidad. Solo recibirán una notificación cuando se apruebe la publicación.",
    "Nuevo",
    "Nueva insignia obtenida",
    "Nuevo comentario en tu publicación",
    "Nuevo seguidor",
    "Nueva solicitud de amistad",
    "Nueva publicación",
    "Nueva respuesta a tu comentario",
    "Sin Círculo",
    "Todavía no hay actividad de Gold",
    "No hay misiones activas ahora mismo",
    "Todavía no hay publicaciones aprobadas en este Círculo.",
    "Todavía no hay publicaciones aprobadas en este tema.",
    "Todavía no hay publicaciones aprobadas. Inicia la primera conversación.",
    "Todavía no hay actualizaciones en esta categoría.",
    "Todavía no hay publicaciones visibles.",
    "Aún no hay contenido personalizado. Sigue a personas, temas o Círculos para dar forma a este feed.",
    "Nada que mostrar aquí por ahora.",
    "Desactivado de forma predeterminada. BIL Gold y Community XP siguen separados de tu suscripción.",
    "Opción {index}",
    "Solo texto opcional. BIL no solicita GPS para publicaciones de Comunidad.",
    "Encuesta",
    "Encuesta cerrada",
    "Pregunta de la encuesta",
    "Publicar en el Círculo",
    "Las publicaciones son privadas en este perfil.",
    "Primero se comprueban la calidad, la moderación y la interacción significativa.",
    "Misión completada",
    "Ramadán y ayuno",
    "Listo para reclamar",
    "Eliminar opción",
    "Recompensa ya reclamada.",
    "Recompensa reclamada.",
    "BIL solo activa las reglas de recompensa después de la verificación del servidor y cuando las comprobaciones de seguridad están listas.",
    "Recompensas",
    "Recompensas no disponibles",
    "Las recompensas se desbloquean solo cuando la relación de amistad verificada cumple los requisitos.",
    "Correr",
    "Buscar nombre de usuario",
    "Visto",
    "Configura tu identidad pública y tus opciones de privacidad.",
    "Comparte rutinas y experiencias de ayuno con respeto cultural.",
    "Comparte ideas prácticas de comidas y hábitos de alimentación sostenibles.",
    "Comparte avances, rutinas y ánimo para correr.",
    "Comparte avances sostenibles y apoyo sin comparaciones ni presión.",
    "Mostrar seguidores",
    "Mostrar seguidos",
    "Mostrar amigos",
    "Mostrar nivel de membresía",
    "Mostrar publicaciones en mi perfil",
    "Inicia sesión para aceptar",
    "Inicia sesión para ver BIL Gold y las recompensas.",
    "Inicia sesión para ver perfiles de Comunidad.",
    "A alguien le gustó tu publicación",
    "Moneda de Comunidad utilizable",
    "Crear una publicación",
    "Inicial",
    "Apoya mejores rutinas de sueño sin afirmaciones médicas.",
    "Esta invitación no es válida o ha caducado.",
    "Esta invitación no es válida, ha caducado o ya se usó.",
    "Esta invitación no está disponible.",
    "Esta invitación ya se utilizó.",
    "Esta lista no está disponible ahora mismo.",
    "Esta recompensa no está disponible ahora mismo.",
    "Los temas no están disponibles ahora mismo. Aun así puedes publicar.",
    "Temas — elige hasta 3",
    "Las invitaciones BIL con seguimiento aún no están activas.",
    "Las invitaciones con seguimiento aún no están activas.",
    "Usado",
    "Ver {count} respuestas",
    "Votar",
    "Semanal",
    "Camino para perder peso",
    "No puedes aceptar tu propia invitación.",
    "Has ganado una recompensa de Comunidad",
    "Te mencionaron en una publicación",
    "Tu solicitud de amistad fue aceptada",
    "Tu publicación se guardó",
    "Ya son amigos — ver perfil",
    "seguidores",
    "miembros",
    "publicaciones",
  ],
  'tr': <String>[
    "{actor} arkadaşlık isteğini kabul etti",
    "{actor} gönderine yorum yaptı",
    "{actor} seni takip etmeye başladı",
    "{actor} gönderini beğendi",
    "{actor} bir gönderide senden bahsetti",
    "{actor} yorumuna yanıt verdi",
    "{actor} sana arkadaşlık isteği gönderdi",
    "{inviterName} seni BIL’e katılmaya davet etti",
    "{total} oy",
    "10 Bin Adım",
    "Güvenli ve kademeli fitness ilerlemesi için sıcak bir alan.",
    "AI Coach kullanımı",
    "Daveti kabul et",
    "Kabul edilen arkadaşlarının gönderileri burada görünecek.",
    "Kabul etmek seni kimin davet ettiğini kaydeder. Tek başına Gold vermez.",
    "Anket ekle",
    "Seçenek ekle",
    "Birden fazla seçime izin ver",
    "Bu hesaba zaten başka bir davet bağlı.",
    "2–6 seçenekli bir soru sor.",
    "BIL Gold etkinliği",
    "BIL Ödülleri",
    "BIL bu daveti güvenli şekilde doğrulayamadı.",
    "BIL ödül durumunu güvenli şekilde doğrulayamadı.",
    "BIL daveti",
    "Bakiye düzeltmesi",
    "Saygılı ol, özel sağlık bilgilerini paylaşma ve Topluluk politikasına uy.",
    "Başlangıç Fitness",
    "Daha İyi Uyku",
    "Düzenli yürüyüş alışkanlığı oluşturun ve birbirinizi teşvik edin.",
    "Meydan okuma güncellemesi",
    "Bir seçenek seç",
    "Bir veya daha fazla seçenek seç",
    "Diğer üyelerin hangi sosyal bölümleri görebileceğini seç. Sağlık verileri asla dahil edilmez.",
    "Çevre — isteğe bağlı",
    "Çevreler",
    "Şehir veya yer etiketi",
    "Alındı",
    "Yorumlar ve bahsetmeler",
    "Topluluk seviyesi",
    "Topluluk profili gizliliği",
    "Topluluk görevi",
    "Topluluk görevi ödülü",
    "Topluluk konuları",
    "İlerlemek için doğrulanmış Topluluk eylemini tamamla.",
    "Topluluk profilini tamamla",
    "Bu davet güvenli şekilde kabul edilemedi. Tekrar dene.",
    "Bu ödül güvenli şekilde alınamadı. Tekrar dene.",
    "Daha fazla geçmiş yüklenemedi.",
    "Oyun kaydedilemedi. Tekrar dene.",
    "Şu anda bahsetmeler aranamadı.",
    "Bu Çevre güvenli şekilde güncellenemedi. Tekrar dene.",
    "Bu konu güvenli şekilde güncellenemedi. Tekrar dene.",
    "Değerli bir gönderi oluştur",
    "Hesap oluştur",
    "Günlük",
    "Güç antrenmanı, süreklilik ve toparlanmayı konuşun.",
    "Kazan",
    "Kazanıldı",
    "Kazanılan ve kullanılan BIL Gold kayıtları burada görünecek.",
    "Profili düzenle",
    "Anketi tamamla: bir soru ve 2–6 farklı seçenek ekle.",
    "Takip et",
    "Onaylı gönderilerini burada görmek için üyeleri takip et.",
    "Takipçiler",
    "Takip edilenler",
    "Senin İçin",
    "Arkadaşlık istekleri, kabul edilen bağlantılar ve okunmamış mesajlar burada görünecek.",
    "Git",
    "Izgara görünümü",
    "Sağlıklı Beslenme",
    "Yanıtları gizle",
    "Davet kabul edildi ve arkadaşlık oluşturuldu. Gold için hesabın yeni olması ve sunucu bütünlük kontrolleri hâlâ gereklidir.",
    "Davet kaydedildi.",
    "Davet kullanılamıyor",
    "Bir arkadaş davet et",
    "Katıl",
    "İçinde gönderi paylaşmak için bir Çevreye katıl.",
    "Ayrıl",
    "Beğeniler ve kaydedilenler",
    "Liste görünümü",
    "Daha fazla yorum dizisi yükle",
    "Daha fazla yanıt yükle",
    "Konum — isteğe bağlı",
    "Kişilerden bahset — isteğe bağlı",
    "Keşfedilebilir en fazla 10 Topluluk üyesinden bahset. Yalnızca gönderi onaylandıktan sonra bildirim alırlar.",
    "Yeni",
    "Yeni rozet kazanıldı",
    "Gönderine yeni yorum",
    "Yeni takipçi",
    "Yeni arkadaşlık isteği",
    "Yeni gönderi",
    "Yorumuna yeni yanıt",
    "Çevre yok",
    "Henüz Gold etkinliği yok",
    "Şu anda etkin görev yok",
    "Bu Çevrede henüz onaylı gönderi yok.",
    "Bu konuda henüz onaylı gönderi yok.",
    "Henüz onaylı gönderi yok. İlk sohbeti başlat.",
    "Bu kategoride henüz güncelleme yok.",
    "Henüz görünür gönderi yok.",
    "Henüz kişiselleştirilmiş içerik yok. Bu akışı şekillendirmek için kişileri, konuları veya Çevreleri takip et.",
    "Şimdilik burada gösterilecek bir şey yok.",
    "Varsayılan olarak kapalı. BIL Gold ve Community XP aboneliğinden ayrı kalır.",
    "Seçenek {index}",
    "Yalnızca isteğe bağlı metin. BIL Topluluk gönderileri için GPS istemez.",
    "Anket",
    "Anket kapandı",
    "Anket sorusu",
    "Çevrede paylaş",
    "Bu profilde gönderiler gizli.",
    "Önce kalite, moderasyon ve anlamlı etkileşim kontrol edilir.",
    "Görev tamamlandı",
    "Ramazan ve Oruç",
    "Almaya hazır",
    "Seçeneği kaldır",
    "Ödül zaten alındı.",
    "Ödül alındı.",
    "Ödül kuralları yalnızca sunucu doğrulaması ve güvenlik kontrolleri hazır olduktan sonra BIL tarafından etkinleştirilir.",
    "Ödüller",
    "Ödüller kullanılamıyor",
    "Ödüller yalnızca doğrulanmış arkadaşlık ilişkisi uygun olduğunda açılır.",
    "Koşu",
    "Kullanıcı adını ara",
    "Görüldü",
    "Herkese açık kimliğini ve gizlilik seçimlerini ayarla.",
    "Kültüre saygılı oruç rutinleri ve deneyimleri paylaş.",
    "Pratik öğün fikirleri ve sürdürülebilir beslenme alışkanlıkları paylaş.",
    "Koşu ilerlemeni, rutinlerini ve teşviklerini paylaş.",
    "Karşılaştırma baskısı olmadan sürdürülebilir ilerleme ve destek paylaş.",
    "Takipçileri göster",
    "Takip edilenleri göster",
    "Arkadaşları göster",
    "Üyelik seviyesini göster",
    "Gönderileri profilimde göster",
    "Kabul etmek için giriş yap",
    "BIL Gold ve ödülleri görmek için giriş yap.",
    "Topluluk profillerini görmek için giriş yap.",
    "Birisi gönderini beğendi",
    "Harcanabilir Topluluk para birimi",
    "Bir gönderi başlat",
    "Başlangıç",
    "Tıbbi iddialar olmadan daha iyi uyku rutinlerini destekle.",
    "Bu davet geçersiz veya süresi dolmuş.",
    "Bu davet geçersiz, süresi dolmuş veya zaten kullanılmış.",
    "Bu davet kullanılamıyor.",
    "Bu davet zaten kullanılmış.",
    "Bu liste şu anda kullanılamıyor.",
    "Bu ödül şu anda kullanılamıyor.",
    "Konular şu anda kullanılamıyor. Yine de gönderi paylaşabilirsin.",
    "Konular — en fazla 3 seç",
    "Takip edilen BIL davetleri henüz etkin değil.",
    "Takip edilen davetler henüz etkin değil.",
    "Kullanıldı",
    "{count} yanıtı gör",
    "Oyla",
    "Haftalık",
    "Kilo Verme Yolculuğu",
    "Kendi davetini kabul edemezsin.",
    "Bir Topluluk ödülü kazandın",
    "Bir gönderide senden bahsedildi",
    "Arkadaşlık isteğin kabul edildi",
    "Gönderin kaydedildi",
    "Arkadaşsınız — profili görüntüle",
    "takipçiler",
    "üyeler",
    "gönderiler",
  ],
};
