part of 'runtime_copy_community_expansion.dart';

const _communityExpansionSoutheastAsiaRows = <String, List<String>>{
  'id': <String>[
    "{actor} menerima permintaan pertemanan Anda",
    "{actor} mengomentari postingan Anda",
    "{actor} mulai mengikuti Anda",
    "{actor} menyukai postingan Anda",
    "{actor} menyebut Anda dalam sebuah postingan",
    "{actor} membalas komentar Anda",
    "{actor} mengirim permintaan pertemanan kepada Anda",
    "{inviterName} mengundang Anda bergabung dengan BIL",
    "{total} suara",
    "10 Ribu Langkah",
    "Ruang yang ramah untuk kemajuan kebugaran yang aman dan bertahap.",
    "Penggunaan AI Coach",
    "Terima undangan",
    "Postingan dari teman yang telah diterima akan muncul di sini.",
    "Menerima undangan mencatat siapa yang mengundang Anda. Tindakan ini sendiri tidak memberikan Gold.",
    "Tambahkan jajak pendapat",
    "Tambahkan opsi",
    "Izinkan beberapa pilihan",
    "Undangan lain sudah ditautkan ke akun ini.",
    "Ajukan satu pertanyaan dengan 2–6 opsi.",
    "Aktivitas BIL Gold",
    "Hadiah BIL",
    "BIL tidak dapat memverifikasi undangan ini dengan aman.",
    "BIL tidak dapat memverifikasi status hadiah Anda dengan aman.",
    "Undangan BIL",
    "Penyesuaian saldo",
    "Bersikaplah hormat, hindari detail kesehatan pribadi, dan ikuti kebijakan Komunitas.",
    "Kebugaran Pemula",
    "Tidur Lebih Baik",
    "Bangun kebiasaan berjalan yang konsisten dan saling menyemangati.",
    "Pembaruan tantangan",
    "Pilih satu opsi",
    "Pilih satu atau beberapa opsi",
    "Pilih bagian sosial mana yang dapat dilihat anggota lain. Data kesehatan tidak pernah disertakan.",
    "Lingkaran — opsional",
    "Lingkaran",
    "Label kota atau tempat",
    "Diklaim",
    "Komentar & sebutan",
    "Level Komunitas",
    "Privasi profil Komunitas",
    "Misi Komunitas",
    "Hadiah misi Komunitas",
    "Topik Komunitas",
    "Selesaikan tindakan Komunitas yang terverifikasi untuk membuat kemajuan.",
    "Lengkapi profil Komunitas Anda",
    "Undangan ini tidak dapat diterima dengan aman. Coba lagi.",
    "Hadiah ini tidak dapat diklaim dengan aman. Coba lagi.",
    "Riwayat lainnya tidak dapat dimuat.",
    "Suara Anda tidak dapat direkam. Coba lagi.",
    "Sebutan tidak dapat dicari sekarang.",
    "Lingkaran ini tidak dapat diperbarui dengan aman. Coba lagi.",
    "Topik ini tidak dapat diperbarui dengan aman. Coba lagi.",
    "Buat postingan yang bermanfaat",
    "Buat akun",
    "Harian",
    "Diskusikan latihan kekuatan, konsistensi, dan pemulihan.",
    "Dapatkan",
    "Didapatkan",
    "Entri BIL Gold yang didapatkan dan digunakan akan muncul di sini.",
    "Edit profil",
    "Selesaikan jajak pendapat: tambahkan pertanyaan dan 2–6 opsi yang berbeda.",
    "Ikuti",
    "Ikuti anggota untuk melihat postingan mereka yang disetujui di sini.",
    "Pengikut",
    "Mengikuti",
    "Untuk Anda",
    "Permintaan pertemanan, koneksi yang diterima, dan pesan yang belum dibaca akan muncul di sini.",
    "Buka",
    "Tampilan kisi",
    "Makan Sehat",
    "Sembunyikan balasan",
    "Undangan diterima dan pertemanan dibuat. Gold tetap bergantung pada akun baru dan pemeriksaan integritas server.",
    "Undangan disimpan.",
    "Undangan tidak tersedia",
    "Undang teman",
    "Gabung",
    "Gabung ke Lingkaran untuk membuat postingan di dalamnya.",
    "Keluar",
    "Suka & tersimpan",
    "Tampilan daftar",
    "Muat lebih banyak utas komentar",
    "Muat lebih banyak balasan",
    "Lokasi — opsional",
    "Sebut orang — opsional",
    "Sebut hingga 10 anggota Komunitas yang dapat ditemukan. Mereka hanya diberi tahu setelah postingan disetujui.",
    "Baru",
    "Lencana baru didapatkan",
    "Komentar baru pada postingan Anda",
    "Pengikut baru",
    "Permintaan pertemanan baru",
    "Postingan baru",
    "Balasan baru untuk komentar Anda",
    "Tanpa Lingkaran",
    "Belum ada aktivitas Gold",
    "Tidak ada misi aktif saat ini",
    "Belum ada postingan yang disetujui di Lingkaran ini.",
    "Belum ada postingan yang disetujui di topik ini.",
    "Belum ada postingan yang disetujui. Mulai percakapan pertama.",
    "Belum ada pembaruan dalam kategori ini.",
    "Belum ada postingan yang terlihat.",
    "Belum ada yang dipersonalisasi. Ikuti orang, topik, atau Lingkaran untuk membentuk feed ini.",
    "Belum ada yang dapat ditampilkan di sini.",
    "Nonaktif secara default. BIL Gold dan Community XP tetap terpisah dari langganan Anda.",
    "Opsi {index}",
    "Hanya teks opsional. BIL tidak meminta GPS untuk postingan Komunitas.",
    "Jajak pendapat",
    "Jajak pendapat ditutup",
    "Pertanyaan jajak pendapat",
    "Posting di Lingkaran",
    "Postingan bersifat privat di profil ini.",
    "Kualitas, moderasi, dan interaksi yang bermakna diperiksa terlebih dahulu.",
    "Misi selesai",
    "Ramadan & Puasa",
    "Siap diklaim",
    "Hapus opsi",
    "Hadiah sudah diklaim.",
    "Hadiah diklaim.",
    "Aturan hadiah hanya diaktifkan oleh BIL setelah verifikasi server dan pemeriksaan keamanan siap.",
    "Hadiah",
    "Hadiah tidak tersedia",
    "Hadiah hanya terbuka setelah hubungan pertemanan yang terverifikasi memenuhi syarat.",
    "Lari",
    "Cari nama pengguna",
    "Sudah dilihat",
    "Atur identitas publik dan pilihan privasi Anda.",
    "Bagikan rutinitas dan pengalaman puasa yang menghormati budaya.",
    "Bagikan ide makanan praktis dan kebiasaan makan berkelanjutan.",
    "Bagikan kemajuan, rutinitas, dan dukungan dalam berlari.",
    "Bagikan kemajuan berkelanjutan dan dukungan tanpa tekanan perbandingan.",
    "Tampilkan pengikut",
    "Tampilkan yang diikuti",
    "Tampilkan teman",
    "Tampilkan tingkat keanggotaan",
    "Tampilkan postingan di profil saya",
    "Masuk untuk menerima",
    "Masuk untuk melihat BIL Gold dan hadiah.",
    "Masuk untuk melihat profil Komunitas.",
    "Seseorang menyukai postingan Anda",
    "Mata uang Komunitas yang dapat digunakan",
    "Mulai postingan",
    "Pemula",
    "Dukung rutinitas tidur yang lebih baik tanpa klaim medis.",
    "Undangan ini tidak valid atau sudah kedaluwarsa.",
    "Undangan ini tidak valid, kedaluwarsa, atau sudah digunakan.",
    "Undangan ini tidak tersedia.",
    "Undangan ini sudah digunakan.",
    "Daftar ini tidak tersedia saat ini.",
    "Hadiah ini tidak tersedia saat ini.",
    "Topik tidak tersedia saat ini. Anda tetap dapat membuat postingan.",
    "Topik — pilih hingga 3",
    "Undangan BIL yang dilacak belum aktif.",
    "Undangan yang dilacak belum aktif.",
    "Digunakan",
    "Lihat {count} balasan",
    "Pilih",
    "Mingguan",
    "Perjalanan Menurunkan Berat Badan",
    "Anda tidak dapat menerima undangan Anda sendiri.",
    "Anda mendapatkan hadiah Komunitas",
    "Anda disebut dalam sebuah postingan",
    "Permintaan pertemanan Anda diterima",
    "Postingan Anda disimpan",
    "Anda berteman — lihat profil",
    "pengikut",
    "anggota",
    "postingan",
  ],
  'ms': <String>[
    "{actor} menerima permintaan persahabatan anda",
    "{actor} mengulas siaran anda",
    "{actor} mula mengikuti anda",
    "{actor} menyukai siaran anda",
    "{actor} menyebut anda dalam satu siaran",
    "{actor} membalas ulasan anda",
    "{actor} menghantar permintaan persahabatan kepada anda",
    "{inviterName} menjemput anda menyertai BIL",
    "{total} undian",
    "10 Ribu Langkah",
    "Ruang mesra untuk kemajuan kecergasan yang selamat dan beransur-ansur.",
    "Penggunaan AI Coach",
    "Terima jemputan",
    "Siaran daripada rakan yang diterima akan muncul di sini.",
    "Menerima jemputan merekodkan siapa yang menjemput anda. Ia tidak memberikan Gold dengan sendirinya.",
    "Tambah tinjauan",
    "Tambah pilihan",
    "Benarkan berbilang pilihan",
    "Jemputan lain sudah dipautkan kepada akaun ini.",
    "Tanya satu soalan dengan 2–6 pilihan.",
    "Aktiviti BIL Gold",
    "Ganjaran BIL",
    "BIL tidak dapat mengesahkan jemputan ini dengan selamat.",
    "BIL tidak dapat mengesahkan status ganjaran anda dengan selamat.",
    "Jemputan BIL",
    "Pelarasan baki",
    "Bersikap hormat, elakkan butiran kesihatan peribadi dan ikuti dasar Komuniti.",
    "Kecergasan Pemula",
    "Tidur Lebih Baik",
    "Bina tabiat berjalan yang konsisten dan saling memberi galakan.",
    "Kemas kini cabaran",
    "Pilih satu pilihan",
    "Pilih satu atau lebih pilihan",
    "Pilih bahagian sosial yang boleh dilihat oleh ahli lain. Data kesihatan tidak pernah disertakan.",
    "Bulatan — pilihan",
    "Bulatan",
    "Label bandar atau tempat",
    "Dituntut",
    "Ulasan & sebutan",
    "Tahap Komuniti",
    "Privasi profil Komuniti",
    "Misi Komuniti",
    "Ganjaran misi Komuniti",
    "Topik Komuniti",
    "Lengkapkan tindakan Komuniti yang disahkan untuk membuat kemajuan.",
    "Lengkapkan profil Komuniti anda",
    "Jemputan ini tidak dapat diterima dengan selamat. Cuba lagi.",
    "Ganjaran ini tidak dapat dituntut dengan selamat. Cuba lagi.",
    "Sejarah lanjut tidak dapat dimuatkan.",
    "Undian anda tidak dapat direkodkan. Cuba lagi.",
    "Sebutan tidak dapat dicari sekarang.",
    "Bulatan ini tidak dapat dikemas kini dengan selamat. Cuba lagi.",
    "Topik ini tidak dapat dikemas kini dengan selamat. Cuba lagi.",
    "Cipta siaran yang bernilai",
    "Cipta akaun",
    "Harian",
    "Bincangkan latihan kekuatan, konsistensi dan pemulihan.",
    "Peroleh",
    "Diperoleh",
    "Entri BIL Gold yang diperoleh dan digunakan akan muncul di sini.",
    "Edit profil",
    "Lengkapkan tinjauan: tambah satu soalan dan 2–6 pilihan berbeza.",
    "Ikuti",
    "Ikuti ahli untuk melihat siaran mereka yang diluluskan di sini.",
    "Pengikut",
    "Mengikuti",
    "Untuk Anda",
    "Permintaan persahabatan, hubungan yang diterima dan mesej belum dibaca akan muncul di sini.",
    "Pergi",
    "Paparan grid",
    "Pemakanan Sihat",
    "Sembunyikan balasan",
    "Jemputan diterima dan persahabatan diwujudkan. Gold masih bergantung pada akaun baharu dan semakan integriti pelayan.",
    "Jemputan disimpan.",
    "Jemputan tidak tersedia",
    "Jemput rakan",
    "Sertai",
    "Sertai Bulatan untuk membuat siaran di dalamnya.",
    "Keluar",
    "Sukaan & disimpan",
    "Paparan senarai",
    "Muat lebih banyak jalur ulasan",
    "Muat lebih banyak balasan",
    "Lokasi — pilihan",
    "Sebut orang — pilihan",
    "Sebut sehingga 10 ahli Komuniti yang boleh ditemui. Mereka hanya dimaklumkan selepas siaran diluluskan.",
    "Baharu",
    "Lencana baharu diperoleh",
    "Ulasan baharu pada siaran anda",
    "Pengikut baharu",
    "Permintaan persahabatan baharu",
    "Siaran baharu",
    "Balasan baharu kepada ulasan anda",
    "Tiada Bulatan",
    "Belum ada aktiviti Gold",
    "Tiada misi aktif sekarang",
    "Belum ada siaran diluluskan dalam Bulatan ini.",
    "Belum ada siaran diluluskan dalam topik ini.",
    "Belum ada siaran diluluskan. Mulakan perbualan pertama.",
    "Belum ada kemas kini dalam kategori ini.",
    "Belum ada siaran yang kelihatan.",
    "Belum ada yang diperibadikan. Ikuti orang, topik atau Bulatan untuk membentuk suapan ini.",
    "Tiada apa untuk dipaparkan di sini buat masa ini.",
    "Dimatikan secara lalai. BIL Gold dan Community XP kekal berasingan daripada langganan anda.",
    "Pilihan {index}",
    "Teks pilihan sahaja. BIL tidak meminta GPS untuk siaran Komuniti.",
    "Tinjauan",
    "Tinjauan ditutup",
    "Soalan tinjauan",
    "Siar dalam Bulatan",
    "Siaran adalah peribadi pada profil ini.",
    "Kualiti, moderasi dan penglibatan bermakna diperiksa terlebih dahulu.",
    "Misi selesai",
    "Ramadan & Puasa",
    "Sedia untuk dituntut",
    "Buang pilihan",
    "Ganjaran sudah dituntut.",
    "Ganjaran dituntut.",
    "Peraturan ganjaran hanya diaktifkan oleh BIL selepas pengesahan pelayan dan semakan keselamatan sedia.",
    "Ganjaran",
    "Ganjaran tidak tersedia",
    "Ganjaran hanya dibuka apabila hubungan persahabatan yang disahkan memenuhi syarat.",
    "Larian",
    "Cari nama pengguna",
    "Dilihat",
    "Tetapkan identiti awam dan pilihan privasi anda.",
    "Kongsi rutin dan pengalaman puasa dengan hormat budaya.",
    "Kongsi idea hidangan praktikal dan tabiat pemakanan mampan.",
    "Kongsi kemajuan, rutin dan galakan dalam larian.",
    "Kongsi kemajuan mampan dan sokongan tanpa tekanan perbandingan.",
    "Tunjukkan pengikut",
    "Tunjukkan yang diikuti",
    "Tunjukkan rakan",
    "Tunjukkan tahap keahlian",
    "Tunjukkan siaran pada profil saya",
    "Log masuk untuk menerima",
    "Log masuk untuk melihat BIL Gold dan ganjaran.",
    "Log masuk untuk melihat profil Komuniti.",
    "Seseorang menyukai siaran anda",
    "Mata wang Komuniti yang boleh dibelanjakan",
    "Mulakan siaran",
    "Pemula",
    "Sokong rutin tidur yang lebih baik tanpa dakwaan perubatan.",
    "Jemputan ini tidak sah atau telah tamat tempoh.",
    "Jemputan ini tidak sah, tamat tempoh atau sudah digunakan.",
    "Jemputan ini tidak tersedia.",
    "Jemputan ini sudah digunakan.",
    "Senarai ini tidak tersedia sekarang.",
    "Ganjaran ini tidak tersedia sekarang.",
    "Topik tidak tersedia sekarang. Anda masih boleh membuat siaran.",
    "Topik — pilih sehingga 3",
    "Jemputan BIL yang dijejak belum aktif.",
    "Jemputan yang dijejak belum aktif.",
    "Digunakan",
    "Lihat {count} balasan",
    "Undi",
    "Mingguan",
    "Perjalanan Menurunkan Berat Badan",
    "Anda tidak boleh menerima jemputan anda sendiri.",
    "Anda memperoleh ganjaran Komuniti",
    "Anda disebut dalam satu siaran",
    "Permintaan persahabatan anda diterima",
    "Siaran anda disimpan",
    "Anda berkawan — lihat profil",
    "pengikut",
    "ahli",
    "siaran",
  ],
  'vi': <String>[
    "{actor} đã chấp nhận lời mời kết bạn của bạn",
    "{actor} đã bình luận về bài viết của bạn",
    "{actor} đã bắt đầu theo dõi bạn",
    "{actor} đã thích bài viết của bạn",
    "{actor} đã nhắc đến bạn trong một bài viết",
    "{actor} đã trả lời bình luận của bạn",
    "{actor} đã gửi cho bạn lời mời kết bạn",
    "{inviterName} đã mời bạn tham gia BIL",
    "{total} phiếu",
    "10 nghìn bước",
    "Một không gian thân thiện cho tiến bộ thể chất an toàn và từng bước.",
    "Mức sử dụng AI Coach",
    "Chấp nhận lời mời",
    "Bài viết của những người bạn đã được chấp nhận sẽ xuất hiện tại đây.",
    "Việc chấp nhận ghi nhận ai đã mời bạn. Chỉ riêng việc này không cấp Gold.",
    "Thêm cuộc thăm dò",
    "Thêm lựa chọn",
    "Cho phép chọn nhiều phương án",
    "Một lời mời khác đã được liên kết với tài khoản này.",
    "Đặt một câu hỏi với 2–6 lựa chọn.",
    "Hoạt động BIL Gold",
    "Phần thưởng BIL",
    "BIL không thể xác minh lời mời này một cách an toàn.",
    "BIL không thể xác minh trạng thái phần thưởng của bạn một cách an toàn.",
    "Lời mời BIL",
    "Điều chỉnh số dư",
    "Hãy tôn trọng, tránh chia sẻ thông tin sức khỏe riêng tư và tuân thủ chính sách Cộng đồng.",
    "Thể lực cho người mới",
    "Ngủ tốt hơn",
    "Xây dựng thói quen đi bộ đều đặn và khích lệ lẫn nhau.",
    "Cập nhật thử thách",
    "Chọn một phương án",
    "Chọn một hoặc nhiều phương án",
    "Chọn những phần xã hội mà thành viên khác có thể xem. Dữ liệu sức khỏe không bao giờ được đưa vào.",
    "Vòng tròn — tùy chọn",
    "Các Vòng tròn",
    "Nhãn thành phố hoặc địa điểm",
    "Đã nhận",
    "Bình luận & lượt nhắc",
    "Cấp Cộng đồng",
    "Quyền riêng tư hồ sơ Cộng đồng",
    "Nhiệm vụ Cộng đồng",
    "Phần thưởng nhiệm vụ Cộng đồng",
    "Chủ đề Cộng đồng",
    "Hoàn thành hành động Cộng đồng đã xác minh để tiến bộ.",
    "Hoàn thiện hồ sơ Cộng đồng của bạn",
    "Không thể chấp nhận lời mời này một cách an toàn. Hãy thử lại.",
    "Không thể nhận phần thưởng này một cách an toàn. Hãy thử lại.",
    "Không thể tải thêm lịch sử.",
    "Không thể ghi nhận phiếu bầu của bạn. Hãy thử lại.",
    "Hiện không thể tìm kiếm lượt nhắc.",
    "Không thể cập nhật Vòng tròn này một cách an toàn. Hãy thử lại.",
    "Không thể cập nhật chủ đề này một cách an toàn. Hãy thử lại.",
    "Tạo một bài viết có giá trị",
    "Tạo tài khoản",
    "Hằng ngày",
    "Thảo luận về tập sức mạnh, tính nhất quán và phục hồi.",
    "Kiếm",
    "Đã kiếm",
    "Các mục BIL Gold đã kiếm và đã dùng sẽ xuất hiện tại đây.",
    "Chỉnh sửa hồ sơ",
    "Hoàn tất cuộc thăm dò: thêm một câu hỏi và 2–6 lựa chọn khác nhau.",
    "Theo dõi",
    "Theo dõi thành viên để xem bài viết đã duyệt của họ tại đây.",
    "Người theo dõi",
    "Đang theo dõi",
    "Dành cho bạn",
    "Lời mời kết bạn, kết nối đã chấp nhận và tin nhắn chưa đọc sẽ xuất hiện tại đây.",
    "Đi",
    "Chế độ lưới",
    "Ăn uống lành mạnh",
    "Ẩn câu trả lời",
    "Lời mời đã được chấp nhận và tình bạn đã được tạo. Gold vẫn phụ thuộc vào tài khoản mới và kiểm tra tính toàn vẹn của máy chủ.",
    "Đã lưu lời mời.",
    "Lời mời không khả dụng",
    "Mời một người bạn",
    "Tham gia",
    "Tham gia một Vòng tròn để đăng bài trong đó.",
    "Rời",
    "Lượt thích & đã lưu",
    "Chế độ danh sách",
    "Tải thêm chuỗi bình luận",
    "Tải thêm câu trả lời",
    "Vị trí — tùy chọn",
    "Nhắc đến mọi người — tùy chọn",
    "Nhắc tối đa 10 thành viên Cộng đồng có thể được tìm thấy. Họ chỉ được thông báo sau khi bài viết được duyệt.",
    "Mới",
    "Đã nhận huy hiệu mới",
    "Bình luận mới trên bài viết của bạn",
    "Người theo dõi mới",
    "Lời mời kết bạn mới",
    "Bài viết mới",
    "Câu trả lời mới cho bình luận của bạn",
    "Không có Vòng tròn",
    "Chưa có hoạt động Gold",
    "Hiện không có nhiệm vụ đang hoạt động",
    "Chưa có bài viết được duyệt trong Vòng tròn này.",
    "Chưa có bài viết được duyệt trong chủ đề này.",
    "Chưa có bài viết được duyệt. Hãy bắt đầu cuộc trò chuyện đầu tiên.",
    "Chưa có cập nhật trong danh mục này.",
    "Chưa có bài viết hiển thị.",
    "Chưa có nội dung cá nhân hóa. Theo dõi người, chủ đề hoặc Vòng tròn để định hình bảng tin này.",
    "Hiện chưa có gì để hiển thị ở đây.",
    "Tắt theo mặc định. BIL Gold và Community XP vẫn tách biệt với gói đăng ký của bạn.",
    "Lựa chọn {index}",
    "Chỉ văn bản tùy chọn. BIL không yêu cầu GPS cho bài viết Cộng đồng.",
    "Thăm dò",
    "Thăm dò đã đóng",
    "Câu hỏi thăm dò",
    "Đăng trong Vòng tròn",
    "Bài viết ở chế độ riêng tư trên hồ sơ này.",
    "Chất lượng, kiểm duyệt và tương tác có ý nghĩa được kiểm tra trước.",
    "Nhiệm vụ đã hoàn thành",
    "Ramadan & Nhịn ăn",
    "Sẵn sàng nhận",
    "Xóa lựa chọn",
    "Phần thưởng đã được nhận.",
    "Đã nhận phần thưởng.",
    "Quy tắc phần thưởng chỉ được BIL kích hoạt sau khi xác minh phía máy chủ và các kiểm tra an toàn đã sẵn sàng.",
    "Phần thưởng",
    "Phần thưởng không khả dụng",
    "Phần thưởng chỉ mở khóa khi mối quan hệ bạn bè đã xác minh đủ điều kiện.",
    "Chạy bộ",
    "Tìm tên người dùng",
    "Đã xem",
    "Thiết lập danh tính công khai và lựa chọn quyền riêng tư của bạn.",
    "Chia sẻ thói quen và trải nghiệm nhịn ăn phù hợp văn hóa.",
    "Chia sẻ ý tưởng bữa ăn thiết thực và thói quen ăn uống bền vững.",
    "Chia sẻ tiến bộ, thói quen và sự khích lệ trong chạy bộ.",
    "Chia sẻ tiến bộ bền vững và hỗ trợ mà không tạo áp lực so sánh.",
    "Hiển thị người theo dõi",
    "Hiển thị người đang theo dõi",
    "Hiển thị bạn bè",
    "Hiển thị cấp thành viên",
    "Hiển thị bài viết trên hồ sơ của tôi",
    "Đăng nhập để chấp nhận",
    "Đăng nhập để xem BIL Gold và phần thưởng.",
    "Đăng nhập để xem hồ sơ Cộng đồng.",
    "Ai đó đã thích bài viết của bạn",
    "Tiền tệ Cộng đồng có thể chi tiêu",
    "Bắt đầu một bài viết",
    "Người mới",
    "Hỗ trợ thói quen ngủ tốt hơn mà không đưa ra tuyên bố y khoa.",
    "Lời mời này không hợp lệ hoặc đã hết hạn.",
    "Lời mời này không hợp lệ, đã hết hạn hoặc đã được sử dụng.",
    "Lời mời này không khả dụng.",
    "Lời mời này đã được sử dụng.",
    "Danh sách này hiện không khả dụng.",
    "Phần thưởng này hiện không khả dụng.",
    "Chủ đề hiện không khả dụng. Bạn vẫn có thể đăng bài.",
    "Chủ đề — chọn tối đa 3",
    "Các lời mời BIL được theo dõi chưa hoạt động.",
    "Các lời mời được theo dõi chưa hoạt động.",
    "Đã dùng",
    "Xem {count} câu trả lời",
    "Bỏ phiếu",
    "Hằng tuần",
    "Hành trình giảm cân",
    "Bạn không thể chấp nhận lời mời của chính mình.",
    "Bạn đã nhận phần thưởng Cộng đồng",
    "Bạn được nhắc đến trong một bài viết",
    "Lời mời kết bạn của bạn đã được chấp nhận",
    "Bài viết của bạn đã được lưu",
    "Các bạn là bạn bè — xem hồ sơ",
    "người theo dõi",
    "thành viên",
    "bài viết",
  ],
};
