import 'bil_locale_policy.dart';

/// Reviewed copy for the body-model inputs and calculated composition card.
/// Every visible key is complete across the 25 release locales.
abstract final class BodyModelRuntimeCopy {
  static const supported = <String>{
    'ar',
    'en',
    'fr',
    'es',
    'tr',
    'de',
    'it',
    'pt-BR',
    'pt-PT',
    'ur',
    'fa',
    'hi',
    'id',
    'ms',
    'ja',
    'ko',
    'zh-Hans',
    'zh-Hant',
    'ru',
    'bn',
    'vi',
    'th',
    'pl',
    'nl',
    'uk',
  };

  static const values = <String, Map<String, String>>{
    'Hips': {
      'ar': 'الورك',
      'en': 'Hips',
      'fr': 'Hanches',
      'es': 'Caderas',
      'tr': 'Kalça',
      'de': 'Hüften',
      'it': 'Fianchi',
      'pt-BR': 'Quadris',
      'pt-PT': 'Ancas',
      'ur': 'کولہے',
      'fa': 'باسن',
      'hi': 'कूल्हे',
      'id': 'Pinggul',
      'ms': 'Pinggul',
      'ja': 'ヒップ',
      'ko': '엉덩이',
      'zh-Hans': '臀围',
      'zh-Hant': '臀圍',
      'ru': 'Бёдра',
      'bn': 'নিতম্ব',
      'vi': 'Vòng hông',
      'th': 'สะโพก',
      'pl': 'Biodra',
      'nl': 'Heupen',
      'uk': 'Стегна',
    },
    'Expected body composition': {
      'ar': 'تركيب الجسم المتوقع',
      'en': 'Expected body composition',
      'fr': 'Composition corporelle estimée',
      'es': 'Composición corporal estimada',
      'tr': 'Tahmini vücut kompozisyonu',
      'de': 'Geschätzte Körperzusammensetzung',
      'it': 'Composizione corporea stimata',
      'pt-BR': 'Composição corporal estimada',
      'pt-PT': 'Composição corporal estimada',
      'ur': 'متوقع جسمانی ساخت',
      'fa': 'ترکیب بدنی تخمینی',
      'hi': 'अनुमानित शारीरिक संरचना',
      'id': 'Perkiraan komposisi tubuh',
      'ms': 'Anggaran komposisi badan',
      'ja': '推定体組成',
      'ko': '예상 신체 구성',
      'zh-Hans': '预计身体成分',
      'zh-Hant': '預估身體組成',
      'ru': 'Расчётный состав тела',
      'bn': 'আনুমানিক শরীরের গঠন',
      'vi': 'Thành phần cơ thể ước tính',
      'th': 'องค์ประกอบร่างกายโดยประมาณ',
      'pl': 'Szacowany skład ciała',
      'nl': 'Geschatte lichaamssamenstelling',
      'uk': 'Розрахунковий склад тіла',
    },
    'Expected body fat': {
      'ar': 'دهون الجسم المتوقعة',
      'en': 'Expected body fat',
      'fr': 'Masse grasse estimée',
      'es': 'Grasa corporal estimada',
      'tr': 'Tahmini vücut yağı',
      'de': 'Geschätzter Körperfettanteil',
      'it': 'Grasso corporeo stimato',
      'pt-BR': 'Gordura corporal estimada',
      'pt-PT': 'Gordura corporal estimada',
      'ur': 'متوقع جسمانی چربی',
      'fa': 'چربی بدن تخمینی',
      'hi': 'अनुमानित शरीर की चर्बी',
      'id': 'Perkiraan lemak tubuh',
      'ms': 'Anggaran lemak badan',
      'ja': '推定体脂肪率',
      'ko': '예상 체지방',
      'zh-Hans': '预计体脂率',
      'zh-Hant': '預估體脂率',
      'ru': 'Расчётный процент жира',
      'bn': 'আনুমানিক শরীরের চর্বি',
      'vi': 'Mỡ cơ thể ước tính',
      'th': 'ไขมันในร่างกายโดยประมาณ',
      'pl': 'Szacowana tkanka tłuszczowa',
      'nl': 'Geschat lichaamsvet',
      'uk': 'Розрахунковий відсоток жиру',
    },
    'Expected fat-free mass': {
      'ar': 'الكتلة الخالية من الدهون المتوقعة',
      'en': 'Expected fat-free mass',
      'fr': 'Masse maigre estimée',
      'es': 'Masa libre de grasa estimada',
      'tr': 'Tahmini yağsız vücut kütlesi',
      'de': 'Geschätzte fettfreie Masse',
      'it': 'Massa magra stimata',
      'pt-BR': 'Massa livre de gordura estimada',
      'pt-PT': 'Massa isenta de gordura estimada',
      'ur': 'متوقع چربی سے پاک کمیت',
      'fa': 'توده بدون چربی تخمینی',
      'hi': 'अनुमानित वसा-रहित द्रव्यमान',
      'id': 'Perkiraan massa bebas lemak',
      'ms': 'Anggaran jisim bebas lemak',
      'ja': '推定除脂肪量',
      'ko': '예상 제지방량',
      'zh-Hans': '预计去脂体重',
      'zh-Hant': '預估去脂體重',
      'ru': 'Расчётная безжировая масса',
      'bn': 'আনুমানিক চর্বিমুক্ত ভর',
      'vi': 'Khối lượng không mỡ ước tính',
      'th': 'มวลไร้ไขมันโดยประมาณ',
      'pl': 'Szacowana masa beztłuszczowa',
      'nl': 'Geschatte vetvrije massa',
      'uk': 'Розрахункова безжирова маса',
    },
    'Higher uncertainty': {
      'ar': 'عدم يقين أعلى',
      'en': 'Higher uncertainty',
      'fr': 'Incertitude plus élevée',
      'es': 'Mayor incertidumbre',
      'tr': 'Daha yüksek belirsizlik',
      'de': 'Höhere Unsicherheit',
      'it': 'Incertezza maggiore',
      'pt-BR': 'Maior incerteza',
      'pt-PT': 'Maior incerteza',
      'ur': 'زیادہ غیر یقینی',
      'fa': 'عدم قطعیت بیشتر',
      'hi': 'अधिक अनिश्चितता',
      'id': 'Ketidakpastian lebih tinggi',
      'ms': 'Ketidakpastian lebih tinggi',
      'ja': '不確実性が高い',
      'ko': '불확실성 높음',
      'zh-Hans': '不确定性较高',
      'zh-Hant': '不確定性較高',
      'ru': 'Повышенная неопределённость',
      'bn': 'অনিশ্চয়তা বেশি',
      'vi': 'Độ không chắc chắn cao hơn',
      'th': 'ความไม่แน่นอนสูงขึ้น',
      'pl': 'Większa niepewność',
      'nl': 'Hogere onzekerheid',
      'uk': 'Вища невизначеність',
    },
    'Estimate': {
      'ar': 'تقدير',
      'en': 'Estimate',
      'fr': 'Estimation',
      'es': 'Estimación',
      'tr': 'Tahmin',
      'de': 'Schätzung',
      'it': 'Stima',
      'pt-BR': 'Estimativa',
      'pt-PT': 'Estimativa',
      'ur': 'تخمینہ',
      'fa': 'برآورد',
      'hi': 'अनुमान',
      'id': 'Perkiraan',
      'ms': 'Anggaran',
      'ja': '推定値',
      'ko': '예상치',
      'zh-Hans': '估算值',
      'zh-Hant': '估算值',
      'ru': 'Оценка',
      'bn': 'অনুমান',
      'vi': 'Ước tính',
      'th': 'ค่าประมาณ',
      'pl': 'Szacunek',
      'nl': 'Schatting',
      'uk': 'Оцінка',
    },
    'Complete the required values to calculate an estimate.': {
      'ar': 'أكمل القيم المطلوبة لحساب التقدير.',
      'en': 'Complete the required values to calculate an estimate.',
      'fr': 'Renseignez les valeurs requises pour calculer une estimation.',
      'es': 'Completa los valores necesarios para calcular una estimación.',
      'tr': 'Tahmini hesaplamak için gerekli değerleri tamamlayın.',
      'de': 'Vervollständige die Pflichtwerte, um eine Schätzung zu berechnen.',
      'it': 'Completa i valori richiesti per calcolare una stima.',
      'pt-BR': 'Preencha os valores necessários para calcular uma estimativa.',
      'pt-PT': 'Preencha os valores necessários para calcular uma estimativa.',
      'ur': 'تخمینہ نکالنے کے لیے مطلوبہ اقدار مکمل کریں۔',
      'fa': 'برای محاسبه برآورد، مقادیر لازم را کامل کنید.',
      'hi': 'अनुमान की गणना के लिए आवश्यक मान पूरे करें।',
      'id': 'Lengkapi nilai wajib untuk menghitung perkiraan.',
      'ms': 'Lengkapkan nilai wajib untuk mengira anggaran.',
      'ja': '推定値を計算するには必須項目を入力してください。',
      'ko': '예상치를 계산하려면 필수 값을 입력하세요.',
      'zh-Hans': '请填写必填值以计算估算结果。',
      'zh-Hant': '請填寫必填值以計算估算結果。',
      'ru': 'Заполните обязательные значения, чтобы рассчитать оценку.',
      'bn': 'অনুমান হিসাব করতে প্রয়োজনীয় মানগুলো পূরণ করুন।',
      'vi': 'Hoàn tất các giá trị bắt buộc để tính ước tính.',
      'th': 'กรอกค่าที่จำเป็นให้ครบเพื่อคำนวณค่าประมาณ',
      'pl': 'Uzupełnij wymagane wartości, aby obliczyć szacunek.',
      'nl': 'Vul de vereiste waarden in om een schatting te berekenen.',
      'uk': 'Заповніть обов’язкові значення, щоб розрахувати оцінку.',
    },
    'Circumference estimate using waist, neck and height.': {
      'ar': 'تقدير بالمحيطات باستخدام الخصر والرقبة والطول.',
      'en': 'Circumference estimate using waist, neck and height.',
      'fr':
          'Estimation par circonférence avec la taille, le cou et la stature.',
      'es': 'Estimación por perímetros usando cintura, cuello y estatura.',
      'tr': 'Bel, boyun ve boy kullanılarak çevre tahmini.',
      'de': 'Umfangsschätzung anhand von Taille, Hals und Körpergröße.',
      'it': 'Stima da circonferenze con vita, collo e altezza.',
      'pt-BR':
          'Estimativa por circunferência usando cintura, pescoço e altura.',
      'pt-PT': 'Estimativa por perímetros usando cintura, pescoço e altura.',
      'ur': 'کمر، گردن اور قد سے محیطی تخمینہ۔',
      'fa': 'برآورد محیطی با استفاده از کمر، گردن و قد.',
      'hi': 'कमर, गर्दन और लंबाई से परिधि-आधारित अनुमान।',
      'id': 'Perkiraan lingkar menggunakan pinggang, leher, dan tinggi.',
      'ms': 'Anggaran lilitan menggunakan pinggang, leher dan tinggi.',
      'ja': 'ウエスト、首回り、身長による周囲径推定です。',
      'ko': '허리, 목둘레, 키를 사용한 둘레 기반 예상치입니다.',
      'zh-Hans': '使用腰围、颈围和身高进行围度估算。',
      'zh-Hant': '使用腰圍、頸圍和身高進行圍度估算。',
      'ru': 'Оценка по обхватам талии, шеи и росту.',
      'bn': 'কোমর, ঘাড় ও উচ্চতা ব্যবহার করে পরিধিভিত্তিক অনুমান।',
      'vi': 'Ước tính theo vòng eo, vòng cổ và chiều cao.',
      'th': 'ประมาณจากรอบเอว รอบคอ และส่วนสูง',
      'pl': 'Szacunek obwodowy na podstawie talii, szyi i wzrostu.',
      'nl': 'Omtrekschatting met taille, nek en lengte.',
      'uk': 'Оцінка за обхватами талії, шиї та зростом.',
    },
    'Circumference estimate using waist, hips, neck and height.': {
      'ar': 'تقدير بالمحيطات باستخدام الخصر والورك والرقبة والطول.',
      'en': 'Circumference estimate using waist, hips, neck and height.',
      'fr':
          'Estimation par circonférence avec la taille, les hanches, le cou et la stature.',
      'es':
          'Estimación por perímetros usando cintura, caderas, cuello y estatura.',
      'tr': 'Bel, kalça, boyun ve boy kullanılarak çevre tahmini.',
      'de': 'Umfangsschätzung anhand von Taille, Hüften, Hals und Körpergröße.',
      'it': 'Stima da circonferenze con vita, fianchi, collo e altezza.',
      'pt-BR':
          'Estimativa por circunferência usando cintura, quadris, pescoço e altura.',
      'pt-PT':
          'Estimativa por perímetros usando cintura, ancas, pescoço e altura.',
      'ur': 'کمر، کولہوں، گردن اور قد سے محیطی تخمینہ۔',
      'fa': 'برآورد محیطی با استفاده از کمر، باسن، گردن و قد.',
      'hi': 'कमर, कूल्हे, गर्दन और लंबाई से परिधि-आधारित अनुमान।',
      'id':
          'Perkiraan lingkar menggunakan pinggang, pinggul, leher, dan tinggi.',
      'ms': 'Anggaran lilitan menggunakan pinggang, pinggul, leher dan tinggi.',
      'ja': 'ウエスト、ヒップ、首回り、身長による周囲径推定です。',
      'ko': '허리, 엉덩이, 목둘레, 키를 사용한 둘레 기반 예상치입니다.',
      'zh-Hans': '使用腰围、臀围、颈围和身高进行围度估算。',
      'zh-Hant': '使用腰圍、臀圍、頸圍和身高進行圍度估算。',
      'ru': 'Оценка по обхватам талии, бёдер, шеи и росту.',
      'bn': 'কোমর, নিতম্ব, ঘাড় ও উচ্চতা ব্যবহার করে পরিধিভিত্তিক অনুমান।',
      'vi': 'Ước tính theo vòng eo, vòng hông, vòng cổ và chiều cao.',
      'th': 'ประมาณจากรอบเอว รอบสะโพก รอบคอ และส่วนสูง',
      'pl': 'Szacunek obwodowy na podstawie talii, bioder, szyi i wzrostu.',
      'nl': 'Omtrekschatting met taille, heupen, nek en lengte.',
      'uk': 'Оцінка за обхватами талії, стегон, шиї та зростом.',
    },
    'BMI-and-age fallback. Add complete circumferences for a more direct estimate.': {
      'ar':
          'تقدير بديل يعتمد على مؤشر الكتلة والعمر. أضف المحيطات الكاملة لتقدير أكثر مباشرة.',
      'en':
          'BMI-and-age fallback. Add complete circumferences for a more direct estimate.',
      'fr':
          'Estimation de secours selon l’IMC et l’âge. Ajoutez tous les périmètres pour une estimation plus directe.',
      'es':
          'Estimación alternativa según IMC y edad. Añade todos los perímetros para una estimación más directa.',
      'tr':
          'BKİ ve yaşa dayalı yedek tahmin. Daha doğrudan bir tahmin için tüm çevreleri ekleyin.',
      'de':
          'Ersatzschätzung nach BMI und Alter. Ergänze alle Umfänge für eine direktere Schätzung.',
      'it':
          'Stima alternativa da BMI ed età. Aggiungi tutte le circonferenze per una stima più diretta.',
      'pt-BR':
          'Estimativa alternativa por IMC e idade. Adicione todas as circunferências para uma estimativa mais direta.',
      'pt-PT':
          'Estimativa alternativa por IMC e idade. Adicione todos os perímetros para uma estimativa mais direta.',
      'ur':
          'BMI اور عمر پر مبنی متبادل تخمینہ۔ زیادہ براہ راست تخمینے کے لیے تمام محیط درج کریں۔',
      'fa':
          'برآورد جایگزین بر پایه BMI و سن. برای برآورد مستقیم‌تر همه محیط‌ها را وارد کنید.',
      'hi':
          'BMI और उम्र पर आधारित वैकल्पिक अनुमान। अधिक प्रत्यक्ष अनुमान के लिए सभी परिधियाँ जोड़ें।',
      'id':
          'Perkiraan cadangan berbasis BMI dan usia. Tambahkan semua lingkar untuk perkiraan lebih langsung.',
      'ms':
          'Anggaran sandaran berdasarkan BMI dan umur. Tambah semua lilitan untuk anggaran lebih langsung.',
      'ja': 'BMIと年齢による代替推定です。より直接的な推定には周囲径をすべて入力してください。',
      'ko': 'BMI와 나이를 사용한 대체 예상치입니다. 더 직접적인 예측을 위해 모든 둘레를 입력하세요.',
      'zh-Hans': '基于 BMI 和年龄的备用估算。填写完整围度可获得更直接的估算。',
      'zh-Hant': '基於 BMI 和年齡的備用估算。填寫完整圍度可獲得更直接的估算。',
      'ru':
          'Резервная оценка по ИМТ и возрасту. Добавьте все обхваты для более прямой оценки.',
      'bn':
          'BMI ও বয়সভিত্তিক বিকল্প অনুমান। আরও সরাসরি অনুমানের জন্য সব পরিধি যোগ করুন।',
      'vi':
          'Ước tính dự phòng theo BMI và tuổi. Thêm đủ số đo vòng để có ước tính trực tiếp hơn.',
      'th':
          'ค่าประมาณสำรองจาก BMI และอายุ เพิ่มรอบวัดให้ครบเพื่อประมาณได้ตรงยิ่งขึ้น',
      'pl':
          'Szacunek zastępczy na podstawie BMI i wieku. Dodaj pełne obwody, aby uzyskać bardziej bezpośredni wynik.',
      'nl':
          'Alternatieve schatting op basis van BMI en leeftijd. Voeg alle omtrekken toe voor een directere schatting.',
      'uk':
          'Резервна оцінка за ІМТ і віком. Додайте всі обхвати для прямішої оцінки.',
    },
    'Educational estimate, not a diagnosis.': {
      'ar': 'تقدير تعليمي وليس تشخيصًا.',
      'en': 'Educational estimate, not a diagnosis.',
      'fr': 'Estimation éducative, pas un diagnostic.',
      'es': 'Estimación educativa, no un diagnóstico.',
      'tr': 'Eğitsel bir tahmindir; tanı değildir.',
      'de': 'Eine informative Schätzung, keine Diagnose.',
      'it': 'Stima informativa, non una diagnosi.',
      'pt-BR': 'Estimativa educativa, não é um diagnóstico.',
      'pt-PT': 'Estimativa informativa, não é um diagnóstico.',
      'ur': 'تعلیمی تخمینہ ہے، تشخیص نہیں۔',
      'fa': 'برآورد آموزشی است، نه تشخیص.',
      'hi': 'शैक्षिक अनुमान है, निदान नहीं।',
      'id': 'Perkiraan edukatif, bukan diagnosis.',
      'ms': 'Anggaran pendidikan, bukan diagnosis.',
      'ja': '参考用の推定値であり、診断ではありません。',
      'ko': '교육 목적의 예상치이며 진단이 아닙니다.',
      'zh-Hans': '仅供教育参考，并非诊断。',
      'zh-Hant': '僅供教育參考，並非診斷。',
      'ru': 'Информационная оценка, а не диагноз.',
      'bn': 'শিক্ষামূলক অনুমান, রোগ নির্ণয় নয়।',
      'vi': 'Ước tính mang tính giáo dục, không phải chẩn đoán.',
      'th': 'เป็นค่าประมาณเพื่อความรู้ ไม่ใช่การวินิจฉัย',
      'pl': 'Szacunek edukacyjny, nie diagnoza.',
      'nl': 'Educatieve schatting, geen diagnose.',
      'uk': 'Інформаційна оцінка, а не діагноз.',
    },
  };

  static String? resolve(String english, String localeTag) {
    final canonical = BilLocalePolicy.canonicalSupportedTag(localeTag);
    return canonical == null ? null : values[english]?[canonical];
  }

  static bool get balanced =>
      supported.length == 25 &&
      values.values.every(
        (translations) =>
            translations.length == supported.length &&
            translations.keys.toSet().containsAll(supported) &&
            supported.containsAll(translations.keys) &&
            translations.values.every((value) => value.trim().isNotEmpty),
      );
}
