part of 'runtime_copy_community_social.dart';

const _communitySocialAsiaRows = <String, List<String>>{
  'ur': <String>[
    'BIL پر @{handle} کو شامل کریں: {uri}',
    'دوست شامل کریں',
    'مسدود کریں',
    'اس رکن کو مسدود کریں؟',
    'کیمرے تک رسائی مسترد یا محدود ہے۔ اسے سسٹم کی ترتیبات میں فعال کریں اور دوبارہ کوشش کریں۔',
    'جواب منسوخ کریں',
    'کوڈ اسکین کرنے کے لیے iOS یا Android کیمرہ درکار ہے۔',
    'تبصرہ نہیں بھیجا گیا۔ آپ کا متن محفوظ ہے؛ دوبارہ کوشش کریں۔',
    'تبصرے',
    'پرانی پوسٹس لوڈ نہیں ہو سکیں۔ دوبارہ کوشش کریں۔',
    'محفوظ پوسٹس اپ ڈیٹ نہیں ہو سکیں۔ دوبارہ کوشش کریں۔',
    'اس ردِعمل کو اپ ڈیٹ نہیں کیا جا سکا۔ دوبارہ کوشش کریں۔',
    'دوستی کی درخواست نہیں بھیجی جا سکی۔ دوبارہ کوشش کریں۔',
    'کسی دوست سے یہ کوڈ اسکین کروائیں۔ یہ صرف آپ کے عوامی کمیونٹی پروفائل کی شناخت کرتا ہے؛ اس سے کسی کو سائن اِن نہیں کیا جا سکتا۔',
    'مزید لوڈ کریں',
    'مزید تبصرے لوڈ کریں',
    'پرانی پوسٹس لوڈ کریں',
    'رکن مسدود کر دیا گیا۔',
    'میرا BIL کوڈ',
    'ابھی کوئی تبصرہ نہیں۔ احترام کے ساتھ گفتگو شروع کریں۔',
    'کیمرے کو BIL کے دوستی کوڈ پر رکھیں۔ کچھ بھی اپ لوڈ نہیں کیا جاتا۔',
    'پوسٹ',
    'آپ کی محفوظ کردہ پوسٹس نجی رہتی ہیں اور یہاں دکھائی دیتی ہیں۔',
    'محفوظ فہرست سے ہٹائیں',
    'کوڈ تبدیل کریں',
    'یہ کوڈ تبدیل کریں',
    'اپنا BIL کوڈ تبدیل کریں؟',
    'جواب دیں',
    '{member} کو جواب دیا جا رہا ہے',
    'رپورٹ انسانی جائزے کے لیے بھیج دی گئی۔',
    'کیمرہ دوبارہ آزمائیں',
    'درخواست کا جائزہ لیں',
    'پوسٹ محفوظ کریں',
    'محفوظ پوسٹس',
    'دوستی کا کوڈ اسکین کریں',
    'تبصرہ بھیجیں',
    'کوڈ شیئر کریں',
    'پوسٹ شیئر کریں',
    'کم دکھائیں',
    'مزید دکھائیں',
    'یہ کوڈ غلط، میعاد ختم، نجی یا غیر دستیاب ہے۔',
    'یہ BIL کا موجودہ دوستی کوڈ نہیں ہے۔',
    'تبصرہ لکھیں',
    'پہلے تبصرہ لکھیں۔',
    'اب آپ کمیونٹی یا پیغامات میں ایک دوسرے کو نہیں دیکھ سکیں گے۔',
    'آپ کا BIL کوڈ اس وقت دستیاب نہیں۔ دوبارہ کوشش کریں۔',
    'آپ کا BIL کوڈ دستیاب نہیں۔ سائن اِن کریں، اپنا کمیونٹی پروفائل مکمل کریں، پھر دوبارہ کوشش کریں۔',
    'آپ کا پرانا کوڈ کام کرنا بند کر دے گا۔ دوستوں کو نیا کوڈ درکار ہوگا۔',
  ],
  'fa': <String>[
    '@{handle} را در BIL اضافه کنید: {uri}',
    'افزودن دوست',
    'مسدود کردن',
    'این عضو مسدود شود؟',
    'دسترسی به دوربین رد یا محدود شده است. آن را در تنظیمات سیستم فعال کنید و دوباره امتحان کنید.',
    'لغو پاسخ',
    'اسکن کد به دوربین iOS یا Android نیاز دارد.',
    'دیدگاه ارسال نشد. متن شما حفظ شده است؛ دوباره امتحان کنید.',
    'دیدگاه‌ها',
    'بارگیری پست‌های قدیمی‌تر ممکن نشد. دوباره امتحان کنید.',
    'به‌روزرسانی پست‌های ذخیره‌شده ممکن نشد. دوباره امتحان کنید.',
    'به‌روزرسانی این واکنش ممکن نشد. دوباره امتحان کنید.',
    'درخواست دوستی ارسال نشد. دوباره امتحان کنید.',
    'اجازه دهید یک دوست این کد را اسکن کند. این کد فقط نمایه عمومی شما در انجمن را شناسایی می‌کند و نمی‌تواند کسی را وارد حساب کند.',
    'بارگیری بیشتر',
    'بارگیری دیدگاه‌های بیشتر',
    'بارگیری پست‌های قدیمی‌تر',
    'عضو مسدود شد.',
    'کد BIL من',
    'هنوز دیدگاهی ثبت نشده است. گفت‌وگویی محترمانه آغاز کنید.',
    'دوربین را به سمت کد دوستی BIL بگیرید. چیزی بارگذاری نمی‌شود.',
    'پست',
    'پست‌هایی که ذخیره می‌کنید خصوصی هستند و اینجا نمایش داده می‌شوند.',
    'حذف از ذخیره‌شده‌ها',
    'جایگزینی کد',
    'جایگزینی این کد',
    'کد BIL خود را جایگزین می‌کنید؟',
    'پاسخ',
    'پاسخ به {member}',
    'گزارش برای بررسی انسانی ارسال شد.',
    'تلاش دوباره با دوربین',
    'بررسی درخواست',
    'ذخیره پست',
    'پست‌های ذخیره‌شده',
    'اسکن کد دوستی',
    'ارسال دیدگاه',
    'اشتراک‌گذاری کد',
    'اشتراک‌گذاری پست',
    'نمایش کمتر',
    'نمایش بیشتر',
    'این کد نامعتبر، منقضی، خصوصی یا دردسترس‌نبودنی است.',
    'این یک کد دوستی فعلی BIL نیست.',
    'نوشتن دیدگاه',
    'ابتدا یک دیدگاه بنویسید.',
    'دیگر یکدیگر را در انجمن یا پیام‌ها نخواهید دید.',
    'کد BIL شما اکنون در دسترس نیست. دوباره امتحان کنید.',
    'کد BIL شما در دسترس نیست. وارد حساب شوید، نمایه انجمن خود را تکمیل کنید و دوباره امتحان کنید.',
    'کد قدیمی شما از کار خواهد افتاد. دوستانتان به کد جدید نیاز خواهند داشت.',
  ],
  'hi': <String>[
    'BIL पर @{handle} को जोड़ें: {uri}',
    'मित्र जोड़ें',
    'ब्लॉक करें',
    'इस सदस्य को ब्लॉक करें?',
    'कैमरे की पहुँच अस्वीकृत या प्रतिबंधित है। इसे सिस्टम सेटिंग में चालू करें और फिर कोशिश करें।',
    'जवाब रद्द करें',
    'कोड स्कैन करने के लिए iOS या Android कैमरा चाहिए।',
    'टिप्पणी नहीं भेजी गई। आपका टेक्स्ट सुरक्षित है; फिर से कोशिश करें।',
    'टिप्पणियाँ',
    'पुराने पोस्ट लोड नहीं हो सके। फिर कोशिश करें।',
    'सहेजे गए पोस्ट अपडेट नहीं हो सके। फिर कोशिश करें।',
    'इस प्रतिक्रिया को अपडेट नहीं किया जा सका। फिर कोशिश करें।',
    'मित्र अनुरोध नहीं भेजा जा सका। फिर कोशिश करें।',
    'किसी मित्र को यह कोड स्कैन करने दें। यह केवल आपकी सार्वजनिक समुदाय प्रोफ़ाइल की पहचान करता है; इससे कोई भी साइन इन नहीं कर सकता।',
    'और लोड करें',
    'और टिप्पणियाँ लोड करें',
    'पुराने पोस्ट लोड करें',
    'सदस्य को ब्लॉक कर दिया गया।',
    'मेरा BIL कोड',
    'अभी कोई टिप्पणी नहीं है। सम्मानजनक बातचीत शुरू करें।',
    'कैमरे को BIL मित्र कोड की ओर करें। कुछ भी अपलोड नहीं किया जाता।',
    'पोस्ट',
    'आपके सहेजे गए पोस्ट निजी रहते हैं और यहाँ दिखाई देते हैं।',
    'सहेजे गए से हटाएँ',
    'कोड बदलें',
    'यह कोड बदलें',
    'अपना BIL कोड बदलें?',
    'जवाब दें',
    '{member} को जवाब दिया जा रहा है',
    'रिपोर्ट मानवीय समीक्षा के लिए भेजी गई।',
    'कैमरा फिर आज़माएँ',
    'अनुरोध की समीक्षा करें',
    'पोस्ट सहेजें',
    'सहेजे गए पोस्ट',
    'मित्र कोड स्कैन करें',
    'टिप्पणी भेजें',
    'कोड साझा करें',
    'पोस्ट साझा करें',
    'कम दिखाएँ',
    'ज़्यादा दिखाएँ',
    'यह कोड अमान्य, समाप्त, निजी या अनुपलब्ध है।',
    'यह मौजूदा BIL मित्र कोड नहीं है।',
    'टिप्पणी लिखें',
    'पहले टिप्पणी लिखें।',
    'अब आप समुदाय या संदेशों में एक-दूसरे को नहीं देखेंगे।',
    'आपका BIL कोड अभी उपलब्ध नहीं है। फिर कोशिश करें।',
    'आपका BIL कोड उपलब्ध नहीं है। साइन इन करें, अपनी समुदाय प्रोफ़ाइल पूरी करें और फिर कोशिश करें।',
    'आपका पुराना कोड काम करना बंद कर देगा। मित्रों को नए कोड की आवश्यकता होगी।',
  ],
  'id': <String>[
    'Tambahkan @{handle} di BIL: {uri}',
    'Tambah Teman',
    'Blokir',
    'Blokir anggota ini?',
    'Akses kamera ditolak atau dibatasi. Aktifkan di pengaturan sistem lalu coba lagi.',
    'Batalkan balasan',
    'Pemindaian kode memerlukan kamera iOS atau Android.',
    'Komentar tidak terkirim. Teks Anda tetap disimpan; silakan coba lagi.',
    'Komentar',
    'Postingan lama tidak dapat dimuat. Coba lagi.',
    'Postingan tersimpan tidak dapat diperbarui. Coba lagi.',
    'Reaksi ini tidak dapat diperbarui. Coba lagi.',
    'Permintaan pertemanan tidak dapat dikirim. Coba lagi.',
    'Minta teman memindai kode ini. Kode ini hanya mengidentifikasi profil Komunitas publik Anda; kode ini tidak dapat digunakan untuk masuk ke akun siapa pun.',
    'Muat lainnya',
    'Muat komentar lainnya',
    'Muat postingan lama',
    'Anggota diblokir.',
    'Kode BIL Saya',
    'Belum ada komentar. Mulai percakapan yang saling menghormati.',
    'Arahkan kamera ke kode teman BIL. Tidak ada yang diunggah.',
    'Postingan',
    'Postingan yang Anda simpan bersifat privat dan muncul di sini.',
    'Hapus dari tersimpan',
    'Ganti kode',
    'Ganti kode ini',
    'Ganti Kode BIL Anda?',
    'Balas',
    'Membalas {member}',
    'Laporan dikirim untuk ditinjau manusia.',
    'Coba kamera lagi',
    'Tinjau permintaan',
    'Simpan postingan',
    'Postingan tersimpan',
    'Pindai Kode Teman',
    'Kirim komentar',
    'Bagikan kode',
    'Bagikan postingan',
    'Tampilkan lebih sedikit',
    'Tampilkan lebih banyak',
    'Kode ini tidak valid, kedaluwarsa, privat, atau tidak tersedia.',
    'Ini bukan kode teman BIL yang berlaku saat ini.',
    'Tulis komentar',
    'Tulis komentar terlebih dahulu.',
    'Anda tidak akan lagi saling melihat di Komunitas atau pesan.',
    'Kode BIL Anda sedang tidak tersedia. Coba lagi.',
    'Kode BIL Anda tidak tersedia. Masuk, lengkapi profil Komunitas Anda, lalu coba lagi.',
    'Kode lama Anda akan berhenti berfungsi. Teman perlu menggunakan kode yang baru.',
  ],
  'ms': <String>[
    'Tambah @{handle} di BIL: {uri}',
    'Tambah Rakan',
    'Sekat',
    'Sekat ahli ini?',
    'Akses kamera dinafikan atau dihadkan. Dayakannya dalam tetapan sistem dan cuba lagi.',
    'Batalkan balasan',
    'Pengimbasan kod memerlukan kamera iOS atau Android.',
    'Komen tidak dihantar. Teks anda disimpan; cuba lagi.',
    'Komen',
    'Siaran lama tidak dapat dimuatkan. Cuba lagi.',
    'Siaran yang disimpan tidak dapat dikemas kini. Cuba lagi.',
    'Reaksi ini tidak dapat dikemas kini. Cuba lagi.',
    'Permintaan rakan tidak dapat dihantar. Cuba lagi.',
    'Minta rakan mengimbas kod ini. Kod ini hanya mengenal pasti profil Komuniti awam anda; kod ini tidak boleh melog masuk sesiapa.',
    'Muatkan lagi',
    'Muatkan lebih banyak komen',
    'Muatkan siaran lama',
    'Ahli disekat.',
    'Kod BIL Saya',
    'Belum ada komen. Mulakan perbualan yang saling menghormati.',
    'Halakan kamera ke kod rakan BIL. Tiada apa-apa dimuat naik.',
    'Siaran',
    'Siaran yang anda simpan adalah peribadi dan dipaparkan di sini.',
    'Alih keluar daripada simpanan',
    'Gantikan kod',
    'Gantikan kod ini',
    'Gantikan Kod BIL anda?',
    'Balas',
    'Membalas kepada {member}',
    'Laporan dihantar untuk semakan manusia.',
    'Cuba kamera lagi',
    'Semak permintaan',
    'Simpan siaran',
    'Siaran disimpan',
    'Imbas Kod Rakan',
    'Hantar komen',
    'Kongsi kod',
    'Kongsi siaran',
    'Tunjukkan kurang',
    'Tunjukkan lagi',
    'Kod ini tidak sah, telah tamat tempoh, peribadi atau tidak tersedia.',
    'Ini bukan kod rakan BIL semasa.',
    'Tulis komen',
    'Tulis komen dahulu.',
    'Anda tidak akan dapat melihat satu sama lain lagi dalam Komuniti atau mesej.',
    'Kod BIL anda tidak tersedia sekarang. Cuba lagi.',
    'Kod BIL anda tidak tersedia. Log masuk, lengkapkan profil Komuniti anda dan cuba lagi.',
    'Kod lama anda akan berhenti berfungsi. Rakan perlu menggunakan kod baharu.',
  ],
  'bn': <String>[
    'BIL-এ @{handle}-কে যোগ করুন: {uri}',
    'বন্ধু যোগ করুন',
    'ব্লক করুন',
    'এই সদস্যকে ব্লক করবেন?',
    'ক্যামেরা ব্যবহারের অনুমতি প্রত্যাখ্যাত বা সীমিত। সিস্টেম সেটিংসে এটি চালু করে আবার চেষ্টা করুন।',
    'উত্তর বাতিল করুন',
    'কোড স্ক্যান করতে iOS বা Android ক্যামেরা প্রয়োজন।',
    'মন্তব্য পাঠানো হয়নি। আপনার লেখা রাখা হয়েছে; আবার চেষ্টা করুন।',
    'মন্তব্য',
    'পুরোনো পোস্ট লোড করা যায়নি। আবার চেষ্টা করুন।',
    'সংরক্ষিত পোস্ট আপডেট করা যায়নি। আবার চেষ্টা করুন।',
    'এই প্রতিক্রিয়া আপডেট করা যায়নি। আবার চেষ্টা করুন।',
    'বন্ধুত্বের অনুরোধ পাঠানো যায়নি। আবার চেষ্টা করুন।',
    'কোনো বন্ধুকে এই কোডটি স্ক্যান করতে দিন। এটি শুধু আপনার সর্বজনীন কমিউনিটি প্রোফাইল শনাক্ত করে; এটি কাউকে সাইন ইন করাতে পারে না।',
    'আরও লোড করুন',
    'আরও মন্তব্য লোড করুন',
    'পুরোনো পোস্ট লোড করুন',
    'সদস্যকে ব্লক করা হয়েছে।',
    'আমার BIL কোড',
    'এখনো কোনো মন্তব্য নেই। সম্মানজনক আলোচনা শুরু করুন।',
    'ক্যামেরাটি BIL বন্ধু কোডের দিকে ধরুন। কিছুই আপলোড করা হয় না।',
    'পোস্ট',
    'আপনার সংরক্ষণ করা পোস্টগুলো ব্যক্তিগত এবং এখানে দেখা যায়।',
    'সংরক্ষিত তালিকা থেকে সরান',
    'কোড বদলান',
    'এই কোডটি বদলান',
    'আপনার BIL কোড বদলাবেন?',
    'উত্তর দিন',
    '{member}-কে উত্তর দেওয়া হচ্ছে',
    'রিপোর্টটি মানব পর্যালোচনার জন্য পাঠানো হয়েছে।',
    'ক্যামেরা দিয়ে আবার চেষ্টা করুন',
    'অনুরোধ পর্যালোচনা করুন',
    'পোস্ট সংরক্ষণ করুন',
    'সংরক্ষিত পোস্ট',
    'বন্ধু কোড স্ক্যান করুন',
    'মন্তব্য পাঠান',
    'কোড শেয়ার করুন',
    'পোস্ট শেয়ার করুন',
    'কম দেখান',
    'আরও দেখান',
    'এই কোডটি অবৈধ, মেয়াদোত্তীর্ণ, ব্যক্তিগত বা অনুপলভ্য।',
    'এটি বর্তমান BIL বন্ধু কোড নয়।',
    'মন্তব্য লিখুন',
    'আগে একটি মন্তব্য লিখুন।',
    'কমিউনিটি বা বার্তায় আপনারা আর একে অপরকে দেখতে পাবেন না।',
    'আপনার BIL কোড এখন অনুপলভ্য। আবার চেষ্টা করুন।',
    'আপনার BIL কোড অনুপলভ্য। সাইন ইন করুন, কমিউনিটি প্রোফাইল সম্পূর্ণ করুন এবং আবার চেষ্টা করুন।',
    'আপনার পুরোনো কোড কাজ করা বন্ধ করবে। বন্ধুদের নতুন কোডটি লাগবে।',
  ],
};
