part of 'runtime_copy_next_workspace.dart';

const _nextWorkspaceRows0 = <String, List<String>>{
  "ar": [
    "تعذر تأكيد قراءة هذه التحديثات. حاول مجددًا.",
    "تحديد هذه الصفحة كمقروءة",
    "لنصنع فرقًا اليوم.",
    "تركيز اليوم",
    "خطوة صغيرة في كل مرة. مدربك هنا ليساعدك على التسجيل والمراجعة والتخطيط.",
    "أدوات خطتك",
    "سجّل وجبة",
    "تسجيل صوتي",
    "تحدث فقط",
    "خلال ثوانٍ",
    "مسح منتج",
    "باركود / ملصق",
    "حوّل وجبتك إلى معلومات",
    "التقط صورة لمراجعة الطعام والكميات قبل إضافتها إلى سجلك.",
    "جرّب تسجيل الصورة  ‹",
    "تسلسل يومك الصحي",
    "وجبات مسجلة",
    "{count} وجبات في سجلك الفعلي",
    "نشاط متزامن",
    "ستظهر تسجيلاتك الفعلية هنا.",
    "خطوات صغيرة مستمرة تصنع تقدمًا حقيقيًا.\n— مدرب BIL الذكي",
    "شريك صحتك، معك دائمًا",
    "ابحث في محادثاتك",
  ],
  "fr": [
    "Impossible de confirmer la lecture de ces mises à jour. Réessayez.",
    "Marquer cette page comme lue",
    "Faisons de cette journée une réussite.",
    "Priorité du jour",
    "Une petite action à la fois. Votre coach vous aide à noter, faire le point et planifier.",
    "Outils de votre programme",
    "Noter un repas",
    "Saisie vocale",
    "Parlez simplement",
    "En quelques secondes",
    "Scanner un produit",
    "Code-barres / Étiquette",
    "Comprenez mieux chaque repas",
    "Prenez une photo pour vérifier les aliments et les portions avant de les ajouter à votre journal.",
    "Essayer la saisie photo  ›",
    "Votre suivi santé",
    "Repas enregistrés",
    "{count} repas dans votre journal réel",
    "Activité synchronisée",
    "Vos données vérifiées apparaîtront ici.",
    "De petites actions régulières permettent de vrais progrès.\n— Coach IA BIL",
    "Votre partenaire santé, toujours à vos côtés",
    "Rechercher des conversations",
  ],
  "es": [
    "No se pudo confirmar la lectura de estas actualizaciones. Inténtalo de nuevo.",
    "Marcar esta página como leída",
    "Hagamos que hoy cuente.",
    "Prioridad de hoy",
    "Una pequeña acción cada vez. Tu entrenador te ayuda a registrar, reflexionar y planificar.",
    "Herramientas de tu plan",
    "Registrar una comida",
    "Registro por voz",
    "Solo habla",
    "En segundos",
    "Escanear producto",
    "Código de barras / Etiqueta",
    "Comprende mejor cada comida",
    "Haz una foto para revisar los alimentos y las porciones antes de añadirlos a tu diario.",
    "Probar registro con foto  ›",
    "Tu historial de salud",
    "Comidas registradas",
    "{count} comidas en tu diario real",
    "Actividad sincronizada",
    "Tus registros verificados aparecerán aquí.",
    "Las pequeñas acciones constantes generan un progreso real.\n— Entrenador IA BIL",
    "Tu compañero de salud, siempre contigo",
    "Buscar conversaciones",
  ],
  "tr": [
    "Bu güncellemelerin okunduğu doğrulanamadı. Lütfen yeniden deneyin.",
    "Bu sayfayı okundu olarak işaretle",
    "Bugünü verimli geçirelim.",
    "Bugünün odağı",
    "Her seferinde küçük bir adım. Koçunuz kayıt tutmanıza, değerlendirmenize ve planlamanıza yardımcı olur.",
    "Plan araçları",
    "Öğün kaydet",
    "Sesli kayıt",
    "Sadece konuşun",
    "Saniyeler içinde",
    "Ürün tara",
    "Barkod / Etiket",
    "Her öğünden bilgi edinin",
    "Günlüğünüze eklemeden önce yiyecekleri ve porsiyonları incelemek için fotoğraf çekin.",
    "Fotoğrafla kaydı dene  ›",
    "Sağlık geçmişiniz",
    "Kaydedilen öğünler",
    "Gerçek günlüğünüzde {count} öğün kaydı",
    "Etkinlik eşitlendi",
    "Doğrulanmış kayıtlarınız burada görünecek.",
    "Küçük ve düzenli adımlar anlamlı ilerleme sağlar.\n— BIL Yapay Zekâ Koçu",
    "Sağlık yolculuğunuzda daima yanınızda",
    "Konuşmalarda ara",
  ],
  "de": [
    "Diese Updates konnten nicht als gelesen bestätigt werden. Bitte erneut versuchen.",
    "Diese Seite als gelesen markieren",
    "Machen wir das Beste aus diesem Tag.",
    "Fokus für heute",
    "Eine kleine Handlung nach der anderen. Dein Coach hilft dir beim Erfassen, Reflektieren und Planen.",
    "Planwerkzeuge",
    "Mahlzeit erfassen",
    "Spracheingabe",
    "Einfach sprechen",
    "In Sekunden",
    "Produkt scannen",
    "Barcode / Etikett",
    "Jede Mahlzeit besser verstehen",
    "Fotografiere dein Essen, um Lebensmittel und Portionen vor dem Eintragen zu prüfen.",
    "Fotoerfassung ausprobieren  ›",
    "Dein Gesundheitsverlauf",
    "Erfasste Mahlzeiten",
    "{count} Mahlzeiten in deinem tatsächlichen Tagebuch",
    "Aktivität synchronisiert",
    "Deine bestätigten Einträge erscheinen hier.",
    "Kleine, regelmäßige Schritte führen zu echten Fortschritten.\n— BIL KI-Coach",
    "Dein Gesundheitspartner, immer an deiner Seite",
    "Unterhaltungen durchsuchen",
  ],
  "it": [
    "Non è stato possibile confermare la lettura di questi aggiornamenti. Riprova.",
    "Segna questa pagina come letta",
    "Facciamo fruttare questa giornata.",
    "Priorità di oggi",
    "Una piccola azione alla volta. Il tuo coach ti aiuta a registrare, riflettere e pianificare.",
    "Strumenti del piano",
    "Registra un pasto",
    "Registrazione vocale",
    "Basta parlare",
    "In pochi secondi",
    "Scansiona prodotto",
    "Codice a barre / Etichetta",
    "Comprendi meglio ogni pasto",
    "Scatta una foto per controllare alimenti e porzioni prima di aggiungerli al diario.",
    "Prova la registrazione con foto  ›",
    "La tua cronologia salute",
    "Pasti registrati",
    "{count} pasti nel tuo diario effettivo",
    "Attività sincronizzata",
    "Le tue registrazioni verificate appariranno qui.",
    "Piccole azioni costanti creano progressi significativi.\n— Coach IA BIL",
    "Il tuo compagno di salute, sempre con te",
    "Cerca conversazioni",
  ],
};
