import 'package:flutter/widgets.dart';
import 'bil_locale_policy.dart';

/// Localized presentation only. No clinical alarm or continuous monitoring is inferred.
abstract final class SapphireCopy {
  static const keys = <String>[
    'welcome',
    'together',
    'loading',
    'dailyTotal',
    'recordedTotal',
    'dailyAverage',
    'restingAverage',
    'inProgress',
    'closedDays',
    'above100',
    'first',
    'peak',
    'heartNotice',
    'noCompleted',
    'samples',
    'summaries',
  ];
  static const values = <String, List<String>>{
    'en': [
      'Welcome to BIL Community',
      'Share your journey. Grow together.',
      'Preparing your community…',
      'Daily total',
      'Total of imported samples',
      'Average of recorded samples',
      'Average resting-heart-rate samples',
      'Today · in progress',
      'Daily averages appear after the day ends.',
      'Recorded above 100 bpm',
      'First recorded',
      'Peak reading',
      'Heart rate can rise during activity. This marker is not a medical alert.',
      'No completed days yet.',
      'Recorded samples',
      'Daily summaries',
    ],
    'ar': [
      'أهلًا بك في مجتمع BIL',
      'شارك رحلتك. نتقدم معًا.',
      'نجهّز مجتمعك…',
      'المجموع اليومي',
      'مجموع القراءات المستوردة',
      'متوسط القراءات المسجلة',
      'متوسط قراءات نبض الراحة',
      'اليوم · قيد الاكتمال',
      'يظهر المتوسط اليومي بعد انتهاء اليوم.',
      'قراءة أعلى من ١٠٠ نبضة/دقيقة',
      'أول تسجيل',
      'أعلى قراءة',
      'قد يرتفع النبض أثناء النشاط. هذه العلامة ليست إنذارًا طبيًا.',
      'لا توجد أيام مكتملة بعد.',
      'القراءات المسجلة',
      'ملخصات الأيام',
    ],
    'fr': [
      'Bienvenue dans la communauté BIL',
      'Partagez votre parcours. Avançons ensemble.',
      'Préparation de votre communauté…',
      'Total quotidien',
      'Total des mesures importées',
      'Moyenne des mesures enregistrées',
      'Moyenne des mesures du pouls au repos',
      'Aujourd’hui · en cours',
      'Les moyennes quotidiennes apparaissent après la fin de la journée.',
      'Mesure supérieure à 100 bpm',
      'Première mesure',
      'Mesure maximale',
      'Le pouls peut augmenter pendant une activité. Ce repère n’est pas une alerte médicale.',
      'Aucune journée terminée.',
      'Mesures enregistrées',
      'Résumés quotidiens',
    ],
    'es': [
      'Te damos la bienvenida a BIL Community',
      'Comparte tu camino. Crezcamos juntos.',
      'Preparando tu comunidad…',
      'Total diario',
      'Total de las muestras importadas',
      'Promedio de las muestras registradas',
      'Promedio de las muestras del pulso en reposo',
      'Hoy · en curso',
      'Los promedios diarios aparecen al terminar el día.',
      'Registro superior a 100 lpm',
      'Primer registro',
      'Lectura máxima',
      'El pulso puede subir durante la actividad. Esta marca no es una alerta médica.',
      'Aún no hay días completos.',
      'Muestras registradas',
      'Resúmenes diarios',
    ],
    'de': [
      'Willkommen in der BIL-Community',
      'Teile deinen Weg. Gemeinsam wachsen.',
      'Deine Community wird vorbereitet…',
      'Tagessumme',
      'Summe importierter Messwerte',
      'Durchschnitt erfasster Messwerte',
      'Durchschnitt erfasster Ruhepulswerte',
      'Heute · noch nicht abgeschlossen',
      'Tagesdurchschnitte erscheinen nach Tagesende.',
      'Messwert über 100 Schlägen/min',
      'Erste Erfassung',
      'Höchster Messwert',
      'Der Puls kann bei Aktivität steigen. Diese Markierung ist kein medizinischer Alarm.',
      'Noch keine abgeschlossenen Tage.',
      'Erfasste Messwerte',
      'Tagesübersichten',
    ],
    'it': [
      'Benvenuto nella community BIL',
      'Condividi il tuo percorso. Cresciamo insieme.',
      'Preparazione della tua community…',
      'Totale giornaliero',
      'Totale dei campioni importati',
      'Media dei campioni registrati',
      'Media dei campioni del battito a riposo',
      'Oggi · in corso',
      'Le medie giornaliere appaiono al termine della giornata.',
      'Valore registrato oltre 100 bpm',
      'Prima rilevazione',
      'Valore massimo',
      'Il battito può aumentare durante l’attività. Questo indicatore non è un allarme medico.',
      'Nessuna giornata completa.',
      'Campioni registrati',
      'Riepiloghi giornalieri',
    ],
    'pt-BR': [
      'Boas-vindas à comunidade BIL',
      'Compartilhe sua jornada. Vamos crescer juntos.',
      'Preparando sua comunidade…',
      'Total diário',
      'Total das amostras importadas',
      'Média das amostras registradas',
      'Média das amostras do pulso em repouso',
      'Hoje · em andamento',
      'As médias diárias aparecem após o fim do dia.',
      'Registro acima de 100 bpm',
      'Primeiro registro',
      'Maior leitura',
      'O pulso pode subir durante a atividade. Este marcador não é um alerta médico.',
      'Ainda não há dias completos.',
      'Amostras registradas',
      'Resumos diários',
    ],
    'pt-PT': [
      'Bem-vindo à comunidade BIL',
      'Partilhe o seu percurso. Crescemos juntos.',
      'A preparar a sua comunidade…',
      'Total diário',
      'Total das amostras importadas',
      'Média das amostras registadas',
      'Média das amostras do pulso em repouso',
      'Hoje · em curso',
      'As médias diárias aparecem depois do fim do dia.',
      'Registo acima de 100 bpm',
      'Primeiro registo',
      'Leitura máxima',
      'O pulso pode subir durante a atividade. Este marcador não é um alerta médico.',
      'Ainda não há dias completos.',
      'Amostras registadas',
      'Resumos diários',
    ],
    'tr': [
      'BIL Topluluğuna hoş geldiniz',
      'Yolculuğunu paylaş. Birlikte gelişelim.',
      'Topluluğun hazırlanıyor…',
      'Günlük toplam',
      'İçe aktarılan ölçümlerin toplamı',
      'Kaydedilen ölçümlerin ortalaması',
      'Dinlenik nabız ölçümlerinin ortalaması',
      'Bugün · devam ediyor',
      'Günlük ortalamalar gün bittikten sonra görünür.',
      '100 atım/dk üzerinde ölçüm',
      'İlk kayıt',
      'En yüksek ölçüm',
      'Nabız hareket sırasında artabilir. Bu işaret tıbbi bir alarm değildir.',
      'Henüz tamamlanmış gün yok.',
      'Kaydedilen ölçümler',
      'Günlük özetler',
    ],
    'fa': [
      'به جامعه BIL خوش آمدید',
      'مسیرتان را به اشتراک بگذارید. با هم پیشرفت کنیم.',
      'در حال آماده‌سازی جامعه شما…',
      'مجموع روزانه',
      'مجموع نمونه‌های واردشده',
      'میانگین نمونه‌های ثبت‌شده',
      'میانگین نمونه‌های ضربان در حالت استراحت',
      'امروز · در حال تکمیل',
      'میانگین روزانه پس از پایان روز نمایش داده می‌شود.',
      'ثبت بالاتر از ۱۰۰ ضربه در دقیقه',
      'اولین ثبت',
      'بالاترین مقدار',
      'ضربان ممکن است هنگام فعالیت بالا برود. این نشانگر هشدار پزشکی نیست.',
      'هنوز روز کاملی وجود ندارد.',
      'نمونه‌های ثبت‌شده',
      'خلاصه‌های روزانه',
    ],
    'ur': [
      'BIL کمیونٹی میں خوش آمدید',
      'اپنا سفر شیئر کریں۔ مل کر آگے بڑھیں۔',
      'آپ کی کمیونٹی تیار ہو رہی ہے…',
      'روزانہ کا مجموعہ',
      'درآمد شدہ پیمائشوں کا مجموعہ',
      'درج شدہ پیمائشوں کی اوسط',
      'آرام کی حالت میں نبض کی پیمائشوں کی اوسط',
      'آج · جاری ہے',
      'روزانہ کی اوسط دن ختم ہونے کے بعد ظاہر ہوتی ہے۔',
      '۱۰۰ دھڑکن فی منٹ سے زیادہ پیمائش',
      'پہلا اندراج',
      'سب سے زیادہ پیمائش',
      'سرگرمی کے دوران نبض بڑھ سکتی ہے۔ یہ نشان طبی انتباہ نہیں ہے۔',
      'ابھی کوئی مکمل دن نہیں۔',
      'درج شدہ پیمائشیں',
      'روزانہ کے خلاصے',
    ],
    'hi': [
      'BIL समुदाय में आपका स्वागत है',
      'अपनी यात्रा साझा करें। साथ आगे बढ़ें।',
      'आपका समुदाय तैयार हो रहा है…',
      'दैनिक कुल',
      'आयातित मापों का कुल',
      'दर्ज मापों का औसत',
      'आराम की धड़कन के मापों का औसत',
      'आज · जारी है',
      'दैनिक औसत दिन समाप्त होने के बाद दिखते हैं।',
      '100 धड़कन/मिनट से ऊपर दर्ज',
      'पहला माप',
      'सबसे अधिक माप',
      'गतिविधि के दौरान धड़कन बढ़ सकती है। यह संकेत चिकित्सकीय चेतावनी नहीं है।',
      'अभी कोई पूरा दिन नहीं है।',
      'दर्ज माप',
      'दैनिक सारांश',
    ],
    'bn': [
      'BIL কমিউনিটিতে স্বাগতম',
      'নিজের পথচলা শেয়ার করুন। একসঙ্গে এগিয়ে যাই।',
      'আপনার কমিউনিটি প্রস্তুত হচ্ছে…',
      'দৈনিক মোট',
      'আমদানি করা পরিমাপের মোট',
      'রেকর্ড করা পরিমাপের গড়',
      'বিশ্রামের হৃদস্পন্দনের পরিমাপের গড়',
      'আজ · চলমান',
      'দিন শেষ হওয়ার পরে দৈনিক গড় দেখা যায়।',
      'মিনিটে ১০০ স্পন্দনের বেশি রেকর্ড',
      'প্রথম রেকর্ড',
      'সর্বোচ্চ পরিমাপ',
      'সক্রিয় অবস্থায় হৃদস্পন্দন বাড়তে পারে। এই চিহ্ন চিকিৎসাগত সতর্কতা নয়।',
      'এখনও কোনো সম্পূর্ণ দিন নেই।',
      'রেকর্ড করা পরিমাপ',
      'দৈনিক সারাংশ',
    ],
    'id': [
      'Selamat datang di Komunitas BIL',
      'Bagikan perjalananmu. Berkembang bersama.',
      'Menyiapkan komunitasmu…',
      'Total harian',
      'Total sampel yang diimpor',
      'Rata-rata sampel tercatat',
      'Rata-rata sampel denyut saat istirahat',
      'Hari ini · berlangsung',
      'Rata-rata harian muncul setelah hari berakhir.',
      'Tercatat di atas 100 denyut/menit',
      'Catatan pertama',
      'Nilai tertinggi',
      'Denyut dapat naik saat beraktivitas. Penanda ini bukan peringatan medis.',
      'Belum ada hari yang selesai.',
      'Sampel tercatat',
      'Ringkasan harian',
    ],
    'ms': [
      'Selamat datang ke Komuniti BIL',
      'Kongsi perjalanan anda. Maju bersama.',
      'Menyediakan komuniti anda…',
      'Jumlah harian',
      'Jumlah sampel yang diimport',
      'Purata sampel direkodkan',
      'Purata sampel denyutan semasa rehat',
      'Hari ini · masih berjalan',
      'Purata harian muncul selepas hari berakhir.',
      'Direkodkan melebihi 100 denyutan/minit',
      'Rekod pertama',
      'Bacaan tertinggi',
      'Denyutan boleh meningkat ketika aktif. Penanda ini bukan amaran perubatan.',
      'Belum ada hari yang lengkap.',
      'Sampel direkodkan',
      'Ringkasan harian',
    ],
    'ja': [
      'BILコミュニティへようこそ',
      '歩みを分かち合い、ともに成長。',
      'コミュニティを準備しています…',
      '1日の合計',
      '取り込んだ測定値の合計',
      '記録された測定値の平均',
      '安静時心拍数の測定値の平均',
      '今日・集計中',
      '1日の平均はその日が終わってから表示されます。',
      '毎分100拍を超える記録',
      '最初の記録',
      '最大の測定値',
      '活動中は心拍数が上がることがあります。この表示は医療警報ではありません。',
      '終了した日のデータはまだありません。',
      '記録された測定値',
      '1日のまとめ',
    ],
    'ko': [
      'BIL 커뮤니티에 오신 것을 환영합니다',
      '여정을 나누고 함께 성장해요.',
      '커뮤니티를 준비하고 있어요…',
      '일일 합계',
      '가져온 측정값의 합계',
      '기록된 측정값의 평균',
      '안정 시 심박수 측정값의 평균',
      '오늘 · 진행 중',
      '일일 평균은 하루가 끝난 후 표시됩니다.',
      '분당 100회 초과 기록',
      '첫 기록',
      '최고 측정값',
      '활동 중에는 심박수가 높아질 수 있습니다. 이 표시는 의료 경고가 아닙니다.',
      '아직 완료된 날짜가 없습니다.',
      '기록된 측정값',
      '일일 요약',
    ],
    'zh-Hans': [
      '欢迎来到 BIL 社区',
      '分享历程，共同成长。',
      '正在准备你的社区…',
      '每日总量',
      '导入样本总量',
      '已记录样本的平均值',
      '已记录静息心率样本的平均值',
      '今天 · 尚未结束',
      '每日平均值会在当天结束后显示。',
      '记录超过每分钟 100 次',
      '首次记录',
      '最高读数',
      '活动时心率可能升高。此标记不是医疗警报。',
      '暂无已完成日期。',
      '已记录样本',
      '每日摘要',
    ],
    'zh-Hant': [
      '歡迎來到 BIL 社群',
      '分享歷程，一同成長。',
      '正在準備你的社群…',
      '每日總量',
      '匯入樣本總量',
      '已記錄樣本的平均值',
      '已記錄靜息心率樣本的平均值',
      '今天 · 尚未結束',
      '每日平均值會在當天結束後顯示。',
      '記錄超過每分鐘 100 次',
      '首次記錄',
      '最高讀數',
      '活動時心率可能升高。此標記不是醫療警報。',
      '尚無已完成日期。',
      '已記錄樣本',
      '每日摘要',
    ],
    'ru': [
      'Добро пожаловать в сообщество BIL',
      'Делитесь своим путём. Растём вместе.',
      'Готовим ваше сообщество…',
      'Сумма за день',
      'Сумма импортированных измерений',
      'Среднее записанных измерений',
      'Среднее измерений пульса в покое',
      'Сегодня · день продолжается',
      'Средние значения появляются после окончания дня.',
      'Записано выше 100 уд/мин',
      'Первая запись',
      'Максимальное значение',
      'При активности пульс может повышаться. Эта отметка не является медицинским предупреждением.',
      'Завершённых дней пока нет.',
      'Записанные измерения',
      'Итоги дня',
    ],
    'uk': [
      'Ласкаво просимо до спільноти BIL',
      'Діліться своїм шляхом. Зростаємо разом.',
      'Готуємо вашу спільноту…',
      'Сума за день',
      'Сума імпортованих вимірювань',
      'Середнє записаних вимірювань',
      'Середнє вимірювань пульсу у спокої',
      'Сьогодні · день триває',
      'Середні значення з’являються після завершення дня.',
      'Записано понад 100 уд/хв',
      'Перший запис',
      'Найвище значення',
      'Під час активності пульс може зростати. Ця позначка не є медичним попередженням.',
      'Завершених днів ще немає.',
      'Записані вимірювання',
      'Підсумки дня',
    ],
    'pl': [
      'Witaj w społeczności BIL',
      'Podziel się swoją drogą. Rozwijajmy się razem.',
      'Przygotowujemy Twoją społeczność…',
      'Suma dzienna',
      'Suma zaimportowanych pomiarów',
      'Średnia zapisanych pomiarów',
      'Średnia pomiarów tętna spoczynkowego',
      'Dzisiaj · w toku',
      'Średnie dzienne pojawiają się po zakończeniu dnia.',
      'Zapis powyżej 100 uderzeń/min',
      'Pierwszy zapis',
      'Najwyższy pomiar',
      'Podczas aktywności tętno może wzrosnąć. Ten znacznik nie jest alarmem medycznym.',
      'Brak zakończonych dni.',
      'Zapisane pomiary',
      'Podsumowania dzienne',
    ],
    'nl': [
      'Welkom bij de BIL-community',
      'Deel je reis. Groei samen.',
      'Je community wordt voorbereid…',
      'Dagtotaal',
      'Totaal van geïmporteerde metingen',
      'Gemiddelde van vastgelegde metingen',
      'Gemiddelde van rusthartslagmetingen',
      'Vandaag · nog bezig',
      'Daggemiddelden verschijnen na afloop van de dag.',
      'Meting boven 100 slagen/min',
      'Eerste meting',
      'Hoogste meting',
      'De hartslag kan stijgen bij activiteit. Deze markering is geen medisch alarm.',
      'Nog geen afgeronde dagen.',
      'Vastgelegde metingen',
      'Dagoverzichten',
    ],
    'vi': [
      'Chào mừng đến với cộng đồng BIL',
      'Chia sẻ hành trình. Cùng nhau tiến bộ.',
      'Đang chuẩn bị cộng đồng của bạn…',
      'Tổng trong ngày',
      'Tổng các mẫu đã nhập',
      'Trung bình các mẫu đã ghi',
      'Trung bình các mẫu nhịp tim lúc nghỉ',
      'Hôm nay · đang diễn ra',
      'Trung bình ngày hiển thị sau khi ngày kết thúc.',
      'Ghi nhận trên 100 nhịp/phút',
      'Ghi nhận đầu tiên',
      'Số đo cao nhất',
      'Nhịp tim có thể tăng khi vận động. Dấu này không phải cảnh báo y tế.',
      'Chưa có ngày hoàn tất.',
      'Các mẫu đã ghi',
      'Tóm tắt hằng ngày',
    ],
    'th': [
      'ยินดีต้อนรับสู่ชุมชน BIL',
      'แบ่งปันเส้นทาง เติบโตไปด้วยกัน',
      'กำลังเตรียมชุมชนของคุณ…',
      'ยอดรวมรายวัน',
      'ยอดรวมตัวอย่างที่นำเข้า',
      'ค่าเฉลี่ยตัวอย่างที่บันทึก',
      'ค่าเฉลี่ยตัวอย่างชีพจรขณะพัก',
      'วันนี้ · ยังไม่สิ้นสุด',
      'ค่าเฉลี่ยรายวันจะแสดงหลังสิ้นสุดวัน',
      'บันทึกเกิน 100 ครั้งต่อนาที',
      'บันทึกครั้งแรก',
      'ค่าสูงสุด',
      'ชีพจรอาจสูงขึ้นระหว่างทำกิจกรรม เครื่องหมายนี้ไม่ใช่สัญญาณเตือนทางการแพทย์',
      'ยังไม่มีวันที่สิ้นสุดแล้ว',
      'ตัวอย่างที่บันทึก',
      'สรุปรายวัน',
    ],
  };
  static String text(String localeTag, String key) {
    final index = keys.indexOf(key);
    if (index < 0) throw ArgumentError.value(key, 'key');
    final canonical = BilLocalePolicy.canonicalSupportedTag(localeTag) ?? 'en';
    return (values[canonical] ?? values['en']!)[index];
  }
}

String sapphireText(BuildContext context, String key) => SapphireCopy.text(
  BilLocalePolicy.canonicalTag(Localizations.localeOf(context)),
  key,
);
