part of 'bil_workout_routines_page.dart';

String _fullscreenVideoCopy(BuildContext context, String key) {
  final tag = BilLocalePolicy.canonicalTag(Localizations.localeOf(context));
  final localized =
      _fullscreenVideoCopyByLocale[tag] ?? _fullscreenVideoCopyByLocale['en']!;
  return localized[key] ?? _fullscreenVideoCopyByLocale['en']![key] ?? key;
}

const _fullscreenVideoCopyByLocale = <String, Map<String, String>>{
  'ar': {
    'loading': 'جارٍ تحميل الفيديو',
    'buffering': 'جارٍ تحميل التشغيل',
    'retry': 'إعادة المحاولة',
    'replay': 'إعادة التشغيل',
    'speed': 'سرعة التشغيل',
    'progress': 'تقدّم الفيديو',
    'back5': 'الرجوع 5 ثوانٍ',
    'forward5': 'التقدّم 5 ثوانٍ',
    'startError': 'تعذّر تشغيل الفيديو. تحقّق من الاتصال وأعد المحاولة.',
    'stallError': 'توقّف التشغيل مؤقتًا. أعد المحاولة للمتابعة من موضعك.',
    'speedError': 'هذه السرعة غير مدعومة على هذا الجهاز.',
  },
  'en': {
    'loading': 'Loading video',
    'buffering': 'Buffering video',
    'retry': 'Retry',
    'replay': 'Replay',
    'speed': 'Playback speed',
    'progress': 'Video progress',
    'back5': 'Rewind 5 seconds',
    'forward5': 'Forward 5 seconds',
    'startError': "Video couldn't start. Check your connection and try again.",
    'stallError': 'Playback stalled. Retry to continue where you left off.',
    'speedError': "This speed isn't supported on this device.",
  },
  'fr': {
    'loading': 'Chargement de la vidéo',
    'buffering': 'Mise en mémoire tampon',
    'retry': 'Réessayer',
    'replay': 'Rejouer',
    'speed': 'Vitesse de lecture',
    'progress': 'Progression de la vidéo',
    'back5': 'Reculer de 5 secondes',
    'forward5': 'Avancer de 5 secondes',
    'startError':
        'Impossible de démarrer la vidéo. Vérifiez votre connexion et réessayez.',
    'stallError':
        'La lecture est bloquée. Réessayez pour reprendre où vous en étiez.',
    'speedError': "Cette vitesse n'est pas prise en charge sur cet appareil.",
  },
  'es': {
    'loading': 'Cargando vídeo',
    'buffering': 'Almacenando vídeo',
    'retry': 'Reintentar',
    'replay': 'Repetir',
    'speed': 'Velocidad de reproducción',
    'progress': 'Progreso del vídeo',
    'back5': 'Retroceder 5 segundos',
    'forward5': 'Avanzar 5 segundos',
    'startError':
        'No se pudo iniciar el vídeo. Comprueba tu conexión e inténtalo de nuevo.',
    'stallError':
        'La reproducción se detuvo. Reintenta para continuar donde estabas.',
    'speedError': 'Esta velocidad no es compatible con este dispositivo.',
  },
  'tr': {
    'loading': 'Video yükleniyor',
    'buffering': 'Video arabelleğe alınıyor',
    'retry': 'Tekrar dene',
    'replay': 'Yeniden oynat',
    'speed': 'Oynatma hızı',
    'progress': 'Video ilerlemesi',
    'back5': '5 saniye geri sar',
    'forward5': '5 saniye ileri sar',
    'startError':
        'Video başlatılamadı. Bağlantınızı kontrol edip tekrar deneyin.',
    'stallError':
        'Oynatma durdu. Kaldığınız yerden devam etmek için tekrar deneyin.',
    'speedError': 'Bu hız bu cihazda desteklenmiyor.',
  },
  'de': {
    'loading': 'Video wird geladen',
    'buffering': 'Video wird gepuffert',
    'retry': 'Erneut versuchen',
    'replay': 'Wiederholen',
    'speed': 'Wiedergabegeschwindigkeit',
    'progress': 'Videofortschritt',
    'back5': '5 Sekunden zurück',
    'forward5': '5 Sekunden vor',
    'startError':
        'Das Video konnte nicht gestartet werden. Prüfe deine Verbindung und versuche es erneut.',
    'stallError':
        'Die Wiedergabe stockt. Versuche es erneut, um an derselben Stelle fortzufahren.',
    'speedError':
        'Diese Geschwindigkeit wird auf diesem Gerät nicht unterstützt.',
  },
  'it': {
    'loading': 'Caricamento video',
    'buffering': 'Buffering del video',
    'retry': 'Riprova',
    'replay': 'Riproduci di nuovo',
    'speed': 'Velocità di riproduzione',
    'progress': 'Avanzamento video',
    'back5': 'Indietro di 5 secondi',
    'forward5': 'Avanti di 5 secondi',
    'startError':
        'Impossibile avviare il video. Controlla la connessione e riprova.',
    'stallError':
        'La riproduzione si è bloccata. Riprova per continuare dallo stesso punto.',
    'speedError': 'Questa velocità non è supportata su questo dispositivo.',
  },
  'pt-BR': {
    'loading': 'Carregando vídeo',
    'buffering': 'Carregando reprodução',
    'retry': 'Tentar novamente',
    'replay': 'Repetir',
    'speed': 'Velocidade de reprodução',
    'progress': 'Progresso do vídeo',
    'back5': 'Voltar 5 segundos',
    'forward5': 'Avançar 5 segundos',
    'startError':
        'Não foi possível iniciar o vídeo. Verifique a conexão e tente novamente.',
    'stallError':
        'A reprodução parou. Tente novamente para continuar de onde estava.',
    'speedError': 'Esta velocidade não é compatível com este dispositivo.',
  },
  'pt-PT': {
    'loading': 'A carregar o vídeo',
    'buffering': 'A carregar a reprodução',
    'retry': 'Tentar novamente',
    'replay': 'Repetir',
    'speed': 'Velocidade de reprodução',
    'progress': 'Progresso do vídeo',
    'back5': 'Recuar 5 segundos',
    'forward5': 'Avançar 5 segundos',
    'startError':
        'Não foi possível iniciar o vídeo. Verifique a ligação e tente novamente.',
    'stallError':
        'A reprodução parou. Tente novamente para continuar onde ficou.',
    'speedError': 'Esta velocidade não é suportada neste dispositivo.',
  },
  'ur': {
    'loading': 'ویڈیو لوڈ ہو رہی ہے',
    'buffering': 'ویڈیو بفر ہو رہی ہے',
    'retry': 'دوبارہ کوشش کریں',
    'replay': 'دوبارہ چلائیں',
    'speed': 'پلے بیک کی رفتار',
    'progress': 'ویڈیو کی پیش رفت',
    'back5': '5 سیکنڈ پیچھے',
    'forward5': '5 سیکنڈ آگے',
    'startError':
        'ویڈیو شروع نہیں ہو سکی۔ اپنا کنکشن چیک کر کے دوبارہ کوشش کریں۔',
    'stallError':
        'پلے بیک رک گیا۔ اسی جگہ سے جاری رکھنے کے لیے دوبارہ کوشش کریں۔',
    'speedError': 'یہ رفتار اس ڈیوائس پر دستیاب نہیں ہے۔',
  },
  'fa': {
    'loading': 'در حال بارگذاری ویدیو',
    'buffering': 'در حال بافر ویدیو',
    'retry': 'تلاش دوباره',
    'replay': 'پخش دوباره',
    'speed': 'سرعت پخش',
    'progress': 'پیشرفت ویدیو',
    'back5': '۵ ثانیه به عقب',
    'forward5': '۵ ثانیه به جلو',
    'startError': 'ویدیو شروع نشد. اتصال خود را بررسی کنید و دوباره تلاش کنید.',
    'stallError': 'پخش متوقف شد. برای ادامه از همان نقطه دوباره تلاش کنید.',
    'speedError': 'این سرعت در این دستگاه پشتیبانی نمی‌شود.',
  },
  'hi': {
    'loading': 'वीडियो लोड हो रहा है',
    'buffering': 'वीडियो बफ़र हो रहा है',
    'retry': 'फिर कोशिश करें',
    'replay': 'फिर से चलाएँ',
    'speed': 'चलाने की गति',
    'progress': 'वीडियो की प्रगति',
    'back5': '5 सेकंड पीछे',
    'forward5': '5 सेकंड आगे',
    'startError':
        'वीडियो शुरू नहीं हो सका। अपना कनेक्शन जाँचें और फिर कोशिश करें।',
    'stallError': 'वीडियो रुक गया। उसी जगह से जारी रखने के लिए फिर कोशिश करें।',
    'speedError': 'यह गति इस डिवाइस पर समर्थित नहीं है।',
  },
  'id': {
    'loading': 'Memuat video',
    'buffering': 'Menyangga video',
    'retry': 'Coba lagi',
    'replay': 'Putar ulang',
    'speed': 'Kecepatan pemutaran',
    'progress': 'Progres video',
    'back5': 'Mundur 5 detik',
    'forward5': 'Maju 5 detik',
    'startError': 'Video tidak dapat dimulai. Periksa koneksi lalu coba lagi.',
    'stallError':
        'Pemutaran terhenti. Coba lagi untuk melanjutkan dari posisi terakhir.',
    'speedError': 'Kecepatan ini tidak didukung di perangkat ini.',
  },
  'ms': {
    'loading': 'Memuatkan video',
    'buffering': 'Menimbal video',
    'retry': 'Cuba semula',
    'replay': 'Main semula',
    'speed': 'Kelajuan main balik',
    'progress': 'Kemajuan video',
    'back5': 'Undur 5 saat',
    'forward5': 'Maju 5 saat',
    'startError':
        'Video tidak dapat dimulakan. Semak sambungan dan cuba semula.',
    'stallError':
        'Main balik terhenti. Cuba semula untuk menyambung dari tempat terakhir.',
    'speedError': 'Kelajuan ini tidak disokong pada peranti ini.',
  },
  'ja': {
    'loading': '動画を読み込み中',
    'buffering': '動画をバッファリング中',
    'retry': '再試行',
    'replay': 'もう一度再生',
    'speed': '再生速度',
    'progress': '動画の進行状況',
    'back5': '5秒戻る',
    'forward5': '5秒進む',
    'startError': '動画を開始できませんでした。接続を確認して再試行してください。',
    'stallError': '再生が停止しました。再試行すると同じ位置から続けられます。',
    'speedError': 'このデバイスではこの速度を使用できません。',
  },
  'ko': {
    'loading': '동영상 불러오는 중',
    'buffering': '동영상 버퍼링 중',
    'retry': '다시 시도',
    'replay': '다시 재생',
    'speed': '재생 속도',
    'progress': '동영상 진행률',
    'back5': '5초 뒤로',
    'forward5': '5초 앞으로',
    'startError': '동영상을 시작할 수 없습니다. 연결을 확인하고 다시 시도하세요.',
    'stallError': '재생이 멈췄습니다. 다시 시도하면 보던 위치부터 이어집니다.',
    'speedError': '이 기기에서는 이 속도를 지원하지 않습니다.',
  },
  'zh-Hans': {
    'loading': '正在加载视频',
    'buffering': '正在缓冲视频',
    'retry': '重试',
    'replay': '重新播放',
    'speed': '播放速度',
    'progress': '视频进度',
    'back5': '后退 5 秒',
    'forward5': '前进 5 秒',
    'startError': '无法开始播放视频。请检查网络连接后重试。',
    'stallError': '播放已停滞。重试即可从上次位置继续。',
    'speedError': '此设备不支持该播放速度。',
  },
  'zh-Hant': {
    'loading': '正在載入影片',
    'buffering': '正在緩衝影片',
    'retry': '重試',
    'replay': '重新播放',
    'speed': '播放速度',
    'progress': '影片進度',
    'back5': '倒退 5 秒',
    'forward5': '前進 5 秒',
    'startError': '無法開始播放影片。請檢查網路連線後重試。',
    'stallError': '播放已停滯。重試即可從上次位置繼續。',
    'speedError': '此裝置不支援該播放速度。',
  },
  'ru': {
    'loading': 'Загрузка видео',
    'buffering': 'Буферизация видео',
    'retry': 'Повторить',
    'replay': 'Воспроизвести снова',
    'speed': 'Скорость воспроизведения',
    'progress': 'Ход видео',
    'back5': 'Назад на 5 секунд',
    'forward5': 'Вперёд на 5 секунд',
    'startError':
        'Не удалось запустить видео. Проверьте подключение и повторите попытку.',
    'stallError':
        'Воспроизведение остановилось. Повторите попытку, чтобы продолжить с того же места.',
    'speedError': 'Эта скорость не поддерживается на данном устройстве.',
  },
  'bn': {
    'loading': 'ভিডিও লোড হচ্ছে',
    'buffering': 'ভিডিও বাফার হচ্ছে',
    'retry': 'আবার চেষ্টা করুন',
    'replay': 'আবার চালান',
    'speed': 'প্লেব্যাকের গতি',
    'progress': 'ভিডিওর অগ্রগতি',
    'back5': '৫ সেকেন্ড পিছিয়ে যান',
    'forward5': '৫ সেকেন্ড এগিয়ে যান',
    'startError': 'ভিডিও শুরু করা যায়নি। সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।',
    'stallError':
        'প্লেব্যাক থেমে গেছে। একই জায়গা থেকে চালাতে আবার চেষ্টা করুন।',
    'speedError': 'এই ডিভাইসে এই গতি সমর্থিত নয়।',
  },
  'vi': {
    'loading': 'Đang tải video',
    'buffering': 'Đang tải bộ đệm video',
    'retry': 'Thử lại',
    'replay': 'Phát lại',
    'speed': 'Tốc độ phát',
    'progress': 'Tiến trình video',
    'back5': 'Lùi 5 giây',
    'forward5': 'Tiến 5 giây',
    'startError': 'Không thể bắt đầu video. Hãy kiểm tra kết nối rồi thử lại.',
    'stallError': 'Video đã dừng. Hãy thử lại để tiếp tục từ vị trí trước đó.',
    'speedError': 'Thiết bị này không hỗ trợ tốc độ này.',
  },
  'th': {
    'loading': 'กำลังโหลดวิดีโอ',
    'buffering': 'กำลังบัฟเฟอร์วิดีโอ',
    'retry': 'ลองอีกครั้ง',
    'replay': 'เล่นอีกครั้ง',
    'speed': 'ความเร็วในการเล่น',
    'progress': 'ความคืบหน้าของวิดีโอ',
    'back5': 'ย้อนกลับ 5 วินาที',
    'forward5': 'เดินหน้า 5 วินาที',
    'startError':
        'ไม่สามารถเริ่มวิดีโอได้ โปรดตรวจสอบการเชื่อมต่อแล้วลองอีกครั้ง',
    'stallError': 'การเล่นหยุดชะงัก ลองอีกครั้งเพื่อเล่นต่อจากตำแหน่งเดิม',
    'speedError': 'อุปกรณ์นี้ไม่รองรับความเร็วนี้',
  },
  'pl': {
    'loading': 'Ładowanie filmu',
    'buffering': 'Buforowanie filmu',
    'retry': 'Spróbuj ponownie',
    'replay': 'Odtwórz ponownie',
    'speed': 'Szybkość odtwarzania',
    'progress': 'Postęp filmu',
    'back5': 'Cofnij o 5 sekund',
    'forward5': 'Przewiń o 5 sekund',
    'startError':
        'Nie udało się uruchomić filmu. Sprawdź połączenie i spróbuj ponownie.',
    'stallError':
        'Odtwarzanie zatrzymało się. Spróbuj ponownie, aby kontynuować od tego samego miejsca.',
    'speedError': 'Ta szybkość nie jest obsługiwana na tym urządzeniu.',
  },
  'nl': {
    'loading': 'Video laden',
    'buffering': 'Video bufferen',
    'retry': 'Opnieuw proberen',
    'replay': 'Opnieuw afspelen',
    'speed': 'Afspeelsnelheid',
    'progress': 'Videovoortgang',
    'back5': '5 seconden terug',
    'forward5': '5 seconden vooruit',
    'startError':
        'De video kon niet starten. Controleer je verbinding en probeer het opnieuw.',
    'stallError':
        'Het afspelen is vastgelopen. Probeer opnieuw om verder te gaan waar je was.',
    'speedError': 'Deze snelheid wordt niet ondersteund op dit apparaat.',
  },
  'uk': {
    'loading': 'Завантаження відео',
    'buffering': 'Буферизація відео',
    'retry': 'Повторити',
    'replay': 'Відтворити знову',
    'speed': 'Швидкість відтворення',
    'progress': 'Перебіг відео',
    'back5': 'Назад на 5 секунд',
    'forward5': 'Вперед на 5 секунд',
    'startError':
        'Не вдалося запустити відео. Перевірте з’єднання та повторіть спробу.',
    'stallError':
        'Відтворення зупинилося. Повторіть спробу, щоб продовжити з того самого місця.',
    'speedError': 'Ця швидкість не підтримується на цьому пристрої.',
  },
};
