import 'package:flutter/widgets.dart';

import '../../../app/localization/bil_locale_policy.dart';

part 'workout_routines_state_copy.dart';
part 'workout_video_session_copy.dart';

const workoutVideoGroupIds = <String>[
  'gym-push',
  'gym-pull',
  'gym-legs',
  'gym-warm-up-mobility',
  'gym-full-body',
  'gym-upper-lower',
  'gym-muscle-pair-split',
  'gym-arnold-split',
  'gym-powerbuilding',
  'gym-exercise-technique',
  'home-resistance-upper-body',
  'home-resistance-lower-body',
  'home-resistance-full-body',
  'home-cardio-conditioning',
  'home-cardio-low-impact',
  'home-home-bodyweight',
  'home-core-stability',
  'home-mobility-flexibility',
  'home-recovery-beginner',
  'home-balance-coordination',
];

/// Canonical groups for legacy routines created before discovery packs began
/// persisting stable group IDs. Unknown values still fail closed below.
const _legacyWorkoutVideoGroupAliases = <String, String>{
  'Strength': 'gym-powerbuilding',
  'Cardio': 'home-cardio-conditioning',
  'Recovery': 'home-recovery-beginner',
};

String workoutVideoGroupTitle(BuildContext context, String groupId) {
  return workoutVideoGroupTitleForTag(
    BilLocalePolicy.canonicalTag(Localizations.localeOf(context)),
    groupId,
  );
}

/// Returns a reviewed group label without requiring a widget context.
///
/// Discovery metadata uses this strict entry point so missing copy fails
/// closed instead of exposing an internal group identifier.
String workoutVideoGroupTitleForTag(String localeTag, String groupId) {
  final canonicalGroupId = _legacyWorkoutVideoGroupAliases[groupId] ?? groupId;
  final index = workoutVideoGroupIds.indexOf(canonicalGroupId);
  if (index < 0) {
    throw FormatException('Unknown workout video group: $groupId.');
  }
  final tag = BilLocalePolicy.canonicalSupportedTag(localeTag);
  if (tag == null) {
    throw FormatException('Unsupported workout video locale: $localeTag.');
  }
  final labels = _groupLabels[tag];
  if (labels == null) {
    throw StateError('Missing workout video group copy for $tag.');
  }
  if (labels.length != workoutVideoGroupIds.length) {
    throw StateError('Workout video group locale matrix is incomplete.');
  }
  return labels[index];
}

String workoutVideoSessionName(BuildContext context, String sessionId) {
  final parts = sessionId.split('-');
  final type = parts.first;
  final index = workoutVideoSessionTypes.indexOf(type);
  if (index < 0) return sessionId;
  final tag = BilLocalePolicy.canonicalTag(Localizations.localeOf(context));
  final labels = _sessionLabels[tag] ?? _sessionLabels['en']!;
  if (labels.length != workoutVideoSessionTypes.length) {
    throw StateError('Workout video session locale matrix is incomplete.');
  }
  final variant = parts.length > 1 ? parts.last.toUpperCase() : '';
  return '${labels[index]} $variant'.trim();
}

String workoutVideoMonthTitle(BuildContext context, int month) {
  final tag = BilLocalePolicy.canonicalTag(Localizations.localeOf(context));
  final pattern = _monthTitlePatterns[tag] ?? _monthTitlePatterns['en']!;
  return pattern.replaceFirst('{month}', '$month');
}

String workoutVideoPhaseTitle(BuildContext context, int phase) {
  final tag = BilLocalePolicy.canonicalTag(Localizations.localeOf(context));
  final pattern = _phaseTitlePatterns[tag] ?? _phaseTitlePatterns['en']!;
  return pattern.replaceFirst('{phase}', '$phase');
}

String workoutVerifiedMovementCount(BuildContext context, int count) {
  final tag = BilLocalePolicy.canonicalTag(Localizations.localeOf(context));
  final pattern =
      _verifiedMovementPatterns[tag] ?? _verifiedMovementPatterns['en']!;
  return pattern.replaceFirst('{count}', '$count');
}

const _groupLabels = <String, List<String>>{
  'en': [
    'Push',
    'Pull',
    'Legs',
    'Warm-up & mobility',
    'Full body',
    'Upper / Lower',
    'Muscle pair split',
    'Arnold split',
    'Strength + hypertrophy',
    'Exercise technique',
    'Upper-body strength',
    'Lower-body strength',
    'Full-body strength',
    'Cardio conditioning',
    'Low-impact cardio',
    'Home bodyweight',
    'Core stability',
    'Mobility & flexibility',
    'Beginner recovery',
    'Balance & coordination',
  ],
  'ar': [
    'الدفع',
    'السحب',
    'الأرجل',
    'الإحماء والحركة',
    'كامل الجسم',
    'علوي / سفلي',
    'تقسيم أزواج العضلات',
    'تقسيم أرنولد',
    'القوة والتضخيم',
    'تقنية التمرين',
    'قوة الجزء العلوي',
    'قوة الجزء السفلي',
    'قوة كامل الجسم',
    'تمارين اللياقة القلبية',
    'كارديو منخفض التأثير',
    'تمارين منزلية بوزن الجسم',
    'ثبات الجذع',
    'الحركة والمرونة',
    'تعافٍ للمبتدئين',
    'التوازن والتناسق',
  ],
  'fr': [
    'Poussée',
    'Tirage',
    'Jambes',
    'Échauffement et mobilité',
    'Corps entier',
    'Haut / Bas',
    'Répartition par paires musculaires',
    'Split Arnold',
    'Force et hypertrophie',
    'Technique d’exercice',
    'Force du haut du corps',
    'Force du bas du corps',
    'Force du corps entier',
    'Conditionnement cardio',
    'Cardio à faible impact',
    'Poids du corps à domicile',
    'Stabilité du tronc',
    'Mobilité et souplesse',
    'Récupération débutant',
    'Équilibre et coordination',
  ],
  'es': [
    'Empuje',
    'Tirón',
    'Piernas',
    'Calentamiento y movilidad',
    'Cuerpo completo',
    'Superior / Inferior',
    'División por pares musculares',
    'Rutina Arnold',
    'Fuerza e hipertrofia',
    'Técnica de ejercicio',
    'Fuerza del tren superior',
    'Fuerza del tren inferior',
    'Fuerza de cuerpo completo',
    'Acondicionamiento cardiovascular',
    'Cardio de bajo impacto',
    'Peso corporal en casa',
    'Estabilidad del core',
    'Movilidad y flexibilidad',
    'Recuperación para principiantes',
    'Equilibrio y coordinación',
  ],
  'tr': [
    'İtiş',
    'Çekiş',
    'Bacak',
    'Isınma ve hareketlilik',
    'Tüm vücut',
    'Üst / Alt',
    'Kas çifti bölümü',
    'Arnold bölümü',
    'Güç ve hipertrofi',
    'Egzersiz tekniği',
    'Üst vücut kuvveti',
    'Alt vücut kuvveti',
    'Tüm vücut kuvveti',
    'Kardiyo kondisyonu',
    'Düşük etkili kardiyo',
    'Evde vücut ağırlığı',
    'Merkez bölge dengesi',
    'Hareketlilik ve esneklik',
    'Başlangıç toparlanması',
    'Denge ve koordinasyon',
  ],
  'de': [
    'Drücken',
    'Ziehen',
    'Beine',
    'Aufwärmen & Mobilität',
    'Ganzkörper',
    'Oberkörper / Unterkörper',
    'Muskelpaar-Split',
    'Arnold-Split',
    'Kraft & Hypertrophie',
    'Übungstechnik',
    'Oberkörperkraft',
    'Unterkörperkraft',
    'Ganzkörperkraft',
    'Cardio-Kondition',
    'Gelenkschonendes Cardio',
    'Körpergewicht zu Hause',
    'Rumpfstabilität',
    'Mobilität & Flexibilität',
    'Erholung für Einsteiger',
    'Gleichgewicht & Koordination',
  ],
  'it': [
    'Spinta',
    'Trazione',
    'Gambe',
    'Riscaldamento e mobilità',
    'Corpo intero',
    'Parte superiore / inferiore',
    'Split per coppie muscolari',
    'Split Arnold',
    'Forza e ipertrofia',
    'Tecnica degli esercizi',
    'Forza parte superiore',
    'Forza parte inferiore',
    'Forza corpo intero',
    'Condizionamento cardio',
    'Cardio a basso impatto',
    'Corpo libero a casa',
    'Stabilità del core',
    'Mobilità e flessibilità',
    'Recupero principianti',
    'Equilibrio e coordinazione',
  ],
  'pt-BR': [
    'Empurrar',
    'Puxar',
    'Pernas',
    'Aquecimento e mobilidade',
    'Corpo inteiro',
    'Superior / Inferior',
    'Divisão por pares musculares',
    'Divisão Arnold',
    'Força e hipertrofia',
    'Técnica de exercício',
    'Força da parte superior',
    'Força da parte inferior',
    'Força de corpo inteiro',
    'Condicionamento cardiovascular',
    'Cardio de baixo impacto',
    'Peso corporal em casa',
    'Estabilidade do core',
    'Mobilidade e flexibilidade',
    'Recuperação para iniciantes',
    'Equilíbrio e coordenação',
  ],
  'pt-PT': [
    'Empurrar',
    'Puxar',
    'Pernas',
    'Aquecimento e mobilidade',
    'Corpo inteiro',
    'Superior / Inferior',
    'Divisão por pares musculares',
    'Divisão Arnold',
    'Força e hipertrofia',
    'Técnica de exercício',
    'Força da parte superior',
    'Força da parte inferior',
    'Força de corpo inteiro',
    'Condicionamento cardiovascular',
    'Cardio de baixo impacto',
    'Peso corporal em casa',
    'Estabilidade do tronco',
    'Mobilidade e flexibilidade',
    'Recuperação para iniciantes',
    'Equilíbrio e coordenação',
  ],
  'ur': [
    'دھکیلنا',
    'کھینچنا',
    'ٹانگیں',
    'وارم اپ اور حرکت',
    'پورا جسم',
    'اوپری / نچلا جسم',
    'عضلاتی جوڑی کی تقسیم',
    'آرنلڈ تقسیم',
    'طاقت اور عضلاتی اضافہ',
    'ورزش کی تکنیک',
    'اوپری جسم کی طاقت',
    'نچلے جسم کی طاقت',
    'پورے جسم کی طاقت',
    'کارڈیو کنڈیشننگ',
    'کم اثر والا کارڈیو',
    'گھر پر جسمانی وزن',
    'مرکزی استحکام',
    'حرکت اور لچک',
    'ابتدائی بحالی',
    'توازن اور ہم آہنگی',
  ],
  'fa': [
    'فشار',
    'کشش',
    'پاها',
    'گرم‌کردن و تحرک',
    'تمام بدن',
    'بالاتنه / پایین‌تنه',
    'تقسیم جفت عضلانی',
    'تقسیم آرنولد',
    'قدرت و هایپرتروفی',
    'تکنیک تمرین',
    'قدرت بالاتنه',
    'قدرت پایین‌تنه',
    'قدرت تمام بدن',
    'آمادگی هوازی',
    'کاردیوی کم‌فشار',
    'وزن بدن در خانه',
    'پایداری مرکزی',
    'تحرک و انعطاف‌پذیری',
    'ریکاوری مبتدی',
    'تعادل و هماهنگی',
  ],
  'hi': [
    'पुश',
    'पुल',
    'पैर',
    'वार्म-अप और गतिशीलता',
    'पूरा शरीर',
    'ऊपरी / निचला',
    'मांसपेशी जोड़ी विभाजन',
    'आर्नोल्ड विभाजन',
    'शक्ति और मांसपेशी वृद्धि',
    'व्यायाम तकनीक',
    'ऊपरी शरीर की शक्ति',
    'निचले शरीर की शक्ति',
    'पूरे शरीर की शक्ति',
    'कार्डियो कंडीशनिंग',
    'कम प्रभाव वाला कार्डियो',
    'घर पर बॉडीवेट',
    'कोर स्थिरता',
    'गतिशीलता और लचीलापन',
    'शुरुआती रिकवरी',
    'संतुलन और समन्वय',
  ],
  'id': [
    'Dorong',
    'Tarik',
    'Kaki',
    'Pemanasan & mobilitas',
    'Seluruh tubuh',
    'Tubuh atas / bawah',
    'Split pasangan otot',
    'Split Arnold',
    'Kekuatan & hipertrofi',
    'Teknik latihan',
    'Kekuatan tubuh atas',
    'Kekuatan tubuh bawah',
    'Kekuatan seluruh tubuh',
    'Kondisi kardio',
    'Kardio benturan rendah',
    'Beban tubuh di rumah',
    'Stabilitas inti',
    'Mobilitas & fleksibilitas',
    'Pemulihan pemula',
    'Keseimbangan & koordinasi',
  ],
  'ms': [
    'Tolakan',
    'Tarikan',
    'Kaki',
    'Pemanasan & mobiliti',
    'Seluruh badan',
    'Badan atas / bawah',
    'Pecahan pasangan otot',
    'Pecahan Arnold',
    'Kekuatan & hipertrofi',
    'Teknik senaman',
    'Kekuatan badan atas',
    'Kekuatan badan bawah',
    'Kekuatan seluruh badan',
    'Kondisi kardio',
    'Kardio impak rendah',
    'Berat badan di rumah',
    'Kestabilan teras',
    'Mobiliti & fleksibiliti',
    'Pemulihan pemula',
    'Keseimbangan & koordinasi',
  ],
  'ja': [
    'プッシュ',
    'プル',
    '脚',
    'ウォームアップと可動性',
    '全身',
    '上半身 / 下半身',
    '筋群ペア分割',
    'アーノルド分割',
    '筋力と筋肥大',
    'エクササイズ技術',
    '上半身の筋力',
    '下半身の筋力',
    '全身の筋力',
    '有酸素コンディショニング',
    '低負荷カーディオ',
    '自宅自重トレーニング',
    '体幹の安定性',
    '可動性と柔軟性',
    '初心者向け回復',
    'バランスと協調性',
  ],
  'ko': [
    '밀기',
    '당기기',
    '하체',
    '워밍업 및 가동성',
    '전신',
    '상체 / 하체',
    '근육 쌍 분할',
    '아놀드 분할',
    '근력 및 근비대',
    '운동 기술',
    '상체 근력',
    '하체 근력',
    '전신 근력',
    '유산소 컨디셔닝',
    '저충격 유산소',
    '홈 맨몸 운동',
    '코어 안정성',
    '가동성 및 유연성',
    '초보자 회복',
    '균형 및 협응',
  ],
  'zh-Hans': [
    '推',
    '拉',
    '腿部',
    '热身与灵活性',
    '全身',
    '上肢 / 下肢',
    '肌群搭配分化',
    '阿诺德分化',
    '力量与肌肥大',
    '动作技术',
    '上肢力量',
    '下肢力量',
    '全身力量',
    '心肺训练',
    '低冲击有氧',
    '居家自重训练',
    '核心稳定',
    '灵活性与柔韧性',
    '新手恢复',
    '平衡与协调',
  ],
  'zh-Hant': [
    '推',
    '拉',
    '腿部',
    '熱身與活動度',
    '全身',
    '上肢 / 下肢',
    '肌群搭配分化',
    '阿諾德分化',
    '力量與肌肥大',
    '動作技術',
    '上肢力量',
    '下肢力量',
    '全身力量',
    '心肺訓練',
    '低衝擊有氧',
    '居家自重訓練',
    '核心穩定',
    '活動度與柔韌性',
    '新手恢復',
    '平衡與協調',
  ],
  'ru': [
    'Жим',
    'Тяга',
    'Ноги',
    'Разминка и подвижность',
    'Всё тело',
    'Верх / Низ',
    'Сплит пар мышц',
    'Сплит Арнольда',
    'Сила и гипертрофия',
    'Техника упражнений',
    'Сила верхней части тела',
    'Сила нижней части тела',
    'Сила всего тела',
    'Кардиоподготовка',
    'Низкоударное кардио',
    'Вес тела дома',
    'Стабильность корпуса',
    'Подвижность и гибкость',
    'Восстановление для начинающих',
    'Баланс и координация',
  ],
  'bn': [
    'পুশ',
    'পুল',
    'পা',
    'ওয়ার্ম-আপ ও গতিশীলতা',
    'সম্পূর্ণ শরীর',
    'উপরের / নিচের অংশ',
    'পেশি-জোড়া বিভাজন',
    'আর্নল্ড বিভাজন',
    'শক্তি ও পেশি বৃদ্ধি',
    'ব্যায়াম কৌশল',
    'উপরের শরীরের শক্তি',
    'নিচের শরীরের শক্তি',
    'সম্পূর্ণ শরীরের শক্তি',
    'কার্ডিও কন্ডিশনিং',
    'কম-প্রভাব কার্ডিও',
    'বাড়িতে বডিওয়েট',
    'কোর স্থিতিশীলতা',
    'গতিশীলতা ও নমনীয়তা',
    'শুরুর পুনরুদ্ধার',
    'ভারসাম্য ও সমন্বয়',
  ],
  'vi': [
    'Đẩy',
    'Kéo',
    'Chân',
    'Khởi động & linh hoạt',
    'Toàn thân',
    'Thân trên / thân dưới',
    'Chia cặp nhóm cơ',
    'Lịch Arnold',
    'Sức mạnh & phì đại cơ',
    'Kỹ thuật bài tập',
    'Sức mạnh thân trên',
    'Sức mạnh thân dưới',
    'Sức mạnh toàn thân',
    'Thể lực tim mạch',
    'Cardio ít tác động',
    'Tập trọng lượng cơ thể tại nhà',
    'Ổn định vùng lõi',
    'Linh hoạt & dẻo dai',
    'Phục hồi cho người mới',
    'Thăng bằng & phối hợp',
  ],
  'th': [
    'ท่าดัน',
    'ท่าดึง',
    'ขา',
    'วอร์มอัปและการเคลื่อนไหว',
    'ทั่วร่างกาย',
    'ช่วงบน / ช่วงล่าง',
    'แบ่งคู่กล้ามเนื้อ',
    'แบ่งแบบอาร์โนลด์',
    'ความแข็งแรงและเพิ่มกล้าม',
    'เทคนิคการออกกำลังกาย',
    'ความแข็งแรงช่วงบน',
    'ความแข็งแรงช่วงล่าง',
    'ความแข็งแรงทั่วร่างกาย',
    'ความฟิตคาร์ดิโอ',
    'คาร์ดิโอแรงกระแทกต่ำ',
    'บอดี้เวตที่บ้าน',
    'ความมั่นคงแกนกลาง',
    'การเคลื่อนไหวและความยืดหยุ่น',
    'ฟื้นฟูสำหรับผู้เริ่มต้น',
    'สมดุลและการประสานงาน',
  ],
  'pl': [
    'Wypychanie',
    'Przyciąganie',
    'Nogi',
    'Rozgrzewka i mobilność',
    'Całe ciało',
    'Góra / Dół',
    'Split par mięśniowych',
    'Split Arnolda',
    'Siła i hipertrofia',
    'Technika ćwiczeń',
    'Siła górnej części ciała',
    'Siła dolnej części ciała',
    'Siła całego ciała',
    'Kondycja kardio',
    'Kardio o niskim obciążeniu',
    'Masa ciała w domu',
    'Stabilność tułowia',
    'Mobilność i elastyczność',
    'Regeneracja dla początkujących',
    'Równowaga i koordynacja',
  ],
  'nl': [
    'Duwen',
    'Trekken',
    'Benen',
    'Warming-up & mobiliteit',
    'Hele lichaam',
    'Boven / Onder',
    'Spierpaar-split',
    'Arnold-split',
    'Kracht & hypertrofie',
    'Oefentechniek',
    'Kracht bovenlichaam',
    'Kracht onderlichaam',
    'Kracht hele lichaam',
    'Cardioconditie',
    'Low-impact cardio',
    'Lichaamsgewicht thuis',
    'Corestabiliteit',
    'Mobiliteit & flexibiliteit',
    'Herstel voor beginners',
    'Balans & coördinatie',
  ],
  'uk': [
    'Жим',
    'Тяга',
    'Ноги',
    'Розминка й рухливість',
    'Усе тіло',
    'Верх / Низ',
    'Спліт пар м’язів',
    'Спліт Арнольда',
    'Сила й гіпертрофія',
    'Техніка вправ',
    'Сила верхньої частини тіла',
    'Сила нижньої частини тіла',
    'Сила всього тіла',
    'Кардіопідготовка',
    'Низькоударне кардіо',
    'Вага тіла вдома',
    'Стабільність корпусу',
    'Рухливість і гнучкість',
    'Відновлення для початківців',
    'Баланс і координація',
  ],
};
