part of 'workout_video_group_copy.dart';

const workoutVideoSessionTypes = <String>['push', 'pull', 'legs'];

const _monthTitlePatterns = <String, String>{
  'en': 'Month {month}',
  'ar': 'الشهر {month}',
  'fr': 'Mois {month}',
  'es': 'Mes {month}',
  'tr': '{month}. ay',
  'de': 'Monat {month}',
  'it': 'Mese {month}',
  'pt-BR': 'Mês {month}',
  'pt-PT': 'Mês {month}',
  'ur': 'مہینہ {month}',
  'fa': 'ماه {month}',
  'hi': 'महीना {month}',
  'id': 'Bulan {month}',
  'ms': 'Bulan {month}',
  'ja': '{month}か月目',
  'ko': '{month}개월차',
  'zh-Hans': '第 {month} 个月',
  'zh-Hant': '第 {month} 個月',
  'ru': 'Месяц {month}',
  'bn': 'মাস {month}',
  'vi': 'Tháng {month}',
  'th': 'เดือน {month}',
  'pl': 'Miesiąc {month}',
  'nl': 'Maand {month}',
  'uk': 'Місяць {month}',
};

const _phaseTitlePatterns = <String, String>{
  'en': 'Phase {phase}',
  'ar': 'المرحلة {phase}',
  'fr': 'Phase {phase}',
  'es': 'Fase {phase}',
  'tr': '{phase}. aşama',
  'de': 'Phase {phase}',
  'it': 'Fase {phase}',
  'pt-BR': 'Fase {phase}',
  'pt-PT': 'Fase {phase}',
  'ur': 'مرحلہ {phase}',
  'fa': 'مرحله {phase}',
  'hi': 'चरण {phase}',
  'id': 'Fase {phase}',
  'ms': 'Fasa {phase}',
  'ja': 'フェーズ {phase}',
  'ko': '{phase}단계',
  'zh-Hans': '第 {phase} 阶段',
  'zh-Hant': '第 {phase} 階段',
  'ru': 'Этап {phase}',
  'bn': 'পর্যায় {phase}',
  'vi': 'Giai đoạn {phase}',
  'th': 'ระยะ {phase}',
  'pl': 'Etap {phase}',
  'nl': 'Fase {phase}',
  'uk': 'Етап {phase}',
};

const _verifiedMovementPatterns = <String, String>{
  'en': '{count} verified movements',
  'ar': '{count} حركة موثقة',
  'fr': '{count} mouvements vérifiés',
  'es': '{count} movimientos verificados',
  'tr': '{count} doğrulanmış hareket',
  'de': '{count} geprüfte Bewegungen',
  'it': '{count} movimenti verificati',
  'pt-BR': '{count} movimentos verificados',
  'pt-PT': '{count} movimentos verificados',
  'ur': '{count} تصدیق شدہ حرکات',
  'fa': '{count} حرکت تأییدشده',
  'hi': '{count} सत्यापित मूवमेंट',
  'id': '{count} gerakan terverifikasi',
  'ms': '{count} pergerakan disahkan',
  'ja': '検証済み動作 {count} 件',
  'ko': '검증된 동작 {count}개',
  'zh-Hans': '{count} 个已验证动作',
  'zh-Hant': '{count} 個已驗證動作',
  'ru': '{count} проверенных движений',
  'bn': '{count}টি যাচাইকৃত মুভমেন্ট',
  'vi': '{count} động tác đã xác minh',
  'th': '{count} ท่าที่ผ่านการตรวจสอบ',
  'pl': '{count} zweryfikowanych ruchów',
  'nl': '{count} geverifieerde bewegingen',
  'uk': '{count} перевірених рухів',
};

const _sessionLabels = <String, List<String>>{
  'en': ['Push', 'Pull', 'Legs'],
  'ar': ['دفع', 'سحب', 'أرجل'],
  'fr': ['Poussée', 'Tirage', 'Jambes'],
  'es': ['Empuje', 'Tirón', 'Piernas'],
  'tr': ['İtiş', 'Çekiş', 'Bacaklar'],
  'de': ['Drücken', 'Ziehen', 'Beine'],
  'it': ['Spinta', 'Trazione', 'Gambe'],
  'pt-BR': ['Empurrar', 'Puxar', 'Pernas'],
  'pt-PT': ['Empurrar', 'Puxar', 'Pernas'],
  'ur': ['دھکیلنا', 'کھینچنا', 'ٹانگیں'],
  'fa': ['فشار', 'کشش', 'پاها'],
  'hi': ['पुश', 'पुल', 'पैर'],
  'id': ['Dorong', 'Tarik', 'Kaki'],
  'ms': ['Tolak', 'Tarik', 'Kaki'],
  'ja': ['プッシュ', 'プル', '脚'],
  'ko': ['밀기', '당기기', '하체'],
  'zh-Hans': ['推', '拉', '腿'],
  'zh-Hant': ['推', '拉', '腿'],
  'ru': ['Жим', 'Тяга', 'Ноги'],
  'bn': ['ধাক্কা', 'টান', 'পা'],
  'vi': ['Đẩy', 'Kéo', 'Chân'],
  'th': ['ดัน', 'ดึง', 'ขา'],
  'pl': ['Wypychanie', 'Przyciąganie', 'Nogi'],
  'nl': ['Duwen', 'Trekken', 'Benen'],
  'uk': ['Жим', 'Тяга', 'Ноги'],
};
