-- BIL Gold v1 foundation.
-- The append-only ledger is the authority. bil_gold_accounts is only an
-- atomically maintained projection for bounded balance reads.
set local lock_timeout='5s';
set local statement_timeout='30s';

do $$
begin
  if to_regclass('public.bil_gold_accounts') is not null
     or to_regclass('public.bil_gold_ledger') is not null then
    raise exception 'bil_gold_v1_already_exists';
  end if;
end
$$;

create table public.bil_gold_accounts (
  owner_id uuid primary key references auth.users(id) on delete cascade,
  balance bigint not null default 0 check (balance >= 0),
  updated_at timestamptz not null default pg_catalog.clock_timestamp()
);

create table public.bil_gold_ledger (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  delta bigint not null check (delta <> 0 and abs(delta) <= 1000000000),
  balance_after bigint not null check (balance_after >= 0),
  source_kind text not null
    check (source_kind ~ '^[a-z][a-z0-9_]{2,47}$'),
  idempotency_key text not null
    check (char_length(idempotency_key) between 16 and 160),
  request_digest text not null
    check (request_digest ~ '^[0-9a-f]{64}$'),
  copy_key text not null
    check (copy_key ~ '^[a-z][a-z0-9_]{2,63}$'),
  reference_kind text
    check (reference_kind is null or reference_kind ~ '^[a-z][a-z0-9_]{2,47}$'),
  reference_id text
    check (reference_id is null or char_length(reference_id) between 1 and 160),
  reverses_entry_id bigint
    references public.bil_gold_ledger(id) on delete set null,
  created_at timestamptz not null default pg_catalog.clock_timestamp(),
  constraint bil_gold_ledger_owner_idempotency_key
    unique(owner_id,idempotency_key),
  constraint bil_gold_ledger_reference_pair
    check ((reference_kind is null) = (reference_id is null)),
  constraint bil_gold_ledger_reversal_semantics
    check (
      (source_kind='reversal' and reverses_entry_id is not null)
      or (source_kind<>'reversal' and reverses_entry_id is null)
    )
);

create unique index bil_gold_ledger_single_reversal_idx
  on public.bil_gold_ledger(reverses_entry_id)
  where reverses_entry_id is not null;

create index bil_gold_ledger_owner_history_idx
  on public.bil_gold_ledger(owner_id,created_at desc,id desc);

alter table public.bil_gold_accounts enable row level security;
alter table public.bil_gold_ledger enable row level security;

revoke all on table public.bil_gold_accounts
  from public,anon,authenticated,service_role;
revoke all on table public.bil_gold_ledger
  from public,anon,authenticated,service_role;

create or replace function private.bil_post_gold_ledger_v1(
  p_owner uuid,
  p_delta bigint,
  p_source_kind text,
  p_idempotency_key text,
  p_copy_key text,
  p_reference_kind text default null,
  p_reference_id text default null,
  p_reverses_entry_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_digest text;
  v_existing public.bil_gold_ledger%rowtype;
  v_original public.bil_gold_ledger%rowtype;
  v_balance bigint;
  v_new_balance bigint;
  v_entry_id bigint;
begin
  if p_owner is null or not exists(
    select 1 from auth.users u where u.id=p_owner
  ) then
    raise exception 'gold_owner_invalid' using errcode='22023';
  end if;
  if p_delta is null or p_delta=0 or abs(p_delta)>1000000000 then
    raise exception 'gold_delta_invalid' using errcode='22023';
  end if;
  if p_source_kind is null
     or p_source_kind !~ '^[a-z][a-z0-9_]{2,47}$' then
    raise exception 'gold_source_kind_invalid' using errcode='22023';
  end if;
  if p_idempotency_key is null
     or char_length(p_idempotency_key) not between 16 and 160 then
    raise exception 'gold_idempotency_key_invalid' using errcode='22023';
  end if;
  if p_copy_key is null
     or p_copy_key !~ '^[a-z][a-z0-9_]{2,63}$' then
    raise exception 'gold_copy_key_invalid' using errcode='22023';
  end if;
  if (p_reference_kind is null) <> (p_reference_id is null) then
    raise exception 'gold_reference_pair_invalid' using errcode='22023';
  end if;
  if p_reference_kind is not null
     and p_reference_kind !~ '^[a-z][a-z0-9_]{2,47}$' then
    raise exception 'gold_reference_kind_invalid' using errcode='22023';
  end if;
  if p_reference_id is not null
     and char_length(p_reference_id) not between 1 and 160 then
    raise exception 'gold_reference_id_invalid' using errcode='22023';
  end if;
  if (p_source_kind='reversal') <> (p_reverses_entry_id is not null) then
    raise exception 'gold_reversal_semantics_invalid' using errcode='22023';
  end if;

  v_digest := encode(
    extensions.digest(
      pg_catalog.jsonb_build_object(
        'owner',p_owner::text,
        'delta',p_delta,
        'source_kind',p_source_kind,
        'copy_key',p_copy_key,
        'reference_kind',p_reference_kind,
        'reference_id',p_reference_id,
        'reverses_entry_id',p_reverses_entry_id
      )::text,
      'sha256'
    ),
    'hex'
  );

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('bil_gold:'||p_owner::text,0)
  );

  select * into v_existing
  from public.bil_gold_ledger l
  where l.owner_id=p_owner
    and l.idempotency_key=p_idempotency_key;

  if found then
    if v_existing.request_digest<>v_digest then
      raise exception 'gold_idempotency_payload_mismatch'
        using errcode='22023';
    end if;
    return pg_catalog.jsonb_build_object(
      'entry_id',v_existing.id,
      'balance',v_existing.balance_after,
      'delta',v_existing.delta,
      'duplicate',true
    );
  end if;

  if p_reverses_entry_id is not null then
    select * into v_original
    from public.bil_gold_ledger l
    where l.id=p_reverses_entry_id
      and l.owner_id=p_owner
    for share;

    if not found then
      raise exception 'gold_reversal_target_invalid' using errcode='22023';
    end if;
    if p_delta<>-v_original.delta then
      raise exception 'gold_reversal_delta_invalid' using errcode='22023';
    end if;
    if exists(
      select 1
      from public.bil_gold_ledger l
      where l.reverses_entry_id=p_reverses_entry_id
    ) then
      raise exception 'gold_entry_already_reversed' using errcode='23505';
    end if;
  end if;

  insert into public.bil_gold_accounts(owner_id,balance)
  values(p_owner,0)
  on conflict(owner_id) do nothing;

  select a.balance into v_balance
  from public.bil_gold_accounts a
  where a.owner_id=p_owner
  for update;

  v_new_balance := v_balance+p_delta;
  if v_new_balance<0 then
    raise exception 'gold_insufficient_balance' using errcode='22003';
  end if;

  insert into public.bil_gold_ledger(
    owner_id,delta,balance_after,source_kind,idempotency_key,
    request_digest,copy_key,reference_kind,reference_id,reverses_entry_id
  )
  values(
    p_owner,p_delta,v_new_balance,p_source_kind,p_idempotency_key,
    v_digest,p_copy_key,p_reference_kind,p_reference_id,p_reverses_entry_id
  )
  returning id into v_entry_id;

  update public.bil_gold_accounts
  set balance=v_new_balance,
      updated_at=pg_catalog.clock_timestamp()
  where owner_id=p_owner;

  return pg_catalog.jsonb_build_object(
    'entry_id',v_entry_id,
    'balance',v_new_balance,
    'delta',p_delta,
    'duplicate',false
  );
end
$$;

revoke all on function private.bil_post_gold_ledger_v1(
  uuid,bigint,text,text,text,text,text,bigint
) from public,anon,authenticated,service_role;

create or replace function public.bil_gold_balance_v1()
returns jsonb
language plpgsql
stable
security definer
set search_path=''
as $$
declare
  v_owner uuid:=(select auth.uid());
  v_balance bigint;
  v_updated_at timestamptz;
begin
  if v_owner is null then
    raise exception 'authentication_required' using errcode='42501';
  end if;
  select a.balance,a.updated_at into v_balance,v_updated_at
  from public.bil_gold_accounts a
  where a.owner_id=v_owner;
  return pg_catalog.jsonb_build_object(
    'balance',coalesce(v_balance,0),
    'updated_at',v_updated_at
  );
end
$$;

create or replace function public.bil_gold_history_v1(
  p_before_created_at timestamptz default null,
  p_before_id bigint default null,
  p_limit integer default 30
)
returns table(
  id bigint,
  delta bigint,
  balance_after bigint,
  source_kind text,
  copy_key text,
  reference_kind text,
  reference_id text,
  reverses_entry_id bigint,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path=''
as $$
declare
  v_owner uuid:=(select auth.uid());
begin
  if v_owner is null then
    raise exception 'authentication_required' using errcode='42501';
  end if;
  if p_limit is null or p_limit<1 or p_limit>100 then
    raise exception 'gold_history_limit_invalid' using errcode='22023';
  end if;
  if (p_before_created_at is null) <> (p_before_id is null) then
    raise exception 'gold_history_cursor_invalid' using errcode='22023';
  end if;

  return query
  select
    l.id,l.delta,l.balance_after,l.source_kind,l.copy_key,
    l.reference_kind,l.reference_id,l.reverses_entry_id,l.created_at
  from public.bil_gold_ledger l
  where l.owner_id=v_owner
    and (
      p_before_created_at is null
      or (l.created_at,l.id)<(p_before_created_at,p_before_id)
    )
  order by l.created_at desc,l.id desc
  limit p_limit;
end
$$;

revoke all on function public.bil_gold_balance_v1()
  from public,anon,service_role;
grant execute on function public.bil_gold_balance_v1()
  to authenticated;

revoke all on function public.bil_gold_history_v1(timestamptz,bigint,integer)
  from public,anon,service_role;
grant execute on function public.bil_gold_history_v1(timestamptz,bigint,integer)
  to authenticated;

do $$
begin
  if to_regclass('public.bil_gold_accounts') is null
     or to_regclass('public.bil_gold_ledger') is null then
    raise exception 'bil_gold_v1_table_postcondition_failed';
  end if;
  if to_regprocedure('private.bil_post_gold_ledger_v1(uuid,bigint,text,text,text,text,text,bigint)') is null
     or to_regprocedure('public.bil_gold_balance_v1()') is null
     or to_regprocedure('public.bil_gold_history_v1(timestamptz,bigint,integer)') is null then
    raise exception 'bil_gold_v1_function_postcondition_failed';
  end if;
end
$$;
