-- Community XP / level v1 foundation.
-- XP is permanent reputation, never spendable currency. Negative XP is only
-- possible through an explicit reversal of a prior ledger entry.
set local lock_timeout='5s';
set local statement_timeout='30s';

do $$
begin
  if to_regclass('public.bil_community_reputation_accounts') is not null
     or to_regclass('public.bil_community_xp_ledger') is not null
     or to_regclass('public.bil_community_level_policy') is not null then
    raise exception 'community_reputation_v1_already_exists';
  end if;
end
$$;

create table public.bil_community_reputation_accounts (
  owner_id uuid primary key references auth.users(id) on delete cascade,
  xp bigint not null default 0 check (xp >= 0),
  updated_at timestamptz not null default pg_catalog.clock_timestamp()
);

create table public.bil_community_xp_ledger (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  delta bigint not null check (delta <> 0 and abs(delta) <= 1000000000),
  xp_after bigint not null check (xp_after >= 0),
  source_kind text not null
    check (source_kind ~ '^[a-z][a-z0-9_]{2,47}$'),
  idempotency_key text not null
    check (char_length(idempotency_key) between 16 and 160),
  request_digest text not null
    check (request_digest ~ '^[0-9a-f]{64}$'),
  copy_key text not null
    check (copy_key ~ '^[a-z][a-z0-9_]{2,63}$'),
  reference_kind text
    check (reference_kind is null or reference_kind ~ '^[a-z][a-z0-9_]{2,47}$'),
  reference_id text
    check (reference_id is null or char_length(reference_id) between 1 and 160),
  reverses_entry_id bigint
    references public.bil_community_xp_ledger(id) on delete set null,
  created_at timestamptz not null default pg_catalog.clock_timestamp(),
  constraint bil_community_xp_owner_idempotency_key
    unique(owner_id,idempotency_key),
  constraint bil_community_xp_reference_pair
    check ((reference_kind is null) = (reference_id is null)),
  constraint bil_community_xp_reversal_semantics
    check (
      (source_kind='reversal' and reverses_entry_id is not null)
      or (source_kind<>'reversal' and reverses_entry_id is null)
    ),
  constraint bil_community_xp_no_negative_awards
    check (source_kind='reversal' or delta>0)
);

create unique index bil_community_xp_single_reversal_idx
  on public.bil_community_xp_ledger(reverses_entry_id)
  where reverses_entry_id is not null;

create index bil_community_xp_owner_history_idx
  on public.bil_community_xp_ledger(owner_id,created_at desc,id desc);

create table public.bil_community_level_policy (
  level integer primary key check (level between 1 and 1000),
  min_xp bigint not null unique check (min_xp >= 0),
  title_copy_key text not null
    check (title_copy_key ~ '^[a-z][a-z0-9_]{2,63}$'),
  active boolean not null default true,
  updated_at timestamptz not null default pg_catalog.clock_timestamp()
);

insert into public.bil_community_level_policy(level,min_xp,title_copy_key,active)
values(1,0,'community_level_1',true);

alter table public.bil_community_reputation_accounts enable row level security;
alter table public.bil_community_xp_ledger enable row level security;
alter table public.bil_community_level_policy enable row level security;

revoke all on table public.bil_community_reputation_accounts
  from public,anon,authenticated,service_role;
revoke all on table public.bil_community_xp_ledger
  from public,anon,authenticated,service_role;
revoke all on table public.bil_community_level_policy
  from public,anon,authenticated,service_role;

create or replace function private.bil_post_community_xp_v1(
  p_owner uuid,
  p_delta bigint,
  p_source_kind text,
  p_idempotency_key text,
  p_copy_key text,
  p_reference_kind text default null,
  p_reference_id text default null,
  p_reverses_entry_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_digest text;
  v_existing public.bil_community_xp_ledger%rowtype;
  v_original public.bil_community_xp_ledger%rowtype;
  v_xp bigint;
  v_new_xp bigint;
  v_entry_id bigint;
begin
  if p_owner is null or not exists(
    select 1 from auth.users u where u.id=p_owner
  ) then
    raise exception 'community_xp_owner_invalid' using errcode='22023';
  end if;
  if p_delta is null or p_delta=0 or abs(p_delta)>1000000000 then
    raise exception 'community_xp_delta_invalid' using errcode='22023';
  end if;
  if p_source_kind is null
     or p_source_kind !~ '^[a-z][a-z0-9_]{2,47}$' then
    raise exception 'community_xp_source_kind_invalid' using errcode='22023';
  end if;
  if p_source_kind<>'reversal' and p_delta<0 then
    raise exception 'community_xp_negative_award_forbidden' using errcode='22023';
  end if;
  if p_idempotency_key is null
     or char_length(p_idempotency_key) not between 16 and 160 then
    raise exception 'community_xp_idempotency_key_invalid' using errcode='22023';
  end if;
  if p_copy_key is null
     or p_copy_key !~ '^[a-z][a-z0-9_]{2,63}$' then
    raise exception 'community_xp_copy_key_invalid' using errcode='22023';
  end if;
  if (p_reference_kind is null) <> (p_reference_id is null) then
    raise exception 'community_xp_reference_pair_invalid' using errcode='22023';
  end if;
  if p_reference_kind is not null
     and p_reference_kind !~ '^[a-z][a-z0-9_]{2,47}$' then
    raise exception 'community_xp_reference_kind_invalid' using errcode='22023';
  end if;
  if p_reference_id is not null
     and char_length(p_reference_id) not between 1 and 160 then
    raise exception 'community_xp_reference_id_invalid' using errcode='22023';
  end if;
  if (p_source_kind='reversal') <> (p_reverses_entry_id is not null) then
    raise exception 'community_xp_reversal_semantics_invalid' using errcode='22023';
  end if;

  v_digest := encode(
    extensions.digest(
      pg_catalog.jsonb_build_object(
        'owner',p_owner::text,
        'delta',p_delta,
        'source_kind',p_source_kind,
        'copy_key',p_copy_key,
        'reference_kind',p_reference_kind,
        'reference_id',p_reference_id,
        'reverses_entry_id',p_reverses_entry_id
      )::text,
      'sha256'
    ),
    'hex'
  );

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('bil_community_xp:'||p_owner::text,0)
  );

  select * into v_existing
  from public.bil_community_xp_ledger l
  where l.owner_id=p_owner
    and l.idempotency_key=p_idempotency_key;

  if found then
    if v_existing.request_digest<>v_digest then
      raise exception 'community_xp_idempotency_payload_mismatch'
        using errcode='22023';
    end if;
    return pg_catalog.jsonb_build_object(
      'entry_id',v_existing.id,
      'xp',v_existing.xp_after,
      'delta',v_existing.delta,
      'duplicate',true
    );
  end if;

  if p_reverses_entry_id is not null then
    select * into v_original
    from public.bil_community_xp_ledger l
    where l.id=p_reverses_entry_id
      and l.owner_id=p_owner
    for share;

    if not found then
      raise exception 'community_xp_reversal_target_invalid' using errcode='22023';
    end if;
    if p_delta<>-v_original.delta then
      raise exception 'community_xp_reversal_delta_invalid' using errcode='22023';
    end if;
    if exists(
      select 1
      from public.bil_community_xp_ledger l
      where l.reverses_entry_id=p_reverses_entry_id
    ) then
      raise exception 'community_xp_entry_already_reversed' using errcode='23505';
    end if;
  end if;

  insert into public.bil_community_reputation_accounts(owner_id,xp)
  values(p_owner,0)
  on conflict(owner_id) do nothing;

  select a.xp into v_xp
  from public.bil_community_reputation_accounts a
  where a.owner_id=p_owner
  for update;

  v_new_xp := v_xp+p_delta;
  if v_new_xp<0 then
    raise exception 'community_xp_below_zero' using errcode='22003';
  end if;

  insert into public.bil_community_xp_ledger(
    owner_id,delta,xp_after,source_kind,idempotency_key,
    request_digest,copy_key,reference_kind,reference_id,reverses_entry_id
  )
  values(
    p_owner,p_delta,v_new_xp,p_source_kind,p_idempotency_key,
    v_digest,p_copy_key,p_reference_kind,p_reference_id,p_reverses_entry_id
  )
  returning id into v_entry_id;

  update public.bil_community_reputation_accounts
  set xp=v_new_xp,
      updated_at=pg_catalog.clock_timestamp()
  where owner_id=p_owner;

  return pg_catalog.jsonb_build_object(
    'entry_id',v_entry_id,
    'xp',v_new_xp,
    'delta',p_delta,
    'duplicate',false
  );
end
$$;

revoke all on function private.bil_post_community_xp_v1(
  uuid,bigint,text,text,text,text,text,bigint
) from public,anon,authenticated,service_role;

create or replace function public.bil_community_my_reputation_v1()
returns jsonb
language plpgsql
stable
security definer
set search_path=''
as $$
declare
  v_owner uuid:=(select auth.uid());
  v_xp bigint;
  v_level integer;
  v_title_copy_key text;
  v_next_level integer;
  v_next_level_xp bigint;
begin
  if v_owner is null then
    raise exception 'authentication_required' using errcode='42501';
  end if;

  select coalesce(a.xp,0) into v_xp
  from (select 1) seed
  left join public.bil_community_reputation_accounts a
    on a.owner_id=v_owner;

  select p.level,p.title_copy_key
  into v_level,v_title_copy_key
  from public.bil_community_level_policy p
  where p.active and p.min_xp<=v_xp
  order by p.min_xp desc,p.level desc
  limit 1;

  if v_level is null then
    raise exception 'community_level_policy_invalid';
  end if;

  select p.level,p.min_xp
  into v_next_level,v_next_level_xp
  from public.bil_community_level_policy p
  where p.active and p.min_xp>v_xp
  order by p.min_xp,p.level
  limit 1;

  return pg_catalog.jsonb_build_object(
    'xp',v_xp,
    'level',v_level,
    'title_copy_key',v_title_copy_key,
    'next_level',v_next_level,
    'next_level_xp',v_next_level_xp
  );
end
$$;

revoke all on function public.bil_community_my_reputation_v1()
  from public,anon,service_role;
grant execute on function public.bil_community_my_reputation_v1()
  to authenticated;

do $$
begin
  if to_regclass('public.bil_community_reputation_accounts') is null
     or to_regclass('public.bil_community_xp_ledger') is null
     or to_regclass('public.bil_community_level_policy') is null then
    raise exception 'community_reputation_v1_table_postcondition_failed';
  end if;
  if to_regprocedure('private.bil_post_community_xp_v1(uuid,bigint,text,text,text,text,text,bigint)') is null
     or to_regprocedure('public.bil_community_my_reputation_v1()') is null then
    raise exception 'community_reputation_v1_function_postcondition_failed';
  end if;
end
$$;
